### ISSUE TITLE
Manuelle Installation 

### ISSUE THREAD

**Issue by 11wolli** [contao/core-bundle#1000]
Hallo Community, ich habe es nochmal versucht, in der Hoffnung das es diesmal flupt Contao 4.4.2 unter Win 10 und Php 7.0.13 zu Installieren.
Es geht einfach nicht, schade.
Fehler:
[2017-08-03 09:47:18] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_sc ope":"backend","_token_check":true,"_controller":" Contao\\InstallationBundle\\Controller\\Installati onController::installAction","_route":"contao_inst all"},"request_uri":"http://localhost/walter4/web/contao/install","method":"GET"} []
[2017-08-03 09:47:27] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFou ndException(code: 0): Attempted to load class "Config" from the global namespace.\nDid you forget a "use" statement? at C:\\xampp7\\htdocs\\walter4\\vendor\\contao\\core-bundle\\src\\Resources\\contao\\library\\Contao\\E nvironment.php:537)"} []

Wolli

**Comment by leofeyer** [comment]
Bitte wende Dich mit Fragen an das [Forum](https://community.contao.org/de/). Wenn sich in der Diskussion herausstellt, dass das Problem durch einen Fehler in Contao verursacht wird, kannst Du diesen gerne hier melden.

**Comment by mlwebworker** [comment]
Leo kannst Du das bitte wieder öffnen. Er ist aus dem Forum zu Github verwiesen worden https://community.contao.org/de/showthread.php?67088-Manuelle-Installation&p=447674&viewfull=1#post447674

**Comment by patrickjDE** [comment]
Eventuell gibt es Zusammenhänge mit diesem Issue: https://github.com/contao/standard-edition/issues/64#issuecomment-311940285

Wobei die (reproduzierbare) Ursache dort bei einer frischen Installation eigentlich nicht möglich sein sollte...

**Comment by leofeyer** [comment]
@mlwebworker Das Issue kann ich nur öffnen, wenn darin ein Fehler beschrieben wird, den wir beheben müssen. Bei mir tritt das Problem aber nicht auf.

**Comment by fritzmg** [comment]
@leofeyer the ticket seems to be a duplicate of https://github.com/contao/standard-edition/issues/64
However, https://github.com/contao/standard-edition/issues/64 probably needs to be moved to another repository, but it's still unclear where the cause of the issue lies.

> Bei mir tritt das Problem aber nicht auf.

Apparently it only occurs under Windows.

**Comment by 11wolli** [comment]
Windows Version 10
Apache 2.4.23
xampp Control Panel Version 3.2.2
phpMyAdmin 4.5.1
Php Version 7.0.13

**Comment by mlwebworker** [comment]
@leofeyer Wie können wir am besten herausfinden, ob es ein echtes Problem ist bzw. unter welchen Umständen dieses Problem auftritt. Ich hatte vor kurzem C4.4 auch noch XAMPP mit PHP 7.0.x laufen. Im Moment nutze ich PHP 7.1 Ich könnte das auch relativ problemlos switchen, aber bei mit tritt das Problem  nicht auf. Mir fehlt auch das nötige Wissen um ganz gezielt nach möglichen Fehleinstellungen zu fragen.
Ich habe bei mir auch gezielt über composer und manuell installiert. Mehr versehentlich als absichtlich dabei auch mal die standard-edition. Alles läuft.

**Comment by leofeyer** [comment]
Das Problem wurde mittlerweile behoben (siehe contao/installation-bundle@f04da58fe3607a890dd193cbaa8e188be3080f00). Es war tatsächlich ein Duplikat von contao/standard-edition#64, wie @fritzmg bereits vermutet hatte.
