### ISSUE TITLE
SCSS for backend

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/core-bundle#1005]
Hi,
is it possible to enable the support for scss files in back end via $GLOBALS['TL_CSS'][]?

Thx for feedback.

**Comment by leofeyer** [comment]
We could use the combiner to aggregate `$GLOBALS['TL_CSS'][]` in the back end, too. But can you explain what you want to accomplish?

**Comment by daniel-nemeth** [comment]
I just want to be able to add a .scss file to use sass with.

**Comment by leofeyer** [comment]
For your own extension?

**Comment by daniel-nemeth** [comment]
not only but in most cases

**Comment by leofeyer** [comment]
You do realize that compiling SCSS files has major performance drawbacks compared to providing pre-compiled CSS files, right? See #1010 and #987 for more information.

**Comment by daniel-nemeth** [comment]
Yes i do. But the performance in back end doesn't matter that much then in front end.
But since there is to less request for this feature I will use precompiled or normal CSS in further.

Thanks!
