### ISSUE TITLE
The BackendSessionListener should actually be a UserSessionListener

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1008]
...and also implement the logic for a FE member. Because if a page is currently already in the proxy cache, you won't get a fresh version if you log in as a front end member.

**Comment by leofeyer** [comment]
I'm struggling to reproduce this.

I have logged in in a separate browser window and reloaded the page (which is in the cache). I have been given the fresh page instead of the one from the cache.

**Comment by Toflar** [comment]
Does not sound logical to me. It should fail. Can you debug why it does not load from the cache? It should because nobody is telling it it shouldn't 😄

**Comment by leofeyer** [comment]
Fixed in 9f105519cfbdd7e73bfbc8f324132e8d7482491b.

**Comment by Toflar** [comment]
Thank you!

**Comment by leofeyer** [comment]
Welcome you are. 😄
