### ISSUE TITLE
Add a cache check for uncombined scss files

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1013]
The `getFileUrls` method in the `combiner` class do not check if a scss file is already compiled (an associated css file exists in the assets folder). The `getCombinedFileUrl` method does. Although the `TL_ASSETS_URL` is only used in the `getCombinedFileUrl` method.

I created a PR (#1012) which adds the same behaviour when returning the urls for uncombined and combined scss and js files.

**Comment by leofeyer** [comment]
Why did you open this issue? You have created #1012 already.

**Comment by agoat** [comment]
Sorry, I may have taken your wish too literally ;-)
