### ISSUE TITLE
Change table to add NOT NULL failed

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#1024]
I added the `NOT NULL` option to a field which previously allowed null values. The database update tool creates a broken SQL statement for that.

SQL definition in the dca
```sql
varchar(5) NOT NULL default ''
```
Created alter statement
```sql
ALTER TABLE tl_example CHANGE staff staff VARCHAR(5) DEFAULT '' NOT NULL
```
Steps to reproduce

1. Create a field with `varchar(5) default NULL`
2. Change field sql to `varchar(5) NOT NULL default ''`
3. Open the install tool and apply SQL changes

**Comment by leofeyer** [comment]
What is wrong with the created statement?

**Comment by dmolineus** [comment]
Sorry, misread the database exception. There was some issues with existing data.
