### ISSUE TITLE
Migration C 3.5.28 ->4.4.2: Neue Artikel werden nicht angezeigt.

### ISSUE THREAD

**Issue by mpunkt** [contao/core-bundle#1027]
Nach einer Migration werden keine neuen Artikel angezeigt. Ändert man bei einem Artikel z.B den Teaser wird dieser Artikel anschließend auch nicht mehr angezeigt.
`SELECT inColumn FROM tl_article` zeigt bei den betroffenen Artikeln "Hauptspalte" anstatt "main". Das Problem tritt bei mehreren Installationen auf. Auf demo.contao.org konnte ich es nicht reproduzieren.

**Comment by aschempp** [comment]
Hast du die Datenbankmigration via Install-Tool durchgeführt?

**Comment by mpunkt** [comment]
Ja, genauso wie im Video von Leo Feyer (Contao Nordtag) beschrieben. Bei der Migration gab es ein Problem ([https://github.com/contao/core-bundle/issues/1006]). Das fehlende Feld habe ich per `ALTER TABLE ...` hinzugefügt. Der Rest fuktionierte einwandfrei. Per Composer habe ich ein Update auf C 4.4.3 ausgeführt.

**Comment by mpunkt** [comment]
Ich habe nochmal eine Migration 3.5.28 > 4.4.3 ausgeführt:

- Download C 4.4.3 `curl -L https://download.contao.org/4.4.3 | tar xf --strip-components=1`
- `CREATE DATABASE dbname`
- Kopiere files/ templates/ und relevante system/modules/ aus C 3.5.28
- `chown -R www-data:www-data ...`
- `mysql dbname < sql-dump-aus-3.5.28`
- Starte https://meinedomain.tld/contao/install

Die beschriebene Vorgehensweise läuft fehlerfrei.  Wenn ich eine Artikeleinstellung ändere steht in tl_article.inColumn "Hauptspalte" und damit verschwindet er.

**Comment by leofeyer** [comment]
Lässt sich das Problem in der Onlinedemo reproduzieren?

**Comment by mpunkt** [comment]
Nein definitiv nicht. Ich kenne jetzt aber den Verursacher: **merger2 Version 3.0.8**
Das Bundle **contao-community-alliance/merger2 Version 3.0.11** lässt sich mit  composer leider nicht installieren. Deshalb bin ich noch in der Testphase, ob in 3.0.11 der Fehler auch auftritt. Das Ticket kann damit geschlossen werden.
Ich bin allerdings auf ein anderes Problem gestoßen, das sich in der Onlinedemo auch nicht reproduzieren lässt: Artikel, bei denen ein Teaser angezeigt werden soll, werden im Frontend nicht dargestellt. Bevor ich mir wieder eine 'blutige Nase' hole, werde ich das aber noch genauer untersuchen.

Danke an alle, die mitgedacht haben.
