### ISSUE TITLE
Contao-Demo not usable

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1029]
I tried to reproduce an error in the Contao-Demo.

Unfortunately, I am kicked out every second or third click.
I tried to generate the sitemap, but it would work (it only works from time to time).
I tried to clear everything in Maintenance mode, but I was logged out twice and only at the third try it worked.
Now, I got an Error 502:
![image](https://user-images.githubusercontent.com/2657385/29462613-41cefe62-8430-11e7-9239-862bc25e9240.png)

Furthermore, the time when the demo is reset is not shown anymore.

If anyone tries the demo like this, they would resile from using Contao.

**Comment by leofeyer** [comment]
I cannot reproduce this. I run all maintenance tasks in the demo twice without any problems.

**Comment by leofeyer** [comment]
BTW, please report issues with the online demo here: https://github.com/contao/website
