### ISSUE TITLE
Exclude pages from sitemap

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1030]
On our project, we have some hidden pages, which we do not want to be shown in the Sitemap on share/sitemap.xml

The setting of the pages are
* noindex,nofollow
* not in search index
* hidden in the menu
* show in sitemap: Standard
![image](https://user-images.githubusercontent.com/2657385/29462791-d1cba9fc-8430-11e7-830d-634766f07bc3.png)

In my experience, with these settings, the page should not be shown in share/sitemap.xml. But it is.

What am I doing wrong here? Is "show in sitemap: never" the only solution to exclude pages from Sitemap? If so, when was this change?

Thank you.

**Comment by netzarbeiter** [comment]
https://github.com/contao/core/issues/5365
