### ISSUE TITLE
Events & News, first level, add an image: Multiple editing does not work

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1031]
When I try to add an image on the first level in events or news and want to use the edit multiple function the checkboxes and folders appear only, but no images. This misbehaviour I could reproduce in the demo too. 

![contao 4 4 3 events file picker](https://user-images.githubusercontent.com/3715050/29469007-c7eb7d20-8446-11e7-946d-61483d89f9c0.gif)

**Comment by aschempp** [comment]
I think these two lines must be removed to fix the issue: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/drivers/DC_Folder.php#L3048-L3049

**Comment by leofeyer** [comment]
Indeed. Fixed in 54b428073886577aa3cc05c02bb07598da4222c6. Thank you @aschempp.
