### ISSUE TITLE
Frontend-Preview doesn't open specific page, always home page

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1034]
Contao 4.4: When clicking on frontend-preview, I always get to the start page. In former Contao-Versions, this was different.

You can reproduce this issue in the online demo: Click on Site Structure, edit a page (for example Content Elements -> Accordion, page 52). Then click on preview.

The URL is loaded with `https://demo.contao.org/contao/preview?ref=VVYoMso-?page=52`
But the start page is opened.

Thank you :)

**Comment by leofeyer** [comment]
See #1033.
