### ISSUE TITLE
Use image.html5 in ce_image.html5

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#1037]
Replace the whole content in `ce_image` content block with `<?php $this->insert('image', $this->arrData); ?>`

**Comment by leofeyer** [comment]
As discussed in Mumble on September 7th, it is ok to to add the `itemprop="associatedMedia"` tag in the `ce_image.html5` template.

**Comment by leofeyer** [comment]
Changed in b6483d40c8617f26a5c62be6890d8077d03c7c51.
