### ISSUE TITLE
jquery colorbox

### ISSUE THREAD

**Issue by jewo5** [contao/core-bundle#1038]
Wenn ich eine Bildergalerie erzeuge und sie mit jquery colorbox anzeigen lasse (mit Lightbox), dann stimmen im Frontend bei geöffneter Lightbox die Next, Previous und Close Buttons beim **hovern** nicht - es werden falsch aussehende Buttons  angezeigt (Contao 4.4.3)

**Comment by Aybee** [comment]
Also see here https://github.com/contao/core/issues/8747
