### ISSUE TITLE
Duplicate ids when editing multiple folders in file manager

### ISSUE THREAD

**Issue by michb** [contao/core-bundle#1041]
There is a small problem when editing multiple folders in file manager. If you want to edit the field `Public [protected]` for multiple entries at once all checkboxes have the id `opt_protected_0`.
Therefore all labels have the same `for` attribute. They look like this
```html 
<label for="opt_protected_0">Public</label>
```
This leads to the problem - when clicking on any label - only the first checkbox will change.

**Steps to reproduce**
+ goto file manager
+ select multiple folders
+ click edit
+ choose `Public [protected]`
+ click on any label

Checkboxes are working fine and selection will be stored properly. But clicking on the labels causing the problems and this is also no valid html markup.

**Comment by leofeyer** [comment]
Fixed in 9d78b59faa2e4675731aa400375fbe84aa189a69.
