### ISSUE TITLE
IE 11 display Problem with responsive.css

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1043]
Just a tiny bug:

In the responsive.min.css there is the definition
`img{max-width:100%;height:auto}`
In IE11, this definition is buggy and the images are cropped.
Better would be:
`img{max-width:100%;width:100%;height:auto}`

**Comment by Xendiadyon** [comment]
Hm. Forget it. Then every symbol would be resized to 100% per default.
Better you leave it as it is.

**Comment by Aybee** [comment]
On which page in the online demo backend can I see this behaviour? I like to see this IE11 behaviour.
