### ISSUE TITLE
Optimize the be_tinyMCE.html5 template

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1044]
I refer to this ticket https://github.com/contao/core/pull/8154 which is set to milestone 4.2.0, open and declared as feature.

I've modified my tinyCustom.php which I use for years in my own and customer backends so it fits to Contao 4.4.3.
```php
<?php

namespace Contao;

if ($GLOBALS['TL_CONFIG']['useRTE']):

?>
<script>window.tinymce || document.write('<script src="<?= TL_ASSETS_URL ?>assets/tinymce4/js/tinymce.gzip.js">\x3C/script>')</script>
<script>
setTimeout(function() {
  window.tinymce && tinymce.init({
    skin: 'contao',
    selector: '#<?= $this->selector ?>',
    language: '<?= Backend::getTinyMceLanguage() ?>',
    element_format: 'html',
    document_base_url: '<?= Environment::get('base') ?>',
    entities: '160,nbsp,60,lt,62,gt,173,shy',
    branding: false,
    setup: function(editor) {
      editor.getElement().removeAttribute('required');
    },
    init_instance_callback: function(editor) {
      if (document.activeElement && document.activeElement.id && document.activeElement.id == editor.id) {
        editor.editorManager.get(editor.id).focus();
      }
      editor.on('focus', function() { Backend.getScrollOffset(); });
    },
    file_browser_callback: function(field_name, url, type, win) {
      Backend.openModalBrowser(field_name, url, type, win);
    },
    file_browser_callback_types: <?= json_encode($this->fileBrowserTypes) ?>,
    plugins: 'autosave charmap code fullscreen image importcss link lists paste searchreplace tabfocus visualblocks',
    browser_spellcheck: true,
    tabfocus_elements: ':prev,:next',
    importcss_append: true,
    // optional CSS file to import style class formats from (should be configurable somewhere, here for testing in files/css/tinymce.css)
    <?php
      $cssPath = Config::get('uploadPath') . '/css/tinymce.css';
      if(file_exists($cssPath)):
    ?>
    content_css: '<?= $cssPath . '?' . time() ?>',
    <?php endif; ?>
    extended_valid_elements: 'q[cite|class|title],article,section,hgroup,figure,figcaption',
    menubar: 'file edit insert view',
    toolbar: 'formatselect | styleselect | removeformat | bold italic | link unlink | bullist numlist outdent indent | undo redo | code',

    paste_as_text: true, // activate 'paste as text' in menu bar
    // only use SPAN when necessary
    importcss_selector_converter: function(selector) {
      if(selector.charAt(0) == '.') {
        return {title: selector.substr(1), inline: 'span', selector: '*', classes: selector.substr(1)};
      }
    },
    keep_styles: false, // don't copy formats on enter to new block - default = true
    // building the style formats
    style_formats: [
      {title: 'Inline', items: [
        {title: 'Underline', icon: 'underline', format: 'underline'},
        {title: 'Strikethrough', icon: 'strikethrough', format: 'strikethrough'},
        {title: 'Superscript', icon: 'superscript', format: 'superscript'},
        {title: 'Subscript', icon: 'subscript', format: 'subscript'},
        {title: 'Code', icon: 'code', format: 'code'}
      ]},
      {title: 'Alignment', items: [
        {title: 'Left', icon: 'alignleft', format: 'alignleft'},
        {title: 'Center', icon: 'aligncenter', format: 'aligncenter'},
        {title: 'Right', icon: 'alignright', format: 'alignright'},
        {title: 'Justify', icon: 'alignjustify', format: 'alignjustify'}
      ]}
    ],
    // building the block formats
    block_formats:
      'H1=h1;' +
      'H2=h2;' +
      'H3=h3;' +
      'H4=h4;' +
      'H5=h5;' +
      'H6=h6;' +
      'Paragraph=p;' +
      'Blockquote=blockquote;' +
      'DIV=div;' +
      'ADDRESS=address;' +
      'PRE=pre;'
  });
}, 0);
</script>
<?php endif; ?>
```
Please give it a try. Also see the comments inside. Tell me if you need a DIFF file.

**Comment by leofeyer** [comment]
I have assigned contao/core#8154 to the next feature release milestone.

Regarding your code suggestions:

* `content_css`: Not everybody needs this (e.g. I never use it), therefore we have not enabled it by default
* `toolbar`: Why did you remove `format` and `table`? You realize that the `format` toolbar has way more options than the `formatselect` dropdown, do you?
* `paste_as_text`: I often paste HTML – probably more often than plain text – so I don't want this option to be enabled by default
* `keep_styles`: This one might actually make sense, although a lot of people might disagree.

IMO it is impossible to configure TinyMCE in a way that it suits everyone, therefore we only provide a basic configuration and store it in an editable template which everyone can adjust to their needs.

**Comment by Aybee** [comment]
**content_css**
But this is the easiest way to offer formats to editors. Also you have a direct control of attached classes by just putting the cursor into the formated text. The chosen class then is marked and you also can apply multiple classes. Also you can chose a class open the code mode and change it to yours. I think many of us want the feature to set up classes to elements.

**toolbar**
All from toolbar **format** is there. See screenshot to compare places.

IMHO we don't need **table** here. There's a CE type table for tables and editors often do bad things with those RTE tables.
![screengrab-20170902-183446](https://user-images.githubusercontent.com/1143013/29997513-63ad572c-9015-11e7-9f91-a99b42404527.png)

**paste_as_text**
Das war dafür gedacht, dass nicht der ganze Müll mitkommt, wenn man einen Text aus einer HTML-Seite markiert und kopiert. Da war immer sehr viel Mist bei den Kunden, den man bereinigen musste. Hatte gehofft, dass dies auch für Word, PDF usw. funktioniert. Aber in meinem Firefox auf Windows funktioniert das noch nichtmal mit HTML. Ich habe meinen Kunden sowieso gesagt, sie mögen bitte in die Code-Editor-Ansicht einfügen und nicht in die WYSIWYG-Oberfläche. Brauch ich also nicht, war nur gut gemeint.

**keep_styles**
Yes, I come to this when I want to optimize the styleselect behaviour. And I somehow remember that this 
was necessary to achive the optimization (multiple classes, class marking in dropdown, SPAN only when necessary).

Yes, as you can see there is no specific new option, it's just optimized to reach the most wanted parts without going through levels in dropdown menus. Also e.g. when the cursor is in a word and you click on format H2 you get this H* immediately. And later on when you set the cursor into this H2 the dropdown directy shows you "H2", you didn't have to check within tootbar dropdown or this tiny statusbar.

So this template is thought as the basic core template.

**Comment by Aybee** [comment]
> @leofeyer 
...the format toolbar has way more options than the formatselect dropdown...

Did you test it or just read the code? Also it would be nice if other developers test this template and tell me what they think about it.

**Comment by fritzmg** [comment]
`paste_as_text` should work fine in all browsers. And I agree that it should be enabled by default. So far I have included a custom `be_tinyMCE.html5` template in all Contao 4 projects where I set this to true. Having to enabled this manually each time is a pain, because you also have to click away an annoying pop up.

**Comment by Aybee** [comment]
You're right. I did another test and it worked (copied from contao demo latest news in footer)
**paste_as_text = true**
```html
<p>2014-05-23 14:10<br>New Contao Versions in short intervalls</p>
```
**paste_as_text = false** (default, not set)
```html
<div class="layout_simple arc_1 block first even">
  <time datetime="2014-05-23T14:10:00+02:00">2014-05-23 14:10</time>
  <a title="Read the article: New Contao Versions in short intervalls" href="https://demo.contao.org/en/news-detail/new-contao-versions-in-short-intervalls.html">
  New Contao Versions in short intervalls
  </a>
</div>
```
Paste the complete HTML could be fine sometime when you're an admin and know what you do. But normal editors never control the HTML from where they copy and the result what they are pasting.
