### ISSUE TITLE
jQuery ui path in Contao 4.4.3

### ISSUE THREAD

**Issue by sietsevandreven** [contao/core-bundle#1045]
The assets/jquery/ui/ path is not correct. The path in contao 4.4.3 is assets/jquery-ui/. So, jquery based functions are not working because of the missing jquery file...

I attached the j_accordion in theme -> lay-out.  On the front end an error occured: `GET http://localhost/assets/jquery-ui//jquery-ui.min.js 404 (Not Found)`.

**Comment by Aybee** [comment]
There is no path /jquery/ui/ within the core. j_accordion.html5 is correct.
https://github.com/contao/core-bundle/blob/dc1acb458f53f3e4899d3874f05c3e25889b9819/src/Resources/contao/templates/jquery/j_accordion.html5#L2
Didn't I told you this in the forum?
