### ISSUE TITLE
4.4.3: SVG-Grafiken werden nicht größer dargestellt als Standard

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#1048]
Habe ich ein SVG z.B. mit der Standardgröße 59x59 so wird dieses SVG in Galerien als auch in Inhaltselementen nicht größer dargestellt als diese 59x59, auch wenn man 200 angegeben hat. In der Demo läßt sich das nicht nachstellen, weil es keine SVG-Dateien gibt und ein Upload nicht möglich ist.

Dasselbe Verhalten kann man bei Grafiken vom Typ JPEG, PNG usw. beobachten. In C3 konnte man diese Grafiken noch größer darstellen. In C4 wird die Größe auf die Standardgröße der Grafik begrenzt. D.h. eine Grafik mit 300 px Breite, bekommt man auch nie größer als 300 px. Das scheint in C4 wohl so gewollt. Aber sicher nicht bei Vektorgrafiken. Die sind wohl versehentlich in das Feature mit reingerutscht.

**Comment by ausi** [comment]
Ja, das Verhalten ist so gewollt. Siehe #667.

**Comment by Samson1964** [comment]
Ja, aber doch nicht bei SVG?! Das Format wurde doch sicher glatt übersehen.

**Comment by ausi** [comment]
Das hängt von der SVG-Datei ab. Eine SVG-Datei mit fixer Größe wird exakt gleich wie eine Pixel-Grafik behandelt, also nicht hochskaliert. Eine SVG-Datei die eine Proportion (`viewBox`) vorgibt aber keine fixe Größe hat wird hochskaliert. SVG-Dateien die überhaupt keine Größen- oder Proportions-Angaben enthalten werden nicht verändert.

Die drei verschiedenen Typen von SVG-Dateien sind im Ticket contao/core#7882 beschrieben.

**Comment by Samson1964** [comment]
Konkret geht es um [diese SVG-Datei](https://de.wikipedia.org/wiki/Datei:ChessBase-Logo.svg). Die wurde leider nur mit 59x59 in Inkscape erstellt, läßt sich aber beliebig verlustfrei skalieren. Nur eben nicht mit Contao 4, was mir das Hochskalieren verweigert.
Bleibt mir also im Moment nur das Patchen von C4 oder das Ändern der SVG-Datei.

**Comment by ausi** [comment]
In dieser SVG-Datei sollte `width="59.200001" height="59.470001"` mit `viewBox="0 0 59.200001 59.470001"` ersetzt werden wenn man möchte dass die Grafik hochskaliert werden kann.

**Comment by Samson1964** [comment]
Okay danke! Das ist einfacher als C4 patchen. Da muß ich vorher drauf achten, um alle SVG-Dateien die ich benutzen will entsprechend zu modifizieren.

**Comment by fritzmg** [comment]
@frontendschlampe dann kannst du die Bildgröße aber nicht über Contao steuern.
