### ISSUE TITLE
add CSS-ID/class to option wizard

### ISSUE THREAD

**Issue by mpitz** [contao/core-bundle#1049]
CSS-ID/class fields for each option in this interface would be fine to mark up specific options:

![image](https://user-images.githubusercontent.com/6831223/29923503-0ca39548-8e5a-11e7-8b4d-97d9e366fa18.png)

**Comment by Toflar** [comment]
Why don't you just use attribute selectors on the value?

**Comment by mpitz** [comment]
If you want to send the value via EMail it can be very complex like "Seleced option for a hard copy". With CSS selectors this is very inconvenient.

**Comment by asaage** [comment]
Styling options of a select input is difficult anyway - in case of mobile-devices it's impossible...
If attribute selectors are not convenient enough and the order of your options is more or less fixed you can still use ```nth-child()``` selectors.

**Comment by mpitz** [comment]
> If attribute selectors are not convenient enough and the order of your options is more or less fixed you can still use nth-child() selectors.

Yes the use of the `nth-child()` selectors is possible. It is supportet for many browsers but < IE 11 (http://caniuse.com/#feat=css-sel3)

Anayway: what if the order is not fixed?

**Comment by Toflar** [comment]
Well you can also ask the same about classes: What if the CSS classes are not fixed?

I don't see any value adding this here, really. Especially because the value attribute should be short an concise and not contain "Hello this is the green value" but rather just "green". Might as well use attribute selectors then.

**Comment by mpitz** [comment]
> Especially because the value attribute should be short an concise and not contain "Hello this is the green value" but rather just "green". Might as well use attribute selectors then.

Yes you are right.

But if you want to send the value of the option via EMail in a context a "nice" described value could be more useable than having a "nice" name for the selector.

But maybe I'm the only one with such a problem ;-)

**Comment by agoat** [comment]
> But if you want to send the value of the option via EMail in a context a "nice" described value could be more useable than having a "nice" name for the selector.

If you want to format the values before sending them by email you should use the [prepareFormData](https://docs.contao.org/books/manual/3.4/de/07-contao-anpassen/contao-hooks.html#prepareformdata) Hook.

**Comment by leofeyer** [comment]
>  But maybe I'm the only one with such a problem ;-)

It seems so. 😄 At least nobody seconded your request within the last 6 month, therefore I'm closing the ticket.
