### ISSUE TITLE
Interner CSS-Editor

### ISSUE THREAD

**Issue by jewo5** [contao/core-bundle#1052]
#893 
Das Ein- und Ausblenden funktioniert m.E. in 4.4.3  immer noch nicht richtig - wenn ich den Style das erste Mal ausblende, passiert nichts, blende ich ihn danach wieder ein, wird er ausgeblendet und ab diesem Mal ausblenden funktioniert es von da an "falsch herum" - also bei Ausblenden des Styles wird er eingeblendet und umgekehrt.

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by jewo5** [comment]
Habe es gerade in der Online-Demo mit einem Background für body versucht. Mein Background funktioniert, aber das Ein- oder Ausblenden hat überhaupt keine Auswirkungen in der Demo...
Ich könnte einen Zugang zu einer Contao 4 - Testinstallation zur Verfügung stellen. Hier kann es ausprobiert werden.

**Comment by asaage** [comment]
Soweit ich das eruieren konnte ist es ein Problem mit dem Servercache bzw. dem ```expires Header```.
Weil die internen Stylesheets nichtmehr kombiniert werden werden die mit ihrem Originalnamen ausgeliefert.
Hängt man urlParameter an die Stylesheetresource bekommt man auch was aktuelles. Browsercache leeren, incognitoFenster, oder Wartung (script-cache leeren) bewirkt allerdings nichts.
Reproduzieren: In der Onlinedemo:

- Stylesheet anlegen (z.B. test.css ```h1{color:red;}```
- dieses dem Layout hinzufügen
- FE aufrufen
- ```h1``` Eintrag im Stylesheet (de)aktivieren
- FE aktualisieren und vergleichen

**Comment by jewo5** [comment]
Habe ich jetzt nicht wirklich verstanden - wo muss welcher url-Parameter angehängt werden und wozu ist das gut?

**Comment by asaage** [comment]
im Falle der OnlineDemo
https://demo.contao.org/assets/css/test.css
≠
https://demo.contao.org/assets/css/test.css?foo=bar

**Comment by m-werk** [comment]
Ich hab bei mir die Version 4.4.6 und hier hat das ausblenden der css-datei auch keine auswirkung. Erst wenn ich "Daten Bereinigen" klicke (Skriptcache leeren) wird auch das css ausgeblendet bzw. eingeblendet.

**Comment by ausi** [comment]
In der Live-Demo wird die CSS-Datei von CloudFlare gecacht weil sich der Dateiname nicht ändert. Außerdem wird bei dem Ajax-Toggle die CSS-Datei nicht neu genertiert. Hier fehlt ein Aufruf von `updateStyleSheet()`: https://github.com/contao/core-bundle/blob/4dcff8339d4c61665bf82e0b1cdae6a520e1df47/src/Resources/contao/dca/tl_style.php#L757

**Comment by leofeyer** [comment]
Fixed in cb8dcbe634b28b8a0fd8376af0b79cb093b101e9. The same issue occurred in the calendar and news bundle with the RSS feeds not being updated.
