### ISSUE TITLE
Contao 4.4.4 Design-Anpassung für begrenzte Breite im Backend

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#1053]
Die Design-Anpassung im Contao 4.4.4 würde ich gerne mal hier diskutieren:

Durch das Update auf 4.4.4 werden die Maus-Kilometer erhöht.

Das Backend sieht so aus:
![backend1](https://user-images.githubusercontent.com/1942550/30117116-9fc10be8-931f-11e7-9452-9b4220b3d476.png)

Mit wenigen CSS-Anpassungen könnte es so aussehen:
![backend2](https://user-images.githubusercontent.com/1942550/30117134-a9848510-931f-11e7-84f4-a8927cf5b3c8.png)

Das Problem mit dem nicht immer sichtbaren Speichern-Button, könnte mit einem Sticky-Footer (https://packagist.org/packages/jrgregory/m17-sticky-backend-footer) gelöst werden:
![backend-mit-sticky-footer](https://user-images.githubusercontent.com/1942550/30117148-b2d69ea0-931f-11e7-86a5-ac1910899e73.png)

Was meint ihr?

**Comment by fritzmg** [comment]
Generell habe ich bei all meinen Contao 4 Installationen die Option __Breite begrenzen__ beim _Backend-Theme_ aktiviert - da die Strecken, die man mit dem Cursor zurücklegen muss, auf einem großen Monitor ansonsten viel zu lang wären.

Ich finde auch, dass es nicht optimal ist, das Hauptmenü ganz links zu haben, da man dadurch wieder unnötige Strecken zurücklegen muss.

**Comment by leofeyer** [comment]
Ich verstehe, dass die Klickwege auf einem großen Monitor sehr lang sind. So ist das aber z.B. in ActiveCollab 5 oder in Grav auch, denn eine sehr viel bessere Lösung gibt es kaum, wenn die linke Spalte immer links sein soll.

Ich selbst habe ja auch einen größeren Monitor, aber mein Browserfenster geht nie über die ganze Breite. Sieht das nicht bei 80% der Webseiten dürftig aus?

Zu Deinem Vorschlag bezüglich `margin: 0 auto`: Mir gefällt diese Lösung nicht. Die linke Spalte soll eigentlich links bleiben, daher wäre es IMO eher eine Option, die Content-Spalte auch links zu haben anstatt zu zentrieren. Ich schließe mich aber gerne der Mehrheit an in dieser Frage.

@contao/developers @frontendschlampe @sascha-mueller @stefan-at-work @JanoschSkuplik @Ainschy

**Comment by aschempp** [comment]
Contao war seit Jahren immer mittelzentriert, das hat sich gut bewährt. Ich finde Bjarke's zweites Bild massiv besser als am linken Rand.

Die Diskussion um "ich benutze nie die volle Grösse" müssen wir nicht führen, jeder arbeitet anders und für diesen Fall gibt es ja die Option *nicht zu begrenzen*.

**Comment by netzarbeiter** [comment]
Content-Spalte links würde so aussehen:
![backend-3](https://user-images.githubusercontent.com/1942550/30118192-b1131bc2-9322-11e7-9676-55ab504c2e9a.png)

**Comment by fritzmg** [comment]
Alles links ausrichten macht, finde ich, keinen Sinn. Zumal dann die Buttons rechts oben total losgelöst vom Rest wären.

**Comment by stefan-at-work** [comment]
ich würde das auch zentrieren. Allerdings würde ich dann statt einer 1140er Breite (240+900) auf 1280 (240+1040) gehen. Das sieht dann etwas gefälliger aus oder spricht etwas dagegen auf eine 1280er Breite zu gehen?

**Comment by stefan-at-work** [comment]
Nachtrag zu besseren Verständnis: ich meine beim begrentzten Backend-Theme den Mainbereich auf 1040px zu erhöhen.

**Comment by stefan-at-work** [comment]
oder die Luxusvariante:
![breite](https://user-images.githubusercontent.com/5325314/30122399-9a0696fa-932e-11e7-89f0-a31ab91fb86b.jpg)

**Comment by leofeyer** [comment]
Das Problem daran ist, dass wir uns in Richtung Full-Screen-App bewegen wollen (vgl. Sascha's Entwürfe). Da ist die Zentrierung absolut kontraproduktiv.

**Comment by stefan-at-work** [comment]
Dann würde ich das analog AC5 machen. Linke Spalte links und Contenbereich max. width 1500px. zentriert. Das sieht IMHO sehr geschmeidig aus.
Evt. dann noch unter Benutzereinstellungen Geburtsdatum + Fotoauswahl nebeneinander

**Comment by netzarbeiter** [comment]
Weil AC5 genannt wurde, bei der 5 handelt es sich um ein komplett neues Design. Die Wege sind vom Konstrukt her kürzer, dass bekommen wir so in einem Bugfix-Release nicht hin.

Bis zur Full-Screen-App ist noch ein langer Weg und bis dahin ist die Zentrierung doch kein Problem.

**Comment by frontendschlampe** [comment]
> Generell habe ich bei all meinen Contao 4 Installationen die Option Breite begrenzen beim Backend-Theme aktiviert - da die Strecken, die man mit dem Cursor zurücklegen muss, auf einem großen Monitor ansonsten viel zu lang wären.

Darüber hatte ich auch schon mit Leo gesprochen, aber wie @aschempp schon sagt, ist das halt kein Diskussionsthema, da jeder anders arbeitet. Dafür gibt es ja Breite begrenzen.

> Ich finde auch, dass es nicht optimal ist, das Hauptmenü ganz links zu haben, da man dadurch wieder unnötige Strecken zurücklegen muss.

Ja es sind ganz schöne Wege, aber hier muss ich @stefan-at-work zustimmen: als ich das erste mal AC5 gesehen haben, war das auf den ersten Blick sehr eigenartig mit der Navispalte ganz links und zentriertem Inhalt, aber jetzt, nachdem ich fast 3 Tage ständig im Active Collab 5 gearbeitet habe, muss ich sagen, dass die Benutzung gar nicht so schlecht ist. Es sieht schlimmer aus, als man es benutzen kann. Vor allem wird man nicht so abgelenkt, dadurch dass der Hauptbereich eine größere Abtrennung zur Navi hat.

Großer Screen (2560 px Breite)
<img width="2560" alt="screenshot 2017-09-06 18 58 43" src="https://user-images.githubusercontent.com/1232819/30124481-942f77e0-9335-11e7-9155-55b4e018b7d5.png">

Kleiner Screen (1800 px Breite)
<img width="1777" alt="screenshot 2017-09-06 18 59 20" src="https://user-images.githubusercontent.com/1232819/30124483-983045fe-9335-11e7-81ce-6f60465cb225.png">

Grundsätzlich gibt es meiner Meinung nach auch keine Möglichkeit, das Menü irgendwo anders hin zu verschieben als auf die linke Seite. Für oben ist es zu umfangreich und unten oder rechts ist halt absolut ungewohnt.

Aktuell haben wir halt eine Übergangszeit, so lange wir noch nicht weitere Infos/Möglichkeiten für die rechte Seite und einer Fullscreen-Anwendung haben.

**Comment by fritzmg** [comment]
@stefan-at-work das wäre ja kein Unterschied zur aktuellen Situation?

**Comment by fritzmg** [comment]
@frontendschlampe die Abgrenzung hast du ja allerdings auch nur bei großen Screens. Das bietet also keinen generellen Vorteil.

**Comment by frontendschlampe** [comment]
> @frontendschlampe die Abgrenzung hast du ja allerdings auch nur bei großen Screens. Das bietet also keinen generellen Vorteil.

Wie meinst du das?

Wie gesagt, ich habe die letzten Tage sehr viel im AC5 gearbeitet und kam im Fullscreen super mit der Bearbeitung zurecht!

**Comment by stefan-at-work** [comment]
@fritzmg - Unterschied insofern, als das ich ohne Seitenbegrenzung das Layout von AC5 übernehmen würde. Dann habe ich bei großen Screens den Contenbereich auf max. 1500 reduziert statt wie momentan 100%.

Bei einer optionalen Begrenzung würde ich dann zentrieren mit einer Gesamtbreite von z.B. 1280px. Das wäre in meinen Augen ein guter Kompromiss.

**Comment by leofeyer** [comment]
> Weil AC5 genannt wurde, bei der 5 handelt es sich um ein komplett neues Design. Die Wege sind vom Konstrukt her kürzer, dass bekommen wir so in einem Bugfix-Release nicht hin.

Dieses Argument verstehe ich entweder nicht oder es ist falsch.

![](https://user-images.githubusercontent.com/1192057/30130427-621bdd2a-9349-11e7-96ef-826ee655bc3f.png)

![](https://user-images.githubusercontent.com/1192057/30130436-68ce03fa-9349-11e7-8ee5-1dc9f98ab241.png)

Die Wege sind in Contao 4 sogar **kürzer** als in AC5, wenn die Breite begrenzt wird.

**Comment by frontendschlampe** [comment]
> Die Wege sind in Contao 4 aktuell sogar kürzer als in AC5, wenn die Breite begrenzt wird.

Wenn man davon ausgeht, dass man öfter an der rechten Hälfte zu tun hat, dann ja. Wenn man aber mehr in der linken Hälfte des Hauptbereichs was machen muss, dann sind die Wege mit zunehmender Anzahl weiter.

**Comment by netzarbeiter** [comment]
Im AC5 sind alle wichtigen Bedienfelder links von der Mitte. In Contao sind sie leider rechts von der Mitte (Bearbeiten, Duplizieren, etc.).

**Comment by fritzmg** [comment]
> @fritzmg - Unterschied insofern, als das ich ohne Seitenbegrenzung das Layout von AC5 übernehmen würde. Dann habe ich bei großen Screens den Contenbereich auf max. 1500px reduziert statt wie momentan 100%.

Achso, ich dachte du meintest mit Begrenzung. Das Ticket hier von @netzarbeiter handelt ja hauptsächlich um die neue Ansicht in Conto 4.4.4 bei _aktiver_ Begrenzung.

> Wie meinst du das?

@frontendschlampe dein Punkt war ja, dass du es schön findest, wenn du eine größere Abgrenzung zwischen "Content" und Hauptnavigation hast, so wie in Active Collab 5. Aber diese Abgrenzung hast du ja nur, wenn die Auflösung einen gewissen Punkt übersteigt, ist also kein genereller Vorteil, sondern ergibt sich erst ab einer gewissen Auflösung.

Ich sehe momentan keinen Vorteil darin die Hauptnavigation am ganz linken Rand zu haben, während der "Content" Bereich begrenzt ist, bei aktivierter Begrenzung.

**Comment by leofeyer** [comment]
> Im AC5 sind alle wichtigen Bedienfelder links von der Mitte.

Das stimmt einfach nicht. Schau Dir bitte folgende Ansichten an:

* Systemeinstellungen
* Add-ons
* Papierkorb
* Personen
* Projekte -> Bearbeiten

In allen Ansichten befinden sich die Links bzw. Buttons ganz rechts.

**Comment by netzarbeiter** [comment]
Unsere AC5 Diskussion steht einer Lösungsfindung im Weg.

**Comment by leofeyer** [comment]
Ich kann Deine falschen Aussagen aber auch nicht einfach so stehen lassen.

**Comment by netzarbeiter** [comment]
Bei den Systemeinstellungen und Add-ons hast du recht, die habe ich jedoch in einem Jahr mit AC5 einmal gebraucht. Beim Projekt -> Bearbeiten hat man schon die hälfte des Weges hinter sich.

Bilder sagen mehr als tausend Worte.
![projekt](https://user-images.githubusercontent.com/1942550/30153724-ca86bd62-93b7-11e7-93d9-c0a810d8702e.png)
![projekt](https://user-images.githubusercontent.com/1942550/30153737-d471f71a-93b7-11e7-82e0-7e9819772c16.gif)
![personen](https://user-images.githubusercontent.com/1942550/30153750-e2c07a08-93b7-11e7-8930-ed39214b56a4.png)
![rechnungen](https://user-images.githubusercontent.com/1942550/30153763-f0ef944c-93b7-11e7-8633-0b1c960ef796.png)
![berichte](https://user-images.githubusercontent.com/1942550/30153767-f7faf1aa-93b7-11e7-9e03-6bf2eb8aefda.png)
![papierkorb](https://user-images.githubusercontent.com/1942550/30153773-fb53ecbc-93b7-11e7-914a-f9fd9fa22df5.png)

So jetzt steht einer Lösungsfindung nichts mehr im Weg.

**Comment by agoat** [comment]
Das Layout in 4.4.3 war besser. 

Ich verstehe auch nicht ganz die Diskussion bezüglich der Breiten-Begrenzung. Prinzipiell ist es schön das es diese Möglichkeit gibt, aber wenn ich an einem großen Bildschirm arbeite (Ich sitze hier vor einem 4k-Monitor), gibt es ja immer noch die Möglichkeit das Browserfenster kleiner zu machen. 
Ich komme ja auch nicht auf die die contao.org-Seite im Vollbild auf meinem 4k-Monitor zu öffnen (sieht grässlich aus). 

Mir wäre viel lieber wenn die Schaltflächen etwas größer sind - 16x16 Buttons sind aufgrund der hohen Pixeldichte nicht mehr zeitgemäß. Aber auch hier helfe ich mir mit der Zoom-Funktion.

**Comment by frontendschlampe** [comment]
Also wenn ich mir diese Diskussion und auch die Diskussionen der letzten Wochen/Monate so im Kopf durchgehe und dann noch den Kommentar von @agoat einrechne, dann ergibt sich meiner Meinung auch ein "klares" Bild:

Aktuell machen wir kleine Schritte auf Basis des alten Layouts. Gerade in Hinblick auf Icons und die allgemeine Darstellung der Optionen sind das immer Anpssungen, die auf Basis von veralteten Anforderungen (nur eine große Screengröße) gemacht werden. Wenn wir das Layout von Grund auf neu denken würden und z.B. die Klickflächen bei Buttons und Icons vergrößern würden, dann würden wir hier wahrscheinlich nicht darüber diskutieren, wie weit der Weg zum linken Menü ist. Wenn man nämlich auf großen Screens die Schriften, Abstände, Breiten, Klickflächen usw. erhöht, sind die Mauswege nur noch relativ. Wenn sich das dann auch dynamisch bei kleineren Bildschirmen anpasst, dann ist es auch dort kein Problem. Wenn z.B. auf größeren Screens die linke Navi-Spalte breiter ist und auch der mittlere Bereich nicht mehr nur 900 px breit ist, sondern vielleicht 1200 px, dann ist das auch wieder besser. Die Möglichkeit, das Fenster kleiner zu schieben besteht ja immer. Ob es dann noch einen Punkt geben muss, um die Breite zu begrenzen, ist dann fraglich. Macht ja auch kein anderer. Da ist das Beispiel von @agoat schon richtig.

Aktuell binden wir imho zu viel Zeit in das Layout, die wir eigentlich für wichtigere Dinge aufwenden könnten.

**Comment by fritzmg** [comment]
Jeder arbeitet anders. Ich finde es mühsam meinen Browser nur wegen dem Contao nicht auf Fullscreen laufen lassen zu müssen.

**Comment by leofeyer** [comment]
> Beim Projekt -> Bearbeiten hat man schon die hälfte des Weges hinter sich.

Ja, da hast Du Recht.

> Ich verstehe auch nicht ganz die Diskussion bezüglich der Breiten-Begrenzung. Prinzipiell ist es schön das es diese Möglichkeit gibt, aber wenn ich an einem großen Bildschirm arbeite (Ich sitze hier vor einem 4k-Monitor), gibt es ja immer noch die Möglichkeit das Browserfenster kleiner zu machen.

Diesen Punkt hatten wir bereits ganz am Anfang besprochen. Jeder arbeitet anders und daher ist es keine Option zu sagen "mach halt Dein Browserfenster kleiner".

**Comment by agoat** [comment]
> Das Problem mit dem nicht immer sichtbaren Speichern-Button, könnte mit einem Sticky-Footer (https://packagist.org/packages/jrgregory/m17-sticky-backend-footer) gelöst werden:

Zum Thema Sticky-Footer (bzw. immer sichtbare Schaltfläche):
Dazu ist keine Erweiterung nötig. Ich löse das seit der 4er-Version einfach mit einem kleinen CSS-Snipset das ich im Template (be_main.html5) einfüge. Ich pflege das für jede Version in einem kleinen Repository (https://github.com/agoat/contao4-backendtheme-fixedformsubmit) und kopiere dann den HTML-Code einfach in Contao rüber. Eine [aktuelle Version](https://github.com/agoat/contao4-backendtheme-fixedformsubmit/blob/master/contao4.4/be_main-4.4.4.html#L20-L55) für 4.4.4 gibt es auch schon (extra Datei, da sich der HTML-Code geändert hat).

Noch ein kleiner Hinweis: Im Order 'dev' gibt es noch eine Version für den Symfony Developermodus, bei dem die Schaltflächen per JS etwas nach oben geschoben werden, da sie sonst von der Debug-Bar verdeckt werden (funktioniert nicht immer, aber da ärgere nur ich mich selbst und nicht der Kunde).

**Comment by agoat** [comment]
> Ich finde es mühsam meinen Browser nur wegen dem Contao nicht auf Fullscreen laufen lassen zu müssen.

Du hast ja bestimmt nicht nur ein Browserfenster am laufen, oder? D.h. du musst ja nicht alle Fenster verkleinern. Aber du hast recht, jeder arbeitet anders.

> Diesen Punkt hatten wir bereits ganz am Anfang besprochen. Jeder arbeitet anders und daher ist es keine Option zu sagen "mach halt Dein Browserfenster kleiner".

Daher finde ich ja auch die Möglichkeit, die Breite optional zu begrenzen, nicht schlecht.

Es stellt sich aber die Frage, wie weit wir mit extra Funktionen auf die verschiedensten Bedürfnisse eingehen. Ich wünsche mir z.B. manchmal auch, dass das linke Menü bei meterlangen Inhaltslisten nicht nach oben verschwinden würde, sondern fix wäre. Das brächte aber auch wieder andere Schwierigkeiten mit dem Layout.

Noch schöner wäre, bei ausreichender Breite, ein immer sichtbarer Seiten-/Verzeichnisbaum. Aber das ist was für die nächste Major-Version (in der Design-Studie hat mir das schon sehr gefallen).

**Comment by fritzmg** [comment]
> Du hast ja bestimmt nicht nur ein Browserfenster am laufen, oder?

Doch... Wenn überhaupt dann habe ich mehrere Desktops mit je einer Browser Instanz laufen ;). Maximal noch zusätzlich ein Incognito Fenster.

**Comment by leofeyer** [comment]
Die Mehrheit scheint sich ja für ein zentriertes Layout auszusprechen, daher möchte ich gerne folgende zwei Fragen stellen:

1. Bleiben wir bei einer maximalen Breite von 1140px oder erhöhen wir auf 1280px wie von @stefan-at-work vorgeschlagen?

2. Soll der Hintergrund rechts und links eher hell oder eher dunkel sein (siehe Screenshots)?

![dadadc](https://user-images.githubusercontent.com/1192057/30156535-3b91ac8a-93c0-11e7-94c2-7370f7b2442f.png)

<img width="1024" alt="9a9a9c" src="https://user-images.githubusercontent.com/1192057/30156541-3fcf3dda-93c0-11e7-955b-240b70a822ac.png">

<img width="1024" alt="3a3a3c" src="https://user-images.githubusercontent.com/1192057/30156543-4341c4c4-93c0-11e7-9356-9b8c11e01766.png">

**Comment by fritzmg** [comment]
Mein Vote wäre:

* 1140px (eine größere Breite bietet im aktuellen Layout imho keinen Vorteil, weswegen man ja generell zur begrenzten Breite tendiert)
* Hintergrund kann meiner Meinung nach gleich bleiben.

**Comment by leofeyer** [comment]
> Hintergrund kann meiner Meinung nach gleich bleiben.

Das kann er nicht, denn der Content-Bereich "hängt" sonst in der Luft.

**Comment by frontendschlampe** [comment]
ich bringe auch mal noch eine Idee ein ... :-D

Mit Breite begrenzen würde dann die Navi nicht mehr links hängen. (Bitte mal von den zusätzlichen Icons und Infos in der Seitenstruktur nicht ablenken lassen)

![screenshot-2017-09-07-11 15 09_komplett](https://user-images.githubusercontent.com/1232819/30156999-6c08caaa-93c1-11e7-9f4e-0a20cd8ac3c1.jpg)

**Comment by agoat** [comment]
Zu 1.: Breiter würde ich es auch nicht machen. Die Begrenzung ist dafür da, es möglichst kompakt zu halten.

Zu 2.: Schwierige Frage. Dunkel sieht auch schick aus. Aber tendenziell würde ich eher ein helleres Grau nehmen, da die Arbeitsfläche von Contao ja nahezu weiß ist und der Kontrast sonst zu groß wird.

**Comment by leofeyer** [comment]
Wir könnten auch die gesamten Änderungen am Content-Bereich zurücknehmen und die Submit-Buttons ohne separaten Kasten anzeigen:

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/30157362-662f581e-93c2-11e7-9cd8-0c99d255c5a6.png">

**Comment by netzarbeiter** [comment]
1. 1140px
2. 1 Variante (mit dem hellen Hintergrund)
3. Änderungen am Content-Bereich zurücknehmen? Finde ich nicht nötig

**Comment by agoat** [comment]
Der graue Kasten um die Submit-Buttons finde ich durchaus sinnvoll. Dadurch wird das Formular-Ende deutlich. Ansonsten müsste man u.a. beim 'Pagination' Template auch Änderungen machen. 

Mit dem grauen Kasten sind die Schaltflächen, die das gesamte Formular betreffen, oben und unten vom Rest der Formularfelder optisch abgetrennt.

**Comment by leofeyer** [comment]
Gut, dann wäre es zukünftig also so:

![](https://user-images.githubusercontent.com/1192057/30161212-e672ec22-93cf-11e7-8f20-4224519cb608.png)

**Comment by agoat** [comment]
Also ich finde es eigentlich unnötig das ganze nochmal in einem eigenen Block darzustellen. Warum nicht die ganze Breite der Hauptspalte ausnutzen. 

Ehrlich gesagt finde ich die vorherige Version dahingehend besser (Content-Bereich).
![c444](https://user-images.githubusercontent.com/1402434/30161724-1ca2f218-93d2-11e7-8fc7-fc63b71d7d54.jpg)

**Comment by leofeyer** [comment]
Du solltest die Diskussion vielleicht noch mal lesen. Den neuen Block haben wir, damit wir die Submit-Buttons am Ende des Formulars darstellen können anstatt am Ende der Seite.

**Comment by agoat** [comment]
> Den neuen Block haben wir, damit wir die Submit-Buttons am Ende des Formulars darstellen können anstatt am Ende der Seite.

Die (grau hinterlegte) Zeile mit den Submit-Buttons kann doch auch so direkt unterhalb des Formulars angezeigt werden. Dazu muss doch nicht das Formular in einem weißen Kasten im grauen Content-Bereich darstellen. 
Der Content-Bereich gliedert sich in:
- Breadcrumb
- Filtermenu/Versionmenu (grau hinterlegt)
- Hinzufügen/Zurück Schaltflächen
- Liste oder Formularfelder
- Speicher Schaltflächen (auch grau hinterlegt)

Die Punkte 2-4 brauchen m.E. keinen eigenen Kasten. 

Aber ich will mich da jetzt auch nicht zu sehr einmischen. Hier zu meckern ist einfach und ich hab mich jetzt nicht intensiv genug damit beschäftigt, um hier alles mögliche zu kritisieren. Du hast bestimmt schon viel Zeit da investiert und das respektiere ich.

Aber ich bleibe dabei, das Layout von 4.4.3 hat mir bezüglich der Formular- und Listendarstellung besser gefallen.

**Comment by leofeyer** [comment]
Geändert wie besprochen in c2d952c9d0205297d0b0eecdb1dac2609c80fd4c. Das Backend ist nun wieder zentriert und insgesamt standardmäßig maximal 1.400 Pixel breit und mit der Option "Breite begrenzen" standardmäßig 1.140 Pixel.

**Comment by fritzmg** [comment]
> Das kann er nicht, denn der Content-Bereich "hängt" sonst in der Luft.

Das kann ja auch so sein. Ist ja auch in dem hier oft referenziertem AC5 so.

**Comment by leofeyer** [comment]
Nein, das ist in AC5 keineswegs so. Dort geht der Content-Bereich ja immer bis zum Rand.

**Comment by fritzmg** [comment]
Hier nicht: https://user-images.githubusercontent.com/1232819/30124481-942f77e0-9335-11e7-9155-55b4e018b7d5.png

**Comment by leofeyer** [comment]
Doch klar. Der (graue) Content-Bereich geht bis ans rechte Ende. Bei Contao hingegen hört der Content-Bereich bei 1.400px bzw. 1.1140px auf:

![](https://user-images.githubusercontent.com/1192057/30202469-deabb6a4-947e-11e7-8895-7c157df870fc.png)

**Comment by fritzmg** [comment]
Achso, ich dachte eher an https://user-images.githubusercontent.com/1942550/30117134-a9848510-931f-11e7-84f4-a8927cf5b3c8.png

**Comment by agoat** [comment]
Deshalb finde ich die vorherige Version besser. 

- Header - Hintergrund: orange
- Menu links - Hintergrund: dunkel grau
- Content/Formular  - Hintergrund: weiß bzw. fast weiß

Wenn die Breadcumb mit im Kasten ist, dann kann man den (jetzt weißen) Kasten auf den ganzen Contentbereich ausdehnen und braucht keinen Kasten im Kasten oder so. Und es hängt nichts in der Luft.

Und eine **standardmäßige Begrenzung** der Breite ist absolut der **falsche Ansatz**!! Was bring mir dann eine Schaltfläche mit der ich die Breite von (auf meinem Monitor lächerliche) 1400px auf 1140px reduzieren kann. 

Für die, die das Backend auf einem großen Monitor haben ist die optionale Begrenzung gut, um die Klickwege zu reduzieren. Aber manche möchten keine Begrenzung.

**Comment by leofeyer** [comment]
> Und eine standardmäßige Begrenzung der Breite ist absolut der falsche Ansatz!

Das nennt sich "responsive design". 😄

**Comment by agoat** [comment]
> Das nennt sich "responsive design". 😄

Das wäre aber ein schwacher Ansatz für 'Responsive Design' ;-)

**Comment by internetinnovations** [comment]
> Das Problem mit dem nicht immer sichtbaren Speichern-Button, könnte mit einem Sticky-Footer (https://packagist.org/packages/jrgregory/m17-sticky-backend-footer) gelöst werden:

Vielleicht habe ich auch etwas überlesen, gibt es hierzu noch Feedback?
Dieses Feature wäre für die Content-Manager unserer Kunden eine riesige Erleichterung unter Contao 4.4...

**Comment by agoat** [comment]
> Dieses Feature wäre für die Content-Manager unserer Kunden eine riesige Erleichterung unter Contao 4.4...

Dazu sind nur etwa 20 Zeilen JS- und CSS-Code notwendig. Ich habe mir dafür ein `be_main.html5` template erstellt (siehe https://github.com/agoat/contao4-backendtheme-fixedformsubmit/tree/master/contao4.4).

Einfach die RAW-Ansicht kopieren und in der Contao Template-Verwaltung einfügen.
