### ISSUE TITLE
Design-Änderungen in Contao 4.4.4

### ISSUE THREAD

**Issue by nexper** [contao/core-bundle#1054]
Welchen Grund hat es, dass die Hintergrundfarbe im Content-Bereich wieder auf grau statt weiß geändert wurde? Ich finde im Sinne der modernen UI, die bis 4.4.3 vorhanden war ist es ein Rückschritt in die alte Richtung. Außerdem stören mich diese extremen weißen Trennstriche bei den Icons rechts in der Navbar. Könnte man das evtl. etwas dezenter gestalten?

Würde gerne mit euch darüber diskutieren, was ihr besser findet.

**Comment by Aybee** [comment]
Wenn ich das richtig sehe, dann wurde die Farbe nicht geändert. Hintergrund im "Content-Bereich" ist immer noch weiß.
```css
#main .content {
	margin: 15px 10px;
	background: #fff;
	border: 1px solid #ddd;
}
```
Allerdings ist jetzt im Modus "Breite begrenzen" die BE-Navigation ganz am linken Rand. Das ist **sehr schlecht** und kann IMHO so nicht bleiben. Ich habe dadurch einen zusätzlichen unnötigen Weg mit der Maus von 330px und muss nun auch meinen Kopf drehen, wenn ich meinen Blick vom Inhalt auf die Navigation und zurück richten möchte.
![screengrab-20170906-205456](https://user-images.githubusercontent.com/1143013/30129344-e174cb3a-9345-11e7-9729-62fea1eac178.png)
👎

**Comment by leofeyer** [comment]
Siehe #1053.

**Comment by leofeyer** [comment]
> Außerdem stören mich diese extremen weißen Trennstriche bei den Icons rechts in der Navbar. Könnte man das evtl. etwas dezenter gestalten?

@nexper Ich bin für Vorschläge offen.

**Comment by nexper** [comment]
Ich würde Vorschlagen, das man die orange Hintergrundfarbe aufhellt. Ähnlich wie die Trennstriche in der Sidebar-Navigation ja auch eine hellere Version der Hintergrundfarbe sind. Sonst ist der Kontrast einfach zu heftig.

Darf ich fragen, wieso Ihr die Text-Navigation in pure Icons umgewandelt habt?

@Aybee - Ich meine tatsächlich nicht den Contentbereich an sich, sondern die graue Farbe drum herum. Wenn das Layout auf "fluid" stand bisher, dann war der Bereich unter Navbar und neben Sidebar komplett weiß.

**Comment by fritzmg** [comment]
@Aybee es ist der Unterschied zwischen https://user-images.githubusercontent.com/1942550/30117134-a9848510-931f-11e7-84f4-a8927cf5b3c8.png und https://user-images.githubusercontent.com/1942550/30117148-b2d69ea0-931f-11e7-86a5-ac1910899e73.png gemeint.

**Comment by xchs** [comment]
> Darf ich fragen, wieso Ihr die Text-Navigation in pure Icons umgewandelt habt?

In diesem Zusammenhang vielleicht auch ganz interessant ein Artikel, den ich neulich gelesen habe: [How icons are ruining interfaces](https://axesslab.com/icons-ruining-interfaces/)

TL;DR: Icons should have labels

Ich habe mich heute schon ein paar Mal dabei ertappt, wie ich im Backend von Contao 4.4.4 erfolglos auf das Label "Benutzer k.jones" geklickt habe 😺

**Comment by leofeyer** [comment]
> Ich würde Vorschlagen, das man die orange Hintergrundfarbe aufhellt. Ähnlich wie die Trennstriche in der Sidebar-Navigation ja auch eine hellere Version der Hintergrundfarbe sind. 

Das hatte ich bereits versucht und es sah komisch aus.

<img width="253" alt="" src="https://user-images.githubusercontent.com/1192057/30149306-6f8945c0-93a7-11e7-9905-46820de113bf.png">

**Comment by OMOSde** [comment]
Ich persönlich fand das alte Verhalten vom tmenu eigentlich sehr gut. Ich verstehe nicht, warum man Informationen versteckt (Label), wenn der Platz ausreichend vorhanden ist. Bzgl. Usability empfinde ich das als falsch.

**Comment by leofeyer** [comment]
> How icons are ruining interfaces

Die Argumentation ist relativ dünn IMO. Schau Dir doch einfach mal die Header von ein paar großen Seiten an (Facebook, Twitter, Apple, Gmail etc.), dann siehst Du, dass überall Icons verwendet werden.

> Ich habe mich heute schon ein paar Mal dabei ertappt, wie ich im Backend von Contao 4.4.4 erfolglos auf das Label "Benutzer k.jones" geklickt habe

Das ist in der Tat unglücklich. Werde ich ändern.

**Comment by frontendschlampe** [comment]
Können wir die Diskussion nicht in einem Ticket führen? ;-)

**Comment by xchs** [comment]
> Die Argumentation ist relativ dünn IMO. Schau Dir doch einfach mal die Header von ein paar großen Seiten an (Facebook, Twitter, Apple, Gmail etc.), dann siehst Du, dass überall Icons verwendet werden.

Dann hast Du den Succus des Artikels irgendwie missverstanden. Im gegenständlichen Artikel geht es ja nicht darum, auf Icons zu verzichten. Ganz im Gegenteil! Wenn man Icons verwendet (und da spricht ja überhaupt nichts dagegen), sollte man nach Möglichkeit immer auch ein passendes Label vorsehen (*). Das ist im Navigationsmenü bei Twitter der Fall und bei Apple auch.

Kurzum: Icon UND Label!

(*) Mir ist schon klar, dass aus Layout- und Platzgründen die Verwendung von Icons + Labels nicht immer und überall möglich ist. Aber dort, wo es geht, sollte man es imho auch machen (siehe Header von Contao 4.4.3).

**Comment by leofeyer** [comment]
> Wenn man Icons verwendet sollte man nach Möglichkeit immer auch ein passendes Label vorsehen

Ja und genau das ist eben **nicht** der Fall! Bei keinem (!) der genannten Beispiele. Muss ich jetzt wirklich Screenshots machen?

**Comment by xchs** [comment]
> Muss ich jetzt wirklich Screenshots machen?

Nein, die Screenshots kann ich ja auch machen:
* Twitter:
![screenshot-twitter com-2017-09-07-14-49-45](https://user-images.githubusercontent.com/1218766/30164242-179fb8fa-93dc-11e7-94c4-35df0e4a96d5.png)
![screenshot-twitter com-2017-09-07-14-50-18](https://user-images.githubusercontent.com/1218766/30164248-1b494fac-93dc-11e7-8799-bbb768fd42c3.png)
* Apple:
![screenshot-www apple com-2017-09-07-14-51-05](https://user-images.githubusercontent.com/1218766/30164254-20d5f9c0-93dc-11e7-9a17-7e5d11e6136b.png)

**Comment by OMOSde** [comment]
Vielleicht sollte man sich auch nicht so stark auf andere konzentrieren, sondern eher schauen, was für den Benutzer am sinnvollsten ist. 

Ich persönlich empfinde ein Icon + label deutlich besser.

Siehe auch: https://www.nngroup.com/articles/icon-usability/

**Comment by leofeyer** [comment]
> Nein, die Screenshots kann ich ja auch machen

Sehr schade, dass wir das jetzt wirklich machen. Aber gut:

<img width="1022" alt="" src="https://user-images.githubusercontent.com/1192057/30169806-b567384a-93ed-11e7-93da-3c5aaa054ba6.png">

<img width="1023" alt="" src="https://user-images.githubusercontent.com/1192057/30169807-b5682336-93ed-11e7-866d-ff889227d507.png">

<img width="1023" alt="" src="https://user-images.githubusercontent.com/1192057/30169808-b56897d0-93ed-11e7-987b-c232ec1ba503.png">

Hab alle Icons ohne Label eingekreist.

**Comment by fritzmg** [comment]
@leofeyer in deinen Beispielen ist ja auch der Platz entsprechend gering. Bei den top Buttons in Contao macht es meiner Meinung nach auch keinen Sinn die Labels zu entfernen - solange noch Platz ist.

**Comment by j0nem** [comment]
Außerdem hat man sich als User daran gewöhnt, dass bei Icons ohne Label beim Klick keine großartigen Veränderungen an der Seite auftreten (sondern sich nur Überlaufmenüs oder Flyouts öffnen und schließen, wie bei Facebook, Apple oder auch Inbox), da man ja aufgrund der fehlenden Information nicht immer ganz genau weiß, was dort passiert. Bei den Top-Buttons in Contao öffnet sich allerdings entweder eine ganz neue Seite oder man wird sogar komplett ausgeloggt.

**Comment by nexper** [comment]
Ich stimme @j0nem zu. Bei puren Icons erwartet man eher ein Dropdown-Menü oder ähnliches.
Vorschlag: Labels neben den Icons ab Tablet-Auflösung wieder sichtbar und danach kann man ja für die mobile Ansicht das einkürzen. Vor allem, weil z.B. das Frontend-Vorschau-Icon nicht für jeden sofort verständlich ist was es macht. Im Gegensatz z.B. zu einem Warenkorb.

@leofeyer - Ich persönlich finde die aufgehellte Hintergrundfarbe bei den Trennstrichen gar nicht mal so schrecklich. Aber vielleicht bin ich da ja auch der einzige, den das stört. Was sagen die anderen hier? Ggf. völlig auf die Trenner verzichten? Sind ja in deinen oben gezeigten Beispielen auch nicht vorhanden.
Aber vielleicht gibt es ja auch einen guten Grund, dass du die so eingebaut hast wie sie jetzt sind. :)

**Comment by leofeyer** [comment]
Wo wir beim Thema sind: Wäre folgendes eine Möglichkeit?

![](https://user-images.githubusercontent.com/1192057/30243156-ff9bb9c4-95a3-11e7-9918-d8eab25d8976.png)

@frontendschlampe @netzarbeiter /cc

**Comment by OMOSde** [comment]
Das wäre ein Verzicht auf die durchgängige Topbar (orange)? Das würde ich nicht begrüßen. Wir stellen dort dem Kunden gerne Kontaktinformationen oder andere wichtige Short-Links zur Verfügung.

**Comment by netzarbeiter** [comment]
Würde das Wartungsmodus-Symbol links von den drei Punkten angezeigt?

![contao1](https://user-images.githubusercontent.com/1942550/30261267-0e0462d0-96cc-11e7-82dc-df2a19372009.png)

Ein Bereich für Short-Links und Kontaktinformationen würde weiterhin bestehen:
![contao2](https://user-images.githubusercontent.com/1942550/30261312-5263ef86-96cc-11e7-9399-f251101d4c9b.png)

**Comment by agoat** [comment]
Ist schon jemandem aufgefallen, dass die Zeile mit den Sort-, Search-, Show-Feldern in der mobilen Ansicht etwas unsinnig durcheinander gewürfelt werden (auch ersichtlich in den Beispielbildern von @leofeyer)??
Evtl. ist es hier besser die Felder links zu 'floaten' (ungetestet).

Außerdem wäre es noch für die 'Usibility' sinnvoll, wenn die Filter, die in der mobilen Ansicht untereinander stehen, versteckt bzw. ausklappbar wären. So ist auf jeder Seite fast ein ganzer Bildschirm runter zu scrollen bis der eigentliche Inhalt zu sehen ist.

**Comment by leofeyer** [comment]
Hier wäre die nicht-mobile Ansicht:

<img width="399" alt="" src="https://user-images.githubusercontent.com/1192057/30439698-c6013476-9974-11e7-9ef3-df7cc8f63d3d.png">

<img width="371" alt="" src="https://user-images.githubusercontent.com/1192057/30439693-c5712840-9974-11e7-8353-7f07009b8ab7.png">

Ich weiß aber noch nicht, ob mir das wirklich gefällt. 😄

**Comment by leofeyer** [comment]
Vielleicht besser so:

<img width="309" alt="" src="https://user-images.githubusercontent.com/1192057/30440446-d43724a4-9976-11e7-884a-fd21092e1881.png">

**Comment by leofeyer** [comment]
![](https://user-images.githubusercontent.com/1192057/30440487-fabe8720-9976-11e7-9e57-38e9fc583f3c.png)

**Comment by fritzmg** [comment]
I think it wouldn't hurt to still show the icon + the label for the preview for example (in the Desktop view)

**Comment by agoat** [comment]
+1 für die Headerbar
-1 für den weißen Inhaltskasten auf grauem Hintergrund (Layout von 4.4.3 war hier besser)

Da ja jetzt (siehe #1053) bei der Breitenbegrenzung sowohl der Header als auch das Menü mit Inhalt begrenzt wird, gibt es kein Problem wenn der weiße Hintergrund bis an die Ränder geht.

**Comment by leofeyer** [comment]
Behoben in e4cb5f257cf1b12844bce31b51f37ae37f4143d6.
