### ISSUE TITLE
Define collation for new sql array syntax in DCA doesn't work

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1056]
Hello,

I just noticed that it's now possible to define the sql schema as an array rather than a string. Unfortunately, collations (or options) don't seem to be passed to the relevant point in contao. This:

```'sql' => ['type' => 'string', 'length' => 128, 'default' => '', 'options' => ["collation"=>"utf8_bin"]],```

doesn't work as

```'sql' => "varchar(128) COLLATE utf8_bin NOT NULL default ''",```

does.

Is it just not implemented, yet? Or am I doing something wrong?

**Comment by aschempp** [comment]
The configuration is passed to Doctrine, so it depends if Doctrine supports that. Also, be aware that the DBAL syntax (we're using) is different from ORM annotations!
