### ISSUE TITLE
Model::getClassFromTable doesn't respect namespaces

### ISSUE THREAD

**Issue by saibotd** [contao/core-bundle#1060]
We are currently upgrading a module to a Bundle and I can't get around this one problem, which may be a bug or a misunderstanding on my side. Our Bundle uses the dca and some custom models, all of the models are name-spaced (OurCompany/OurBundle/Models). We also use the ContaoManager to autoload everything in Contao (Managed Edition).
The error now is that Contao expects the namespace of all models to be global I guess:

`Attempted to load class \"CalendarsModel\" from the global namespace.\nDid you forget a \"use\" statement? at /var/www/html/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Model/Registry.php:104)`

The name for the model is dependent on the name for the table alone (if I'm reading Model::getClassFromTable corect, that is) so how can we 'inject' our namespace, so that Contao knows where to look?

Btw. If I remove the models everything works fine (except for our custom model methods, of course).

**Comment by ausi** [comment]
You can register your model class in the *src/Resources/contao/config/config.php* like so:

```php
$GLOBALS['TL_MODELS']['tl_calendars'] = 'OurCompany\\OurBundle\\Models\\CalendarsModel';
```

**Comment by saibotd** [comment]
@ausi That's it! You saved my weekend 👍
