### ISSUE TITLE
copying form fields creates invalid field names

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1062]
If you copy a form field in the form generator, Contao automatically appends ` (Kopie)` or ` (copy)` (with a space in front) to the field name, which creates an invalid field name and thus the form field will not work in the front end. Any data submitted for such a form field will not be recognized by Contao.

**Comment by leofeyer** [comment]
Why is this a problem? The field cannot be saved with the parenthesis in it.

**Comment by fritzmg** [comment]
> Why is this a problem? The field cannot be saved with the parenthesis in it.

It is already saved once copied. Also if you copy multiple fields, you won't be in any edit form.

**Comment by leofeyer** [comment]
Fixed in 8f44653567ca3d20358ffb2b35a7c28d4d668930.

**Comment by fritzmg** [comment]
Wouldn't this change also create invalid form fields? For example when you copy the whole form, or multiple fields.

**Comment by leofeyer** [comment]
You are right. I have reverted the changes in 54dc145fc3b24a4548b55c42927f73cbcf382812 and simply changed the field order in the DCA so the label gets the `(copy)` suffix.
