### ISSUE TITLE
Require symfony/symfony

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#1070]
Shouldn't it be correct to require(-dev?) ``symfony/symfony`` in (all) contao bundles?
(Not that anyone uses the core-bundle standalone right now...)

----
Background: I stumbled across this when I wrote a manager plugin for a reusable bundle. During development I  use composer with the bundle's ``composer.json`` to get code checking and autocompletion for the required components. For the manager plugin the bundle classes are needed - so e.g. for ``TwigBundle`` there is the need to require ``symfony/symfony``.  

see [Manager Plugin](https://github.com/contao/core-bundle/blob/master/src/ContaoManager/Plugin.php) references ``SecurityBundle``, ``TwigBundle``, ``MonologBundle``... and ``ContaoManagerBundle`` btw.

**Comment by leofeyer** [comment]
I don't think so. First, requiring `symfony/symfony` has been implicitly deprecated with Symfony flex. Second, you should only require the components that you are actually using, so maybe the requirements of the manager plugin are not sufficient?

Does this issue affect only the manager plugin?

**Comment by m-vo** [comment]
Likely that it only affects the manager plugin. 

In the core we're e.g. using the following use statement.
```php
use Symfony\Bundle\TwigBundle\TwigBundle;
```
It's arguabable if a ``TwigBundle::class`` really is consuming the class as this string might work without the class beeing present. But code checking complains about it so that's why I thought it might be useful to have it available as a dev-requirement.

**Comment by leofeyer** [comment]
Well `use Symfony\Bundle\TwigBundle\TwigBundle` does indicate that the Twig bundle is a required dependency that should be listed in the `composer.json` file.

**Comment by aschempp** [comment]
`contao/manager-plugin` certainly is the wrong target, you might have mistaken that for the manager-bundle

**Comment by leofeyer** [comment]
As discussed in Mumble on November 30th, 2017, my initial answer was correct. 😄 

> you should only require the components that you are actually using
