### ISSUE TITLE
Template "gallery_default.html5" changes will be ignored in Backend

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#1073]
Hello,

I created a copy of the template `gallery_default.html5` in my theme template folder and changed something. If I test the page in the Frontend view, all my changes are visible.
But in the Backend view, my changes will be ignored. 

If I move the template from my theme folder in the root template folder, it works in FE and BE.

If I create a copy of `gallery_default.html5` in the root template folder and in my theme folder. The FE use the template from my theme folder and the BE use the template from the root folder.

This is not normal, is it?

I use Contao 4.4.4

**Comment by leofeyer** [comment]
> This is not normal, is it?

Yes. The theme folder is only considered in the front end.
