### ISSUE TITLE
Search::indexPage wirft Fehler sobald <meta name="keywords"> definiert

### ISSUE THREAD

**Issue by fatcrobat** [contao/core-bundle#1078]
Contao Version: 4.4.4

Der Fehler trifft auf, sobald meta keywords im Kopf der Seite eingebunden werden:

```
DRIVEREXCEPTION
An exception occurred while executing 'INSERT INTO tl_search_index (pid, word, relevance, language) VALUES ('44', 'studienplatz,studienplatzklage,universität,einklagen,rechtsanwalt,anwalt,anwaltauskunft,studieren,medizin,psychologie,studium', 1, 'de')':

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'word' at row 1
```

Hier der zugehörige keywords meta-tag.

```
<meta name="keywords" content="studienplatz,studienplatzklage,universität,einklagen,rechtsanwalt,anwalt,anwaltauskunft,studieren,medizin,psychologie,studium">
```

**Der Fehler trifft nur dann auf, wenn die Keywords ohne ein Leerzeichen nach dem Komma separiert wurden.**

```
<meta name="keywords" content="studienplatz, studienplatzklage, universität, einklagen, rechtsanwalt, anwalt, anwaltauskunft, studieren, medizin, psychologie, studium">
```
*Diese Formatierung würde den Fehler nicht produzieren.*

**Comment by fritzmg** [comment]
Du hast die eigentliche Fehlermeldung bzw. den Grund für den Fehler abgeschnitten.

**Comment by fatcrobat** [comment]
@fritzmg Nun mit kompletter Fehlermeldung.

**Comment by fritzmg** [comment]
It appears `Search::indexPage` cannot handle cases well, where words are delimited by commas without spaces - resulting in one long word instead of words separated by these commas.

**Comment by leofeyer** [comment]
Das ist richtig, die Methode erwartet, dass die Suchbegriffe mittels Leerzeichen getrennt sind. Sollten wir wohl ändern, oder @contao/developers ?

**Comment by ausi** [comment]
I think there are two separate issues:

First we don’t limit the length of words in https://github.com/contao/core-bundle/blob/60970bc1027a9b293279342ec0158df2b471da73/src/Resources/contao/library/Contao/Search.php#L286 which causes the SQL error `Data too long`.

This should be easy to fix by checking `mb_strlen()` on the word before inserting it.

In https://github.com/contao/core-bundle/blob/60970bc1027a9b293279342ec0158df2b471da73/src/Resources/contao/library/Contao/Search.php#L238 we define `[\w\'.:,+-]` as the allowed characters in a word so `foo,bar` gets recognized as a single word instead of two separate words.

I don’t see why `,` should be a word character but maybe there is a reason for that?

**Comment by Toflar** [comment]
`StringUtil::trimsplit(' ,', $keywords)` should do.

**Comment by leofeyer** [comment]
Fixed in 836f0fd99c70a86f7b20faa69facaa17c19fba97.

@ausi I figure now that we are splitting the keywords correctly, we don't have to check the string length. Although, what would we do with a too long string? Thrown an exception? Truncate it?

**Comment by ausi** [comment]
> I figure now that we are splitting the keywords correctly, we don't have to check the string length.

I think we should check the string length nevertheless to avoid the SQL error.

> Although, what would we do with a too long string? Thrown an exception? Truncate it?

I would truncate it, IIRC Contao supports searching for the beginning of words, so the truncated version of a very long word would still make sense.

**Comment by fritzmg** [comment]
> I would truncate it, IIRC Contao supports searching for the beginning of words

Only if you enable that in the settings of the search module. Otherwise it searches for whole words by default.

**Comment by m-vo** [comment]
>Only if you enable that in the settings of the search module. Otherwise it searches for whole words by default.

I think that would be fine in this edge case.

**Comment by fritzmg** [comment]
Agreed, just wanted to mention that.

**Comment by leofeyer** [comment]
Is an edge case that **nobody** had in the last over 11 years really worth the time and energy to handle it?
