### ISSUE TITLE
Request token handling buggy

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1080]
There are two issues:

1. You cannot send `POST` requests with `application/json` as you must provide `REQUEST_TOKEN` as post value. I think we should fix that by falling back to a header.

2. You get a pure nonsense `X-Ajax-Location` response in the front end if you do not provide a valid token.

Wdyt about something like this:

```diff
diff --git a/src/Framework/ContaoFramework.php b/src/Framework/ContaoFramework.php
index b63d9a6..b1e92c9 100644
--- a/src/Framework/ContaoFramework.php
+++ b/src/Framework/ContaoFramework.php
@@ -446,11 +446,13 @@ class ContaoFramework implements ContaoFrameworkInterface, ContainerAwareInterfa
             define('REQUEST_TOKEN', 'cli' === PHP_SAPI ? null : $requestToken->get());
         }
 
-        if ($this->canSkipTokenCheck() || $requestToken->validate($this->request->request->get('REQUEST_TOKEN'))) {
+        if ($this->canSkipTokenCheck() || $requestToken->validate(
+            $this->request->request->get('REQUEST_TOKEN', $this->request->headers->get('Contao-Request-Token')))
+        ) {
             return;
         }
 
-        if ($this->request->isXmlHttpRequest()) {
+        if ($this->request->isXmlHttpRequest() && 'BE' === $this->getMode()) {
             throw new AjaxRedirectResponseException($this->router->generate('contao_backend'));
         }
 ```

**Comment by leofeyer** [comment]
Isn't the first one (fallback to the `Contao-Request-Token` header) a new feature whereas "only throw the exception in the back end" is a bugfix?

**Comment by Toflar** [comment]
It's just impossible to send a regular json post request to the FE at the moment, it's not really a feature to me :)

**Comment by leofeyer** [comment]
It is not impossible. You can use a separate route with the `_request_token` attribute set to `false`.

@contao/developers Should we add the new header in the next bugfix version?

**Comment by bytehead** [comment]
👍  for adding the new header in the next bugfix version, 4.4.x is at least LTS.

**Comment by Toflar** [comment]
> It is not impossible. You can use a separate route with the _request_token attribute set to false.

No you can't in many cases because permissions are still not in their own services so I could reuse them. In many cases, the only save way is to run through the whole stack again.

**Comment by leofeyer** [comment]
So after the change we can send the header either as POST data or as HTTP header, can't we?

@ausi Any security concerns?

**Comment by ausi** [comment]
No security concerns. But I think we could make it simpler by just skipping the request token check for AJAX requests completely. Adding `$this->request->isXmlHttpRequest()` to `canSkipTokenCheck()` should be enough.

[From OWASP](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Protecting_REST_Services:_Use_of_Custom_Request_Headers):

> An alternate defense which is particularly well suited for AJAX endpoints is the use of a custom request header. This defense relies on the same-origin policy (SOP) restriction that only JavaScript can be used to add a custom header, and only within its origin.
>
> A particularly attractive custom header and value to use is:
> 
> * X-Requested-With: XMLHttpRequest

**Comment by Toflar** [comment]
Yes we could do that because having that header makes it a non-simple-request and thus forcing a CORS preflight request.
Adding the check to `canSkipTokenCheck()` would force the developers to pass `X-Requested-With: XMLHttpRequest` so I'd be fine with that solution :)

**Comment by leofeyer** [comment]
I don't think that this would solve @Toflar's problem.

**Comment by leofeyer** [comment]
But that would not solve the `application/json` request issue, would it?

**Comment by Toflar** [comment]
It would, you can disable the token check if it's an ajax request because it's not needed. The detection of whether it is an ajax request or not is done using the `X-Requested-With` header. And sending that (which you'll need to skip the check) makes it a non-simple-CORS-request by definition thus allowing only same origin requests.

**Comment by leofeyer** [comment]
Fixed in d81ac82c370ce21fe291e92f38435d84f777c177.

**Comment by aschempp** [comment]
There's a reason we returned that Ajax response, and I'm pretty sure that was to toggle a login redirect if I toggle a subpalette in the backend etc. Now that would not longer be done, do you think that's a good idea?

**Comment by leofeyer** [comment]
I know what you are referring to, but I don't think it applies here. The exception would only be thrown if the request token check failed and since we are not checking the request token upon Ajax requests anymore, it can never happen if you toggle a palette.

**Comment by aschempp** [comment]
Sort of true, it means the user will get a token error message when saving a backend record instead of being redirected when toggling a subpalette.

**Comment by leofeyer** [comment]
Why would he get an error message at all?

**Comment by aschempp** [comment]
Because the token might expire.

**Comment by leofeyer** [comment]
@ausi @Toflar I think @aschempp has a point here.

**Comment by ausi** [comment]
> it means the user will get a token error message when saving a backend record

Which is perfectly fine if the token did expire, what else should happen?

**Comment by Toflar** [comment]
It used to redirect you to `/contao` because of the `X-Ajax-Location` header but I never understood that.
