### ISSUE TITLE
Inhaltselement Hyperlink zeigt keinen Link bei fehlendem Linktext an

### ISSUE THREAD

**Issue by Jaaaan** [contao/core-bundle#1081]
Hallo zusammen,
lässt man beim Inhaltselement Hyperlink den zusätzlichen Linktext weg, so wird im Frontend auch nicht der normale Link angezeigt. Im Seitenquelltext ist jedoch erkennbar, dass dort ein Link vorhanden ist: 
![grafik](https://user-images.githubusercontent.com/16544159/30521116-66f16346-9bba-11e7-9ad6-eceef5e52e4b.png)
Auch in der Onlinedemo reproduzierbar:
![grafik](https://user-images.githubusercontent.com/16544159/30521130-a2b28306-9bba-11e7-8038-8d19ef3437de.png)
Oder muss seit Contao 4 immer ein Linktext zusätzlich vergeben werden?
Danke schon mal!

**Comment by leofeyer** [comment]
Behoben in 2bc6aa9d8d3511f61702bc3cbff30cbcf6fc9fdd.
