### ISSUE TITLE
Remove the general width limitation of the backend layout

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1082]
Sorry, I have to open this Issue.

The general limit of 1400px is totally nonsence!!
Why do we have a 'Limit width' button??

Please remove the general limit. 

As discussed in former issue tickets the top bar is ok now. But the general limit is a NOGO. 
And the the grey background of the content doesn't look good IMO. I wish to we can have the layout of 4.4.3 for the content section again. It was with the white background clean and nice.

**Comment by leofeyer** [comment]
We have extensively discussed the back end theme changes in #1053, #1054 and the last Mumble call and I have implemented the solution that the majority has agreed on. I'm not gonna discuss this again!

**Comment by agoat** [comment]
To be clear, it's nothing personal and I don't want to annoy you (anymore). 
Just had to say it one last time, promised ;-)

**Comment by asaage** [comment]
I agree - the general limit is nonsense.
1. this will reduce the width by just 260px 
![image](https://user-images.githubusercontent.com/4138336/30543304-d6dad7be-9c82-11e7-9ebf-e46d4938abb4.png)
2. this looks ridiculous 
![image](https://user-images.githubusercontent.com/4138336/30543066-feb20d3a-9c81-11e7-9dee-d014b0b7cc95.png)

Why not let the user decide which width to be the limit and if left blank go for [Full-Screen](https://github.com/contao/core-bundle/issues/1053#issuecomment-327536295)?
If i am to lazy to reduce the width of my browser-window the limited (1400px or 1140px) centered layout will be covered by other application-windows anyway while multitasking.

**Comment by christian-schattat** [comment]
Den Anpassungen gingen lange und teilweise emotionale Diskussionen voraus und mir ist klar, dass nun wahrscheinlich niemand mehr Lust auf das Thema hat. Leider habe ich die Anpassungen erst nach dem Update wahrgenommen und verpasst, mich an der Diskussion zu beteiligen.

Nach den Diskussionen in #1053 und #1054 sehe ich auch, dass es einige Anwender stören mag, wenn Mauswege zu lang werden und deshalb ist die Option _Breite begrenzen_ im Backend auch nützlich. Aber ich kann aus den Diskussionen nicht ableiten, warum auch die Ansicht ohne begrenzte Breite unter eben dieser Begrenzung leiden muss.

Wie gesagt, mir ist bewusst, dass ich zu spät bin. Aber schade ist es um das Feature _Fullscreen_ auf jeden Fall.

**Comment by leofeyer** [comment]
Das Backend verhält sich responsive, sowohl auf kleinen als auch auf großen Monitoren. Eine Breite von 2500 Pixeln bedeutet für viele nur längere Mauswege ohne irgendeinen Mehrwert, daher haben wir uns auf die 1400 Pixel geeinigt.

Die Option "Breite begrenzen" hat damit gar nichts zu tun. Sie sorgt nur dafür, dass das Backend niemals breiter wird als es in Contao <4.4 war (nämlich 1140px). Über den Sinn dieser Option kann man jetzt angesichts der Begrenzung auf 1400 bzw. 1440 Pixel natürlich streiten …

Vermutlich wäre es sinnvoller, aus der Option "Breite begrenzen" in Contao 4.5 die Option "Breite nicht begrenzen" zu machen, damit das Backend standardmäßig maximal 1440 Pixel breit ist und bei Bedarf wieder Fulllscreen werden kann.

**Comment by nexper** [comment]
Ich finde die Idee, die Checkbox "Breite begrenzen" gegen "Backend im Fullscreen-Modus anzeigen" auszutauschen deutlich besser. Meine Kunden haben sich auch positiv über den ausgefüllten Screen geäußert. Habe jetzt im Zuge von Contao 4.4.5 ein BE-CSS mit in meine Kundenerweiterung integriert, um die Fullscreen-Ansicht wieder zu aktivieren.

**Comment by agoat** [comment]
Nur zur Info: Ich habe ein einfaches 'be_main.html5' Template, das neben immer sichtbaren Speicherbuttons, auch in Teilen das Layout von 4.4.3 wiederherstellt. Zumindest was den Fullscreen-Modus und die Tabellen Darstellung angeht. 
https://github.com/agoat/contao4-backendtheme-fixedformsubmit/tree/master/contao4.4

**Comment by fritzmg** [comment]
Imho sollte es nicht nur um die "Mauswege" gehen, sondern auch um die "Blickwege". Selbst bei einer Begrenzung von 1440px sind diese, meiner Meinung nach, etwas zu lang:

![screen-shot-2017-10-18-at-09 57 52](https://user-images.githubusercontent.com/4970961/31707343-59a30f42-b3ec-11e7-8f0f-dc0b1b91c280.png)

Im aktuellen Backend Layout von Contao sind die Schaltflächen für die Aktionen eines Elements und die Information darüber, welches Element es ist, auf jeweils gegenüberliegenden Seiten. Bei einem schmalen Bildschirm/Browserbreite, bzw. einer kleinen Maximalbreite ist das kein Problem, da dann beides nicht so weit auseinander liegt.

![screen-shot-2017-10-18-at-10 11](https://user-images.githubusercontent.com/4970961/31707587-09965f80-b3ed-11e7-90a7-dbf333d65378.png)

**Comment by agoat** [comment]
> Im aktuellen Backend Layout von Contao sind die Schaltflächen für die Aktionen eines Elements und die Information darüber, welches Element es ist, auf jeweils gegenüberliegenden Seiten. Bei einem schmalen Bildschirm/Browserbreite, bzw. einer kleinen Maximalbreite ist das kein Problem, da dann beides nicht so weit auseinander liegt.

Ich hatte mal versucht die Schaltflächen nach links neben den Element Titel zu schieben, aber auf die schnelle kein zufriedenstellendes Ergebnis bekommen. 
Allerdings finde ich es nach wie vor nicht gut, aufgrund von Maus- und Blickwege das gesamte Layout in der Breite zu begrenzen (wenn dann nur optional), denn ich habe einen großen (und breiten) Monitor damit ich da viel darstellen kann.

Wie schonmal erwähnt und auch in der Fallstudie gezeigt, wäre ein immer sichtbarer Seitenbaum, also ein Drei-Spalten Layout mit Menü, Seitenbaum und Elementeigenschaften sehr schön und würde den vorhanden Platz bei breiten Bildschirmen besser ausnutzen (und viele Klickwege sparen).
Vielleicht ist das schon in 4.5 möglich.

**Comment by leofeyer** [comment]
Geändert in c77e0e9f27e3fe6541f177fa8334afd095845dc2
