### ISSUE TITLE
After update to 4.4.5: Alerts are not properly displayed

### ISSUE THREAD

**Issue by jscholtysik** [contao/core-bundle#1083]
After the update from 4.4.4 to 4.4.5 the alerts in the upper right corner left beside the preview are not displayed in a proper way and are cutted:

![bildschirmfoto 2017-09-18 um 12 25 11](https://user-images.githubusercontent.com/1425566/30538225-51ed02a8-9c6d-11e7-89a8-e4db8196cd77.png)

It doesn't matter whether the backend width is limited to 1140px or to 1400px in the user settings...

**Comment by leofeyer** [comment]
Did you clear the browser cache after the update?

**Comment by jscholtysik** [comment]
Yes, i did. This problem only occurs in Firefox (I have 55.0.3). Chrome 61.0.3163.91 and Safari 10.1.2 are fine.

**Comment by leofeyer** [comment]
Tatsache. Firefox kommt mit dem `text-indent:100%` offenbar nicht klar.

@ausi /cc

**Comment by leofeyer** [comment]
`text-indent:4em` würde funktionieren.

**Comment by jscholtysik** [comment]
Ist ja Gott sei Dank kein tragischer Fehler...

**Comment by leofeyer** [comment]
https://stackoverflow.com/questions/18405604/firefox-text-indent-bug-on-overflow-hidden

**Comment by leofeyer** [comment]
Sieht aber nicht so aus, als würde der Bug in Firefox behoben. Das Ticket ist seit über 4 Jahren offen. 😄

**Comment by fritzmg** [comment]
Ist vielleicht einfach Interpretationsfrage. Die `width:100%` sollten sich hier ja auf die `content-box` beziehen - welche eben nur 16px breit ist. Durch das padding sieht man aber mehr als nur die `content-box`.

_Allerdings:_ verwendet man `box-sizing:border-box` behebt das das Problem entgegen der Erwartung auch nicht ;). Hier sollten `100%` ja dann die Breite der `border-box` sein, ist es aber dann - zumindest bei `text-indent`, nicht.

Aus dem FireBug ticket lese ich jetzt allerdings auch nicht heraus, was nun für richtig befunden wird...

**Comment by BugBuster1701** [comment]
Betrifft auch Linux Firefox, die `text-indent:4em;` Angabe bringt jedoch keine Besserung.

**Comment by leofeyer** [comment]
@BugBuster1701 Ich hab leider kein Linux Firefox, daher kann ich das schlecht debuggen. Versuch mal ob `100px` funktioniert.

**Comment by BugBuster1701** [comment]
ok, funktioniert beides, 4em und 100px.

**Comment by leofeyer** [comment]
Behoben in 1dfcb763a469b5acfcb0d64a5b4c8b3f03922e8f. Getestet in Chrome, Firefox und Safari.

**Comment by MacKP** [comment]
Da bin ich leider etwas zu spät... (und hab auch noch im falschen repro gesucht...).
Wenn das ganze auch noch Barrierefrei sein soll, dann wäre es eigentlich besser, des Wort nicht aus dem Viewport zu schieben.
Aktuell würde die Information komplett verschwinden, wenn man die Hintergrundfarbe vom Browser einstellt (siehe Bild).
Um das nachzustellen: Firefox > Einstellungen > Inhalt > Farben > Hintergrundfarbe (egal welche) einstellen und dann 'Oben ausgewählte Farben anstatt der Farben der Seite verwenden' auf 'Immer' einstellen.
Deswegen sollten solche Elemente entweder immer mit Text angezeigt werden (ist ja auch bei der Mobilen Ansicht so) oder direkt als richtiges Image per img-Tag eingebunden werden.

Viele Grüße
![contao-be_ff_hg_custom](https://user-images.githubusercontent.com/1241811/30952425-22d41f0c-a428-11e7-82cd-13e8231b3aaf.png)

**Comment by leofeyer** [comment]
Bei einem richtigen img-Tag kann ich aber nicht sagen, dass ich bei der mobilen Ansicht den Text anzeigen möchte.

**Comment by MacKP** [comment]
Ja, kann sein das es dann einfacher ist, den Text auch noch mal zu kapseln und dann mit li img und li .text das ganze jeweils anzusprechen. 
Wobei ich eigentlich dafür wäre immer Bild und Text bzw. dann nur Text, wenn es mit Bild zu viel wird. Dann brauch da auch nichts angepasst werden.

Viele Grüße
