### ISSUE TITLE
What an improvement ...

### ISSUE THREAD

**Issue by Seefahrer** [contao/core-bundle#1084]
Could I pls get back the nice BE theme of C4.4.4, what I've got now is horrifying ...\
![bildschirmfoto 2017-09-18](https://user-images.githubusercontent.com/12233592/30541275-f2cc8498-9c7a-11e7-8e20-eefeba63ef93.png)

**Comment by Seefahrer** [comment]
I've tried to restore the former (4.4.4) condition by simply copying the 4.4.4 flexible theme into the 4.4.5 installation, unfortunately -despite clearing ALL caches incl. rm -rf prod- I cannot get rid of this terrifying desaster ...

**Comment by leofeyer** [comment]
You have to clear the browser cache. This is obviously not correct (see the online demo).

**Comment by Seefahrer** [comment]
As I said before: I did clear all caches, also the browser cache, what else I could do more?
