### ISSUE TITLE
XML-Sitemap and german umlauts in page-alias

### ISSUE THREAD

**Issue by rustykowski** [contao/core-bundle#1085]
Bei automatischer Alias-Erzeugung aus dem Seitennamen werden deutsche Umlaute nicht mehr umgwandelt, da Umlaute offenbar für Browser kein Problem darstellen.
Bei der Erzeugung der XML-Sitemap entsteht aber ein Kodierungsfehler, der zur Ausgabe von fehlerhaften URLs führt, die bei Aufruf zu einem 404-Fehler führen.
Die Suchmaschine (mod_search) gibt ebenfalls kodierte URLs aus, macht dabei aber nicht diesen Fehler.

Hier 3 Beispiele (1. Umlaut / 2. mod_search / 3. XML-Sitemap)

veröffentlichungen
ver%C3%B6ffentlichungen
ver%25C3%25B6ffentlichungen

Über uns
%C3%BCber-uns
%25C3%25BCber-uns

führungsrolle
f%C3%BChrungsrolle
f%25C3%25BChrungsrolle

Das Fehlermuster besteht also in überflüssigen Zeichen "25" nach jedem "%".

**Comment by leofeyer** [comment]
Siehe 1096.

**Comment by leofeyer** [comment]
@ausi Müssen wir die URLs in der Sitemap denn überhaupt noch enkodieren? Wenn die Browser `veröffentlichungen.html` verarbeiten können, kann es Google dann in der `sitemap.xml` nicht auch?

**Comment by leofeyer** [comment]
Siehe #1095.
