### ISSUE TITLE
Minimum password length for password widget

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/core-bundle#1086]
Hi,
I tried to change the minimum password length for the password widget. First I changed the 'minlength' value via DCA, but this option doesn't work since the Validator of the Widget checks for the minlength from Config.

`if (Utf8::strlen($varInput) < \Config::get('minPasswordLength'))`

Is their a possibility to change the check to eval 'minlength' or if not set to minlength from config? Or does I misunderstand something?

**Comment by Toflar** [comment]
Unfortunately not but a pull request fixing this would be very welcome :)

**Comment by daniel-nemeth** [comment]
I hope this will work since I'm a noob with Github :)

**Comment by Toflar** [comment]
So you'll learn something new. Apparently you only forked and changed the code, now you have to submit a PR so we can comment on it :) Have a look at https://help.github.com/articles/creating-a-pull-request/ :)

**Comment by daniel-nemeth** [comment]
https://github.com/contao/core-bundle/pull/1087
Is this not working?

**Comment by Toflar** [comment]
Ah sorry, you could've linked it directly then I would've noticed :) Cool, as every PR is essentially an issue too, you can close this one in favour of the PR :)

**Comment by daniel-nemeth** [comment]
Ok thanks for your help!
