### ISSUE TITLE
Querscroll im BE

### ISSUE THREAD

**Issue by squidi** [contao/core-bundle#1091]
Unschöner Querscroll durch negativen Margin für #tmenu a,#tmenu h2 in main.css

![bildschirmfoto 2017-09-19 um 14 04 44](https://user-images.githubusercontent.com/488443/30591807-9ac68b5c-9d44-11e7-85c6-ffb844008dc0.png)

![bildschirmfoto 2017-09-19 um 14 05 44](https://user-images.githubusercontent.com/488443/30591820-a59debf6-9d44-11e7-9758-7b3dff433777.png)

**Comment by leofeyer** [comment]
Ich schau mal, ob das `margin-left:-4px` weg kann. Falls nicht würde es auch reichen, das `padding-right:3px` auf `padding-right:4px` zu erhöhen.

**Comment by squidi** [comment]
für #tmenu -> padding-right:3px auf padding-right:4px

![bildschirmfoto 2017-09-21 um 19 45 14](https://user-images.githubusercontent.com/488443/30710384-ada79faa-9f05-11e7-8eee-ac34f25694d5.png)

**Comment by leofeyer** [comment]
Behoben in 0054f8aba57e7383bf8450049f9a48212bbcfc65.
