### ISSUE TITLE
DropZone Upload im Inhaltselement

### ISSUE THREAD

**Issue by pointout** [contao/core-bundle#1092]
Wenn ich eine Datei in der Dateiverwaltung hochlade, geht die per Drag and Drop mit dem DropZone Uploader ("Hier klicken oder Dateien ablegen").
Will ich es direkt aus dem Inhaltselement machen (Bild hinzufügen-Quelldatei auswählen-Datei hochladen) funtioniert das nicht. Das Formular bietet sowohl den Durchsuchen-Button als auch das Dropfeld an (siehe Screenshot). "Hier klicken oder Dateien ablegen" geht hier aber nicht. Getestet in Firefox un Chrome.

![contaofileupload](https://user-images.githubusercontent.com/8960545/30611789-bdf98e38-9d82-11e7-8be0-baa830081391.JPG)

**Comment by fritzmg** [comment]
I can confirm the issue.

**Comment by leofeyer** [comment]
Das ist bisher auch kein unterstützter Anwendungsfall. Gibt es eine Fehlermeldung?

**Comment by aschempp** [comment]
@leofeyer es geht um den Picker. Im Picker funktioniert Dropzone nicht. Sollte durch den Pull Request von @ausi behoben sein, wäre aber zu testen.

**Comment by leofeyer** [comment]
Ah, mein Fehler. Ich denke allerdings nicht, dass @ausi's PR das abdeckt (Du beziehst Dich auf #1093, oder?).

**Comment by leofeyer** [comment]
Ja, wurde durch @ausi's PR behoben.
