### ISSUE TITLE
4.4.5: Backend-Theme > Breite begrenzen

### ISSUE THREAD

**Issue by christian-schattat** [contao/core-bundle#1097]
Die Option _Benutzerprofil > Backend-Theme > Breite begrenzen_ funktioniert nicht mehr. Bei Contao 4.4.4 konnte das Backend noch die volle Breite nutzen.

![bildschirmfoto 2017-09-18 um 15 23 21](https://user-images.githubusercontent.com/10039087/30648837-41d0efde-9e1f-11e7-8c6e-e0146df065a0.png)

Jetzt erscheinen auch bei deaktivierter Checkbox "4:3-Balken" an den Rändern.

![bildschirmfoto 2017-09-18 um 15 32 11](https://user-images.githubusercontent.com/10039087/30648853-4bb50602-9e1f-11e7-8239-0c9e909565b4.png)

Ich bin nicht sicher, ob es sich um einen Fehler oder um eine bewusste Änderung handelt. Bei Backend-Modulen mit mehreren Spalten in der Übersicht war die volle Breite sehr übersichtlich und deshalb hoffe ich auf einen Fehler. ;-)

**Comment by asaage** [comment]
https://github.com/contao/core-bundle/issues/1082

**Comment by leofeyer** [comment]
Wie lässt sich das in der Onlinedemo reproduzieren?

**Comment by fritzmg** [comment]
Duplicate of #1082. The change was deliberate.

**Comment by christian-schattat** [comment]
Zunächst einmal Entschuldigung dafür, dass ich das Thema nicht in den geschlossenen Tickets gesucht habe.

In der Online-Demo lässt sich nur noch das aktuelle Verhalten reproduzieren. Bei begrenzter Breite erscheinen erwartungsgemäss die Balken am linken und rechten Rand mit zentriertem Backend.

![breite begrenzt](https://user-images.githubusercontent.com/10039087/30651326-a95a2f02-9e25-11e7-8252-e4e848850124.png)

Zu meinem Bedauern ist das nun aber auch der Fall, wenn ich die Backend-Breite nicht begrenze (inaktive Checkbox):

![breite nicht begrenzt](https://user-images.githubusercontent.com/10039087/30651458-0bedc610-9e26-11e7-9073-0548f09d501e.png)

In Contao 4.4.4 konnte die volle Browserbreite verwendet werden. Das kam auch bei meinen Kunden gut an und ich traue mich gar nicht, dort jetzt auf 4.4.5 zu aktualisieren. ;-)

**Comment by leofeyer** [comment]
Das haben wir geändert. Das Backend wird nicht breiter als 1.400 Pixel (wird in der 4.4.6 auf 1.440 Pixel erweitert), weil die Mauswege sonst zu lang werden. Die Diskussion dazu findest Du in #1082 und den dort verlinkten Tickets.
