### ISSUE TITLE
Level der Überschrift vom vorangegangenen Element übernehmen

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#1098]
Pflegt man einen Artikel und setzt mehrere Überschriften, so ist standardmäßig immer das Level H1 ausgewählt. Es wäre meiner Meinung nach eine Erleichterung, wenn standardmäßig immer das vorausgegangene Level gesetzt wird.

Bsp:
1. CE mit Inhaltselement Text Überschrift H3
2. CE ohne Überschrift
3. Beim Anlegen eines neuen Elements, sollte nun H3 ausgewählt werden. Level von 2. wird ignoriert.

**Comment by leofeyer** [comment]
Das halte ich aus mehreren Gründen für problematisch. Erstens müsste man immer alle vorherigen Elemente durchgehen und zweitens wäre das kontraproduktiv für alle, die HTML5 Sections nutzen.

**Comment by asaage** [comment]
Die Idee finde ich vom Prinzip nicht schlecht - aber ich bezweifel, dass das optimale Hierarchien erzeugt.
Bei einigen Projekten habe ich das so gelöst:
- für h1 den Artikel-titel genutzt und ins Article-template codiert
- für neue Contentelemente die default-einstellung (h1) auf h2 geändert mit dcaconfig: ```
$GLOBALS['TL_DCA']['tl_content']['fields']['headline']['default'] = array('unit' => 'h2', 'value' => '');```

**Comment by frontendschlampe** [comment]
Also wir kennen doch alle unsere Kunden und wenn der Kunde 10 h1-Headlines haben will, dann macht er das - spätestens dann, wenn er seinen Zugang zum System hat.

Wir als Webdesigner sind außerdem nicht für die richtige Nutzung von Headlines oder anderen Auszeichnungen zuständig. Das wäre ja des selbe mit Listen: der Redakteur mach eine Aufzählung und nutzt dafür aber nicht eine ul (weil er keine Lust hat oder nicht dran denkt), sondern macht das schön manuell mit - und Leerzeichen.

Des weiteren wird das natürlich sehr problematisch, wenn man mehrere Artikel benutzt, denn dann müsste ich dort prüfen, welche Überschriften im vorangegangenen Artikel genutzt werden.

**Comment by asaage** [comment]
>immer das vorausgegangene Level

So wie ich das verstanden hab geht's @dmolineus ja auch nicht darum korrekte Hierarchien zu erzeugen sondern darum, dass die Vorbelegung h1-h6 historisch begründet wird - sprich das, was zuletzt verwendet wurde (egal ob das im gleichen Artikel, einer News oder einem Event war).

**Comment by frontendschlampe** [comment]
ich habe das schon verstanden, aber was ist da der Sinn dran? Das passt doch in den meisten Fällen so oder so nicht und ich muss auf jeden Fall wieder ein Überschriftsgrad auswählen. Also kann man es ja direkt lassen.

**Comment by dmolineus** [comment]
> Das halte ich aus mehreren Gründen für problematisch. Erstens müsste man immer alle vorherigen Elemente durchgehen und zweitens wäre das kontraproduktiv für alle, die HTML5 Sections nutzen.

Zu ersterem: Nein, es würde ausreichen das Element zu laden, wo der Wert der Headline-Spalte länger ist als das serialisierte Feld für eine leere Überschrift

Zu letzterem: Für die ist die Standardoption dann auch nicht immer hilfreich

> Wir als Webdesigner sind außerdem nicht für die richtige Nutzung von Headlines oder anderen Auszeichnungen zuständig. Das wäre ja des selbe mit Listen: der Redakteur mach eine Aufzählung und nutzt dafür aber nicht eine ul (weil er keine Lust hat oder nicht dran denkt), sondern macht das schön manuell mit - und Leerzeichen.

In dem Fall sehe ich es als Arbeitserleichterung für alle an. Dass die Redakteure den Sinn verstehen müssen, schon klar.

> Des weiteren wird das natürlich sehr problematisch, wenn man mehrere Artikel benutzt, denn dann müsste ich dort prüfen, welche Überschriften im vorangegangenen Artikel genutzt werden.

Man muss es ja nicht übertreiben. Eine Überprüfung pro Artikel/News/Event reicht ja schon.

> ich habe das schon verstanden, aber was ist da der Sinn dran? Das passt doch in den meisten Fällen so oder so nicht und ich muss auf jeden Fall wieder ein Überschriftsgrad auswählen. Also kann man es ja direkt lassen.

Wenn man Überschriften auf einer Seite setzt, weicht diese im Normalfall ein Level ab oder bleibt. Eine Voreinstellung auf das historische Level erleichtert die Datenpflege mit der Tastatur. Überschrift eingeben, Tabulator und bei Bedarf Pfeil nach oben oder unten.

Wenn es die Mehrheit nicht als hilfreich empfindet, kein Problem. Hab gerade ein Projekt, das textlastig ist und fand es da sehr hilfreich.

**Comment by frontendschlampe** [comment]
> Man muss es ja nicht übertreiben. Eine Überprüfung pro Artikel/News/Event reicht ja schon.

aber genau da sehe ich ja das Problem: man baut ein Feature ein, was nur halb funktioniert. Dann kann man es auch weglassen. Wenn man sowas einbaut, dann müsste er ja alle Elemente auf der Seite berücksichtigen und das ist nicht möglich.

**Comment by aschempp** [comment]
Totally agree with @frontendschlampe

**Comment by fritzmg** [comment]
Imho muss das doch einfach nur in der Session gespeichert werden.

**Comment by asaage** [comment]
> einfach nur in der Session gespeichert 

So hatte ich mir das auch gedacht.

**Comment by leofeyer** [comment]
Wie am 5. Oktober in Mumble besprochen, halten wir das für nicht machbar. 

Eine mögliche Verbesserung wäre es eventuell, wenn wir das Überschrift-Level standardmäßig gar nicht setzen, so dass man explizit wählen muss (weil sonst eine Fehlermeldung kommt). Die Lösung ersetzt jedoch nicht das benötigten Verständnis des Benutzers, welches Level für welche Überschrift zu verwenden ist.

**Comment by leofeyer** [comment]
Implementiert in aeec95dcb3b1c23157c397efb4c44719555dbd0a.

**Comment by tsarma** [comment]
Wow cool, something I was doing from long time ago now comes out of box. Didn't saw this until today when I am updating my old modules. Thank you. 👍
