### ISSUE TITLE
Contao Enterprise

### ISSUE THREAD

**Issue by x-christian-romeni** [contao/core-bundle#1100]
I'm not sure if this is the right repo to make such a feature request... So I'll just go along:

I have taken a look around the CMS Scene and noticed that many, who are aiming to be Professional CMS, are also targeting the Enterprise Sector.

This is somehow missing in Contao. Contao is targeting private persons, small to medium businesses, but seems to have no chance to reach large companies or the upper "Mittelstand".

Most of them are now getting their websites up to date, looking for ways to integrate them with their IT Strategies, Publishing Workflows, etc.

One aspect is that more and more they start to add content in a more editorially manner. They might have PR Companies delivering content or working directly in the CMS. So there is a demand for some kind of workflow.

I was wondering which direction will Contao take?

My thought is, there should be a Enterprise Version.
It is the default Contao Standard Edition with all that we currently have in Contao, but added a few Modules that are developed by a Contao Enterprise Team.
These features are purely designed for Enterprise Customers. Like AD user integration, Publishing Workflows, etc.
The Enterprise Version will cost a one-time fee for all major versions and additional support bundles.

Off course I know that there would have to be some significant changes in the Contao Structure or the "Contao Company". I guess a Contao Enterprise GmbH or something like that, with own developers would be the right way, and maybe a strategy that will take Contao the next step in becoming the one, the only, best CMS.

I'm just guessing, but maybe these features will also open the US market. Where Contao is currently not successful at all.

Lets take some awesome steps together towards a bright Contao Future!

**Comment by leofeyer** [comment]
Please move this discussion to the [forums](https://community.contao.org/).
