### ISSUE TITLE
tl_class in DCA-Eval-Array produces overlapping with fileTree

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1101]
Hello,

both of the fields in the screenshot have set ```'tl_class' => 'w50'```. The lower one has also ```clr``` set:

![screen](https://user-images.githubusercontent.com/1485098/30798622-96e3adf4-a1da-11e7-8119-85bc67102cdb.png)

Thanks in advance.

Bye

**Comment by Toflar** [comment]
Add `autoheight` to your file tree.

**Comment by Defcon0** [comment]
Ah, I see. Now it works, thanks.
