### ISSUE TITLE
Prefix global functions

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1103]
We should enable the `NativeFunctionInvocationFixer` in the php-cs-fixer in the develop branch so all our global functions are prefixed by `\`. So instead of using e.g. `is_object()` we should use `\is_object()`. This will give us quite a performance boost because for global functions, the PHP engine can trigger additional optimizations when using opcode. E.g. if we use `\in_array()` with `true` as third parameter and the array is static, it doesn't have to evaluate over and over again but instead opcode will cache the result.
I didn't test it at all but I expect some pretty notable performance gains.

More info: https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/

**Comment by leofeyer** [comment]
It seems that PhpStorm supports both ways of "fixing" this: https://blog.jetbrains.com/phpstorm/2017/01/phpstorm-2017-1-eap-171-2455/

Do you prefer adding a `use` statement or prefixing every method call with `\`? Both will be tedious to implement.

**Comment by ausi** [comment]
AFAIK this optimization is only relevant for a subset of native PHP functions, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-328810072 and https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3048#issuecomment-330137157

IMO we should only activate `NativeFunctionInvocationFixer` for these methods once the fixer has an option to do so (FriendsOfPHP/PHP-CS-Fixer#3048)

**Comment by Toflar** [comment]
Yes, I was just about to comment the same. Let's wait for a decision there and use the fixer like we already do now.

**Comment by leofeyer** [comment]
I have prefixed our function calls manually with an adjusted version of the fixer in 941b81d5eed7c9e110a4f1ade822c2527af38919. I'll leave the ticket open until the fixer has been adjusted.

I haven't changed the legacy code, although there are a lot of function calls in it as well. How do we handle this?
