### ISSUE TITLE
Feature: Add pictures into the TinyMCE text field per Drag and Drop

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1108]
It would be great to improve the user experience with the possibility to add pictures into the TinyMCE text field per Drag and Drop. The picture could be saved automatically in a special order (e.g. with date like in WordPress?)

After loading of the picture the user could have the possibility to add the meta informations, to change the file name or to choose the visible area. But I think it should be more generally easier and quicker than now.

**Comment by leofeyer** [comment]
We are not the TinyMCE developers. Please request the feature here: https://github.com/tinymce/tinymce
