### ISSUE TITLE
Feature: Icon for file upload next to each folder

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1109]
We could have an icon for the file upload next to each folder. Then we would't need to click on arrow. Also it could be a big user experience improvement to add files per _drag & drop_ over a folder. In this case the loading process would start automatically.

**Comment by leofeyer** [comment]
We already have (Contao 3 and 4).

<img width="786" alt="" src="https://user-images.githubusercontent.com/1192057/30869839-7dec2d2c-a2e2-11e7-91cb-e8e44aaad31d.png">

**Comment by jankout** [comment]
sorry

**Comment by jankout** [comment]
But there is still something new. 

_Also it could be a big user experience improvement to add files per drag & drop over a folder. In this case the loading process would start automatically._
