### ISSUE TITLE
Failed to load TinyMCE

### ISSUE THREAD

**Issue by sepp21** [contao/core-bundle#1110]
Der TinyMCE-Editor erscheint im Backend nicht. Die Konsole weist folgende Fehlermeldung aus:

"Failed to load: https://domain.com/assets/tinymce4/js/tinymce.gzip.php?js=true&plugins=autosave,charmap,code,fullscreen,image,importcss,link,lists,paste,searchreplace,tabfocus,table,visualblocks&themes=modern&languages=de"

Installation:
Contao 4.4.5 über Contao-Manager installiert
Ordnerstruktur wurde beachtet html/CMS/web

Server:
PHP Version 7.0.10
HTTP_ACCEPT_ENCODING | gzip, deflate
gzip compression | enabled

**Comment by leofeyer** [comment]
Tritt das Problem in der Onlinedemo auch auf?

**Comment by sepp21** [comment]
Nein dort tritt das Problem nicht auf!
Problem tritt auch browserunabhängig auf.

**Comment by leofeyer** [comment]
Dann liegt der Fehler nicht bei Contao.
