### ISSUE TITLE
C4.4.5: Navigationsbuttons in j_colorbox bei hover fehlerhaft 

### ISSUE THREAD

**Issue by mpunkt** [contao/core-bundle#1111]
Das Problem tritt auf, wenn die Komponente Formulare aus dem CSS-Framework aktiviert ist. Ursache scheint die Zeile 119 `background-position:0 -15px !important;` in forms.css. Das Problem ist auf der Demoseite reproduzierbar.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core/issues/8747 » https://github.com/contao-components/contao/pull/8
