### ISSUE TITLE
default language for meta data in file manager

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1112]
In Contao 4, the default language for the meta data form in the file manager is not the user's back end language anymore, like it used to be in Contao 3.

### Reproduction

1. Create a website root for the language `en`.
2. Create a website root for the language `ar`.
3. Set the back end language for your back end user to _English_.
4. Upload a file and edit its meta info.

The preselected language for the meta info will be _Arabic - العربية_ instead of _English_.

**Comment by DanielSchwiperich** [comment]
Can confirm, it's using the first configured language from the alphabetic order

**Comment by leofeyer** [comment]
Fixed in d160150ad94fa02285d35c4228f9605add9c1f15.
