### ISSUE TITLE
Update length of tl_member and tl_user.password

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1113]
According to the [PHP documentation][1], our password fields should have a length of 255:

> PASSWORD_DEFAULT - Use the bcrypt algorithm (default as of PHP 5.5.0). Note that this constant is designed to change over time as new and stronger algorithms are added to PHP. For that reason, the length of the result from using this identifier can change over time. Therefore, it is recommended to store the result in a database column that can expand beyond 60 characters (255 characters would be a good choice).

Currently, bcrypt uses 60 characters but PHP 7.2 is around the corner and will use `Argon2i` as default algorithm which generates 96 character long hashes. That would still work out for us but I guess we should follow the recommendation and increase the lenghts to 255.

Happy we did that change to `password_hash` back in 3.4 because as of PHP 7.2 Contao automatically gets one of the strongest password hashing algorithms in the world 🎉 

Note: We should check if our `Encryption::test()` also recognizes the new algorithm when upgrading old sha1 hashed passwords.

[1]: http://php.net/password_hash

**Comment by leofeyer** [comment]
Changed in 187427b9187857392110c13472cd6e055366b754.
