### ISSUE TITLE
junctioned bundles on windows cause errors

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1114]
If you junction a local repository via
```
"repositories": [
    {
        "type": "path",
        "url": "C:\\Path\\To\\Repo\\contao-foo"
    }
]
```
and this repository contains its own template files for example, then the following error will occur, if you go to _Layout_ » _Templates_ » __New template__ in the back end:
```
InvalidArgumentException:
Path "C:\Path\To\Repo\contao-foo\src/Resources/contao/templates\ce_foo.html5" is not inside the Contao root dir

  at vendor\contao\core-bundle\src\Resources\contao\library\Contao\StringUtil.php:1145
  at Contao\StringUtil::stripRootDir('C:\\Path\\To\\Repo\\contao-foo\\src/Resources/contao/templates\\ce_foo.html5')
     (vendor\contao\core-bundle\src\Resources\contao\dca\tl_templates.php:249)
  at tl_templates->addNewTemplate(object(DC_Folder))
     (vendor\contao\core-bundle\src\Resources\contao\classes\Backend.php:437)
  at Contao\Backend->getBackendModule('tpl_editor', null)
     (vendor\contao\core-bundle\src\Resources\contao\controllers\BackendMain.php:131)
  at Contao\BackendMain->run()
     (vendor\contao\core-bundle\src\Controller\BackendController.php:55)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
  at call_user_func_array(array(object(BackendController), 'mainAction'), array())
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:171)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web\app_dev.php:62)
```

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
Could you please try if the error also occurs if you add the following configuration:

```json
"repositories": [
    {
        "type": "path",
        "url": "C:\\Path\\To\\Repo\\contao-foo",
        "options": {
            "symlink": false
        }
    }
]
```

**Comment by fritzmg** [comment]
This works of course, since composer then copies the files. However, that's not really what I want while developing a bundle.

**Comment by aschempp** [comment]
I'm very much unsure if we can and should support this. There are tons of horrible issues with symlinked packages anyway that we can't solve (e.g. impossible to find relative paths to Contao), so we can't really support this anway…

**Comment by fritzmg** [comment]
The reason I am doing is because I though this is the best practice way of developing packages/bundles/extensions. @discordier also recommended it on the community forum.

@ausi and @Toflar showed me another way in IRC - by requiring the package via --prefer-source, and developing it directly in the vendor folder. However this has its downsides too.

I haven't come across any other issues with symlinking packages this way into a symfony applications. The fatal error when trying to create a new template via the back end is the only one so far.

**Comment by leofeyer** [comment]
> @ausi and @Toflar showed me another way in IRC - by requiring the package via `--prefer-source`, and developing it directly in the vendor folder. However this seems to have its downsides too.

This is how I do it, too. I have tried the other setup as well, but it was just too cumbersome.

**Comment by stefanschleich** [comment]
I just came across this issue too. Could you give me and the other users stumbling upon this a little how to on developing bundles inside the vendor folder? Thanks.

**Comment by leofeyer** [comment]
You only need to require it in your `composer.json` file:

```json
{
    "require": {
        "vendor/package": "dev-master",
    },
    "config": {
        "preferred-install": {
            "vendor/": "source",
            "*": "dist"
        }
    }
}
```

If your bundle is in a private repo, you might have to add this as well (see [here](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)).

**Comment by fritzmg** [comment]
This has actually been fixed meanwhile? At least I cannot reproduce it any more when composer creates a junction for repositories that are referenced like this.
