### ISSUE TITLE
Problem mit eigenen Layoutbereichen

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#1115]
Ich habe gerade ein komisches Verhalten bei den eigenen Layoutbereichen festgestellt. Es werden auch leere Layoutbereiche ausgegeben, wenn nur ein Layoutbereich gefüllt ist. Wenn gar keiner gefüllt ist, wird auch keiner ausgegeben.

Zum Nachstellen in der Onlinedemo:

Im Backend:

- in einem Layout 2 Layoutbereiche *nachdemheader* und *vordemfooter* anlegen
- unter *eingebundene Module* Artikel zuweisen

Im Frontend:

- entsprechende Seite mit dem Layout aufrufen und feststellen, dass kein eigener Layoutbereich ausgegeben wird. Dieses Verhalten ist auch **korrekt**, da ja kein Inhalt vorhanden ist.

Im Backend:

- unter *Artikel* auf der entsprechenden Seite einen Artikel im Layoutbereich *nachdemheader* anlegen und ein CE Text mit beliebigen Text anlegen.

Im Frontend:

- entsprechende Seite aufrufen und feststellen, dass zwar wie gewünscht der Layoutbereich *nachdemheader* mit dem gewünschten Text ausgegeben wird, aber auch der Layoutbereich *vordemfooter* auftaucht, obwohl dieser leer ist (beinhaltet nur verschiedene ```div``` aus dem Template. Und dieses Verhalten ist **falsch**! Sobald ein eigener Layoutbereich befüllt ist, werden alle anderen eigenen Layoutbereiche ebenfalls ausgegeben, obwohl sie leer sind.

Des weiteren wundere ich mich, wo das ```div.custom``` herkommt. Dieser ```div.custom``` ist vollkommen überflüssig und sollte (wenn überhaupt) im Template ```block_section.html5``` stehen

**Comment by leofeyer** [comment]
Welche Contao-Version betrifft das?

**Comment by frontendschlampe** [comment]
puuuh ... müsste C3 und auch C4 sein, aber ich kann es gern nochmal testen.

**Comment by frontendschlampe** [comment]
soeben, wie oben beschrieben in der Contao Demo nochmals probiert und es lässt sich genau so nachstellen.

Mal abgesehen von diesem Problem, sollte eigentlich nie was ausgegeben werden, wenn nichts gerendert wird. Wenn der Artikel sichtbar ist, aber keinen Inhalt hat, wird er trotzdem ausgegeben.

**Comment by leofeyer** [comment]
Behoben in 42ad2c47d4c0c4d6f6c4d45f0d756cd03e683bcd.

**Comment by kubjo** [comment]
Ich verwende zwei eigene  Layoutbereiche, der erste beinhaltet die Navigation, alles OK! Der zweite soll einfach leer sein und dadurch, dass ich ihn transparent mache, scheint ein Hintergrundbild durch, das dann "überscrollt" wird. Hier funtkioniert es noch (4.5.6): [http://www.fotografeninnung-stuttgart.de/](http://www.fotografeninnung-stuttgart.de/ ) 
Hier leider nicht mehr: [https://www.wernerottens.de/](https://www.wernerottens.de/)
Es wäre schon sinnvoll, wenn man Bereiche auch leer lassen könnte.

**Comment by kubjo** [comment]
@fritzmg Diese Lösung erscheint mir ein wenig "mit Kanonen nach Spatzen geschossen", ein einfaches Leerzeichen als html-code hat es auch getan ;-).  Das reicht mir jetzt mal für's Erste.
