### ISSUE TITLE
Back button in back end redirects to "wrong" page

### ISSUE THREAD

**Issue by bezin** [contao/core-bundle#1117]
Hi there, 

while working with Contao 4.4 I experienced one unexpected redirect in the back end that I would like to discuss. To reproduce on demo.contao.org:

1. Duplicate an article in the backend, e.g. "Content Elements" on the corresponding page. 
2. Insert the duplicate after the original.
3. Save and Edit
4. Edit first text element and click "Save and Close".

If you click on the back button now, you will be redirected to the back end frontpage, but would one not expect to be redirected to the articles page?

If you skip step 4 and click the back button in step 3, it does exactly that.

Cheers
Benedict

**Comment by fritzmg** [comment]
It's an ongoing issue that still has not been resolved completely: https://github.com/contao/core/issues/6127

**Comment by leofeyer** [comment]
Can you please replace https://github.com/contao/core-bundle/blob/master/src/EventListener/StoreRefererListener.php#L151 with

```php
$referers[$refererId] = end($referers);
```

and see if it has any ramifications?

@contao/developers /cc

**Comment by bezin** [comment]
I did replace this line and I have not had any unexpected side effects so far.

**Comment by leofeyer** [comment]
Fixed in 8654dafb076998d90a7abc50b4f95474e65f57c5.
