### ISSUE TITLE
Webfonts im Backend werden doppelt geladen

### ISSUE THREAD

**Issue by stefanschleich** [contao/core-bundle#1118]
Die Schrift 'Lato Retina' wird mit ihren einzelnen Schnitten mehrfach geladen, wenn ich eine Seite im Backend aufruft, so werden allein 1.2. MB nur für die Fonts transferiert. Beim Öffnen oder Neuladen einer Seite im Backend laden die Fonts zum ersten mal recht zügig, dann verschwinden kurz alle Textelemente für ca. 1 Sekunde, dann erscheinen Sie wieder.

Hier ein Screenshot aus Chrome:

<img width="1171" alt="contao-4 4 5 -backend-webfonts" src="https://user-images.githubusercontent.com/1949608/31038531-a4f02ef4-a577-11e7-9e13-13e69e9f730c.png">

Das Problem tritt auf mit Contao 4.4.5. in der Managed Edition mit Chrome 60 unter OS X El Capitan auf einem Retina MacBook.

**Comment by leofeyer** [comment]
Ich kann das Problem in der Onlinedemo nicht reproduzieren (Chrome 61.0.3163.100 auf macOS 10.13).

**Comment by websolutions-hamburg** [comment]
Ich glaube das doppelte Laden passiert nur wenn der TinyMce Editor geladen wird. Ich kann das Verhalten in der Onlinedemo reproduzieren. Aber nur wenn ich zum Beispiel die Artikeleinstellungen bearbeite.

**Comment by leofeyer** [comment]
Die Dateien werden in diesem Fall natürlich zweimal geladen, da der TinyMCE in einem Iframe läuft und die Fonts in diesem ebenfalls benötigt werden. Kannst Du Dir bitte mal die vollständigen URLs ansehen? Die Fonts müssten einmal aus `system/themes/flexible/fonts` kommen und einmal aus `assets/tinymce4/js/skins/contao/fonts`.

**Comment by websolutions-hamburg** [comment]
@leofeyer da hast du absolut Recht. Ich kann bestätigen das die Fonts aus den beiden verschiedenen Verzeichnissen geladen werden. Was bei dem TinyMCE im iFrame ja auch logisch ist.

**Comment by leofeyer** [comment]
Ich habe das Font-Loading in contao-components/tinymce4@bf0b07577de5cf1023b5bad837fde363fe522565 insofern optimiert, als dass TinyMCE selbst jetzt nicht nochmal irgendwelche Fonts lädt. Da wir eine eigene Skin namens `contao` haben, können wir wohl annehmen, dass der Editor im Contao-Kontext läuft, in dem die Webfonts bereits vorhanden sind.

Das zweite Laden der Fonts innerhalb des Iframes bleibt jedoch wie oben geschrieben notwendig.
