### ISSUE TITLE
Show predefined dimensions on top

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#1119]
Hello,

is it possible to show the predefined dimensions for the image size on top? And relative and exact dimensions after the predefined.
If I create predefined dimensions, then they will be more important than default dimensions. And the editors shall they use. But all the time, the editors must scroll down to reach the predefined dimensions.

![image](https://user-images.githubusercontent.com/26099903/31059938-f46b70a4-a709-11e7-8e0a-3391697e7d74.png)

**Comment by leofeyer** [comment]
Changed in 10049d96745bb3eeb414ef58551158c0f2c38737.
