### ISSUE TITLE
Missing description example for the title tag in layout configuration

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#1120]
Hello,

in older Contao versions, e.q. 4.2, the description for the title tag, in the layout configuration, in german was:
> Hier können Sie das Title-Tag überschreiben (Standard: {{page::pageTitle}} - {{page::rootPageTitle}})

In the current Contao 4.4 version the description was shortened to:
> Hier können Sie ein individuelles Title-Tag setzen.

The old description was very helpful, because it already contained an example of how to build the title tag and also shown how does it works at the moment.
Is it possible to reinsert this help text, or has it been deliberately removed?

**Comment by fritzmg** [comment]
I too was wondering why this was removed.

**Comment by Toflar** [comment]
The translations are managed on transifex, so I don't know if that was even removed by @leofeyer or somebody else 😄

**Comment by xchs** [comment]
@Toflar See b3280fd9b020769968c46a2b1f7f1fcb2eeace60

**Comment by leofeyer** [comment]
See contao/core#8222.

**Comment by websolutions-hamburg** [comment]
@leofeyer I don't understand why you deleted the description for the **title tag**. The ticket https://github.com/contao/core/issues/8222 describes an issue with the **viewport tag**, but not with the title tag.
The wording and behavior for the title tag was right. Nothing was wrong on it.

Or do I overlook something?

**Comment by leofeyer** [comment]
We have changed it so we don't need to adjust the translations if the default value changes. Therefore I would like to keep it the way it is. We could add a placeholder attribute though:

<img width="535" alt="" src="https://user-images.githubusercontent.com/1192057/31177624-e2b8ed96-a916-11e7-8939-2e5c35782567.png">

**Comment by leofeyer** [comment]
Implemented in 95a9d5adac1d4b3ce3cd0ecf1c5e5c5773dc1781.
