### ISSUE TITLE
front end language affects back end login language

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1124]
1. Log into the Contao Online Demo.
2. Create a new website root with the language set to _French_ (`fr`).
3. Assign one of the page layouts to the French website root.
4. Create a new page with the alias `index` in the French website root.
5. Log out of the back end.
6. Go to https://demo.contao.org/fr/
7. Go to https://demo.contao.org/contao/login

The back end login is suddenly french.

I am not sure if this is a bug or feature. A customer of us was confused by this. They have a website with a lot of different languages and when they switch around in the front end to check the content, his back end login form suddenly changes to whatever language they visited last.

Imho only the `Accept-Language` should define which language the back end form should be by default. And/or there should be a selection.

**Comment by leofeyer** [comment]
This is due to the locale being stored in the session. We have overworked the locale handling in Contao 4.5 and I can confirm that it also fixes this issue.
