### ISSUE TITLE
Adjust the tagged services after updating to Symfony 3.4

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1131]
After updating to Symfony 3.4, we can remove the `PickerProviderPass` and the `FragmentRegistryPass` passes and inject the tagged services directly:

http://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services

**Comment by aschempp** [comment]
We sure still need `FragementRegistryPass` because it does way more on the tagged information.

**Comment by aschempp** [comment]
We sure still need `FragementRegistryPass` because it does way more on the tagged information.

**Comment by leofeyer** [comment]
Ok, I'm closing this one, as it would only apply to the `PickerProviderPass` and we would have to rework the class so the tagged services are passed as constructor argument (or in a new method). Not worth the effort IMHO.
