### ISSUE TITLE
4.4.x - Navigation: Umlaute werden nicht sauber umschrieben

### ISSUE THREAD

**Issue by Marchie1412** [contao/core-bundle#1132]
Bei Menüpunkten mit Umlauten wird der Alias nicht umschrieben. Ich weiß, dass inzwischen Unicode erlaubt ist und die URLs funktionieren ja auch. 
Aber: im Quellcode steht nämlich für einen Menüpunkt "Schlüsselnotdienst" jetzt `<a href="schl%C3%BCsselnotdienst.html" title="Schlüsselnotdienst" ....>`
Irgendwie nicht wirklich toll. Gibt es da eine Lösung?

**Comment by leofeyer** [comment]
Der Link sieht für mich richtig aus. Was genau stört Dich daran?

**Comment by Marchie1412** [comment]
"richtig" insofern dass er funzt. Aber nicht nur für Google wäre ein <a href="schlüsselnotdienst.html" ...> besser.

**Comment by fritzmg** [comment]
Für Google ist das egal ;)

**Comment by Marchie1412** [comment]
ist aber nicht wirklich sauber ...

**Comment by fritzmg** [comment]
Sauber ist das auf jeden Fall. In HTML5 aber tatsächlich nicht unbedingt notwendig. Dort können URLs Unicode Zeichen enthalten.

**Comment by Marchie1412** [comment]
OK, dann muss man halt jetzt die Aliase mit Umlaute selbst schreiben ....

**Comment by Marchie1412** [comment]
Die SEO-Leute mit denen ich zusammenarbeite, übrigens zertifizierte Google-Partner, sagen eindeutig, dass es nicht egal ist und zu verschiedenen Problemen u.a. in der Search Console führen kann. Die Umlaute sollten auf jeden Fall anders geschrieben werden.

**Comment by mlwebworker** [comment]
zertifizierte Google-Partner bezieht sich ja eher auf Adwords-Werbung und dieser Link https://www.seo-suedwest.de/1825-google-umlaute-encodierte-urls.html
widerspricht dieser Ansicht eindeutig

**Comment by Marchie1412** [comment]
Punkt 1 ist leider nicht der Fall und Punkt 2 spricht nur das geringere Übel an. Beides führt zu Problemen. Aber egal ... dann halt manuell :-(

**Comment by ausi** [comment]
[Google selbst verlangt](https://www.sitemaps.org/protocol.html#escaping), dass URLs in Sitemaps URL-escaped werden müssen. `schl%C3%BCsselnotdienst.html` ist die korrekte Schreibweise.

„zertifizierter Google-Partner“ bedeutet, dass man über $ 3.000,- Dollar pro Monat in AdWords investieren muss und dass ein Mitarbeiter die AdWords-Prüfung ablegen muss.

**Comment by Marchie1412** [comment]
Boah eh!!! Alles super nett hier ... :-(
Dass Google das selbst verlangt und damit auch Probleme macht ist bekannt: Ich poste jetzt einfach noch die Aussage meiner Fachleute hier rein und dann bin ich weg. Keine Lust auf so einen Schlagabtausch:

----- schnipp ----
Grundsätzlich empfehle ich nach wie vor Umlaute und Sonderzeichen in der URL zu vermeiden. Die Probleme sind auf langfristiger Sicht immens (auch wenn es im Browser erstmal funktioniert!).
Google macht selbst schon solche komische Umschreibungen, was zu Fehlern in z.B. der Search Console führt, und URLs, die eigentlich umgeleitet werden müssen, nicht umgeleitet werden können wgn. Inkompatibilität der verschiedenen Systeme und Datenbanken, wo URLs alles gespeichert werden.
---------- schnipp ----------

**Comment by ausi** [comment]
Liegt hierbei vielleicht ein Missverständnis vor?

Der letze Kommentar lässt vermuten dass die Schreibweise `<a href="schluesselnotdienst.html" ...>` mit `ue` anstatt `ü` gewünscht ist. Dabei wäre wir uns einig :) und es gibt auch bereits ein Ticket dazu: #1016.

**Comment by zonky2** [comment]
Google muss mehr Steuern zahlen - dann wirds was mit dem Sch%C3%BCsselnotdienst!

**Comment by CMSworker** [comment]
@Marchie1412 Es ist bereits ein Update #1016 in Vorbereitung, dass die automatische Umwandlung von Umlauten wie ü in ue ermöglicht, wie es bei Contao 3 der Fall war. Es kann aber noch einige Wochen dauern, bis das im Core integriert ist, da noch auf Änderungen in erforderlichen Abhängigkeiten gewartet wird. Oder habe ich das Anliegen falsch verstanden?

**Comment by Marchie1412** [comment]
#ausi danke. Ja ue ist besser als ü. Kommt dann wohl in 4.5. dann kann im besten Fall jeder so wie er es für richtig hält.

**Comment by leofeyer** [comment]
@ausi Können wir nicht unabhängig von den Änderungen in der 4.5 in

https://github.com/contao/core-bundle/blob/05295bf5a06101a5928c586d0d0cfb1985f92641/src/Resources/contao/modules/Module.php#L407

ein `rawurldecode()` hinzufügen? Dann wären die `href`s im Quelltext wieder lesbar.

**Comment by ausi** [comment]
Ich denke, dass `schl%C3%BCsselnotdienst.html` die korrekte Schreibweise ist, auch wenn `schlüsselnotdienst.html` erlaubt sein sollte.

Ein einfaches `rawurldecode()` würde auf jeden Fall zu Problemen führen mit Zeichen die in URLs nicht erlaubt sind.

**Comment by leofeyer** [comment]
Kann der Seitenalias denn überhaupt Zeichen enthalten, die in URLs nicht erlaubt sind?

**Comment by ausi** [comment]
Das weiß ich nicht. Aber der `$href` kann auch eine externe Weiterleitung sein, nicht nur ein Alias.

**Comment by leofeyer** [comment]
Das stimmt. Wir könnten das `rawurldecode()` natürlich nur in den Zeilen 366 und 370 anwenden.

**Comment by leofeyer** [comment]
Oder wie wäre es, wenn wir nur echte Unicode-Zeichen dekodieren?

```php
$strUrl = preg_replace_callback(
	'/(%[A-F0-9]{2}(?:%[A-F0-9]{2})+)/',
	function ($value) {
		return rawurldecode($value[0]);
	},
	$strUrl
);
```

**Comment by ausi** [comment]
Ich versteh den Sinn davon einfach nicht. Wir verwenden URLs überall URL-encoded, auch der HTTP-Standard erlaubt nur ASCII Zeichen. Warum sollten wir etwas einbauen was eventuell zu Problemen führen könnte?

Wir müssten den Browser-Support prüfen. Und auch alle relevanten Web-Crawler müssten Internationalized-URLs unterstützen damit wir das ändern können. IMO ist der Aufwand deutlich zu hoch und das „Feature“ hat für mich keinen Vorteil.

**Comment by leofeyer** [comment]
Ja, Du hast Recht. Dann schließe ich das Ticket mit dem Hinweis auf #1016 und #954.
