### ISSUE TITLE
Re #1132 - Umlaute im Alias

### ISSUE THREAD

**Issue by Seefahrer** [contao/core-bundle#1134]
Sorry, dass ich wieder auf diese Thema kommen muss, leider hab ich soeben festgestellt, dass mit den encoded URLs unter jQuery >=1.12.4 ein Problem auftritt:

Aktuell erstelle ich eine kleine Seite mit dem "wr/onepage-bundle". Ein Menüpunkt ist "Über mich", woraus von Contao der Alias "über-mich" generiert wird, encoded "%C3%BCber-mich". Diese Codierung führt dazu, dass im Smoothscroll-Script der Funktionsaufruf "document.getElementById(id)" den Return-Wert "Null" liefert. Vergebe ich von Hand den Alias "ueber-mich" läuft alles korrekt.

Sorry, falls ich mich nicht exakt gem. der Entwickler-Linguistik ausgedrückt haben sollte ...

**Comment by ausi** [comment]
In diesem Fall müsste vermutlich das Smooth-Scroll-Script angepasst werden, damit es den Alias dekodiert, z. B. mit `document.getElementById(decodeURI(id))`.

**Comment by ausi** [comment]
Mit Contao 4.5 werden dann durch #1016 die Aliase wieder von `ü` zu `ue` übersetzt.

**Comment by Seefahrer** [comment]
Danke für den Tip, Änderung im Script hat funktioniert!
