### ISSUE TITLE
show fieldset legend in form email

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1136]
It would be helpful to the recipient if the automatically generated email also included fieldset legends as headings, when form data is sent by email.

For instance imagine if you have a form with two fieldsets called _Participant_ and _Contact person_. In the first fieldset you would have the fields `participant_name` with the label _Name_ and `participant_email` with the label _Email_, while in the second you would have the fields `contact_name` with the label _Name_ and `contact_email` with the label _Email_.

However, in the email it would look like this:
```
Name: Lorem Ipsum
Email: foo@foo.com
Name: Dolor Sitamet
Email: arr@arr.com
```
The recipient would have to remember that the first pairing is the _Participant_ and the second pairing is the _Contact person_. It would even be impossible to distinguish between them, if one of those pairings are not mandatory and the setting `skipEmpty` is active.

Ideally, with fieldsets (that have legends) the resulting Email should look like this for example:
```
Participant
Name: Lorem Ipsum
Email: foo@foo.com

Contact person
Name: Dolor Sitamet
Email: arr@arr.com
```

**Comment by leofeyer** [comment]
I won't implement this for various reasons. First, widgets that are not submitting input are not added to `$arrProcessed` and thus not passed to the `processFormData()` method.

**Comment by xchs** [comment]
> Adding empty lines and section headlines, which are not key:value pairs, will break their scripts.

We could add a  key:value pair for the fieldsets, too. E.g.:
```
Fieldset: Participant
Name: Lorem Ipsum
Email: foo@foo.com
Fieldset: Contact person
Name: Dolor Sitamet
Email: arr@arr.com
```
That would probably not break the parsing scripts.
