### ISSUE TITLE
Adding static bundle assets broken

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#1137]
Adding static assets which are part of a bundle does not work without adding the `web` folder.

The [combiner already handles the special case](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Combiner.php#L128-L140), but the controller does not in:

 - https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Controller.php#L791-L794
 - https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Controller.php#L856-L859

**Comment by leofeyer** [comment]
Fixed in e31fdf6957d534158cc0707819242a6de405b915.
