### ISSUE TITLE
Definition von Bildgrößen umständlich

### ISSUE THREAD

**Issue by Glumanda99** [contao/core-bundle#1138]
**TDLR**; Ich finde die Definition der Bildgrößen umständlich und zum Teil unnötig kompliziert. Mein Use-Case wird nicht abgedeckt. Es wird davon ausgegangen, dass alle Bilder die selbe Auflösung haben und die Seite nur von professionellen Menschen gepflegt wird. Echter Content ist schmutzig. Echter Content wird von Laien erstellt. Echter Content befolgt keine Standards.

## Probleme und Lösungen

~~Ausgabe der verwendeten vordefinierten Größe im Quelltext
Jenachdem welche vordefinierte Bildgröße von Redakteuren ausgewählt wird, sollte diese auch per Klasse in der Ausgabe erscheinen. Ich denke es macht Sinn, wenn ich davon ausgehe, dass eine andere vordefinierte Bildgröße mit einer anderen Darstellung einhergehen kann.~~

### Kein `srcset` Attribut bei fehlender Breite/Höhe 
Da die Breite und Höhe zur Berechnung der Bildgrößen in Contao herangezogen wird, werden keine Bilder bei fehlender Breite/Höhe erzeugt. Ich finde die Herangehensweise von einer fest definierten Größe auszugehen ohnehin sinnfrei. Stattdessen sollte man wie @fritzmg bereits richtig festgestellt hat, von der Größe des jeweiligen Bildes selber ausgehen. Der ganze Sinn hinter responsive Images ist es schließlich die angezeigte Breite der Bilder in Relation zu Viewport und Pixeldichte bereitzustellen und den Browser das richtige Bild selbst wählen zu lassen. Da kann ich mit einer absoluten Angabe in Pixel recht wenig anfangen, vorallem wenn ich nicht weiß wie der Kontext dazu ausschaut. Genauso verwirrend finde ich es diese Angabe dann auch noch auf Redakteure loszulassen. Die Breite/Höhe wird zwar auch für das klassische `src` Attribut benötigt, inwieweit ein Redakteur aber damit anzufangen weiß steht auf einem anderen Blatt. Man kann nicht erwarten, dass sich Redakteure mit responsiv Images auseinandersetzen. Das mag hier vlt. nicht zur Diskussion stehen, ist aber Teil des Problems. Wie auch immer, ich finde die Berechnung der Bildgrößen anhand einer Multiplikation zweier Werte unnötig kompliziert.

#### Vorschlag:
- Bei fehlender Breite/Höhe sollte die Größe des jeweiligen Bildes selbst herangezogen werden
- "Pixeldichte/Skalierungsfaktor" in "Srcset-Attribut" umbenennen
- zusätzlich die direkte manuelle Eingabe von Breitenangaben ermöglichen

#### Vorteile:
- einfacher, verständlicher, direkter
- wer mit sizes und srcset bereits vertraut ist bekommt es auch ohne Anleitung hin
- keine unnötige Verwirrung bei Redakteuren mit Angaben von Pixel ohne jeden Kontext

~~Bildgrößen werden ohne Rücksicht auf ihre Originalauflösung generiert
Beispiel: Bilder in unterschiedlichen Auflösungen werden ins Backend hochgeladen. Vordefinierte Bildgröße "Galerie 360x", proportional, Pixeldichte 1x, 2x, 3x, 4x, 5x, 6x, 7x. Es wird keine Rücksicht darauf genommen ob das hochgeladene Bild nur eine Auflösung von 640x480 hat. Demzufolge werden Bilder großgezogen und via `srcset` auch bereitgestellt. Es kann nicht sein, dass ein so kleines Bild dann auf mit einer Auflösung von 1920x1440 daher kommt. Auch wenn ich mich mit obiger Limitierung anfreunden kann, dieses Problem macht es derzeit unmöglich für mich Contao einzusetzen, weil von falschen Bedingungen ausgegangen wird die so nicht existieren. Bilder sollten niemals vergrößert werden.~~

**Comment by frontendschlampe** [comment]
eine kurze Frage: Welche Contao Version verwendest du, denn die Eingabe einer CSS-Klasse ist in Contao 4 möglich (https://github.com/contao/core-bundle/commit/02a92d8e662898dc50ed8fa4204508c0eebdd86f) und auch das Vergrößern von Bildern wird nicht mehr gemacht!

**Comment by Glumanda99** [comment]
3.5

**Comment by ausi** [comment]
@Glumanda99 Danke für das konstruktive Feedback. 👍

> Jenachdem welche vordefinierte Bildgröße von Redakteuren ausgewählt wird, sollte diese auch per Klasse in der Ausgabe erscheinen.

CSS-Klassen für Bildgrößen ist bereits implementiert, siehe #555

> "Pixeldichte/Skalierungsfaktor" in "Srcset-Attribut" umbenennen

In einem `srcset`-Attribut steht ja nicht nur `1x, 2x`, sondern auch die Pfade dazu. Wäre das nicht mehr verwirrend wenn die Einstellung `srcset` heißt und dann gar keine Source-Pfade angegeben werden?

> zusätzlich die direkte manuelle Eingabe von Breitenangaben ermöglichen

Das ist bereits möglich. Anstatt, `1x, 2x` kann auch z. B. `200w, 400w` eingegeben werden.

> Bilder sollten niemals vergrößert werden.

Werden sie auch nicht mehr seit Contao 4.3. Siehe #342.

> Bei fehlender Breite/Höhe sollte die Größe des jeweiligen Bildes selbst herangezogen werden

Kannst du hierfür ein Beispiel nennen mit welchen Einstellungen du welches Ergebnis erwartest? Dieses Feature lässt sich vermutlich hinzufügen, wenn es dafür einen Use-Case gibt.

**Comment by Glumanda99** [comment]
> In einem srcset-Attribut steht ja nicht nur 1x, 2x, sondern auch die Pfade dazu. Wäre das nicht mehr verwirrend wenn die Einstellung srcset heißt und dann gar keine Source-Pfade angegeben werden?

Habe mich nicht verständlich genug ausgedrückt, die Pfade dazu sollten automatisch generiert werden. Wäre es umgekehrt nicht genauso verwirrend wenn ich Breitenbeschreibungen eingebe? `300w` sind für mich keine Pixeldichte oder Skalierungsfaktor. Ich fand es deshalb naheliegender und offensichtlicher es beim Attribut anzusprechen.

> Das ist bereits möglich. Anstatt, 1x, 2x kann auch z. B. 200w, 400w eingegeben werden.

Ok, habe es gerade in der Demo gesehen. Verstehe nicht warum man solche Fehler nicht in der 3.5.30 behebt. Laut Semver fällt das doch definitiv unter "backwards-compatible bug fixes".

> Kannst du hierfür ein Beispiel nennen mit welchen Einstellungen du welches Ergebnis erwartest? Dieses Feature lässt sich vermutlich hinzufügen, wenn es dafür einen Use-Case gibt.

Hat sich mit der Möglichkeit zur direkten Breitenangabe erledigt.

**Comment by ausi** [comment]
> Verstehe nicht warum man solche Fehler nicht in der 3.5.30 behebt.

Die Angabe von `w`-Descriptors wurde als neues Feature eingestuft, nicht als Bug.

> Wäre es umgekehrt nicht genauso verwirrend wenn ich Breitenbeschreibungen eingebe? `300w` sind für mich keine Pixeldichte oder Skalierungsfaktor. Ich fand es deshalb naheliegender und offensichtlicher es beim Attribut anzusprechen.

Wie wäre es mit „Srcset-Descriptors / Skalierungsfaktoren“?
