### ISSUE TITLE
/contao/install writes symlinks on each request

### ISSUE THREAD

**Issue by timgatzky** [contao/core-bundle#1140]
On each request to /contao/install the /web folder will be rewritten from scratch. No matter if you are logged in to the install tool or backend. 
That might cause high load on the server just by requesting this url on any contao 4.4 installation. Calling this in an endless loop might break the server down.

Two screenshots to underline the issue

1. Taken at 9:34
![screenshot_2471](https://user-images.githubusercontent.com/970730/31485420-06f4fc40-af34-11e7-8d78-6d700764f7f1.jpg)

2. Taken at 9:50 -> just called /contao/install -> folder has been recreated from scratch
![screenshot_2472](https://user-images.githubusercontent.com/970730/31485426-0cb54626-af34-11e7-8d8c-a2f42e006677.jpg)

**Comment by leofeyer** [comment]
Fixed in contao/installation-bundle@cec052e90f1d1be285a38240b22e0d673a7f7599 and contao/manager-bundle@7cdd7eac0e395b8d806c732b80faac939e5c73c7.

**Comment by Toflar** [comment]
In addition to that, you'll be able to disable the installation bundle as of Contao 4.5 completely.

**Comment by leofeyer** [comment]
By the way, you should never disclose any information about a possible security vulnerability in public (see https://en.wikipedia.org/wiki/Responsible_disclosure).

**Comment by timgatzky** [comment]
Ok, I think you should delete the issue. I honestly thought github would be a good place. Did not know about the security mail address. Sorry for that. 

I think you underrate this. That is a highly security issue in my opinion. I use the Mail know.

**Comment by timgatzky** [comment]
Fixed that issue pretty fast. But how do you recreate the symlinks now without manually deleting the folders? The backend maintenance "rebuild symlinks in /web folder" has no effect on the /bundles, /system, /assets folders / symlinks. Entering the Install-Tool has also no effect either. That would make sense here (just like deleting the /var/cache).
Did I miss something?

**Comment by discordier** [comment]
Building bundle symlinks is the job of the composer install script or the contao-manager.
NOT the job of Contao.

This is like this because it is a one time task performed directly post installation and will not be done during the operation of the application.

if you want to recreate them while developing a bundle, run:
- using composer: `composer run-script post-install-cmd`
- using the Contao manager: `php web/contao-manager.phar.php composer run-script post-install-cmd`

That is all to be done.

**Comment by timgatzky** [comment]
80% of our clients do not use the manager. Maybe that number will change when it's not on beta status anymore. Adding the manager to a manually installed installation does not work yet. (maybe I missed something and it is possible) 
The manager is supposed to be an optional tool. But even for us the manager does not work well enough to recommend it. But that is a different story.

Contao did build the symlinks, that's why this issue had to be started. Contao shall do this when entering the install tool and the manager should remain optional. Composer terminal task should not be involved. In the backend there is a whole maintenance job called "rebuild symlinks". Just let it build the complete list of symlinks and also let the install tool do that.
