### ISSUE TITLE
Image sizes are not applied correctly in the preview mode

### ISSUE THREAD

**Issue by Balindil** [contao/core-bundle#1145]
For example, if I create an image size of 300x300 (exact size), this is displayed correctly in the frontend, but not in the preview mode. There, the image is adjusted only proportionally. Its not cropped.

**Comment by ausi** [comment]
What exactly do you mean with “preview mode”? The Front end preview or the element preview in the backend?
Can you post a screenshot of the problem?

**Comment by Glumanda99** [comment]
I just tried that on [demo.contao.org](http://demo.contao.org/). It works with predefined dimensions. If you don't use predefined dimensions, choose **important part**. I don't know, why there is no option like **crop** to choose from.

**Comment by Balindil** [comment]
Sorry, I think there is a problem with the used theme and modified templates.
