### ISSUE TITLE
search module always appends ID parameter

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1146]
In the current Contao version, the search module always adds an `id` GET parameter to the search URL, which was not previously the case. So currently the URLs are
```
search.html?id=12&keywords=foo
```
instead of just
```
search.html?keywords=foo
```
This happens because in the template there are the [following lines](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/templates/modules/mod_search.html5#L7-L9):
```php
<?php if ($this->id): ?>
  <input type="hidden" name="id" value="<?= $this->id ?>">
<?php endif; ?>
```
However, `$this->id` will _always_ be present, since it's set in [`Module::generate`](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/modules/Module.php#L225).

281193d83165cae720027dfe7866b0c6de2335b9 is the cause for why this happens now. Previously, the `mod_search…` template was not built via `$this->Template` and thus `$this->id` was indeed empty (thx @ausi).

I cannot find any reason why the `id` parameter could be necessary in the first place. The parameter is never used in `ModuleSearch` or anywhere else as far as I can see. Is this a remnant from previous Contao versions may be? May be it can simply be removed from the template now?

**Comment by ausi** [comment]
The ID was previously used here: https://github.com/contao/core/blob/2474ff9a8e0cf0f533818461d20930e49baaa9b0/system/modules/core/modules/ModuleSearch.php#L93

Because we removed `disableAlias` in Contao 4, I think we can remove the ID parameter from the search template without causing problems.

**Comment by leofeyer** [comment]
Removed in c4e04ad4857dcfb6cc72d64d611ad5fa0170a99d.
