### ISSUE TITLE
backend scroll position not saved

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1147]
There still seems to be a problem with the saving and/or restoring of the backend scroll position.

### Reproduction

1. Add a lot of content elements to an article.
2. Scroll down and edit one content element in the middle or at the end for example.
3. Click _Save and close_.

You will be at the top of the page again.

(Tested in Contao 4.4.7)

**Comment by leofeyer** [comment]
See https://github.com/contao/core/issues/7688.
