### ISSUE TITLE
PrettyErrorScreenListener triggered on non-Contao routes

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1149]
When I register a custom route, the `PrettyErrorScreenListener` is still triggered. I think we should use the scope matcher here too. Wdyt?

**Comment by Toflar** [comment]
It does not check the scope, otherwise I would not have opened this issue?

**Comment by bytehead** [comment]
We had the same problem as well.

**Comment by leofeyer** [comment]
Fixed in 9abe32c9b468375ae042d81809dafe8a5ac8dd06.
