### ISSUE TITLE
Links are not distinguishable in the help wizard

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#1150]
When using links in the explanation for the help wizard, the links are not distinguishable in the text:

![848195fb-fb3f-4b24-9298-fb8e43d0e5b2](https://user-images.githubusercontent.com/1186266/31712174-95a14bd6-b3fa-11e7-8ae6-079c2713acc1.png)

Example how to fix it:

```css
.tl_help_table a {
    color: #77ac45;
}
```

![83e02af9-76bc-4be1-ae3a-25afa1f1ed01](https://user-images.githubusercontent.com/1186266/31712200-a70c5c80-b3fa-11e7-9dfb-f71e87f3ef9f.png)

**Comment by leofeyer** [comment]
Fixed amongst others in c33d1b59a5591661064fed11eb2c067c8d2e86e7.
