### ISSUE TITLE
Contao uses secondary instead of primary language

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1151]
Tested in Contao 4.4.7.

## Reproduction

1. Set _English (en)_ as the primary language in your language settings in Google Chrome.
2. Set _Russian (ru)_ as the secondary language in your language settings in Google Chrome.
3. Open the Contao Install Tool or Contao Backend Login.

The displayed language will be Russian.

![lang2](https://user-images.githubusercontent.com/4970961/31770878-272b8d34-b4da-11e7-8c7a-6b4903bce791.png)

### Language Settings

![lang](https://user-images.githubusercontent.com/4970961/31770843-ec693d22-b4d9-11e7-8cda-c6257c6b9873.png)

### Request Headers

```
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:en,ru;q=0.8,en-US;q=0.6
Cache-Control:max-age=0
Connection:keep-alive
Cookie:
Host:
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

Discovered via https://community.contao.org/de/showthread.php?68464-Install-Tool-auf-Russisch

**Comment by aschempp** [comment]
Contao 3 oder Contao 4?

**Comment by OMOSde** [comment]
Das Problem kommt aus dem Forum: https://community.contao.org/de/showthread.php?68464-Install-Tool-auf-Russisch

Contao 4.4.7

**Comment by fritzmg** [comment]
I tested it with Contao 4.4.7

**Comment by leofeyer** [comment]
I cannot reproduce the issue.

<img width="1024" alt="" src="https://user-images.githubusercontent.com/1192057/32600388-c00a6276-c53f-11e7-90c1-4741199ce37d.png">

**Comment by mlwebworker** [comment]
Ich habe im Chrome heute den Spaß mit Japanisch oder ist es Chinesisch. Es gibt keine Einstellungen in der Sprache von Chrome, die auf eine derart exotische Sprache hinweisen. 

![2017_12_22_backend_contao_chinesisch](https://user-images.githubusercontent.com/3602676/34299985-4c20aef2-e726-11e7-8495-00459ab8733d.png)


In Firefox, Vivaldi, Opera besteht das Problem nicht. Ebenso nicht unter Chrome auf einem zweiten Rechner (Mac). 
Auch das entfernen aller weiteren Sprachen (vorhanden war englisch und US-englisch aus Chrome ändert nichts am Problem in Chrome.
Eine zweite Contao 4 Installation ist unter Chrome an dem Rechner mit dem Phänomen auch nicht betroffen. Ziemlich mysteriös.

**Comment by mlwebworker** [comment]
Ich hatte das Problem heute wieder dieses mal im Firefox unter Windows 10.
Contao 4.4.18
Bisher haben weder Neustart des Browsers noch Neustart des Rechners und/oder Browsercache löschen eine Änderung hervorgebracht.
Andere Browser laufen.

![2018_04_21_login_chinesisch](https://user-images.githubusercontent.com/3602676/39099342-cfd8ded8-4679-11e8-86b1-32458ad47db8.png)

**Comment by mlwebworker** [comment]
Das Problem scheint weiterhin zu bestehen. Ich selbst hatte es in letzter Zeit mit der 4.4.20 einige Male in englischer Sprache (Browser Chrome, Windows 10). Was ja fast gar nicht ins Gewicht fällt, aber im Forum hat jemand auch gerade das Problem mit russisch. https://community.contao.org/de/showthread.php?71482-ungefragte-Sprachanzeige&p=479446#post479446

**Comment by mlwebworker** [comment]
Heute hatte ich mal wieder ein russisches login. Contao 4.4.20, Browser Chrome, Windows 10

**Comment by leofeyer** [comment]
Das ist wirklich seltsam. Du hast aber keinen russischen Trojaner auf dem Rechner, der unbemerkt im Web surft, so dass Chrome denkt, Du könntest Russisch? 😄

**Comment by mlwebworker** [comment]
Das glaub ich eigentlich nicht. Passierte ja meist auch auf englisch bei mir und das Problem mit russisch war ja zufällig auch im Forum.
