### ISSUE TITLE
<strong> Element in nav_default but not in mod_breadcumb

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1154]
Updating from 3.5 intallation i noticed that the [nav_default template](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/navigation/nav_default.html5#L5) uses the ```<strong>``` instead of ```<span>``` tag for the active Item.
In the [commit-history](https://github.com/contao/core-bundle/commits/master/src/Resources/contao/templates/navigation/nav_default.html5) i could not find when or why this has changed.
Of course it's an easy fix to adjust the template (or fix my css) but i don't really think the use of ```<strong>``` is semantically correct here.

**Comment by fritzmg** [comment]
It is semantically correct. See

* https://stackoverflow.com/a/271776/374996
* https://github.com/contao/core/issues/6336

**Comment by asaage** [comment]
Alright - i'm not shure why one would like to emphasize something that has already been cklicked on and offers no further actions but it should be **strong** in [mod_breadcrumb](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_breadcrumb.html5#L8) then too.

**Comment by fritzmg** [comment]
> Alright - i'm not shure why one would like to emphasize something that has already been cklicked on and offers no further actions

It's about the semantic meaning of the HTML markup, not about click actions. `<strong>` semantically emphasises its content, signifying the currently active element in this case.

**Comment by fritzmg** [comment]
You should reopen and rename the ticket for mod_breadcrumb.

**Comment by leofeyer** [comment]
Changed in acd841e33a50347487009da8508c931ae6a9a03e.
