### ISSUE TITLE
jQuery path is wrong for Contao 4.4.7

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1155]
Hello,

in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/pages/PageRegular.php on lines 409, 414 and 419 there's the wrong path for the jquery installed with composer:

`assets/jquery/js/jquery.min.js|static`

should be

`assets/jquery/jquery.min.js|static`

**Comment by fritzmg** [comment]
No, the path should be
```
assets/jquery/js/jquery.min.js
```
See https://github.com/contao-components/jquery/tree/3.2.1

**Comment by Defcon0** [comment]
Ah, just seen, one of our composer modules required "components/jquery" instead of "contao-components/jquery". Sorry for that one ;-)
