### ISSUE TITLE
C4: Edit data of multiple pages doesn't work ("override")

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#1156]
Just noticed that multiple pages cannot be edited in C4 anymore.

Steps to reproduce:
1) Log in to https://demo.contao.org/contao
2) Go to "Site structure" and click on "Edit multiple"
3) Select one or several pages and the action "Override" (which is a strange translation of "Überschreiben")
4) Select one or several fields and click "Continue"

The fields are only shown once (even if several pages were selected) and do not contain any data.

Can anyone confirm?

**Comment by fritzmg** [comment]
That's not a bug. That's what happens when you choose _Override_ instead of _Edit_.

**Comment by pgerundt** [comment]
Sorry. Stupid me.
