### ISSUE TITLE
Zu hoher Speicherverbrauch beim Erstellen der XML-Sitemap

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#1157]
Folgendes Szenario: ManagedServer bei Domainfactory, PHP 7.1, frische Installation Contao 4.4.7 ohne Extras, memory_limit php.ini = 1000M

Darin habe ich meine Datenbank aus C3 importiert (1,6 GB groß, 1.641 Seiten, 1.046 Events, 13.127 Nachrichten). Templates und Erweiterungen aus C3 habe ich nicht übernommen. Es ist also nur eine blanke 4.4.7 mit der Datenbank von 3.5.30.

Beim Speichern von Seiten und beim Neuschreiben der XML-Dateien kommen Fehler, z.B.:
`Fatal error: Out of memory (allocated 462274560) (tried to allocate 28672 bytes) in /xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 146 Fatal error: Out of memory (allocated 462274560) (tried to allocate 36864 bytes) in Unknown on line 0`

Unter C3.5 funktioniert das Ganze tadellos.

Siehe dazu auch das [Forum](https://community.contao.org/de/showthread.php?68507-Out-of-memory-in-PDOStatement-php-(line-146)&p=454650#post454650)
Oder auch: https://github.com/contao/core/issues/7928

**Comment by ausi** [comment]
Die Fehlermeldung `Out of memory (allocated 462274560)` deutet darauf hin, dass das memory_limit kleiner als 500 MB ist (462.274.560 Byte).

**Comment by fritzmg** [comment]
@ausi Ungeachtet dessen sind 440+ MiB Speicherverbrauch sehr viel. Laut den Informationen von @Samson1964 meldet die Debug Bar von Contao 3 nur einen Speicherverbrauch von 34 MiB beim aufbauen der XML Dateien in der Systemwartung.

**Comment by Samson1964** [comment]
Mail der df)-Technik auf meine Supportanfrage:

> Unsere Technik hat Ihr Anliegen bearbeitet und hat hier entsprechend das Limit auf der Domain einmal auf 1GB erhöht. Bitte testen Sie es jetzt noch einmal, es sollte nun eigentlich funktionieren.

Und es hat funktioniert! Was die Technik da genau gemacht hat, wurde mir nicht geschrieben. Auf jeden Fall hat sie nicht am memory_limit meiner php.ini herumgeschraubt.

**Comment by Samson1964** [comment]
Nachtrag auf Nachfrage bei df):

> Wir haben den zur Verfügung gestellten RAM erhöht. Diese Einstellung ist nicht durch Sie möglich, kann aber gerne bei Nennung der betreffenden Domain durch uns angepasst werden, sofern es sich um einen ManagedServer-Tarif handelt.

**Comment by Toflar** [comment]
Ist halt schwer sowas zu fixen, ohne mit den konkreten Daten arbeiten zu können.

**Comment by Samson1964** [comment]
Ich kann meine C3-Datenbank im SQL-Format gern zur Verfügung stellen. @Toflar : Darf ich den Download-Link an Dich schicken?

Wenn man gleich mehrere Seiten in der Seitenstruktur bearbeitet, dann reichten selbst die jetzt freigegebenen 1 GB nicht aus.

**Comment by Toflar** [comment]
Jap, e-mail findest du auf meinem Profil :) Was muss ich machen um es nachzustellen? Die DB einfach auf die 4.4 anheben und dann mehrere Seiten bearbeiten?

**Comment by Toflar** [comment]
So, Frank hat mir die DB geschickt und ich hab mir mal die Mühe gemacht das Problem ein paar Stunden zu analysieren. Folgendes ist dabei herausgekommen:

Ich brauchte insgesamt 915 MB um die Sitemap neu aufbauen zu können. 85.6% davon gehen auf Kosten von `\NewsModel::findPublishedDefaultByPid()`. In der DB befinden sich 7733 relevante News-Einträge die für den Aufbau der Sitemap relevant sind. Für jeden davon wird ein Model gebaut bzw. eigentlich ist schon alleine die DB-Abfrage dann das Problem, weil wir eine Collection bauen und die mit `$pdoStatement->fetchAll()` komplett ins Memory geladen wird. Geht auch gar nicht anders, weil wir ja komplette Models haben müssten. Partial Models (also nur einen Teil von der DB abfragen statt `SELECT *`) sind sehr fragil und fast kein ORM verfügt über eine solche Funktion. Das ist keine Option für mich.
Das einzig sinnvolle für mich wäre `\News::getSearchablePages()` auf direkte DB-Abfragen statt Models umzubauen.

**Comment by Samson1964** [comment]
Danke Yanick! In Contao 3 geht die Sitemap-Erstellung deutlich speicherschonender zu Werke. Warum ist Contao 4 auf einmal an der Stelle so speicherhungrig?

**Comment by Toflar** [comment]
Keine Ahnung, das habe ich nicht verglichen.

**Comment by fritzmg** [comment]
> Das einzig sinnvolle für mich wäre \News::getSearchablePages() auf direkte DB-Abfragen statt Models umzubauen.

Wasn't this [already decided](https://github.com/contao/core/issues/7928#issuecomment-130788699) once? ;)

**Comment by fritzmg** [comment]
> Ich brauchte insgesamt 915 MB um die Sitemap neu aufbauen zu können. 85.6% davon gehen auf Kosten von \NewsModel::findPublishedDefaultByPid(). In der DB befinden sich 7733 relevante News-Einträge die für den Aufbau der Sitemap relevant sind. Für jeden davon wird ein Model gebaut bzw. eigentlich ist schon alleine die DB-Abfrage dann das Problem, weil wir eine Collection bauen und die mit $pdoStatement->fetchAll() komplett ins Memory geladen wird. Geht auch gar nicht anders, weil wir ja komplette Models haben müssten.

Das würde ja bedeuten, dass ein einzelne Model Objekt (durchschnittliche) 100 KiB verbraucht - aber sollte das nicht eigentlich weit weniger sein?

**Comment by Toflar** [comment]
Ich hab nirgendwo behauptet, dass ausschliesslich die Model-Instanz schuld ist :). Ich vermute dass der DB-Buffer da noch mit rein spielt, was in Contao 3 anders war und womöglich den Unterschied ausmachen könnte. Ich hab's aber noch nicht getestet.
So oder so ist es bei performance-relevanten (wie schreibt sich das eigentlich? :D) Methoden (wie hier vorliegend) nicht empfehlenswert, mit Models zu arbeiten. ORM's muss man als Erleichterung für Entwickler verstehen. Sie können von Natur aus niemals mit der Performance von direkten Queries mithalten. Deshalb weiss ich nicht, inwiefern sich hier weitere Analysen lohnen, der Umbau auf direkte Queries wäre imho ohnehin sinnvoll.

**Comment by Toflar** [comment]
Also konkret meine ich die Zeile hier: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Database/Result.php#L95
Die lädt alle Daten in den RAM (steht auch ein schönes TODO dort :-)). In der 3 haben wir einen Cursor und in der 4 eben nicht mehr, weil keiner weiss (oder sich noch keiner damit beschäftigt hat) ob wir das nachbauen könnten auf Basis von PDO.
Aber wie gesagt, eigentlich kann ich mir das nicht erklären, weil der Garbage Collector schmeisst ja nur Objekte weg, die nicht mehr referenziert werden. Und bei uns werden ja alle referenziert sobald sie in die Registry kommen (was ja in der 3 auch der Fall ist). Evtl. behält er in der 4 auch das DB-Resultset im RAM und in der 3 nicht, warum auch immer. Aber ob mich das jetzt interessieren sollte, habe ich noch nicht entschieden 😄

**Comment by Toflar** [comment]
Interessiert mich offenbar doch:

Also der Unterschied ist logisch: In Contao 3 nutzen wir DB Cursors, das heisst von den 7k Datensätzen wird jeweils immer nur ein Datensatz geladen, dann das Model dazu angelegt, dann wird der Datensatz verworfen (Memory wird hier freigegeben) und ab zum nächsten Datensatz etc. 
In Contao 4 laden wir das ganze Resultset in den RAM (damit wir rückwärtskompatibel bleiben können mit unserem `Result::next()` und `Result::prev()`), womit nie Memory freigegeben wird bzw. erst nachdem die gesamte Collection gebaut wurde womit wir natürlich den Peak von 915 erreichen.
Also wenn wir da auf PDO Cursors umbauen könnten, hätten wir wieder den Contao 3 Zustand, welcher aber immer noch nicht optimal ist.

**Comment by leofeyer** [comment]
Wir könnten auch eine zweite Collection-Klasse bauen, die ein Resultset übergeben bekommt und direkt mit den DB Cursors arbeitet. Die wäre dann halt nicht rückwärtskompatibel, könnte aber in Fällen wie diesem verwendet werden.

**Comment by Toflar** [comment]
Soweit ich sehen konnte, können wir das eben nicht. Gäbe es Cursors wäre es ja eben BC. Aber PDO bietet keine an für MySQL. Ich hab zumindest nix gefunden, auch nicht im PHP Sourcecode...

**Comment by leofeyer** [comment]
Verstehe. Und wenn wir den `mysqli`-Driver statt des `pdo_mysql`-Drivers für Doctrine konfigurieren würden?

**Comment by aschempp** [comment]
Soweit mir bekannt kann die Doctribe DBAL kein seeking, weil nicht alle Plattformen das können.

**Comment by Samson1964** [comment]
Derselbe Fehler trat jetzt auch beim Aufruf eines (großen) Nachrichten-Archives im BE auf, nachdem ich die Domain gewechselt habe. Ich habe Domainfactory gebeten auch für die neue Domain das Limit von den ca. 460 MB auf 1 GB hochzustellen.

**Comment by leofeyer** [comment]
>> Das einzig sinnvolle für mich wäre \News::getSearchablePages() auf direkte DB-Abfragen statt Models umzubauen.
>
>Wasn't this [already decided](https://github.com/contao/core/issues/7928#issuecomment-130788699) once? ;)

As discussed in Mumble on April 12th, this is what we want to do (and the only thing we can do).

**Comment by fritzmg** [comment]
@Samson1964 (und alle anderen, die Installationen mit sehr vielen Events und News haben): als Workaround könnt ihr folgendes machen:

`app/Resources/contao/dca/tl_news.php`
```php
$GLOBALS['TL_DCA']['tl_news']['fields']['pid']['relation']['load'] = 'lazy';
$GLOBALS['TL_DCA']['tl_news']['fields']['author']['relation']['load'] = 'lazy';
```

`app/Resources/contao/dca/tl_calendar_events.php`
```php
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['pid']['relation']['load'] = 'lazy';
$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['author']['relation']['load'] = 'lazy';
```

Danach natürlich
```
vendor/bin/contao-console cache:clear --no-warmup
vendor/bin/contao-console cache:warmup
```

**Comment by leofeyer** [comment]
Siehe #1549.
