### ISSUE TITLE
SCSS-Dateien neu generieren, wenn Unterdateien neuer (filemtime)

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1158]
Ich beziehe mich auf https://github.com/contao/core-bundle/issues/987 und https://github.com/contao/core-bundle/commit/64a8a2593fa3ade59167fb87e76121ec58daa03d

Wir hatten ja mal kurzzeitig die Änderungen, dass Contao in eine SCSS-Datei reinschaut und den importeten Dateien folgt und sie auf Änderungen überprüft.
Dieses Feature wurde, wenn ich das richtig sehe, implementiert und dann wieder rückgängig gemacht:
https://github.com/contao/core-bundle/commits/master/src/Resources/contao/library/Contao/Combiner.php

Begründung habe ich hier gefunden:
https://github.com/contao/core-bundle/pull/1010#issuecomment-321550112
Was aber offenbar nicht sehr auf Gegenliebe stößt.

Wir hatten das bei uns immer manuell gelöst, indem durch ein kleines PHP-Skript (eingebunden über initconfig.php) alle scss-Dateien im Ordner durchgegangen wurden und - falls neuer - die filetime der basis app.scss aktualisiert wurde. Das hat Contao dann zum erneuten Generieren und Einlesen der app.scss bewogen. Das war eigentlich immer ein ziemlich solider Hack :)
Sobald wir produktiv gegangen sind, konnten wir diesen Check aus der initconfig.php einfach auskommentieren.
Leider funktioniert das jetzt aber mit Contao 4.4.7 nicht mehr.

**Erstens:** Wenn ich das richtig verstanden habe, wurde die überprüfung der filemtime der app.scss nun deaktiviert.
Wieso? Wie läuft das stattdessen ab? Contao scheint mir keinerlei Überprüfung mehr durchzuführen, ob die app.scss (im Layout eingebunden) nun geändert wurde.

**Zweitens:** Wenn wir stattdessen über die app_dev.php gehen sollen (was ich eigentlich nur ungern möchte), gibt es eine Anleitung, wie man den Zugriff auf die app_dev.php freischaltet und ein Passwort für den dev Entrypoint setzt? Ich habe nicht ganz verstanden, wie das ablaufen soll.

Wir können tatsächlich so wie es aktuell ist nicht entwickeln, wenn wir bei jeder Änderung in der Systemwartung den Scriptcache leeren müssen.

Bitte um Hilfe.

**Comment by fritzmg** [comment]
> Zweitens: Wenn wir stattdessen über die app_dev.php gehen sollen (was ich eigentlich nur ungern möchte), gibt es eine Anleitung, wie man den Zugriff auf die app_dev.php freischaltet und ein Passwort für den dev Entrypoint setzt? Ich habe nicht ganz verstanden, wie das ablaufen soll.

```
vendor/bin/contao-console contao:install-web-dir --user=USER --password=PASSWORD
```

**Comment by Xendiadyon** [comment]
@fritzmg Vielen Dank für die rasend schnelle Antwort.

Ergänzend für alle Passiv-Leser:
1) Es muss ein htaccess-Passwortschutz gesetzt sein.
2) im TL_ROOT (also oberhalb von web/) muss der Befehl ausgeführt werden:
`php vendor/bin/contao-console contao:install-web-dir --user=USER --password=PASSWORD`
(bei Domainfactory: `php7.1.6-cli vendor/bin/contao-console contao:install-web-dir --user=USER --password=PASSWORD`) wobei USER/PASSWORD dem htaccess-Passwortschutz entsprechen.
3) Anschließend kann das Projekt über app_dev.php aufgerufen werden; hier wird der Cache bei jedem Aufruf gelöscht.

Vielen Dank, so können wir immerhin erst mal weiter entwickeln. Aber vielleicht bekommen wir es auch ohne die app_dev hin? Das ist ja insbesondere dann unpraktisch, wenn man mal eben den Cache leeren möchte, aber keinen htaccess-Schutz (mehr) aktiv hat?

**Comment by fritzmg** [comment]
> Es muss ein htaccess-Passwortschutz gesetzt sein.

Nein, das ist keine Anforderung.

> Anschließend kann das Projekt über app_dev.php aufgerufen werden; hier wird der Cache bei jedem Aufruf gelöscht.

Das stimmt so nicht ganz. Über `app_dev.php` wird kein Cache aufgebaut. Auch nicht der interne Cache von Contao. _Allerdings_ kann es selbst über die `app_dev.php` sein, dass der interne Cache von Contao existiert, wenn du zuvor bspw.
```
vendor/bin/contao-console cache:warmup --env=dev
```
ausgeführt hast. In dem Fall müsstest du den Cache nochmal löschen.
