### ISSUE TITLE
Standard-Viewport wird nicht mehr ausgefüllt

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1160]
Vielleicht habt ihr eine Idee, woran das liegen könnte?

Normalerweise wird der Viewport eines Themes ja automatisch auf `width=device-width,initial-scale=1.0` gesetzt, wenn er nicht definiert ist.
Das funktioniert auch meistens. Bei einigen unserer Contao-Installationen (sowohl Update von 3.5 als auch Neuinstallation) war es nun aber so, dass das viewport-Feld leer war und dadurch dann auch überhaupt kein viewport-Tag definiert wurde. Bei anderen Installationen wiederum erhalten wir - wie erwartet -
den o.g. Standard-Viewport-Tag.

Ich werde meinen Kollegen also die Empfehlung geben, sicherheitshalber immer den o.g. viewport-Tag zu setzen.

Aber habt ihr eine Idee, warum manchmal der leere viewport-Tag im Theme mit dem Standard ersetzt wird und warum er manchmal weggelassen wird? Habt ihr das auch selbst mal beobachtet?

**Comment by fritzmg** [comment]
> Normalerweise wird der Viewport eines Themes ja automatisch auf width=device-width,initial-scale=1.0 gesetzt, wenn er nicht definiert ist.

Nur, wenn du `responsive.css` im Contao CSS Framework ausfüllst. Andernfalls musst du deinen eigenen Viewport setzen. Siehe auch https://github.com/contao/core/issues/8222

**Comment by Aybee** [comment]
Genau, vergiss einfach die Kenntnis darüber, dass da irgendwas default gesetzt wird. In C3.5 war da der Hilfetext lückenhaft, man brauchte also geheimes Insiderwissen darüber, was @fritzmg erklärt hat.

In C4 hast du diese Info erst gar nicht mehr, ich vermute, weil sie uninteressant ist.
> Hier können Sie ein individuelles Viewport-Tag setzen.

Wobei hier das Wort "individuelles" schon schlecht ist, weil es suggeriert, dass sonst irgendein Viewport-Tag gesetzt wird, was aber nicht der Fall ist.

Besser
> Hier können Sie das Viewport-Tag setzen.

Der Fallback auf ein Viewport-Tag bei Auswahl von _Responsives Layout_ ist nur ein Automatismus im Hintergrund, weil diejenigen, welche das angehakt haben, auf jeden Fall einen Viewport-Tag benötigen.

**Comment by Aybee** [comment]
@leofeyer 
Hier https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/en/tl_layout.xlf#L218-L220
Bitte den Text ändern
```
      <trans-unit id="tl_layout.viewport.1">
        - <source>Here you can set a custom viewport tag.</source>
        + <source>Here you can set a viewport tag.</source>
      </trans-unit>
```
Weil "custom" suggeriert, dass sonst ein "default" generiert wird, was nicht der Fall ist.

**Comment by Xendiadyon** [comment]
vielen Dank für die Erklärung, das hat mir sehr weitergeholfen.

**Comment by leofeyer** [comment]
Ich habe den Text in 324720ee4e37c6366ebae097acb04e128482077a angepasst.

**Comment by Aybee** [comment]
Thank you 👍
