### ISSUE TITLE
C4: Bearbeitung mehrerer Seiten (Felder vom Typ pageTree)

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#1162]
Hallo zusammen,

ich glaube, es gibt einen Bug wenn man Felder vom Typ `pageTree` von mehreren Seiten gleichzeitig bearbeitet. Aufgefallen ist es bei `terminal42/contao-changelanguage` aber es scheint ein Bug im `core-bundle` zu sein.

Reproduzierung:
- In der Seitenstruktur "mehrere bearbeiten" klicken, eine Seite auswählen und Button "bearbeiten" klicken
- Ein Feld vom Typ "pageTree" auswählen und Button "weiter" klicken
- Button "Auswahl ändern" klicken und Seite wählen
- Klick auf Button "Anwenden" bringt JS-Fehlermeldung und schließt modalDialog nicht

Ursache:

modalDialog öffnet URL
`contao/page?do=page&amp;table=tl_page&amp;field=languageMain&amp;act=show&amp;id=999&amp;value=&amp;rt=...
`
Dort wird der PageSelector mit dem Code
```
<ul class="tl_listing tree_view picker_selector" id="languageMain" data-callback="reloadPagetree" data-inserttag="link_url">
[...]
```
gerendert.

Klick auf "Anwenden" führt nun in der core.js
```
var frm = window.frames['simple-modal-iframe'],
[...]
ul = frm.document.getElementById(opt.id);
```
aus; wobei `opt.id` den Wert `languageMain_999` hat.

Das `<ul>` müsste also `id="languageMain_999"` haben.

Ich konnte den Fehler bis zum `core-bundle/src/Resources/contao/widgets/PageSelector.php` verfolgen. Hier enthält `$this->strId` die "falsche" id.
Da das Modal immer mit der gleichen URL aufgerufen wird - egal ob eine oder mehrere Seiten bearbeitet werden - muss man vermutlich in der `src/Resources/contao/widgets/PageTree.php` ansetzen und dort `(Input::get('act') == 'editAll')` abfragen.

Sorry für den langen Text. Kann jemand den Bug bestätigen bzw. ist er vielleicht zwischenzeitlich schon gefixt?

**Comment by pgerundt** [comment]
Ach verdammt, ist wohl gefixt:
https://github.com/contao/core-bundle/commit/630cc38aefab65813cb088c721b98fa2070a3c82

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/core/issues/6788.
