### ISSUE TITLE
Größenangabe in SVG wird nicht erkannt

### ISSUE THREAD

**Issue by BeaB8** [contao/core-bundle#1163]
Eine Test SVG, über Illustrator erstellt, wurde über die Dateiverwaltung hochgeladen und dann als Inhaltselement "Bild" eingefügt. Eine Bildgröße wird nicht zugewiesen.

Der Quelltext ist dann nicht valide.

```
<svg id="Ebene_1" data-name="Ebene 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 52.3 52.3">
  <defs>
    <style>
      .cls-1 {
        fill: red;
      }
    </style>
  </defs>
  <title>test</title>
  <g>
    <rect class="cls-1" x="0.5" y="0.5" width="51.3" height="51.3"/>
    <path d="M51.3,1V51.3H1V1H51.3m1-1H0V52.3H52.3V0Z"/>
  </g>
</svg>
```

```
<figure class="image_container" itemscope="" itemtype="http://schema.org/ImageObject">
<img src="pfad/test.svg" width="" height="" alt="" itemprop="image">
</figure>
```

Ich hoffe, das ist für euch relevant.

Viele Grüße von Bea

**Comment by ausi** [comment]
Das SVG-Bild hat keine Dimensionen, da es keine `width` und `height` attribute hat. Die Größenbehandlung von SVG Dateien ist in contao/core#7882 genauer beschrieben.

**Comment by BeaB8** [comment]
Man müsste also herausfinden, wie man die Optionen beim SVG Export in Illustrator setzen muss, damit ein Code herauskommt, der den Vorgaben im Core entspricht.

**Comment by fritzmg** [comment]
@ausi laut dem Ticket sollte das SVG ja dann als
```html
<img src="image.svg">
```
ausgegeben werden, oder nicht?

**Comment by BeaB8** [comment]
Genau so binde ich die Dateien ein, die ich für das globale Layout benötige. Die Größen definiere ich über css und fertig.
Es kann ja aber auch den Fall geben, dass ein Grafiker irgendwelche Illustrationen anfertigt und die Datei dann an den Redakteur weiterleitet und dieser das dann über Artikel einfügt. Das wollte ich hier nur melden, dass der Validator nicht immer mit den Ergebnissen zufrieden ist, je nachdem welche Optionen im Grafikprogramm gesetzt wurden.

**Comment by ausi** [comment]
OK, verstehe. Aktuell wird `<img src="image.svg" width="" height="">` ausgegeben, die korrekte Ausgabe wäre jedoch `<img src="image.svg">`.

Das sollte sich lösen lassen indem wir in https://github.com/contao/core-bundle/blob/a3b68142c327b787e01090d7d9c9737e699122b2/src/Resources/contao/templates/picture/picture_default.html5#L11 die Abfrage `elseif (!$this->sources)` mit `elseif (!$this->sources && $this->img['width'] && $this->img['height'])` ersetzen.

@BeaB8 Kannst du bitte testen ob dadurch das Problem auf deiner Seite behoben wird?

**Comment by frontendschlampe** [comment]
naja ... einem svg kann durchaus eine Größe mitgegeben werden.

```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" ...```

Von daher sollte die Größe einfach nur korrekt ausgelesen werden, oder?

**Comment by ausi** [comment]
Ja, bei einem SVG-Bild mit `width` und `height` Attribut funktioniert das auch korrekt. Aber bei einem SVG-Bild ohne diese Angaben, sollten keine leeren Attribute im HTML ausgegeben werden.

**Comment by fritzmg** [comment]
Ich dachte wenn ein SVG `width` und `height` hat, dann hat die Bildgrößeneinstellung in Contao keine Auswirkung mehr? Deswegen hatte ich immer `width` und `height` in allen SVGs entfernt, die in Contao (mit Bildgrößenangaben) ausgeben werden 😁

**Comment by frontendschlampe** [comment]
> Ja, bei einem SVG-Bild mit width und height Attribut funktioniert das auch korrekt. Aber bei einem SVG-Bild ohne diese Angaben, sollten keine leeren Attribute im HTML ausgegeben werden.

ah ... alles klar

**Comment by ausi** [comment]
> Ich dachte wenn ein SVG `width` und `height` hat, dann hat die Bildgrößeneinstellung in Contao keine Auswirkung mehr?

Nein, ein SVG mit `width` und `height` wird genau so behandelt wie eine Pixel-Grafik. Es wird geresized, aber nicht upscaled.

**Comment by fritzmg** [comment]
kk, macht Sinn.

**Comment by BeaB8** [comment]
@ausi 
Habe das getestet und das betroffene SVG wird nun ohne Größenangaben ausgegeben.
(Entschuldige die späte Antwort, war arbeitstechnisch versackt)

**Comment by ausi** [comment]
Wird durch #1178 behoben.
