### ISSUE TITLE
Felder mit options_callback werden im editAll Modus ohne Formularfeld gelistet

### ISSUE THREAD

**Issue by markocupic** [contao/core-bundle#1164]
Felder mit options_callback werden im editAll Modus ohne Formularfeld gelistet.
Getestet auf Contao 3.5 und Contao 4.4. (Contao Demo)

Vorgehen:
themes -> modules
"Mehrere bearbeiten" klicken
Mehrere items auswählen
Danach auf "Bearbeiten" button klicken
Danach ein Feld auswählen, das die options über einen options_callback bezieht (z.B. Formular [forms])

Jetzt auf "weiter" Button klicken. 
Resultat: Die items werden leer und ohne Formularfeld (select-Feld) gelistet.

**Comment by leofeyer** [comment]
Das liegt daran, dass das Feld `Formular [form]` in den gewählten Datensätzen nicht vorkommt.
