### ISSUE TITLE
You have requested a non-existent service "contao.image.resize_calculator"

### ISSUE THREAD

**Issue by joeherold** [contao/core-bundle#1169]
Hallo zusammen!

Wenn ich bei einem getImage Hook das $objImage->computeResize() aus einem 3er Modul ausführe, dann wird ja die Contao Core Image Klasse verwendet (für legacy). 
In Zeile 598 wird der Service "contao.image.resize_calculator" geladen. Aber das wirft bei meiner 4.4.1 Version einen Fehler. Auch in einer 4.4.7.
https://github.com/contao/core-bundle/blob/a3b68142c327b787e01090d7d9c9737e699122b2/src/Resources/contao/library/Contao/Image.php#L598

```code
You have requested a non-existent service \"contao.image.resize_calculator\". Did you mean this: \"contao.image.resizer\"?
```

Wo liegt das Problem???

**Comment by ausi** [comment]
Vermutlich müssen wir `public: false` in der services.yml entfernen, @contao/developers 
 ?

**Comment by joeherold** [comment]
ok, ich probiere das mal in einer lokalen umgebung aus und berichte ob es klappt

**Comment by joeherold** [comment]
@ausi yep, genau das ist das problem!
wenn ich public: false entferne, dann geht es und ist rückwärts kompatibel

**Comment by leofeyer** [comment]
Geändert in 5e97998e06c7f4b9a832692fb3234cbd7d0e2499.

**Comment by joeherold** [comment]
Merci!
