### ISSUE TITLE
4.4.7: Combiner adds extra media info in debug mode for js files

### ISSUE THREAD

**Issue by DyaGa** [contao/core-bundle#1170]
See [line 234](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Combiner.php#L234) of `Combiner.php` it adds additional `|screen` media value to js source in debug mode. Example:

```
bundles/app/template/js/vendor.min.js|screen
```

**Comment by leofeyer** [comment]
Even though this is clearly a configuration error (you should never add `|screen` to a JS file), I have added an additional check in 7bb0cfe4f3c4900ebfe4bc5057bde1fe004739b2.
