### ISSUE TITLE
ID/Class in Modul wird nicht übernommen

### ISSUE THREAD

**Issue by BeaB8** [contao/core-bundle#1174]
Moin,
bin wie folgt vorgegangen:
- Modul Typ "Eigener HTML Code" angelegt
- Modul als Artikel eingefügt und dabei die Felder ID/Klasse befüllt
Ergebnis:
- Weder die ID noch die Klasse kommt im Quelltext an.
VG von Bea

**Comment by fritzmg** [comment]
Das ist normal. Das Modul bzw. Inhaltselement gibt einfach den von dir eingegeben (oder im Template verwendeten) HTML Code aus.

**Comment by BeaB8** [comment]
Danke für die Info. Trotzdem finde ich es nicht so glücklich, im BE Felder anzubieten, die dann nicht übernommen werden.  VG!

**Comment by fritzmg** [comment]
Es wäre aber auch unglücklich, wenn diese Felder nicht angeboten werden - man sie aber trotzdem verwenden möchte. Du kannst ja in einem eigenen `mod_html[_…]` Template bspw. darauf zugreifen.

**Comment by BeaB8** [comment]
Ok, danke für die Mühe!

**Comment by Aybee** [comment]
> @BeaB8 im BE Felder anzubieten, die dann nicht übernommen werden

Die werden nur übernommen, wenn man das Modul ins Layout einbindet. Das ist eine bekannte Limitation. Ist schon oft angefragt worden. Ich meinte auch, dass dies mal geändert wurde und zwar so, dass diese ID im Inhaltselement übernommen wird, wenn dort keine eingetragen wurde und die CSS-Klasse/n an die CSS-Klasse/n aus dem Inhaltselement angehängt werden.

Kann aber sein, dass es bei allen anderen Modulen wie oben beschrieben funktioniert nur nicht bei dem HTML-Modul, weil dies kein Wrapper-HTML hat.

BTW Man kann ein Modul nicht als Artikel einfügen.

**Comment by fritzmg** [comment]
> Die werden nur übernommen, wenn man das Modul ins Layout einbindet. Das ist eine bekannte Limitation. Ist schon oft angefragt worden. Ich meinte auch, dass dies mal geändert wurde und zwar so, dass diese ID im Inhaltselement übernommen wird, wenn dort keine eingetragen wurde und die CSS-Klasse/n an die CSS-Klasse/n aus dem Inhaltselement angehängt werden.

Das ist etwas anderes. Hier geht es um das Inhaltselement bzw. Modul vom Typ `html`. Bei diesem Element/Modul wird nur der HTML Code ausgegeben, den man selbst eingegeben hat.

**Comment by Aybee** [comment]
Dann hatte ich ja richtig vermutet, dass dies nur bei HTML so ist. Klassen mergen ist also umgetzt. Sehr gut. Weißt du auch auswendig, was mit der ID passiert?

**Comment by fritzmg** [comment]
Soweit ich weiß wird die ID nicht übernommen. Habe ich jetzt aber nicht überprüft.
