### ISSUE TITLE
File::createIfNotExists is never used

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1177]
In Contao 4, the second argument for `File::__construct()` has been dropped. Thus files will not be created by default any more, when using `new File(…)`.

However in Contao 3 when the file was created, its directory was also created if it does not exist yet. This was done in `File::createIfNotExists` (see [File.php#L447-L451](https://github.com/contao/core/blob/3.5.30/system/modules/core/library/Contao/File.php#L447-L451)). In Contao 4 this function is never called anywhere any more though (but still present: [File.php#L408-L438](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/library/Contao/File.php#L408-L438)), thus this functionality is not there any more in Contao 4.

Now the directory for a new file has to be created manually, before writing a file. I am not sure if this is intentional?

**Comment by leofeyer** [comment]
Removing the method would be a BC break, therefore it is still in the code. But we are no longer using it.

**Comment by ausi** [comment]
> Now the directory for a new file has to be created manually, before writing a file.

@fritzmg Did you test this? If I’m reading the code correctly, parent folders still get created once the new file gets saved: https://github.com/contao/core-bundle/blob/a3b68142c327b787e01090d7d9c9737e699122b2/src/Resources/contao/library/Contao/File.php#L563-L567

**Comment by fritzmg** [comment]
In my case it didn't, but I'll test again.

**Comment by fritzmg** [comment]
@ausi the folder will only be created, if you manually close the (non existing) file first. But why would you have to close a file before writing it?

Consider the following code:
```php
$objFile = new \File('files/lorem/ipsum.txt');
$strIpsum = $objFile->getContent();
$strIpsum = $strIpsum . ' foo';
$objFile->write($strIpsum);
```
This works fine in Contao 3, even if the folder `files/lorem` does not exist. The folder (and file) will automatically be created, empty content is retrieved from the file and then the new content is written into the file.

However in Contao 4 this code does not work. Neither the file nor the folder is created and you will get the following error in the front end:
```
Warning: file_get_contents(files/lorem/ipsum.txt): failed to open stream: No such file or directory in vendor\contao\core-bundle\src\Resources\contao\library\Contao\File.php on line 607
```
This would work in Contao 4, but seems a bit silly:
```php
$objFile = new \File('files/lorem/ipsum.txt');
$objFile->close();
$objFile = new \File('files/lorem/ipsum.txt');
$strIpsum = $objFile->getContent();
$strIpsum = $strIpsum . ' foo';
$objFile->write($strIpsum);
```

**Comment by fritzmg** [comment]
This seems more and more like a bug to me - or at least it's very cumbersome to work with the `File` class in Contao 4 now due to this change. Is it discourraged to use this class in Contao 4+ in general?

**Comment by fritzmg** [comment]
Another problem I noticed: when using the `File` class in Contao 4, the content of the file will only be written, if you manually close the file, whereas in Contao 3 you did not have to manually close the file. Try the following in Contao 4 for example:
```php
$fs = new \Symfony\Component\Filesystem\Filesystem();
$fs->mkdir(TL_ROOT . '/files/foo');
$fs->touch(TL_ROOT . '/files/foo/test.txt');

$objFile = new \File('files/foo/test.txt');
$objFile->write('test');
```
The file `files/foo/test.txt` will be empty. Add another
```php
$objFile->close();
```
then the file `files/foo/test.txt` will have `test` in it.

**Comment by leofeyer** [comment]
> The following would work in Contao 4, but seems a bit silly:
> ```php
> $objFile = new \File('files/lorem/ipsum.txt');
> $objFile->write('');
> $objFile->close();
> $objFile = new \File('files/lorem/ipsum.txt');
> $strIpsum = $objFile->getContent();
> $strIpsum = $strIpsum . ' foo';
> $objFile->write($strIpsum);
> ```

You are right, we should create the directory if the file is written and it does not yet exist. But actually, you should do:

```php
$fs = new Filesystem();
$file = TL_ROOT.'/files/lorem/ipsum.txt';
$ipsum = '';

if ($fs->exists($file)) {
    $ipsum = file_get_contents($file);
}

$fs->dumpFile($file, $ipsum.' foo');
```

> in Contao 4, the content of the file will only be written, if you manually close the file, whereas in Contao 3 you did not have to manually close the file

The code which does this has not been changed:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/File.php#L154-L160

**Comment by leofeyer** [comment]
> @fritzmg Did you test this? If I’m reading the code correctly, parent folders still get created once the new file gets saved

Ah, true. Thanks for the heads up, @ausi. Then you can do:

```php
$strIpsum = '';
$objFile = new File('files/lorem/ipsum.txt');

if ($objFile->exists()) {
    $strIpsum = $objFile->getContent();
}

$objFile->write($strIpsum.' foo');
$objFile->close();
```

I'd still recommend to use the Symfony filesystem.

**Comment by fritzmg** [comment]
> The code which does this has not been changed:

I know, but this is what I observed. In Contao 4 you have to manually close the file in order for the contents to be actually written to the file. In Contao 3 you do not.
