### ISSUE TITLE
CSS body height issue in popup

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1179]
We are encountering a CSS issue in one of our Contao 4.4.7 systems. When the record edit form is shorter than the popup height and one of the field is select menu with the `chosen` script, the body within iframe gets a scrolling bar and the open chosen menu is cut off. See the demonstration on the image below:

![2017-11-08 at 10 01](https://user-images.githubusercontent.com/193483/32540209-4339a5be-c46c-11e7-836b-ee12d61d2bc9.png)

It looks like that the below part of CSS code in `main.css` is causing that:

```css
@media (max-width: 991px) {
    html, body {
        overflow-x: hidden;
    }
}
```

That rule also makes the `overflow-y: hidden;` as described here https://css-tricks.com/popping-hidden-overflow/#article-header-id-0

If it's not a good idea to remove that code just for popups, maybe it would be enough to add the `height: 100%;` to that rule.

**Comment by leofeyer** [comment]
Fixed in e9806404610a2d329f5001475c7d041983c14fc5.
