### ISSUE TITLE
"Redirect to last page visited" redirects to favicon.ico, if not present

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1180]
If your website does not have a favicon defined and there is no `favicon.ico` in the website's root and you enable the __Redirect to last page visited__ option in your login or logout module (or logout page), you will sometimes be redirected to `example.org/favicon.ico` (which will show the 404 page).

This is because the browser automatically looks for a `favicon.ico` in the website's root. Since it is not present, the `contao_catch_all` route generates a 404 page (see also the discussion in #1172) and thus the URL of this "page" is put into the session as the last page.

**Comment by aschempp** [comment]
I've had this in the backend as well. I guess the referer store listener should not handle 404s? :D

**Comment by leofeyer** [comment]
Fixed in 2994b6f4ffb17fb04e101b32a5e03577243dc978.
