### ISSUE TITLE
Unknown insert tags and flags are not logged (in the backend log)

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1182]
Unknown insert tag and flags (e.g. `{{non::sense|logme}}`) will return an empty string and should be logged. In the `InsertTags` class on line [964](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L964) and [1058](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L1058) the `monolog.logger.contao` service as called but nothing is shown in the log.

It looks like it's a problem in the `monolog.logger.contao` service. I haven't searched in the logger service for a bug yet, just found this problem when using the `decodeEntity` flag which is not correctly handled.

**Comment by fritzmg** [comment]
This kind of logging goes into `var/logs`. I am assuming this is intentional.

**Comment by agoat** [comment]
> This kind of logging goes into var/logs

I didn't found an entry in my log file in the first try (because it's full of debugging info like 'Matched route "_wdt"...'). But you are right. 

A unknown insert tag is logged in the var/logs file(s).

But does it make sense? A normal editor will never (be able to) look into these log files. I also expected an entry in the backend log first.

**Comment by aschempp** [comment]
Does it not log in the back end either?

**Comment by fritzmg** [comment]
In order for it to be logged to the back end the following context needs to be added:
```php
array('contao' => new ContaoContext($strFunction, $strCategory))
```
(see [System.php#L247-L265](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/library/Contao/System.php#L247-L265)), which `InsertTags::doReplace` currently does not do. It is only logged to `var/logs`.

**Comment by leofeyer** [comment]
It is not supposed to be logged in the back end IMO.

**Comment by leofeyer** [comment]
@contao/developers Where do we want to log unknown insert tags and unknown insert tag flags? In `var/logs` or in `tl_log`?

**Comment by aschempp** [comment]
I think it's a content management mistake so `tl_log` seems right to me.

**Comment by bytehead** [comment]
👍

**Comment by leofeyer** [comment]
Changed in 1737ce027f596926cf630268747a6946d80c19b8.
