### ISSUE TITLE
The insert tag flag 'decodeEntities' is documented but not handled

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1183]
On the contao manual page (for version 4.4) under [Managing content > Insert tags](https://docs.contao.org/books/manual/4.4/en/04-managing-content/insert-tags.html) the flag `decodeEntities` is listet but it's not handled in the [InsertTags](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L976) class.

The encodeEmail is handled (with calling `String::$flag()`), so we can simply add decodeEntities here, too:

```php
//@ InsertTags below Line 976

switch ($flag)
{
//...
    case 'encodeEmail':
    case 'decodeEntities': // << this is currently missing
        $arrCache[$strTag] = \StringUtil::$flag($arrCache[$strTag]);
        break;
```

**Comment by fritzmg** [comment]
It seems this was (mistakenly) removed when the `InsertTags` class was introduced in Contao 3.5.0.

**Comment by ausi** [comment]
I think it was intentionally removed in contao/core@f5ad1d00a3a7ea6e382ad1d7cd7589f7d5df35e9 (Contao 3.5.16)

**Comment by leofeyer** [comment]
Maybe you want to create a PR to update the documentation?

**Comment by agoat** [comment]
> I think it was intentionally removed in contao/core@f5ad1d0 (Contao 3.5.16)

Is there a reason why? Is it security relevant?
In my case, I tried to insert an HTML module with an iframe for piwik's optout option into the TinyMCE editor in the text of the privacy statement.

**Comment by Toflar** [comment]
> Is it security relevant?

Yes. It allows you to mask evil stuff by encoding it and the flag will then decode it again. I think at that time we didn't have any confirmed attack but we all felt unsafe about having it.
