### ISSUE TITLE
Insert Tag {{br}} generates Error in RSS-Feed if used in Event-Titles

### ISSUE THREAD

**Issue by balduin-kowalski** [contao/core-bundle#1187]
If you use {{br}} in an event-title and if an RSS-Feed is generated from the corresponding event-archive, an error occurs in the RSS-Feed. Depending from the used browser the event in question is just excluded from the feed, or an error-message is shown.

**Comment by fritzmg** [comment]
This can be reproduced in the Contao Online Demo. Add a `{{br}}` to any news title and then create the RSS feed. If you validate the resulting RSS feed, it will show the following error for example:

> line 1, column 442: XML parsing error: <unknown>:1:461: mismatched tag [help]
>
> `   ... ><item><title>New Contao Versions in<br> short intervalls</title><descri ...`

The RSS feed generation is simply missing a `strip_tags` after replacing insert tags.

**Comment by balduin-kowalski** [comment]
I got to mention, that the error does not occur, if you allowHtml for the Event-Titles and use a <br> instead of an {{br}}. In this case the RSS-Feed just strips the <br> from the code and generates no error.

**Comment by leofeyer** [comment]
Fixed in 182772b9fa37aae9f21207ddf887d7ec62393e6d.
