### ISSUE TITLE
Contao 4.4.7 installation error

### ISSUE THREAD

**Issue by sietsevandreven** [contao/core-bundle#1189]
When installing contao 4.4.7, the following error appears in the web/error_log file:

PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/usr/contao4/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 72

**Comment by bytehead** [comment]
You need to enable PHP 7.1: https://wiki.php.net/rfc/class_const_visibility

**Comment by fritzmg** [comment]
@sietsevandreven you should post this kind of question on the forum. You do not need to enable PHP 7.1, as Contao 4.4.7 is compatible with PHP 5.6. However, you probably made a mistake during the installation or a composer update.

**Comment by leofeyer** [comment]
@sietsevandreven Turned out that this was a problem with the managed edition and not a mistake of yours. https://github.com/contao/managed-edition/issues/25
