### ISSUE TITLE
Dropzone-Upload im Backend POST > Maximale Upload-Dateigröße

### ISSUE THREAD

**Issue by LinkingYou** [contao/core-bundle#1192]
Im aktuellen Contao 4.4.8 kommt es bei uns in einer speziellen Konstellation zu Problemen mit großen Dateien:

Ein Kunde möchte einige Bilder im Backend in die Dropzone hochladen. Die Bilder die der Kunde auf einmal in die Dropzone schiebt, haben folgende Größe (in dieser Reihenfolge): 16,7MB / 20,3MB / 16,3MB / 12,2MB / 11,4MB / 11,2MB. Folgende Einstellungen haben die einzelnen Komponenten:

Einstellung Apache:
`MaxRequestLen 30000000`

Einstellung Contao:
`Maximale Upload-Dateigröße: 25000000`

Einstellung php.ini:
```
post_max_size = 32M
upload_max_filesize = 32M
```
Im Grunde sollte das so funktionieren. Alle Bilder werden auch hochgeladen - nur die ersten beiden nicht (X-Symbol). Werden diese einzeln hochgeladen, funktioniert alles. PHP-Log zeigt keine Problem. Contao-Log auch nicht. Nur das Apache-Log hat einen Eintrag:

```
[Thu Nov 16 10:14:55.232937 2017] [fcgid:warn] [pid 27349] [client 123.123.123.123:55454] mod_fcgid: HTTP request 
length 30007296 (so far) exceeds MaxRequestLen (30000000), referer: https://www.die-domain-des-kunden.de/
```
Es scheint so, dass die Dropzone in einem Post immer zwei Dateien übertragen möchte. In diesem Falle also 16,7MB+20.3MB=37MB. Bei den folgenden Dateien kommt diese Konstellation nicht mehr zu Stande.

Deswegen vermute ich einen Bug in der Dropzone oder in der Konfiguration des Dropzone-Objects. Im Contao-Demo kann ich das leider nicht testen - Upload ist hier ja nicht erlaubt.

**Comment by fritzmg** [comment]
Die `MaxRequestLen` solltest du wohl eher auf zumindest `33554432` setzen, wenn du Uploads bis zu `32M` erlaubst.

**Comment by LinkingYou** [comment]
Da hast Du sicherlich recht (hab ich der Vollständigkeit halber auf dem Server angepasst). Ändert aber leider nichts an dem Verhalten.

**Comment by fritzmg** [comment]
Tatsächlich ist die DropZone im Contao Backend so konfiguriert, dass sie mehrere Dateien in _einem_ Request sendet. Siehe [DropZone.php#L60](https://github.com/contao/core-bundle/blob/4.4.8/src/Resources/contao/classes/DropZone.php#L60)

> __uploadMultiple__
> default: null
> Whether to send multiple files in one request. […]




http://www.dropzonejs.com/#config-uploadMultiple

**Comment by Toflar** [comment]
We could add `chunking: true` and `chunkSize: <maxUploadSize>` couldn't we?

**Comment by fritzmg** [comment]
Sounds reasonable. But does that provide any advantage? What if the `uploadMultiple` setting was simply removed?

**Comment by Toflar** [comment]
Well it would need to be supported by Contao but it would improve the speed when uploading lots of data. Imho this has to be either removed (as a hotfix anyway) but we could also think about having support for chunked upload.

**Comment by agoat** [comment]
+1 for `chunking`. 

Another problem with big uploads are timeouts (expecially on shared hosting environments).

**Comment by leofeyer** [comment]
Fixed in ec3bd92400677ee41624254a9e60381e519c2273.

**Comment by leofeyer** [comment]
Regarding chunked uploads: We should discuss this new feature separately from this bug request. Preferably in a pull request. 😄
