### ISSUE TITLE
BE_USER_LOGGED_IN does not work in front end anymore

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1193]
## Reproduction 

1. Log into the Contao back end. 
2. Create a new template called `analytics_test`.
3. Insert `<?php var_dump(BE_USER_LOGGED_IN);` into the template.
4. Activate the template in your page layout.
5. Do not log out of the back end and open a new tab for the front end.

The output will be
```
bool(false)
```
Tested in Contao 4.4.8.

**Comment by joergmoldenhauer** [comment]
Same in 3.5.17.

**Comment by fritzmg** [comment]
@joergmoldenhauer you should test in Contao `3.5.31`.

**Comment by aschempp** [comment]
The variable is only true if you enable the frontend preview!

**Comment by fritzmg** [comment]
Right, sorry for the confusion.
