### ISSUE TITLE
alpha transparency killed by image resizer with compressed pictures?

### ISSUE THREAD

**Issue by ngdot** [contao/core-bundle#1195]
Hi, If I upload an png with alpha transparency contao deletes this information while resizing(?), so the asset picture has no alpha transparency anymore. Setup: Contao 4.4.8 with PHP 7.1.11 and GD & imagick. 
Testfile from W3c can be found [here](https://www.w3.org/Graphics/PNG/alphatest.png).

Can anyone help?

**Comment by NicolasGoerlach** [comment]
Update: Only got the problem If i use compressed pictures. Tested: tinypng.com and gulp-image

**Comment by ausi** [comment]
I was not able to reproduce this. Resizing the testfile worked with GD and with Imagick.

**Comment by NicolasGoerlach** [comment]
Hm, maybe its a version problem of gd and imagick?
Which version do you use? And on what system?
I'm on stable Jessie with GD 2.1.1 and imagick 3.4.3.

**Comment by leofeyer** [comment]
@NicolasGoerlach Does the problem still occur?
