### ISSUE TITLE
Subpalette in type selector doesn't work in DCA

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1197]
Hello,

as I understood correctly, contao 4 supports nested sub palettes. That seems to be correct. But if my selector field is not a checkbox (char(1) in terms of sql) but a select field with multiple states, this results in failing behavior:

![screen](https://user-images.githubusercontent.com/1485098/33011818-5386117e-cddf-11e7-951a-3c33cbe1f89e.png)

In this case "Typ" and "Veröffentlichen" are selector fields with subpalettes.

Are nested sub palettes not supported for select fields being the selector field?

**Comment by leofeyer** [comment]
Can you please post your DCA code?

**Comment by Defcon0** [comment]
Strange, the issue seems to be solved now (without my fixing it). Either a contao update fixed it, or there was something wrong in my code. Nevermind ;)
