### ISSUE TITLE
Bug with permissions on tl_form_field.invisible

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1199]
The `invisible` field in `tl_form_field` does not have any label or any `eval` configuration. Thus you are unable to allow access to that field for a certain user group.
However, the access to it is checked in `toggleVisibility()`. So either the permission check has to be removed or the field configuration has to be extended so I can allow access to that field :-)

**Comment by leofeyer** [comment]
Fixed in 88f6d58dd0da94c2e00655d7cc70fb9f78069c93.
