### ISSUE TITLE
Console for web profiler

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#120]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/42) by @aschempp
Wednesday Feb 04, 2015 at 09:58 GMT

Just found this bundle, might be useful to include, also if we don't have a full composer support in Contao 4.0.

https://github.com/winzou/ConsoleBundle

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Tuesday Mar 03, 2015 at 08:19 GMT

+1

However, we should make sure that this is not a security issue.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Tuesday Mar 03, 2015 at 08:22 GMT

Absolutely. It also only works if `assets:install` is called. But composer does that by default, so…

Feel free to assign it to me.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Tuesday Mar 10, 2015 at 11:34 GMT

I've played a bit with this and came up with the following results:

1. It's a pretty neat console in the browser, allowing for things like `assets:install` etc.
2. It only runs Symfony console commands, but that still allows to execute database commands etc.
3. Looks like it can't run composer commands (by default)
3. There are several design problems in the current setup that prevent this from easily working (e.g. `RequestToken` check for all POSTs)

**Conclusion:** I still think this could be neat, but only if there is no alternative to e.g. `assets:install`

**Comment by importer** [comment]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @Toflar
Tuesday Mar 10, 2015 at 13:01 GMT

I guess it could be added as a feature in future, not something we need to spend time on now.

**Comment by aschempp** [comment]
Please move this to 4.x.x milestone.

**Comment by aschempp** [comment]
I think we should close this, as it's a feature everyone can install if necessary.
