### ISSUE TITLE
Feature: Inserttags for ID detection 

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1200]
It would be nice to have an inserttag that could detect the ID of event and news to use it in the templates or forms without writing the php code. 

For example I would like to use it in a hidden form field that is integrated per en extension in an event to detect the event title and to transform it to another reservation form where the event name appears automatically in the specified field. I can imagine following inserttag

```
{{event_title::eventID}}
{{news_title::newsID}}
```

or for all _elementID_

What do you think?

**Comment by asaage** [comment]
Not sure what you want to achieve. You can use ```{{page::pageTitle}}``` in the title-field of your detail-page.
```{{page::pageTitle}}``` should then be replaced with news/event-titles in form-fields on that page as well.

**Comment by m-vo** [comment]
If you're already editing the templates, what's wrong with PHP? If everything's Twig some day (...), things will probably get even simpler in the templates.

**Comment by leofeyer** [comment]
As @m-vo explained, the event data is already available in the templates. Try e.g. `$this->id` to retrieve the event ID.
