### ISSUE TITLE
Problems wehen installing contao with utf8mb4_unicode collation

### ISSUE THREAD

**Issue by igi-iwersen** [contao/core-bundle#1201]
Hello everybody,

there are some problems when installing contao with a mysql database within using UTF8mb4_unicode_ci Collation.
I have tried many times with many constellations and i think that there are still some errors and unexpected behaviors by contao.
I read the discussion here https://github.com/contao/core/issues/8484 and tried to use these inforamtions to get it done. 
Here is a list of actions i tried. Maybe it will help someone to find and fix possibly existing errors:

# Situation: 
- Clean Contao instance (3.5.31) on a localhost Windows System (XAMPP 3.2.1 with PHP 5.6.8 (also teste with PHP7) + MySQL 5.6.24).
- Usecase to test: Saving a Emoji character in a varchar tablefiled (https://emojipedia.org/grinning-face-with-smiling-eyes/).

## Step 1:
- Start install.php tool and set DB character set to UTF8mb4 and Table collation to utf8mb4_unicode_ci.
- Let contao do the update process and creates new tables.

## Result:
Fatal error: Uncaught exception Exception with message Query error: Specified key was too long; max key length is 1000 bytes (CREATE TABLE `tl_search` ( `id` int(10) unsigned NOT NULL auto_increment, `pid` int(10) unsigned NOT NULL default '0', `tstamp` int(10) unsigned NOT NULL default '0', `title` varchar(255) NOT NULL default '', `url` varchar(255) NOT NULL default '', `text` mediumtext NULL, `filesize` double unsigned NOT NULL default '0', `checksum` varchar(32) NOT NULL default '', `protected` char(1) NOT NULL default '', `groups` blob NULL, `language` varchar(5) NOT NULL default '',

## Step 2: Fix in dcaconfig.php and restart install.php:
$GLOBALS['TL_DCA']['tl_search']['config']['sql']['keys']['url'] = 'index(250)'; 
$GLOBALS['TL_DCA']['tl_search']['config']['sql']['keys']['text'] = 'index(250)'; 

## Result: 
The defined collation is UTF8mb4_unicode_ci (in phpmyadmin) but contao created all tables as UTF8mb4_general_ci.

## Step 3: Restart install.php and have a look to the messages in the table check area.
- A lot of changes are displayed:

ALTER TABLE `tl_article` CHANGE `title` `title` varchar(255) NOT NULL default '';
ALTER TABLE `tl_article` CHANGE `inColumn` `inColumn` varchar(32) NOT NULL default '';
ALTER TABLE `tl_article` CHANGE `keywords` `keywords` text NULL;
.
.
.

Nearly every table need to be changed. But even if i press the "update database" button, no changes evident.

## Result: 
Only the following changed are displayed (i think this are the knows problems which were talked about in the other github discussion)

ALTER TABLE `tl_files` DROP INDEX `path`, ADD KEY `path` (`path`(333));
ALTER TABLE `tl_member` DROP INDEX `email`, ADD KEY `email` (`email`);
ALTER TABLE `tl_user` DROP INDEX `email`, ADD KEY `email` (`email`);
ALTER TABLE `tl_version` DROP INDEX `fromTable`, ADD KEY `fromTable` (`fromTable`);
ALTER TABLE `tl_newsletter_recipients` DROP INDEX `email`, ADD KEY `email` (`email`);

## Step 5: Added these lines to fix in dcaconfig.php and reload the install.php:

$GLOBALS['TL_DCA']['tl_files']['config']['sql']['keys']['path'] = 'index(250)'; 
$GLOBALS['TL_DCA']['tl_member']['config']['sql']['keys']['email'] = 'index(250)';
$GLOBALS['TL_DCA']['tl_user']['config']['sql']['keys']['email'] = 'index(250)';
$GLOBALS['TL_DCA']['tl_version']['config']['sql']['keys']['fromTable'] = 'index(250)';
$GLOBALS['TL_DCA']['tl_newsletter_recipients']['config']['sql']['keys']['email'] = 'index(250)';

## Result: 
No errors / changes are displayed. The tables are UTF8mb4_general_ci and Emojis can be stored correctly. Unfortunately UTF8mb4_unicode_ci doesn't work.

## Result: 
install.php has some changes (see below) and wants to set collation to utf8_bin (never told contao to act this way):

ALTER TABLE `tl_article` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_form` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_member` CHANGE `username` `username` varchar(64) COLLATE utf8_bin NULL;
ALTER TABLE `tl_page` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_search_index` CHANGE `word` `word` varchar(64) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_user` CHANGE `username` `username` varchar(64) COLLATE utf8_bin NULL;
ALTER TABLE `tl_calendar_events` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_calendar_feed` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_faq` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_news` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_news_feed` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';
ALTER TABLE `tl_newsletter` CHANGE `alias` `alias` varchar(128) COLLATE utf8_bin NOT NULL default '';

## Result: 
Errors / changes are gone, database charset is UTF8mb4_unicode_ci but tables are still in UTF8mb4_general_ci (i expected UTF8mb4_unicode_ci).

---------------------

# Next example / test: Another Contao instance, with already (fresh) installed database and tables (the normal way, everything in utf8_general_ci).

## Result: 
No errors / no changes. Emojis cannot be stored in the database (clean default contao system).

## Result: 
Fatal error: Uncaught exception Exception with message Query error: Specified key was too long; max key length is 1000 bytes (ALTER TABLE tl_search CHANGE url url varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '') thrown in system\modules\core\library\Contao\Database\Statement.php on line 295

## Step 3: Fix in dcaconfig.php (like in the example before):

$GLOBALS['TL_DCA']['tl_search']['config']['sql']['keys']['url'] = 'index(250)'; 
$GLOBALS['TL_DCA']['tl_search']['config']['sql']['keys']['text'] = 'index(250)'; 

(no other errors are displayed).

## Result: 
Database is set to utf8mb4_unicode_ci, the tables are still set to utf8_general_ci (no mb4!) + Emoji cant be stored.

## Result: 
The index-length errors are displayed again (as previously seen).

## Result: 
In the install.php tool the collation is still utf8mb4_unicode_ci, database tables (phpmyadmin) are utf8_general_ci (no mb4!) BUT: Emojis can be stored correctly (even if the collections of the tables are uft8_general_ci!)

## Summery: 
- Errors in install.php tool if tables with utf8mb4_unicode_ci shall be created. Contao can't seem to create it. utf8mb4_general_ci seems to work out.
- The already known index length problems occurred.
- Contao wants to set the tables to uft8mb4_bin instead of utf8_unicode_ci
- No idea why Emojis can be stored, even if only database collation is UTF8mb4_unicode_ci and tables are utf8_general_ci.

**Comment by fritzmg** [comment]
Can you do such a report on Contao 4.4.8(+) as well?

**Comment by igi-iwersen** [comment]
I'll be glad to do that. Unfortunately it will take some time because I haven't worked with Contao 4 yet.

**Comment by aschempp** [comment]
We have changed database abstraction layer in Contao 4. We are not gonna change that in Contao 3.5, so please test it with Contao 4 and we'll see if we need to get that fixed in Doctrine DBAL Schema.

**Comment by fritzmg** [comment]
Related: #113

**Comment by leofeyer** [comment]
Full utf8mb4 support is not available before Contao 4.5.
