### ISSUE TITLE
Icon layout_.svg and other disabled icons missing

### ISSUE THREAD

**Issue by OMOSde** [contao/core-bundle#1202]
Used on https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_theme.php#L451

**Comment by leofeyer** [comment]
The following icons are missing:

* css_.svg
* modules_.svg
* layout_.svg
* sizes_.svg
* theme_export_.svg

@frontendschlampe Could you please open the existing icons (without underscore), desaturate them and send them to me?

**Comment by leofeyer** [comment]
Maybe we can generally desaturate icons via CSS or via the `<feColorMatrix>` SVG filter?

**Comment by frontendschlampe** [comment]
> The following icons are missing:
> 
> css_.svg
> modules_.svg
> layout_.svg
> sizes_.svg
> theme_export_.svg
> 
> @frontendschlampe Could you please open the existing icons (without underscore), desaturate them > and send them to me?

Yes - no problem

> Maybe we can generally desaturate icons via CSS or via the <feColorMatrix> SVG filter?

I have no experience with that - we have to try. But when I compare to "normal" pixel images and automatically desaturation it could have some unexpected results.

**Comment by leofeyer** [comment]
> it could have some unexpected results.

True.

**Comment by leofeyer** [comment]
@frontendschlampe What about this ticket? 😉

**Comment by frontendschlampe** [comment]
I'm sorry for delay. I will make them as soon as possible! :-(

**Comment by leofeyer** [comment]
I have added the icons in 53b2ab3ac64a3ae29a3a9cb23eff68a5edb86cdc. Thank you @frontendschlampe.
