### ISSUE TITLE
uncached insert tags do not load default language file

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1203]
A call to
```php
\System::loadLanguageFile('default');
```
seems to be missing for uncached insert tags.

## Reproduction

1. Activate the page cache in your site structure.
2. Insert the following into a HTML or text content element on a page: `{{date::l, d. F Y}}`.
3. Clear the page cache.
4. Log out of the back end.
5. Open the page containing the insert tag in the front end. You'll see `Sunday, 26. November 2017` as expected.
6. Refresh the page - now the page will be loaded from the page cache and you'll see `, 26. 2017`.

The `\Date::parse` function uses Contao's translations for weekdays and months for example. These translations will only be present, if `\System::loadLanguageFile('default');` is executed at any point. For the front end this is currently only done in `PageRegular::prepare` and when a user logs in.

**Comment by leofeyer** [comment]
The actual problem seems to be that the `Date` class does not execute `System::loadLanguageFile()` before accessing the `$GLOBALS['TL_LANG']` array.

**Comment by leofeyer** [comment]
Fixed in ba7fbf05a0add075652bcf48ec557c124fa9970b.
