### ISSUE TITLE
image sizes visible/not visible

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#1205]
Nearly every element (e.g. pages, modules, articles, news archives) can be switched visible and invisible but not the image sizes - there's only the possibility to hide the child elements of an image size. So it would be great if the parent image size could switched, too.

**Comment by fritzmg** [comment]
@leofeyer I think this also has been closed by mistake? I guess there is a lot of overlap with contao/contao and contao/core-bundle issue IDs right now.

**Comment by aschempp** [comment]
I don't think that would make sense. You can't toggle a news archive either, because that's an element a user chooses somewhere (e.g. in the news module settings). If you wanna hide an image size, remove it from the user permissions.
