### ISSUE TITLE
infinite redirect under certain circumstances

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1210]
This code
```php
// Redirect to the website root or language root (e.g. en/)
if (\Environment::get('relativeRequest') == '')
{
    if (\Config::get('addLanguageToUrl') && !\Config::get('doNotRedirectEmpty'))
    {
        $arrParams = array('_locale' => $objRootPage->language);

        $strUrl = \System::getContainer()->get('router')->generate('contao_index', $arrParams);
        $strUrl = substr($strUrl, strlen(\Environment::get('path')) + 1);

        static::redirect($strUrl, 301);
    }
    elseif (($objPage = \PageModel::findFirstPublishedByPid($objRootPage->id)) !== null)
    {
        // Redirect if the page is not the language fall back or the alias is not "index" or "/" (see #8498 and #8560)
        if (!$objRootPage->fallback || !in_array($objPage->alias, array('index', '/')))
        {
            static::redirect($objPage->getFrontendUrl(), 302);
        }
    }
}
```
from [Frontend.php#L343-L363](https://github.com/contao/core-bundle/blob/4.4.8/src/Resources/contao/classes/Frontend.php#L343-L363) causes an infinite redirect under the following setup for example:

## Reproduction

1. Create the following website structure: ![screenshot-2017-11-30 site structure - contao open source cms](https://user-images.githubusercontent.com/4970961/33436481-811b2274-d5e5-11e7-8aea-819cbad411be.png)
    * Set a page layout for each website root.
    * The English website root has the language `en` set and is __not__ the fallback.
    * The German website root has the language `de` set and it is the fallback.
    * The English _Home_ page has the Alias `index`, the German _Home_ page has the Alias `home`.
2. Set `contao.prepend_locale` to `false`.
3. Set the primary language of your browser to `en`.

Open the website (without a request parameter) in the frontend. Contao will redirect you infinite times.

## Cause

Since `addLanguageToUrl` is `false`, we will arrive at this bit of code:
```php
elseif (($objPage = \PageModel::findFirstPublishedByPid($objRootPage->id)) !== null)
{
    // Redirect if the page is not the language fall back or the alias is not "index" or "/" (see #8498 and #8560)
    if (!$objRootPage->fallback || !in_array($objPage->alias, array('index', '/')))
    {
        static::redirect($objPage->getFrontendUrl(), 302);
    }
}
```
Since the `Accept-Language` is `en` the root page found from
```php
$objRootPage = \PageModel::findFirstPublishedRootByHostAndLanguage($host, $accept_language);
```
will be the english one and the first published page within that website root is the English _Home_ page with the alias `index`. However, since that website root is __not__ defined as the fallback language, Contao will redirect to the first published page within the website root. And since that page has the alias `index`, the redirect will be an empty request and the whole thing starts over again.

**Comment by leofeyer** [comment]
Fixed in 8bdd9235f70c353919c65be6564c6fa1fe70dba6.
