### ISSUE TITLE
How to replace the Message class?

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1211]
This is a follow-up ticket to #445 and #490.

As discussed in Mumble on November 30th, 2017, the implementation in #490 is cumbersome to use.

```php
System::getContainer()
    ->get('session')
    ->getFlashBag()
    ->add('contao.my-scope.error', 'An error occurred')
;
```

Maybe there should be a service instead, which provides similar methods as in the `Message` class?

```php
System::getContainer()
    ->get('contao.messages')
    ->addError('An error occurred', 'my-scope' /* optional */)
;
```

**Comment by backbone87** [comment]
I think the basic impl on #490 was fine. just a `Messages` service is missing

**Comment by backbone87** [comment]
Just a quick scrible
```php
interface Message {
  public function text(): string;
  public function withText(?string $text): Message;
  public function params(): array;
  public function withParams(...string $params): Message;
  public function withAddedParams(...string $params): Message;
  public function scope(): string;
  public function withScope(): Message;
}
interface TranslatedMessage extends Message {
  public function translationDomain(): ?string;
  public function withTranslationDomain(string $domain): void;
}
interface Messages {
  public function add(Message $message, bool $skipDuplicate = true): void;
  public function addAll(array $messages, bool $skipDuplicates = true): void;
  public function get(?string $scope = null): array;
  public function getRendered(?string $scope = null, ?string $tpl = null): string;
  public function take(?string $scope = null): array;
  public function takeRendered(?string $scope = null, ?string $tpl = null): string;
  public function render(array $messages, ?string $tpl = null): string;
}
```

**Comment by aschempp** [comment]
Honestly I disagree. In a regular controller, adding flashes is pretty simple.

```php
class MyController
{
    public function __invoke(SessionInterface $session)
    {
        $session->getFlashBag()->add('vendor.whatever');
    }
}
```

The major advantage to me is that each developer uses their own message domain, and that is a **must**. Otherwise we will continue to have conflicts, modules showing flash message of others just because we use the same message scope!

I agree it's more cumbersome in old code, but that's because it's old code and we should get rid of that…

**Comment by backbone87** [comment]
So if someone requires a translated message he also needs to inject the translator? Sorry but this is too common of a pattern, which i think is worth having a small helper service for

**Comment by aschempp** [comment]
Well that's the default Symfony way, isn't it? So if that would be a real issue, I would assume Symfony would come up with something in their DX approach?

**Comment by backbone87** [comment]
it has nothing to do with symfony. The flash messages are part of the HttpKernel and translations come from the Translation component and there is no dependency between them. Symfony does not, will not and should not provide a service for every use case.

Contao messages are a concrete feature that can be solved by using symfony flash messages, twig and the translator. (In the old Contao way, translations were not provided out of the box with messages, but i would include this common task in the reworked Contao messages)

**Comment by aschempp** [comment]
Seriously? Symfony **provides a flash bag** which is explicitly made for **flash messages**? If they would not care about flash messages, they would ask you to simply write something to the session yourself.

**Comment by aschempp** [comment]
By the way, it's even simpler. Controllers already have a `$this->addFlash()` method.

**Comment by backbone87** [comment]
Please read carefully what i write. The feature set of Contao messages is not equal to the feature set of flash messages. Contao messages did also provide rendering. And i propose also adding translation features to Contao Messages. Why? Because its a very common task to translate Contao messages.

I never said we should not use flash messages as a foundation of contao messages. Actually the 3 services that the `Messages` service i proposed should use are `twig`, `translator` and `session`.

**Comment by aschempp** [comment]
Okay. I would not add three classes to abstract a task that can be done with three other classes.

**Comment by backbone87** [comment]
these 3 classes i want to introduce implement the contao message feature in a clean way. You can ofc also bloat the method arguments of the `Messages` service.

**Comment by aschempp** [comment]
Another interesting topic @bytehead just brought up is that translation can (and maybe should) be done when **outputting** messages, not when adding them. So `$this->addFlash('my.domain', 'my.problem.occured')` and then in the template use `$this->trans($this->getFlash('my.domain'))`.

**Comment by backbone87** [comment]
While i am not sure that this can be easily achieved (especially when you deal with nested translations), my proposal didnt make any statement about when the translation happens (adding or rendering time)
