### ISSUE TITLE
Fehlender Focus beim PopUp

### ISSUE THREAD

**Issue by Schmidty2** [contao/core-bundle#1213]
Contao 4.4.8: Wenn man auf einem iPad mit Safari, Firefox oder Chrome (iOS 11.1.2) ein Bild einfügen möchte, kann man im PopUp des Dateimanagers nicht nach unten scrollen, es scrollt der abgedunkelte Hintergrund. Hier fehlt der Focus auf dem PopUp-Fenster.
Aber auch bei anderen PopUp-Fenstern die Bearbeitungsmöglichkeiten bieten (z.B. Module über das Seitenlayout bearbeiten) ist dieses Verhalten vorhanden.

Das Ganze kann man in der Offiziellen Online-Demo nachvollziehen.

Bei Contao 3.5.x war dieses fehlerhafte Verhalten auch vorhanden, wurde bereinigt und ist dort jetzt ebenfalls wieder vorhanden (Contao 3.5.31 - https://github.com/contao/core/issues/8708).

**Comment by leofeyer** [comment]
Kann ich nicht bestätigen, denn auch hier ist @ausi's Code noch drin:

https://github.com/contao-components/simplemodal/blob/master/css/simplemodal.css#L78-L87

Kann sonst jemand das Problem reproduzieren?

**Comment by Schmidty2** [comment]
Ich habe jetzt mehrere Tests gemacht - ja, der Code ist vorhanden.
Aber: Es funktioniert definitiv nicht unter iOS 11.2.1, das Ganze kann in der Onlkine-Demo nachvollzogen werden.

**Comment by leofeyer** [comment]
@ausi /cc

> das Ganze kann in der Onlkine-Demo nachvollzogen werden.

Wie genau?

**Comment by ausi** [comment]
> iOS 11.1.2
> iOS 11.2.1

Mit welcher der beiden Versionen wurde getestet?

**Comment by ausi** [comment]
Ich kann den Fehler reproduzieren am iPad Air mit iOS 11.2 in der Online demo.

> Wie genau?

Neues Inhaltselement erstellen, „Add an image“ aktivieren und auf „Change selection“ klicken. Danach lässt sich die Dateiverwaltung nicht scrollen.

**Comment by Schmidty2** [comment]
Unter iOS 11.2.5 auf einem iPad Pro 9,7" (erste Generation) ist das Verhalten ebenfalls noch genau so vorhanden, die Dateiverwaltung (und andere z.B. Module über das Seitenlayout bearbeiten) lassen sich nicht scrollen.

**Comment by leofeyer** [comment]
Ich kann den Fehler auch auf dem iPad reproduzieren, allerdings funktioniert alles sobald ich die Web-Konsole aufmache. Das erschwert das Debuggen natürlich …

**Comment by ausi** [comment]
In meinen Tests tritt der Bug nur auf wenn die Adresszeile des Browsers ausgeblendet ist (durchs nach unten scrollen).

Anscheinend ist die Höhe im CSS `calc(100% + 1px)` zu gering bemessen, mit `calc(100% + 5px)` tritt der Bug bei mir nicht mehr auf.
