### ISSUE TITLE
"Auswahl aufheben" wird überlagert von Symfony-Icon im Dev-Modus

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#1216]
Leider kann man in der Dateiverwaltung kein Häkchen setzen bei "Auswahl aufheben", wenn der Dev-Modus aktiv ist:
![app_dev-modus](https://user-images.githubusercontent.com/4542730/33548850-e6782602-d8e8-11e7-9875-3e9edd1684c4.jpg)

**Comment by fritzmg** [comment]
Related: https://github.com/symfony/symfony/issues/23528 - allerdings weiß ich nicht, wie man den neuen profiler aktivieren kann.

Wenn du die Profiler Toolbar nicht brauchst, kannst du sie abschalten, indem du folgendes in die `app/config/config_dev.yml` einfügst:
```yml
web_profiler:
    toolbar: false
```

**Comment by leofeyer** [comment]
Du kannst auch einfach auf das Label "Auswahl aufheben" klicken.

**Comment by Samson1964** [comment]
Ja stimmt. Ich habe zwar auch darauf geklickt, aber man bekommt ja keine Info ob das da wirklich funktioniert.
