### ISSUE TITLE
Contao 4.4 Cron throws error with PHP 7.2

### ISSUE THREAD

**Issue by TB1234** [contao/core-bundle#1217]
With PHP 7.2.0 the latest Conto 4.4.8 version throws an error if you call the Contao cron.
Error: 

    Warning: count(): Parameter must be an array or an object that implements Countable in /home/.../vendor/lexik/maintenance-bundle/Listener/MaintenanceListener.php on line 184

PHP: 7.2.0
Contao: 4.4.8

**Comment by Toflar** [comment]
There are other issues, Contao 4.4 is not yet compatible with php 7.2.
@leofeyer pls update the `travis.yml` in the hotfix branch to test on 7.2 too :)

**Comment by leofeyer** [comment]
This has to be fixed in the maintenance bundle. There is a pull request already:

https://github.com/lexik/LexikMaintenanceBundle/pull/74

**Comment by leofeyer** [comment]
Version 2.1.3 of the LexikMaintenanceBundle has been released a couple of days ago.

**Comment by leofeyer** [comment]
Fixed in contao/manager-bundle@becf997eb3228d447f7f1c0cc70c6a79603c191a.
