### ISSUE TITLE
Network connection has been lost on mobile - Iphone

### ISSUE THREAD

**Issue by AgenceUpMotion** [contao/core-bundle#1221]
Hello

I develop a site to test contao 4 but it does not work on Iphone, Safari and Macos Safari.

I have the following message on Iphone and Safari: "Safari can not open the page because the network connection has been lost"

And on Iphone Google Chrome: "No internal connection, ERR_INTERNET_DISCONNECTED"

thank you in advance

**Comment by iGweb** [comment]
Hello,

I'm having the same problem as you!

I have a site to put in production very soon, so if you find the solution I am interested ;-)

Thank you

**Comment by Toflar** [comment]
You're both sitting in France. `ERR_INTERNET_DISCONNECTED` means you are disconnected from the Internet. Unfortunately, Contao needs the Internet to work...

PS: In case this was an April Fools' joke: It's December.

**Comment by leofeyer** [comment]
I also don't see how this has anything to do with Contao.

**Comment by AgenceUpMotion** [comment]
This is not a joke..
@leofeyer have you tested on iphone?

Look this : https://www.handi-defis.fr/

It works very well on desktop but not on Safari and Iphone.
I have wifi and internet.

Why close the subject?
What is the relationship with France?

**Comment by AgenceUpMotion** [comment]
Here is another link to test: 
http://cm.prod-web.fr/accueil.html

**Comment by Toflar** [comment]
What makes you think that a Connection Error is related to Contao? I'm sure you can open e.g. https://contao.org on your mobile phone. Maybe there's some connection issue with your server.

**Comment by AgenceUpMotion** [comment]
On my phone I have access to the backend:
https://www.handi-defis.fr/contao/
but not at the front:
https://www.handi-defis.fr/

Strange no?
If I had a server problem I would not have access to the backend?

**Comment by Toflar** [comment]
That's all pretty relevant information you should've probably included in the initial issue description.
Is it reproducible on demo.contao.org?

**Comment by AgenceUpMotion** [comment]
Unfortunately no, against the theme contao (http://theme-preview.org/en/dentist-contao-4) is not responsive on my iphone.
It can not have any relation.

Do you encounter the problem also on the website Handi Defis like me?

**Comment by Toflar** [comment]
> Do you encounter the problem also on the website Handi Defis like me?

I do yes. Which still does not make it a Contao problem yet. We need more information to help. You have to find out if there's a setting, extension, etc. that causes the problem. Is your website responsive or are you talking about the mobile layout?

**Comment by AgenceUpMotion** [comment]
On this test: http://cm.prod-web.fr/accueil.html
I only installed contao 4 doing nothing (one page, one page layout and one article). can I give you access if you want to see if everything is well configured?

**Comment by bytehead** [comment]
Is it (http://cm.prod-web.fr/accueil.html) on the same server as https://www.handi-defis.fr/ ?

**Comment by AgenceUpMotion** [comment]
No, both are hosted at OVH but not on the same server
PHP : 7.0
MYSQL v.5.6

**Comment by AgenceUpMotion** [comment]
when I reload the site on mobile, it displays very quickly (0.5sec) and then the problem message connection

**Comment by Toflar** [comment]
Without having more info on what is possibly causing the issue, we have absolutely no possibility to help here, sorry.

**Comment by bytehead** [comment]
Maybe it's related to OVH? http://community.ovh.com/t/connexion-reseau-perdue-depuis-ios-10-3-2/3031

**Comment by AgenceUpMotion** [comment]
I will give you the backoffice of the website, it can help you?

**Comment by Toflar** [comment]
> I will give you the backoffice of the website, it can help you?

No, as stated before, at the moment there's no reason to think Contao has an issue here. I'm reading what @bytehead linked a few minutes ago.

**Comment by Toflar** [comment]
Okay so after reading http://community.ovh.com/t/connexion-reseau-perdue-depuis-ios-10-3-2/3031/36 I'm very convinced there's an OVH configuration issue with the combination of SAPIs (cgi, php-fpm) and php versions. Try contacting the support.

**Comment by AgenceUpMotion** [comment]
can you tell me what you recommend as an exact version? to guide them during my phone call

**Comment by Toflar** [comment]
There are thousands of Contao setups out there, all using different combinations of supported php versions (5.6 - 7.1) and all common php server APIs (short: SAPI), from mod_php to fast-cgi to php-fpm. We have never encountered a similar issue.
Best choice is PHP 7.1 (or 7.2 as soon as Contao 4.4.9 is released and support is added) plus php-fpm for maximum performance. But what exactly causes the issue and why it happens only on mobile is not something anyone of us could find out. It must be related to the server configuration.

**Comment by AgenceUpMotion** [comment]
Thank you for your valuable help.
I contact the support OVH and you know about the problem if you wish.

One thing is on, I have good internet ^^
Sincerely

**Comment by AgenceUpMotion** [comment]
I just modified my OVH configuration
See attached image (http://www.hostingpics.net/viewer.php?id=398703Capture.png)

A new error appears?
Maybe not the right configuration

**Comment by AgenceUpMotion** [comment]
Everything works fine,
I just passed the PHP configuration from 7.0 to 7.1 and the phpcgi php engine

Thank you very much for your help and for taking the time to help me!

Long live contao ahah!

PS: Johnny is dead and it's not a joke on April 1st
