### ISSUE TITLE
4.5. beta3 - MySQL 5.5.7 oder 5.7.7

### ISSUE THREAD

**Issue by Ainschy** [contao/core-bundle#1226]
Hi,
laut Contao News zur Beta3 wird von MySQL 5.5.7 als Mindestanforderung beschrieben. Im weiteren Verlauf von der Version 5.7.7.

[https://contao.org/de/news/contao_4-5-0-beta3.html](url)

Ich hab auf meinem Hosting bei All-inkl. die MySQL 5.6.38 und bekomme die DB im Installtool nicht eingerichtet. Eine Migration einer 4.4.8 Contao DB lief auch nicht.

var/log sagt:

> [2017-12-10 20:50:35] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred while executing 'ALTER TABLE tl_newsletter_recipients CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci':\n\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes at /www/htdocs/wXXXXXX/webseiten/beta45/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:121, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes at /www/htdocs/wXXXXXX/webseiten/beta45/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes at /www/htdocs/wXXXXXX/webseiten/beta45/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []
[2017-12-10 20:52:00] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://cto4.xxxxxxxxxx.xyz/contao/install","method":"POST"} []

Laut Auskunft eines Contao Kollegen läuft bei all-inkl.com unter der MySQL 5.7.20 die 4.5beta3 problemlos.

VG.
Oliver

**Comment by fritzmg** [comment]
MySQL 5.5.7 alleine reicht nicht - es muss auch die config des MySQL Servers entsprechend angepasst werden. Siehe: https://github.com/contao/core/issues/8484#issuecomment-350256170

**Comment by andreheeke** [comment]
Ich halte nochmal als Ergänzung kurz fest das selbst bei All-Inkl - und das war bislang der Hoster wo alles lief - die RC1 nicht mehr in den Standard-Paketen Privat, PrivatPlus, Premium und Business installiert werden kann ohne in der config.yml die alten DB-Infos zu hinterlegen.
Ich bin mir unsicher ob das Ganze nicht etwas zu umständlich ist.

Musste die Umstellung auf den neuen innodb_large_prefix denn wirklich sein? Alle großen Hoster laufen maximal mit MySQL 5.5 in den Grundeinstellungen bei normalen Hosting-Paketen. Ich möchte meinen Kunden ungerne in einem Jahr erklären wieso wir nun auf teure, individuell eingerichtete Server umziehen müssen, wenn wir "am Zahn der Zeit" bleiben wollen.

Bin gespannt auf eure Meinung dazu. :)

**Comment by fritzmg** [comment]
> Alle großen Hoster laufen maximal mit MySQL 5.5

MySQL 5.5 hat im December 2016 den EOL erreicht...

**Comment by Ainschy** [comment]
@andreheeke bei All-inkl kannst du ohne Probleme den Support bitten ein i.d.R. kostenloses Update durchzuführen. Wird dann über Nacht durchgeführt, selbst wenn man es erst spät am Abend in Auftrag gibt.

**Comment by Seefahrer** [comment]
Habe ich letzte Nacht von All-Inkl machen lassen, der neue Server hat jetzt per default: php 7.1.11 und MySql 5.7.20.

**Comment by leofeyer** [comment]
Es geht ja auch ohne Probleme weiterhin mit MyISAM und utf8_general_ci, wenn man eine ältere MySQL-Version hat. Wir haben diese Kombination über 11 Jahre genutzt und nur weil MyISAM in MySQL 8 wegfällt, heißt es nicht, dass es plötzlich schlecht ist, MyISAM weiterhin in MySQL 5.5 zu nutzen!
