### ISSUE TITLE
Set the JPEG image quality

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#1228]
Hello,

in Contao 3.5 it was possible to set the jpeg image quality. We experienced that Google Insights is more content when setting the quality to 88% instead of 90%.

In Contao 4, there is no such setting anymore.
How could we adjust the image quality?

Thank you.

**Comment by xchs** [comment]
You can do this in the `app/config/config.yml` configuration file (see https://github.com/contao/core-bundle#configuration)
