### ISSUE TITLE
make the bredcrumb work like in 3.5

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1229]
the current breadcrumb looks kind of weird to me - it should not display something like "News Detail"
![image](https://user-images.githubusercontent.com/4138336/33882200-a04c11b6-df37-11e7-81df-0e5b99b44f16.png)

in Contao 3 it was using the pageTitle of the page in the first place and fell back to the name of the page if no title was not set.

![image](https://user-images.githubusercontent.com/4138336/33882285-e2ec3078-df37-11e7-8549-2a23c4f633d0.png)

I see concerns about the length of the breadcrumb https://github.com/contao/core/issues/7357 but this is something i would fix with css text-overflow: ellipsis

going this route:
 ![image](https://user-images.githubusercontent.com/4138336/33882337-0925baa2-df38-11e7-90e0-6d7b8197fd00.png) is somehow not very desirable.

**Comment by asaage** [comment]
im confused...
it's being messed around with...
https://github.com/contao/core-bundle/issues/822
i guess i just use my own custom template 😄

**Comment by fritzmg** [comment]
I cannot confirm, that what you are saying is true. In Contao 3.5, the result is the same as in Contao 4.4. i.e. it produces
```
Contao Official Demo > Modules > News > News Detail
```
and _not_
```
Contao Official Demo > Modules > News > News Headline
```
Though I agree that the last item should may be always be an insert tag, so that the title which might have been changed by a reader module is displayed.

**Comment by asaage** [comment]
you are right.
in 3.5 i was putting {{page::pageTitle}} into the PageTitle to achive this (which is still more convenient that putting it into the PageName-Field).
in 3.2 it was working like that right out of the box.
