### ISSUE TITLE
Make PageForward::getForwardUrl protected or add a hook to modify the forward url

### ISSUE THREAD

**Issue by pwaldhauer** [contao/core-bundle#1235]
Use case:

We have a special type of page to forward to an internal page, but with an added anchor (#-fragment) like:

`example.com/abcd` --> `example.com/any/other/path#test`

Currently we have to either copy the whole getForwardUrl method into our page type or use reflection to make it accessible.

Ref: https://github.com/contao/core-bundle/blob/2ec59c9ebb6579d4fb63ff992808ccfb64eb238b/src/Resources/contao/pages/PageForward.php#L57-L126

**Comment by leofeyer** [comment]
Changed in faedd63ab27aef0b4ae3486e8abb45bdfddaa439.
