### ISSUE TITLE
Thumbnail-size in Filemanager

### ISSUE THREAD

**Issue by rustykowski** [contao/core-bundle#1236]
The preview-images in filemanagers tree-view have a fixed height of 50px.
Depending on the subject, sometimes this is not enough to distinguish the pictures.
Would it be possible to make the thumbnail size configurable in the settings?

**Comment by Aybee** [comment]
I've done this in Contao 3.5 with the executeResize HOOK. Maybe this works in Conao 4. But making this configurable also will be nice.
```php
/**
 * Make bigger thumbs in BE by use of executeResize HOOK
 *
 * @param $objImage - the Image object
 *
 * @return void - no return value expected
 */
public function minThumbs($objImage)
{
  if(TL_MODE == 'BE' && $objImage->getTargetHeight() <= 50)
  {
    $objImage->setTargetHeight($objImage->getTargetHeight() * 1.5);
  }
}
```

**Comment by rustykowski** [comment]
Thank you Aybee!
Where has this function to be written? Can i put it into one of the config-files, or do i need a custom extension?

**Comment by m-vo** [comment]
@rustykowski In general the ``AppBundle`` would be the right place. If you've got one already, it's not much overhead: you can register this listener as a tagged service  (not documented yet, see #1094).

**Comment by leofeyer** [comment]
Since you are the first one to ever bring this up in over 11 years, I doubt that it is a common use case. Let's see what others think.

**Comment by Aybee** [comment]
This was asked once in the forum, so I developed this solution. I seldom use it by myself.

**Comment by leofeyer** [comment]
I'm closing this due to lack of interest.
