### ISSUE TITLE
Add a keyboard shortcut for the slide out back end menu

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1240]
Could we add a keyboard shortcut (e.g. <kbd>Alt</kbd> + <kbd>m</kbd>) to open and close the slide out back end menu? In principle, something similar to the menu keyboard shortcut (<kbd>m</kbd>) on `contao.org`.

**Comment by leofeyer** [comment]
The slide out back end menu is only available on mobile devices where you normally don't have a keyboard. What is your use case?

**Comment by xchs** [comment]
> The slide out back end menu is only available on mobile devices

If I reduce the size of the browser window accordingly, the slide out menu is also displayed on the desktop.

**Comment by leofeyer** [comment]
Is this a real use case or just a development issue?

**Comment by xchs** [comment]
> Is this a real use case

Yep, I currently have two browser windows arranged next to each other (so they fill the entire screen).
