### ISSUE TITLE
Wartungsmodus nicht mehr aktiv nach Aktualisierung auf 4.4.9

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#1241]
Eine Installation befindet sich im Wartungsmodus, ich aktualisiere die Installation auf Contao 4.4.9.

Danach ist der Wartungsmodus nicht mehr aktiv, der `maintenance_lock` in `var/cache` ist aber immer noch vorhanden.

Der Wartungsmodus ging in den letzten Contao-Versionen bei der Aktualisierung nicht verloren.

**Comment by leofeyer** [comment]
Kann das jemand reproduzieren?

**Comment by netzarbeiter** [comment]
Habe jetzt in einer frischen 4.4.9-Installation den Wartungsmodus aktiviert und gesehen, dass dieser die Datei `maintenance_lock` nicht in `var/cache` sondern in `var` erstellt. Bei einer 4.4.8 wird die `maintenance_lock` im Verzeichnis `var/cache` erstellt.

**Comment by xchs** [comment]
> Kann das jemand reproduzieren?

Ich konnte das gerade für ein Update von Contao 4.4.8 auf 4.4.9 reproduzieren. Der Wartungsmodus war nach dem Update nicht mehr aktiv.

**Comment by fritzmg** [comment]
> Habe jetzt in einer frischen 4.4.9-Installation den Wartungsmodus aktiviert und gesehen, dass dieser die Datei maintenance_lock nicht in var/cache sondern in var erstellt. Bei einer 4.4.8 wird die maintenance_lock im Verzeichnis var/cache erstellt.

Indeed, siehe https://github.com/contao/manager-bundle/blob/4.4.8/src/Resources/contao-manager/lexik_maintenance.yml#L9 vs. https://github.com/contao/manager-bundle/blob/4.4.9/src/Resources/contao-manager/lexik_maintenance.yml#L9

**Comment by leofeyer** [comment]
Stimmt, das haben wir umgestellt, damit der Wartungsmodus nicht automatisch beendet wird, wenn man den Cache leert. Insofern ist das ein "einmaliges" Problem beim Update von der 4.4.8 auf die 4.4.9.

**Comment by netzarbeiter** [comment]
Dazu hätte ich noch eine Frage, wenn ich in einer 4.4.8 den Cache über den Manager oder auch über die Konsole lösche, bleibt der Wartungsmodus aktiv, wann wird er automatisch beendet?

**Comment by fritzmg** [comment]
Das passiert nur, wenn du den gesamten `var/cache` Ordner manuell löschst. Wenn du den Cache über den Contao Manager oder die jeweiligen Kommandos auf der Konsole löschst, wird ja nur entweder `var/cache/prod` oder `var/cache/dev` gelöscht.
