### ISSUE TITLE
Asterisk not preserved in search panel

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1242]
When I search for e.g. a page alias `*destination-in-24h` it correctly finds `foobar/folder/destination-in-24h` but the input field in the filter panel only contains `destination-in-24h` instead of `*destination-in-24h`.

**Comment by leofeyer** [comment]
This is actually intended:

https://github.com/contao/core-bundle/blob/8b85d5aa99e853dfc4c4153348ada454c4239ef3/src/Resources/contao/drivers/DC_Table.php#L5069

A leading asterisk would break the regex.
