### ISSUE TITLE
BE_USER_LOGGED_IN not set by ContaoFramework::initialize

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1244]
Many of the `findPublished…` methods of Contao's Models use something like this:
```php
if (isset($arrOptions['ignoreFePreview']) || !BE_USER_LOGGED_IN)
{
	$time = \Date::floorToMinute();
	$arrColumns[] = "($t.start='' OR $t.start<='$time') AND ($t.stop='' OR $t.stop>'" . ($time + 60) . "') AND $t.published='1'";
}
```
This is supposed to ensure that only published items are returned, _unless_ the `BE_USER_LOGGED_IN` constant is `true` or the `ignoreFePreview` model option is set.

(_Note:_ in Contao `4.4.9`, `Model::isPreviewMode` was introduced, which implements the same logic.)

However, imagine a custom route where you do the following:
```php
/**
 * @Route(defaults={"_scope" = "frontend", "_locale" = "de"})
 */
class DefaultController extends Controller
{
    /**
     * @Route("/foo", name="foo")
     * @return Response
     */
    public function fooAction(Request $request)
    {
        $this->container->get('contao.framework')->initialize();
        System::loadLanguageFile('default');
        $objFoo = SomeModel::findPublishedByFoo();

        // …
    }
}
```
In this case, the model will select also the _not published_ items from the database, because the `BE_USER_LOGGED_IN` constant is never defined - which means PHP treats it as the string `'BE_USER_LOGGED_IN'` which evaluates to true.

Currently, `ContaoFramework::setConstants` sets this constant _only_ if the request is __not__ a front end request (or when there is no request). Probably because the constant is set in `Contao\FrontendIndex` as well.

Thus, if you manually initialize the Contao Framework (within your own route for instance), you have to make sure yourself that this constant is defined as well, otherwise the `Model::findPublished…` methods will not work as expected.

**Comment by leofeyer** [comment]
This is why we have added the `Model::isPreviewMode()` method.

**Comment by fritzmg** [comment]
Right, sorry, I missed that that method actually adds a defined check (and a type check).
