### ISSUE TITLE
remove Guillemets from pagination

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1245]
Last year the arrow brackets where removed from the mod_booknav template (https://github.com/contao/core-bundle/commit/d7239fa8b23805554c52b7f857cfab38fdbb09f3).
The pagination template however still renders  Guillemets `«` `»` in the first and last items (this time originating from the translationfiles)
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/de/default.xlf#L2184
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/de/default.xlf#L2196

**Comment by leofeyer** [comment]
We need to adjust the source file: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/languages/en/default.xlf#L1644

**Comment by leofeyer** [comment]
Removed in aad08292279affabd9584013aa50e5034d695e29.
