### ISSUE TITLE
Don’t replace the $GLOBALS array

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#1252]
In https://github.com/contao/core-bundle/blob/8ca706c4e5f21c9ca2044069b2919689654b9f58/src/EventListener/GlobalsMapListener.php#L37 the `$GLOBALS` variable gets replaced. This seems to cause very weird issues in PHP. After that line gets executed no new global variables get added to `$GLOBALS` anymore. This breaks for example the access to `$GLOBALS['objPage']`.

**Comment by leofeyer** [comment]
Fixed in 58f5e92e66ed50a8350f7098ca85a76e0006a0c5.

**Comment by leofeyer** [comment]
Fixed in 1334e636a1ad8f1a8d4646acfdbe3e7f8958a1bf.
