### ISSUE TITLE
Problems with using contao-console in cronjob

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1254]
Hello,

my hoster serverprofis.de recently (whyever) decided to remove the php-cli direct symlink for me on the shell. The consequence of this is that I can only use php in cronjobs (i.e. in crontab -e). But here command line parameters don't work since it's the fcgi-cgi-version of the php binary which ignores command line parameters. In fact calling

`php <mypath>/vendor/bin/contao-console somecommand`

simply calls 

`php <mypath>/vendor/bin/contao-console`

Since having php-cli back is not an option for the hoster (which is great besides that) the hoster offered lsphp as the alternative which has more performance (in their opinion, I honestly can't say if that's right).

So calling

`lsphp <mypath>/vendor/bin/contao-console somecommand`

works, but only if I remove the first line in contao-console which is

`#!/usr/bin/env php`

else I would get:

```
#!/usr/bin/env php
11:03:58 ERROR     [console] Error thrown while running command "acme:my-proj:subscription-observer". Message: "Failed to start the session because headers have already been sent by "/home2/acme/stage.my-proj.de/vendor/contao/manager-bundle/bin/contao-console" at line 2." ["error" => RuntimeException { …},"command" => "acme:my-proj:subscription-observer","message" => "Failed to start the session because headers have already been sent by "/home2/acme/stage.my-proj.de/vendor/contao/manager-bundle/bin/contao-console" at line 2."] []


  [RuntimeException]                                                                                                                                                          
  Failed to start the session because headers have already been sent by "/home2/acme/stage.my-proj.de/vendor/contao/manager-bundle/bin/contao-console" at line 2.  


acme:my-proj:subscription-observer [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

When removing the first line in contao-console, everything seems to be working fine (at least in my 3 test cases). So is it an option to have a version of that file without the first line? Of course I could add this file to one of my private modules but this is not update safe as you might guess ;-)

Thanks in advance.

Bye!

**Comment by fritzmg** [comment]
Just create your own "console" file with the contents of the regular contao-console, sans `#!/usr/bin/env php`. Then execute
```
lsphp your-console some:command
```

**Comment by Defcon0** [comment]
Already did that ;-) But it's not really an update safe solution :-(

**Comment by fritzmg** [comment]
The first line cannot be removed, otherwise you would not be able to execute the console without having to define the PHP CLI. You need to create your own console interface and maintain it accordingly.

However there might be additional drawbacks as some commands might check for `PHP_SAPI === 'cli'` which will not work in your environment.

As already mentioned on the forum, you should use a hosting environment with a proper PHP CLI.

**Comment by Defcon0** [comment]
I already feared that, but I do understand, of course. Though I'm quite confident that the check you mentioned won't be a problem.

Changing the hoster currently is not an option since the hoster is very good in terms of pricing and configurability of products (if you know a hoster at the same pricing level, please let me know via private message ;-) ).

**Comment by fritzmg** [comment]
> and configurability of products

Evidently it is not? ;)



> if you know a hoster at the same pricing level, please let me know via private message

Ask for suggestions in your forum thread and provide information on the price and performance level.

**Comment by Defcon0** [comment]
OK, I'll do so.

> and configurability of products

I meant configurability of which functions I want to pay for and which of them not. Often I can book single options like my own ip without booking some higher package. Of course in this case, the hoster is a pain :-(
