### ISSUE TITLE
addToUrl hängt ein "_local=..." als GET-Parameter an

### ISSUE THREAD

**Issue by zonky2** [contao/core-bundle#1257]
Wird in einem Template eine URL-Generierung erzeugt 
```
$ortUrl = '<a href="'  . \Frontend::addToUrl('orderBy=schulungsort_ort&orderDir=ASC') . '">Ort</a>';
```

wird ein `_locale=de` als GET-Parameter angehangen und nach erneutem Aufruf ist der Parameter "in der URL" als /_locale/de ... nach erneutem Aufruf kommt eine 404

siehe https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Frontend.php#L441

Workaround: `..._locale=&` mit als Parameter in die addToUrl

C 4.4.8

**Comment by leofeyer** [comment]
Fixed in a21e52b4568de0fe5649820c16b8ad8d17ca28c7.

**Comment by zonky2** [comment]
THX!
