### ISSUE TITLE
Missing DataContainer-Parameter in onload_callback in ModuleRegistration

### ISSUE THREAD

**Issue by Xirdion** [contao/core-bundle#1259]
If you add a onload_callback to tl_member you expect the DataContainer-object as parameter.

The Registration-Module also calls the callback-functions (ModuleRegistration.php line 85). But it does not add the the  DataContainer-Object as argument. So when the module gets called there is an error-message.

`[2017-12-20 16:10:01] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Too few arguments to function Foo\\BarBundle\\Resources\\contao\\dca\\tl_foo_member::onloadCallback(), 0 passed in /Applications/MAMP/htdocs/project/vendor/contao/core-bundle/src/Resources/contao/modules/ModuleRegistration.php on line 85 and exactly 1 expected at /Applications/MAMP/htdocs/project/var/cache/prod/contao/dca/tl_member.php:1024)"} []`

contao-core: 4.4.9
php: 7.1

**Comment by Aybee** [comment]
I'm struggeling about this just today in Contao 2.11 ;). There also is no DataContainerObject with the onload_callback. https://docs.contao.org/books/manual/2.11/en/06-Data-Container-Arrays.html#table-configuration

Just to tell that there maybe never was one.

**Comment by aschempp** [comment]
That is a known limitation, you have to adjust your callback accordingly.

**Comment by Xirdion** [comment]
Thanks for the info. So this is not a bug but only a limitation. I can easily avoid this error with a default value for the parameter. I close this issue.
