### ISSUE TITLE
Replace rand() with random_int()

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1261]
Replace `rand()` with `random_int()` or at least `mt_rand()`.

**Comment by Toflar** [comment]
`random_bytes()` is the only one you should use if you want it to be really secure :)

**Comment by leofeyer** [comment]
It is just to select a random image from an array of images, so … 😄

**Comment by ausi** [comment]
@Toflar AFAIK `random_int()` uses the exact same source as `random_bytes()` does.

**Comment by ausi** [comment]
@leofeyer `random_int()` requires PHP 7, so I don’t think we can use that in Contao 4.4.

**Comment by Toflar** [comment]
> @Toflar AFAIK random_int() uses the exact same source as random_bytes() does.

Yeah, the original issue description did not contain `random_int()` ;)

**Comment by leofeyer** [comment]
It sure did.

**Comment by aschempp** [comment]
`random_int` is polyfilled by https://github.com/paragonie/random_compat so we sure can use it in Contao 4.4

**Comment by leofeyer** [comment]
Fixed in 049cf3cb8b9850db21f67cead8596f52c60c7cd4.
