### ISSUE TITLE
4.5-RC2 Setting the backend language doesn’t work anymore

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#1264]
Changing the language in backend on the profile page doesn’t work.

**Comment by aschempp** [comment]
Is it not saved or not applied?

**Comment by ausi** [comment]
It gets saved, but no applied.

**Comment by ausi** [comment]
If I log out after changing the language and then login again it gets applied correctly.

**Comment by leofeyer** [comment]
See #1266.
