### ISSUE TITLE
Don't mark copied content elements with (copy) in the headline

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1267]
Currently (4.4.9 and 4.5.0-RC2) when copying a content element (e.g. text), the headline is rewritten to something like '... (copy)'. IMO this makes almost no sense for content elements.
This was also discussed in 2011 (https://github.com/contao/core/issues/2938) when the feature to mark copies was implemented .

Using the idea of @dmolineus in #586 might be useful.

**Comment by leofeyer** [comment]
See #586.
