### ISSUE TITLE
Formular-Element Erklärung wird nicht richtig interpretiert

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#1268]
Sowohl in Contao 3.5.31 als auch in Contao 4.4.8 gibt es Probleme beim Wechseln eines Elementtyps im Formulargenerator.

![formulargenerator](https://user-images.githubusercontent.com/4542730/34325901-3179529a-e8a0-11e7-912b-10be4d0ec255.jpg)

Ich habe in meinem Formular ein Element "Erklärung" und ein Element "Textfeld". Beide haben den internen Namen "email". Das Erklärungsfeld war vorher ein Textfeld mit dem Namen "email". Ich habe es später als Erklärungsfeld weiterverwendet. Dabei wird leider der Name "email" nicht vergessen.
Im FE wird das Erklärungsfeld ganz normal angezeigt, wenn das "richtige" E-Mail-Feld nicht vorhanden ist. Gibt es aber ein "richtiges" E-Mail-Feld (wie in der Grafik), dann wird das "richtige" E-Mail-Feld nicht angezeigt und das Erklärungsfeld wird zum E-Mail-Feld.

Soweit klar, oder muß ich das in der Demo Schritt für Schritt nochmal nachbauen (falls es geht)?

**Comment by fritzmg** [comment]
Ich kann das Problem nachvollziehen. Passiert zB auch wenn man _Speichern und duplizieren_ benutzt. Und es passiert prinzipiell mit allen Formular Feldern, bei denen man keinen Feldnamen setzen kann. Also auch bspw
Fieldsets. 

Das Problem mit _Speichern und duplizieren_ könnte man zumindest mit einem `doNotCopy => true` reduzieren.

**Comment by leofeyer** [comment]
Behoben in 92302aadaff0e3409efe76acfc01031f8fd62650.

**Comment by fritzmg** [comment]
@leofeyer this might still lead to problems with custom form fields that have no `name`, wouldn't it?

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by fritzmg** [comment]
If an extension adds another form field type that has no `name` in its palette, the same problem would still occur, since it will not be catched by
```php
\in_array($objFields->type, array('explanation', 'fieldset', 'html', 'captcha', 'submit'))
```

**Comment by leofeyer** [comment]
Changed in 170fff7f5899d5823196ad0b73a6e946285d815e.
