### ISSUE TITLE
4.4 Selecting a directory doesn’t keep the sort order

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#1270]
If you select a directory in the settings of a gallery for example, the sort order gets mixed up.
Tested in the online demo:

<img width="871" alt="bildschirmfoto 2017-12-27 um 12 31 45" src="https://user-images.githubusercontent.com/367169/34380514-408df538-eb02-11e7-924b-9df377a2820c.png">

<img width="324" alt="bildschirmfoto 2017-12-27 um 12 31 59" src="https://user-images.githubusercontent.com/367169/34380517-455d77be-eb02-11e7-9b2d-11ed5e0fae53.png">

**Comment by leofeyer** [comment]
Fixed in 47ff17e6695ff99f0caa69bd06ffc882f3e6ea34.
