### ISSUE TITLE
Registry optional in the DcaSchemaProvider class

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1271]
@contao/developers Why is the second constructor argument of the `DcaSchemaProvider` class optional?

https://github.com/contao/core-bundle/blob/4967d3a7adc85d0d706d58e9bdf4726563d08983/src/Doctrine/Schema/DcaSchemaProvider.php#L43

We are not handling the case `null === $this->doctrine` so the argument is required implicitly.

**Comment by ausi** [comment]
It was introduced in #725, probably because of BC.
Maybe we forgot to get the registry from the container if the parameters is missing in the constructur?

**Comment by leofeyer** [comment]
> probably because of BC

I think so, too. However, to remain backwards compatibility, it is not enough to make new constructor arguments optional. We also have to handle the case that they are not set in the code. 😄 

We can make the argument non-optional now, because it was never really possible to omit it without a bunch of null pointer exceptions.

**Comment by leofeyer** [comment]
Fixed in a33df23777bb90140d7d16e50b5783079ac15fe7.
