### ISSUE TITLE
Remember me does not work in prod

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1272]
The remember me feature does not work in production.

* Log in in the front end with "remember me" enabled
* Navigate to an unprotected site
* You should have a `PHPSESSID` and a `REMEMBERME` cookie
* Delete the `PHPSESSID` cookie
* Reload the site
* The `REMEMBERME` cookie is gone

```
security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\CookieTheftException(code: 0): This token was already used. The account is possibly compromised. at vendor/symfony/symfony/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php:70)"} []
```

The issue does not occur in development. @aschempp @bytehead /cc

**Comment by aschempp** [comment]
see #1275

**Comment by leofeyer** [comment]
See #1280.
