### ISSUE TITLE
Require fully authenticated to change passwords

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1273]
If a member is authenticated based on a remember me cookie, they should be required to re-authenticate before changing their password (and maybe more?).

**Comment by aschempp** [comment]
We simply need to throw an `AccessDeniedException` which will be handled by the firewall listener (see https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ExceptionListener.php#L120)

**Comment by leofeyer** [comment]
We should check the `IS_FULLY_AUTHENTICATED` role before throwing the exception. 😉

**Comment by leofeyer** [comment]
> We simply need to throw an `AccessDeniedException` which will be handled by the firewall listener

Unfortunately this does not work. I'm getting stuck here:

https://github.com/contao/core-bundle/blob/5e8f65ba154b6fef6b0d2b1701ff980b2c855d1c/src/Controller/FrontendController.php#L100-L102

**Comment by leofeyer** [comment]
Never mind, I forgot to create a 401 page in the site structure.

**Comment by leofeyer** [comment]
@contao/developers Of course the login form shows "You are logged in as …" in this case, because the member is logged in (just not fully authenticated). Do we want to log out the member or do we just show the login form? The latter implies that the member can navigate to another menu item and keep being logged in (based on the remember me cookie).

**Comment by leofeyer** [comment]
See #1610.
