### ISSUE TITLE
Distinguish between 401 and 403

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1274]
We should distinguish between 401 (not authenticated) and 403 (authenticated but insufficient permissions). This implies adding a new page type 401.

In this context, we might want to remove the logout page type, as this is now handled by Symfony.

**Comment by aschempp** [comment]
We need to register an `access_denied_handler` in the firewall that renders the 403 page type, and replace the existing `error_403` handling with the 401 page type.

**Comment by leofeyer** [comment]
See #1381.
