### ISSUE TITLE
Under contao 4.5.0 the "switch user" operation doesn't work in the backend in the user module.

### ISSUE THREAD

**Issue by markocupic** [contao/core-bundle#1276]
Hello
In the backend in tl_user the "switch user" operation doesn't work under contao 4.5.0.
Can someone confirm this issue?

**Comment by leofeyer** [comment]
Yes, unfortunately. 😢

**Comment by leofeyer** [comment]
@aschempp I am 100% sure that this worked in version 4.5.0-RC2.

**Comment by aschempp** [comment]
me too 😢

**Comment by aschempp** [comment]
interestingly, it does work in the `app_dev.php`

**Comment by aschempp** [comment]
I'm pretty sure this is a preflight issue again, because the firewall switches the user but the new token is not saved in the session due to the preflight abort.

**Comment by leofeyer** [comment]
See #1280.
