### ISSUE TITLE
4.5 - CSS-Klassen in Backendnavigation unterschiedlich zu 4.4 (title-Attribut fehlt ebenfalls)

### ISSUE THREAD

**Issue by OMOSde** [contao/core-bundle#1278]
Beispiel - Navigationspunkt Dateiverwaltung - 4.4:

`<a href="/app_dev.php/contao?do=files&amp;ref=_3ZQasiW" class="navigation files" title="">Dateiverwaltung</a>`

in 4.5:

`<a href="/app_dev.php/contao?do=files&amp;ref=_lBs9CSM" title="" class="navigation system">Dateiverwaltung</a>`

Kommt sicher durch die Umstellung auf das knpMenu. Wenn man in https://github.com/contao/core-bundle/blob/master/src/EventListener/BackendMenuListener.php#L67 $moduleName anstatt $categoryName verwendet, sind die ursprünglichen Klassen wieder vorhanden.

**Comment by leofeyer** [comment]
Behoben in 3274e0bb1729b6caeee97bc3214479bb6c41b12d.
