### ISSUE TITLE
Feature: Make files downloadable in the backend filemanager, even if the folder is not public

### ISSUE THREAD

**Issue by markocupic** [contao/core-bundle#1279]
Contao sends an error 404, when I try to download a file inside a protected folder in the filemanager of the Contao backend. 
Could it be a feature that file downloads are realised via the File::sendToBrowser method? Of course it is necessary to check users privileges before.

**Comment by leofeyer** [comment]
This seems to be the case already?

https://github.com/contao/core-bundle/blob/6e5f7c211791d8a8be66fe75fc3e4f2c9e0de582/src/Resources/contao/controllers/BackendPopup.php#L97-L102

**Comment by markocupic** [comment]
To trigger the download dialogue the href should be something like this. Shouldn't it?

`<a href="contao/popup?download=true&src=files/some_folder/some_file.docx">`
But in fact it is: 
`<a href="files/some_folder/some_file.docx">`

Tested on on clean contao 4.5 installation without any 3rd party extensions.

**Comment by markocupic** [comment]
I can fix the issue by hacking line 2750 of DC_Folder.php.

`$return .= '<a href="contao/popup?download=true&src='. base64_encode($currentEncoded).'" title="'.\StringUtil::specialchars($GLOBALS['TL_LANG']['MSC']['view']).'" target="_blank">' . \Image::getHtml($objFile->icon, $objFile->mime).'</a> '.$strFileNameEncoded.$thumbnail.'</div> <div class="tl_right">';`

**Comment by xchs** [comment]
> @markocupic Contao sends an error 404, when I try to download a file inside a protected folder in the filemanager of the Contao backend

How do you try to download the file? Do you click on the file icon ("View in a new window")? Or do you open file details via the info icon and click the button "Download the file"? In the first case I also get an error 404 (which is understandable), in the second case, however, the file is offered to me correctly for download (via a download link of the form `https://example.com/contao/popup?src=ZmlsZXMvdGVzdC9fYWxlbmRlcjIwMTgucGRm&download=1`)

**Comment by markocupic** [comment]
Oh my god!
I did not know, that there is a download button. (That isn't very intuitive.)
Well, then I close this issue. Hannes, thank you very much.
