### ISSUE TITLE
Trusted proxies

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#128]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/50) by @aschempp
Wednesday Feb 18, 2015 at 08:00 GMT

The trusted proxies from Contao configuration should be set in the Symfony container.

http://symfony.com/doc/current/reference/configuration/framework.html#trusted-proxies

**Comment by trevorff** [comment]
Thank yo a lot for sharing. As for me, the most trusted proxies are the socks5 I buy from http://buy.fineproxy.org/eng/ website. They are really realiable and never gave up on me. Thanks again ;)

**Comment by trevorff** [comment]
Thank yo a lot for sharing. As for me, the most trusted proxies are the socks5 I buy from http://buy.fineproxy.org/eng/ website. They are really realiable and never gave up on me. Thanks again ;)

**Comment by Toflar** [comment]
As discussed on Mumble on April 8th, we need to do the following:

* Remove the legacy proxy settings as upgrading from Contao 3 to 4 is not possible anyway
* Adjust the `Environment` class to use the Symfony proxy settings for BC

**Comment by leofeyer** [comment]
See #176.
