### ISSUE TITLE
Session handling in Contao 4.4

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1283]
I am referring to #1260, which has solved the legacy session access problem for Contao 4.5. However, it seems we have not fixed it in Contao 4.4 yet, have we?

@Toflar /cc

**Comment by Toflar** [comment]
I think we have to wait for Symonfy because there are yet more changes to that. Currently I guess all of the reverse proxy caching is just simply broken and we cannot do anything about it until the situation is clarified.

**Comment by leofeyer** [comment]
This ticket is not about the broken HTTP cache caused by the session changes in Symfony. It is about legacy session handling (starting the session as soon as someone accesses `$_SESSION`).

Don't we have to always start the session when the framework is initialized in Contao 4.4?

**Comment by aschempp** [comment]
We should, but I think it was only by accident.

**Comment by leofeyer** [comment]
As discussed in Mumble on Januar 18th, 2018, we want to add a response listener that makes the response public depending on the page settings and that is triggered after the one that automatically makes the response private. The listener should also check if the response is cacheable.

**Comment by leofeyer** [comment]
The listener needs to be removed again in Contao 4.5.

**Comment by leofeyer** [comment]
> The listener needs to be removed again in Contao 4.5.

After further analyzing of the session usage in Contao, I believe we also need the listener in version 4.5. There is a lot of

https://github.com/contao/comments-bundle/blob/bc9c347dbfe722352082605fad17f9bab08cfe5d/src/Resources/contao/classes/Comments.php#L285-L296

and ignoring our cache logic – may it be good or bad – would break BC.

**Comment by Toflar** [comment]
The logic is also needed for FOSHttpCacheBundle's UserContextListener. I'll check with @dbu what we can do here.

**Comment by leofeyer** [comment]
I have reverted the changes, because they feel wrong. We have to thoroughly discuss cache and session handling on the next developer's meeting.

**Comment by aschempp** [comment]
So it will stay broken for another month?

**Comment by leofeyer** [comment]
The reverted changes do not fix the issue, either, so yes, sadly.

**Comment by leofeyer** [comment]
The best intermediate fix is to require Symfony in version `3.3.*` instead of `^3.3`. The breaking changes were introduced in Symfony 3.4.

**Comment by aschempp** [comment]
> The reverted changes do not fix the issue, either, so yes, sadly.

😞  can you explain why?

> The best intermediate fix is to require Symfony in version 3.3.* instead of ^3.3. The breaking changes were introduced in Symfony 3.4.

Not really ideal as that version is out of date and does not get bugfixes anymore.

**Comment by leofeyer** [comment]
I'd rather use a slightly outdated version than no HTTP cache. But you can decide for yourself of course.

**Comment by leofeyer** [comment]
See #1388.
