### ISSUE TITLE
Maintenance mode UX glitch / warning

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#1284]
When entering maintenance mode with `lexik:maintenance:lock` a warning gets displayed:

```
Ttl doesn't work with Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver driver
```

When unlocking again with `lexik:maintenance:unlock` the following message gets displayed:

```
Impossible to do this action.
```

Everything seems to work, so these are probably warnings that can be ignored allthough I'd be interested in what causes the second one. (It's shown in green and was maybe there all the time but I didn't notice it because it looks so innocent. :grinning: )

(4.5.0 inside managed edtion)

**Comment by leofeyer** [comment]
You should probably report this at `lexik/LexikMaintenanceBundle`. There seems to be a similar issue already: https://github.com/lexik/LexikMaintenanceBundle/issues/76
