### ISSUE TITLE
Application state is not stored

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1288]
It seems that in Contao 4.5 the application state is not stored in the session anymore. Open palettes, active filters etc. are reset after each logout.

**Comment by leofeyer** [comment]
@aschempp @bytehead I guess this is also related to Symfony security? Maybe our session save handler is triggered after the session has been closed by the logout handler?

**Comment by leofeyer** [comment]
We have to add the user session data in `AuthenticationSuccessHandler::onAuthenticationSuccess()`.

**Comment by leofeyer** [comment]
Fixed in 2b627d4e42fcdffe7aed690875d5e83dc5fc3e8e.

**Comment by aschempp** [comment]
I'm not sure this is entirely correct. It means the session is only loaded from database on the actual login. Not sure it will be done on `remember_me` and it certainly will not be done on each request. And I'm pretty sure that was previously the case.

**Comment by leofeyer** [comment]
This is just one additional step, I did not remove the existing `UserSessionListener`.

**Comment by leofeyer** [comment]
Because the firewall redirects after a successful login so any listener below priority 8 is never executed.

**Comment by aschempp** [comment]
Why would that matter? After the redirect the session should be loaded again? The only reason I can think of is that the save handler is still executed and overwrites the user data. However, if that is the case, then the handling is wrong because the session must never be saved to the user if it was not loaded before. The redirect could come from anywhere…

**Comment by leofeyer** [comment]
You may be right. Feel free to provide a better implementation.

**Comment by leofeyer** [comment]
Ok, so the problem is that `$token->getUser()` in

https://github.com/contao/core-bundle/blob/e4f0d29c314d22ca2ac235ff938027f48aaf985b/src/EventListener/UserSessionListener.php#L79-L85

only returns the incomplete, unserialized `User` object upon login. Therefore `$user->session` is empty and the existing session data is overwritten.

**Comment by aschempp** [comment]
Why would the user not be complete? And why is the listener (priority 0) even executed when the firewall redirects on priority 8?

**Comment by leofeyer** [comment]
I might have been wrong about the redirect. You may want to debug this yourself.
