### ISSUE TITLE
Metadaten werden nach Eingabe gelöscht (Contao 4.5.1)

### ISSUE THREAD

**Issue by planepix** [contao/core-bundle#1290]
Nach Eintrag von Metadaten in der Dateiverwaltung (Contao 4.5.1) werden diese Daten nicht gespeichert. Die Eingabefelder sind nach dem Sichern leer.

**Comment by asaage** [comment]
confirmed...
& 4.5.0 has the same problem.

**Comment by fritzmg** [comment]
Has anyone figured out a fix for this yet? We'd need to hotfix this in a current project.

**Comment by leofeyer** [comment]
Fixed in 08a04c96aac825145090adbd3814994b346b5a97.
