### ISSUE TITLE
Sichtbarkeit bei Inhaltselementen

### ISSUE THREAD

**Issue by kehr-solutions** [contao/core-bundle#1291]
Wenn man bei einem Inhaltselement die Sichtbarkeit in der Übersicht ändern möchte, funktioniert das leider nicht. Nach einem Refresh der Seite ist das Element wieder mit dem altem Sichtbarkeitsstand.

Contao Version 4.5.0 sowie 4.5.1
PHP 7.1.3

`Request URL:http://domain.tld/contao?do=article&table=tl_content&id=20&rt=jTsg_-XXqdnkdEvdVoQenEuZPgAgEf82FDnwMTwsybk&ref=apX_aEWt&tid=1&state=0&rt=jTsg_-XXqdnkdEvdVoQenEuZPgAgEf82FDnwMTwsybk
Request Method:GET
Status Code:302 Found
Referrer Policy:origin`

**Comment by leofeyer** [comment]
Behoben in beb7812938230b7fdbe152afdcb82c2124de351a.
