### ISSUE TITLE
Hook prepare form data arguments

### ISSUE THREAD

**Issue by baumannsven** [contao/core-bundle#1292]
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/forms/Form.php#L321

In contao 3.5 is the $this argument don't the last argument.

**Comment by baumannsven** [comment]
Here contao 3.5
https://github.com/contao/core/blob/master/system/modules/core/forms/Form.php#L305

**Comment by zonky2** [comment]
look at https://github.com/contao/core-bundle/issues/155
