### ISSUE TITLE
Fragment im Frontend durch ua::class

### ISSUE THREAD

**Issue by operatorone** [contao/core-bundle#1294]
Nach einer sauberen Installation von Contao 4.4.12 erscheint im Frontend folgender Snippet:
> " itemscope itemtype="http://schema.org/WebPage"> 

Source-Code dazu:
```
<body id="top" class="&lt;esi:include src=" onerror="continue"></body>
<p>" itemscope itemtype="http://schema.org/WebPage"&gt;
    </p>
<div id="wrapper">
```

Sobald ich im Template **fe_page.html5** das Insert-Tag **{{ua::class}}** aus der Zeile: 

```
<body id="top" class="{{ua::class}}<?php if ($this->class) echo ' ' . $this->class; ?>"<?php if ($this->onload): ?> onload="<?= $this->onload ?>"<?php endif; ?> itemscope itemtype="http://schema.org/WebPage">
```

entfernte, verschwindet dieses Snippet. Ich habe keinerlei Frontend-Module eingebunden, um zu prüfen, ob es daran lag. Ist aber nicht der Fall.

**Comment by leofeyer** [comment]
Das kann ich weder in meiner Testumgebung noch in meinen Live-Systemen reproduzieren. Hat sonst noch jemand dieses Problem?

**Comment by xchs** [comment]
In meiner Contao 4.4.12 Installation (COD) kann ich diesbezüglich ebenfalls kein Problem erkennen.

> @operatorone Nach einer sauberen Installation von Contao 4.4.12

Wie hast Du Contao installiert? Über das ZIP-Archiv oder via Composer/CM?

**Comment by dmolineus** [comment]
Tritt das wirklich in einem blanken Container auf oder sind Erweiterungen im Einsatz?

Fehler wurde Mal in Zusammenhang mit contao-hyphenator reported:

 - https://github.com/heimrichhannot/contao-hyphenator reported
 - https://github.com/contao-bootstrap/layout/issues/6

**Comment by operatorone** [comment]
@xchs:Ich habe das System über den contao-manager installiert. Cache ist keiner in der Seitenstruktur aktiviert.

@dmolineus: contao-hyphenator habe ich nicht mehr installiert. Ich hatte sie auf Verdacht wieder entfernt. Der Fehler besteht trotzdem.

Folgendes habe ich installiert:

alnv/prosearch | 1.1.0
-- | --
clue/stream-filter | v1.4.0
codefog/contao-cookiebar | 1.3.3
codefog/contao-haste | 4.17.7
composer/ca-bundle | 1.1.0
contao-community-alliance/composer-plugin | 3.0.8
contao-components/ace | 1.2.9
contao-components/chosen | 1.1.10
contao-components/colorbox | 1.6.4
contao-components/colorpicker | 1.4.0.2
contao-components/compass | 0.12.2.1
contao-components/contao | 7.1.4
contao-components/datepicker | 2.2.0.4
contao-components/dropzone | 4.3.0
contao-components/highlight | 8.9.1
contao-components/html5shiv | 3.7.3
contao-components/installer | 1.2.6
contao-components/jquery | 1.12.4
contao-components/jquery-ui | 1.12.1.1
contao-components/mediabox | 1.5.4.2
contao-components/mediaelement | 4.2.7
contao-components/mootools | 1.6.0.5
contao-components/respimage | 1.4.2
contao-components/simplemodal | 2.0.7
contao-components/swipe | 2.0.6.2
contao-components/tablesort | 3.4.9
contao-components/tablesorter | 2.0.5.6
contao-components/tinymce4 | 4.6.7.2
contao/calendar-bundle | 4.4.12
contao/comments-bundle | 4.4.12
contao/core-bundle | 4.4.12
contao/faq-bundle | 4.4.12
contao/image | 0.3.5
contao/imagine-svg | 0.1.5
contao/installation-bundle | 4.4.12
contao/listing-bundle | 4.4.12
contao/manager-bundle | 4.4.12
contao/manager-plugin | 2.2.0
contao/news-bundle | 4.4.12
contao/newsletter-bundle | 4.4.12
craffft/contao-imagesortwizard | 2.3.1
craffft/contao-photoalbums2 | 2.0.1
craffft/contao-sortwizard | 1.4.0
craffft/contao-translation-fields | 1.7.0
derhaeuptling/contao-seo-serp-preview | 3.0.1
dklemmt/contao_dk_mmenu | 2.0.1
do-while/contao-backupdb-bundle | 1.2.1
doctrine/annotations | v1.6.0
doctrine/cache | v1.7.1
doctrine/collections | v1.5.0
doctrine/common | v2.8.1
doctrine/dbal | v2.6.3
doctrine/doctrine-bundle | 1.8.1
doctrine/doctrine-cache-bundle | 1.3.2
doctrine/inflector | v1.2.0
doctrine/lexer | v1.0.1
fig/link-util | 1.0.0
friendsofsymfony/http-cache | 2.1.0
friendsofsymfony/http-cache-bundle | 2.1.1
fritzmg/contao-lightcase | 2.0.1
glumanda99/contao-rellax | 1.0
guzzlehttp/guzzle | 6.3.0
guzzlehttp/promises | v1.3.1
guzzlehttp/psr7 | 1.4.2
hofff/contao-opengraph | 3.2.0
imagine/imagine | v0.7.1
jdorn/sql-formatter | v1.2.17
jeremykendall/php-domain-parser | 3.0.0
knplabs/knp-menu | 2.3.0
knplabs/knp-menu-bundle | v2.2.1
knplabs/knp-time-bundle | 1.8.0
leafo/scssphp | v0.6.7
league/uri | 4.2.2
lexik/maintenance-bundle | v2.1.3
madeyourday/contao-rocksolid-antispam | v2.0.0
madeyourday/contao-rocksolid-columns | v2.0.0
madeyourday/contao-rocksolid-custom-elements | v2.2.3
madeyourday/contao-rocksolid-icon-picker | v2.0.2
madeyourday/contao-rocksolid-slider | v2.0.2
matthiasmullie/minify | 1.3.58
matthiasmullie/path-converter | 1.1.0
menatwork/contao-multicolumnwizard | 3.3.15
michelf/php-markdown | 1.7.0
mindbird/contao-uitotop | 1.0.6
monolog/monolog | 1.23.0
nelmio/cors-bundle | 1.5.4
nelmio/security-bundle | 2.4.0
oyejorge/less.php | v1.7.0.14
paragonie/random_compat | v2.0.11
patchwork/utf8 | v1.3.1
php-http/client-common | 1.7.0
php-http/discovery | 1.3.0
php-http/guzzle6-adapter | v1.1.1
php-http/httplug | v1.1.0
php-http/message | 1.6.0
php-http/message-factory | v1.0.2
php-http/promise | v1.0.0
phpspec/php-diff | v1.1.0
phpunit/php-token-stream | 1.4.12
psr/cache | 1.0.1
psr/container | 1.0.0
psr/http-message | 1.0.1
psr/link | 1.0.0
psr/log | 1.0.2
psr/simple-cache | 1.0.0
roave/security-advisories | dev-master fe89fd2
sensio/distribution-bundle | v5.0.21
sensio/framework-extra-bundle | v3.0.29
sensiolabs/ansi-to-html | v1.1.3
sensiolabs/security-checker | v4.1.6
simplepie/simplepie | 1.5.1
swiftmailer/swiftmailer | v5.4.8
symfony/monolog-bundle | v3.1.2
symfony/polyfill-apcu | v1.6.0
symfony/polyfill-intl-icu | v1.6.0
symfony/polyfill-mbstring | v1.6.0
symfony/polyfill-php56 | v1.6.0
symfony/polyfill-php70 | v1.6.0
symfony/polyfill-util | v1.6.0
symfony/swiftmailer-bundle | v2.6.7
symfony/symfony | v3.4.3
tecnickcom/tcpdf | 6.2.13
terminal42/contao-changelanguage | 3.1.7
terminal42/contao-easy_themes | 2.2.6
terminal42/header-replay-bundle | 1.3.0
true/punycode | v2.1.1
twig/twig | v1.35.0
ua-parser/uap-php | v3.5.0
webmozart/assert | 1.2.0
webmozart/path-util | 2.3.0

**Comment by operatorone** [comment]
Habe nun noch mal alle Caches gelöst, Warmup gemacht und vorher das geänderte fe_page.html5 entfernt. Nun tritt der Fehler komischerweise nicht mehr auf.
