### ISSUE TITLE
Inserttags from modules are working but logged as "unknown inserttag"

### ISSUE THREAD

**Issue by nomiad** [contao/core-bundle#1295]
If an inserttag hook is registerd in replaceInsertTags it works, but it logs that there is an unknown insert tag.
it should not be logged as unknown since the module has "defined" it.

Contao Version: 4.4.12 (composer)
PHP: 7.1.9
Problably problem found in vendor\contao\core-bundle\src\Resources\contao\library\Contao\InsertTags.php:959 (break Statement)
Solution: Break out of outer switch statement if inserttag was replaced correctly.

**Comment by leofeyer** [comment]
I am using a lot of custom insert tags in my own projects and I cannot reproduce this in any. How does your code look like and what is the exact log message?

**Comment by nomiad** [comment]
Its a small util. you can find the code here:
https://github.com/guavestudios/contao-insertbyalias/blob/master/library/InsertByAlias.php

It is used to reference a module by an alias instead of an db ID

The message is:
INFO09:46:30 | contao | Unknown insert tag: insert_module_alias::changelanguage

**Comment by leofeyer** [comment]
How did you register the callback?

**Comment by nomiad** [comment]
it is registered at https://github.com/guavestudios/contao-insertbyalias/blob/14bf13e0a0d71b414437917bdfbab6a28fe871bf/config/config.php#L4

The hook itself works and renders the module.
But the info is still displayed.

Log is written in current tree at:
https://github.com/contao/core-bundle/blob/8ca706c4e5f21c9ca2044069b2919689654b9f58/src/Resources/contao/library/Contao/InsertTags.php#L1007

**Comment by leofeyer** [comment]
I have installed your extension and added an insert tag as described:

<img width="554" alt="" src="https://user-images.githubusercontent.com/1192057/36101211-f6067ae0-1008-11e8-9709-0aa398ca43b5.png">

<img width="534" alt="" src="https://user-images.githubusercontent.com/1192057/36101220-fadc1a0c-1008-11e8-9bbd-316927e1b998.png">

The insert tag is replaced correctly in the front end:

<img width="544" alt="" src="https://user-images.githubusercontent.com/1192057/36101222-ff7a7cf2-1008-11e8-9540-86a0feab861e.png">

No "unknown insert tag" log entries have been written.

**Comment by leofeyer** [comment]
Ok, the log entries have not been written but the Symfony toolbar showed them. I have fixed the issue in 937c93610bd7814535bc4056c767854c79f4e75d now.

**Comment by nomiad** [comment]
Yeah, i've tried the patch and it solved the the Toolbar Error. Thanks for fixing!
