### ISSUE TITLE
copyright info within tl_files

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1297]
One request we regularly get from customers is the ability to store copyright information for any kind of file and being able to display that information either with the file or collectively somewhere.

Typically one would put this into the `caption` section of the `meta` field, however this is not semantically correct in HTML5. The correct way would be to use a `<small>` element within a `<footer>` element of a sectioning element belonging to that resource. See https://stackoverflow.com/questions/21483356/how-to-mark-the-copyright-of-an-image-in-html for example for a detailed explanation.

For images the markup would look like this:
```html
<figure>
  <img src="files/content/foo.jpg" alt="lorem ipsum dolor">
  <footer><small><!-- copyright --></small></footer>
  <figcaption><!-- caption --></figcaption>
</figure>
```

Thus I want to discuss if it would make sense to provide an additional separate `copyright` field (either directly or within `meta`) for `tl_files` in the core.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 15th, the majority was against adding an additional field by default. Additional fields can easily be added in the DCA file.

Also, the `<footer><small>` markup does not seem to be an official recommendation, does it?

**Comment by fritzmg** [comment]
> Also the `<footer><small>` markup does not seem to be an official recommendation, is it?

According to https://www.w3.org/TR/2013/CR-html5-20130806/text-level-semantics.html#the-small-element, the `<small>` tag can be used to semantically denote copyright information for example. And according to https://www.w3.org/TR/2013/CR-html5-20130806/sections.html#the-footer-element copyright data should be defined in a `<footer>` section of the parent element.

**Comment by Aybee** [comment]
IMHO i18n for a copyright field is not necessary, so this field must not be a meta field, just a simple field. Just an additonal thought. I don't know if Contao does a language fallback of this meta fields if only the fallback language is filled out. If Contao does a language fallback it also can be a meta field as then we don't have to fill in the copyright multiple times.

**Comment by leofeyer** [comment]
> IMHO i18n for a copyright field is not necessary

That's another argument against using a meta field for the copyright.

**Comment by Aybee** [comment]
Yes, it can be a direct field within tl_files.

**Comment by jankout** [comment]
@fritzmg 

Hello Fritz, I'm trying to output the additional fields `copyright_link` and `copyright_licence` from the table `tl_files`. I added them in my dca file (Contao 4.7) `App/Recources/contao/dca/tl_files.php` with this code

```
<?php
use Contao\CoreBundle\DataContainer\PaletteManipulator;

$GLOBALS['TL_DCA']['tl_files']['fields']['copyright_licence'] =
[
    'label' => ['Copyright-Lizenz', 'Unter welcher Lizenz kann man diese Datei nutzen'],
    'inputType'   => 'text',
    'exclude'     => true,
    'eval'      => array('tl_class' => 'w50'),
    'sql'       => ['type' => 'string', 'length' => 255, 'default' => ''],
];
$GLOBALS['TL_DCA']['tl_files']['fields']['copyright_link'] =
[
    'label' => ['Lizenz-Link', 'Link zur Copyrightlizenz'],
    'inputType'   => 'text',
    'eval'  => array('tl_class' => 'w50', 'dcaPicker' => true),
    'sql'       => ['type' => 'string', 'length' => 255, 'default' => ''],
];

PaletteManipulator::create()
    ->addField('copyright_licence', PaletteManipulator::POSITION_APPEND)
    ->addField('copyright_link', PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('default', 'tl_files', 'metaFields')
;
```

To output them I use 

```
<?php if ($this->copyright_licence || $this->copyright_link): ?>
  <?php if ($this->copyright_link): ?><a href="<?php echo $this->copyright_link ?>" target="_blank"><?php endif ?><?php echo $this->copyright_licence ?><?php if ($this->copyright_link): ?></a><?php endif ?>
```
Unfortunately, it does not work. 

Do you have a better solution which you would like to share for everybody with similar issue?

**Comment by fritzmg** [comment]
Please use the community forum for such questions and provide more details.

**Comment by jankout** [comment]
> Please use the community forum for such questions and provide more details.

Ok, siehe https://community.contao.org/de/showthread.php?77824-Zus%C3%A4tzliche-Felder-bei-Dateiverwaltung-ausgeben&p=524231#post524231
