### ISSUE TITLE
Do not encode backend navigation items

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1298]
Since Contao 4.5 and switch to the Twig templates, the backend navigation item labels are encoded. There are some extensions that inject some HTML code using `getUserNavigation` hook and now this is broken.

I think the `{{ child.label }}` should be changed to `{{ child.label|raw }}` here: https://github.com/contao/core-bundle/blob/4.5/src/Resources/views/Backend/be_menu.html.twig#L15

Related: https://github.com/derhaeuptling/contao-seo-serp-preview/issues/7

**Comment by leofeyer** [comment]
Fixed in 00f0411f18091c0bd9e6e23684308b7ac6bc79a4.
