### ISSUE TITLE
Use Symfony VarDumper component

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#130]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/52) by @aschempp
Saturday Feb 21, 2015 at 18:00 GMT

http://symfony.com/blog/new-in-symfony-2-6-vardumper-component

It could actually be a compatible replacement for our `dump` function.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Feb 26, 2015 at 12:45 GMT

Please assign this to me

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Feb 26, 2015 at 12:56 GMT

I can't. GitHub only allows me to assign it to myself.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Feb 26, 2015 at 12:57 GMT

You should probably create a team with us but only give us pull access.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Feb 26, 2015 at 12:59 GMT

Ah, I forgot to add the dev team to the new repos. Will do now :)

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Tuesday Mar 10, 2015 at 09:59 GMT

I just tested this. It's pretty cool as it does output the dumps into the web profiler. However, there are two problems:

1. The dump function is only available after the container is build (which should be fine for legacy code)
2. Normally, it's only available in the dev environment (as the `DebugBundle` should only be loaded then).

I suggest to add this for a quick discussion.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Tuesday Mar 10, 2015 at 19:39 GMT

I could live with the two limitations.

**Comment by importer** [comment]
> <a href="https://github.com/discordier"><img src="https://avatars.githubusercontent.com/u/940331?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @discordier
Sunday Mar 22, 2015 at 02:13 GMT

So could I. IMO development related things should not be available in prod at all. I like the fact that by this accidental leakage of "forgotten" showTemplateVars is finally history.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Sunday Mar 22, 2015 at 17:36 GMT

@Toflar if you can agree too we can finish this an add a note to the UPGRADE.md

**Comment by importer** [comment]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @Toflar
Monday Mar 23, 2015 at 00:20 GMT

Agreed.

**Comment by aschempp** [comment]
There are only two actions to enable this: Add the `DebugBundle` to the kernel, and delete our own `dump()` method. I think we don't need a pull request for that ;-)

**Comment by leofeyer** [comment]
Implemented in 4650b5a522fa36aad3dbe9a13175d51d9154330c.
