### ISSUE TITLE
Cache in Contao 4.4.12 & 4.5.1 funktioniert nicht

### ISSUE THREAD

**Issue by derastronaut** [contao/core-bundle#1302]
In Bezug auf dieses [Foren-Thema](https://community.contao.org/de/showthread.php?69350-Contao-cachet-nicht) funktioniert der Cache unter Contao 4.4.12 und 4.5.1 (nach Update der 4.4.12 in einer Testinstallation des Projekts) nicht.

Auch in einer anderen 4.4.12-Installation funktioniert nach dem letzten Update aller Pakete (heute Morgen) im Contao-Manager der Cache nicht mehr. Die Pakete sind:

- Updating symfony/symfony (v3.4.2 => v3.4.3): Downloading (100%)
- Updating doctrine/inflector (v1.2.0 => v1.3.0): Downloading (100%)
- Updating lexik/maintenance-bundle (v2.1.2 => v2.1.3): Downloading (100%)
- Updating terminal42/header-replay-bundle (1.3.0 => 1.4.0): Downloading (100%)
- Updating matthiasmullie/minify (1.3.57 => 1.3.58): Downloading (100%)
- Updating sensiolabs/security-checker (v4.1.6 => v4.1.7): Downloading (100%)

Um für mich den Fehler auszuschließen hatte ich die htaccess, die noch unter system/config liegende localconfig.php und eine gemeinsame Erweiterung überprüft. Ich konnte keine Fehler feststellen.

Der im Thema erwähnte [Bug](https://github.com/contao/core-bundle/issues/1246) ist bereits gefixt. Habe die besagte Datei überprüft.

**Comment by Toflar** [comment]
Der Cache wird noch einen Moment nicht funktionieren, es sind zwei, drei PR's zum Teil gemerged und noch offen bei Symfony. Das Handling der Session wurde gefixt und überarbeitet, leider mit Side-Effects. Jetzt sollte es aber passen. Ich denke ich warte die neuste 3.4er ab und passe dann Contao an. Ob es funktioniert hängt also vor allem auch von der eingesetzten Symfony Version ab.

**Comment by leofeyer** [comment]
Siehe #1246.
