### ISSUE TITLE
Conspicuity in the source code written into the cache file

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1306]
When I activate the server cache and then look into the cache file in `var/cache/prod/http_cache`, I see this in the source code:
```php
…
<!--[if lt IE 9]><?php echo "<s"; ?>cript src="assets/html5shiv/js/html5shiv-printshiv.min.js"></script><![endif]-->
…
```
That is not necessarily a problem so far, but I'm wondering why `<?php echo "<s"; ?>` is getting written there.

[Contao 4.4.12]

**Comment by ausi** [comment]
Symfony does this, 
see https://github.com/symfony/symfony/blob/1df45e43563a37633b50d4a36478090361a0b9de/src/Symfony/Component/HttpKernel/HttpCache/AbstractSurrogate.php#L27-L30 
and https://github.com/symfony/symfony/blob/1df45e43563a37633b50d4a36478090361a0b9de/src/Symfony/Component/HttpKernel/HttpCache/Esi.php#L84

Probably to prevent things like `<script language="php">` from getting executed.

**Comment by xchs** [comment]
Thank you, @ausi .

I was just wondering why all other `<script>` tags are not affected by this replacement. So, basically, Symfony only considers script tags within HTML comments as potentially dangerous.
