### ISSUE TITLE
Back end module "user" is not allowed for user

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1309]
To reproduce:
* _Account Manager_ > _Users_: Add a new back end user (no administrator)
* Switch to the newly created user
* Open the user menu in the upper right corner and click on _Profile_
* Change something in the profile settings (e.g. _Clear cache_) and _Save and close_
* You should see now a new change log entry on the back end dashboard
* Click on the pencil icon (_Edit the element_)
* Contao shows an error message: _Back end module "user" is not allowed for user "xy"_

Shouldn't the back end user not be allowed to inspect/edit the changes regarding the own user profile? Otherwise this change log entry makes no sense (for the user concerned).

![backend](https://user-images.githubusercontent.com/1218766/34900394-e3e9e2a0-f7ff-11e7-87c0-4ae0f42804eb.png)

[Contao 4.5.2]

**Comment by aschempp** [comment]
I think the pencil should be disabled?

**Comment by leofeyer** [comment]
It used to point to the user profile, however https://github.com/contao/core/issues/7987 .

**Comment by leofeyer** [comment]
As discussed in Mumble on February 15th, we want to check the particular case in the `checkPermission` callback of `tl_user`, so if a user wants to access their own profile via `do=user` but does not have permission, redirect them to `do=profile`.

**Comment by leofeyer** [comment]
Fixed in 15806d3c5fcb19f3c329806c25bb8180359f5265.

**Comment by aschempp** [comment]
Hmm, the solution does not match what we discussed on Mumble according to your notes?

**Comment by leofeyer** [comment]
Correct, because the solution we came up in Mumble did not work. It only fixed the "edit" link but there is also a "compare versions" link which still threw the exception. Also, we wanted to add the check in the `checkPermission` method, however, the exception is thrown much earlier in `Backend::getBackendModule()`.

**Comment by aschempp** [comment]
I get that, but can't we just add a redirect? Instead of adding a specific handling of this case in the log viewer, we could also handle it in `getBackendModule` and redirect to the user screen.

**Comment by leofeyer** [comment]
No, we cannot as I explained above. The redirect only works for the "edit" button, not for the "compare versions" button.
