### ISSUE TITLE
Back end keyboard shortcut no longer works

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1310]
It seems like the back end keyboard shortcut <kbd>Alt</kbd>+<kbd>t</kbd> (or <kbd>Alt</kbd>+<kbd>⇧</kbd>+<kbd>t</kbd> on Firefox) no longer works.

[Contao 4.5.2 / Chrome 63 / Firefox 57 / Windows 10]

**Comment by leofeyer** [comment]
Does it work in Contao 4.4?

**Comment by xchs** [comment]
> Does it work in Contao 4.4?

Nope.

It seems that there is no link "Back to top" (with an `accesskey="t"`attribute) anymore.

**Comment by leofeyer** [comment]
That's correct, because every browser (desktop and mobile) provides a way to jump to the top of the page. We might even remove the `id="top"` attribute in the `be_main.html5` template.

**Comment by xchs** [comment]
It's fine with me, too.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 15th, we want to keep the `id="top"` in the back end template in case an extension uses it, but we don't want to re-add the "back to top" link in the back end.
