### ISSUE TITLE
4.5.x: email shipping of the form-module is broken

### ISSUE THREAD

**Issue by ChrisEbert** [contao/core-bundle#1311]
After updating contao from 4.4.7 to 4.5.2 (PHP version is 7.1), mail delivery of the form-module (and newsletter-bundle) is broken.

I have a simple contact form, to send an email with the contents of the form fields after submitting the form.
After hitting submit, I'm redirected to the redirect-page but no email was sent.

This entry appears inside the System-Log:
```
Details: | Form "Kontakt" could not be sent: Expected response code 220 but got code "", with message ""
Funktion: | Contao\Form::processFormData
```
The log-files are empty. There is no special smtp-server configured.

I could not reproduce it for the contao demo, because it is still v4.4.8.

**Comment by aschempp** [comment]
Are you using Unix or Windows?

**Comment by xchs** [comment]
I was also able to reproduce the error under Linux.

**Comment by ChrisEbert** [comment]
The issue appears on unix machines. Locally I'm using the php:7-apache docker image.

**Comment by aschempp** [comment]
So the background to my question is that we updated to Swiftmailer 6 in Contao 4.5, which does not longer support the PHP `mail()` method. It's either SMTP or Postfix sending. The best solution is probably to configure an SMTP server if you don't have one yet.

**Comment by ChrisEbert** [comment]
Ah ok. Sounds for me like a breaking change. Wouldn‘t it be bettet to do this in a major contao update?

**Comment by ChrisEbert** [comment]
Ok, I understand. 

After using the STMP server for sending the emails, everything works as expected. 👍 

If somebody else is having this issue, there is a nice (german) article on how to configure your own smtp server in Contao 4 - https://contao.ninja/smtp-einstellungen.html

Thanks for your hard work guys!
