### ISSUE TITLE
Bug: Code with C# highlighting not possible

### ISSUE THREAD

**Issue by WebDucer** [contao/core-bundle#1312]
Hello.

I moving from Contao 3.5 to 4.4. In my tutorial I use a lot of code examples (most in C#). After Migration none of code examples is highlighted. If I try to set the language for syntax highlighting to C# I got an error by saving the content element (error: "Invalid option value!"). All other languages seems to work.

**Comment by leofeyer** [comment]
Does it work in the online demo?

**Comment by WebDucer** [comment]
It doesn't work in online demo too.

![contao](https://user-images.githubusercontent.com/761881/34940279-2d8baa38-f9ef-11e7-9aba-e46f5e87323e.PNG)

**Comment by leofeyer** [comment]
Fixed in da93be27d8e119cec2b20d5905b7deb8dc867ba1.

**Comment by WebDucer** [comment]
@leofeyer Wird es auch die Korrektur für 4.4 (LTS) geben?

**Comment by leofeyer** [comment]
Ja.

**Comment by leofeyer** [comment]
Backported in e548ebe2423e646eb9fb6269d5a6a567c4efc110.
