### ISSUE TITLE
Contao from 4.5 on is not compatible to any version of mariadb anymore

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/core-bundle#1317]
Contao 4.5 switched to innodb and needs the setting `innodb_large_prefix` to be active. 
This is only the case from mariadb 10.2 onwards by default. 

The problem then is that with mariadb 10.2 `rows` got a reserved word. But this is used by contao in `tl_layout` for example. 

There was a PR for quoting the reserved word #1262 but it got rolled back. See for https://github.com/contao/core/pull/8813 for reasons. 

---

This means mariadb can only be used by people who can change the default setting `innodb_large_prefix` to true on the servers their websites are running and using mariadb 10.1. 

---

Since linux distros have switched to mariadb this will get a big problem pretty soon I'd imagine. 

The least we should do right now is give information well visible here on github on I think also on contao.org. 

If you look here for the issue you only find a merged PR which looks like to solve the problem #1262 and a previous closed one #1106 
You have to look very close to see the revert commit and there is no reasoning on it. 

If this ticket stays open it should popup directly for everyone searching for the term `mariadb` 

Maybe it should also noted on

- https://contao.org/de/download.html 
- https://docs.contao.org/books/manual/current/de/01-installation/den-live-server-konfigurieren.html#contao-systemvoraussetzungen

---

I post some of the error messages you get, so just users easy find info about the problem they are encountering

```
An exception occurred while executing 'INSERT INTO tl_layout (rows, cols, framework, loadingOrder, modules, mooSource, align, pid, tstamp) VALUES ...
```

```
An exception occurred while executing 'UPDATE tl_layout SET rows='2rwh' WHERE id=

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows='2rwh' WHERE id ...
```

**Comment by leofeyer** [comment]
All of what you have said has been discussed before.

> This means mariadb can only be used by people who can change the default setting `innodb_large_prefix` to true on the servers their websites are running and using mariadb 10.1. 

This statement is wrong. You can use MariaDB 10.1 without any adjustments if you switch the charset to `utf8` and the collation to `utf8_unicode_ci` (or `utf8_general_ci` as used in Contao before).

> The problem then is that with mariadb 10.2 `rows` got a reserved word. But this is used by contao in `tl_layout` for example. 

The problem is not limited to the reserved word. Doctrine only supports MySQL 5.7 or MariaDB 10.2 in version 2.7, which is however currently unreleased and requires at least PHP 7.1.

**Comment by leofeyer** [comment]
See contao/core#8813, contao/core-bundle#918, contao/installation-bundle#83, contao/installation-bundle#80 and probably more.
