### ISSUE TITLE
4.4.12: TinyMCE stellt kein STRONG dar

### ISSUE THREAD

**Issue by derastronaut** [contao/core-bundle#1319]
In jeder 4.4.12-Installation von mir, darunter eine eigens für dieses Problem frisch angelegte Testinstallation, wird im TinyMCE kein Fettdruck (strong) angezeigt. Kursiv hingegen funktioniert.

Contao 4.5.0 und 4.5.2 sind nicht betroffen, ebenso die Contao-Demo 4.4.8 nicht.

**Comment by fritzmg** [comment]
Welcher Browser und welches Betriebssystem?

**Comment by derastronaut** [comment]
MacOS High Sierra (aktuell) und Firefox 57.0.4

**Comment by fritzmg** [comment]
Retina display?

**Comment by derastronaut** [comment]
Jo

**Comment by xchs** [comment]
Related: https://github.com/contao/core-bundle/issues/1198

**Comment by leofeyer** [comment]
Welche Version von TinyMCE ist denn installiert?

**Comment by derastronaut** [comment]
Laut der JS-Datei 4.6.7 (2017-09-18).

**Comment by leofeyer** [comment]
Ich kann das Problem nicht nachvollziehen. Hier ein Screenshot aus einer 4.4.12 mit Retina-Display:

<img width="1026" alt="" src="https://user-images.githubusercontent.com/1192057/35437496-efa17476-0292-11e8-8f39-f294872791ff.png">

**Comment by derastronaut** [comment]
Kurioserweise habe ich eine (mittlerweile) 4.4.13-Installation (mit angepasster be_tinyMCE), in der Fettdruck funktioniert. **Aber:** In einer anderen 4.4.13-Installation (ohne extra be_tinyMCE-Template) geht Fettdruck hingegen nicht. In der eigens für das Fettdruck-Problem angelegte 4.4.12-Installation, die immer noch auf dem selben Stand ist, geht es auch nicht.

Hier ein Screenshot aus der 4.4.13 mit dem Problem:
![contao_4 4 13-bold-issue](https://user-images.githubusercontent.com/5235594/35437945-eb802700-0294-11e8-9ed7-8bb54e74dfcd.png)

**Comment by leofeyer** [comment]
Das kann aber dann kein Core-Problem sein, wenn es nur in ausgewählten Installationen auftritt, oder?
