### ISSUE TITLE
error in {{file::*}} insert tag leads to empty response

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1321]
Tested in Contao 4.5.2 (with header-replay-bundle 1.4.1).

__Reproduction__:

* Create a file called `templates/foo.php`.
* Insert `<?php $this->foo();` into the file.
* Create a new HTML content element with the content `{{file::foo.php}}`.
* Open the front end in the `prod` environment.

You will only see a blank page from the `500` response, instead of the usual pretty error screen.

The cause seems to be the same as described here: https://github.com/contao/core-bundle/issues/1307#issuecomment-357296451

**Comment by leofeyer** [comment]
Can you please test this again with the latest `4.5` branch? I'm seeing the pretty error screen on my system.

**Comment by fritzmg** [comment]
I cannot reproduce it with `contao/core-bundle: 4.5.4` and `terminal42/header-replay-bundle: 1.4.2`.
