### ISSUE TITLE
Contao 4 on IIS can't connect to database

### ISSUE THREAD

**Issue by CaptinJackSparow** [contao/core-bundle#1324]
I'm trying to run Contao 4 on IIS and get it to connect to a database on a different machine. I can connect to it when running MAMP on my Mac. 
I can also connect to the database server from the same machine I'm trying to install Contao 4 on, with an older version of Contao.
I would like Contao to show or log why it can't connect to the database.

**Comment by leofeyer** [comment]
Did you check the log files?

**Comment by CaptinJackSparow** [comment]
I tried, but there are no log files.

**Comment by leofeyer** [comment]
Please try it in debug mode (`app_dev.php`).

**Comment by fritzmg** [comment]
I can confirm that any error regarding the database connection in the install tool will not be logged or displayed anywhere. There will be no log entry and Symfony's profiler will also show no reason for the failed connection.

This should definitely be changed. It's important to know the actual error text _and code_ of the failed connection attempt in order to figure out the problem.

**Comment by CaptinJackSparow** [comment]
Okay, well I guess I have more issues then that. I was getting the "Could not connect to database" error because I had gone through a domain to the install. When I try to go through localhost, I can't login. 
On the one install of 4.4 I am getting an invalid token request.

On a fresh install of 4.5.3 (manual or composer) I type my password in and it just reloads the page and continues to ask for the password. It doesn't say invalid password or anything like that.
It shows this for depreciations but no errors.

> Time	Channel	Message
10:11:13
php	User Deprecated: Using the Contao\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead.
Show context    Show trace
10:11:13
php	User Deprecated: The "contao.install_tool" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Show context    Show trace
10:11:13
php	User Deprecated: The "contao.install_tool_user" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Show context    Show  trace

**Comment by CaptinJackSparow** [comment]
An update... 
I changed the php version to 7.2 and now I can login to the install through localhost.
However, here is all the info it gives when I try to connect to the database.

Depreciations

> Time	Channel	Message
18:00:09
php	User Deprecated: Using the Contao\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead.
Show context    Show trace
18:00:09
php (2 times)	User Deprecated: The "contao.install_tool" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Show context    Show trace
18:00:09
php	User Deprecated: The "contao.install_tool_user" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Show context    Show trace

Then under errors and info it shows this

> INFO
18:00:09
request	Matched route "contao_install".
Hide context
[▼
  "route" => "contao_install"
  "route_parameters" => [▼
    "_scope" => "backend"
    "_token_check" => true
    "_controller" => "Contao\InstallationBundle\Controller\InstallationController::installAction"
    "_route" => "contao_install"
  ]
  "request_uri" => "http://localhost/contao/install"
  "method" => "POST"
]

Now it's also printing this in the log:

> [2018-02-06 18:09:18] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"http://localhost/contao/install","method":"POST"} []
[2018-02-06 18:09:19] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"6af897","_route":"_wdt"},"request_uri":"http://localhost/_wdt/6af897","method":"GET"} []

**Comment by CaptinJackSparow** [comment]
Well I have figured out finally why it wouldn't connect... I browsed the "main page" and saw something about pdo connection. So I checked my php settings and pdo_mysql was disabled. 
Something that I think should be added to the contao check would be to check if that is enabled or not... would have helped. :) 

Now, I have yet another problem. When using the app.php the backend theme won't display, however when using the app_dev.php it shows? There's no css at all. It does give a contao message saying that javascript is disabled, but it isn't. There are no error logs either. 

At least I'm getting closer though :)

**Comment by CaptinJackSparow** [comment]
Okay, another update on the css... Maybe I should post it in a new issue, because it seems to be related to Contao 4.5, as I've put Contao 4.4 on and it's all working now. :D

**Comment by leofeyer** [comment]
> This should definitely be changed. It's important to know the actual error text and code of the failed connection attempt in order to figure out the problem.

Fixed in contao/installation-bundle@9ca96edb96cfeac20b49d713bbd8defa072a480e.
