### ISSUE TITLE
Fehler bei Ordnerauswahl im Galerie-Modul

### ISSUE THREAD

**Issue by derastronaut** [contao/core-bundle#1328]
In Contao 4.5.2 werden in den Galerien Ordnerauswahlen ignoriert. Somit werden nicht mehr alle Bilder aus dem Ordner aufgelistet und angezeigt.

Wenn man die Bilder manuell auswählt werden sie angezeigt.

Unter 4.4.12 hat es noch funktioniert.

Ein Foren-Mitglied konnte das Problem in der Demo nachstellen: https://community.contao.org/de/showthread.php?69457-Reicht-Auswahl-des-Ordners-nicht-mehr-aus

**Comment by leofeyer** [comment]
Das Problem entstand durch #925 und ist in 85adefc5667a5e3f5966a4b8cf39b3f4c3f17b79 nun behoben.

**Comment by dmolineus** [comment]
Will it be backported for LTS 4.4?

**Comment by leofeyer** [comment]
Read my comment again. The problem was only introduced in Contao 4.5. 😉

**Comment by dmolineus** [comment]
> Read my comment again. The problem was only introduced in Contao 4.5. :wink:

I stumbled upon that issue in Contao 4.4 as well lately. That's why I asked. However I cannot reproduce it anymore with 4.4.13. So everything is fine. :)
