### ISSUE TITLE
GD, Imagick oder Gmagick

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#1329]
Und möchte eine Website mit Contao 4.4.* auf einem Hosteurope Webspace installieren. Alle Probleme sind erstmal soweit umschifft, aber an einem Problem hängen wir: Welche PHP-Erweiterung zur Bildbearbeitung wird denn nun benötigt?

In dieses Problem bin ich jetzt schon zum 2. Mal innerhalb kürzester Zeit gelaufen:

So wie im Titel steht es in den Systemvoraussetzungen auf contao.org und das haben auch die Serveradministratoren gelesen und haben es so interpretiert, dass es eine von den drei aufgezählten benötigt.

In der ```vendor/imagine/imagine/README.md``` steht folgendes:

> Depending on the chosen Image implementation, you may need **one** of the following:
> - GD2
> - Imagick
> - Gmagick

Das bestärkt den Serveradmin natürlich ebenfalls noch darin, dass es nur eine benötigt (auch wenn da explizit nochmal drüber steht *Depending on the chosen Image implementation*).

Ich habe nun zweimal den Fall, dass auf dem Server nur GD installiert ist und mit Contao nix anzufangen ist, weil die Meldung kommt:

```Imagick not installed```

und im error.log

```[2018-01-20 12:27:24] app.CRITICAL: An exception occurred. {"exception":"[object] (Imagine\\Exception\\RuntimeException(code: 0): Imagick not installed at /*/vendor/imagine/imagine/lib/Imagine/Imagick/Imagine.php:36)"} []```

Somit könnte man die Systemanforderung auch dahingehend interpretieren, dass man GD UND Imagick oder Gmagick benötigt. Ich kann mich erinnern, dass beim ersten Mal, als das Problem auftrat, ich mit @leofeyer gesprochen habe und er nach Rücksprache mit @ausi zu dem selben Schluss gekommen ist

Es gibt auch im Forum darüber einen Thread https://community.contao.org/de/showthread.php?66361-Problem-mit-Anzeige-von-Bildern-durch-Imagick/page2 in dem darüber diskutiert wird. Da hat jedoch @Toflar folgendes beschrieben:

> Imagick ist keine Voraussetzung für Contao. Voraussetzung ist mind. die GD Library (vorausgesetzt
> man hat eben nichts besseres).
> 
> Folgendes geschieht also:
> - Wenn Gmagick verfügbar ist, nimm Gmagick
> - Wenn Imagick vorhanden ist, nimm Imagick
> - Ansonsten wähle GD

Also irgendwas passt da nicht zusammen und das sollten wir eindeutig dokumentieren.

**Comment by fritzmg** [comment]
Also ich kann nicht bestätigen, dass man GD __und__ Imagick oder Gmagick braucht. In meiner lokalen Entwicklungsumgebung habe ich weder Imagick noch Gmagick verfügbar und habe so ein Problem noch in keiner unserer Contao 4 Projekte feststellen können.

@frontendschlampe wie lässt du den Symfony Cache bauen? Wichtig ist, dass die Umgebung, die beim aufbauen des Symfony Cache verwendet wird, die selben Voraussetzungen hat, wie die Umgebung in der PHP letztendlich unter dem eingesetzten Webserver läuft.

Wenn du zB ein `composer install`, `composer update` oder `cache:clear` & `cache:warmup` über das PHP CLI machst (also über die Konsole) und über die PHP CLI ist Imagick oder Gmagick verfügbar, dann wird der Cache so aufgebaut, dass also entweder Gmagick oder Imagick verwendet wird. Hast du dann aber im _Webserver_ Gmagick oder Imagick __nicht__ verfügbar, kommt es zu diesem Problem.

**Comment by fritzmg** [comment]
@frontendschlampe führe über SSH mal folgendes aus:
```
/usr/bin/php{major}.{minor} -m | grep -i magick
```
Ersetze `{major}` und `{minor}` mit der richtigen PHP version, die im Webserver für die Contao Installation eingestellt ist.

**Comment by frontendschlampe** [comment]
Ich bin grad unterwegs, kann es also erst morgen Vormittag testen. 

Die Cache-Verzeichnisse habe ich via Konsole konplett gelöscht und dann mit composer install wieder aufbauen lassen. Trotzdem immer noch der Fehler. Sehr eigenartig gerade! :-/

**Comment by leofeyer** [comment]
Contao braucht zwingend nur die GDlib. Wenn man optional Imagick nutzen möchte, braucht man trotzdem weiterhin die GDlib. Das ändert sich eventuell in einer zukünftigen Version.

Hast Du vielleicht Imagick in der CLI-Version von PHP aber nicht in der normalen? Dann würde beim `composer update` Imagick ausgewählt und würde im Webprozess fehlen.

**Comment by fritzmg** [comment]
> Die Cache-Verzeichnisse habe ich via Konsole konplett gelöscht und dann mit composer install wieder aufbauen lassen. Trotzdem immer noch der Fehler. Sehr eigenartig gerade! :-/

Ja wie gesagt, wenn über's PHP CLI die Imagick oder Gmagick Extension verfügbar ist, wird auch der Cache dementsprechend aufgebaut.

> Contao braucht zwingend nur die GDlib. Wenn man optional Imagick nutzen möchte, braucht man trotzdem weiterhin die GDlib. Das ändert sich eventuell in einer zukünftigen Version.

Ah ok, daran hatte ich nicht gedacht. In meinem docs PR von damals ist das nun falsch drin, da steht nun drin, dass entweder eine der 3 libs benötigt wird (und nicht dass die Gd lib auf jeden Fall vorhanden sein muss, was ja in der Regel kein Problem ist).

**Comment by xchs** [comment]
> Imagick not installed

Ja, in diese "Falle" bin ich auch schon gestolpert: https://github.com/contao/core-bundle/issues/1255

Ich nehme also an, dass bei Dir, @frontendschlampe, ebenso das zutrifft, was @fritzmg hier und in meinem Ticket als Ursache angeführt hat:

> This might happen if you built the cache via the console where Imagick is available via the PHP CLI - but it is not available via the PHP process of your webserver.

**Comment by frontendschlampe** [comment]
> @frontendschlampe führe über SSH mal folgendes aus:
> 
> ```/usr/bin/php{major}.{minor} -m | grep -i magick```
>
> Ersetze {major} und {minor} mit der richtigen PHP version, die im Webserver für die Contao Installation eingestellt ist.

Hab ich gemacht und da kommt ```imagick```, was ja bedeuten würde, dass Imagick über die Konsole zur Verfügung steht. Nachdem ich erneut den Cache gelöscht und ein composer install gemacht habe, erhalte ich nun wenigstens keine Fehlermeldung mehr wg. Imagick. Ich habe keine Ahnung, ob da jetzt der Serverbetreuer was dran gemacht hat.

Dafür ist es nun:

```[2018-01-21 11:24:29] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to create \"/tmp/25cb4c1cd3a3bc35b8f61ae415296bbc\": mkdir(): Permission denied. at /*/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:103)"} []```

Ich liebe diesen Webspace .... NICHT.

**Comment by xchs** [comment]
> da kommt imagick, was ja bedeuten würde, dass Imagick über die Konsole zur Verfügung steht

Hast Du mittels `phpinfo()` geschaut, ob imagick` auch dem PHP Webprozess zur Verfügung steht?

**Comment by frontendschlampe** [comment]
> Contao braucht zwingend nur die GDlib.

Das ist sehr verwirrend. Ich bin mir zu 100% sicher, dass wir da vor ein paar Wochen anders drüber gesprochen haben. @ausi erinnert sich auch nicht mehr?

> Wenn man optional Imagick nutzen möchte, braucht man trotzdem weiterhin die GDlib.

Oder wir haben uns bei diesem Punkt missverstanden?!

**Comment by frontendschlampe** [comment]
> Hast Du mittels phpinfo() geschaut, ob imagick` auch dem PHP Webprozess zur Verfügung steht?

Habe ich soeben geschaut und da wird nix gefunden, wenn ich nach *magick* suche - man man man ...

**Comment by fritzmg** [comment]
> Habe ich soeben geschaut und da wird nix gefunden, wenn ich nach magick suche - man man man ...

Dann sollte es aber wieder zu diesem Problem kommen, da der Cache nun mit der Verwendung von Imagick aufgebaut wurde. Dein Hoster muss sicherstellen, dass in beiden Umgebungen Imagick vorhanden oder nicht vorhanden ist.

**Comment by frontendschlampe** [comment]
> Dann sollte es aber wieder zu diesem Problem kommen, da der Cache nun mit der Verwendung von Imagick aufgebaut wurde. Dein Hoster muss sicherstellen, dass in beiden Umgebungen Imagick vorhanden oder nicht vorhanden ist.

jo ... sicherlich ... das nervt gewaltig ... danke Hosteurope

**Comment by fritzmg** [comment]
Als Workaround könntest du `var/cache/prod` löschen und dann das Contao Install Tool aufrufen. Dann sollte der Cache im Kontext des Webservers aufgebaut werden.

**Comment by frontendschlampe** [comment]
> Als Workaround könntest du var/cache/prod löschen und dann das Contao Install Tool aufrufen. Dann sollte der Cache im Kontext des Webservers aufgebaut werden.

Öhm ... *lol ... das hat geholfen ... Wahnsinn

**Comment by xchs** [comment]
> Dafür ist es nun:
> 
> [2018-01-21 11:24:29] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Failed to create \"/tmp/25cb4c1cd3a3bc35b8f61ae415296bbc\": mkdir(): Permission denied. at /*/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:103)"} []

Kann sein, dass Du für den Zugriff auf den temporären Ordner die Umgebungsvariable in Deiner `app.php` bzw. `app_dev.php` so setzen musst:
```php
putenv("TMPDIR=/is/htdoc/is/htdocs/user_tmp/wp1234567_ABCDEFGHIJ/");
```
(`wp1234567_ABCDEFGHIJ` müsstest Du natürlich entsprechend Deinem Hosting anpassen)

**Comment by frontendschlampe** [comment]
> Kann sein, dass Du für den Zugriff auf den temporären Ordner die Umgebungsvariable in Deiner ```app.php``` bzw. ``` app_dev.php``` so setzen musst:

Naja ... dieser Fehler kommt nicht im FE, sondern im BE, wenn ich die Systemwartung ausführe.

**Comment by xchs** [comment]
Das sollte gleichermaßen für FE wie BE gelten.

**Comment by frontendschlampe** [comment]
> Das sollte gleichermaßen für FE wie BE gelten.
>
> (```wp1234567_ABCDEFGHIJ``` müsstest Du natürlich entsprechend Deinem Hosting anpassen)

Ok ... dann habe ich sie ggfs. falsch angepasst?!

Die Zeile füge ich ja einfach in der ```app.php``` und der ```app_dev.php``` am Ende hinzu. Für ```wp1234567``` setze ich die entsprechende wp-Nummer des Benutzers. Und was muss ich dann für ```_ABCDEFGHIJ``` setzen?

**Comment by xchs** [comment]
> Die Zeile füge ich ja einfach in der app.php und der app_dev.php am Ende hinzu

Am besten gleich am Anfang nach dem PHP-Tag.

> Und was muss ich dann für _ABCDEFGHIJ setzen?

Den genauen Pfad müsstest Du eigentlich im HostEurope AdminPanel finden.

**Comment by fritzmg** [comment]
Idealerweise sollte aber HostEurope den Temp Pfad korrekt konfigurieren. Eine PHP Webapplikation muss Schreibrechte dafür besitzen.

**Comment by frontendschlampe** [comment]
ah ... jetzt funzt es ... mit dem richtigen Pfad:

```putenv("TMPDIR=/is/htdocs/user_tmp/wp123456789_ABCDEFGH/");

Ich danke Euch! :-*

**Comment by frontendschlampe** [comment]
Abschließend bleibt aber zum ursprünglichen Thema zu sagen:

Die Beschreibung auf contao.org ist nicht ganz eindeutig:

```GD, Imagick oder Gmagick```

Außerdem ist die Beschreibung in ```vendor/imagine/imagine/README.md```

> Depending on the chosen Image implementation, you may need one of the following:
> 
> - GD2
> - Imagick
> - Gmagick

nicht korrekt, denn GD wird auf jeden Fall benötigt und Imagick oder Gmagick sind optional. Das sollte auf jeden Fall angepasst werden.

Was den Betrieb von Contao 4 auf einem Hosteurope Webspace angeht, so kann man das zwar mit der Anpassung des TMP-Verzeichnisses in der ```app.php``` und der ```app_dev.php``` durchaus bewerkstelligen, aber die Nutzung des Contao-Managers oder composer über die Kommandozeile ist praktisch unmöglich. Somit gehen alle Vorteile der Wartung und Aktualisierung von Contao komplett verloren.

@fritzmg und @xchs ich danke Euch für Eure Hilfe. Ich liebe unsere Community! *thumbsup

**Comment by fritzmg** [comment]
> Abschließend bleibt aber zum ursprünglichen Thema zu sagen:
> 
> Die Beschreibung auf contao.org ist nicht ganz eindeutig:
> 
> GD, Imagick oder Gmagick
> 
> Außerdem ist die Beschreibung in vendor/imagine/imagine/README.md
> 
>     Depending on the chosen Image implementation, you may need one of the following:
> 
>         GD2
>         Imagick
>         Gmagick
> 
> nicht korrekt, denn GD wird auf jeden Fall benötigt und Imagick oder Gmagick sind optional. Das sollte auf jeden Fall angepasst werden.

Ja wie gesagt, hier sollte die Dokumentation angepasst werden. Auch der Contao Check überprüft das falsch. Jedoch ist es mehr oder weniger vernachlässigbar, da es, vermutlich, kaum Umgebungen geben wird, wo Imagick oder Gmagick vorhanden ist, Gd jedoch nicht.

**Comment by dmolineus** [comment]
Wäre v
Hilfreich, dass man eine Konfigurationsmöglichkeit hätte um die Bildbibliothek selbst zu bestimmen. Damit könnte man Probleme, die durch Inkonsistenzen zwischen der cli und der Webserver php Version umgehen

**Comment by aschempp** [comment]
Das wäre eigentlich kein Problem, müsste lediglich von unserem CompilerPass berücksichtigt werden.

**Comment by leofeyer** [comment]
> Damit könnte man Probleme, die durch Inkonsistenzen zwischen der cli und der Webserver PHP Version umgehen.

Ja, für diesen speziellen Fall schon. Aber die Verwendung unterschiedlicher PHP-Versionen bzw. der gleichen PHP-Version mit unterschiedlichen Extensions bleibt weiterhin problematisch. Ist z.B. in der CLI-Version die mbstring-Extension geladen, wird kein Polyfill installiert; fehlt die Extension dann aber im Webprozess, sind die mb_-Funktionen kaputt.

Deswegen sehe ich es als Voraussetzung, dass auf der Kommandozeile dieselbe PHP-Version läuft wie im Webprozess. Alles andere birgt unkalkulierbare Risiken, die wir nicht alle in der Konfiguration abfangen können.

**Comment by fritzmg** [comment]
Wir hatten gerade ein sehr ungutes Problem bei dem Hoster WebGo. Aus irgendeinem Grund wurde auf allen Servern unserer Kunden, die Shared Hosting Pakete von WebGo verwenden, Imagick einfach so gestern Abend entfernt. Das hatte zur Folge dass alle diese Contao 4.4+ Installationen nicht mehr funktionierten.
```
[2018-02-07 09:37:54] app.CRITICAL: An exception occurred. {"exception":"[object] (Imagine\\Exception\\RuntimeException(code: 0): Imagick not installed at …/vendor/imagine/imagine/lib/Imagine/Imagick/Imagine.php:36)"} []
```
Bei allen Contao Installationen musste daher ein `cache:clear` + `cache:warmup` gemacht werden.

Es wäre außerdem nicht schlecht wenn man bspw. über die contao-console herausfinden könnte, welche Library nun in Verwendung ist (oder geht das schon?), anstatt selbst in var/cache/prod herum zu stöbern.

**Comment by fritzmg** [comment]
> Es wäre außerdem nicht schlecht wenn man bspw. über die contao-console herausfinden könnte, welche Library nun in Verwendung ist (oder geht das schon?), anstatt selbst in var/cache/prod herum zu stöbern.
```
 vendor/bin/contao-console debug:container contao.image.imagine
```
thx @Toflar ;)

**Comment by leofeyer** [comment]
Wie am 15. Februar auf Mumble besprochen kann das grundsätzliche Problem (PHP-CLI !== PHP-WEB) nur gelöst werden, indem der Cache einmal gelöscht wird und durch den Web-Prozess neu aufgebaut wird. Dazu wäre es gut, im Manager einen Button "Cache nur leeren" zu haben.

**Comment by fritzmg** [comment]
Dadurch wird aber der interne Cache von Contao nicht aufgebaut (außer man besucht das Contao Install Tool).

**Comment by leofeyer** [comment]
@fritzmg Da hast Du Recht. 😢

Ich habe jetzt ein Ticket in `contao/contao-manager` angelegt, in dem wir diskutieren können, wie die "richtige" Lösung aussehen sollte.
