### ISSUE TITLE
Contao 4.5.2: Error message after calling contao/install

### ISSUE THREAD

**Issue by markocupic** [contao/core-bundle#1331]
I have installed contao 4.5.2 with 
composer create-project contao/managed-edition

When calling the installtool, contao throws the following error message:
`
Parse error: syntax error, unexpected '?' in /home/aeracing/public_html/test2/vendor/contao/manager-bundle/src/ContaoManager/Plugin.php on line 137
`

Cyon webhosting
tested with PHP 7.2 & 7.1

Can anybody reproduce this error?

PS: There is no error when installing version 4.5.1

**Comment by fritzmg** [comment]
Are you sure you did your tests with PHP 7.1 and 7.2? Nullable return types were introduced in PHP 7.1.

**Comment by markocupic** [comment]
@fritzmg 
Thank you for your response.
It seems like the cyon needs some time to switch from the default php version to my preferred version. 
After 20' of waiting,   I've tested again. Now with success any without any error. ???

**Comment by bytehead** [comment]
@markocupic you can try to kill the running process and clean the opcache this way: `pkill lsphp`.
So the version switch should go faster.

**Comment by markocupic** [comment]
@bytehead 
Hoi David
Super! Vielen Dank, werde ich mal testen. 
Ond e liebe Gruess
us Sursee ;-)
