### ISSUE TITLE
Contao language list incomplete/out of date

### ISSUE THREAD

**Issue by backbone87** [contao/core-bundle#1333]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Missing are at least `no` Norwegian and `tl` Tagalog

**Comment by leofeyer** [comment]
It seems we have removed it on purpose: https://github.com/contao/core/commit/8e59390611d9c91a444fd04c257aabbf504ea70a

I couldn't find an explaining ticket though. Does anyone remember?

**Comment by aschempp** [comment]
Because we added `nb` and `nn`, where `no` is a macrolanguage?

**Comment by m-vo** [comment]
Hope this wasn't kind of a no_No[?](https://productforums.google.com/forum/#!topic/webmasters/HXCv5axVRPI/discussion)

**Comment by backbone87** [comment]
whats the exact reason to remove an ISO code, whats wrong with macrolanguages?

**Comment by fritzmg** [comment]
> Because we added nb and nn, where no is a macrolanguage?

Contao currently supports the following macrolanguages:

* ak
* sq
* ar
* ay
* az
* zh
* cr
* et
* ff
* gn
* ik
* kr
* kv
* kg
* ku
* lv
* mg
* mn
* oj
* om
* fa
* ps
* qu
* sc
* sw
* uz
* yi
* za

`no` is the only macrolanguage missing.

Furthermore, Contao supports these languages, which are covered by other macrolanguages that are also supported by Contao (excluding nn and and nb):

* id (covered by ms)

**Comment by leofeyer** [comment]
I'm not against re-adding `no`. What about `tl`?

**Comment by leofeyer** [comment]
Fixed in e45e092fd2207d5bc3077347261d173b46b643e7.

**Comment by backbone87** [comment]
@leofeyer tagalog is still missing

**Comment by leofeyer** [comment]
That's because you did not answer my question above. 😉 And @fritzmg said that `no` is the only missing macro language?

**Comment by leofeyer** [comment]
Also, is it Tagalog or Filipino? In `$langsNative` we are mapping `tl` to Filipino.

https://en.wikipedia.org/wiki/Tagalog_language

**Comment by backbone87** [comment]
It is called tagalog on my project.

**Comment by leofeyer** [comment]
Fixed in d5af49ef9730d94b3da6cb5c2caee7d8369f8abb.
