### ISSUE TITLE
[FR] New field avatar for tl_member

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1335]
Most of the time my customers need a member image. I'm missing this for years. I think this will be an often used core feature. Module "Personal data" should offer the possibility to upload an image in the FE. In BE form use the filepicker.

**Comment by leofeyer** [comment]
See contao/core#7224.

**Comment by m-vo** [comment]
Wait, a duplicate tag for a FR in a feature-frozen repository? :-) Could you then move the referenced ticket in the right repository?

**Comment by Aybee** [comment]
I only searched in core-bundle as I know that 3.5 is feature closed.

Ticket #7224 from core is not the same. It's also a bit to complecated to me. I don't want an upload widget. There's an old(?) avatar extension where I can upload a file from local but that is not what I want. I want to pick an image with the filepicker in BE. Like the image in CEs, News and Events. Also this avatar extension limits images to a special size. That is not what I need.

And of course the member shoud be able to upload an image with "Personal data" in FE. But uploading an image in FE is already possible with the form generator. 

![bildschirmfoto am 2018-01-24 um 00 47 50](https://user-images.githubusercontent.com/1143013/35306904-794d72d2-00a0-11e8-8910-cc56e7759a51.png)
From the image above we only need the field "Source file" and a preview if an image is selected. Don't need the checkbox "Add an image" nor the rest.

In "Personal data" we need "Image size" and "Fullsize view".

**Comment by leofeyer** [comment]
> I only searched in core-bundle as I know that 3.5 is feature closed.

Contao 3 being feature complete certainly does not mean that all 472 open issues will be thrown away and have to be re-added here!

> I don't want an upload widget.

So you mean you first want to open the file manager, upload an image there, then go back to the user profile and select it? Seems cumbersome to me. What about the front end where there is no file manager?

It is very likely that an avatar field will behave similar to the existing avatar extension.

**Comment by Aybee** [comment]
> So you mean you first want to open the file manager, upload an image there, then go back to the user profile and select it? Seems cumbersome to me.

This is what my customers do for years. Meanwhile it's possible to open the filemanager within the filepicker for upoading an image if it's not already there. (Not in the online Demo).

You never have said that it is cumbersome to upload images before we can select them in CEs, News, Events ... But we don't have to discuss this as with the filepicker we already can select an image from the file manager **or** upload one if it's not already there.

> What about the front end where there is no file manager?

Front end upload within the "Personal data" module by a member is a complete other thing. Here things should be as in most accounts we know from the internet. Upload your image from your computer (or choose gravatar ...).

> It is very likely that an avatar field will behave similar to the existing avatar extension.

But I think it's up to us how it will behave. We don't have to take a look at the avatar extension as all we need is this field "Source file" which opens the filepicker. And the neccessary modification within the "Personal data" module.

**Comment by Aybee** [comment]
Within the Personal data modulewe also need to select a fallback image.
