### ISSUE TITLE
search index does not work anymore

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1337]
__Reproduction:__

1. Install Contao `4.5.3` (Managed Edition).
2. Set up everything so that you can open at least one page in the front end.
3. Go to _System_ » _Maintenance_ and click _Rebuild index_.

After rebuilding is finished, you will not see any pages in the search index under _System_ » _Maintenance_.

I also verified that it is still working in Contao `4.5.2` for example. Some users on the forum indicate that it is also not working in Contao `4.4.13`, but I haven't confirmed that yet.

As far as I can tell the `onKernelTerminate` event of the `AddToSearchIndexListener` is never called. But I could not figure out why.

**Comment by fritzmg** [comment]
I can confirm that it is also not working in Contao `4.4.13`. It is still working in Contao `4.4.12`.

**Comment by kikmedia** [comment]
Confirmed for 4.4.13

**Comment by folkfreund** [comment]
I never updated to 4.4.13 (still on 4.4.12) but I had the same issue a few days ago. After some tries it worked then... So it seems not to be related to changes from 4.4.12 to 4.4.13.

**Comment by fritzmg** [comment]
> I never updated to 4.4.13 (still on 4.4.12) but I had the same issue a few days ago. After some tries it worked then... So it seems not to be related to changes from 4.4.12 to 4.4.13.

Hm, I cannot confirm that. If I only downgrade the core-bundle to 4.4.12 (or 4.5.2) the search index works. If I upgrade to 4.4.13 (or 4.5.3) the search index stops working. So a dependency for cannot be the cause.

**Comment by dmolineus** [comment]
> Hm, I cannot confirm that. If I only downgrade the core-bundle to 4.4.12 (or 4.5.2) the search index works. If I upgrade to 4.4.13 (or 4.5.3) the search index stops working. So a dependency for cannot be the cause.

You never know if a dependency update (symfony, header-replay) caused the search index stopped working. ;)

**Comment by leofeyer** [comment]
We ran into [this issue](https://github.com/contao/core-bundle/issues/955#issuecomment-315399434) again (also see https://github.com/symfony/symfony/issues/23546).

The ` || !$this->scopeMatcher->isFrontendMasterRequest($event)` condition needs to be removed again:

https://github.com/contao/core-bundle/blob/502998701032d07cd3daa9eadbd01b0758ecda89/src/EventListener/AddToSearchIndexListener.php#L64

**Comment by leofeyer** [comment]
Reverted in c56cf49709fb5c794f4e3cefd7c35e7c5eadc162 for Contao 4.4.

**Comment by fritzmg** [comment]
> You never know if a dependency update (symfony, header-replay) caused the search index stopped working. ;)

Sure you can.

**Comment by aschempp** [comment]
Can you shed some light on why the request it not a frontend master request?

**Comment by leofeyer** [comment]
See my comment above: https://github.com/contao/core-bundle/issues/1337#issuecomment-360253524

**Comment by aschempp** [comment]
That's not really an explanation. I think the actual issue is that we're executing on the `kernel.terminate` event?

**Comment by fritzmg** [comment]
> That's not really an explanation. I think the actual issue is that we're executing on the kernel.terminate event?

But that's deliberate, isn't it? Updating the search index should not block the response for the client (in PHP-FPM environments).

**Comment by aschempp** [comment]
Yeah, but maybe we can solve the problem by pushing search information into the service during the actual request so we don't need validate the frontend master request?

btw. how does the search index work with (esi) fragments?

**Comment by Toflar** [comment]
> btw. how does the search index work with (esi) fragments?

It ignores them.

**Comment by rflx** [comment]
I've tried to patch https://github.com/contao/core-bundle/commit/c56cf49709fb5c794f4e3cefd7c35e7c5eadc162 with Contao 4.4.13 but the issue isn't gone. Did someone tested the commit?

**Comment by fritzmg** [comment]
Did you delete the cache after patching?

**Comment by rflx** [comment]
Forgot to… That was it. Now its working!

**Comment by leofeyer** [comment]
Instead of patching, you could try to require `"contao/core-bundle": "4.4.x-dev as 4.4.12"` in your `composer.json`. The issue has already been fixed.

**Comment by zodit** [comment]
Sorry if i change subject, but i have the same problem in Contao 3.5.33, and this has not Symfony related issues, isn't it? The search module is not working, i cleaned the cache and rebuilt the index (the process seems right, all pages are there and going "green"). But the truth is: no page is indexed. In my MySql DB i see the 2 tables "tl_search" and "tl_search_index" are empty.

**Comment by bytehead** [comment]
@zodit Search enabled? (`$GLOBALS['TL_CONFIG']['enableSearch']   = true;`)

**Comment by zodit** [comment]
@bytehead Where should i see that string? I don't see it in my "localconfig.php" or in my "initconfig.php", anywhere else?

**Comment by xchs** [comment]
If you don't see it there, the search function should be enabled by default.

**Comment by fritzmg** [comment]
@zodit I cannot confirm your problem. Search index works fine in Contao 3.5.33.

**Comment by zodit** [comment]
I moved the website on another server to make deep tests (disabling modules, putting safe mode, removing custom templates, etc...). Nothing about this. Finally i discovered the problem: it is in Maintenance. When i rebuild the index i do it with a registered member, because i need the research for some news inside the reserved area. This is not working, the tables are empty. Instead, if i rebuild the index selecting the guest (-) option, the index is working: 55 records in tl_search, and 8056 records in tl_search_index. But doing so, the reserved pages are not indexed. Is this some bug?

**Comment by daureluc** [comment]
Hi all, I have contao 4.4.14, I have read all threads on the subjects so far. And checked my files for the "patch" mentioned above. This is a fresh contao install i created to test the problem. 

The problem is: contao does not index any pages, even though it goes through the indexing process fine. The table don't get updated

 i know the following is unrelated but i just wanted to give some context:

 >

> i have uploaded the official demo and installed it, as well as isotope core and ical full calendar from martin/kozianka.
> All are installed and functioning. I also had to make a change in my mysql config to solve compatibility issue with isotope
> I have checked all files from patch c56cf49 and all are fine

> 

If anyone can help from here, it be great, i could really use this search engine :)
Thanks
