### ISSUE TITLE
HTML-Entitäten werden in den Übersetzungen wieder dekodiert

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core-bundle#1339]
Ganz einfach nachzustellen:

In der langconfig.php einfach folgende Zeile einfügen.

```php
$GLOBALS['TL_LANG']['tl_settings']['websiteTitle'][1] = '&lt;h1&gt;Hallo Welt!&lt;/h1&gt;&lt;title&gt;';
```
Danach in die Contao-Einstellungen gehen. Surprise 👍 

Das dekodierte Title-Tag sorgt in dem Fall dafür das der Rest einfach im Quelltext verschwindet. 

Im Use-Case ist mir das hier aufgefallen: https://github.com/Tastaturberuf/anyStores/blob/master/languages/de/tl_anystores.php#L44

Ist auch nicht in jeder 4.4-Bugfix-Version aufgetreten, muss eines der letzten Updates gewesen sein. Konnte das beim Zurückrollen aber nicht nachstellen.

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren:

<img width="548" alt="" src="https://user-images.githubusercontent.com/1192057/35434158-6a12170e-0286-11e8-8261-e8ed032fe53f.png">

Die Ausgabe im Quelltext ist unverändert so wie in der `langconfig.php` hinterlegt.

**Comment by Tastaturberuf** [comment]
Ich hab das in 3 Installationen (Nginx, Apache 2.4, PHP 7.0/7.1). Ich deaktiviere mal alles andere und berichte.

**Comment by Tastaturberuf** [comment]
OK ist Invalid, liegt an der Erweiterung https://github.com/OMOSde/contao-om-backend. Ich mach dort das Ticket auf. 'Tschuldigung.
