### ISSUE TITLE
Return value of MemoryTokenStorage::getUsedTokens() must be of the type array, null returned

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#1342]
https://github.com/contao/core-bundle/blob/3144e6820d56a8ed1604e47a3803e0fd72283c0c/src/Csrf/MemoryTokenStorage.php#L95

This happens because `$this->tokens` is still null. I think the correct solution would be to check for that case and return an empty array in the method.

**Comment by ausi** [comment]
How can `$this->tokens` be null?
Should we add `$this->assertInitialized();` to the `getUsedTokens()` method?

**Comment by aschempp** [comment]
I think we intentionally did not. The initialize method was not called, so no tokens were used and an empty array is the correct response.

**Comment by ausi** [comment]
Seems reasonable. So I agree that we should return an empty array if `$this->tokens` is `null`.

**Comment by leofeyer** [comment]
Fixed in e51323a251f8063863c1517a50eb2fd689085561.
