### ISSUE TITLE
Metadaten - Bildunterschrift mit Link

### ISSUE THREAD

**Issue by AgentCT** [contao/core-bundle#1343]
Das Feld "Bildunterschrift" in den Metadaten lässt zwar das Speichern von Links zu, jedoch werden die Links dann nicht im FE angezeigt. Bei einigen Bildern ist es jedoch wichtig, dass man nicht nur eine Bildunterschrift setzt sondern auch einen Link auf die jeweilige Lizenz des Bildes.

**Comment by Aybee** [comment]
Du musst die Metadaten als Eigenschaften der Bilder betrachten, so wie IPTC oder Exif Daten. Die Ausgabetemplates sind dann auf die zu erwatenden Ausgabewünsche der Mehrheit eingestellt. Wenn dir dies nicht reicht, dann muss du dein Ausgabetemplate anpassen.

Übrigens wird der Link aus dem Feld "Link" auch nur dann als Link ausgegeben, wenn im CE die Option "Full-size view/new window" angehakt ist.

**Comment by Aybee** [comment]
Zusätzlich kann man im Feld caption HTML eintragen.
caption:
```html
Go to <a href="https://contao.org/">contao.org</a>
```
