### ISSUE TITLE
No pretty error screen when 404 page is missing

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1345]
Currently, when you do not define a 404 page in the site structure, there's no pretty error screen by Contao. Is that the desired behaviour?

**Comment by leofeyer** [comment]
I don't know if we still desire this behavior, but it was the desired behavior when we first discussed the pretty error screens. We explicitly left 403 and 404 errors to the Symfony exception handler if there is no error page in the Contao site structure.

**Comment by Toflar** [comment]
Once https://github.com/contao/core-bundle/issues/1172 is resolved, this is okay for me. Closing.
