### ISSUE TITLE
404 page is not loaded from the correct page tree under certain circumstances

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1346]
Given the following site structure:

* domain.com, de (fallback)
    * 404 page
* domain.com, en
    * no 404 page

If you enable `prepend_locale` and you call `domain.com/de/whatever` **with an English browser** it will not find the correct 404 page, it will try to load it from the `en` page tree.
I would expect it to extract the `de` from the URL and thus find the correct root page and render the corresponding 404 page.

In Contao 4, everything is redirected to `app.php` and handled by Contao, so `/de/whatever` is handled by Contao no matter the `urlSuffix` you configured.

However, the code that extracts and sets the language from the URL is only executed (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Frontend.php#L107) **if the urlSuffix** matches (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Frontend.php#L90).

So in my opinion, extracting the language from the URL has to be done even if the `urlSuffix` does not match because otherwise it will fail here (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Frontend.php#L310) and thus no correct root page will be found and there's a nonsense 404 page that's going to be rendered.

I agree that the `urlSuffix` basically means "hey Contao, please do not handle this request" but still, the page handler is called. So either the request has to be completely ignored or the page handler should find the correct language.

/cc @qzminski

**Comment by fritzmg** [comment]
Duplicate of #1172 :)

**Comment by Toflar** [comment]
Ah true, thx! I only noticed because half of the pages logged exceptions and the other half did not :D
