### ISSUE TITLE
DCA Picker broken for articles (and possibly other entities that don't have children)

### ISSUE THREAD

**Issue by pwaldhauer** [contao/core-bundle#1347]
Contao Version: 4.4.12

**Steps to reproduce:**

- Add an "Text" Element to an article
- Add some text
- Use the "link" button in the TinyMCE to add a hyperlink to a part of the text
- In the shiny new DCA picker choose "articles"
- Choose any article from the list
- Save the text element
- Try to change the hyperlink by clicking the previously selected text and the "link" icon

**Expected result:**

The modal shows a list of articles where it should be possible to choose a new one to link to

**Result:**

The modal loads forever and fails either with a "Memory limited exhausted" error, or "Maximum function nesting level of '256' reached, aborting!", when xdebug is enabled.

Since the stacktrace contains a lot of `Contao\Database->getChildRecords( ???, ???, ???, ???, ??? )` I guess the `DC_Table->generateTree` tries so load the children of the articles from the... article table (which is not possible because the `pid` column of `tl_article` references `tl_page`...) and then gets stuck in an endless loop.

The queries that are generated on my system are confirming that:

```
SELECT id, pid FROM tl_article WHERE pid IN(12,2,19,18)
SELECT id, pid FROM tl_article WHERE pid IN(3,1,14)
```

(hundreds of them)

I can reproduce this behaviour on different systems that are on Contao 4.4.x

I don't really understand why it does not happen, when you open the picker for the first time (with no prior selection) -- getChildRecords seems not to be called in this situation.

**Quick fix:**

Replace line 528 of src/Resources/contao/library/Contao/Database.php with this:

`if (empty($arrParentIds) || $strTable === 'tl_article')`

**Comment by leofeyer** [comment]
I cannot reproduce the issue in my test environment. Did you check the online demo?

**Comment by naturefriend** [comment]
I get a memory error with linked articles with the following error messages. Using the hyperlink element.
And only for already linked articles. This does not happen with linked pages. If you change the link value to an external link for example and save it, you can work normally the next time you open the pagepicker.
As soon as the selected item (article) is saved, the error message appears the next time the DCA Picker is called.

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /XXX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 146

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /XXX/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php on line 626

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in Unknown on line 0`

**Comment by leofeyer** [comment]
@pwaldhauer Does the problem still occur?
