### ISSUE TITLE
install 4.5.3

### ISSUE THREAD

**Issue by goransi** [contao/core-bundle#1349]
I have successfuly installed Contao 4.5.3, but when I want to login to backend get this error:

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of Contao\CoreBundle\Translation\Translator::getFromGlobals() must be of the type string or null, array returned in /home/xtalkshop/public_html/vendor/contao/core-bundle/src/Translation/Translator.php:117 Stack trace:
#0 /home/xtalkshop/public_html/vendor/contao/core-bundle/src/Translation/Translator.php(57): Contao\CoreBundle\Translation\Translator->getFromGlobals('XPT.matter')
#1 /home/xtalkshop/public_html/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Extension/TranslationExtension.php(97): Contao\CoreBundle\Translation\Translator->trans('XPT.matter', Array, 'contao_exceptio...', NULL)
#2 /home/xtalkshop/public_html/var/cache/prod/twig/92/922f90196aa2effb3f07492a9adebbc553466d61af81d7e46f0e2d9baba77bfa.php(43): Symfony\Bridge\Twig\Extension\TranslationExtension->trans('XPT.matter', Array, 'contao_exceptio...') 
#3 /home/xtalkshop/public_html/vendor/twig/twig/lib/Twig/Template.php(188): __TwigTemplate_2605134ed37a940dab in /home/xtalkshop/public_html/vendor/contao/core-bundle/src/Translation/Translator.php on line 117

**Comment by leofeyer** [comment]
I cannot reproduce this in the online demo. Please refer to the [forums](https://community.contao.org).
