### ISSUE TITLE
Article list module does not check for articles

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#1351]
I'm getting a ContextError in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_articlelist.html5#L6 because the variable is not set if not articles are found in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleArticleList.php#L95

**Comment by leofeyer** [comment]
Fixed in db5f60bcd8f6a3e8c2f588cbcf7810fa1e5f0881.
