### ISSUE TITLE
C45 keine automatische Seitenalias Generierung

### ISSUE THREAD

**Issue by MaCo7** [contao/core-bundle#1352]
**Hosting Mittwald, managed V-Server: mySQL5.7x / mySQL5.6x, PHP7.1 FPM.**

Contao generiert keine Seitenaliase. Diese müssen manuell eingegeben werden sonst Fehlermeldung: "No Transliterator transform rule found for "$AE = [Ä {A \u0308}];$OE = [Ö {O \u0308}];$UE = [Ü {U "

VG Martin

**Comment by fritzmg** [comment]
/cc @ausi 

War die ursprüngliche Fehlermeldung nicht
```
No Transliterator transform rule found for "ASCII" with locale ""
```
? Siehe https://community.contao.org/de/showthread.php?69650-Contao-4-5-Mittwald

**Comment by ausi** [comment]
Die Fehlermeldung deutet darauf hin, dass die `Transliterator`-Klasse auf dem Webserver nicht korrekt funktioniert.

Kannst du bitte folgende Zeilen auf dem Server ausführen und das Resultat davon hier posten?

```php
var_dump(\Transliterator::create('Latin-ASCII'));
var_dump(\Transliterator::createFromRules('::Latin-ASCII;'));
var_dump(in_array('Latin-ASCII', \Transliterator::listIDs(), true));
var_dump(\Transliterator::listIDs());
```

**Comment by MaCo7** [comment]
Hallo, ja das hängt anscheinend davon ab, was man unter "Alias Einstellungen" -> "Gültige Alias-Zeichen". Diese Meldung kommt bei mir, wenn ich nichts einstelle.

**Comment by MaCo7** [comment]
@ausi 
Du meinst via SSH Shell? Da kommen folgenden Fehlermeldungen, wenn ich das direkt eintippe. 
-bash: Syntaxfehler beim unerwarteten Wort `\Transliterator::create'
-bash: Syntaxfehler beim unerwarteten Wort `\Transliterator::createFromRules'
-bash: Syntaxfehler beim unerwarteten Wort `in_array'
-bash: Syntaxfehler beim unerwarteten Wort `\Transliterator::listIDs'

**Comment by ausi** [comment]
Die Zeilen sind PHP-Code, für die Ausführung direkt auf der command line kannst du folgendes verwenden:

```sh
php -r "var_dump(\Transliterator::create('Latin-ASCII')); var_dump(\Transliterator::createFromRules('::Latin-ASCII;')); var_dump(in_array('Latin-ASCII', \Transliterator::listIDs(), true));"
```

und:

```sh
php -r "var_dump(\Transliterator::listIDs());"
```

**Comment by MaCo7** [comment]
Ich wusste da stimmt was nicht ;)
Error in argument 1, char 2: option not found r
Denke das geht so auch nicht via ssh?

**Comment by MaCo7** [comment]
Error in argument 1, char 2: option not found r
Usage: php [-q] [-h] [-s] [-v] [-i] [-f <file>]
       php <file> [args...]
  -a               Run interactively
  -b <address:port>|<port> Bind Path for external FASTCGI Server mode
  -C               Do not chdir to the script's directory
  -c <path>|<file> Look for php.ini file in this directory
  -n               No php.ini file will be used
  -d foo[=bar]     Define INI entry foo with value 'bar'
  -e               Generate extended information for debugger/profiler
  -f <file>        Parse <file>.  Implies `-q'
  -h               This help
  -i               PHP information
  -l               Syntax check only (lint)
  -m               Show compiled in modules
  -q               Quiet-mode.  Suppress HTTP Header output.
  -s               Display colour syntax highlighted source.
  -v               Version number
  -w               Display source with stripped comments and whitespace.
  -z <file>        Load Zend extension <file>.
  -T <count>       Measure execution time of script repeated <count> times.

**Comment by fritzmg** [comment]
That's the wrong PHP executable. You need a PHP CLI.

**Comment by MaCo7** [comment]
Server runs on 7.1 FPM. Can i set PHP CLI on SSH?

**Comment by ausi** [comment]
`php -a` sollte auch ausreichen:

```sh
echo "var_dump(\Transliterator::create('Latin-ASCII')); var_dump(\Transliterator::createFromRules('::Latin-ASCII;')); var_dump(in_array('Latin-ASCII', \Transliterator::listIDs(), true));" | php -a
```

```sh
echo "var_dump(\Transliterator::listIDs());" | php -a
```

**Comment by fritzmg** [comment]
Siehe https://github.com/contao/contao-manager/wiki/Mittwald
```
/usr/local/bin/php_cli
```

**Comment by MaCo7** [comment]
Also, wenn ich das via php_cli aufrufe:

php_cli -r "var_dump(\Transliterator::create('Latin-ASCII')); var_dump(\Transliterator::createFromRules('::Latin-ASCII;')); var_dump(in_array('Latin-ASCII', \Transliterator::listIDs(), true));"

```
object(Transliterator)#1 (1) {
  ["id"]=>
  string(11) "Latin-ASCII"
}
object(Transliterator)#1 (1) {
  ["id"]=>
  string(13) "RulesTransPHP"
}
bool(true)
```

--------------

php_cli -r "var_dump(\Transliterator::listIDs());"

```
array(273) {
  [0]=>
  string(11) "ASCII-Latin"
  [1]=>
  string(11) "Accents-Any"
  [2]=>
  string(17) "Amharic-Latin/BGN"
  [3]=>
  string(11) "Any-Accents"
  [4]=>
  string(14) "Any-Publishing"
  [5]=>
  string(12) "Arabic-Latin"
  [6]=>
  string(16) "Arabic-Latin/BGN"
  [7]=>
  string(14) "Armenian-Latin"
  [8]=>
  string(18) "Armenian-Latin/BGN"
  [9]=>
  string(21) "Azerbaijani-Latin/BGN"
  [10]=>
  string(20) "Belarusian-Latin/BGN"
  [11]=>
  string(18) "Bengali-Devanagari"
  [12]=>
  string(16) "Bengali-Gujarati"
  [13]=>
  string(16) "Bengali-Gurmukhi"
  [14]=>
  string(15) "Bengali-Kannada"
  [15]=>
  string(13) "Bengali-Latin"
  [16]=>
  string(17) "Bengali-Malayalam"
  [17]=>
  string(13) "Bengali-Oriya"
  [18]=>
  string(13) "Bengali-Tamil"
  [19]=>
  string(14) "Bengali-Telugu"
  [20]=>
  string(14) "Bopomofo-Latin"
  [21]=>
  string(19) "Bulgarian-Latin/BGN"
  [22]=>
  string(14) "Cyrillic-Latin"
  [23]=>
  string(18) "Devanagari-Bengali"
  [24]=>
  string(19) "Devanagari-Gujarati"
  [25]=>
  string(19) "Devanagari-Gurmukhi"
  [26]=>
  string(18) "Devanagari-Kannada"
  [27]=>
  string(16) "Devanagari-Latin"
  [28]=>
  string(20) "Devanagari-Malayalam"
  [29]=>
  string(16) "Devanagari-Oriya"
  [30]=>
  string(16) "Devanagari-Tamil"
  [31]=>
  string(17) "Devanagari-Telugu"
  [32]=>
  string(10) "Digit-Tone"
  [33]=>
  string(19) "Fullwidth-Halfwidth"
  [34]=>
  string(14) "Georgian-Latin"
  [35]=>
  string(18) "Georgian-Latin/BGN"
  [36]=>
  string(11) "Greek-Latin"
  [37]=>
  string(15) "Greek-Latin/BGN"
  [38]=>
  string(18) "Greek-Latin/UNGEGN"
  [39]=>
  string(16) "Gujarati-Bengali"
  [40]=>
  string(19) "Gujarati-Devanagari"
  [41]=>
  string(17) "Gujarati-Gurmukhi"
  [42]=>
  string(16) "Gujarati-Kannada"
  [43]=>
  string(14) "Gujarati-Latin"
  [44]=>
  string(18) "Gujarati-Malayalam"
  [45]=>
  string(14) "Gujarati-Oriya"
  [46]=>
  string(14) "Gujarati-Tamil"
  [47]=>
  string(15) "Gujarati-Telugu"
  [48]=>
  string(16) "Gurmukhi-Bengali"
  [49]=>
  string(19) "Gurmukhi-Devanagari"
  [50]=>
  string(17) "Gurmukhi-Gujarati"
  [51]=>
  string(16) "Gurmukhi-Kannada"
  [52]=>
  string(14) "Gurmukhi-Latin"
  [53]=>
  string(18) "Gurmukhi-Malayalam"
  [54]=>
  string(14) "Gurmukhi-Oriya"
  [55]=>
  string(14) "Gurmukhi-Tamil"
  [56]=>
  string(15) "Gurmukhi-Telugu"
  [57]=>
  string(19) "Halfwidth-Fullwidth"
  [58]=>
  string(9) "Han-Latin"
  [59]=>
  string(15) "Han-Latin/Names"
  [60]=>
  string(12) "Hangul-Latin"
  [61]=>
  string(9) "Hans-Hant"
  [62]=>
  string(9) "Hant-Hans"
  [63]=>
  string(12) "Hebrew-Latin"
  [64]=>
  string(16) "Hebrew-Latin/BGN"
  [65]=>
  string(17) "Hiragana-Katakana"
  [66]=>
  string(14) "Hiragana-Latin"
  [67]=>
  string(10) "IPA-XSampa"
  [68]=>
  string(10) "Jamo-Latin"
  [69]=>
  string(22) "JapaneseKana-Latin/BGN"
  [70]=>
  string(15) "Kannada-Bengali"
  [71]=>
  string(18) "Kannada-Devanagari"
  [72]=>
  string(16) "Kannada-Gujarati"
  [73]=>
  string(16) "Kannada-Gurmukhi"
  [74]=>
  string(13) "Kannada-Latin"
  [75]=>
  string(17) "Kannada-Malayalam"
  [76]=>
  string(13) "Kannada-Oriya"
  [77]=>
  string(13) "Kannada-Tamil"
  [78]=>
  string(14) "Kannada-Telugu"
  [79]=>
  string(17) "Katakana-Hiragana"
  [80]=>
  string(14) "Katakana-Latin"
  [81]=>
  string(16) "Kazakh-Latin/BGN"
  [82]=>
  string(17) "Kirghiz-Latin/BGN"
  [83]=>
  string(16) "Korean-Latin/BGN"
  [84]=>
  string(11) "Latin-ASCII"
  [85]=>
  string(12) "Latin-Arabic"
  [86]=>
  string(14) "Latin-Armenian"
  [87]=>
  string(13) "Latin-Bengali"
  [88]=>
  string(14) "Latin-Bopomofo"
  [89]=>
  string(14) "Latin-Cyrillic"
  [90]=>
  string(16) "Latin-Devanagari"
  [91]=>
  string(14) "Latin-Georgian"
  [92]=>
  string(11) "Latin-Greek"
  [93]=>
  string(18) "Latin-Greek/UNGEGN"
  [94]=>
  string(14) "Latin-Gujarati"
  [95]=>
  string(14) "Latin-Gurmukhi"
  [96]=>
  string(12) "Latin-Hangul"
  [97]=>
  string(12) "Latin-Hebrew"
  [98]=>
  string(14) "Latin-Hiragana"
  [99]=>
  string(10) "Latin-Jamo"
  [100]=>
  string(13) "Latin-Kannada"
  [101]=>
  string(14) "Latin-Katakana"
  [102]=>
  string(15) "Latin-Malayalam"
  [103]=>
  string(19) "Latin-NumericPinyin"
  [104]=>
  string(11) "Latin-Oriya"
  [105]=>
  string(12) "Latin-Syriac"
  [106]=>
  string(11) "Latin-Tamil"
  [107]=>
  string(12) "Latin-Telugu"
  [108]=>
  string(12) "Latin-Thaana"
  [109]=>
  string(10) "Latin-Thai"
  [110]=>
  string(20) "Macedonian-Latin/BGN"
  [111]=>
  string(17) "Malayalam-Bengali"
  [112]=>
  string(20) "Malayalam-Devanagari"
  [113]=>
  string(18) "Malayalam-Gujarati"
  [114]=>
  string(18) "Malayalam-Gurmukhi"
  [115]=>
  string(17) "Malayalam-Kannada"
  [116]=>
  string(15) "Malayalam-Latin"
  [117]=>
  string(15) "Malayalam-Oriya"
  [118]=>
  string(15) "Malayalam-Tamil"
  [119]=>
  string(16) "Malayalam-Telugu"
  [120]=>
  string(19) "Maldivian-Latin/BGN"
  [121]=>
  string(19) "Mongolian-Latin/BGN"
  [122]=>
  string(19) "NumericPinyin-Latin"
  [123]=>
  string(20) "NumericPinyin-Pinyin"
  [124]=>
  string(13) "Oriya-Bengali"
  [125]=>
  string(16) "Oriya-Devanagari"
  [126]=>
  string(14) "Oriya-Gujarati"
  [127]=>
  string(14) "Oriya-Gurmukhi"
  [128]=>
  string(13) "Oriya-Kannada"
  [129]=>
  string(11) "Oriya-Latin"
  [130]=>
  string(15) "Oriya-Malayalam"
  [131]=>
  string(11) "Oriya-Tamil"
  [132]=>
  string(12) "Oriya-Telugu"
  [133]=>
  string(16) "Pashto-Latin/BGN"
  [134]=>
  string(17) "Persian-Latin/BGN"
  [135]=>
  string(20) "Pinyin-NumericPinyin"
  [136]=>
  string(14) "Publishing-Any"
  [137]=>
  string(17) "Russian-Latin/BGN"
  [138]=>
  string(17) "Serbian-Latin/BGN"
  [139]=>
  string(22) "Simplified-Traditional"
  [140]=>
  string(12) "Syriac-Latin"
  [141]=>
  string(13) "Tamil-Bengali"
  [142]=>
  string(16) "Tamil-Devanagari"
  [143]=>
  string(14) "Tamil-Gujarati"
  [144]=>
  string(14) "Tamil-Gurmukhi"
  [145]=>
  string(13) "Tamil-Kannada"
  [146]=>
  string(11) "Tamil-Latin"
  [147]=>
  string(15) "Tamil-Malayalam"
  [148]=>
  string(11) "Tamil-Oriya"
  [149]=>
  string(12) "Tamil-Telugu"
  [150]=>
  string(14) "Telugu-Bengali"
  [151]=>
  string(17) "Telugu-Devanagari"
  [152]=>
  string(15) "Telugu-Gujarati"
  [153]=>
  string(15) "Telugu-Gurmukhi"
  [154]=>
  string(14) "Telugu-Kannada"
  [155]=>
  string(12) "Telugu-Latin"
  [156]=>
  string(16) "Telugu-Malayalam"
  [157]=>
  string(12) "Telugu-Oriya"
  [158]=>
  string(12) "Telugu-Tamil"
  [159]=>
  string(12) "Thaana-Latin"
  [160]=>
  string(10) "Thai-Latin"
  [161]=>
  string(10) "Tone-Digit"
  [162]=>
  string(22) "Traditional-Simplified"
  [163]=>
  string(17) "Turkmen-Latin/BGN"
  [164]=>
  string(19) "Ukrainian-Latin/BGN"
  [165]=>
  string(15) "Uzbek-Latin/BGN"
  [166]=>
  string(10) "XSampa-IPA"
  [167]=>
  string(8) "az-Lower"
  [168]=>
  string(8) "az-Title"
  [169]=>
  string(8) "az-Upper"
  [170]=>
  string(12) "cs-cs_FONIPA"
  [171]=>
  string(5) "cs-ja"
  [172]=>
  string(5) "cs-ko"
  [173]=>
  string(12) "cs_FONIPA-ja"
  [174]=>
  string(12) "cs_FONIPA-ko"
  [175]=>
  string(8) "el-Lower"
  [176]=>
  string(8) "el-Title"
  [177]=>
  string(8) "el-Upper"
  [178]=>
  string(5) "es-am"
  [179]=>
  string(12) "es-es_FONIPA"
  [180]=>
  string(5) "es-ja"
  [181]=>
  string(5) "es-zh"
  [182]=>
  string(9) "es_419-ja"
  [183]=>
  string(9) "es_419-zh"
  [184]=>
  string(12) "es_FONIPA-am"
  [185]=>
  string(23) "es_FONIPA-es_419_FONIPA"
  [186]=>
  string(12) "es_FONIPA-ja"
  [187]=>
  string(12) "es_FONIPA-zh"
  [188]=>
  string(5) "it-am"
  [189]=>
  string(5) "it-ja"
  [190]=>
  string(10) "ja_Latn-ko"
  [191]=>
  string(10) "ja_Latn-ru"
  [192]=>
  string(8) "lt-Lower"
  [193]=>
  string(8) "lt-Title"
  [194]=>
  string(8) "lt-Upper"
  [195]=>
  string(8) "nl-Title"
  [196]=>
  string(5) "pl-ja"
  [197]=>
  string(12) "pl-pl_FONIPA"
  [198]=>
  string(12) "pl_FONIPA-ja"
  [199]=>
  string(5) "ro-ja"
  [200]=>
  string(12) "ro-ro_FONIPA"
  [201]=>
  string(12) "ro_FONIPA-ja"
  [202]=>
  string(5) "ru-ja"
  [203]=>
  string(5) "ru-zh"
  [204]=>
  string(5) "sk-ja"
  [205]=>
  string(12) "sk-sk_FONIPA"
  [206]=>
  string(12) "sk_FONIPA-ja"
  [207]=>
  string(8) "tr-Lower"
  [208]=>
  string(8) "tr-Title"
  [209]=>
  string(8) "tr-Upper"
  [210]=>
  string(17) "zh_Latn_PINYIN-ru"
  [211]=>
  string(8) "Any-Null"
  [212]=>
  string(9) "Any-Lower"
  [213]=>
  string(9) "Any-Upper"
  [214]=>
  string(9) "Any-Title"
  [215]=>
  string(8) "Any-Name"
  [216]=>
  string(8) "Name-Any"
  [217]=>
  string(10) "Any-Remove"
  [218]=>
  string(15) "Any-Hex/Unicode"
  [219]=>
  string(12) "Any-Hex/Java"
  [220]=>
  string(9) "Any-Hex/C"
  [221]=>
  string(11) "Any-Hex/XML"
  [222]=>
  string(13) "Any-Hex/XML10"
  [223]=>
  string(12) "Any-Hex/Perl"
  [224]=>
  string(7) "Any-Hex"
  [225]=>
  string(15) "Hex-Any/Unicode"
  [226]=>
  string(12) "Hex-Any/Java"
  [227]=>
  string(9) "Hex-Any/C"
  [228]=>
  string(11) "Hex-Any/XML"
  [229]=>
  string(13) "Hex-Any/XML10"
  [230]=>
  string(12) "Hex-Any/Perl"
  [231]=>
  string(7) "Hex-Any"
  [232]=>
  string(7) "Any-NFC"
  [233]=>
  string(8) "Any-NFKC"
  [234]=>
  string(7) "Any-NFD"
  [235]=>
  string(8) "Any-NFKD"
  [236]=>
  string(7) "Any-FCD"
  [237]=>
  string(7) "Any-FCC"
  [238]=>
  string(9) "Any-Latin"
  [239]=>
  string(10) "Any-Telugu"
  [240]=>
  string(12) "Any-Gurmukhi"
  [241]=>
  string(12) "Any-Gujarati"
  [242]=>
  string(13) "Any-Malayalam"
  [243]=>
  string(9) "Any-Oriya"
  [244]=>
  string(14) "Any-Devanagari"
  [245]=>
  string(11) "Any-Kannada"
  [246]=>
  string(9) "Any-Tamil"
  [247]=>
  string(13) "Any-cs_FONIPA"
  [248]=>
  string(6) "Any-ru"
  [249]=>
  string(11) "Any-Bengali"
  [250]=>
  string(12) "Any-Katakana"
  [251]=>
  string(13) "Any-ro_FONIPA"
  [252]=>
  string(6) "Any-zh"
  [253]=>
  string(6) "Any-am"
  [254]=>
  string(17) "Any-es_419_FONIPA"
  [255]=>
  string(13) "Any-es_FONIPA"
  [256]=>
  string(13) "Any-sk_FONIPA"
  [257]=>
  string(8) "Any-Hant"
  [258]=>
  string(8) "Any-Hans"
  [259]=>
  string(12) "Any-Hiragana"
  [260]=>
  string(10) "Any-Syriac"
  [261]=>
  string(9) "Any-Greek"
  [262]=>
  string(16) "Any-Greek/UNGEGN"
  [263]=>
  string(12) "Any-Cyrillic"
  [264]=>
  string(10) "Any-Hangul"
  [265]=>
  string(12) "Any-Bopomofo"
  [266]=>
  string(10) "Any-Arabic"
  [267]=>
  string(8) "Any-Thai"
  [268]=>
  string(12) "Any-Armenian"
  [269]=>
  string(10) "Any-Thaana"
  [270]=>
  string(12) "Any-Georgian"
  [271]=>
  string(10) "Any-Hebrew"
  [272]=>
  string(13) "Any-pl_FONIPA"
```

**Comment by ausi** [comment]
Dann verstehe ich nicht wie es zu der Fehlermeldung `No Transliterator transform rule found …` kommen kann. Ist eventuell das PHP-Setup für die CLI anders als für den Webprozess?

Erstellen bitte eine PHP-Datei mit folgendem Inhalt auf dem Webserver:

```php
<?php
var_dump(\Transliterator::create('Latin-ASCII'));
var_dump(\Transliterator::createFromRules('::Latin-ASCII;'));
var_dump(in_array('Latin-ASCII', \Transliterator::listIDs(), true));
var_dump(\Transliterator::listIDs());
```

und rufe die Datei über den Browser auf.

**Comment by MaCo7** [comment]
8-) Da kommt so etwas:

`NULL NULL bool(false) array(210) { [0]=> string(11) "Accents-Any" [1]=> string(17) "Amharic-Latin/BGN" [2]=> string(11) "Any-Accents" [3]=> string(14) "Any-Publishing" [4]=> string(12) "Arabic-Latin" [5]=> string(16) "Arabic-Latin/BGN" [6]=> string(14) "Armenian-Latin" [7]=> string(18) "Armenian-Latin/BGN" [8]=> string(21) "Azerbaijani-Latin/BGN" [9]=> string(20) "Belarusian-Latin/BGN" [10]=> string(18) "Bengali-Devanagari" [11]=> string(16) "Bengali-Gujarati" [12]=> string(16) "Bengali-Gurmukhi" [13]=> string(15) "Bengali-Kannada" [14]=> string(13) "Bengali-Latin" [15]=> string(17) "Bengali-Malayalam" [16]=> string(13) "Bengali-Oriya" [17]=> string(13) "Bengali-Tamil" [18]=> string(14) "Bengali-Telugu" [19]=> string(19) "Bulgarian-Latin/BGN" [20]=> string(14) "Cyrillic-Latin" [21]=> string(18) "Devanagari-Bengali" [22]=> string(19) "Devanagari-Gujarati" [23]=> string(19) "Devanagari-Gurmukhi" [24]=> string(18) "Devanagari-Kannada" [25]=> string(16) "Devanagari-Latin" [26]=> string(20) "Devanagari-Malayalam" [27]=> string(16) "Devanagari-Oriya" [28]=> string(16) "Devanagari-Tamil" [29]=> string(17) "Devanagari-Telugu" [30]=> string(10) "Digit-Tone" [31]=> string(19) "Fullwidth-Halfwidth" [32]=> string(14) "Georgian-Latin" [33]=> string(18) "Georgian-Latin/BGN" [34]=> string(11) "Greek-Latin" [35]=> string(15) "Greek-Latin/BGN" [36]=> string(18) "Greek-Latin/UNGEGN" [37]=> string(16) "Gujarati-Bengali" [38]=> string(19) "Gujarati-Devanagari" [39]=> string(17) "Gujarati-Gurmukhi" [40]=> string(16) "Gujarati-Kannada" [41]=> string(14) "Gujarati-Latin" [42]=> string(18) "Gujarati-Malayalam" [43]=> string(14) "Gujarati-Oriya" [44]=> string(14) "Gujarati-Tamil" [45]=> string(15) "Gujarati-Telugu" [46]=> string(16) "Gurmukhi-Bengali" [47]=> string(19) "Gurmukhi-Devanagari" [48]=> string(17) "Gurmukhi-Gujarati" [49]=> string(16) "Gurmukhi-Kannada" [50]=> string(14) "Gurmukhi-Latin" [51]=> string(18) "Gurmukhi-Malayalam" [52]=> string(14) "Gurmukhi-Oriya" [53]=> string(14) "Gurmukhi-Tamil" [54]=> string(15) "Gurmukhi-Telugu" [55]=> string(19) "Halfwidth-Fullwidth" [56]=> string(9) "Han-Latin" [57]=> string(12) "Hangul-Latin" [58]=> string(12) "Hebrew-Latin" [59]=> string(16) "Hebrew-Latin/BGN" [60]=> string(17) "Hiragana-Katakana" [61]=> string(14) "Hiragana-Latin" [62]=> string(10) "Jamo-Latin" [63]=> string(22) "JapaneseKana-Latin/BGN" [64]=> string(15) "Kannada-Bengali" [65]=> string(18) "Kannada-Devanagari" [66]=> string(16) "Kannada-Gujarati" [67]=> string(16) "Kannada-Gurmukhi" [68]=> string(13) "Kannada-Latin" [69]=> string(17) "Kannada-Malayalam" [70]=> string(13) "Kannada-Oriya" [71]=> string(13) "Kannada-Tamil" [72]=> string(14) "Kannada-Telugu" [73]=> string(17) "Katakana-Hiragana" [74]=> string(14) "Katakana-Latin" [75]=> string(16) "Kazakh-Latin/BGN" [76]=> string(17) "Kirghiz-Latin/BGN" [77]=> string(16) "Korean-Latin/BGN" [78]=> string(12) "Latin-Arabic" [79]=> string(14) "Latin-Armenian" [80]=> string(13) "Latin-Bengali" [81]=> string(14) "Latin-Cyrillic" [82]=> string(16) "Latin-Devanagari" [83]=> string(14) "Latin-Georgian" [84]=> string(11) "Latin-Greek" [85]=> string(18) "Latin-Greek/UNGEGN" [86]=> string(14) "Latin-Gujarati" [87]=> string(14) "Latin-Gurmukhi" [88]=> string(9) "Latin-Han" [89]=> string(12) "Latin-Hangul" [90]=> string(12) "Latin-Hebrew" [91]=> string(14) "Latin-Hiragana" [92]=> string(10) "Latin-Jamo" [93]=> string(13) "Latin-Kannada" [94]=> string(14) "Latin-Katakana" [95]=> string(15) "Latin-Malayalam" [96]=> string(19) "Latin-NumericPinyin" [97]=> string(11) "Latin-Oriya" [98]=> string(12) "Latin-Syriac" [99]=> string(11) "Latin-Tamil" [100]=> string(12) "Latin-Telugu" [101]=> string(12) "Latin-Thaana" [102]=> string(10) "Latin-Thai" [103]=> string(20) "Macedonian-Latin/BGN" [104]=> string(17) "Malayalam-Bengali" [105]=> string(20) "Malayalam-Devanagari" [106]=> string(18) "Malayalam-Gujarati" [107]=> string(18) "Malayalam-Gurmukhi" [108]=> string(17) "Malayalam-Kannada" [109]=> string(15) "Malayalam-Latin" [110]=> string(15) "Malayalam-Oriya" [111]=> string(15) "Malayalam-Tamil" [112]=> string(16) "Malayalam-Telugu" [113]=> string(19) "Maldivian-Latin/BGN" [114]=> string(19) "Mongolian-Latin/BGN" [115]=> string(19) "NumericPinyin-Latin" [116]=> string(20) "NumericPinyin-Pinyin" [117]=> string(13) "Oriya-Bengali" [118]=> string(16) "Oriya-Devanagari" [119]=> string(14) "Oriya-Gujarati" [120]=> string(14) "Oriya-Gurmukhi" [121]=> string(13) "Oriya-Kannada" [122]=> string(11) "Oriya-Latin" [123]=> string(15) "Oriya-Malayalam" [124]=> string(11) "Oriya-Tamil" [125]=> string(12) "Oriya-Telugu" [126]=> string(16) "Pashto-Latin/BGN" [127]=> string(17) "Persian-Latin/BGN" [128]=> string(20) "Pinyin-NumericPinyin" [129]=> string(14) "Publishing-Any" [130]=> string(17) "Russian-Latin/BGN" [131]=> string(17) "Serbian-Latin/BGN" [132]=> string(22) "Simplified-Traditional" [133]=> string(12) "Syriac-Latin" [134]=> string(13) "Tamil-Bengali" [135]=> string(16) "Tamil-Devanagari" [136]=> string(14) "Tamil-Gujarati" [137]=> string(14) "Tamil-Gurmukhi" [138]=> string(13) "Tamil-Kannada" [139]=> string(11) "Tamil-Latin" [140]=> string(15) "Tamil-Malayalam" [141]=> string(11) "Tamil-Oriya" [142]=> string(12) "Tamil-Telugu" [143]=> string(14) "Telugu-Bengali" [144]=> string(17) "Telugu-Devanagari" [145]=> string(15) "Telugu-Gujarati" [146]=> string(15) "Telugu-Gurmukhi" [147]=> string(14) "Telugu-Kannada" [148]=> string(12) "Telugu-Latin" [149]=> string(16) "Telugu-Malayalam" [150]=> string(12) "Telugu-Oriya" [151]=> string(12) "Telugu-Tamil" [152]=> string(12) "Thaana-Latin" [153]=> string(10) "Thai-Latin" [154]=> string(10) "Tone-Digit" [155]=> string(22) "Traditional-Simplified" [156]=> string(17) "Turkmen-Latin/BGN" [157]=> string(19) "Ukrainian-Latin/BGN" [158]=> string(15) "Uzbek-Latin/BGN" [159]=> string(8) "Any-Null" [160]=> string(9) "Any-Lower" [161]=> string(9) "Any-Upper" [162]=> string(9) "Any-Title" [163]=> string(8) "Any-Name" [164]=> string(8) "Name-Any" [165]=> string(10) "Any-Remove" [166]=> string(15) "Any-Hex/Unicode" [167]=> string(12) "Any-Hex/Java" [168]=> string(9) "Any-Hex/C" [169]=> string(11) "Any-Hex/XML" [170]=> string(13) "Any-Hex/XML10" [171]=> string(12) "Any-Hex/Perl" [172]=> string(7) "Any-Hex" [173]=> string(15) "Hex-Any/Unicode" [174]=> string(12) "Hex-Any/Java" [175]=> string(9) "Hex-Any/C" [176]=> string(11) "Hex-Any/XML" [177]=> string(13) "Hex-Any/XML10" [178]=> string(12) "Hex-Any/Perl" [179]=> string(7) "Hex-Any" [180]=> string(7) "Any-NFC" [181]=> string(8) "Any-NFKC" [182]=> string(7) "Any-NFD" [183]=> string(8) "Any-NFKD" [184]=> string(7) "Any-FCD" [185]=> string(7) "Any-FCC" [186]=> string(9) "Any-Latin" [187]=> string(10) "Any-Syriac" [188]=> string(9) "Any-Greek" [189]=> string(16) "Any-Greek/UNGEGN" [190]=> string(10) "Any-Telugu" [191]=> string(12) "Any-Gurmukhi" [192]=> string(12) "Any-Cyrillic" [193]=> string(10) "Any-Hangul" [194]=> string(11) "Any-Bengali" [195]=> string(12) "Any-Katakana" [196]=> string(10) "Any-Arabic" [197]=> string(8) "Any-Thai" [198]=> string(12) "Any-Gujarati" [199]=> string(13) "Any-Malayalam" [200]=> string(12) "Any-Hiragana" [201]=> string(12) "Any-Armenian" [202]=> string(10) "Any-Thaana" [203]=> string(7) "Any-Han" [204]=> string(12) "Any-Georgian" [205]=> string(9) "Any-Oriya" [206]=> string(14) "Any-Devanagari" [207]=> string(10) "Any-Hebrew" [208]=> string(11) "Any-Kannada" [209]=> string(9) "Any-Tamil" }`

**Comment by ausi** [comment]
Wir kommen dem Problem schon näher. Anscheinend fehlen im PHP-Setup des Webprozesses einige Transformation-Rules. Wiederhole bitte den Test mit der PHP-Datei, diesmal mit folgendem Inhalt:

```php
<?php
var_dump(INTL_ICU_VERSION);
(new \ReflectionExtension('intl'))->info();
```

**Comment by MaCo7** [comment]
Das gibt folgendes aus:

```
string(5) "4.4.1"
intl
Internationalization support	enabled
version	1.1.0
ICU version	4.4.1
ICU Data version	4.4.0.1
Directive	Local Value	Master Value
intl.default_locale	no value	no value
intl.error_level	0	0
intl.use_exceptions	0	0
```

**Comment by ausi** [comment]
Ich hab etwas nachgeforscht: die ICU-Version 4.4.1 ist leider zu alt. Mindest-Version ist 4.6 (aus 2010).

Ich habe ein issue dafür in ausi/slug-generator#9 angelegt damit wir in Zukunft die Version als Requirement für Composer definiert haben.

Die beste Lösung für dich ist vermutlich beim Hoster um ein Update der lib-ICU zu bitten (aktuelle Version ist 60.2). Im CLI-PHP ist ja bereits eine neuere Version im Einsatz.

**Comment by MaCo7** [comment]
Vielen Dank Martin, für Deinen zielführenden Einsatz!

**Comment by ausi** [comment]
Falls du in Kontakt mit dem Hoster trittst, wäre es super wenn du auch gleich nachfragen könntest wie das mit den anderen Hostingpaketen und lib-ICU aussieht. Falls sie kein Update durchfüren, wäre es toll wenn du die Info ins Wiki schreiben könntest: https://github.com/contao/contao-manager/wiki/Mittwald

**Comment by MaCo7** [comment]
Werde ich machen! Thx!

**Comment by ausi** [comment]
> Ich habe ein issue dafür in ausi/slug-generator#9 angelegt damit wir in Zukunft die Version als Requirement für Composer definiert haben.

Erledigt in [Version 1.0.1](https://github.com/ausi/slug-generator/releases/tag/v1.0.1).

**Comment by ausi** [comment]
Seit Version [1.0.2](https://github.com/ausi/slug-generator/releases/tag/v1.0.2) ist `ausi/slug-generator` auch mit ICU 4.4 kompatibel.
