### ISSUE TITLE
Set background color for textfields

### ISSUE THREAD

**Issue by pxlcore** [contao/core-bundle#1354]
Hi, 

I'm on a linux system using a dark theme for my desktop.
In this theme all textboxes have a dark grey background color. This is also for HTML form fields.

See my screenshot:
![Screenshot](https://9xd56g-db3pap001.files.1drv.com/y4mJWiZmpd5BTDSfaVaUxYIdzzIREiibVDuArjQf7VeekNiVZCax47gEdb1ua-gv45-7K0OqsO9BxDpkx8ULwN8BbnKv84YIgJEBbBw-WeNayYADEet58lC_vMDqiCCVshuf33gB05OiWCsxdV-OCrpofjAmq32PVbm49M1hNo1vIn4xphDZAdjR4JPiTHQpNBmHV1pf92mvcVEorZ-6d-LRA?width=752&height=455&cropmode=none "Dark Theme: Arc")

Please add a white color in the CSS to the form fields. It's hard to read the black text on a dark grey background.

Thanks.

**Comment by leofeyer** [comment]
Added in 0bef2ae899281b1b8cd8e73e7a011d2d2323f577.
