### ISSUE TITLE
bitte löschen

### ISSUE THREAD

**Issue by akroii** [contao/core-bundle#1355]
bitte löschen

**Comment by ausi** [comment]
Auf beiden screenshots steht 4.4.13 :)

**Comment by akroii** [comment]
Ja, 2 Monate davor stand immer nur 4.4.9 *schnauf* 

Ich zweifelte schon an mir :(

**Comment by aschempp** [comment]
Es ist so dass der Manager die Version des `manager-bundle` anzeigt, das Backend aber die Version des `core-bundle`. In Zukunft wird die immer identisch sein.
