### ISSUE TITLE
Contao 4.5 Environment::get('base') broken in custom entrypoint

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#1356]
When using a custom entrypoint the base url returned by `Environment::get('base')` is broken. It was working up to Contao 4.4. Since 4.5 it's broken.

For more details you may have a look at 
 - https://github.com/netzmacht/contao-icon-wizard/issues/11
 - https://github.com/netzmacht/contao-icon-wizard/blob/master/module/public/popup.php
 - https://github.com/netzmacht/contao-icon-wizard/blob/master/src/WizardController.php#L89

I have no glue what have changed in 4.5.

**Comment by leofeyer** [comment]
There haven't been any changes in the `Environment` class between Contao 4.4 and 4.5:

https://github.com/contao/core-bundle/commits/master/src/Resources/contao/library/Contao/Environment.php

**Comment by dmolineus** [comment]
Yes, I know. That's why a say I have no glue. As it's based on the symfony request, maybe something has changed in symfony or the corresponding listeners.

**Comment by fritzmg** [comment]
@dmolineus see https://github.com/netzmacht/contao-icon-wizard/pull/12 ;)

**Comment by dmolineus** [comment]
Thanks @fritzmg for pointing that typo out.
