### ISSUE TITLE
Missing custom CSS classes for backend navigation items

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1357]
Since Contao 4.5 the backend menu items lack the custom CSS classes functionality. It was present in 4.4 but is no longer in the new Twig template implementation.

Contao 4.4: https://github.com/contao/core-bundle/blob/4.4/src/Resources/contao/templates/backend/be_main.html5#L64
Contao 4.5: https://github.com/contao/core-bundle/blob/4.5/src/Resources/views/Backend/be_menu.html.twig#L7

Some extensions rely on this, e.g. easy_themes that is adding a custom CSS class via `getUserNavigation` hook:
https://github.com/terminal42/contao-easy_themes/blob/master/EasyThemes.php#L278

Issue originated from https://github.com/terminal42/contao-easy_themes/issues/38

**Comment by leofeyer** [comment]
Fixed in b5fc53d05ccf056c6b007ba99f7495e494dbe27e.
