### ISSUE TITLE
wrong default language for meta data when using `lang-COUNTRY` variant of ISO-639-1

### ISSUE THREAD

**Issue by mvscheidt** [contao/core-bundle#1358]
Related Issue: #1112

There is an additional problem with this which appears if you also enter a country in the website root language field

Reproduction Steps (Contao Version 4.4.8):

1. Create a website root for the language `de-DE`
2. Create a website root for the language `it-CH`
3. Create a website root for the language `da-DK`
4. Set the back end language for your back end user to `Italian - Italiano`.
5. Upload a file and edit its meta info.

The preselected Language will be `Danese (Danimarca) - Dansk (Danmark)` instead of `Italian (Switzerland) - Italiano (Svizzera)`

**If you skip step `3` everything happens to works as expected**

Probable Reason why this happens:

It seems that [array_intersect_key](https://github.com/contao/core-bundle/blob/d160150ad94fa02285d35c4228f9605add9c1f15/src/Resources/contao/widgets/MetaWizard.php#L123) uses the sort-order of the [SOURCE array](http://php.net/manual/en/function.array-intersect-key.php#104950) - in contaos case `$languages`.

`$languages` is based on the return value of [$this->getLanguages()](https://github.com/contao/core-bundle/blob/d160150ad94fa02285d35c4228f9605add9c1f15/src/Resources/contao/widgets/MetaWizard.php#L107)

The sorting order of the `$this->getLanguages()` seems to change when you switch your the Backend Language, that's why it seems to work in some instances (in this example if you skip step `3`) and not in others.

I conclude therefore that the Bug always happens if you have the language defined as `lang-COUNTRY` in a website root, but can be hidden by chance depending on the configured root pages and the sort order which is being returned by `$this->getLanguages()`.

----

One solution that came to my mind (for use in MetaWizard):

* Splitting the configured website root language by `-`
* Search for the users language and Return all matches
  * Returning all matches Important because we can have `it-CH` and `it-IT` for example
* Maybe sort the results alphabetically (by country, so you get `CH` first and `IT` second), or by the sorting order of the Backend Website Roots - I'm not sure what would make more sense here.

**Comment by leofeyer** [comment]
Fixed in 94181f7ca21361576c5511f461d18957cf5c28cf.
