### ISSUE TITLE
Redirect and forward pages should have robots selectbox

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#1359]
When setting a regular page to robots = nofollow, the page link in navigation modules is displayed as
`<a ... ref="nofollow">`
When switching this page to 'forward' (or 'redirect') the link stays nofollow but cannot be altered in the backend (only by switching back to 'regular').

Solution:
Add 'robots' to palettes 'forward' and 'redirect' in tl_page.php:
```
'forward'                     => '{title_legend},title,alias,type;{meta_legend},pageTitle,**robots**;...
'redirect'                    => '{title_legend},title,alias,type;{meta_legend},pageTitle,**robots**;...

```

**Comment by leofeyer** [comment]
Fixed in b701ee5440b0882b95dd2323ea402b48f6ac3ebd.
