### ISSUE TITLE
Adjust UPGRADE.md

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#136]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/58) by @Toflar
Tuesday Mar 03, 2015 at 11:39 GMT

* [x] The `disableAlias` feature as been dropped completely.
* [x] The `rewriteUrl` option has been dropped completely. The system handles this automatically now.
* [x] The following entry points do not exist anymore and you thus have to adjust your code:
    * `contao/changelog.php` --> Use the route `contao_backend_changelog` now.
    * `contao/confirm.php` --> Use the route `contao_backend_confirm` now.
    * `contao/file.php` --> Use the route `contao_backend_file` now.
    * `contao/help.php` --> Use the route `contao_backend_help` now.
    * `contao/index.php` --> Use the route `contao_backend_login` now.
    * `contao/install.php` --> Use the route `contao_backend_install` now.
    * `contao/main.php` --> Use the route `contao_backend` now.
    * `contao/page.php` --> Use the route `contao_backend_page` now.
    * `contao/password.php` --> Use the route `contao_backend_password` now.
    * `contao/popup.php` --> Use the route `contao_backend_popup` now.
    * `contao/preview.php` --> Use the route `contao_backend_preview` now.
    * `contao/switch.php` --> Use the route `contao_backend_switch` now.
* [x] The `ModuleLoader` should not be used anymore. If you want to know what modules/bundles are installed, use

    ```php
    <?php
    global $kernel;
    $bundles = $kernel->getContainer()->get('kernel.bundles');
    ```
* [x] Changing configuration parameters at runtime is wrong. You should therefore not use `Config::set()` anymore. E.g. `Config::set('debugMode', true);` will have no effect anymore as the container key `kernel.debug` is now used.

* [x] `$_SESSION['TL_USER_LOGGED_IN']` has been removed.
* [x] TL_ROOT, TL_SCRIPT etc. nicht mehr nutzen.
* [x] Kein `TL_SCRIPT == 'contao/install.php'` mehr.
* [x] The MySQL requirement has been raised to v5.5.3+ (see #35)
* [x] Methode `Frontend::parseMetaFile()` entfernt (war bereits in Contao 3 deprecated)
* [x] Additionally, the `tinymce.css` and `tiny_templates` have been removed from files.
* [x] The `tinymce.php` is no longer located in `system/config` and therefore can't be customized anymore.
* [x] `$this` in all config files (config.php/DCA/language) will be deprecated and potentially removed in Contao 5.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Monday Mar 09, 2015 at 12:53 GMT

The `pathconfig.php` file can/should be removed too as we no longer need it (see https://github.com/contao/core-bundle/commit/3b738762a0bda0c8d2774faa3167a1c8ed2661b4)

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Monday Mar 09, 2015 at 17:11 GMT

The MySQL requirement has been raised to v5.5.3+ (see https://github.com/contao/contao/issues/35)

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Mar 18, 2015 at 16:48 GMT

tinyMCE and ace configuration is now a template instead of a file

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Mar 18, 2015 at 16:51 GMT

Additionally, the `tinymce.css` and `tiny_templates` have been removed from files.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Wednesday Mar 18, 2015 at 16:58 GMT

The `tinymce.php` is no longer located in `system/config` and therefore can't be customized anymore.

**Comment by aschempp** [comment]
We should tell people that `$this` in all config files (config.php/DCA/language) will be deprecated and potentially removed in Contao 5.

**Comment by leofeyer** [comment]
I have adjusted and enhanced the documentation in 7fb1ae9cbb91403966852e1260d29162827ed8ba. There is still a `FIXME` in the `DEPRECATED.md` file, maybe one of you guys will take care of it?

**Comment by Toflar** [comment]
I will.

**Comment by leofeyer** [comment]
Thanks.

**Comment by Toflar** [comment]
Here you go. I also found a bug in the existing description :) https://github.com/contao/core-bundle/pull/177/files

**Comment by leofeyer** [comment]
Excellent :)
