### ISSUE TITLE
Problem with ESI elements in HTML attributes

### ISSUE THREAD

**Issue by vstuber** [contao/core-bundle#1360]
In the form_wrapper template the request token is used with the {{request_token}} insert tag
`<input type="hidden" name="REQUEST_TOKEN" value="{{request_token}}">`

In the HTML output rendered by contao this results in something like this:
`<input type="hidden" name="REQUEST_TOKEN" value="<esi:include src="/_fragment?_path=insertTag%3D%257B%257Brequest_token..._hash=TmgF9tDv%2BjN%2BRO0NN4m%2FvnylwKZJfHbzrzPP3SuRzC4%3D" onerror="continue" />">`

I'm no expert with ESI, in fact I know very little about it, but it seems to me like putting an ESI element inside an HTML attribute might be invalid. At least DOMDocument doesn't seem to like the ESI construct above and to me that's a huge problem because I'm using a contao extension which leverages DOMDocument to process the contao html output in the contao hook "modifyFrontendPage".

In the example mentioned above this could be fixed using `<?php echo REQUEST_TOKEN; ?>` instead of `{{request_token}}`, especially since using ESI with the request token might not even be a good idea. Therefore, this is a change that I would recommend.

But maybe there are other cases where contao creates ESI elements inside HTML attributes and if that's in fact invalid, I think contao should make sure that this doesn't happen.

**Comment by Toflar** [comment]
No, no. It's correct that this is an ESI fragment. It allows you to cache the whole page while having other parts of the page being cached separately. But during output, the `<esi>` tag should get replaced with the correct value. Are you using the managed edition?

**Comment by fritzmg** [comment]
@Toflar what about a `modifyFrontendPage` hook? Won't the `$strBuffer` contain 
```html
<input type="hidden" name="REQUEST_TOKEN" value="<esi:include src="/_fragment?_path=insertTag%3D%257B%257Brequest_token..._hash=TmgF9tDv%2BjN%2BRO0NN4m%2FvnylwKZJfHbzrzPP3SuRzC4%3D" onerror="continue" />">
```
then?

**Comment by Toflar** [comment]
It does, yes.

**Comment by fritzmg** [comment]
May be that's his use case. If you parse the output buffer in order to modify the DOM, it might fail because of the <esi> tags.

**Comment by Toflar** [comment]
Yeah, we might have `<esi` all over the DOM. It is resolved at the very, very end of every request by `AppCache` (or in case you have a real proxy, by the reverse proxy).

**Comment by vstuber** [comment]
I'm using the managed edition and yes, parsing the output buffer (with DOMDocument) in order to modify the DOM is exactly my use case. And it works great unless there's a weird construct with an `<esi>` element inside an HTML attribute. In this case DOMDocument can't handle it and therefore the whole parsing and modifying stuff that I need fails.

The question to me is whether or not it is even correct to put an ESI element inside an HTML attribute. If we consider the whole HTML document combined with the ESI elements to be some kind of XML and if therefore the XML rules apply, then putting an element inside another element's attribute is probably invalid and should be avoided.

If this would be fixed in an upcoming contao version then I could leave my DOM parsing extension as it is because it would soon play nicely with contao again. But if contao keeps these ESI attribute combinations I would have to find a workaround in my extension and that would probably mean stripping all ESI elements before parsing the output buffer and then re-inserting them after the DOM modification. This would probably result in using a lot of regex and would therefore be very ugly considering the regex performance.

Is there a way for a contao webmaster to deactivate the whole ESI thing in a contao project?

**Comment by Toflar** [comment]
It's not something we need to fix. It is intentional. You can punch holes in the HTML wherever you want to. Also, it does not make sense to deactivate it. It's there because we want to be able to cache the website and still have the request token and other insert tags (and whatever else you can imagine) to remain uncached. Deactivating it would mean introducing bugs.

The only thing you can do is apply a regex.

> This would probably result in using a lot of regex and would therefore be very ugly considering the regex performance.

It is one regular expression that is probably as simple as something like `/(<esi:include[^>]*>)/g` and you are already parsing the **whole** DOM so I don't see why that would change anything :-)

**Comment by vstuber** [comment]
Removing all the ESI elements would not be a problem, no question there. But capturing them all and re-inserting them in all the right places after the DOM manipulation is something completely different and performance-wise definitely not something to treat lightly.

By the way, parsing the whole DOM is not such a big deal using `DOMDocument` because it is pretty fast. Parsing the DOM two more times - firstly to get rid of all ESI elements and secondly to re-insert them - might be a problem, though.

Since the caching mechanism of Contao 3.5 did not use ESI and most contao projects probably worked fine without it, I hoped that deactivating it would not be such a problem. Of course, I don't want my extension to rely on the webmaster deactivating a contao feature, so I will have to figure something out.

**Comment by Toflar** [comment]
Just replace all occurences of esi tags with some random generated string, apply your DOM manipulations and replace back:

```php
// Save ESI tags and replace with some random string
$esiTags = [];
$html = preg_replace_callback('/(<esi:include[^>]*>)/', function($matches) use (&$esiTags) {
    foreach ($matches as $match) {
        $placeholder = '---esi-placeholder---' . uniqid('', true);
        $esiTags[$placeholder] = $match;
    }
    return $placeholder;
}, $html);

// Do your DOM manipulation

// Replace back
$html = str_replace(array_keys($esiTags), array_values($esiTags), $html);
```

**Comment by vstuber** [comment]
Seems like I don't have to figure something out after all, because you just did ;-) Very nice, thanks a lot! I'm excited to see the performance impact of that approach. Since re-inserting the ESI elements doesn't use regular expressions (I haven't thought of that in my previous post) it's probably not as bad as I worried.

**Comment by Toflar** [comment]
It's not the first time that I did something like this, so I thought I'd share ;-)

**Comment by akroii** [comment]
I'am getting the same error in productional if I force the 404 page.
I only get it on reader page of [catalog-manager ](https://github.com/alnv/catalog-manager)

```
<body id="top" class="<esi:include src="/_fragment?_path=insertTag%3D%257B%257Bua%253A%253Aclass%257D%257D%26_format%3Dhtml%26_locale%3Dde%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&pageId=65&request=unternehmen%2Fjobs%2Flesen%2Fkfz-mechatroniker-m-wdsf&_hash=XrFgG45%2FyQj0VcphbISoImQHIijvB9QC6bJF4QmHR4g%3D" onerror="continue" /> sub desktop" itemscope itemtype="http://schema.org/WebPage">
```
