### ISSUE TITLE
Bild-Titel: Anführungszeichen brechen Text ab.

### ISSUE THREAD

**Issue by derastronaut** [contao/core-bundle#1363]
In Contao 4.4.13 und in der Demo (4.5.3) werden in einem Bild-Titel solche Eingaben, die ein Anführungszeichen " enthalten, ab diesem Punkt abgeschnitten.

**Beispiel:** Von Wurst bekomme ich "Durst", deshalb esse ich nur Käsekuchen.

Während der Satz im BE-Eingabefeld komplett bleibt, wird im FE nur _**Von Wurst bekomme ich**_ angezeigt.

Den Fehler konnte ich im **Text-** und **Bild-Element** feststellen. Natürlich muss "Metadaten überschreiben" aktiviert werden, um den Bild-Titel auszufüllen. Alternativ-Text und Bild-Unterschrift sind nicht betroffen.

**Comment by Aybee** [comment]
Kann ich nicht bestätigen. Gerade in der Online-Demo 4.5.3 getestet.

**Comment by derastronaut** [comment]
Wie ich gerade herausgefunden habe, muss bei "Großansicht/Neues Fenster" ein Haken gesetzt werden.

![contao-quote-error-01](https://user-images.githubusercontent.com/5235594/36066926-75a8e8de-0eb3-11e8-998e-7a73327417d7.png)
![contao-quote-error-02](https://user-images.githubusercontent.com/5235594/36066927-75c31fba-0eb3-11e8-8933-a5e49e0075d4.png)

**Comment by Aybee** [comment]
Ah, ok, ich dachte zwar, das hätte ich auch getestet, war wohl nix.

Dann fehlt unter dieser Zeile hier
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Controller.php#L1684
noch diese Zeile
```php
$objTemplate->linkTitle = \StringUtil::specialchars($objTemplate->linkTitle);
```

**Comment by leofeyer** [comment]
Behoben in 98d13da38e0f709550a5fe83fc80ce50317f42c2.
