### ISSUE TITLE
Contao 4.5 Bekomme Warnung

### ISSUE THREAD

**Issue by benyi001** [contao/core-bundle#1365]
wenn ich bei http://contao4.5.wagyu-genetics.de/ im BE auf Systemwartung gehe, bekomme ich diese Meldung
Warning: A non-numeric value encountered in /var/www/web25923927/html/wagyu-genetics4.5/vendor/contao/core-bundle/src/Resources/contao/classes/StyleSheets.php on line 996

Wenn ich bei Skriptcache leeren den Haken raus nehme geht alles. Ich habe die StyleSheets.php mit einer anderen Installation verglichen, in der Zeile 996 steht alles identisch drin, also kein Fehler der mir auffalen würde.
Was kann das sein, und wie schaffe ich Abhilfe? 

Ich habe nun die zweite Installation von Contao 4.5.4 mit dem gleichen Fehler/Warnung.

**Comment by fritzmg** [comment]
Why did you close the ticket?

I guess
```php
($color[1] / 100)
```
needs to be changed to
```php
((int) $color[1] / 100)
```

**Comment by leofeyer** [comment]
Was für einen Wert hat `$color[1]` denn in diesem Fall?

**Comment by benyi001** [comment]
Die Werte: return 'rgba(' . implode(',', $this->convertHexColor($color[0], $blnWriteToFile, $vars)) . ','. ($color[1] / 100) .')';

 

Gruß Norbert

 

Von: Leo Feyer [mailto:notifications@github.com] 
Gesendet: Dienstag, 13. Februar 2018 18:03
An: contao/core-bundle
Cc: benyi001; State change
Betreff: Re: [contao/core-bundle] Contao 4.5 Bekomme Warnung (#1365)

 

Was für einen Wert hat $color[1] denn in diesem Fall?

**Comment by leofeyer** [comment]
Du müsstest bitte ein `var_dump($color[1])` in den Code schreiben und dann dessen Ausgabe hier posten.
