### ISSUE TITLE
Cannot install contao 4.5 alone

### ISSUE THREAD

**Issue by baumannsven** [contao/core-bundle#1366]
`
    - contao/core-bundle 4.5.0 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.1 requires terminal42/header-replay-bundle ^1.3 -> satisfiable by terminal42/header-replay-bundle[1.3.0, 1.4.0, 1.4.1].
    - contao/core-bundle 4.5.2 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - contao/core-bundle 4.5.3 requires terminal42/header-replay-bundle ^1.4 -> satisfiable by terminal42/header-replay-bundle[1.4.0, 1.4.1].
    - terminal42/header-replay-bundle 1.3.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2].
    - terminal42/header-replay-bundle 1.4.0 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2].
    - terminal42/header-replay-bundle 1.4.1 requires friendsofsymfony/http-cache 2.* -> satisfiable by friendsofsymfony/http-cache[2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2].
    - friendsofsymfony/http-cache 2.1.2 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.1.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.1.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.2 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.1 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - friendsofsymfony/http-cache 2.0.0 requires php-http/client-implementation ^1.0.0 -> no matching package found.
    - Installation request for contao/core-bundle ^4.5 -> satisfiable by contao/core-bundle[4.5.0, 4.5.1, 4.5.2, 4.5.3].
`

**Comment by baumannsven** [comment]
In the requirements must set the package `php-http/guzzle6-adapter`.

**Comment by Toflar** [comment]
You have to do that on your own, so everyting is correct here.

**Comment by bytehead** [comment]
It should be at least mentioned in the `README.md` to require an explicit `php-http/client-implementation` like `php-http/guzzle6-adapter`.
