### ISSUE TITLE
Fehler bei Update einer 4.4.13 Installation - lexik_maintenance.listener

### ISSUE THREAD

**Issue by planepix** [contao/core-bundle#1369]
Hallo zusammen,

beim Aufruf des Contao Managers und der Aktualisierung erhalte ich folgende Fehlerausgabe (im Konsolenfenster der Managers wie auch direkt in der Konsole):

```
In ParameterBag.php line 102:

  The service "lexik_maintenance.listener" has a dependency on a non-existent
   parameter "lexik_maintenance.response.exception_message". Did you mean one
   of these: "lexik_maintenance.response.http_code", "lexik_maintenance.respo
  nse.http_status"?

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command:
  In ParameterBag.php line 102:

    The service "lexik_maintenance.listener" has a dependency on a non-existent
     parameter "lexik_maintenance.response.exception_message". Did you mean one
     of these: "lexik_maintenance.response.http_code", "lexik_maintenance.respo
    nse.http_status"?
```

Hoster: allinkl
PHP 7.1 / auch unter 7.2 getestet

**Fehleranzeige im Frontend:**
`Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "lexik_maintenance.listener" has a dependency on a non-existent parameter "lexik_maintenance.response.exception_message". Did you mean one of these: "lexik_maintenance.response.http_code", "lexik_maintenance.response.http_status"? in /www/htdocs/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:102 Stack trace: #0 /www/htdocs/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(57): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('lexik_maintenan...') #1 /www/htdocs/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php(219): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('lexik_maintenan...') #2 /www/htdocs/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyIn in /www/htdocs/xxx/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 102`

**Inhalt der composer.json:**
{
```
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "ausi/contao-slug-backport": "^1.0",
        "bugbuster/contao-botdetection-bundle": "^0.2.1",
        "bugbuster/contao-dlstats-bundle": "^1.0",
        "bugbuster/contao-visitors-bundle": "^0.2.0",
        "christianbarkowsky/tabcontrol": "^3.0",
        "codefog/contao-mobile_menu": "^2.6",
        "codefog/contao-news_categories": "^2.8",
        "contao/calendar-bundle": "4.4.*",
        "contao/comments-bundle": "4.4.*",
        "contao/faq-bundle": "4.4.*",
        "contao/listing-bundle": "4.4.*",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "4.4.*",
        "contao/newsletter-bundle": "4.4.*",
        "derhaeuptling/contao-seo-serp-preview": "^3.0",
        "do-while/contao-backupdb-bundle": "^1.2",
        "fritzmg/contao-sharebuttons": "^1.3",
        "fritzmg/contao-youtube-iframe": "2.2.2",
        "madeyourday/contao-rocksolid-columns": "^2.0",
        "madeyourday/contao-rocksolid-slider": "^2.0",
        "netzmacht/contao-font-awesome": "^4.7",
        "numero2/contao-opengraph3": "^4.0",
        "numero2/contao-tinypng": "^4.0",
        "terminal42/contao-ce-access": "^2.0",
        "terminal42/contao-conditionalselectmenu": "^3.0",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-leads": "^1.4",
        "terminal42/notification_center": "^1.4"
    },
    "config": {
        "component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
```

**Comment by planepix** [comment]
Auch in einer weiteren Installation erhalte ich nun zunächst die 4.4.14; im Anschluss wird der gleiche Fehler ausgegeben und die Website lässt sich im Frontend nicht mehr erreichen.

**Comment by x-christian-romeni** [comment]
Ja, das ist korrekt, den fehler habe ich auch:

`In ParameterBag.php line 102:

  The service "lexik_maintenance.listener" has a dependency on a non-existent
   parameter "lexik_maintenance.response.exception_message". Did you mean one
   of these: "lexik_maintenance.response.http_code", "lexik_maintenance.respo
  nse.http_status"?


Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command:
  In ParameterBag.php line 102:

    The service "lexik_maintenance.listener" has a dependency on a non-existent
     parameter "lexik_maintenance.response.exception_message". Did you mean one
     of these: "lexik_maintenance.response.http_code", "lexik_maintenance.respo
    nse.http_status"?`

**Comment by leofeyer** [comment]
Leider hat Lexik das Bundle in der neuesten Version kaputt gemacht:

https://github.com/lexik/LexikMaintenanceBundle/pull/84

Ich habe im Core-Bundle [einen Konflikt hinzugefügt](https://github.com/contao/core-bundle/commit/1d9cb402697f13bec46119d2f0e0f9bc08b12f00), damit die Version nicht installiert wird.

**Comment by leofeyer** [comment]
Inzwischen wurde auch schon die Version 2.1.5 des Bundles veröffentlicht, so dass das Problem auf jeden Fall nicht mehr auftreten sollte.
