### ISSUE TITLE
Contao 4.4.13 mootools not load over CDN only local

### ISSUE THREAD

**Issue by Zwergenmeister** [contao/core-bundle#1371]
Mootools script not available on this site, when CDN is on only local fallback used. 

https://ajax.googleapis.com/ajax/libs/mootools/1.6.0.5/mootools.min.js

This works, there is no version 1.6.0.5 out 

https://ajax.googleapis.com/ajax/libs/mootools/1.6.0/mootools.min.js

Thx

**Comment by leofeyer** [comment]
If you set the script source to "local only", it should not be loaded from ajax.googleapis.com. How do I reproduce the issue in the [online demo](https://demo.contao.org/contao)?

**Comment by Zwergenmeister** [comment]
Only local works fine. 

Problem only with CDN or CDN - Fallback, have checked in contao online demo actived  mootools in the theme - page layout set to CDN and check the link in header and the network protocol in chrome or ff

1.12.4 is in the demo used not working

https://ajax.googleapis.com/ajax/libs/mootools/1.12.4/mootools.min.js 

change link to 1.5.2 and 1.6.0 works

https://developers.google.com/speed/libraries/#mootools

> note:
For versions 1.5.1 and earlier, the filename of the minified version is called mootools-yui-compressed.js instead of  mintools.min.js.

THX

**Comment by leofeyer** [comment]
See #1391.
