### ISSUE TITLE
PageNotFoundException overrides RedirectResponseException

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1373]
### Reproduction:

1. Create an `initializeSystemHook` where you simply execute `\Controller::redirect('https://www.google.at')`.
2. Open the front end with an URL that does not exist within the Contao installation.

The redirect will not be executed. Instead the 404 page will be shown.

This only happens, when the `terminal42/header-replay-bundle` in version `1.4.2` is installed. It does not happen with version `~1.3.0,<=1.4.1` of `terminal42/header-replay-bundle`.

/cc @Toflar 

### Background:

My (Contao 3 and 4 compatible) [contao-short-urls](https://github.com/fritzmg/contao-short-urls) extension relies on the `initializeSystemHook` of Contao to analyze the request path and then create a redirect there. However, `terminal42/header-replay-bundle` in version `1.4.2` broke that functionality somehow.

**Comment by Toflar** [comment]
Hmm, do you have a `composer.json` and `composer.lock` with which I can quickly reproduce?

**Comment by fritzmg** [comment]
Hang on, still have to test something, I think it happens since `1.4.x` in general may be, not just since `1.4.2`.

**Comment by Toflar** [comment]
That would make sense, yes. Pre 1.4 used to send the response if it was not a 200 but we figured that's incorrect. However, I'm not sure about redirect responses. But definitely that's not a Contao issue, you should open that issue here: https://github.com/terminal42/header-replay-bundle/issues

**Comment by fritzmg** [comment]
kk, see https://github.com/terminal42/header-replay-bundle/issues/13
