### ISSUE TITLE
Contao 4.5: CSS bug in BE theme flexible

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#1377]
Using several multiple input elements in BE with class "w50" is not possible:

```
$GLOBALS['TL_DCA']['tl_news']['fields']['whatever'] = array(
        'inputType'     => 'checkbox',
        'options'       => [lot of options],
        'eval'          => array('multiple'=>true, 'tl_class' => 'w50'),
[...]
);
```

Solution:
Change basic.css from
`.w50{width:calc(50% - 30px);float:left;height:80px}`
to
`.w50{width:calc(50% - 30px);float:left;min-height:80px}`

**Comment by Aybee** [comment]
There are other tickets regarding this issue. With different heights on those floated element you would have no consistent rows. It may happen that one widget appears right while the space aside left stays empty then.

**Comment by pgerundt** [comment]
I see. How about some additional css3 clearfix magic:
```
div.widget.w50 + div.widget.w50::after {
  clear:both;
  content: '';
  display: table;
}
```

I know this affects all `div.w50n` (even the first one in a row if you have more than two), but it keeps the rows consistent.

**Comment by Aybee** [comment]
See this ticket #1287
