### ISSUE TITLE
email, email_url Inserttags are not encrypted

### ISSUE THREAD

**Issue by timgatzky** [contao/core-bundle#1378]
Hi guys,
clients reported to us and I could reproduce the issue that the {{email...}} and {{email_url...}} inserttags do not encode the email address anymore.
It's in latest 3.5 and latest 4.4. Can you confirm this.

Thanks in advance, Tim

**Comment by fritzmg** [comment]
I cannot confirm this. HTML output on demo.contao.org for `{{email::example@example.org}}`:
```html
<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#101;&#x78;&#x61;&#109;&#x70;&#x6C;&#101;&#64;&#x65;&#120;&#x61;&#x6D;&#112;&#x6C;&#x65;&#x2E;&#x6F;&#114;&#x67;" class="email">&#101;&#x78;&#x61;&#109;&#x70;&#x6C;&#101;&#64;&#x65;&#120;&#x61;&#x6D;&#112;&#x6C;&#x65;&#x2E;&#x6F;&#114;&#x67;</a>
```
HTML output in a local Contao 4.5.4 installation:
```html
<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#101;&#120;&#x61;&#x6D;&#112;&#108;&#101;&#x40;&#x65;&#x78;&#97;&#x6D;&#x70;&#x6C;&#101;&#46;&#x6F;&#114;&#103;" class="email">&#101;&#120;&#x61;&#x6D;&#112;&#108;&#101;&#x40;&#x65;&#x78;&#97;&#x6D;&#x70;&#x6C;&#101;&#46;&#x6F;&#114;&#103;</a>
```
HTML output in a local Contao 4.4.14 installation:
```html
<a href="&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#x65;&#x78;&#97;&#109;&#x70;&#108;&#101;&#x40;&#x65;&#x78;&#97;&#109;&#112;&#x6C;&#x65;&#46;&#111;&#114;&#x67;" class="email">&#x65;&#x78;&#97;&#109;&#x70;&#108;&#101;&#x40;&#x65;&#x78;&#97;&#109;&#112;&#x6C;&#x65;&#46;&#111;&#114;&#x67;</a>
```

**Comment by timgatzky** [comment]
Thanks man. Issue can be closed. Observing the urls with Chrome console, will show the addresses readable. Observing the whole source code shows the correct encryted version. 
I did not know that! sorry for that.
