### ISSUE TITLE
C4.5: contao.security.token_checker Problem

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#1385]
Ich nutze Insert-Tags die nicht ersetzt im Cache landen.
Genauer gesagt mehrere auf der selben Seite, die von derselben Klasse (erbt von Frontend) und Methode ersetzt werden.

Ich bin im Backend angemeldet und im zweiten Tab rufe ich die FE Seite auf mit den Tags darin.
Gleich am Anfang der Methode prüfe ich wie folgt, ob ein Backend Nutzer angemeldet ist:
```
$objTokenChecker = \System::getContainer()->get('contao.security.token_checker');
if ($objTokenChecker->hasBackendUser())
{ //angemeldet } else { //nicht angemeldet }
```
(identisch Frontend.getLoginStatus nur ohne die Preview Unterscheidung)

Wird der erste Insert-Tag ersetzt, ergibt obiges "true". Wird nun gleich darauf der zweite Insert-Tag ersetzt, ergibt obiges plötzlich "false".

Teste ich das ganze über app_dev.php, ergibt es in beiden Fällen "true".

Muss ich noch was dabei beachten oder ist das ein Bug?

**Comment by leofeyer** [comment]
@contao/developers Hattet ihr das Problem schon mal?

**Comment by aschempp** [comment]
are you developing your own insert tag listeners? Or do you mean an existing core insert tag?

**Comment by BugBuster1701** [comment]
Meine eigenen, noch direkt über Klasse / Methode, nicht über eigenen eventlistener.

**Comment by aschempp** [comment]
Interessant. Ist dein Cache als `uncacheable` markiert?

Nebenfrage: Warum verwendest du keine Event Listener etc. wenn du sowieso Symfony services nutzt? 😆

**Comment by BugBuster1701** [comment]
Die Tags sind noch so wie zu Urzeiten gebaut: `{{cache_tagname::count}}`

Symfony Services nutze ich derzeit nur dann, wenn ich sehe das bestimmte bisherigen Methoden als "deprecated" markiert sind. Wenn ich damit durch bin, kommt die Nutzung von Event Listener dran. (wo sinnvoll) Bin halt noch nicht so weit. Ist in dem Fall ne alte Erweiterung die ich Stück für Stück umwandle.

**Comment by leofeyer** [comment]
Bitte denkt daran das Ticket zu schließen, wenn das Thema erledigt ist. 😄
