### ISSUE TITLE
Tasks to fix and improve caching

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1389]
As pointed out in other issues already, the caching system still needs a lot of love. We are making good progress but there are still a lot of things to do to make Contao become the CMS with the best native caching support out there. We should not forget that our requirements are very complex and it will remain an ongoing topic that will accompany us for another few versions of Contao.
This issue should serve as a central place to keep track of all the TODO's around the HTTP cache.

### Bugfixes

* [x] For Contao versions 4.4 and 4.5, we must force `public` responses even though the session was started (see #1388). @leofeyer 

* [x] The Symfony `ResponseCacheStrategy` does not differentiate between `private` responses and `no-cache` cache headers. We must provide a PR to fix that. (https://github.com/symfony/symfony/pull/26532) @aschempp 

* [x] Our `InsertTagsController` must set `max-age` (client cache) settings based on page settings for BC insert tags (see #1390). @toflar 

* [x] `FrontendTemplate::addCacheHeadersToResponse()` must be fixed because it only sets `private`. The `no-cache` stuff is missing. @leofeyer 

### Features

* [x] We must ensure, we're not starting the session if we don't need it. Starting the session implicitly means that a response is `private` and may not be cached as it may contain personal information. As long as the core still requires stuff like this, we need to force `public` responses.

   * [x] `$_SESSION['FORM_DATA']` is a real killer here because we never unset the information stored in that value. We must introduce a config option in the form settings to disable that (or enable explicitly). It should be removed in version 5.

    * [x] `hasPreviousSession()` should be added everywhere we access the session to make sure the session is not started if there's no cookie (`Input` class) (https://github.com/contao/core-bundle/pull/1471) @toflar

*  [ ] We need insert tags as fragments so every insert tag can decide for its own, how it would like to be rendered (and set the correct caching headers) (https://github.com/contao/core-bundle/pull/1470) @toflar 

*  [x] Add support for tagging responses so that we can cache stuff "forever" and invalidate using cache tags. (https://github.com/contao/manager-bundle/pull/60) @toflar

**Comment by leofeyer** [comment]
@contao/developers I need your feedback in order to fix the last open bugfix. These are the headers we used to send:

```php
if (!headers_sent())
{
	if ($intCache > 0 && (\Config::get('cacheMode') == 'both' || \Config::get('cacheMode') == 'browser'))
	{
		header('Cache-Control: private, max-age=' . ($intCache - time()));
		header('Last-Modified: ' . gmdate('D, d M Y H:i:s', time()) . ' GMT');
		header('Expires: ' . gmdate('D, d M Y H:i:s', $intCache) . ' GMT');
	}
	else
	{
		header('Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0');
		header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
		header('Expires: Fri, 06 Jun 1975 15:10:00 GMT');
	}
}
```

See https://github.com/contao/core-bundle/pull/576/files#diff-9d1eb5ea5f99817ee33995c01eced477L320

@Toflar Your initial PR only uses `setPrivate()`, `setMaxAge()` and `setSharedMaxAge()`. Which headers do you want me to add?

**Comment by Toflar** [comment]
Only these, the rest is irrelevant for what you can configure in the page settings (`Last-Modified` is less-accurate and a fallback method for working with `E-Tag` which we don't do either). And `Expires` is harder to set than `max-age` but does the same. So we only need 

* Private if client cache only (or no cache)
* max-age value for client cache
* s-max-age for server cache

**Comment by leofeyer** [comment]
Hm, I still don't know exactly what to do. 😄 This is the [current code](https://github.com/contao/core-bundle/blob/4.4/src/Resources/contao/classes/FrontendTemplate.php#L372-L400):

```php
global $objPage;

if (($objPage->cache === false || $objPage->cache === 0) && ($objPage->clientCache === false || $objPage->clientCache === 0))
{
	return $response->setPrivate();
}

// Do not cache the response if a user is logged in or the page is protected
// TODO: Add support for proxies so they can vary on member context
if (FE_USER_LOGGED_IN === true || BE_USER_LOGGED_IN === true || $objPage->protected || $this->hasAuthenticatedBackendUser())
{
	return $response->setPrivate();
}

if ($objPage->clientCache > 0)
{
	$response->setMaxAge($objPage->clientCache);
}

if ($objPage->cache > 0)
{
	$response->setSharedMaxAge($objPage->cache);
}

return $response;
```

The third and fourth `if` conditions are clear. Do I apply `no-cache, no-store` in both the first and second `if` condition? And what is the difference between `$objPage->cache === false` and `$objPage->cache === 0`?

**Comment by Toflar** [comment]
> And what is the difference between $objPage->cache === false and $objPage->cache === 0?

None.

> Do I apply no-cache, no-store in both the first and second if condition?

Jop.

**Comment by leofeyer** [comment]
![giphy](https://user-images.githubusercontent.com/1192057/36850040-f693d66e-1d65-11e8-94d7-ef3208da4906.gif)

**Comment by leofeyer** [comment]
So then it is

```php
global $objPage;

if (($objPage->cache === false || $objPage->cache === 0) && ($objPage->clientCache === false || $objPage->clientCache === 0))
{
	$response->headers->addCacheControlDirective('no-cache');
	$response->headers->addCacheControlDirective('no-store');

	return $response->setPrivate();
}

// Do not cache the response if a user is logged in or the page is protected
// TODO: Add support for proxies so they can vary on member context
if (FE_USER_LOGGED_IN === true || BE_USER_LOGGED_IN === true || $objPage->protected || $this->hasAuthenticatedBackendUser())
{
	$response->headers->addCacheControlDirective('no-cache');
	$response->headers->addCacheControlDirective('no-store');

	return $response->setPrivate();
}
```

?

**Comment by aschempp** [comment]
Well `private` does not make sense if it is `no-cache`, right?

**Comment by Toflar** [comment]
It does. It should always be there, no matter the cache directive. They are semantically different and to not provide an answer to the same question.

**Comment by Toflar** [comment]
I've created two more PR's. That list is now reduced two one open item (the checkbox in the form settings). @leofeyer are you going to take over that one?

**Comment by leofeyer** [comment]
Yes.

**Comment by leofeyer** [comment]
@Toflar How does a form setting solve our problem again?

First we would have to add a third argument `$blnNoSession` to all `Input::post*()` methods. Then we would have to set this argument to `true` in the `Form` class.

1. What about the `Widget::getPost()` method?
2. What if someone uses the `Input` class without the `Form` class?

**Comment by aschempp** [comment]
I don't think that's the case. We just don't write to `$_SESSION['FORM_DATA']` when submitting a form. Everything else solves automatically because no session will be started in that case, so neither `Widget` nor `Input` will try to use these values.

**Comment by leofeyer** [comment]
But `Input::findPost()` will still execute `isset($_SESSION['FORM_DATA'][$strKey])` which will start the session, won't it?

**Comment by aschempp** [comment]
Not with https://github.com/contao/core-bundle/pull/1471

**Comment by Toflar** [comment]
> What about the Widget::getPost() method?

I guess this is the reason why this session stuff was introduced back 10 years ago. If you submitted the form with errors, I guess thanks to the session the form was not cleared and the values were propagated again so you could only fix what was wrong: I'm not sure at all though but I think it should not rely on the session either. Nowadays we should leverage browser capabilities to do so (if they do not automatically already, otherwise use localstorage or whatever).

> What if someone uses the Input class without the Form class?

Then the session is getting started if the cookie is there. We cannot prevent that because of BC reasons. I'd really love to drop it completely but we can't.

**Comment by aschempp** [comment]
A submitted form is a POST request, there is no need to keep the session data to reload the value. There is only a reload after successful submit.

**Comment by Toflar** [comment]
I think that used to be different in earlier versions. That's maybe why.

**Comment by leofeyer** [comment]
Since the last open issue (insert tags as fragments) is up for discussion again (see contao/contao#555), I think we can eventually close this ticket.
