### ISSUE TITLE
Extrem langsames Backend

### ISSUE THREAD

**Issue by Benjaminscherf** [contao/core-bundle#1395]
Entschuldigung. Der Eintrag kann gelöscht werden. Ich konnte das Problem lösen.

**Comment by netzarbeiter** [comment]
Du könntest das Problem und den Weg zur Lösung hier reinschreiben und danach das Ticket schliessen. Sollte jemand anderes ein langsames Backend haben, könnte dein Lösungsansatz hilfreich sein.

**Comment by Benjaminscherf** [comment]
Was genau das Problem war, war für mich nicht zu identifizieren mit der Ausnahme, dass es an einer Extension gelegen haben muß. Da ich auf dem 1und1 Server das Problem mit fehlenden Arbeitsspeicher habe ("Process terminated with exit code 255") und so keine Automatischen Updates mit dem Contao Manager machen kann musste ich die Updates der Extensions manuell durchführen. Dies habe ich alles gleichzeitig gemacht und nach Aktualisierung der Datenbank war das Problem gelöst.

**Comment by fritzmg** [comment]
@Benjaminscherf du solltest das nicht manuell machen. Aktualisiere die Contao Installation lokal, kopiere dann die `composer.lock` (und ggf. `composer.json`) auf den Server und führe per SSH auf dem Server ein `composer install` aus. Wichtig ist, dass du für das lokale composer update die selbe PHP Version verwendest, wie diejenige die im 1&1 Web Server eingestellt ist.

**Comment by aschempp** [comment]
> führe per SSH auf dem Server ein composer install aus

das lässt sich übrigens im neusten Manager auch über das GUI machen 😉
