### ISSUE TITLE
Contao 4.5 - DC_Table 

### ISSUE THREAD

**Issue by katgirl** [contao/core-bundle#1396]
New Installation without Sites or Startpage:

`Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: count(): Parameter must be an array or an object that implements Countable" at /home/kirsten/html/kirsten-roschanski.de/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php line 3548`

**Comment by xchs** [comment]
See https://github.com/contao/core-bundle/issues/1353
