### ISSUE TITLE
icon.css better with pseudo elements?

### ISSUE THREAD

**Issue by bennie99** [contao/core-bundle#1397]
Wouldn’t it better to use pseudo elements in the icon.css (:: before in this case)?
You can see what happened  if you just  add a padding to the li tag can be seen in the demo https://demo.contao.org/en/file-elements.html

Because icons are included as a background image in the css-class, the text is above it - here because there is a higher specifity for padding.
It wouldn't have happened with pseudo-elements

I can override that, of course, but then I have to copy the image folder into my structure below files, cause I can’t get to the image folder below assets - not tragic, but maybe it would be an idea to use the included icons.css with pseudo-elements in the future

**Comment by Aybee** [comment]
There simply isn't enought `padding-left` on the `li`.

IMHO there should not be any padding on the LIs. Background-Image and padding should go to the A-Tag. This way the click sensitive area will become more user friendly (bigger) and also the "icon" will be clickable.
