### ISSUE TITLE
Keine Logs werden erstellt wenn eine Seite nicht gefunden wurde

### ISSUE THREAD

**Issue by akroii** [contao/core-bundle#1399]
Hallo,
früher konnte ich Anhand der Log-Einträge im Backend sehen, welche Seite nicht gefunden wurden.
Diese Funktion ist in 4.4.x irgendwie verschwunden. Frühere Versionen habe ich nicht getestet.

Wenn ich in der demo.contao.org aufrufe:
`https://demo.contao.org/en/text-elements-sduifgsdf.html` <- praktisch, ein 404
werden im Backend keine (roten) Einträge erzeugt, dass ein Fehler aufgetreten ist.

![bildschirmfoto 2018-02-26 um 07 51 45](https://user-images.githubusercontent.com/8830861/36656726-ec8cdc90-1ac9-11e8-95b2-463747bd3f8a.png)

In den 404-Seiteneinstellungen wurde die automatische Umleitung zur index.html ausgeschalten.

**Comment by aschempp** [comment]
Die Information wurde absichtlich entfernt, da es zu sehr vielen unnötigen Einträgen führen kann. Die entsprechende Info kann normalerweise dem Access-Log des Webservers entnommen werden.
