### ISSUE TITLE
Uploading big files in Contao 4.5 fails

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1406]
Since Contao 4.5+is now using `"contao-components/dropzone": "^5.0.1"` it's not able to upload big files with more than 30s duration. In Contao 4.4+ the problem don't exists (which is using dropzone ^4.1.1).

The problem is that with the commit (https://github.com/contao-components/dropzone/commit/d9b749b68614f71da5fe5c50428427aa7b49789b) a timeout is now set to 30000 (ms) in the `dropzone(.min).js`. So every upload taking longer than 30s will fail.

The timeout should be set to 0 (which will disable any timeout). This have to be set explicitly (see https://github.com/enyo/dropzone/issues/1561 and https://stackoverflow.com/questions/46379917/dropzone-js-upload-with-php-failed-after-30-seconds-upload/46488162#46488162).

So the dropzone.js should be set to:
```diff
    Dropzone.prototype.defaultOptions = {
      url: null,
      method: "post",
      withCredentials: false,
-     timeout: 30000,
+     timeout: 0,
      parallelUploads: 2,
      uploadMultiple: false,
      maxFilesize: 256,
      paramName: "file",
      createImageThumbnails: true,
      maxThumbnailFilesize: 10,
      thumbnailWidth: 120,
      thumbnailHeight: 120,
      ...
      ...
```

**Comment by leofeyer** [comment]
Fixed in c1d676ca2741709f20aadc51baed4627135aa8b9.
