### ISSUE TITLE
Eventliste im Footer verhindert aufruf einer Detailseite

### ISSUE THREAD

**Issue by akroii** [contao/core-bundle#1407]
Hallo,
ich habe eine Eventliste im Footer, welche maximal 5 Stück anzeigt. Dieser Footer ist auf allen Seiten identisch.
Nun passiert es, wenn ich aus dem Hauptmenü zu den Nachrichten navigiere und eine Neuigkeit anklicke, geschieht es, dass diese nicht gefunden wird. Praktisch erscheint beim aufrufen einer Detail-Seite ein 404.
Auch wenn ich im Catalog Manager Detail-Seiten anlege, werden diese nicht mehr gefunden.
Erst wenn ich das Modul `Eventliste` aus dem Footer wegnehme, funktionieren die Detail-Seiten wieder.

Contao 4.4.14
PHP 7.1

**Comment by fritzmg** [comment]
Du hast in deinem Eventliste Modul vermultich einen Eventreader eingestellt. Entferne die Eventreader Einstellung.

**Comment by akroii** [comment]
Danke, das war es.
