### ISSUE TITLE
FrontendCron Controller never run

### ISSUE THREAD

**Issue by theDyingMountain** [contao/core-bundle#1408]
The `hasToWait `method in the `FrontendCron` Controller always returns true, so the Controller will never run. 
The lastrun value is always set to the current time before the check with the cron timeout.

Steps to reproduce:

1. Set lastrun value to 0 in the database.
2. Call frontend.
3. Debug `$objCron->value` in `FrontCron hasToWait`

**Comment by leofeyer** [comment]
I cannot reproduce this. If `$objCron->value` is `0`, the method returns `false`:

https://github.com/contao/core-bundle/blob/34056c8d62e503520f808a3745d2662d8a9a2834/src/Resources/contao/controllers/FrontendCron.php#L158-L162

**Comment by theDyingMountain** [comment]
I'm wondering that you cannot reproduce that. I don't know what can be wrong with my local environment. I set the lastrun value manually in the database. Then I'm setting breakpoints at lines 64/65 https://github.com/contao/core-bundle/blob/10efd81c1f99094af52f518f227e7a6c9db1e5a6/src/EventListener/CommandSchedulerListener.php#L64-L65 and send a request in the contao backend.
After line 65 is passend by the debugger the lastrun value in the tl_cron table is updated with the current time... Can this be a cache problem? I'm don't have any idea...

**Comment by fritzmg** [comment]
> and send a request in the contao backend.

I haven't looked at the code, but as far as I remember the cron is only executed in the front end and the login page, not in the back end.

**Comment by theDyingMountain** [comment]
@fritzmg : Yes you're right. But the same problem still exists, when i send a request in the frontend. The lastrun value is updated after `$controller->run();` is called.
