### ISSUE TITLE
unsupported_engine

### ISSUE THREAD

**Issue by iulianbeleiu** [contao/core-bundle#1410]
Hi, i don't exactly if you guys opened this issue and if anyone have this problem with database tables engine. After the configuration i go to /contao/install and i've got this error:

an_error_occurred
unsupported_engine

unsupported_engine_explain

doctrine:
    dbal:
        connections:
            default:
                default_table_options:
                    engine: MyISAM

I know that from contao 4.5 is using InnoDB as an engine but i don't really know if i can specify somewhere what engine contao installer should use.

I am using Symfony 3.4 and MariaDB

Thank you,
Iulian

**Comment by fritzmg** [comment]
Just change the engine to InnoDB.

**Comment by iulianbeleiu** [comment]
@fritzmg From where? Is there a way to change it from some configurations of contao-installation or from my database options? The default in my database is set to InnoDB

**Comment by fritzmg** [comment]
You already posted the configuration options yourself ;). Put the following in your `app/config/config.yml`:
```yml
doctrine:
  dbal:
    connections:
      default:
        default_table_options:
          engine: InnoDB
```
