### ISSUE TITLE
The profiler template does not exists

### ISSUE THREAD

**Issue by iulianbeleiu** [contao/core-bundle#1412]
Hi, does anyone have this problem:

The profiler template "ContaoCoreBundle:Collector:contao.html.twig" for data collector "contao" does not exist.

Thanks,

Iulian

**Comment by bytehead** [comment]
Should be fixed in [master](https://github.com/contao/core-bundle/commit/94c7ea7c72350f2314c3132866486cfe9cb91098), which version are you using?

**Comment by bytehead** [comment]
Will be fixed in upcoming 4.4.15, see https://github.com/contao/core-bundle/pull/1379.
