### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by goransi** [contao/core-bundle#1413]
Hello!
I'm using contao 4.5.4 and (some days ago I can't login to admin. After installation "contao-community-alliance/translator": "^2.1" login normally. Today I'm update all with ssh $ composer update. Now I get new error. Here is:
Fatal error: Class 'Backend' not found in /home/myusername/public_html/vendor/contao/core-bundle/src/Resources/contao/classes/Ajax.php on line 26
Where is the problem? Which apache modules and PHP extensions I must to have!?

Thank you for help!
Best ragards,
Goran Sabo

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org) for this kind of questions. If it turns out to be a bug in Contao, I'll happily reopen the ticket.
