### ISSUE TITLE
Tiny Pagepicker läuft in 404 nach Update von 4.4.14 auf 4.4.15

### ISSUE THREAD

**Issue by jommbee** [contao/core-bundle#1415]
Tiny Pagepicker läuft in 404 nach Update von 4.4.14 auf 4.4.15

Aus de Log File:
`request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: XXX/_contao/picker?context=link&extras[fieldType]=radio&extras[filesOnly]=true&value=&popup=1" at /XXX/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 112 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: XXX/_contao/picker?context=link&extras[fieldType]=radio&extras[filesOnly]=true&value=&popup=1 at /XXX/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:112, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: XXX/_contao/picker?context=link&extras[fieldType]=radio&extras[filesOnly]=true&value=&popup=1 at /XXX/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:66)"} []`

**Comment by webdecker** [comment]
Den Fehler habe ich auch nach frischer 4.4.15-Installation mit dem Contao-Manager.

**Comment by netzarbeiter** [comment]
Habe den selben Fehler nach dem Update auf 4.4.15 auf mehreren Installationen, Contao 4.5.6 ist nicht betroffen.

**Comment by leofeyer** [comment]
We have to backport this: https://github.com/contao/core-bundle/commit/65ae1882f89de1cd2e7328308cfafe25231ac301

**Comment by leofeyer** [comment]
Fixed in 4f6cbc4320734abcb791d3349196f83c8373c180.

**Comment by 31er** [comment]
Nach Update von 4.4.14 auf 4.4.16 tritt der Fehler bei mir nun auf.

**Comment by xchs** [comment]
Du musst den Browser-Cache löschen.

**Comment by 31er** [comment]
OK, danke, das war es.
Hatte nur Systemwartung durchgeführt und über den Contao-Manager den Anwendungscache neu aufgebaut.
