### ISSUE TITLE
Teaser-Element

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1417]
1. For the Element "ArticleTeaser" the new Picker should be used.
https://github.com/contao/core-bundle/issues/747
2. As we have Teasers for news and events as well - i think it would make sense to provide that functionality and make the element more generic and rename it to just "Teaser".
Currently the only way for editors to display a __specific__ news/event- Teaser is to create a news/event list module with the short template, limit it to 1 item, use the featured-only flag and hope for the best.
3. It would also be nice to have an article image attribute by default which could be used not only by the Teaser-Element but as og:image, backgroud-image or other use-cases.
https://github.com/contao/core/issues/118
https://github.com/contao/core/issues/8787#issuecomment-334483958

**Comment by leofeyer** [comment]
The article picker has been added meanwhile (see https://github.com/contao/core-bundle/pull/755). A teaser element and the article image options are probably better added in an extension – at least there hasn't been much interest in this feature in the last two years.
