### ISSUE TITLE
Some routes do not work

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#142]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/64) by @leofeyer
Friday Mar 06, 2015 at 20:48 GMT

The following routes no longer work:

 - `http://contao.local/app_dev.php/`
 - `http://contao.local/app_dev.php/en`

@aschempp I guess that's why we had a `contao_root` route in the previous version of the front end loader?

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Monday Mar 09, 2015 at 13:02 GMT

I noticed this too. However, it's not a bug in Contao 4, I found the same in Contao 3 if you have no 404-page redirecting to the language root… All routes (including the ones you mentioned) are forwarded to our Controller, but the "legacy" code does not handle them.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Monday Mar 09, 2015 at 13:16 GMT

I just tested it:

* `http://localhost/contao3` takes me to `http://localhost/contao3/en/` [OK]
* `http://localhost/contao3/` takes me to `http://localhost/contao3/en/` [OK]
* `http://localhost/contao3/en` takes me to `http://localhost/contao3/en/en` [NOK]

In contrast:

* `http://contao4.local/` throws a `ResourceNotFoundException` [NOK]
* `http://contao4.local/en` also throws a `ResourceNotFoundException` [NOK]

This might of course be due to an incomplete URL rewrite configuration. But couldn't we add routes to handle these cases?

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Monday Mar 09, 2015 at 13:28 GMT

Also see https://github.com/contao/core/issues/7666

I never got a `ResourceNotFound`, I did get a `die_nicely` with page-not-found.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Monday Mar 09, 2015 at 19:52 GMT

Do you have "add language to URL" enabled?

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Monday Mar 09, 2015 at 20:13 GMT

I tried both. It worked just fine without, and I had the same issues with `prepend_locale: true`

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Tuesday Mar 10, 2015 at 19:40 GMT

That's why we had a `contao_root` route in the first version of the loader. But I'll check whether I can work around the two issues using the rewrite module of the web server.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Tuesday Mar 10, 2015 at 19:43 GMT

I don’t think so. The Symfony router does match the route, but Contao does not correctly handle it (at least in my case).

**Comment by leofeyer** [comment]
See #76.
