### ISSUE TITLE
Unnecessary long asset names in Contao 4.5

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#1423]
There was a change in the combiner class from 4.4.x to 4.5.x. In 4.5. combining many files (e.g. css) end up with long names like:
```
https://demo.contao.org/assets/css/fonts.css+mooRainbow.min.css+chosen.min.css+simplemodal.min.css+...-15268655.css
```
or 
```
https://demo.contao.org/assets/css/files_contaodemo_theme_scss_theme-styles.min.scss.css
```

Before we had simply a 8 chars long md5 hash.

What was the reason for this change?

I would prefer not to display any original name in the assets filename.

**Comment by leofeyer** [comment]
Contao now behaves similar to the Google Pagespeed module, which generates paths like this (taken from contao.org):

```html
<link rel="stylesheet" href="A.assets,,_contao,,_css,,_layout.min.css+assets,,_contao,,_css,,_responsive.min.css+files,,_hostingwerk,,_bootstrap,,_css,,_bootstrap.min.css+files,,_hostingwerk,,_bootstrap-switch,,_css,,_bootstrap-switch.min.css+files,,_hostingwerk,,_select2,,_css,,_select2.min.css+files,,_hostingwerk,,_material-design-iconic-font,,_css,,_material-design-iconic-font.min.css+files,,_hostingwerk,,_hostingwerk.min.css,Mcc.w7ItbxH83E.css.pagespeed.cf.qWtuccmQ2m.css">
```

I don't see anything wrong with this plus it is much easier to understand than an MD5 hash.

**Comment by Aybee** [comment]
I don't want such filenames. Can someone explain what's the benefit?

**Comment by fritzmg** [comment]
I also don't see the benefit. It bloats the HTML output and If you want to see which assets are behind the combined file, you use the developer environment.

**Comment by leofeyer** [comment]
I'm pretty confident that Google has good reasons for doing it this way. 😉
