### ISSUE TITLE
Remove external resources from public pages

### ISSUE THREAD

**Issue by CMSworker** [contao/core-bundle#1425]
In the twig error layout there is a font from Google CDN (external ressource) loaded:

https://github.com/contao/core-bundle/blob/e0a0411e639234d2dac230bbbe1c7c3670420970/src/Resources/views/Error/layout.html.twig#L10

Error pages may be visible to the public, like when the maintenance mode is active. I know it's nice to have a beautiful formated error page. But this should be optinal or added on purpose by the webmaster only (eg in a custom template).

In terms of privacy there shouldn't be any external ressources loaded without the knowledge and acceptance of the visitor. Aus dem gleichen Grund gibt es z.B. bei Social Plugins von Facebook und Co. die "2-Klick-Lösung", bei welcher der Besucher erst zustimmen muss, dass eine Verbindung zu den Servern der Drittanbieter hergestellt wird, bevor das Plugin angezeigt wird.

Solution: Embed the OpenSans font files directly in Contao core so that it is a self-hostet webfont and not loaded by Google. Or replace it by default webfonts.

"Open Sans" is published with an Apace Licence, so it sould be possible to deliver it directly with the Contao core template package.

**Comment by leofeyer** [comment]
> In terms of privacy there shouldn't be any external ressources loaded without the knowledge and acceptance of the visitor. 

I don't think that this applies to loading web fonts (or any other JS or CSS library). The Facebook plugin collects data and connects it with your profile, so a two step solution makes sense in this case. However, using web fonts simply downloads a style sheet without associating any personal data with any account.

**Comment by xchs** [comment]
What Google says: [What does using the Google Fonts API mean for the privacy of my users?](https://developers.google.com/fonts/faq#what_does_using_the_google_fonts_api_mean_for_the_privacy_of_my_users)
What others write about it: [Google-Tracking von Admins und Web-Besuchern mit Google-Fonts](https://www.hubit.de/google-tracking-von-admins-und-web-besuchern-mit-google-fonts/)

**Comment by leofeyer** [comment]
Let's not get paranoid here, ok? Of course Google sees the IP address and browser language as does *every other website* you visit. You need a VPN if you want to prevent this.

**Comment by agoat** [comment]
This may end in a general discussion about privacy and tracking.

But when requesting a Google font the browser also send a Referer (see image). Using the IP, some browser information and the Referer, a user can be tracked over different webpages.

Google will use this information for sure, that's what they make money with - collecting and selling usage information from internet users.

![googlefontsreferer](https://user-images.githubusercontent.com/1402434/37335265-576ee7fc-26ae-11e8-94ca-df68fe628346.jpg)

**Comment by CMSworker** [comment]
Well, other external resources like jquery, colorbox, tinymce, datepicker etc are also installed via packagist/composer and loaded/delivered locally from the assets folder and not from an exernal domain. What ist the difference here, why didn't you embed them via external CDNs? The benefit would be the same like when using webfonts from Google CDN: The external source is up-to-date and the file could be already in the browser cache if the user has already visited another website that was using the file from the external ressource.

I personally prefer "privacy by design" and having all resources loaded from my own webspace. So I (could/should) know what files I deliver to my visitors and what is beeing tracked, how, where and used for. When using external services it's getting more difficult to explain usage and tracking in the privacy statement...

Well no big deal, I just copied the template to 
/app/Resources/ContaoCoreBundle/views/Error/layout.html.twig
and removed the line with the external webfont, so problem solved.

I just opened this issue so it could be discussed if Contao will use/embed files from external ressources in general or not. I recommend to avoid external CDN and deliver the font files with the core-package.

**Comment by leofeyer** [comment]
I have no problem to use the existing web fonts from the back end theme for the error templates.

**Comment by CMSworker** [comment]
Yes, using the fonts provided locally from the backend theme sounds like a good solution :-)

**Comment by leofeyer** [comment]
Changed in 06e623e4bc40692f2e0f37f47e0e0128b46c0f98.
