### ISSUE TITLE
Contao 5: Plans for frontend editing forms using symfony forms?

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1430]
Hello,

since Contao 3 there was "only" the form generator which is not linked to any DCA fields. Also callbacks on fields were difficult to manage. For persistence we needed efg.

These were the reasons we wrote heimrichhannot/contao-frontendedit. Though it's not perfect, it offers support for editing any dca entity in the frontend supporting palette handling, callbacks, ... The base for the module is heimrichhannot/contao-formhybrid which does the form generation.

At the moment we wonder if it's time to completely refactor this module into a contao 4 bundle using symfony forms.

But also we're wondering if in Contao 5 the framework will have this feature anyway. Of course we don't want to build a parallel structure.

So is there anything like this planned for the "near" future, i.e.:

- form generation with DCA fields of any entity in the frontend
- full palette and sub palette support
- all this "probably" using symfony forms

Thanks in advance!

Bye Defcon0

**Comment by leofeyer** [comment]
It is impossible to say what Contao 5 will contain. We haven't discussed anything so far and we are not planning to release Contao 5 anytime soon.

**Comment by dmolineus** [comment]
@Defcon0 As a side note: I've started to work on a form bundle which takes the form configuration of Contao and build a symfony form for it.

The goal is to support DCA and the form generator. Atm I've started on the form generator.

I'd would be happy if there would be one library to fill this gap and not a dozens different one. Feel free to contribute or contact me if you're planning to go further in this direction.

https://github.com/netzmacht/contao-form-bundle

**Comment by Defcon0** [comment]
@dmolineus Thanks for the hint. Definitely an interesting bundle. At the moment we already have written a module for creating filter forms in the frontend:

https://github.com/heimrichhannot/contao-filter-bundle

This bundle already supports creating symfony forms with various field types symfony supports (including an optional link to DCA fields).

What we would do in the future is to extract the form generation functionality and also support linking the user input to some contao entity (=db record) supporting callbacks and so on. Also what's still missing is (async) palette handling.

Maybe you could also take a look at this bundle?

What might also be interesting: In addition we also wrote a [list-bundle](https://github.com/heimrichhannot/contao-list-bundle) and a [reader-bundle](https://github.com/heimrichhannot/contao-reader-bundle) for arbitrary Contao entities. list-bundle is built on top of the filter-bundle.
