### ISSUE TITLE
login removes app_dev.php

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1432]
Reproduction:

1. Access the back end login page via `example.org/app_dev.php/contao/login`.
2. Log into your account.

You will be redirected to `example.org/contao` instead of `example.org/app_dev.php/contao`.

**Comment by m-vo** [comment]
I experienced that as well and I remember there were also other situations when using the backed were this was the case.

**Comment by leofeyer** [comment]
The `_target_path` field does not contain `app_dev.php`.

**Comment by m-vo** [comment]
True!

**Comment by aschempp** [comment]
> The _target_path field does not contain app_dev.php.

I've had this issue as well. Looks like a Symfony bug to me if the entry point is not added when generating the URL?

**Comment by leofeyer** [comment]
Fixed in c0026a707a01f8da4847bb88e3a203e88f4c8a5f.
