### ISSUE TITLE
unterschiedliches Verhalten für Templateauswahl

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#1438]
Ich habe eine eigenes Galerietemplate angelegt: ```gallery_boxen.html5``` - dieses wird nun immer als erstausgewähltes Template einer Galerie genutzt - wahrscheinlich weil die Auswahl alphabetisch getroffen wird. Das ist natürlich ungünstig. Bei dem Feld "Individuelles Template" ist standardmäßig immer nichts ausgewählt. Dies wäre für das Feld "Galerietemplate" ebenfalls sinnvoll.

Bei den Contentelementen habe ich jetzt keine weiteren Elemente gefunden, die eine doppelte Templateauswahl haben, aber bei Modulen gibt es das auf jeden Fall. Da müsste es ebenfalls geändert werden.

Frage am Rande: Nur eine Templateauswahl ist hier nicht möglich?

**Comment by baumannsven** [comment]
The select field has not an blank option. This is the problem.

See https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_content.php#L598

In the content is testing for it. See https://github.com/contao/core-bundle/blob/master/src/Resources/contao/elements/ContentGallery.php#L327

**Comment by leofeyer** [comment]
Grundsätzlich ist es korrekt, dass das Select-Menü kein leeres Element hat. Das ist auch bei allen anderen Bereichstemplates der Fall:

<img width="593" alt="" src="https://user-images.githubusercontent.com/1192057/38090741-d487e97a-3363-11e8-86f0-721f665430db.png">

<img width="603" alt="" src="https://user-images.githubusercontent.com/1192057/38090744-d953a5de-3363-11e8-84f0-54bbdc488278.png">

<img width="609" alt="" src="https://user-images.githubusercontent.com/1192057/38090752-dd9b1d70-3363-11e8-9863-012a098d2a6f.png">

Das liegt daran, dass dieses Template zwingend ausgewählt werden muss und nicht optional ausgewählt werden kann, wie es beim "Custom element template"-Select der Fall ist. Es handelt sich also erstmal nicht um einen Bug.

Tatsächlich berücksichtigt die `ContentGallery`-Klasse den Fall, dass kein Template ausgewählt wurde, alle anderen Klassen jedoch nicht. Wir müssen besprechen ob wir das bisherige Verhalten zukünftig ändern möchten, allerdings kann es gut sein, dass es Extensions gibt, die sich darauf verlassen, dass die Bereichstemplates immer gesetzt sind.

**Comment by frontendschlampe** [comment]
Ich denke auch eher, dass das Problem darin besteht, dass bei der Auswahl des Default-Templates einfach alphabetisch vorgegangen wird - wie in meinem Beispiel beschrieben. ```gallery_default``` oder jedes andere Template sollte immer das Default- bzw. erstausgewählte Template bleiben. Nur weil ich ein eigenes Template mit einem Namen kleiner "_default" anlege, wie z.B. "_boxen", darf dieses Template nicht als Standardauswahl bei einem neuen Element gelten. Ob es jetzt eine leere Auswahl gibt, ist erstmal ein anderer Punkt.

**Comment by aschempp** [comment]
Die einfache Lösung dafür ist eine leere Option und das das Feld als Pflicht markieren. Das mache ich immer dann wenn keine Auswahl standardmässig genommen werden kann aber eine Auswahl Pflicht ist.

**Comment by fritzmg** [comment]
Dann müsste ein Redakteur aber _immer_ ein Template selbst auswählen.

**Comment by ausi** [comment]
Wäre die einfachste und beste Lösung nicht einfach `'default' => 'gallery_default'` zu setzen?

**Comment by aschempp** [comment]
> Dann müsste ein Redakteur aber *immer* ein Template selbst auswählen.

Bei der Galerie wäre `gallery_default` wohl das richtig. Bei Newslist und -Leser wäre aus meiner Sicht eine erzwungene Auswahl richtig.

**Comment by fritzmg** [comment]
@aschempp so sehe ich das auch.

**Comment by baumannsven** [comment]
@aschempp Wenn man die Templates als default deklariert ist das alles i.O.. Von einer erzwungen Auswahl würde ich absehen. Da dies den Redakteuren auf den Geist gehen wird.

**Comment by frontendschlampe** [comment]
@baumannsven naja ... die erzwungene Auswahl ja nur bei den Modulen. Bei den CE's gibt's nur bei der Galerie die Auswahl von 2 Templates! Von daher wäre es ok. Die Frage ist nur, was bei anderen Erweiterungen passiert, die ggfs. eine zweite Templateauswahl wie bei der Galerie haben.

**Comment by Aybee** [comment]
> @aschempp 
Bei Newslist und -Leser wäre aus meiner Sicht eine erzwungene Auswahl richtig.

Warum? Es müsste doch irgendwie möglich sein z.B. news_latest als Default für die Nachrichtenliste und news_full als Default für den Nachrichtenleser zu setzen.

**Comment by leofeyer** [comment]
Es sind deutlich mehr Templates betroffen als zunächst gedacht:

* `tl_content.galleryTpl`
* `tl_content.cal_template`
* `tl_content.cal_ctemplate`
* `tl_content.com_template`
* `tl_module.navigationTpl`
* `tl_module.memberTpl`
* `tl_module.searchTpl`
* `tl_module.com_template`
* `tl_module.rss_template`
* `tl_module.list_layout`
* `tl_module.list_info_layout`
* `tl_module.news_template`
* `tl_module.nl_template`
* `tl_newsletter.template`
* `tl_newsletter_channel.template`

Ich sehe ehrlich gesagt nicht, dass wir jetzt alle diese Templates umstellen – zumal dazu auch die Paletten angepasst werden müssen, damit die neuen Pflichtfelder sichtbar sind. Dann würde ich lieber die langfristige Lösung abwarten, in der wir auf die Bereichstemplates ganz verzichten können.

**Comment by frontendschlampe** [comment]
ok ... kein Problem. Wenn man es weiß, kann man es ja umschiffen. ;-)

Nur so am Rande: Die Umstellung ist doch theoretisch nur eine "Fleißarbeit", oder? Also wenn man auch als Nichtprogrammierer weiß, was man tun muss und ein Beispiel hat, dann kann man an Hand des Beispiels alle anderen Templates/Paletten auch umstellen?! Ggfs. könnte ich das mal mit machen. Natürlich nachdem ich die Icons gebaut hab.

**Comment by ausi** [comment]
> Ich sehe ehrlich gesagt nicht, dass wir jetzt alle diese Templates umstellen

Aber es geht ja nur darum in der DCA Konfiguration `'default' => 'gallery_default'` oder `'required' => true, 'includeBlankOption' => true` zu setzen. Auch wenn es viele Felder betrifft, ist der Aufwand doch relativ überschaubar, oder?

**Comment by leofeyer** [comment]
Nein, `'default' => 'gallery_default'` ist keine Option, da sonst bei jedem Eintrag in `tl_content` das Feld `gallery` auf `gallery_default` steht – und 99% der Inhaltselemente sind keine Galerien.

Wenn wäre es also `'mandatory' => true, 'includeBlankOption' => true`, aber das ist wie geschrieben mit weiteren Änderungen an den Paletten verbunden, denn aktuell befinden sich die Template-Felder in zugeklappten Paletten.

**Comment by aschempp** [comment]
> Nein, 'default' => 'gallery_default' ist keine Option, da sonst bei jedem Eintrag in tl_content das Feld gallery auf gallery_default steht – und 99% der Inhaltselemente sind keine Galerien.

Das ist doch wurscht? Das Feld wird ja in allen anderen Elementen einfach nicht verwendet. In den Modulen steht auch überall `nav_default` drin?

**Comment by leofeyer** [comment]
Nein, tut es nicht. Das Feld hat keinen Default-Wert:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_module.php#L241-L249

**Comment by aschempp** [comment]
Es ist trotzdem irrelevant… Nimm halt irgend ein anderes Feld, `searchType` ist auch default auf `simple`…

**Comment by leofeyer** [comment]
Das ist auch falsch. Sollten wir ebenfalls ändern, wenn wir die Änderungen implementieren.

**Comment by leofeyer** [comment]
Es ist nicht falsch im Sinne von "muss gefixt werden", aber es bläht die DB unnötig auf und könnte optimiert werden, wenn wir die Templates eh überarbeiten.

**Comment by fritzmg** [comment]
In wie fern wird die Datenbank aufgebläht? Es werden ja keine neuen Felder hinzugefügt.

**Comment by leofeyer** [comment]
Also `gallery_default` hat 16 Zeichen, somit 16 Byte. Wenn es 500 Inhaltselemente gibt, werden in der Tabelle `tl_content` 500 * 16 Byte, also 8 KB an Daten abgelegt. Da von den 500 Inhaltselementen aber vermutlich nur 10 vom Typ "Bildergalerie" sind, sind 490 * 16 Byte an unnötigen Daten gespeichert worden. Und das Problem besteht nicht nur in der `tl_content` …

**Comment by m-vo** [comment]
Ist das nicht ein generelles Problem bei 'shared tables'? Will meinen, ich gebe dir bei deiner Rechnung vollkommen Recht, aber fällt das ins Gewicht? Wenn man z.B. davon ausgeht, dass die meisten Installationen Erweiterungen installiert haben, die dann zahlreiche neue Felder in `tl_modules` hinzufügen (was kaum anders möglich ist).

**Comment by fritzmg** [comment]
> Also gallery_default hat 16 Zeichen, somit 16 Byte. Wenn es 500 Inhaltselemente gibt, werden in der Tabelle tl_content 500 * 16 Byte, also 8 KB an Daten abgelegt. Da von den 500 Inhaltselementen aber vermutlich nur 10 vom Typ "Bildergalerie" sind, sind 490 * 16 Byte an unnötigen Daten gespeichert worden. Und das Problem besteht nicht nur in der tl_content …

Es geht ja nicht darum das SQL zu ändern, sondern nur den `default` Wert im DCA zu setzen. Der `default` Wert wird ja nur dann in der Datenbank gespeichert, wenn du ein Inhaltselement speicherst und diese Feld im DCA des jeweiligen Inhaltselements auch überhaupt angezeigt wird.

**Comment by baumannsven** [comment]
Warum macht man den die default Regelung der Templates nicht wie hier?
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/elements/ContentGallery.php#L324

Wenn das dem Core Team zuviel arbeit ist würde ich dafür einen Pull Request machen.

**Comment by fritzmg** [comment]
> Das ist ein Irrglaube …

Ah, tatsächlich, sorry.

**Comment by ausi** [comment]
Ich stimme @m-vo zu, wir verschwenden mit dem grundsätzlichen Aufbau von den Tabellen viel viel mehr Platz, der zusätzliche Default-Wert fällt dabei nicht ins Gewicht. Bei `tl_content` betrifft es dazu auch nur das Feld `galleryTpl` als einziges. Denn `com_template` hat bereits einen Default-Wert und `cal_template`/`cal_ctemplate` gibt es nicht in `tl_content`.

**Comment by leofeyer** [comment]
Behoben wie von @ausi vorgeschlagen in contao/contao@d3c4261bb8006c60abce8e56def5abddb65739a1.

**Comment by leofeyer** [comment]
@aschempp hat mich gerade darauf aufmerksam gemacht, dass wir auf Mumble bereits eine andere Lösung besprochen hatten. Diese ist nun in 1e02bb06c7d2c286d5ddb3a1591297e2bfbf2094 implementiert.
