### ISSUE TITLE
maxlength for image captions

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core-bundle#1439]
Why is caption field for images is limited to 255 chars?
I do not understand the reason and I think it's wrong.
I already had many cases where I had a longer caption text.
Same for headlines, alt and titles fields.

I think we should remove the max length and save the content as TEXT.

**Comment by Aybee** [comment]
Normaly 255 is enough here. Never heard about that this is not enough. So this (and all other) fields are limited to a capable minimum to save resources. If it is not enough in a special case then you can easily raise this values with the DCA settings.

**Comment by NicolasGoerlach** [comment]
Yes, I already changed the DCA for my projects.
I just wanted to share my experience

**Comment by leofeyer** [comment]
I also think that 255 characters is a reasonable default.
