### ISSUE TITLE
j_colorbox.html5 - open special links as iframe

### ISSUE THREAD

**Issue by Aybee** [contao/core-bundle#1443]
Die Colorbox wird immer wieder falsch benutzt, wenn anstatt Bildern Internetseiten aufgerufen werden sollen. Die Mediabox hat dies immer automatisch richtig gemacht, da sie den Inhalt anhand des Links eingeordnet hat.

Öffnet man Internetseiten mit der Colorbox, dann müssen folgende Optionen gesetzt werden.
```js
width: '60%',
height: '70%',
iframe: true,
```
Damit dies automatisch passiert habe ich einmal das `j_colorbox` angepasst. Zusätzlich ist noch die Option mit darin um diverse Texte zu internationalisieren. Daraus kann ich aber gerne noch ein eigenes Ticket machen. Es soll hier erstmal um das Öffnen mit `iframe: true, ...` von speziellen Links gehen. Im Moment werden Links erkannt, welche auf `.html` enden und Links welche `youtube.com` enthalten.
```php
<?php

// Add the colorbox style sheet
$GLOBALS['TL_CSS'][] = 'assets/colorbox/css/colorbox.min.css|static';

/** *
 * Language options from assets/jquery/colorbox/1.6.1/js/colorbox.js - Contao 3.5.24
 *
 * // internationalization
 * current: "image {current} of {total}",
 * previous: "previous",
 * next: "next",
 * close: "close",
 * xhrError: "This content failed to load.",
 * imgError: "This image failed to load.",
 */

// Language arrays
// All
$cbLang = array(
  'current'  => 'image {current} of {total}',
  'previous' => 'previous',
  'next'     => 'next',
  'close'    => 'close',
  'xhrError' => 'This content failed to load.',
  'imgError' => 'This image failed to load.'
);
// DE
if($GLOBALS['TL_LANGUAGE'] == 'de')
{
  $cbLang = array(
    'current'  => 'Bild {current} von {total}',
    'previous' => 'zurück',
    'next'     => 'weiter',
    'close'    => 'schließen',
    'xhrError' => 'Laden des Inhalts fehlgeschlagen.',
    'imgError' => 'Laden des Bildes fehlgeschlagen.'
  );
}

?>

<script src="<?= TL_ASSETS_URL ?>assets/colorbox/js/colorbox.min.js"></script>
<script>
  (function($) {
    $(document).ready(function() {
      $('a[data-lightbox]').map(function() {
        var isIFrame = false;

        if($(this).attr('href').split('.').pop() == 'html' || $(this).attr('href').indexOf('youtube.com') != -1) {
          isIFrame = true;
        }

        $(this).colorbox({
          // Put custom options here
          loop: false,
          rel: $(this).attr('data-lightbox'),
          maxWidth: '95%',
          maxHeight: '95%',
          width: isIFrame ? '60%' : false,
          height: isIFrame ? '70%' : false,
          iframe: isIFrame,
          // internationalization
          current: '<?= $cbLang['current'] ?>',
          previous: '<?= $cbLang['previous'] ?>',
          next: '<?= $cbLang['next'] ?>',
          close: '<?= $cbLang['close'] ?>',
          xhrError: '<?= $cbLang['xhrError'] ?>',
          imgError: '<?= $cbLang['imgError'] ?>'
        });
      });
    });
  })(jQuery);
</script>
```
Edit: Geändert. Sorry, da waren noch die Ressourcen von der 3.5 anstatt von der 4.

**Comment by leofeyer** [comment]
Wie lässt sich das initiale Problem reproduzieren?

**Comment by Aybee** [comment]
Erstelle ein CE Typ Text. `Link target` =  `https://contao.org/`. `Lightbox` = `lightbox`. Dann im FE auf den Link klicken.

**Comment by leofeyer** [comment]
Ich habe mal die Internationalisierung aus dem Template genommen, damit man die eigentlichen Änderungen sieht:

```html
<script>
  jQuery(function($) {
    $('a[data-lightbox]').map(function() {
      var isIFrame = false;

      if ($(this).attr('href').split('.').pop() == 'html' || $(this).attr('href').indexOf('youtube.com') != -1) {
        isIFrame = true;
      }

      $(this).colorbox({
        // Put custom options here
        loop: false,
        rel: $(this).attr('data-lightbox'),
        maxWidth: '95%',
        maxHeight: '95%',
        width: isIFrame ? '60%' : false,
        height: isIFrame ? '70%' : false,
        iframe: isIFrame
      });
    });
  });
</script>
```

Vermutlich ist es sinnvoll, wenn wir das Template entsprechend anpassen. Allerdings ist die Lösung mit "entweder `.html` oder `youtube.com`" für meinen Geschmack zu unflexibel. Man könnte so nie die Startseite einer Webseite (also die leere Domain) in dem iFrame anzeigen.

@contao/developers /cc

**Comment by leofeyer** [comment]
Andererseits sollte vielleicht der Entwickler der Colorbox das einbauen, damit nicht jeder Colorbox-Nutzer das für sich nachrüsten muss?

**Comment by Toflar** [comment]
Naja, für die Zukunft wäre es imho ohnehin mal an der Zeit die Slider-Skripte und "Colorbox"-Skripte auf Vanilla-JS Lösungen umzurüsten. Das Design dieser Colorbox ist eh fürchterlich und es gibt mittlerweile so viel schönere und einfachere Lösungen, ohne jQuery laden zu müssen. /cc @ausi

**Comment by ausi** [comment]
Mir persönlich gefällt <http://photoswipe.com/>, die kann kein aber iframe/youtube. Ich bin mir auch nicht sicher ob wir iframe/youtube überhaupt unterstützen sollten?

> Allerdings ist die Lösung mit "entweder `.html` oder `youtube.com`" für meinen Geschmack zu unflexibel.

Denke ich auch, der `.html`-Check würde für die meisten Websites wohl nicht funktionieren...

**Comment by fritzmg** [comment]
Alle Lightboxen sind sch … … ön - können aber nicht alles. Ich habe auch noch nicht die Eierlegende Wollmilchsau finden können, die eben alle Eventualitäten abdecken kann, die in Contao bzw. einem CMS vorkommen könnten.

**Comment by Aybee** [comment]
> @leofeyer 
 Man könnte so nie die Startseite einer Webseite (also die leere Domain) in dem iFrame anzeigen.

Ja, dies hatte ich auch bemerkt, war erstmal als Ansatz gedacht. Evtl. würde es reichen, wenn man `.split('.').pop()` auf jpg, png, gif, svg usw. untersucht und nur dann keinen iFrame benutzt.

> @ausi 
Ich bin mir auch nicht sicher ob wir iframe/youtube überhaupt unterstützen sollten?

IMHO ist dies zwingend erforderlich Youtube Videos in einem iFrame zu präsentieren, alleine schon, weil Youtube dies vorschreibt.

Eine Vanilla Lightbox fände ich auch klasse. Als Fan von MooTools hatte ich früher immer die Mediabox benutzt, welche dann aber nicht mehr weiterentwickelt wurde und bestimmt viele Macken hat, was Responsiveness und Touchscreens betrifft. Deshalb benutze ich seither die Colorbox, was mich dann auch dazu gezwungen hat jQuery einzusetzen. Mit einer Vanilla-Lösung wäre man da wieder frei in seiner Entscheidung. Eine gute Vanilla Lightbox habe ich aber auch nicht parat.

**Comment by stefansl** [comment]
Ich baue mir gerade ein Bundle mit BaguetteBox. BB ist modern, in VanillaJS, hat Keyboard- und Touch-Unterstützung und CSS3 Transitions. https://github.com/feimosi/baguetteBox.js
Würde das als Colorbox-Ersatz sehr begrüßen! :)

**Comment by fritzmg** [comment]
@stefansl laut der Doku erfordert es den selector am parent - das würde ja für `data-lightbox` Attribute direkt am Link nicht funktionieren?

**Comment by stefansl** [comment]
@fritzmg Das muss ich noch testen. Ich hab den bis jetzt nur auf .ce_gallery angewendet. Letztendlich könnte das eine Template-Änderung mit sich ziehen. Aber sollte doch gut abwärtskompatibel zu gestalten sein, da nur ein CSS-Klasse hinzukommen würde - und zwar im parent (z.b.lightbox). Ich hab selbst erst damit gestern abend angefangen. :)

**Comment by Aybee** [comment]
> @stefansl BB ist modern, ...

Ich denke schon, dass man auch Seiten (Iframe) und Inline HTML damit öffnen können sollte. Dies ist nur ne ganz minimalistische Box für Gallerien. Unterstützt noch nicht mal einzelne Links, wenn sie nicht gewrappt sind.

**Comment by stefansl** [comment]
@Aybee Du hast recht! Damn it!

**Comment by leofeyer** [comment]
Wie am 17. Mai auf Mumble besprochen ist das halt eine Einschränkung der Colorbox, die wir nicht extra fixen wollen. Wenn Du unbedingt YouTube-Videos in einer Lightbox anzeigen willst (was auf mobilen Geräten nie eine gute User-Experience ist), musst Du halt die Mediabox nehmen oder ein eigenes Skript verwenden.

**Comment by Aybee** [comment]
Ich persönlich würde dies auch nicht machen, aber meine Kunden 😏 .

Aber es sind ja nicht nur YouTube-Videos. Hauptsächlich geht es um meist interne Seiten, welche damit geöffnet werden sollen. Im Forum taucht es immer wieder auf, dass Admins interne Seiten mit der Colorbox öffnen und wenn die dann nicht in einem Iframe sind, führt dies zu ungeahnten Fehlern. Evtl. könnten wir das zumindestens für `.html` und `/` am Ende ins Template bringen.
