### ISSUE TITLE
Contao 4.5 - DC-Table

### ISSUE THREAD

**Issue by jedoStyle** [contao/core-bundle#1446]
> Fixed in 3695d4f

gleiches problem andere Zeile:

Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: count(): Parameter must be an array or an object that implements Countable" at /vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php line 4887

**Comment by leofeyer** [comment]
Siehe #1353.
