### ISSUE TITLE
Verwendung von role=application in mediaelement-and-player.js

### ISSUE THREAD

**Issue by detlevhfischer** [contao/core-bundle#1447]
Ich verwende gerade in einer Contao-Site Videos über mediaelement.js bzw.
mediaelement-and-player.js . Bei der Site geht es um Zugänglichkeit, deshalb soll sie natürlich auch selbst möglichst zugänglich sein, und Contao bietet da ja eine gute Grundlage.

Beim Testen der Videos habe ich nun festgestellt, dass es für Screenreadernutzer nicht möglich ist, nach dem Fokussieren des Videos mit den Pfeiltastennavigation (Browse-Modus) aus dem Video-Bereich wieder herauszukommen, etwa um zu Textinhalten unmittelbar darunter zu gelangen.

Das liegt wohl daran, dass im JS.Element mediaelement-and-player.js die role=application gesetzt wird:
`
t.getElement(t.container).setAttribute('role','application');`

Ich habe die entsprechende Zeile mal in der .min Version von mediaelement-and-player.js auskommentiert, und nun komme ich auch aus dem Element mit Pfeiltasten heraus. Die sonstige Maus-, Tastatur- und Screenreaderbedienung scheint nicht beeinträchtigt.

Ich wollte deshalb vorschlagen, diese Änderung allgemein zu übernehmen.

**Comment by leofeyer** [comment]
Klingt einleuchtend. Du müsstest es allerdings bei [mediaelement/mediaelement](https://github.com/mediaelement/mediaelement/issues) melden, damit die Entwickler von mediaelement.js das einbauen können.
