### ISSUE TITLE
Ordner mit Leerzeichen verursacht Probleme bei Bildauswahl

### ISSUE THREAD

**Issue by cubano** [contao/core-bundle#1449]
Hallo. Enthalten verschachtelte Ordnernamen Leerzeichen, so entstehen Probleme bei der Bildauswahl.

- images
   - Hauptordner A
         - Unterordner A1
         - Unterordner A2
         - Unterordner A3
   - Hauptordner B
        - Unterordner B1
        - Unterordner B2
- videos

Ich erstelle ein Inhaltselement "Galerie" und wähle diverse Fotos aus diversen Unterordnern von A+B aus, lasse dabei alle Ordner wo es ausgewählte Fotos hat aufgeklappt und klicke auf "Anwenden" um meine Auswahl zu bestätigen. Soweit alles gut.

Möchte ich nun meine Auswahl ändern um z.B. weitere Fotos aus dem Unterordner A3 hinzuzufügen und klappe ich dabei übersichtshalber den Hauptordner B zu, so gehen bei Klick auf "Anwenden" alle vorher selektierten Fotos aus den Unterordnern von B verloren.

Keine Probleme bei verschachtelten Ordner ohne Leerzeichen.

Contao 4.4.16

**Comment by fritzmg** [comment]
Bist du dir sicher, dass das etwas mit den Leerzeichen zu tun hat? Dass die Auswahl aus Unterordnern die du zugeklappt hast verloren geht ist meines erachtens zu erwarten.

**Comment by asaage** [comment]
> Dass die Auswahl aus Unterordnern die du zugeklappt hast verloren geht ist meines erachtens zu erwarten

Also ich würde das nicht erwarten. Hab aber auch noch nicht probiert, ob das wirklich passiert.

**Comment by fritzmg** [comment]
Naja, wenn du zB die Funktion "alles auswählen" benutzt wird auch nur das ausgewählt, was in der aktuellan Ansicht tatsächlich sichtbar ist und nicht "alles was möglich ist".

Wenn du einen Teil des Baums (egal ob in der Seitenstruktur oder im Dateimanager) zumachst und dann die aktuelle Auswahl übernimmst, wird eben das übernommen, was aktuell sichtbar ist. Alles andere existiert unter Umständen auch gar nicht mehr im DOM.

**Comment by cubano** [comment]
Da es bei Ordnern ohne Leerzeichen nicht passiert, gehe ich schon davon aus, dass es was mit den Leerzeichen zu tun hat.

Das Verhalten ist meines Erachtens nicht zu erwarten. Bei Webseiten mit vielen Ordner/Bilder ist es durchaus hilfreich, Ordern bei der Auswahl auf-/zuzuklappen.

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren: https://www.dropbox.com/s/17fg1l2w2q2qs7b/1449.mp4?dl=0

**Comment by cubano** [comment]
Hast recht, so ist es bei mir auch nicht reproduzierbar. Nach weiteren Tests habe ich nun die Ursache herausgefunden. Und zwar enthalten (neben den Ordnern mit Leerzeichen) einige Dateien Klammern im Dateinamen, also z.B. Bild-Aussen-(1-von-1).jpg

Sind in einem Unterordner Dateien, welche Klammern enthalten, ausgewählt und klappe ich sowohl den Unterordner als auch den Hauptordner zu, so geht die Auswahl der Bilder verloren.

**Comment by leofeyer** [comment]
Also müsste ich z.B. die Datei `bridge.jpg` im Ordner `Hauptorder A/Unterordner A1` in `bridge-(1-von-1).jpg` umbenennen, um das Problem zu reproduzieren?

**Comment by cubano** [comment]
Ja genau.` bridge.jpg` umbenennen in `Bridge-(1-von-1).jpg`, alle Ordner aufklappen und alle Bilder auswählen und anwenden. Danach wieder in die Bildauswahl reingehen, `Unterordner A1` und `Hauptordner A` zuklappen und anwenden. Danach sollte die Auswahl der selektierten Bilder innerhalb `Unterordner A1` verloren gehen. Mit nur einem Bild innerhalb eines Unterordners habe ich es jedoch nicht getestet, sondern mit 2 oder mehr (hat ev. auch einen Einfluss …)

**Comment by cubano** [comment]
Nach weiteren Tests liegt der Bug doch nicht bei den Klammern :-) Die Ursache sind die Leerzeichen bei den Ordnern und es ist auch in deinem Video auf Dropbox sichtbar.

Nachdem du den `Hauptordner B` zugeklappt und die Änderungen angewendet hast und nachher wieder in die Bildauswahl reingehst, ist der `Hauptordner B` immer noch zugeklappt! Hingegen bei Ordnern ohne Leerzeichen öffnet sich der Ordner und zeigt die ausgewählten Dateien. Wenn du nun den `Hauptordner B` wieder aufklappst, sind die Dateien immer noch ausgewählt, wie im Video, alles i.O. Wenn du jedoch den `Hauptordner B` nicht erneut aufklappst und erneut auf Anwenden klickst, dann gehen die selektierten Bilder der Unterordner verloren.

**Comment by leofeyer** [comment]
Ja, Du hast Recht. Danke für die Geduld. Behoben in 116b0d364654ad447ba17f5bfaba2158c65a80ed.
