### ISSUE TITLE
Useless "coreOnlyMode"

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#145]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/67) by @aschempp
Friday Mar 13, 2015 at 08:38 GMT

The `coreOnlyMode` does no longer work as it does not disable bundles. I also think we don't need it anymore if the install tool is standalone.

**Comment by leofeyer** [comment]
Removed in 8a0c270c399423fbe25aec955c6db4c19cdfe58f.
