### ISSUE TITLE
Contao Navigation skipNavigation 

### ISSUE THREAD

**Issue by TS16V** [contao/core-bundle#1453]
![unbenannt-1](https://user-images.githubusercontent.com/38064792/38293678-b6fa61c4-37e8-11e8-9481-90c47af89087.jpg)

Problem Navigation - Modul in the Validator

http://vorlage1.ips21.de/

` <a id="skipNavigation3" class="invisible">`

**Comment by frontendschlampe** [comment]
Do you use the navi module twice in your layout?

**Comment by fritzmg** [comment]
Yes he does.

**Comment by leofeyer** [comment]
This is the same case as in contao/core-bundle#957. We have agreed on this being a known limitation, so if you want to use two navigation modules in your layout, you will have to create two separate modules.
