### ISSUE TITLE
Strict types in 4.5 are an API BC break

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1455]
One of the users of my extension for Contao 4.4+ reported an issue which relates to the strict types that were introduced in Contao 4.5 – https://github.com/codefog/contao-news_categories/issues/141. There is no way I could extend the parent class method for both 4.4 and 4.5 because a child class cannot have a weaker definition. Thus the only fix for me is to create two separate branches now, one for 4.4 and one for 4.5+ which will be extremely difficult to maintain.

4.4: https://github.com/contao/core-bundle/blob/4.4/src/Picker/AbstractPickerProvider.php#L55
4.5: https://github.com/contao/core-bundle/blob/4.5/src/Picker/AbstractPickerProvider.php#L59

I think strict types must be introduced but in a version like 5.0 and not 4.x. Otherwise it's just an API BC break.

/cc @aschempp @Toflar

**Comment by fritzmg** [comment]
Hm, can't you just use
```php
public function getUrl(PickerConfig $config): ?string
```
in your own class and increase the PHP minimum requirement for your package to 7.1?

**Comment by leofeyer** [comment]
Kamil is right, we must not add type hints to interfaces and abstract classes that exist in both Contao 4.4 and 4.5. Seems I have missed the picker class.

**Comment by leofeyer** [comment]
Fixed in 23676ccd98abde6d1facfe95deba86ad3ae1b912 and contao/installation-bundle@983e7d1badee6e1380707041a20a527582decf11.
