### ISSUE TITLE
Check if BackendUser::getInstance() should throw an exception

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#1458]
Please see this related issue where a runtime exception happens when calling `BackendUser::getInstance()` during the execution of Contao's poor man cron job from the backend: https://github.com/terminal42/contao-easy_themes/issues/40 

I was actually wondering if `BackendUser::getInstance()` (respective `User::loadUserByUsername()`) should throw an exception if no request is available. It does return an empty instance (resp. null) in some cases anyway. To safely use it like in the beforementioned example, there would be the need to check if the request stack contains a request beforehand which is somewhat hidden.

Sidenotes: The example is a from a Contao 3.5 + 4 environment. In general not using `BackendUser::getInstance()` might be the right thing to do.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by m-vo** [comment]
So I guess we should return `null` here instead:

https://github.com/contao/core-bundle/blob/f0a31a1a74b67899d0400085fa922971db0c1f2c/src/Resources/contao/library/Contao/User.php#L493-L496

**Comment by leofeyer** [comment]
This actually depends on whether having an empty request stack is a supported case or not. Since terminal42/contao-easy_themes#40 used to work before the change, I guess it is.

**Comment by aschempp** [comment]
> This actually depends on whether having an empty request stack is a supported case or not.

It absolutely is. It did work before, there was just no authenticated user. This must at least continue to work for `BackendUser::getInstance()`

**Comment by leofeyer** [comment]
Fixed in 5cd70f0199fe08c3b656b1ce432a66e88afbfd39.

**Comment by m-vo** [comment]
Looks good to me. Thanks @leofeyer.
