### ISSUE TITLE
show meta data also in download content element

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1459]
The download**s** content element automatically uses the stored meta data of each file. The download content element does not - it simply displays the file name as the link text and provides custom fields to override the link text and link title.

Since we have the "override meta data" functionality in place for single images on various places (text/image content element, news, events, …), maybe it makes sense to provide the same functionality for the download content element as well? i.e. it would automatically use the meta data and you can override it, if you so wish.

**Comment by leofeyer** [comment]
Implemented in dbb6d396a32fbd254e99d85e9a8be628eb5829ab and contao/installation-bundle@ca78d9dab92929726788194fad5cc271005a6f23.
