### ISSUE TITLE
search does not find anything, if you provide duplicate search phrases

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1460]
Reproduction on demo.contao.org:

1. Add the content "lorem lorem" in a page.
2. Rebuild the search index.
3. Go to the front end and search for `lorem lorem`.

Nothing will be found (with the default setting of "match all words").

Another reproduction and real life use case by which we noticed this issue:

1. Add the content "30 under 30" on a page.
2. Rebuild the search index.
3. Go to the front end and search for `30 under 30` or also just `30 30`.

Nothing will be found.

By contrast try the following searches:

* `30`
* `under 30`
* `30 under`

These search phrases will provide a result.

**Comment by fritzmg** [comment]
Other example: 

[`official demo website`](https://demo.contao.org/en/search.html?keywords=official+demo+website&query_type=and) vs. [`official demo website official`](https://demo.contao.org/en/search.html?keywords=official+demo+website&query_type=and)

**Comment by leofeyer** [comment]
Fixed in 491a32507303dc5fac0115b168f92f401f54a78d.
