### ISSUE TITLE
search highlighting misses words

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1461]
The [starting page](https://demo.contao.org/en/) of the official contao demo contains the following content for example:

> Welcome to the **official demo website** of the open source content managment system Contao. 

However, if you search for [`official demo website`](https://demo.contao.org/en/search.html?keywords=official+demo+website&query_type=and), only the words `official` and `website` will be highlighted in that sentence. The word `demo` will not be highlighted.

**Comment by leofeyer** [comment]
Fixed in b27a3aaf27d8c96457704b80e1b09a7153accc66.
