### ISSUE TITLE
leave the title of the link empty if not set in meta-data (ce_gallery)

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1467]
if you don't set a title in the meta-data the filename is used instead.
I don't think this is usefull at all and it doesn't happen for ce_image.
To reproduce: hover over the thumbnails of the gallery-element or open the colorbox https://demo.contao.org/en/media-elements/articles/media-elements.html

**Comment by leofeyer** [comment]
As discussed in Mumble on May 17th, we want to leave the title empty so it is consistent with the text and image elements.

**Comment by leofeyer** [comment]
Implemented in 7e18359400046188f6eb26a608c547323a946d13.
