### ISSUE TITLE
Feature: Test Mail aus Backend versenden

### ISSUE THREAD

**Issue by contaoacademy** [contao/core-bundle#1469]
Es wäre hilfreich, wenn man per Klick eine Test-Mail versenden könnte um zu überprüfen, ob die SMTP-Einstellungen korrekt gesetzt sind bzw. ob der Server die Mails versenden kann.

Kann gerne unter System-Wartung sein oder evtl. ist das auch besser im Contao Manager aufgehoben.

**Comment by Toflar** [comment]
Das müsste in den Manager, weil es eine Kommandozeilen-Operation ist:

```
vendor/bin/contao-console swiftmailer:email:send --help
```

**Comment by aschempp** [comment]
Ich hätte etwas bedenken über den Manager freien E-Mail Versand zu erlauben. Würde es reichen wenn eine definierte E-Mail an den Systemadmin versendet werden kann?

**Comment by Toflar** [comment]
Naja, du musst ja eingeloggt sein. Aber vordefiniert einfach als Testmail, ist sicher eine gute Option. Das würde ja die Anforderung abdecken :)

**Comment by leofeyer** [comment]
Kann ich das Ticket dann zum Manager verschieben?

**Comment by aschempp** [comment]
Ich denke ein neues Ticket mit verweis ist sinnvoller…
