### ISSUE TITLE
unexpected behaviour with svg-images and image-sizes

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1472]
i noticed that when i use image-sizes in combination with svg-images
additional svg's in the ```srcset``` are created under ```assets/images/``` 
```html
<img src="assets/images/4/foo-b4a0c460.svg"
 srcset="assets/images/4/foo-b4a0c460.svg 1x, assets/images/3/foo-eeec80d9.svg 2x" 
width="250" height="250" alt="foo" itemprop="image">
```
The svg's i am using do not contain ```width/height``` attributes - only the ```viewbox``` attribute and i did not set any ```important-part``` for them in the filemanager.
I would expect contao to just set the width and height on the ```<img>``` and not create additional svg's with contained width/height attributes.

Of course i could just use a different image-size without pixel-density descriptors but i have mixed filetypes in a gallery so that's not really an option.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
I’m not sure what’s the correct way to solve this. Should we just hardcode to not generate different densities for SVG images in the `PictureGenerator`?

**Comment by leofeyer** [comment]
I think we should. It does not make much sense, does it?

**Comment by ausi** [comment]
We should move this issue to contao/image then.
