### ISSUE TITLE
%locale% must not be in parameters.yml

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#148]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/70) by @aschempp
Wednesday Mar 18, 2015 at 18:07 GMT

We have discussed this before. The `%locale%` is the system fallback for everything like language files and therefore should not be configurable by the user. Otherwise if I choose to use `de` as default, modules without a german translation would not provide any labels.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Mar 19, 2015 at 10:32 GMT

This is actually how Symfony does it.

https://github.com/symfony/symfony-standard/blob/2.7/app/config/parameters.yml.dist#L17

If someone wants to change it, why would we stop him?

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Mar 19, 2015 at 14:04 GMT

We should not ask for it in the parameters.yml.dist because it's likely german natives will set it to "de" which will likely break lots of extensions and maybe the core too.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Mar 19, 2015 at 14:34 GMT

Why would it? And why not follow the Symfony standard here?

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Mar 19, 2015 at 14:39 GMT

We've discussed this before. The Contao default locale always was "en". Every module will/should provide an english language folder as the fallback, even if the content is german. If I set the locale to "fr", the backend would not have any labels at all (if FR is not shipped with the core).

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Mar 19, 2015 at 14:47 GMT

We cannot influence the settings anyway, because it is part of the standard edition and people might as well use the Symfony standard edition with the locale being configurable. Therefore we should follow the Symfony standards.

> If I set the locale to "fr", the backend would not have any labels at all

That's probably not true, because English is always loaded as fallback language.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Mar 19, 2015 at 14:48 GMT

> That's probably not true, because English is always loaded as fallback language.

That's exactly the point, it is NOT. At least not for the Symfony translator, and addition that configuration but not using it our own would make no sense at all.

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Mar 19, 2015 at 14:51 GMT

We are not using the Symfony translator yet. And in Contao, English is always loaded as fallback language in case there are missing labels. But we can discuss this on Mumble if you want.

**Comment by importer** [comment]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @aschempp
Thursday Mar 19, 2015 at 19:38 GMT

Yes please.

**Comment by leofeyer** [comment]
Fixed in contao/standard-edition@8ddb970ad3257f436b24cc54cdedf6e973ed3a44.
