### ISSUE TITLE
Bildgrößen -> Sizes Attr. full width

### ISSUE THREAD

**Issue by Metis77** [contao/core-bundle#1484]
In the backend setting for the ImageSizesSets the image sizes attribute should become full width.
Usually the rules there tend to be a little longer.

![screen](https://user-images.githubusercontent.com/1408361/38865685-db49929c-423e-11e8-8350-ddcaa36a1e66.png)

**Comment by fritzmg** [comment]
"Usually"? I never had that problem - though admittedly I never cared to optimize images for different viewport widths _that_ much ;).

**Comment by Metis77** [comment]
@fritzmg  This is of course only relevant for people that actually use it – obviously ;)

But if used, the rules tend to be longer. 
In the example above are "only" three rules.
In that case roughly targeting phone, tablet, desktop.

**Comment by ausi** [comment]
> Usually the rules there tend to be a little longer.

I agree. Just checked some of my image sizes and for most of them the sizes attributes didn’t fit in the half-width input field.

**Comment by leofeyer** [comment]
Changed in 4f06d8b8af90a373fcb5cac599f7f754551ce26d.
