### ISSUE TITLE
Image Compression Quality

### ISSUE THREAD

**Issue by Metis77** [contao/core-bundle#1488]
The image compression of Contao generates rather big files. 
SEO test tools complain about this a lot. And in some projects Google Page Speed is what customers use to benchmark the optimisation of their websites.

I am also thinking that images converted by contao could be much smaller, with same visible quality.

Google Page Speed suggests to use:
`convert puzzle.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB puzzle_converted.jpg`
found at:
https://developers.google.com/speed/docs/insights/OptimizeImages

I downloaded images converted by contao and used the above command, with same quality setting of course.
Images become indeed much smaller, and I could not see any difference.
Same amount of artifacts in surfaces and on borders.

What do you think?
Would it be possible to change this anyway?

**Comment by fritzmg** [comment]
> The image compression of Contao generates rather big files.

Contao does not have it's own JPEG compression library. 

Depending on your server environment either GD, Imagick oder Gmagick is in use. You can find out which library is in use in your installation via the command line - but I forgot the command yet again. I am sure @ausi can tell you though ;)

**Comment by fritzmg** [comment]
> @fritzmg change the command for converting form the one it is now, to

There is no command like that in Contao. Read the Google Page Speed again: `convert` referes to a command line utility from Image Magick: https://www.imagemagick.org/script/convert.php

**Comment by fritzmg** [comment]
You can change the JPEG quality in the `config.yml`:
```
contao:
    image:
        imagine_options:
            jpeg_quality: 80
```
Default is `80`.

Use the following command to find out which image processing library is in use on your server:
```
vendor/bin/contao-console debug:container contao.image.imagine
```

**Comment by Metis77** [comment]
I played around with those image Quality settings.
As written above, this is not about the quality setting, but about the compression of the result.
It can be much better, with same quality. 
And also much better while maintaining same visible quality.

ImageMagik is used. Thank you for the command to test this.
![contao image imagine](https://user-images.githubusercontent.com/1408361/39000460-6a188a58-43f4-11e8-94e2-34c1ef1889a7.png)


Just test to see the difference in since, while not seeing visible difference.

I believe, if this can be improved, it should be improved. And therefor stop google page speed complaining about contao's little image compression.

**Comment by Toflar** [comment]
`jpeg_quality` does exactly that, it controls *compression* for jpeg images.

**Comment by fritzmg** [comment]
What Google Page Speed often complains about is the _optimization_ of PNGs and JPEGs. i.e. stripping header information for example.

@Metis77 please post what exactly Google Page Speed reported in your case.

**Comment by Metis77** [comment]
Ok let me try to explain. 
Maybe there is no room for improvement at all, but I hope there is.

This is not about helping me with an issue, **it is about further improving contao by default.**

### other solutions
Image Optimization is something several other tools do.
But using alike is expensive or not very comfortable.

- For example [Cloudflare](https://blog.cloudflare.com/introducing-polish-automatic-image-optimizati/) offers image optimization in its business plan.

- Optimization can be done manually with the great Mac tool  [imageoptim](https://imageoptim.com/mac ).
Give it a try. The results are much smaller than what contao generates. And a difference in Quality is not really visible. But in this case ImageMagick is not used.

- Also there is the [contao-tiny-compress-images](https://github.com/christianbarkowsky/contao-tiny-compress-images
) plugin that uses 3rd party image provider.

Room for optimizing Contao might be there.


### tests

In some tests I compared the contao resizing results with the simple command: 
`convert img-org.jpg -quality 80 img-simple.jpg` 
and the optimized version of the command that [google](https://developers.google.com/speed/docs/insights/OptimizeImages) suggest:
`convert img-org.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB img-optimized.jpg
`

I guess the first simple one, is what contao is doing right now.
Does anybody know?

I am aware that those commands are for the shell, but the PHP version should do the same.
I cant do those tests in PHP myself.

Now my test results:

#### Tests in Contao
To test this I resized the image stock.jpg in Contao.
Afterwards I optimized it on the shell with the command: 
`convert stock.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB stock-optimized.jpg`

<img width="627" alt="contao" src="https://user-images.githubusercontent.com/1408361/39013814-d5368ffa-4418-11e8-8148-9b723ad3c7e5.png">
As you see, there is a difference, not huge, but there is.

#### Tests on Linux & Mac
This is a test on server:
<img width="771" alt="imagick-linux" src="https://user-images.githubusercontent.com/1408361/39014035-78b657b4-4419-11e8-8c42-5ae950c2b88b.png">

And this on the mac:
<img width="918" alt="imagick-mac" src="https://user-images.githubusercontent.com/1408361/39014045-81a74694-4419-11e8-9531-4da72686f1e4.png">


the results imagick-simple.jpg were created with:
`convert img-org.jpg -quality 80 img-simple.jpg`

the results imagick-optimized.jpg were created with:
`convert img-org.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB img-optimized.jpg`
 

What do you think?

**Comment by Metis77** [comment]
>If you really care, there's more stuff to do like ...

@Toflar I know, but this ticket is really only about image compression. 


> maybe we can check if there are other flags we can set that improve the output a little 

Here are the options. 
those should also be available for the PHP extension.
But in this place they are better explained:
http://www.imagemagick.org/script/command-line-options.php#sampling-factor

And here generic PHP documentation:
http://php.net/imagick
Example using the setSamplingFactors PHP class.
http://php.net/manual/de/imagick.setsamplingfactors.php

I feel little pitty that I can only contribute by sharing links.
I would offer an pullrequest, If I could do PHP like a magician ;)

**Comment by Toflar** [comment]
I don't think imagine (the library we use) supports sampling factors, so that doesn't work.

**Comment by Metis77** [comment]
Ah ok ;/
I also could not find anything about further compression settings, like the samplingfactor, on the "imagine" library end.

**Comment by fritzmg** [comment]
Stripping works though - not sure if that's used already anyway?

**Comment by Toflar** [comment]
[Yes](https://github.com/contao/image/commit/a60e9bc4dcf48b0d8d44c1d1885900451e4c6087)

**Comment by Toflar** [comment]
We're not using `interlace` though, afaics. /cc @ausi

**Comment by fritzmg** [comment]
Imho interlace should not be used by default though. May be that should be configurable.

**Comment by ausi** [comment]
We do use `interlace`, see contao/image#24.
But it is also configurable, see https://github.com/contao/core-bundle/blob/c077941468e25b4d1247f1fbbe8915e04faf23eb/src/DependencyInjection/Configuration.php#L151

**Comment by Metis77** [comment]
> can you provide the link to the affected image and the original source image?

This can be tested on lots of pages.

like: https://www.hotel-des-artistes.de/nachrichten-archiv.html
or: https://www.terminal42.ch/de/flugplatz.html

If you donwload a JPEG an run `convert puzzle.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB puzzle_converted.jpg` you will see.

**Comment by Metis77** [comment]
>You need to test with the original image, not with the already processed image.

@fritzmg check my long comment above, the one with images.
There are detailed tests.

**Comment by fritzmg** [comment]
Your test showed that there is only a 0.7% change difference, which is negligible, isn't it?

**Comment by Metis77** [comment]
the result depends on image tested with.
first test shows a difference of .7%, right.
the other tests are around 10%.

**Comment by ausi** [comment]
I was not able to reproduce this with Contao 4.5.8. Using your command, my test file got 6.7% bigger. Using your command with `-quality 80` keeps the file at the same size, which make sense because Contao uses quality 80 by default.

The reason why it does not work correctly in your case is hard to find without more information about your setup and access to the original and to the converted image file.

**Comment by Metis77** [comment]
Ok I just reproduced my tests:
![ls](https://user-images.githubusercontent.com/1408361/39119147-71dad1c0-46eb-11e8-822d-cee66c8220ef.png)

Images can be found here:
a starting file gets cropped by contao to this file I call org.jpg:
https://contao4.derhaeuptling.com/org.jpg

After running `convert org.jpg -sampling-factor 4:2:0 -strip -quality 80 -interlace JPEG -colorspace sRGB optimiert.jpg` I from shell I geht this file:
https://contao4.derhaeuptling.com/optimiert.jpg

@ausi As you say, you get the same size: could it be, that php imagick runs an older / worse version of ImageMagic than that the CLI command convert I use from shell?
If yes, this would explain that I get reduced file size and you not. 
And the whole task would be redundant.

**Comment by fritzmg** [comment]
I did not quite understand your reproduction. Is org.jpg the original or already processed by Contao? If it was already processed - you need to test with the Original.

**Comment by Metis77** [comment]
@fritzmg Same tests, but starting from the same file.

Source image org.jpg got once cropped by contao -> opt-contao.jpg
And once cropped by convert on console -> opt-console.jpg
with command: `convert org.jpg -sampling-factor 4:2:0 -strip -quality 80 -interlace JPEG -colorspace sRGB -resize 2250 opt-console.jpg`

results:
![results](https://user-images.githubusercontent.com/1408361/39121570-574db744-46f2-11e8-9b76-14d20e5de390.png)

Both results have the same image dimensions.


### ImageMagic Versions
but as @ausi pointed out:  could it be, that php imagick runs an older / worse version of ImageMagic than the CLI command convert I use from shell?
If yes this would explain my differences , while @ausi seams to have no difference

I did compare it:
imagick: ![bildschirmfoto 2018-04-23 um 12 37 33](https://user-images.githubusercontent.com/1408361/39121874-4eae674a-46f3-11e8-8c80-f8a8920a26e5.png)

Convert on console:
![bildschirmfoto 2018-04-23 um 12 39 29](https://user-images.githubusercontent.com/1408361/39121913-6dfac3c8-46f3-11e8-8cfd-9aa46f0a51b7.png)

Not sure if this could make the difference.

**Comment by fritzmg** [comment]
Hm, well there is no difference. In both cases ImageMagick 6.8.9-9 Q16 is in use.

**Comment by ausi** [comment]
I was able to reproduce the issue with your test-file. It seems that if ImageMagick reads from a JPEG file, it keeps the sampling-factor setting as it is and does not use the default `4:2:0` (aka `2x2,1x1,1x1`).

We could add something like the following to the Resizer if we want to handle this case for Imagick and Gmagick ourself:

```php
if ($imagineImage instanceof Imagine\Imagick\Image) {
	$imagineImage->getImagick()->setSamplingFactors(['2x2', '1x1', '1x1']);
}
elseif ($imagineImage instanceof Imagine\Gmagick\Image) {
	$imagineImage->getGmagick()->setSamplingFactors(…?…);
}
```

Or make a pull request to Imagine to add the save option `sampling-factor`.

**Comment by Toflar** [comment]
Cool! The PR sounds - of course - better to me because then I can also benefit from it in other projects of mine that are not Contao related 😃 But it also means a bit more work.
BTW: Did you guys also check png files? I saw there's an extra PNG setting so maybe we should also have a sane default for that one?

**Comment by Metis77** [comment]
@ausi if I do a `convert org.png -sampling-factor 4:2:0 -strip -quality 80 -interlace JPEG -colorspace sRGB corpped-byConsole.png` the result is multiple times bigger, than what contao does.
But probably using `convert` is not the right way to compare this on the console.

**Comment by ausi** [comment]
Pull request: contao/contao#338

**Comment by leofeyer** [comment]
Thank you @ausi.
