### ISSUE TITLE
DSGVO und die Registrierung

### ISSUE THREAD

**Issue by christianbarkowsky** [contao/core-bundle#1491]
Im Zuge der neuen Datenschutzrichtlinie sollte es eine (optional) konfigurierbare Checkbox mit Link - zum bestätigen der AGB/Datenschutzerklärung bei der Registrierung geben (siehe Bildschirmfoto).

Alternativ einen HOOK zum hinzufügen eigener FormElemente (z.B. [extended-checkbox](https://github.com/christianbarkowsky/contao-extended-checkbox/tree/develop), ...)

<img width="564" alt="bildschirmfoto 2018-04-19 um 16 41 30" src="https://user-images.githubusercontent.com/1230547/38998783-9dc0c572-43f0-11e8-8589-488a430d564f.png">

**Comment by christianbarkowsky** [comment]
@leofeyer macht das nicht auch in der 4.4 LTS Sinn?

**Comment by christianbarkowsky** [comment]
Das ist richtig @aschempp - doch dem allgemeinen Benutzer - der das DCA nicht erweitern/anpassen kann - sollte hier entgegengekommen werden und der Arbeitsaufwand minimiert werden.

**Comment by christianbarkowsky** [comment]
Ich hab da mal was vorbereitet >> https://github.com/christianbarkowsky/contao-privacyconsent-bundle

**Comment by aschempp** [comment]
Und genau dafür gibt es Erweiterungen. 😉  Etwas dass sich die installieren können welche es benötigen, und dann kann es auch sehr anwenderspezifisch sein. Es kann 100 Erweiterungen für verschiedene Fälle geben, aber eine Core-Lösung sollte alle 100 Möglichkeiten abdecken, was ich für begrenzt sinnvoll halte.

**Comment by aschempp** [comment]
> macht das nicht auch in der 4.4 LTS Sinn?

Ausserdem wäre eine Erweiterung auch problemlos für ältere Versionen verfügbar, was bei Features im Core nicht geht 😉

**Comment by Toflar** [comment]
Aber nicht in der LTS, weil neues Feature. Und bevor das Argument "aber DSGVO" kommt: Ja, ich verstehe dass man gerne auf einer LTS und gleichzeitig DSGVO-optimiert unterwegs sein möchte. Aber in 6 Monaten kommt Gesetz XY und in weiteren 6 Monaten fällt dem Parlament ein dass Gesetz XY doch nicht so gut war, dann erfindet wer Technologie XY und Technologie X ist plötzlich nicht mehr wichtig usw. usf. Der Markt ändert sich ständig und wir ändern uns mit, aber immer schön brav nach Semantic Versioning. Alles andere endet in einem Scherbenhaufen. Wer nicht updaten will, kann die allermeisten Wünsche immer noch per Extension nachrüsten (lassen).

**Comment by leofeyer** [comment]
Das sehe ich anders. Die DSGVO ist nicht irgendein Gesetz, sondern die bisher umfassendste Neuordnung des Datenschutzes in Europa. Andere CMS haben dafür extra Gremien gebildet, die sich um die Integration kümmern (siehe z.B. https://typo3.org/community/teams/typo3-development/initiatives/gdpr/).

Die DSGVO bedeutet für uns alle teilweise erhebliche Mehrarbeit und wir als Core-Entwickler sollten dafür sorgen, den Leuten einen Teil dieser Mehrarbeit abzunehmen anstatt sie mit Aussagen wie "kann man sich ja per Extension nachrüsten lassen" abzuspeisen! Vor allem weil nur wenige Anpassungen notwendig sind, um den Core DSGVO-ready zu machen.

**Comment by Toflar** [comment]
Ich habe nicht gesagt, die Extension darf nicht von uns sein. Selbstverständlich kann ein `contao/gdpr-bundle` o.ä. zur Verfügung gestellt werden. Aber die 4.4 kriegt auf keinen Fall neue Features!

**Comment by leofeyer** [comment]
Wenn das System nicht mehr mit der aktuellen Gesetzgebung kompatibel ist, muss das geändert werden. Ich verstehe nicht wieso man da überhaupt eine “Bug oder Feature”-Diskussion führen muss.

**Comment by leofeyer** [comment]
Nach aktuellem Stand ist eine Pflicht-Checkbox für die Registrierung nicht notwendig, daher schließe ich das Ticket.

**Comment by fritzmg** [comment]
Naja - außer man möchte die eingegebenen Daten für mehrere, optionale Zwecke verwenden. Wie zum Beispiel Weiterverkauf der Daten, Zustellung von Werbermaterial per Post, etc. Das dürfte man natürlich nur bei den Mitgliedern machen, die dem zugestimmt haben. So etwas könnte man natürlich im Registrierungsformular machen.

Jedoch geht das ja schon per DCA Erweiterung, in sofern muss das nicht in den Core :).
