### ISSUE TITLE
Problem when maintenance mode is enabled

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#1492]
After updating to Contao 4.4.18 still the same behaviour as described in Ticket #1370.

**Comment by joeherold** [comment]
I realized, that the {{ua::class}} token also is empty when maintaince mode is activated. Tested in Contao 4.5.8

**Comment by leofeyer** [comment]
As discussed in Mumble on May 17th, @Toflar will check why the PR does not work.

**Comment by Toflar** [comment]
Okay, I have a reproducible use case and the source now but no idea why it happens and how to fix it yet. I'm pretty sure it's not a Contao bug though.

**Comment by joeherold** [comment]
@Toflar: hahahaha

**Comment by joeherold** [comment]
@Toflar: I am just guessing, but I realized, that the „global $objPage“ is not available in insert Tags.

**Comment by Toflar** [comment]
No, it‘s related to IP handling and routing but I‘ll need a quiet minute to look into it :)

**Comment by aschempp** [comment]
> I‘ll need a quiet minute to look into it :)

Which will be hard, given the fact that they are tearing up the streets in front of our office (for the next 6 months) 😡

**Comment by Toflar** [comment]
After 5h of debugging together with @aschempp, I think we found the source of the problem in Symfony. Here we go: https://github.com/symfony/symfony/pull/27309

**Comment by leofeyer** [comment]
As an intermediate fix, I have whitelisted local requests in c42899bb57566b414dbaf8a1719e028eac2befdc as proposed in #1370. This will not work for Varnish or other "external" HTTP caches, but regarding this we can only wait for symfony/symfony#27309 to get merged.
