### ISSUE TITLE
duplicate IDs for formfields

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1493]
In #957 there is dicussion about same form multiple times on a page which causes invalid html because of duplicate IDs.

I noticed, that the ce_**comment**-form and the mod_**registration**-form
both use ```id="ctrl_email"```
whereas the mod_unsubscribe-form uses something like ```id="ctrl_email_xy"``` (xy being the module-ID)

It would be nice if i could use both forms on the same page and still have valid html.

**Comment by m-vo** [comment]
True, but there are the same problems like in the referenced ticket that changing them would imply a BC break. 

You can still alter the template. Maybe this is a known limitation, then.

**Comment by fritzmg** [comment]
Not being able to put two completely different forms on the same page is rather weird though.

**Comment by asaage** [comment]
The fields are not inside the ce_comment-/mod_registration Template.
I'm not quite shure but i think adding a unique id somewhere [here](https://github.com/contao/comments-bundle/blob/master/src/Resources/contao/classes/Comments.php#L195) could work.
I don't see why this should be a BCbreak (except for possible css-related things).

**Comment by asaage** [comment]
The same problem exists for ```id="ctrl_website"``` if that is activated in the registration-module.

**Comment by leofeyer** [comment]
Adding the module ID to the registration form and the parent ID to the comments form fixes only 99% of the cases (which is good enough I guess). If the parent ID of the comments form happens to be the same as the module ID of the registration form, the problem still exists.

**Comment by leofeyer** [comment]
Fixed in 9d87aa218258b64960aa8c8495eb243c87ab37f3 and contao/comments-bundle@ded4b339373bcb17c922842f24da520b7372c0ff.

**Comment by frontendschlampe** [comment]
May there's a possibility to add a special prefix each module, e.g. nXXX for newsletter, cXXX for comments and fXXX for forms? But I think, it should be a problem, because we have only numeric ID's in Contao, isn't it?

**Comment by leofeyer** [comment]
A prefix would not solve the problem, either, if there were two comment forms on the same page.

**Comment by fritzmg** [comment]
I agree that this is good enough. Having two comment forms with the same parent would be a weird setup anyway, wouldn't it.

**Comment by frontendschlampe** [comment]
> A prefix would not solve the problem, either, if there were two comment forms on the same page.

I think 2 comment modules will have different ID's because they're 2 different modules. With prefix you can solve the problem, that a form and a comment module will not have the same ID.

But no problem ... it's ok like it is. If I have the case, that I have 2 modules with same ID I can change the ID of one module.
