### ISSUE TITLE
Invalid RequestToken mit aktivertem Server-Cache und Client-Cache

### ISSUE THREAD

**Issue by cboelter** [contao/core-bundle#1498]
Wenn ich in meiner Contao-Installation den Server- und Client-Cache aktiviere, habe ich auf diversen Seiten mit Formularen hin und wieder das Problem das ich eine "Invalid RequestToken" meldung erhalte. 
Für mich sieht es so aus, als wenn der RequestToken gecached wird. Wenn ich die Formularseite einmal in zwei verschiedenen Browsern öffne (Safari / Firefox) kann ich das Formular im ersten Browser einwandfrei abschicken, im anderen erhalte ich die "Invalid RequestToken" meldung.
Wenn ich jetzt jedoch den RequestToken aus dem ersten Browser in das Formular des zweiten kopiere, wird auch dieses Formular ohne Probleme abgeschickt.
Wenn ich den Cache komplett deaktiviere, funktionieren alle Formulare ohne Probleme.

Es sit eine Contao 4.4.18 Installation auf NGINX bei Timmehosting.

**Comment by aschempp** [comment]
Es gibt nur eine Erklärung: Dein Kunde nutzt freie Open Source Software, es gibt keine Garantie für irgendwelche Funktionen. Wenn er das Problem dringend gelöst haben muss kann er jederzeit einen Entwickler bezahlen der das Problem analysiert und behebt, sowohl bei Ihm als auch für uns alle. Ansonsten muss er warten bis jemand anderes "Zeit und Lust" hat das kostenlos/in seiner Freizeit "für ihn" zu tun…

**Comment by cboelter** [comment]
@Toflar @aschempp mir ist gerade etwas schleierhaft, warum auf meine eigentlich sehr nette und absolut nicht fordernde Frage so reagiert wird. Wenn es falsch rübergekommen ist, tut es mir leid. 
Ich dachte nur das es vllt. eine technische Erklärung gibt, die es uns "einfachen Leuten" beim Kunden etwas einfacher macht.

**Comment by leofeyer** [comment]
> /cc @aschempp scheinbar hat dein PR das Problem noch nicht gelöst.

Scheint ganz so (siehe #1492). Wir besprechen das Thema beim heutigen Call und halten die Ergebnisse in #1492 fest, daher schließe ich dieses Ticket als Duplikat.

**Comment by cboelter** [comment]
Ich habe das jetzt in einer Installation wo die Korrekturen aus https://github.com/contao/core-bundle/issues/1492 enthalten sind einmal ausprobiert. Leider besteht das Problem mit den RequestToken immer noch :-(
