### ISSUE TITLE
Add a checkbox for module newsletter subscribe

### ISSUE THREAD

**Issue by stefan-at-work** [contao/core-bundle#1499]
as a result of the DSGVO we need an additional note such as "I agree that my personal data will be stored...". Therefor it will be great, when we integrate a mandatoty checkbox and the possibility to add an individual text.

**Comment by asaage** [comment]
related: https://github.com/contao/core-bundle/issues/1491

**Comment by leofeyer** [comment]
> we need an additional note such as "I agree that my personal data will be stored...".

Where did you find this?

**Comment by asaage** [comment]
Es ist zumindest empfohlen:
https://blog-it-recht.de/2017/03/27/sind-das-double-opt-und-eine-checkbox-im-e-mail-marketing-nun-erforderlich-oder-nicht/

**Comment by stefan-at-work** [comment]
§13 der DSGVO kann man auch anders auslegen. Siehe
[](https://onetoone.de/de/artikel/checkliste-sechs-punkte-die-sie-f%C3%BCr-eine-eu-dsgvo-konforme-newsletter-anmeldung-beachten)

**Comment by leofeyer** [comment]
Ja, das ist halt das Problem mit der DSGVO. Niemand weiß es definitiv, solange es keine Urteile gibt.

**Comment by m-vo** [comment]
Trotzdem sollte mMn eine solche Funktionalität im Core nur nachgerüstet werden, wenn sie für alle notwendig ist (d.h. wenn die rechtliche Notwendigkeit irgendwann mal bestätigt sein sollte) oder wenn es für alle die, die sie nachrüsten wollen/müssen sonst einen unvertretbar großen Aufwand bedeuten würde.

**Comment by leofeyer** [comment]
Ich habe in contao/newsletter-bundle@26cfb4d40352fa962ac44e39d07a9af91160a876 ein Textfeld hinzugefügt, in dem man die notwendigen DSGVO-Informationen für das Abonnieren hinterlegen kann (Zusammenfassung, Hinweis auf Abmeldung, Link zur Datenschutzerklärung).
