### ISSUE TITLE
Feature: 4.x Event count function

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1501]
Hello, 

I know this issue we already had but, unfortunately, the feature wasn't created. 

It would be nice to have the same function like in the news module to count events. I think that it's easy to implement it. With this feature would be possible to use the count logic of another extensions like Rocksolid columns. Bellow the code to demonstrate what I would like to do with the events to influence their appearance. 

Few customers of Rocksolid have asked for it.

Thank you. 

```
<?php
    $config = array(
        'large' => array('-large-col-3-1 -large-first', '-large-col-3-1', '-large-col-3-1 -large-last'),
        'medium' => array('-medium-col-2-1 -medium-first', '-medium-col-2-1 -medium-last'),
        'small' => array('-small-col-1-1 -small-first -small-last'),
    );
    $classes = array('rs-column');
    foreach ($config as $name => $media) {
        $classes[] = $media[($this->count - 1) % count($media)];
        if ($this->count - 1 < count($media)) {
            $classes[] = '-' . $name . '-first-row';
        }
    }
    $this->class .= ' ' . implode(' ', $classes);
?>
```

**Comment by leofeyer** [comment]
See https://github.com/contao/core/issues/7825.
