### ISSUE TITLE
4.x: Unicode does not work properly in the links

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1502]
The unicode for _**í**_ does not work properly in the links. See https://www.kcrehlo.cz/cs/projekt/děti-z-dětského-domova-ve-setřekově-v-úst%C3%AD-nad-labem-na-návštěvě

**Comment by fritzmg** [comment]
Looks fine to me? What exactly is the problem?

**Comment by jankout** [comment]
in the link it does not work.

**Comment by fritzmg** [comment]
My screenshot is from the link your provided ;). `í` is properly delivered in the output.

**Comment by ausi** [comment]
@jankout Do you meant the “í” is not displayed in the address bar of Safari?

![safari-url-screenshot](https://user-images.githubusercontent.com/367169/39517344-e6d7cc74-4dff-11e8-94d3-8df55ce5f929.png)

**Comment by jankout** [comment]
yes, exactly.

**Comment by fritzmg** [comment]
That's a problem of Safari then. This is the fully encoded URL that Contao actually generates: 

https://www.kcrehlo.cz/cs/projekt/d%C4%9Bti-z-d%C4%9Btsk%C3%A9ho-domova-ve-set%C5%99ekov%C4%9B-v-%C3%BAst%C3%AD-nad-labem-na-n%C3%A1v%C5%A1t%C4%9Bv%C4%9B

Contao cannot control how the browser displays this URL in its address bar.
