### ISSUE TITLE
Element schützen für erlaubte Mitgliedergruppen klappt nicht

### ISSUE THREAD

**Issue by delirius** [contao/core-bundle#1503]
Ich möchte gerne eine Textelement nur angemeldeten Mitglieder zeigen. Es wird jedoch gar nicht mehr angezeigt. Contao 4.4.18
![image](https://user-images.githubusercontent.com/2039398/39386452-f7551fea-4a74-11e8-8e98-be7399951c80.png)

**Comment by fritzmg** [comment]
Funktioniert in der Contao Online Demo einwandfrei.

**Comment by m-vo** [comment]
(die ist aber auch eine 4.5 - ohne zu sagen, dass ich das bestätigen kann)

**Comment by fritzmg** [comment]
Funktioniert auch in einer Contao 4.4.18 Installation einwandfrei.

**Comment by delirius** [comment]
Ups, mein Fehler. Mein Testmitglied war nicht der entsprechenden Gruppe zugewiesen.
