### ISSUE TITLE
DropZone cannot handle errors

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1506]
If `$this->blnHasError` is set to true for `Contao\DropZone` during `uploadTo(…)` for example, there will simply be a `500` response and the error will not be visible in the DropZone. Instead it will show the following:

![dropzone-error](https://user-images.githubusercontent.com/4970961/39418798-a406ad42-4c5c-11e8-8186-7c4d94d17c6f.png)

In this example I simulated a file with an invalid file name that would trigger
```php
// Invalid file name
if (!\Validator::isValidFileName($file['name']))
{
	\Message::addError($GLOBALS['TL_LANG']['ERR']['filename']);
	$this->blnHasError = true;
}
```
within `FileUpload::uploadTo`. This can be fixed by adding
```diff
	// Redirect or reload
	if (!$objUploader->hasError())
	{
		if ($blnIsAjax)
		{
			throw new ResponseException(new Response(\Message::generateUnwrapped(), 201));
		}

		// Do not purge the html folder (see #2898)
		if (isset($_POST['uploadNback']) && !$objUploader->hasResized())
		{
			\Message::reset();
			$this->redirect($this->getReferer());
		}

		$this->reload();
	}
+	elseif ($blnIsAjax)
+	{
+		throw new ResponseException(new Response(\Message::generateUnwrapped(), 500));
+	}
```
in `DC_Folder::move`. However, then it will still look like this:

![dropzone-error-2](https://user-images.githubusercontent.com/4970961/39418923-75ec1eaa-4c5d-11e8-86b2-3cdff58caacc.png)

Since the `Message` class automatically wraps the messages with HTML and DropZone expects the server response to be pure text.

**Comment by leofeyer** [comment]
See #1506.
