### ISSUE TITLE
Kick all deprecated things for 4.0

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#151]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/73) by @Toflar
Thursday Mar 19, 2015 at 14:03 GMT

We have tons of `@deprecated` statements that have been added in version 2 or 3 already, those methods/classes should be dropped in 4.0 :)

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Thursday Mar 19, 2015 at 15:22 GMT

Fine with me, I guess. Would have to take a detailed look though.

**Comment by importer** [comment]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @Toflar
Thursday Mar 19, 2015 at 15:24 GMT

Would be pretty helpful because then all `@deprecated` hints are related to "from version 3 to version 4".

**Comment by importer** [comment]
> <a href="https://github.com/discordier"><img src="https://avatars.githubusercontent.com/u/940331?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @discordier
Sunday Mar 22, 2015 at 02:04 GMT

I'd love to see a lot to disappear.

**Comment by leofeyer** [comment]
I have searched for `backwards compatibility` and got about 160 results. Not all of them are things to be removed though. I therefore suggest to do the following:

 - Review each result to find the stuff to be remove.
 - Replace the `backwards compatibility` comment with `deprecated, to be removed in Contao 5.0`.
 - Then in Contao 5, we can eventually remove the stuff.

What do you think?

**Comment by aschempp** [comment]
Sounds reasonable. Should we add this for our discussion to go through the stuff?

**Comment by leofeyer** [comment]
If there are no objections, we don't need to discuss it IMHO.

**Comment by discordier** [comment]
I think all BC layers introduced in C3 to be compatible with C2 shall be removed in C4, C2 is simply outdated.
Everything that got introduced in C3.X shall be marked deprecated to be removed in C5.

IMO we also should backport the deprecated parts, which got introduced in the 3.X series for bc, to C3.5 code so other developers will have the time to adjust.

**Comment by leofeyer** [comment]
Closed in favor of #260.
