### ISSUE TITLE
Reverse Proxy: httpHost is appended to httpXForwardedHost

### ISSUE THREAD

**Issue by binarious** [contao/core-bundle#1511]
I'm having an issue with the following feature:
https://github.com/contao/core-bundle/blob/fa05410fbd75cca7655599e59972475fe371ca0e/src/Resources/contao/library/Contao/Environment.php#L335-L347

When used with a reverse proxy, this results in `https://mypublichost.de/myinternalhost.de` instead of the expected `https://mypublichost.de`. Is there a way to prevent this?

Contao: 4.4.18, PHP: 7.1.16

**Comment by leofeyer** [comment]
Please refer to the [forums](https://community.contao.org/de/) for this kind of question. If you search for "sslProxyDomain", you will find existing threads.

**Comment by binarious** [comment]
It's not a question, it's a bug report that the host gets appended when using a reverse proxy. 

I was just asking for a workaround and also found one in https://github.com/contao/core-bundle/issues/895.  The forum wasn't helpful either. There's just [one thread](https://community.contao.org/de/showthread.php?67525-4-4-2-Nach-Installation-mit-Contao-Manager-keine-Backendbenutzung-per-https-m%C3%B6glich&highlight=sslProxyDomain).
