### ISSUE TITLE
Feature: Internal redirect - datapicker for Events, News, FAQ

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#1513]
It would be great when the datapicker could work for Events, News and FAQ for the internal redirect (as page type). 

<img width="1426" alt="internal redirect" src="https://user-images.githubusercontent.com/3715050/39623414-d41216e8-4f95-11e8-867b-288621ccc61f.png">

**Comment by leofeyer** [comment]
Implemented in b33717c1a4bd5e6d76251fbb5d5ca378bd9df974.
