### ISSUE TITLE
broken alias auto generation when using custom validAliasCharacters setting

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1514]
__Reproduction:__

1. Log into the Contao Demo.
2. Go to the site structure and edit the website root settings.
3. Set __Valid alias characters__ to _ASCII numbers and lowercase letters_ and save.
4. Go to the site structure and add a new page within the website root.
5. Set the page type to _External redirect_ for example (without filling the _Alias_).

The __Page alias__ will be filled with `-XX`. Expected behaviour would be for it to stay empty (as is the case when you leave the __Valid alias characters__ setting empty).

/cc @ausi

**Comment by leofeyer** [comment]
Why should the alias remain empty if you explicitly require ASCII numbers and lowercase letters?

**Comment by fritzmg** [comment]
Compare the following reproductions:

1. Log into the Contao Demo.
2. Go to the site structure and add a new page within the website root.
3. Set the page type to _External redirect_ for example (without filling the _Alias_).

The Alias stays empty, this is the expected behavior, as the alias cannot (and should not be) filled with anything, since you haven't saved the page yet.

1. Log into the Contao Demo.
2. Go to the site structure and edit the website root settings.
3. Set __Valid alias characters__ to _ASCII numbers and lowercase letters_ and save.
4. Go to the site structure and add a new page within the website root.
5. Set the page type to _External redirect_ for example (without filling the _Alias_).

The alias is now filled with `-41` for example.

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by leofeyer** [comment]
I still cannot reproduce this. Maybe its me. 😄 

https://www.dropbox.com/s/9nvyh8jwbgscg8e/1514.mp4?dl=0

What did I not do?

**Comment by xchs** [comment]
I cannot reproduce it either.

**Comment by fritzmg** [comment]
Ok, this only happens if there is a page with an _empty alias_ in the site structure - which is an unusual case. It's not actually related to the `validAliasCharacters` setting.

See the following video: https://youtu.be/-CD_oRz0Dxs

There is another bug: if you switch the page type, but don't save, the page will remain in the site structure without an alias or title or url.

**Comment by leofeyer** [comment]
That makes sense then, because if the alias exist (the empty string in this case), Contao appends the page ID.

https://github.com/contao/core-bundle/blob/8a38ecbe5fc7d6860034f77d0eb555a76c56b92b/src/Resources/contao/dca/tl_page.php#L1086

**Comment by fritzmg** [comment]
Yep. But should such "empty" objects remain in the database? Usually such entries are cleaned, e.g. when you create a new record but then go back without saving. In this case the aren't deleted because switching the `type` "saves" them.

**Comment by leofeyer** [comment]
They should not of course, however we cannot really prevent this the way the DCA is designed.
