### ISSUE TITLE
Contao error page is shown instead of Symfony one in dev mode

### ISSUE THREAD

**Issue by christian-kolb** [contao/core-bundle#1517]
I've installed the contao core-bundle into a symfony project and used the setup as described in the README. When building a Contao module and running into an exception (in dev mode app_dev.php), the Contao error page is shown instead of the Symfony one.

- Symfony: 3.4.6
- Contao 4.4.18

Is there a special setting that has to be set or is this simply a bug?

**Comment by bytehead** [comment]
You can disable `pretty_error_screens` in `DEV` mode:
```
# config_dev.yml
contao.pretty_error_screens: false
```

**Comment by christian-kolb** [comment]
That works! Thanks a lot.
Is this documented somewhere?
