### ISSUE TITLE
Remove the changelog view in backend

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#152]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/74) by @aschempp
Friday Mar 20, 2015 at 07:57 GMT

I think we should get rid of this "feature". According to @leofeyer people use it to see what changed **after** a live-update. I think that's totally wrong, because it would be way more useful then to check **before** a live-update, but thats not possible.

We could keep the icon/link but simply point it to https://contao.org/de/changelog.html

**Comment by importer** [comment]
> <a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @Toflar
Friday Mar 20, 2015 at 11:34 GMT

:+1: It's not something that belongs to a CMS anyway^^

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Friday Mar 20, 2015 at 12:28 GMT

Full ACK.

**Comment by importer** [comment]
> <a href="https://github.com/xchs"><img src="https://avatars.githubusercontent.com/u/1218766?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @xchs
Friday Mar 20, 2015 at 17:06 GMT

> We could keep the icon/link but simply point it to https://contao.org/de/changelog.html

If necessary, we should point it to https://contao.org/changelog.html (i.e. without the language string as first URL parameter), since you will be forwarded automatically depending on the browser language.

**Comment by leofeyer** [comment]
Removed in 829da14db4dc41fc8f7229cebc67e3653a30487b.

**Comment by aschempp** [comment]
Didn't we intend to add a link to contao.org?

**Comment by leofeyer** [comment]
> If necessary, we should point it to

I don't think it is necessary. People should read the release announcements before updating, and the announcement will contain links to the change log (and the diff view, the milestone etc.).
