### ISSUE TITLE
"Systemwartung » XML neu schreiben" generiert in der Dev-Umgebung URL´s inklusive 'app_dev.php'

### ISSUE THREAD

**Issue by OMOSde** [contao/core-bundle#1520]
Schritte zur Nachverfolgung:

» Generierung einer XML-Sitemap im Startpunkt der Webseite einrichten
» in der Dev-Umgebung per Systemwartung die XML-Dateien neu schreiben lassen
» die Sitemap unter share enthält in den URL´s nun 'app_dev.php'-Fragmente

» in die Contao-Demo auf demo.contao.org konnte ich mich im Backend nicht einloggen (als k.jones)
» Contao 4.4.18 (auf Symfony 3.4.6)
» getestet in 2 Projekten

**Comment by leofeyer** [comment]
Behoben in 6f5a55f3506155280cedc901326b3e0d66d20ea9.
