### ISSUE TITLE
Mistake in inserttag breaks frontend page

### ISSUE THREAD

**Issue by sleitz** [contao/core-bundle#1521]
Sometimes Contao users make mistakes. We had a user recently who entered the inserttag

```
{{link_url::}}
```

As you can see, he forgot the ID. That can happen. But the frontend immediately issues an HTTP error 500 when accessing the page which contains the inserttag. No other pages are affected.

> Keinen Startpunkt gefunden
> Was ist das Problem?
> Es gibt keinen Startpunkt einer Webseite, der zu der angefragten Sprache und/oder Domain passt.
> 
> Wie kann ich das Problem lösen?
> Wenn Sie explizit eine Sprache gesetzt haben, gehen Sie zur Startseite und sehen Sie, ob Sie  automatisch weitergeleitet werden. Andernfalls kontaktieren Sie den Webmaster und informieren Sie ihn über das Problem.

Not only does the message not make any sense in this situation - there should not be any error in my opinion. Please only render an empty string for broken inserttags.

**Comment by leofeyer** [comment]
I could not reproduce this in the online demo. The tag was simply ignored and no error page was shown.

Can you reproduce it in the online demo?

**Comment by sleitz** [comment]
I was not able to reproduce it in the online demo. But it is reproducible in the affected installation. Online demo is 4.5, affected one is 4.4. Not that there should be a lot of potential in that difference.

**Comment by sleitz** [comment]
It is also not reproducible in any of our other 4.4 installations I tested so far. Which is weird. I'll see if I can dig up a distinction between them.

**Comment by leofeyer** [comment]
I guess it is not a Contao bug then. But let me know what you find, ok?

**Comment by sleitz** [comment]
We invested some time to reproduce this. It is possible to provoke the issue, but only in very rare cases which should not ever happen in a regular Contao instance.

The error message will occur if there are orphaned pages in `tl_page`. Orphaned meaning they use a `pid` which has no matching `id` in the same table.

The instance in which this occured originally is quite old and I'm fairly sure the orphaned entries were not caused by backend interaction but by manual db queries of a web developer in old times. I can't see any immediate issues within Contao.

If one nevertheless would want to prevent this error, one or two things could help:

 * Explicitly change the behaviour of internal methods in order not to stumble over orphaned pages
 * Include checks inside Contao which test database health and monitor orphans and other irregularities
 * Introduce database foreign key constraints (which is more of a long-term project)
