### ISSUE TITLE
Custom layout sections order

### ISSUE THREAD

**Issue by bekanntmacher** [contao/core-bundle#1529]
Aktuell werden eigene Layout Bereiche in der main-Spalte am Schluss angezeigt. Schön wäre, wenn die Reihenfolge analog der inkludierten Module übernommen werden könnte.

Aktuell:
<img width="1244" alt="banners_and_alerts_und_themes_ _contao_official_demo_ _page_layouts_ _edit_layout_id_19_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/1622464/40276631-83c33ccc-5c0f-11e8-9ae4-2ca77f5f17ea.png">

<img width="636" alt="sections_test_-_contao_official_demo_und_frontend_php_-_pasg_-____httpdocs_pasg_" src="https://user-images.githubusercontent.com/1622464/40276633-95ffd800-5c0f-11e8-9498-34d7c74f7432.png">

**Comment by leofeyer** [comment]
Implemented in 5e8f65ba154b6fef6b0d2b1701ff980b2c855d1c.
