### ISSUE TITLE
Move to Symfony 2.7 asap

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#153]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/75) by @aschempp
Friday Mar 20, 2015 at 08:04 GMT

The stable release of Symfony 2.7 will be available starting in May.
http://symfony.com/roadmap?version=2.7#checker

I think we should definitely ship Contao 4 with Symfony 2.7 so we don't have to migrate our base framework in the next 2 years. http://symfony.com/blog/category/living-on-the-edge

**Comment by importer** [comment]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @leofeyer
Friday Mar 20, 2015 at 12:35 GMT

+1 generally.

However, I doubt that we will stay with Symfony 2.7 until 2018 :)

**Comment by importer** [comment]
> <a href="https://github.com/discordier"><img src="https://avatars.githubusercontent.com/u/940331?v=3" align="left" width="42" height="42" hspace="10"></img></a> Comment by @discordier
Sunday Mar 22, 2015 at 02:03 GMT

+1 and as long as we only restrict to minor, composer will bump us up to new versions.

**Comment by leofeyer** [comment]
I'm closing this ticket, since we'll be updated automatically by Composer.

**Comment by aschempp** [comment]
Please reopen this, the composer *require* must be set to `~2.7`.

**Comment by leofeyer** [comment]
Why? Are we using any version 2.7 specific features?

**Comment by aschempp** [comment]
We want to, and we want developers to do so. See https://github.com/contao/core-bundle/issues/202 <https://github.com/contao/core-bundle/issues/202> for an example.

**Comment by leofeyer** [comment]
Then why don't you adjust the version constraint in the context of your PR, which also implements #202?
