### ISSUE TITLE
PrettyErrorScreen does not support errors

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#1530]
https://github.com/contao/core-bundle/blob/master/src/EventListener/PrettyErrorScreenListener.php#L249

I guess this should be `\Throwable`. Not sure how to fix this in 4.4 where we support PHP < 7, but probably just by not having an argument at all?

**Comment by Toflar** [comment]
https://github.com/symfony/polyfill/tree/master/src/Php70#compatibility-notes :)

**Comment by leofeyer** [comment]
It seems that the polyfill only adds the `Error` class but not the `Throwable` interface?

**Comment by leofeyer** [comment]
There are more places where `\Exception` is used either as type hint or in a `catch` clause. What about those occurrences?

**Comment by aschempp** [comment]
More places in the listener or in the application?

**Comment by leofeyer** [comment]
Both.

**Comment by leofeyer** [comment]
I actually was not able to reproduce this. I have added `throw new \DivisionByZeroError();` in the `FrontendIndex` class and the pretty error screen was displayed properly.

How do I reproduce this?

**Comment by aschempp** [comment]
I'm pretty sure it was just an _invalid index_ error for me…

**Comment by leofeyer** [comment]
This has been fixed in contao/contao#32.
