### ISSUE TITLE
Elementtyp "Bild/Galerie" privater Ordner/Grafiken

### ISSUE THREAD

**Issue by kskmedia** [contao/core-bundle#1531]
Ich habe ein mögliches Problem in Verbindung mit nicht öffentlichen Ordnern und darin enthaltenen Grafiken.
Beim Erstellen eines Elementes vom Typ "Bild" oder "Galerie" und der Auswahl von Dateien werden die Ressources mit nicht geladen (404). Wenn man nun die Bildgröße auf proportional setzt und einen Wert (Breite) angibt, werden die Grafiken korrekt gerendert und ausgegeben (das wird wohl daran liegen, dass die gerenderten Dateien in /assets/ liegen). Beim anhaken von "Großansicht/Neues Fenster" kann die originale Ressource wieder nicht geladen werden (404).

Mein Wunsch wäre das der private Modus für die ausgewählte/n Grafik/en umgangen werden würde; z.B. wenn ein Frontenduser eingeloggt ist oder "Großansicht/Neues Fenster" ausgewählt wurde.

**Comment by leofeyer** [comment]
Ich denke nicht, dass das sinnvoll ist. Wir würden die Originalbilder nur unnötig nach `/assets/images` duplizieren und dort wären sie ja dann wieder öffentlich – da kannst Du auch gleich den Ordner veröffentlichen.

Was genau möchtest Du denn erreichen?

**Comment by fritzmg** [comment]
@kskmedia unter Contao 3 könntest du die [fritzmg/contao-file-access](https://github.com/fritzmg/contao-file-access) Extension benutzen, um Dateien bzw. Ordner nur gewissen Frontend Benutzer verfügbar zu machen. Ein Update für Contao 4 wird aber erst irgendwann im Laufe des Jahres kommen.

**Comment by m-vo** [comment]
Das Bild Content Element könnte den Nutzer allerdings darauf hinweisen, dass die ausgewählte Quelle private ist. Denn das Verhalten ist nicht gerade intuitiv (bis man weiß wie Resizer&Co funktionieren).

**Comment by patrickjDE** [comment]
> Denn das Verhalten ist nicht gerade intuitiv (bis man weiß wie Resizer&Co funktionieren).

Und das verstehen die wenigsten Kunden / Redakteure. Sollten sie mMn auch gar nicht müssen, aber ich habe auch keine Patentlösung für die Probleme und Interessentkonflikte, die das ganze Thema public/private, resized aus assets/original aus files bei Bildern umgeben...

Related: #307

**Comment by kskmedia** [comment]
@leofeyer Hintergrund ist, dass ich eine geschützte Seite mit Frontendusern und einem Modul habe. In dem Modul wird für jeden User ein Bild(er) ausgegeben und auch Downloads zur Verfügung gestellt. Diese Dateien sind jeweils nur für den jeweiligen User und dürfen nicht von anderen gesehen/gedownloaded werden. Mit dem CE Downloads im Modul ist dies auch kein Problem nur die Großansicht der Bilder schlägt fehl.
Im Grunde müsste doch die Großansicht genau wie das CE Downloads den querystring "file=" im Link mitbekommen.

**Comment by leofeyer** [comment]
> Diese Dateien […] dürfen nicht von anderen gesehen/gedownloaded werden. 

Aber genau das wäre der Fall, wenn die Dateien in `assets/images/` lägen. Dein Szenario lässt sich nur umsetzen, wenn die Bild-Ausgabe über ein PHP-Skript erfolgt, so wie es in @fritzmg's oben genannter Extension der Fall ist.

> Das Bild Content Element könnte den Nutzer allerdings darauf hinweisen, dass die ausgewählte Quelle private ist.

Das wäre in der Tat hilfreich. Machst Du einen PR? 😬

**Comment by m-vo** [comment]
Kann ich machen. (Komme allerdings erst in knapp zwei Wochen dazu - wann ist der Feature Freeze für die 4.6?)

**Comment by leofeyer** [comment]
Bis zum 30. Juni müssen alle Feature-PRs für die 4.6 da sein.

**Comment by CMSworker** [comment]
Wenn ich das Issue richtig verstehe, fehlt im Grunde bei den Frontend-Mitglieder-/-gruppen die Möglichkeit, "Filemounts" zu machen (Problem 1), wie es bei den Benutzergruppen bereits möglich ist, dort aber offenbar nicht richtig funktioniert (Problem 2).

Mit den Filemounts könnte man auswählen, auf welche privaten Ordner (und darin enthaltene Dateien) eine Mitgliedergruppe oder ein einzelnes Mitglied im Frontend nach dem Login zugreifen darf (z.B. geschützte Fotos für Vereinsmitglieder oder das Beispiel von kskmedia oben). Oder umgekehrt, dass man direkt bei den privaten Ordnern/Dateien auswählen kann, welche Mitglieder/-gruppen darauf zugreifen dürfen.

Für die Ausgabe ist auf jeden Fall eine Prüfung der erforderlichen Berechtigung notwendig, d.h. es gibt eigentlich gar keine andere Lösung, als Dateien aus privaten Ordnern über ein PHP-Script auszugeben, denn:

- Bilder, die in privaten Ordnern liegen, aber über ASSETS öffentlich erreichbar sind, sind ganz klar eine **Sicherheitslücke**. Auch, wenn nur die Thumbnails öffentlich erreichbar sind, und sei es nur temporär. Alles andere führt den Gedanken von "öffentlich" und "nicht öffentlich" ad absurdum.

- Wenn eingeloggte Mitglieder/Benutzer mit der erforderlichen Berechtigung zwar automatisch erstellte Thumbnails von Bildern in geschützten Verzeichnissen sehen können, aber nicht die Originalbilder ansehen können, ist das ganz klar eine **Fehlfunktion**, denn sie haben durch den Login und Filemount ja die Berechtigung dazu erhalten.

Jetzt nur einen Hinweis bei der Dateiauswahl zu ergänzen, das etwas im privaten Ordner liegt, löst IMHO die Grundprobleme nicht. Zumal es ja nicht stimmt: die Thumbnails sind offenbar trotzdem über ASSETS öffentlich erreichbar?!

Zu dem Beispiel unter https://github.com/contao/core-bundle/issues/307#issuecomment-130781285 (Fotograf, der Thumbnails öffentlich machen will, aber die Originale schützen will): Hierfür könnte bei den privaten Ordnern in den Einstellungen eine Checkbox ergänzt werden "Zugriff auf Originaldatei erlauben", die standardmäßig aktiviert ist. Der Fotograf könnte diese Checkbox abwählen und dann hätten die eingeloggten Mitglieder/Benutzer wie bisher nur Zugriff auf die Thumbnails. Theoretisch wäre eine solche Checkbox auch für öffentliche Ordner denkbar, hätte aber zur Folge, das alle Dateien über ein PHP-Script ausgegeben werden müssten, von daher würde ich diese Checkbox auf private Ordner begrenzen.

Von daher stimme ich dafür, den Dateischutz vernünftig im Core zu implementieren, denn die jetzige Lösung scheint konzeptionell falsch zu sein. Falls das wegen fehlender Zeit oder Manpower nicht möglich sein sollte, sollte die Bezeichnung "Private Ordner" bzw. "Öffentlich" geändert werden und das Schloss-Symbol in der Dateiverwaltung geändert werden, denn beides impliziert, dass die enthalten Dateien nur nach Login erreichbar sind, was nicht so ganz zu stimmen scheint.

Just my two cents...

**Comment by fritzmg** [comment]
Eine "Fehlfunktion" ist es nicht, denn das von dir angesprochene Feature gibt es ja nicht. Auch die Bezeichnung "Öffentlich" muss imho nicht geändert werden, denn das öffentlich und nicht öffentlich machen von Ordnern hat nichts direkt mit Mitgliedern zu tun.

Das was du haben möchtest, gibt es zB in der [fritzmg/contao-file-access](https://github.com/fritzmg/contao-file-access) Extension für Contao 3.

**Comment by leofeyer** [comment]
Siehe https://github.com/contao/core-bundle/pull/1594.
