### ISSUE TITLE
PWA: Register service worker on contao backends

### ISSUE THREAD

**Issue by may17** [contao/core-bundle#1532]
One common problem while working with service workers and contao is that you always have to register two serviceworkers. One for the frontend with scope "/" and one for the backend  with scope "/contao" to ensure that the frontend service worker is not responsible for the backend and does not wait for opened backend tabs.

We could also combine this with an default offline page instead of showing the downasaur :)

**Comment by leofeyer** [comment]
Sounds reasonable. How would we do that? 😄

**Comment by may17** [comment]
I‘ll create an pull request :)

**Comment by stefansl** [comment]
Would be a nice feature, when Contao could write the sw.js for us. With all features like cache invalidation, assets caching ...
