### ISSUE TITLE
Toggle Visibility Icon im Formulargenerator vorhanden trotz fehlendem Recht

### ISSUE THREAD

**Issue by de-es** [contao/core-bundle#1533]
In der Felder-Übersicht im Formulargenerator wird das Toggle Visibility-Icon angezeigt und ist auch umschaltbar bzw. anklickbar, obwohl das entsprechende Recht (tl_form_field -> invisible) für den Benutzer bzw. die Benutzergruppe nicht gesetzt ist. Wenn der Benutzer die Sichtbarkeit umschaltet, ändert das Icon entsprechend, aber der Wert wird richtigerweise nicht gespeichert.

Bei den Events, wenn man das vergleichen kann, wird das Visibility-Icon bei fehlendem Recht (hier "published") erst gar nicht angezeigt.

Contao 4.5.8

**Comment by leofeyer** [comment]
Behoben in 110625fd5ffb88ead80b3088d61144e1212c60bb.
