### ISSUE TITLE
Remove repository leftovers

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#154]
> <a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/76) by @aschempp
Saturday Mar 21, 2015 at 18:50 GMT

There are currently two leftovers of the extension repository:

1. The install tool asks wether to install composer
2. There's a `TL_REPOSITORY` log constant.

I think we should remove the former but keep the later 'cause we don't know if anyone used it.

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of #158.

**Comment by aschempp** [comment]
I don't see how they are related?

**Comment by leofeyer** [comment]
The other ticket is about adjusting the install tool, which I am currently doing. This is also what this ticket is about, since we have agreed not to remove the constant in Contao 4.

**Comment by aschempp** [comment]
Ah, :+1:
