### ISSUE TITLE
Backend: Small Suggestion for "Edit More"

### ISSUE THREAD

**Issue by timobanaszak** [contao/core-bundle#1540]
In Contao 4, when editing multiple elements (for instance when you want to copy several elements) the "Copy"-Button is hidden as a Dropup-Menu within the "Delete"-button.

Hiding those buttons seems fine for me, however I would prefer them being hidden in the "Edit" button instead of the delete-button – especially to prevent deleting something by accident. Some of my clients also stated, that they would prefer the "Copy" and "Move" Buttons not hidden at all.

Just bringing this in for discussion. What are your feelings?

![editmultiple](https://user-images.githubusercontent.com/22024726/40977309-e00e3a40-68d0-11e8-9ef9-c96a97b2a81f.jpg)

**Comment by xchs** [comment]
See https://github.com/contao/core/issues/8816
