### ISSUE TITLE
Chrome: Contao keyboard shortcuts do not work in TinyMCE

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#1541]
If the editable area of TinyMCE has the focus (which is always the case when you write or edit something there), the [Contao keyboard shortcuts for saving](https://docs.contao.org/books/manual/4.4/en/02-administration-area/keyboard-shortcuts.html#keyboard-shortcuts-in-edit-mode) apparently do not work anymore.

To reproduce (on a Windows system with Chrome 67):
- place the cursor into the editable area of TinyMCE and write something
- press the keyboard shortcut <kbd>Alt</kbd>+<kbd>s</kbd> (or <kbd>Alt</kbd>+<kbd>c</kbd>): nothing happens
- click somewhere outside TinyMCE and press the above keyboard shortcuts again: the corresponding save button is now triggered

It works as expected in Firefox 60 using the keyboard shortcuts <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>c</kbd>, respectively.

Tested with Contao 3 and Contao 4.

**Comment by leofeyer** [comment]
This is not something we can change IMHO. If we would e.g. override <kbd>Alt</kbd>+<kbd>c</kbd>, people could no longer type `ç`.

**Comment by xchs** [comment]
I see what you mean. I just found it a bit cumbersome to have to click outside the TinyMCE input area every time in order to quickly save what I have just written.

**Comment by patrickjDE** [comment]
Tabbing out also works, and you can get used to it quite fast. For me it's the most convenient way to work around this limitation.

**Comment by xchs** [comment]
> @patrickjDE Tabbing out also works

Yeah, I know. But still … not as comfortable as just
* to write something
* to press the keyboard shortcut <kbd>Alt</kbd>+<kbd>s</kbd></kbd>  (or <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>s</kbd>) to save the record
* continue writing

Furthermore, if you press the <kbd>Tab</kbd> key, then the keyboard shortcut <kbd>Alt</kbd>+<kbd>s</kbd>, you still have to click with the **mouse** back into the input field of TinyMCE, since switching back immediately using the keyboard shortcut <kbd>Shift</kbd>+<kbd>Tab</kbd> does not work.

**Comment by patrickjDE** [comment]
> Furthermore, if you press the Tab key, then the keyboard shortcut Alt+s, you still have to click with the mouse back into the input field of TinyMCE, since switching back immediately using the keyboard shortcut Shift+Tab does not work.

That's the case for all fields? The page reload when saving causes you to lose focus. But that could actually be fixed/improved with a bit of js.

**Comment by xchs** [comment]
> That's the case for all fields?

That's true, though.
