### ISSUE TITLE
Provide custom attribute with setter/getter to use as custom returnPath (Bounce Return E-Mail )

### ISSUE THREAD

**Issue by fatcrobat** [contao/core-bundle#1543]
Current implementation of `Email::sendTo()` does not give you any chance to modify the Bouce-Mail returnPath. It would be great if you can provide an public setter and getter to modify a new property named `returnPath`.

https://github.com/contao/core-bundle/blob/8cda9f237bca6cdce2e10ef4ea22aa65cbcf6ff4/src/Resources/contao/library/Contao/Email.php#L456

`sentTo` could be changed to:
```
$this->objMessage->setReturnPath($this->strReturnPath?:$this->strSender);
```

**Comment by aschempp** [comment]
You should probably not use the outdated Email class in this case. Use the Swiftmailer service directly and you have all the possibilities.
