### ISSUE TITLE
Improve the restore functionality

### ISSUE THREAD

**Issue by bezin** [contao/core-bundle#1548]
Hello fellow Contao friends,

a while ago we planned to improve the restore section of the Core-Bundle and I would like to use this issue to propose some ideas and discuss them. 

*The issue*
Editors are presented with rather technical information like database tables and sql queries, when they would like to restore content they deleted, which we do not find very usable. There are already [two](https://github.com/contao/core/issues/8663) [issues](https://github.com/contao/core/issues/6804) in contao/core. We aim to provide better descriptions for the content deleted.

*Our proposal*
In our [prototype undo extension](https://github.com/presprog/contao-undo) we show the content type (e.g. page, module, layout) and a descriptor (based on different attributes, depending of the content type). For Pages we show the title of the page deleted, for modules the name, for an headline element the headline, for an text element an excerpt of the actual text field.

I would also like to add a hint, if you deleted several elements at once (child elements), something like `(+ 32 elements)` in the label.

![](https://raw.githubusercontent.com/presprog/contao-undo/master/contao-undo-screenshot.jpg)

*Up for discussion*
**Missing translations for element types**
We have plenty of translated labels and messages in Contao. However, there are no labels describing all the entities available, e.g. "Page", "Module" or "Layout". These could be easily provided for Core elements, but extension developers would need to add these translations as well, e.g. "Employee" for a table `tl_employee`. As a fallback we could still use the table name without the prefix.

In our extension we added a new key the global language array, e.g. `$_GLOBALS['TL_LANG']['tl_content']['tl_content']  = [ 'Content element', 'Content elements' ]`. The key might be `'content_type'` or alike rather than duplicating the table name. 

**How to determine the descriptor**
We need to decide which attribute of each element describes itself best. Again, there must be a way for extension developers to decide which attribute (or a combined value of multiple attributes) to use. 

In our extension we do this with a nasty switch statement for prototyping purpose. I think we would need to define this in each DCA, e.g. by adding a new config key like `[...]['config']['restore_label'] = field_name` that might also take an anonymous function to merge multiple attributes (e.g. first and last name for members and users).

That is is by now; I would appreciate any feedback  :)

Cheerio

**Comment by leofeyer** [comment]
I like the overall concept, although we should probably use the event system instead of a [giant switch statement](https://github.com/presprog/contao-undo/blob/master/src/UndoLabelHelper.php#L48-L76) to determine the description. ;)

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
I like the concept as well, but I also like the idea of defining this in the DCA, as that is where the record is related to.

**Comment by bezin** [comment]
> we should probably use the event system instead of a giant switch statement to determine the description. ;)

That is what my "with a nasty switch statement for prototyping purpose" should imply ;) 

I though of the DCA as we define other labels there as well. @aschempp proposed a new config key in contao/core#[6804](https://github.com/contao/core/issues/6804) similiar to `list => sorting => label` which might be better suited than my proposed key. Maybe simply `list => restore => label`.

**Comment by Toflar** [comment]
> Maybe simply list => restore => label.

Sounds okay to me :)

**Comment by leofeyer** [comment]
@bezin Shall we discuss this issue in a Mumble call so you can continue to work on it?

**Comment by leofeyer** [comment]
There is a Mumble call tomorrow (Thursday, 22nd) at 3pm. 😉

**Comment by bezin** [comment]
I know, will be there 👍

**Comment by Toflar** [comment]
@bezin are you planning to work on this for the core? :)

**Comment by bezin** [comment]
Yip, I am still "planning to work" rather than acutally working, but I really wanna make this happen ;-) 
4.8 would be the next version this could be merged into, right?

**Comment by Toflar** [comment]
Cool, jep 4.8 :)

**Comment by bezin** [comment]
See https://github.com/contao/contao/pull/495

**Comment by aschempp** [comment]
closed in favor of https://github.com/contao/contao/pull/495
