### ISSUE TITLE
Adjust the "prepareFormData" hook

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#155]
A new argument has been added in contao/core#7693. It should be the third argument in Contao 4, because all other hooks have been adjusted in a way that `$this` is always the last argument.

**Comment by leofeyer** [comment]
Fixed in 7d0eb17743ca32d2058414c97b78b3f1522ac0cf.

**Comment by aschempp** [comment]
Why would we add that BC break, if we will switch to events sometime soon anyway?

**Comment by leofeyer** [comment]
Because we have adjusted all other hooks and callbacks as well.
