### ISSUE TITLE
Contao 4.5.8 Installing / Uninstalling extensions with error message: The command is already running in another process.

### ISSUE THREAD

**Issue by mlwebworker** [contao/core-bundle#1551]
Ich habe bei Strato (PHP 7.2.5) bei der Installation/Deinstallation von Erweiterungen folgendes Problem:

Die Installation über den Manager endet mit:
```
Generating optimized autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
The command is already running in another process.
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 95:
                                                                           
  An error occurred while executing the "contao:install-web-dir" command:  
                                                                           

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...


# Process terminated with exit code 1
# Result: General error
```

Über die Konsole erhalte ich:
```
reinerzau.de> /opt/RZphp72/bin/php-cli vendor/bin/contao-console contao:install-                                                                                                   web-dir -vvv
The command is already running in another process.
16:41:51 DEBUG     [console] Command "contao:install-web-dir -vvv" exited with c                                                                                                   ode "1"
[
  "command" => "contao:install-web-dir -vvv",
  "code" => 1
]
[]
reinerzau.de>
```

Zu Komlettierung hier noch der log-file
 
[prod-2018-06-09_strato.log](https://github.com/contao/core-bundle/files/2087182/prod-2018-06-09_strato.log)

Bei Neuladen des Browser sind die installierten Erweiterungen vorhanden.
Edit: Bei einem zweiten Versuch trat das Problem auch direkt während der Installation auf. Dann kann auch das Installtool nicht aufgerufen werden, weil die Route zum Installtool scheinbar nicht vorhanden oder gefunden wird

**Comment by fritzmg** [comment]
Zu dem Fehler
```
The command is already running in another process.
```
gibt es ein paar Threads/Posts im Forum. Soweit ich mich erinnere liegt das an einem nicht beschreibbarem TEMP Verzeichnis. Überprüfe die Serverumgebung mal mit dem Contao Check (neueste Master Version).

**Comment by mlwebworker** [comment]
Ich habe mir gerade zum Thema TEMP Verzeichnis diesen Thread https://community.contao.org/de/showthread.php?70652-Installation-von-Contao-4-5-Managed-Edition-bei-STRATO durchgelesen.
Aber so richtig mag ich an das nicht beschreibbare TEMP Verzeichnis nicht glauben. Ich habe gestern die erste Test-Installation fehlerfrei durchführen können. Erst bei der Installation von Erweiterungen kam es zum Problem. Bei einem zweiten Test ist schon die Installation selbst nicht durchgelaufen.

**Comment by leofeyer** [comment]
Sorry, hab das Ticket fälschlicherweise verschoben.

**Comment by fritzmg** [comment]
@mlwebworker führe mal per SSH folgendes aus:
```
cd ~
wget https://github.com/contao/check/archive/feature-cli.zip
unzip feature-cli.zip
```
Dann poste die Ausgabe von
```
/opt/RZphp72/bin/php-cli check-feature-cli/check/cli.php
```
und
```
/opt/RZphp72/bin/php-cli check-feature-cli/check/cli.php Contao45
```

**Comment by mlwebworker** [comment]
Hier die Ausgaben
```
reinerzau.de> /opt/RZphp72/bin/php-cli check-feature-cli/check/cli.php

Contao2: not compatible
Contao3: compatible
Contao4: compatible
Contao45: compatible
Composer: compatible

Run the command again with one of these as an argument, to show more information:
Contao2, Contao3, Contao4, Contao45, Composer, FilePermissions, LiveUpdate, Repository

Example:
$ php cli.php Contao45
```
und

```
reinerzau.de> /opt/RZphp72/bin/php-cli check-feature-cli/check/cli.php Contao45

Contao45:
  hasIcu: true
  hasPhp: true
  hasGraphicsLib: true
  hasDom: true
  hasIntl: true
  canWriteTmpDir: true
  canUseSymlink: true
  canCreateSymlinks: true
  hasXmlReader: true
reinerzau.de>
```
Für mich heißt das, daß das temporärer Verzeichnis beschreibbar ist richtig?

**Comment by fritzmg** [comment]
Ja, dann muss es an etwas Anderem liegen.

**Comment by Toflar** [comment]
Im Log steht folgendes:

> [2018-06-09 18:33:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Page not found: http://test-manager.reinerzau.de/system/modules/leads/assets/leads.css" at /mnt/web005/d3/59/53638259/htdocs/www/reinerzau/test_manager/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php line 109 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): Page not found: http://test-manager.reinerzau.de/system/modules/leads/assets/leads.css at /mnt/web005/d3/59/53638259/htdocs/www/reinerzau/test_manager/vendor/contao/core-bundle/src/EventListener/ExceptionConverterListener.php:109, Contao\\CoreBundle\\Exception\\PageNotFoundException(code: 0): Page not found: http://test-manager.reinerzau.de/system/modules/leads/assets/leads.css at /mnt/web005/d3/59/53638259/htdocs/www/reinerzau/test_manager/vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:64)"} []

Das kann folgendes heissen:

- Entweder ist die Datei tatsächlich nicht dort.
- Symlinks können nicht erstellt werden oder sind falsch und daher ist die Datei nicht erreichbar.
- Der Server ist so eingestellt, dass er Symlinks nicht folgt.

**Comment by aschempp** [comment]
Ich hatte das Problem mit @mlwebworker bereits einmal debugged. Die Lock-Datei des `AbstractLockedCommand` wird beim ersten Aufruf im temporären Verzeichnis abgelegt und bleibt danach dort. Dadurch sind alle weiteren Commands gelockt. Mit irgendwelchen Erweiterungen hat das eigentlich nichts zu tun.

**Comment by fritzmg** [comment]
Der Fehler tritt auch auf, wenn das tmp Verzeichnis nicht beschreibbar ist - daher meine initiale Vermutung.

Erzeugt das `AbstractLockedCommand` immer nur eine Datei mit dem selben Namen dafür?

**Comment by mlwebworker** [comment]
Der Test den ich auf Anfrage von @fritzmg gemacht habe zeigt eigentlich das Symlinks sowohl erstellt als auch verfolgt werden können.
```
reinerzau.de> /opt/RZphp72/bin/php-cli check-feature-cli/check/cli.php Contao45

Contao45:
  hasIcu: true
  hasPhp: true
  hasGraphicsLib: true
  hasDom: true
  hasIntl: true
  canWriteTmpDir: true
  canUseSymlink: true
  canCreateSymlinks: true
  hasXmlReader: true
reinerzau.de>
```

**Comment by mlwebworker** [comment]
Ok, was kann ich noch testen. Ich bin beinahe zu jeder Schandtat bereit um solchen Fehlern auf die Schliche zu kommen. Allerdings reicht mein Wissen in diesem Bereich nicht um da allein weiter auf Fehlersuche zu gehen.

**Comment by fritzmg** [comment]
Für das Problem mit den symlinks von leads würde ich einfach mal folgendes versuchen:

1. `system/modules/leads` löschen
2. `vendor/terminal42/contao-leads` löschen
3. `composer install` ausführen

**Comment by mlwebworker** [comment]
@fritzmg  Es geht nicht um die Reparatur einer konkreten Installation sondern nur um einen Testaccount für die Community (Manager Test)  bei welchem ich dann für die Tests mehr oder weniger wahllos Erweiterungen installiere. Die Erweiterungen aus der Fehlermeldung sind schon längst wieder weg. Hatte ja danach auch noch eine Neuinstallation gemacht. Bei diesem Versuch trat der Fehler gleich in der Installation auf. Beim dritten Versuch klappte die Installation wieder und er ist bei den Erweiterungen hängengeblieben. 
Ich würde ganz gern für die Community dazu beitragen, dass eine sichere Installation von Contao 4 auch bei diesem "Sch.."-Hoster Strato funktioniert. Ist halt in Deutschland einer der Billig-Massenhoster. @Andreas hat sich soviel Mühe gegeben, damit der Installationsprozess auf der langsamen Krücke durchläuft. Wäre doch schade, wenn es dann an Contao selbst scheitert.

**Comment by fritzmg** [comment]
Ja natürlich. Aber die Probleme müssen abgegrenzt werden - das mit den Symlinks hat meines Erachtens nichts mit dem `The command is already running in another process` Problem zu tun.

**Comment by mlwebworker** [comment]
Ich denke die Fehler treten auf, weil Installation/Deinstallation der Erweiterungen auf Grund des noch laufenden Prozesses nicht korrekt abgeschlossen werden kann. Die Erweiterungen werden zwar im Manager angezeigt, scheinen aber nicht korrekt installiert zu sein.
Ich fahre noch mal eine neue Installation.

**Comment by fritzmg** [comment]
Ja, die fehlenden Symlinks sind vermutlich ein Folgefehler. Primär muss der "The command is already running in another process" Fehler gelöst werden.

**Comment by fritzmg** [comment]
@mlwebworker ändere mal [diese Zeile](https://github.com/contao/core-bundle/blob/4.4.18/src/Command/AbstractLockedCommand.php#L32) in `vendor/contao/core-bundle/src/Command/AbstractLockedCommand.php` auf
```php
            $this->getContainer()->getParameter('kernel.project_dir') . '/var/lock'
```
Also insgesamt
```php
        $lock = new LockHandler(
            $this->getName(),
            $this->getContainer()->getParameter('kernel.project_dir') . '/var/lock'
        );
```
Und führe danach wieder ein `composer install` aus (Manager oder SSH).

**Comment by mlwebworker** [comment]
Das ist aus der 4.4.18.  Ich habe hier eine 4.5.8 im Test. Da müsste Deine Änderung wahrscheinlich an diese Stelle

```
    private function getTempDir(): string
    {
        $container = $this->getContainer();
        $tmpDir = $this->getContainer()->getParameter('kernel.project_dir') . '/var/lock';

        if (!is_dir($tmpDir)) {
            $container->get('filesystem')->mkdir($tmpDir);
        }

        return $tmpDir;
    }
```

**Comment by Toflar** [comment]
Ich glaube das ist das Problem. Wir hatten es schon mal und scheinbar nur für die 4.5 gefixt? @leofeyer

**Comment by fritzmg** [comment]
@mlwebworker nein, in Contao 4.4.18 ist das gleich: https://github.com/contao/core-bundle/blob/4.4.18/src/Command/AbstractLockedCommand.php#L30-L33

**Comment by fritzmg** [comment]
@Toflar es geht hier eh um Contao 4.5.8.

Filesystem\LockHandler ist ab Symfony 3.4 deprecated. Contao 4.4 unterstützt aber noch Symfony 3.3, daher wird dort noch der Filesysetem\LockHandler verwendet.

Mit dem neuen FlockStore habe ich mich noch nicht beschäftigt, da könnten natürlich andere Probleme auftreten.

**Comment by mlwebworker** [comment]
Nein
`$tmpDir = sys_get_temp_dir().'/'.md5($this->getContainer()->getParameter('kernel.project_dir'))`
steht auch in der 4.5.8 drin. Oben war schon mit der Anpassung.
Habe gerade mehrere Pakete mit dieser Anpassung installiert. Das lief ohne Probleme.
Ich kann dann heute Abend noch mal weiter testen und auch die Contao 4.4.18 mit den Anpassungen noch einmal durchlaufen lassen.

**Comment by fritzmg** [comment]
@mlwebworker ja, hatte mich vertan ;). Contao 4.4.18 brauchst du nicht mit Änderungen testen - du könntest aber testen ob Contao 4.4.18 _ohne_ Anpassungen mit dem alten Filesystem\LockHandler funktioniert. Dann könnten wir das Problem auf den neuen FlockStore evt. eingrenzen.

**Comment by mlwebworker** [comment]
Das hatte ich glaub auch schon mal getestet nach dem das Problem das erste mal bei Strato aufgetaucht ist. War m.E. das Gleiche. Werde ich aber heute Abend zur Sicherheit noch mal checken.

**Comment by fritzmg** [comment]
Ok verstehe. In Contao 4.5.8 könntest du aber tatsächlich die von dir schon erwähnte Änderung mal probieren, also
```php
$tmpDir = $this->getContainer()->getParameter('kernel.project_dir') . '/var/lock';
```
Nur um obskure Probleme mit dem system tmp dir auszuschließen.

**Comment by mlwebworker** [comment]
Habe ich doch gemacht und oben auch schon geschrieben, dass die Installation von einer Hand voll Erweiterungen fehlerfrei funktioniert hat, mit dieser Anpassung.

**Comment by fritzmg** [comment]
Ah ok, das hatte ich übersehen.

@contao/developers  das system tmp directory als Ort für die lock files scheint bei Strato nicht ganz verlässlich zu sein. Spricht etwas dagegen die lock files einfach in den `/var` Ordner der Contao Installation zu legen?

**Comment by Toflar** [comment]
Eigentlich nicht, aber `sys_get_temp_dir()` ist eigentlich genau dafür da. PHP muss so konfiguriert sein, damit diese Funktion ein Verzeichnis zurück gibt, in das man temporär schreiben darf. Jegliche Extensions und Bundles werden sich darauf verlassen, weil so ist es gedacht. Sprich, auch wenn wir was ändern, bringt das unter Umständen nichts.

**Comment by mlwebworker** [comment]
Also ein hausgemachtes Strato-Problem. Was müsste ich genau schreiben, damit Strato motiviert wird vielleicht was zu ändern (ich weiß ich träume gerade) und vor allem begreift worum es geht.

**Comment by fritzmg** [comment]
@mlwebworker man müsste zuerst mal debuggen warum _genau_ das `$lock->acquire()` fehl schlägt. Du kannst mir ja mal Zugangsdaten zukommen lassen, wenn möglich ;)

**Comment by mlwebworker** [comment]
PN mit den Zugangsdaten ist übers Forum raus. Über Github wusste ich auf Anhieb nicht wie bzw. ob das geht.

**Comment by fritzmg** [comment]
Das habe ich bisher herausgefunden:

* Es macht keinen Unterschied, in welches Directory man das Lock file schreiben lässt. Innerhalb von `/var/lock` in der Contao Installation selbst kann man den Fehler genau so reproduzieren.
* Ist noch kein Lock file da, läuft alles ohne Fehler durch, mit folgenden Log einträgen, wenn man dem Lock einen Logger übergibt (in diesem Fall wurde das `contao:install` command getestet):
```
[2018-06-12 16:13:06] app.INFO: Successfully acquired the "contao:install" lock.
[2018-06-12 16:13:06] app.INFO: Expiration defined for "contao:install" lock for "300" seconds.
```
* Führt man das command erneut durch, kommt es schlicht zu folgendem Fehler:
```
[2018-06-12 16:13:08] app.NOTICE: Failed to acquire the "contao:install" lock. Someone else already acquired the lock.
```
Das erzeugte Lock file ist read-only:
```
-r--r--r-- 1 xxxxxxx yyyyyy    0 Jun 12 18:13 sf.contao-install.3IFCjQ1.lock
```
Das ist vom FlockStore auch absichtlich so gesetzt. FlockStore bekommt dann auch einen validen ressource handle.

Aber - FlockStore kann bei Strato auf diese Datei dann keinen exclusive lock mehr bekommen. Hier kommt es dann immer zu der Exception:
```php
if (!flock($handle, LOCK_EX | ($blocking ? 0 : LOCK_NB))) {
    fclose($handle);
    throw new LockConflictedException();
}
```
Welcher Prozess auf diese Datei noch einen File Lock hat kann ich natürlich nicht herausfinden, da auf dem Server natürlich keine Tools dafür zur Verfügung stehen -_-

**Comment by Toflar** [comment]
Tolle Analyse, danke! Seltsam, können wir den Strato-Support miteinbeziehen? Am besten gleich in der Anfrage schreiben, dass sie 1st und 2nd Level überspringen sollen 😄 
Was ergibt eigentlich `<?php var_dump(extension_loaded('sysvsem')) ?>`?

**Comment by fritzmg** [comment]
> Was ergibt eigentlich <?php var_dump(extension_loaded('sysvsem')) ?>?

`false` :). Dann ist das wohl das Problem, oder?

**Comment by Toflar** [comment]
Nee, das wäre Semaphore Lock. Hätte mich auch überrascht, wenn das auf Strato zur Verfügung stehen würde, aber man kann ja nie wissen 😄 Dann müssen wir herausfinden, warum das File-Locking nicht sauber läuft. Da kann uns nur noch der Support helfen und wenn die's nicht können, sind wir machtlos.

**Comment by fritzmg** [comment]
Ok, werde das zusammen mit @mlwebworker machen.

**Comment by aschempp** [comment]
Die Datei müsste doch einfach beim Release des Locks gelöscht werden? https://github.com/contao/core-bundle/blob/master/src/Command/AbstractLockedCommand.php#L44

@leofeyer warum locken wir die Commands überhaupt? Ich seh dafür nicht wirklich einen Grund, ein `cache:warmup` ist auch nicht gelockt und macht potentiell Dinge kaputt wenn es gleichzeitig ausgeführt wird.

**Comment by aschempp** [comment]
Vielleicht sollten wir das ändern (und/oder bei Symfony nachschauen/nachfragen).

**Comment by leofeyer** [comment]
> @leofeyer warum locken wir die Commands überhaupt? Ich seh dafür nicht wirklich einen Grund, ein `cache:warmup` ist auch nicht gelockt und macht potentiell Dinge kaputt wenn es gleichzeitig ausgeführt wird.

Wenn dem so wäre – und das glaube ich nicht – wäre das ein Bug in Symfony. Ist es nicht vielmehr so, dass Probleme vermieden werden, indem der Cache zuerst im Ordner `pro_` aufgebaut wird und dann in einer atomaren Operation in `prod` umbenannt wird? Bei mehreren gleichzeitigen Aufrufen würde also einfach der letzte gewinnen.

**Comment by fritzmg** [comment]
Naja, die Datei muss ja nicht unbedingt gelöscht werden. Der Locking Mechanismus passiert ja nur mit
```php
flock($handle, LOCK_EX | LOCK_NB)
```
Evt. ist es auch besser, wenn die Datei nicht gelöscht wird? Damit es atomar bleibt.

@leofeyer das ist nur beim löschen so. Build-up/warm-up passiert direkt im prod/dev Ordner.

**Comment by leofeyer** [comment]
I see. Und geht tatsächlich etwas kaputt, wenn man mehrere `cache:warmup`-Prozesse gleichzeitig startet?

**Comment by fritzmg** [comment]
Wir hatten mal einen Fall, wo im Live Betrieb der `prod` Cache gelöscht wurde, woraufhin in hunderten  Requests auch jeweils der Cache aufgebaut wurde, was den Server mit sehr seltsamen Fehlern in die Knie zwang 😁

**Comment by leofeyer** [comment]
Also doch ein Bug in Symfony (fehlendes Locking für `cache:warmup`).

**Comment by fritzmg** [comment]
> Also doch ein Bug in Symfony (fehlendes Locking für cache:warmup).

Naja, während eines Requests wird ja kein `cache:warmup` command ausgeführt. Da wird der Cache ja on-the-fly innerhalb des Requests erzeugt - wenn nicht vorhanden.

**Comment by fritzmg** [comment]
Wir haben eine Support Anfrage an Strato geschickt, da würde ich mal abwarten.

Ansonsten: das locking vielleicht tatsächlich entfernen? Dass das selbe command zwei mal gleichzeitig ausgeführt wird halte ich für einen seltenen Fall. Ist aber prinzipiell möglich, wenn man bspw. das Install Tool zwei mal aufruft.

**Comment by mlwebworker** [comment]
Habe bis jetzt aus der typischen automatischen Eingangsbestätigung noch keine Antwort. Erfahrungsgemäß wird versucht kompliziertere Fragen erst einmal auszusitzen. Ich habe mir eine Nachfrage diesbezüglich für nächste Woche auf Termin gelegt.

**Comment by fritzmg** [comment]
Hier die Antwort von Strato:

> Bei der Überprüfung durch unsere Entwickler konnte festgestellt werden, dass Sie die Befehle für flock wie bei einen Linuxsystem eingesetzt haben.
> Dadurch funktionieren diese in einer Linuxumgebung ohne Einschränkungen.
> Innerhalb unserer Hostingpakete wird jedoch **Solaris** und nicht Linux eingesetzt, dadurch muss die Funktion entsprechend angepasst werden.
> Damit die Funktion innerhalb unserer Hostingpakete korrekt funktioniert, sollte diese wie folgt aufgebaut werden:
> 
> ```
> $fileName = __DIR__ . '/file.lock';
> 
> $handle = fopen($fileName, "r+");
> 
> if (!$handle) {
>     echo "Could not open $fileName\n";
>     exit;
> }
> 
> if (flock($handle, LOCK_EX | LOCK_NB)) {
>     echo "Got a lock on $fileName\n";
> sleep(60);
>     flock($handle, LOCK_UN | LOCK_NB);
> } else {
>     echo "Could not get a lock on $fileName\n";
> }
> ```
> 
> Der Unterschied zu ihren Einstellungen liegt darin, dass Sie r+ im fopen() verwenden.
> Sobald der Code wie im obrigen Beispiel verwendet wird, solltn keine weiteren Einschränkungen auftreten.

Das kann ich auch bestätigen. Ich kann auch bestätigen, dass diese Änderung im Symfony [FlockStore](https://github.com/symfony/lock/blob/v3.4.11/Store/FlockStore.php#L82-L89) das Problem löst:
```diff
-   if (!$handle = fopen($fileName, 'r')) {
+   if (!$handle = fopen($fileName, 'r+')) {
        if ($handle = fopen($fileName, 'x')) {
            chmod($fileName, 0444);
-       } elseif (!$handle = fopen($fileName, 'r')) {
+       } elseif (!$handle = fopen($fileName, 'r+')) {
            usleep(100); // Give some time for chmod() to complete
-           $handle = fopen($fileName, 'r');
+           $handle = fopen($fileName, 'r+');
        }
    }
```

Nur: soll das wirklich so gelöst werden? Ist das eher ein Fehler von Solaris? Oder von der kompilierten PHP Version unter Solaris? Oder von PHP selbst?

**Comment by Toflar** [comment]
Solaris...wow.
Anyway, ich würde vorschlagen du machst einen PR bei Symfony mit diesen Änderungen und erklärst den Hintergrund. Mal sehen was die dann meinen. Oder was denkst du?

**Comment by fritzmg** [comment]
Ja, so würde ich es nun auch machen.

**Comment by leofeyer** [comment]
Ein `r+` sollte kein Problem sein. Ist die Datei halt lesbar und beschreibbar. ¯\\_(ツ)_/¯

Hauptsache es funktioniert. 😄

**Comment by fritzmg** [comment]
So, for some reason this issue is still happening on Strato, even with Symfony 3.4.12. I'll test again with @mlwebworker 's env.

**Comment by fritzmg** [comment]
https://github.com/symfony/symfony/pull/27668#issuecomment-403392924 -_-

**Comment by fritzmg** [comment]
Neuer PR: https://github.com/symfony/symfony/pull/27903

**Comment by xabbuh** [comment]
Berechtigungen werden jetzt auf 644 gesetzt. Könnt Ihr bestätigen, dass das ausreicht oder ist 666 tatsächlich notwendig?

**Comment by fritzmg** [comment]
@xabbuh In der Testumgebung kann ich momentan mit nur einem user testen - somit kann ich leider nicht überprüfen, wie es sich verhält, wenn das selbe lock file von anderen usern benutzt wird.

Innerhalb von Contao wird dieser Fall jedoch vermutlich nie eintreten, da Contao einen Projektspezifischen Pfad für das lock file erstellt und man meistens nur einen user pro Projekt hat.

**Comment by leofeyer** [comment]
@fritzmg Was muss denn hier noch gemacht werden, jetzt da Symfony Deinen PR gemergt hat?

**Comment by fritzmg** [comment]
Nichts, mit dem nächsten Symfony Release sollte das Problem bei Strato endlich der Vergangenheit angehören :).
