### ISSUE TITLE
Subpalettes won't work on users profile page

### ISSUE THREAD

**Issue by bytehead** [contao/core-bundle#1552]
I would like to add a subpalette to the users profile page (`/contao?do=login`) for #1545.
But the ajax request always fails with a `403` thrown on line 1808 here: https://github.com/contao/core-bundle/blob/186b649afa90e008d8414b6d64c153f530cbcee4/src/Resources/contao/drivers/DC_Table.php#L1788-L1809

`intId` has value `false` in this case.

The value gets set on line 413 here:
https://github.com/contao/core-bundle/blob/186b649afa90e008d8414b6d64c153f530cbcee4/src/Resources/contao/classes/Ajax.php#L384-L416

As already discussed with @Toflar, he will try to shed some light/investigate this.

**Comment by Toflar** [comment]
@leofeyer you can assign that to me.

**Comment by Toflar** [comment]
PR is ready https://github.com/contao/core-bundle/pull/1559

**Comment by bytehead** [comment]
Thank you @Toflar! 🎉
