### ISSUE TITLE
Explode limitation set to 2 might be applied

### ISSUE THREAD

**Issue by Jobu** [contao/core-bundle#1555]
https://github.com/contao/core-bundle/blob/186b649afa90e008d8414b6d64c153f530cbcee4/src/Resources/contao/drivers/DC_Table.php#L5103

I think in this line is missing the explode limitation option set to 2!?!

**Comment by leofeyer** [comment]
Why do you think that?

**Comment by Jobu** [comment]
In my case I have a subquery in the concat, so multiple occurences of the dot. This lead to errors when performing search operations.

'foreignKey'              => 'tl_beachcup_team.CONCAT((SELECT CONCAT(tl_beachcup_player.name, " ", tl_beachcup_player.surname, " (", tl_beachcup_player.tax_number, ")") FROM tl_beachcup_player WHERE tl_beachcup_player.id = tl_beachcup_team.player_1), " und ", (SELECT CONCAT(tl_beachcup_player.name, " ", tl_beachcup_player.surname, " (", tl_beachcup_player.tax_number, ")") FROM tl_beachcup_player WHERE tl_beachcup_player.id = tl_beachcup_team.player_2))'

**Comment by leofeyer** [comment]
Fixed in f52fc13f4885a2ce10d9bd2387a78a39bf08ee70. Thank you @Jobu.
