### ISSUE TITLE
Two more drag and drop file manager issues

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1556]
This ticket refers to #1546.

1. If you click the drag handle without actually dragging it, the overlay is activated and stays visible.
https://www.dropbox.com/s/5e5k3gjo1v7rpmg/drag-drop-1.mp4?dl=0

2. It is possible to move folders within their parent folder, which results in an error message.
https://www.dropbox.com/s/fwvxmkiioc852di/drag-drop-2.mp4?dl=0

**Comment by ausi** [comment]
Done: #1567
