### ISSUE TITLE
UX improvement: Focus last edited field after saving

### ISSUE THREAD

**Issue by patrickjDE** [contao/core-bundle#1565]
Inspired by #1541

When editing an item in the backend and saving, the page reloads. The scroll position is then restored, but the keyboard focus is not.

It should be possible with some javascript to also restore the focus to the last edited field. I think this would make for a nicer UX for people who save often. Any other thoughts on this?

**Comment by aschempp** [comment]
I like the idea, can you provide some Javascript for this?

**Comment by patrickjDE** [comment]
I'll have a closer look at it this weekend.

**Comment by leofeyer** [comment]
See #1582.
