### ISSUE TITLE
[4.4] Automatic logout in dev mode when using invalid path in $GLOBALS['TL_JAVASCRIPT']

### ISSUE THREAD

**Issue by christian-kolb** [contao/core-bundle#1572]
I use the core bundle as a Symfony bundle. Within I developed a custom frontend module. 
The issue I run into appears when I use `$GLOBALS['TL_JAVASCRIPT']` with a wrong path, for example: 

```php
$GLOBALS['TL_JAVASCRIPT'][] = 'files/js/mod_member_staff_manage_edit.js';
```

(which does not exist) instead of:

```php
$GLOBALS['TL_JAVASCRIPT'][] = 'files/js/mod_member_staff_manage.js';
```

Then I get the strangest (but reproducible) error. This only applies to **dev mode**. Meaning the `app_dev.php`.

The first time I open the link with the module used in the Frontend I will see the page as usual. But whatever the next interaction is. Being it clicking on another link or refreshing the same page, I will immediately be logged out and moved to the login page (my 403 page redirects to the login).

There are no error messages in the frontend or the (PHP) logs of any kind (I looked through thousands of lines to verify). And once again, this only happens in dev mode. In production there is no logout.

My guess is, that there is some error triggered somewhere within Contao if the file is not found but is caught somewhere else and has only an effect in the next call (because a session is killed or something similar). In any way there should at least be a log message with an error and there should be the same behaviour in dev and production mode.

Things I tried while debugging can be found here: https://github.com/contao/core-bundle/issues/1542#issuecomment-395325812

Might also be an issue in 4.5 and up, but I only have a 4.4 installation at the moment to check.

**Comment by christian-kolb** [comment]
I just used a bundle that creates a custom mask in the Contao backend. It also contains a special css file. As I didn't run the assets command yet, the requested css file wasn't available. This also lead to a logout. So this problem is not just relevant for the frontend, but also the backend components of Contao.

**Comment by christian-kolb** [comment]
And another fun little easter egg: When one of your javascript files references a `.map` file, and this `.map` file isn't available (which it usually isn't in production), you're also logged out. The fun part is that as the `.map` file is only used for the browser internals and therefore you don't get any 404 error which might alert you to the problem. 
It doesn't seem to be an issue with `$GLOBALS['TL_JAVASCRIPT']` itself, as the issue is also there if you reference the javascript file within your template with the script tag.
And it's also there in 4.6 so it doesn't seem to be related to the new security component or fixed by it.
I guess it's related on the way Contao provides files when they are requested in the first place. Something in the process seems to kill or invalidate the session if a file is requested which isn't available on the server.

**Comment by fritzmg** [comment]
I am assuming this happens because any request to a file that does not really exist is processed by the `app.php` and then in turn processed in the `frontend` scope of Contao.

**Comment by christian-kolb** [comment]
Interesting, but this would only affect the backend if the user in the frontend previously set the automatic login, wouldn't it? And it doesn't explain why I have the same effect in the frontend. 

I guess that's the real problem. This was what hit me. Developed locally (including `.map` file), but didn't push it. Then in the frontend opened the module (everything looks fine) switch to next page or refresh the current and get logged out.

The thing I don't get is why the session is killed or the user is logged out. I get that there is some kind of error message, but there has to be some kind of security feature which reacts here.

**Comment by aschempp** [comment]
Are you logged out of the frontend or backend?

**Comment by christian-kolb** [comment]
This issue is in both. So if I'm in the backend and there is something requested that doesn't exist, you're logged out and also if you're in the frontend.
