### ISSUE TITLE
mod_login: "cols" remove this field or add it as css-class

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1577]
The current mod_login offers to choose between one or two columns.
https://demo.contao.org/contao?do=themes&table=tl_module&id=4

I don't realy think it is something we need - but if we keep this field it should be referenced [in the template as a css-class](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_login.html5#L3).

[related issue](https://github.com/contao/core-bundle/issues/235)

**Comment by leofeyer** [comment]
The field can be removed. We are no longer using it as of Contao 4.0.

**Comment by ausi** [comment]
Every installation that currently uses `$this->cols` in the login template would break if we remove this field.

It would also break the SQL website template import for current SQL files.

IMO we must not change this in a bugfix release.

**Comment by leofeyer** [comment]
Agreed. But we can remove it in Contao 4.6, right?

**Comment by ausi** [comment]
Yes, as we don’t guarantee backwards compatibility for templates, I think we can remove it in 4.6.

**Comment by leofeyer** [comment]
Removed in 5fcee7bee23ab0a357eeddc0267d3e366d6d6bb6.
