### ISSUE TITLE
Unterstrich Zwang in Template-"Prefix" Namen

### ISSUE THREAD

**Issue by timgatzky** [contao/core-bundle#1578]
Hi Leute,
in aktuellen C4 Versionen radiert Contao Modul-Templates aus, die nach dem gegeben "Prefix"-String nicht auf Zwang einen Unterstrich fahren oder exakt den Namen des Prefix sind.

Beispiel: Prefix = "mod_customcatalog"
mod_customcatalog -> wird gefunden, weil exakt
mod_customcatalogfilter -> wird nicht mehr gefunden.

Die vorherige Logik erlaubte deutlich flexiblere Tempalte-Namen, bei weniger Zeichen. Auch geht die Abwärtskompatibilität verloren.

3.5
https://github.com/contao/core/blob/8190c51e470390b3c6e5aae32bfab3eaed9db176/system/modules/core/library/Contao/TemplateLoader.php#L83

4.4
https://github.com/contao/core-bundle/blob/fa05410fbd75cca7655599e59972475fe371ca0e/src/Resources/contao/library/Contao/TemplateLoader.php#L81

Gibt es zu dieser getätigten Änderung einen changelog oder Issue, warum das getan wurde?

**Comment by frontendschlampe** [comment]
Das ist korrekt. Es wurde deshalb eingeführt, um nur die passenden Templates anzuzeigen und nicht alle. Somit werden für ein Modul/Element, welches nur die Templates `mod_customcatalog_XXX.html5` auch nur diese angezeigt und nicht auch ein `ce_text.html5`. Das ist auf jeden Fall sehr sinnvoll. Was die Abwärtskompatibilität angeht, so ist das leider so, da von v3 auf v4 ein Majorupdate erfolgt ist und somit BC-Breaks erlaubt sind.

**Comment by timgatzky** [comment]
Ist mir durch die Lappen gegangen. Danke dir.
