### ISSUE TITLE
Database-Parameters not equal to localconfig.php in Install-Tool

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#158]
The Database-Parameters displayed in Install-Tool are not equal to localconfig.php because the are overwritten from parameters.yml in `Contao\Config`. see [Config.php](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/Config.php#L482)

I´m not sure if this is really a issue or just pending.

**Comment by aschempp** [comment]
That's pending, we need to remove that from the install tool. But good to have an issue for that anyway :-)

**Comment by leofeyer** [comment]
Also see #154.

**Comment by leofeyer** [comment]
I have removed the redundant stuff in b5e61e556ad5c0469c077488214386f754317e95. There is still the encryption key in the install tool, which we want to replace with the kernel secret. Pull request anyone?
