### ISSUE TITLE
Feature: Dropzone sichtbar, wenn im Upload-Modus gefiltert wird

### ISSUE THREAD

**Issue by k-webdesign** [contao/core-bundle#1580]
Hi,

es kommt immer und immer wieder vor, dass die User beim Upload einer Datei auf den Ordnernamen klicken, statt auf die Icons zu achten. Dann wundern sie sich, wenn sie im Ordner drin sind. 

Wäre es eine Idee, dass die Dropzone erscheint, wenn man auf einen Ordner klickt, während man im "Upload-Modus" ist?

**Comment by leofeyer** [comment]
Haben wir für die 4.6 (File-Uploads mit Drag & Drop) implementiert.
