### ISSUE TITLE
Symfony WebServer fails when using dump()

### ISSUE THREAD

**Issue by ameotoko** [contao/core-bundle#1584]
I'm not sure whether to address this issue to Contao, Symfony, or PHP. I'll try from here.

Symfony's WebServer goes down with an error `The process has been signaled with signal "11"`, when I'm trying to `dump()` something. 

PHP 7.1.2, Contao 4.5.9

**Comment by Toflar** [comment]
I think 11 is a segfault. So nothing anybody can do anything about it. Maybe you try to dump something that is very huge and then RAM explodes?
