### ISSUE TITLE
Wrong BUILD number constant in current 4.4.20 Zip

### ISSUE THREAD

**Issue by timgatzky** [contao/core-bundle#1591]
Hi,
the BUILD constant in the current 4.4.20 zip is still on 19.

![screenshot_3256](https://user-images.githubusercontent.com/970730/41901838-3c712880-7932-11e8-8349-f9943980a617.jpg)

**Comment by leofeyer** [comment]
That's weird. The constant is set correctly in the core-bundle: https://github.com/contao/core-bundle/blob/4.4.20/src/Resources/contao/config/constants.php

**Comment by leofeyer** [comment]
Ah, the tag of the managed edition is wrong.

**Comment by leofeyer** [comment]
Fixed.
