### ISSUE TITLE
Lost Password - Verbesserung

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1592]
In mehreren Projekten ist mir jetzt schon aufgefallen, dass das Lost-Password-Modul unglücklich designed ist.

Ausgangslage: Das Modul ist auf einer Seite eingebaut, welche Member besuchen, wenn sie ihr Passwort vergessen haben. Dort Versorge ich den Nutzer gern mit Hinweistexten zum Prozedere (in etwa wie [hier](https://demo.contao.org/en/lost-password.html)). Der Nutzer bekommt eine Mail mit dem Reset-Link und landet dann wieder auf der selben Seite - und da liegt mein Problemchen (Selbe Seite / anderes Formular) - denn nun machen diese Hinweistexte keinen Sinn mehr und ich würde gern andere Texte verwenden (etwa Hinweise zur Sicherheit von Passworten etc...)

Ich habe dazu einen alten [Forenbeitrag](https://community.contao.org/de/showthread.php?20042-Passwort-vergessen-Modul-Nach-best%C3%A4tigunsmail-andere-Seite-aufrufen) gefunden - hier scheint's allerdings nie auf der Agenda gelandet zu sein - deshalb jetzt dieses Ticket für weitere Anregungen oder Bedenken.

Lösung 1 wäre, 2 Richtext-Felder für das Modul zu ergänzen welche abhängig davon ausgegeben ob wir uns den Link zuschicken lassen wollen (```username``` & ```email``` Formular) oder ein neus Passwort eingeben sollen (```passwort``` & ```passwort bestätigen``` Formular)

Eine andere Möglichkeit wäre ein zusätzlicher Pagepicker in dem Modul, welcher bestimmt, wohin der ```reset-Link``` führen soll. Das würde dann das Erstellen eine gesonderten Seite und ein erneutes Einbinden des Modul's erfordern.

Dritte Möglichkeit (das sollte ohne jegliche bc-Probleme möglich sein): zusätzlich zum simpleToken 
```##link##``` welches den kompletten Link in der E-mail ausgibt 
```https://demo.contao.org/en/lost-password.html?token=PWee4877d3bb80c656254d50d8cf6cc6```
wird
**```##token##```** eingeführt.
Damit hätte man dann wenigstens die Möglichkeit, sich den Link für die E-mail selbst zusammenzubasteln.

**Comment by frontendschlampe** [comment]
Ich fände Lösung 2 gut, da das ja schon bei anderen Modulen so gemacht wird, wie z.B. Newsletterregistrierung

**Comment by fritzmg** [comment]
@asaage du könntest deinen Text ja einfach nur dann ausgeben, wenn kein `token` Parameter vorhanden ist.

**Comment by asaage** [comment]
@fritzmg richtig: so habe ich es auch schon-mal gemacht... ebenso mit Javascript... es gibt da sicher mehrere Wege, die zum Ziel führen. Es ist für mich eher eine Convenience-Frage und ich möchte sie nicht bei jedem Projekt neu angehen müssen.

**Comment by leofeyer** [comment]
Ich finde Lösung 2 nicht gut, da es zum einen eine dritte (!) Weiterleitungsseite erfordern würde und zum anderen das Setup deutlich verkompliziert (zweite Seite mit zweitem "Passwort vergessen"-Modul etc.). Wir wollen ja die Dinge einfach halten. 😄 

Ich finde die Idee mit den beiden Rich-Text-Feldern gut, die je nach Kontext eingeblendet werden. Das wäre ein Konzept, das wir auch für andere Module übernehmen könnten, um z.B. ein "Vielen Dank für das Absenden des Formulars. Wir melden uns schnellstmöglich." ausgeben zu können, ohne dafür eine komplette Seite mit Artikel und Inhaltselement anlegen zu müssen.

**Comment by Toflar** [comment]
> Das wäre ein Konzept, das wir auch für andere Module übernehmen könnten, um z.B. ein "Vielen Dank für das Absenden des Formulars. Wir melden uns schnellstmöglich." ausgeben zu können, ohne dafür eine komplette Seite mit Artikel und Inhaltselement anlegen zu müssen.

Unsere https://github.com/terminal42/contao-ajaxform macht sowas. Das Formular wird einfach per Ajax abgeschickt und dann durch den Text ersetzt. Sowas wäre wohl nicht verkehrt im Core.

**Comment by leofeyer** [comment]
Siehe contao/contao#204.
