### ISSUE TITLE
drop the linebreak in mod_login template

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1599]
Would be nice if this ```<br>``` could be removed in [mod_login.html5#L24](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_login.html5#L24)
It took some time to figure out why my input-elements didn't want to flex-display consistent
and there is no ```<br>``` in other form ```widget-text```'s.

kind of related to https://github.com/contao/core-bundle/issues/1577

**Comment by leofeyer** [comment]
@contao/developers That's a left-over, isn't it?

**Comment by Toflar** [comment]
Yeah, no idea what purpose that should have there...

**Comment by leofeyer** [comment]
Removed in 71dd6b2a2f61f014fcde9727942c8626a2dd887d.
