### ISSUE TITLE
Do not boot Contao´s Framework twice

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#160]
As discussed in https://github.com/contao/standard-edition/issues/2, we should prevent to boot the Framework twice
Here is a working and testing solution: https://github.com/ContaoBlackforest/core-bundle/commit/fa07a7339592ab17193d066c0e5731b5ac49afc0

I think this have to be discussed. 

Best regards Dominik

**Comment by aschempp** [comment]
I don't think the unit test is correct, as it does check for a property but not for its behavior. The test cannot validate if we check `isBooted` and do not boot again. Not sure if we can test this at all.

**Comment by dtomasi** [comment]
> Not sure if we can test this at all.
I think so, too. But I wrote it to test at least `$isBooted` is set.
If there will be no Exception be thrown, the behavior is not testable.

**Comment by dtomasi** [comment]
> The test cannot validate if we check isBooted and do not boot again

I added a second call to `boot()`. You are right. This is not suitable, but all we can do.
https://github.com/contao/core-bundle/commit/7b09d6d9f9e810887b46e7237041053f16ae56f7

**Comment by aschempp** [comment]
I have cherry-picked your changes and created #166
