### ISSUE TITLE
decodeEntities decoded incomplete?

### ISSUE THREAD

**Issue by zonky2** [contao/core-bundle#1604]
decodeEntities decoded incomplete?

Verification text: `mein <span>Text</span> #Sonderzeichen <xy>haha</xy>`

Output: `mein &lt;span>Text&lt;/span> #Sonderzeichen &lt;xy>haha&lt;/xy>`

why is the `>`  in `&lt;span>` or `/span>` not converted?

We have the same in Contao 3.5. and Contao 4.4
Look at https://github.com/MetaModels/attribute_text/issues/11#issuecomment-403275591

**Comment by leofeyer** [comment]
See https://github.com/contao/core/issues/3998
