### ISSUE TITLE
Events zeigen falsches Datum nach Contao-Update

### ISSUE THREAD

**Issue by k-webdesign** [contao/core-bundle#1614]
Ich habe eine Installation von 2.11 auf 3.5 auf 4.4. geupdated und an den Core-Events nichts verändert. Nun tritt das Phänomen auf, dass das Enddatum des Events in der Eventliste und dem Kalender genau einen Tag später zeigt als im Event eingetragen ist. 

Gehe ich in das Event rein und speichere es noch mal, wird die Darstellung in der Eventliste korrigiert. 

Siehe: 
[alte seite](http://alt.bmw-z1.de/veranstaltungen-archiv) (bitte 2017er Akkordion aufklappen)
[neue seite](https://www.bmw-z1.club/veranstaltungen-archiv.html) (bitte 2017er Akkordion aufklappen)

**Comment by fritzmg** [comment]
Welche Zeitzone hast du jeweils eingetragen?

**Comment by k-webdesign** [comment]
Oh weia, bei der alten war es GMT, bei der neuen Berlin. Die alte Seite ist nicht von mir, bei der neuen hab ich natürlich alles "richtig" eingestellt 🙈
❌❌geschlossen ❌❌
