### ISSUE TITLE
Add "crossorigin" attribute to <img> tags

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#1617]
After reading https://cloudfour.com/thinks/when-7-kb-equals-7-mb/ I wonder if we should add the attribute to all our templates?

Wdyt?

/cc @may17

**Comment by ausi** [comment]
Most images in Contao are loaded from the same origin I think. And if they are loaded from a CDN the `crossorigin` attribute might break the images if the CDN is not configured to allow CORS.

**Comment by may17** [comment]
Whats about the files / assets url on root Pages? That urls could be affected or i am wrong?

**Comment by leofeyer** [comment]
They could.

We have discussed this in Mumble on August 30th and given the possible issues mentioned above, we have decided to close this ticket.
