### ISSUE TITLE
Get rid of `database.sql` and `languages/*.php`

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#162]
Since we have removed a lot of old stuff already, why don't we get rid of the `database.sql` files and the PHP language files? We should use DCA files and XLIFF language files instead.

@contao/developers What do you think?

**Comment by aschempp** [comment]
`database.sql` could be ok, but I know there are a lot of people out there still using/supporting it. Absolutely :-1: on XLIFF, I never use them.

**Comment by discordier** [comment]
I am still using database.sql in a bunch of extensions but am migrating slowly, therefore we could drop support for it for 4.0 final.
Regarding xliff, I always ship the languages as .php and managing the root language as xliff is a major PITA, therefore :-1: from me as well.

**Comment by leofeyer** [comment]
Since we are promising BC, we should probably not drop the `database.sql` support, either. But we should deprecate it to be removed in Contao 5.

**Comment by aschempp** [comment]
>  But we should deprecate it to be removed in Contao 5.

+10 for that

**Comment by ausi** [comment]
Is it possible to use the [symfony/Translation](https://github.com/symfony/Translation) component for an extension in Contao 4? If so, it should be the recommended way for Contao 4 IMO. The Translation component supports XLIFF, YAML, PHP and more out of the box so it should fit for all extension developers. PHP language files with `$GLOBALS` should also be deprecated then.

Relying on XLIFF only, would be bad IMO. I always used the PHP format.

> Since we are promising BC, we should probably not drop the `database.sql` support, either. But we should deprecate it to be removed in Contao 5.

+1

**Comment by aschempp** [comment]
> Is it possible to use the symfony/Translation component for an extension in Contao 4? If so, it should be the recommended way for Contao 4 IMO.

Appart from the fact that you need to fetch the translator from the container (using `global $kernel`) I don't see a reason why that should not be possible.

However, it would then not work with `langconfig.php` etc.

**Comment by ausi** [comment]
What if we use the Symfony Translator in the core and create a custom loader for it which loads the legacy language files and reads them from `$GLOBALS['TL_LANG']`?

**Comment by aschempp** [comment]
I did that a while ago, but I think it adds a lot of overhead and encourages users to write old file formats for the new translator (which we should not).

**Comment by ausi** [comment]
But if the core doesn’t use the Symfony translator at all, users have to write the old file format to extend or modify messages, right?

**Comment by aschempp** [comment]
I guess so, until we build that **feature** ;-)

**Comment by leofeyer** [comment]
We have decided to keep the PHP language files and to deprecate the `database.sql` files in Contao 4, so they can be removed in Contao 5.0.
