### ISSUE TITLE
"Broken image!" when uploading jpg

### ISSUE THREAD

**Issue by internetinnovations** [contao/core-bundle#1623]
We have heavy issues with a new project:
When jpg pictures are uploaded, they are shown as broken in the backoffice.
In the frontend they are shown and work flawlessly.

Error when trying to open a CE via BO with a broken image:
![screenshot_unable-to-open](https://user-images.githubusercontent.com/26227169/42930045-38e29836-8b3c-11e8-9056-bd9cb076202e.JPG)

File Manager:
![screenshot_broken-image](https://user-images.githubusercontent.com/26227169/42929900-b50ed772-8b3b-11e8-802a-79b12bc2c044.JPG)

All other picture file types also work.
Error log shows:
Image "path/picture.jpg" could not be processed: Unable to open image /var/www/project_folder/files/img/picture.jpg

This project uses: Contao Version 4.4.20

**Comment by xchs** [comment]
Check the PHP information (`phpinfo()`) which image libraries (GD, Imagick oder Gmagick) are available and if the JPEG support is enabled.

**Comment by YenRinkleff** [comment]
okay, checked phpinfo() and saw, that gd hasn't jpeg support enabled... Have to look now, how to activate it...

**Comment by internetinnovations** [comment]
It might be useful to update the error log message to include a reference to the image libraries as @xchs postet. Thanks for the info.

**Comment by akroii** [comment]
Same here.
My logs are:
```
[2018-10-11 15:48:57] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []
[2018-10-11 15:48:57] app.CRITICAL: An exception occurred. {"exception":"[object] (Imagine\\Exception\\RuntimeException(code: 445): Crop operation failed at /var/www/web29855652/html/contao4/vendor/imagine/imagine/lib/Imagine/Imagick/Image.php:146, ImagickException(code: 445): unable to open pixel cache `/var/www/web29855652/html/contao4/assets/images/5/yyyy-flotte-e4c6fdd7.jpg': No such file or directory @ error/cache.c/OpenPixelCache/3673 at /var/www/web29855652/html/contao4/vendor/imagine/imagine/lib/Imagine/Imagick/Image.php:141)"} []
```
PHP 7.1.14
Contao 4.4.23
![bildschirmfoto 2018-10-11 um 15 50 59](https://user-images.githubusercontent.com/8830861/46808823-7d2c8880-cd6d-11e8-942f-520862af413c.png)

![bildschirmfoto 2018-10-11 um 15 51 06](https://user-images.githubusercontent.com/8830861/46808850-8f0e2b80-cd6d-11e8-9929-eefbd798e749.png)

**Comment by mestro67** [comment]
I had same problem on Mittwald hosting with Contao 4.6.6 and PHP7.2-FPM, after switching to PHP7.2-CGI, problem was solved.

**Comment by fritzmg** [comment]
Mittwald is claiming, that Imagick is not compatible with PHP-FPM in general. However, I couldn't find any evidence that this is true. I think that something in their setup is wrong.

**Comment by ausi** [comment]
There seem to be issues with Imagick if you use PHP-FPM and chrooting, but that should be fixable: <https://www.ateamsystems.com/tech-blog/imagemagick-under-php-fpm-and-chroot/>

**Comment by fritzmg** [comment]
I see, then someone should tell to Mittwald probably 😁
