### ISSUE TITLE
wrong page-title on 404-errorpage with empty or / url_suffix

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#1624]
Today i stumbled about a strange behaviour.
Usually if you request a nonexisting page and you have set a **non-redirecting** 404 page in your sitestructure the response will contain something like ```<title>Page not found - Contao Official Demo</title>``` and a proper responsecode of 404.

My Setup has folder-urls enabled, ```prepend_locale: true``` and ```url_suffix: '/'```
which causes the following results:

- domain.tld/en/contact/  → status ```200``` ```<title>contact...</title>``` ✓
- domain.tld/en/somethingstupid/ → status ```404``` ```<title>page not found...</title>``` ✓
- domain.tld/en/**contact**/somethingstupid/ → status ```404``` ```<title>contact...</title>``` ?

I tried this without folder-urls and/or without ```prepend_locale: true``` achiving the same results.
```url_suffix: ''``` will also give me the same result.

It's probably not a big deal but i think it's a bug (especialy if you have ```<h1>{{page::pageTitle}}</h1>``` in your layout)

**Comment by leofeyer** [comment]
Its not a bug. `somethingstupid` is treated as `auto_item` parameter in the third case.
