### ISSUE TITLE
Dateiverwaltung - Interne Seite auswählen

### ISSUE THREAD

**Issue by mecintosch** [contao/core-bundle#1625]
Über die Dateiverwaltung lassen sich nur URLs oder InsertTags eintragen, es lässt sich jedoch keine interne Seite wählen.

Bindet man ein Bild als Inhaltselement ein und wählt "Metadaten überschreiben" kann dort sehr wohl über die Weltkugel ein Link auf eine interne Seite gesetzt werden. Ist dann zwar auch ein InsertTag jedoch erspart man sich das manuelle suchen und eintippen der IDs.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core-bundle/pull/1568
