### ISSUE TITLE
no pretty error screen on refused database connection

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1626]
In Contao 4.5.10, if the database connection is actively refused for whatever reason, every route **including** `/contao/install`, will only display the following:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Not Found</title>
    </head>
    <body>
        <h1>Oops! An Error Occurred</h1>
        <h2>The server returned a "404 Not Found".</h2>

        <div>
            Something is broken. Please let us know what you were doing when this error occurred.
            We will fix it as soon as possible. Sorry for any inconvenience caused.
        </div>
    </body>
</html>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Internal Server Error</title>
    </head>
    <body>
        <h1>Oops! An Error Occurred</h1>
        <h2>The server returned a "500 Internal Server Error".</h2>

        <div>
            Something is broken. Please let us know what you were doing when this error occurred.
            We will fix it as soon as possible. Sorry for any inconvenience caused.
        </div>
    </body>
</html>
```
The `dev` environment will show the following errors: https://pastebin.com/C7cm4HC7

Shouldn't the pretty error screen be shown in the `prod` environment instead?

**Comment by m-vo** [comment]
Sounds a bit like the issue in #1422 where Doctrine throws an exception before the kernel is booted (and therefore the listener for pretty error screens doesn't not kick in)?

**Comment by fritzmg** [comment]
Right, I forgot about that. Probably not an issue that's easily solved. Closing :)

**Comment by m-vo** [comment]
Hmm. I not sure how the `/contao/install` route works before entering database credentials. But wouldn't the same error appear if a wrong username/password/port was entered?

**Comment by fritzmg** [comment]
No, because if host and port are correct, Doctrine can establish an initial connection to determine the MySQL server version.

**Comment by m-vo** [comment]
It's still bad that you can enter whatever you want in the installer and it still works but everything goes away if  e.g. the mysql server isn't reachable. :smile:
