### ISSUE TITLE
Send a confirmation mail after submitting a form

### ISSUE THREAD

**Issue by Exotelis** [contao/core-bundle#1627]
I'd like to send the user, who submitted a form, a confirmation e-mail that we received the request.

If you can image, that this feature could become a part of the core (without being a plugin), it would might be possible for me to contribute this functionality.

**Comment by m-vo** [comment]
Any problem with using `terminal42/notification_center` for this task? :smile: 

I agree that Contao's notification functionality isn't that powerful out of the box. But I think we should either migrate this bundle into the core or make the core pluggable/agnostic for message solutions. There a quite a few other places where messages need to be sent e.g. user registration, password reset, newsletter (see https://github.com/contao/core-bundle/issues/1613)...

**Comment by Exotelis** [comment]
`terminal42/notification_center` could be an option if it's compatible with version 4.4+. I hadn't heard of `terminal42/notification_center`.

Migrating this bundle into the core would just make sense if it's no longer maintained, right?

I used to use a plugin that is no longer maintained... I totally forgot the name.

**Comment by m-vo** [comment]
It is compatible, see https://github.com/terminal42/contao-notification_center/blob/1.4.5/composer.json#L15

And why would you think it isn't maintained anymore?

**Comment by fritzmg** [comment]
I think he means EFG.

**Comment by Exotelis** [comment]
Yes I meant that EFG is no longer maintained. Thank you @fritzmg

It would not make sense to migrate the notification center into the core (as long as it is maintained), unless you would get the developer to work upstream ;)

**Comment by m-vo** [comment]
Actually the developers are part of the Contao core team. 😉
