### ISSUE TITLE
4.6-RC1: extensions compatible with Contao 3 and 4 cannot be installed

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#1628]
See https://github.com/contao-community-alliance/composer-plugin/issues/76

I created this ticket to just keep track of the issue in the compser-plugin in this repository too. Contao 4.6 probably should not be released until this is dealt with, otherwise a lot of people might run into this problem.

**Comment by m-vo** [comment]
Unfortunately that's the typical issue if a requirement has been forgotten and was later fixed. :worried: I think the only way to work around this is to add a conflict in a parent bundle. Extensions could stop requiring the 2.* version or the Contao core could add a conflict. Or users must explicitly define conflicts on the application level. 

I remember we had the same discussion with Contao's own bundles which led to the way they are now referenced and released synchronously.

Perhaps we should add a `ConvenientConflicts` package that it's required as `dev-master` in the managed edition by default and handle all those things in there. :smile:

**Comment by leofeyer** [comment]
Thanks for reporting this @fritzmg. I also stumbled across it when I updated contao.org to Contao 4.6.

**Comment by fritzmg** [comment]
@m-vo well in this case it's easily fixed with a new release for the composer-plugin: https://github.com/contao-community-alliance/composer-plugin/pull/77

However, may be the core-bundle should add a conflict for `contao-community-alliance/composer-plugin:<3.0"`

**Comment by leofeyer** [comment]
Yes, either the core bundle or the manager bundle.

**Comment by m-vo** [comment]
Probably even better in the manager bundle, then? Because the core never really had anything to do with the cca composer plugin (e.g. if used in a standalone Symfony application).

**Comment by aschempp** [comment]
Neither does the manager-bundle …

**Comment by aschempp** [comment]
Version 3.0.9 of the composer-plugin has been released that should fix this problem.

**Comment by leofeyer** [comment]
Fixed in contao-community-alliance/composer-plugin@2686fb2299fa4fcde1d3a54ec10cd497661d8536 and dbd770536a5c44458118223914d29ed2fd969649.
