### ISSUE TITLE
Frontent preview

### ISSUE THREAD

**Issue by ChrMue** [contao/core-bundle#1638]
Is it possible to note the name/path of the current page in the header frame of the frontend preview? This would be helpfull if the page looks similar.

**Comment by Toflar** [comment]
That's not really feasible. It's an iframe and we would need to push to the parent window using some `window.postMessage()` implementation. However, the iframe doesn't know if it's shown in the preview or not. So that's a deadlock here imho.

**Comment by ChrMue** [comment]
yes of course, you are right. sorry. but it would be great. 
perhaps it will be possible to place this information anywhere.

**Comment by Toflar** [comment]
Actually it is possible. You're lucky we have dev meeting currently 😄 
PR ready here: https://github.com/contao/core-bundle/pull/1640.

**Comment by ChrMue** [comment]
Thank you very much, Yanick!

**Comment by leofeyer** [comment]
Closing in favor of #1640.
