### ISSUE TITLE
Why are pages of type root excluded from custom navigations?

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1641]
Hello,

why is this the case? Would it be possible to include them? In fact I can choose them in the configuration in the backend but they won't be delivered.

Bye

**Comment by fritzmg** [comment]
Why do you want to select root pages? Those are not "real" pages.

**Comment by fritzmg** [comment]
In such a case I would create a internal redirect page with the title you desire and select that in your custom navigation module.

**Comment by Defcon0** [comment]
Possible but sounds a bit like a workaround ;-) But ok, it's possible ;-)

**Comment by leofeyer** [comment]
It seems to me that a workaround is only required because of your prerequisites:

> Setting the title of the first real page ("Startseite") to the domain's name is no option in the context of this domain.

@contao/developers Should we allow root pages in the custom navigation?

**Comment by Toflar** [comment]
It makes no sense to generate a navigation with root page types. I don't see any use case here.

**Comment by Defcon0** [comment]
@leofeyer 

> Setting the title of the first real page ("Startseite") to the domain's name is no option in the context of this domain.

If I'd do so, all other navigations would have the corporate's name in them. Imagine a navigation like:

> ACME Corp. | About us | Downloads | Imprint | ...

Understandably the customer wants the first point to be "Home" or something like that. Of course I could do all that logic in the template, but this wouldn't be necessary if one could just select the roots.

**Comment by fritzmg** [comment]
I thought you __didn't__ want it to be _Home_?

**Comment by Defcon0** [comment]
No ;-)

Needed situation is that the root is named like the domain (or company) and the first page is named „Home“. Now we need a custom nav where we select the roots so that the links are named like the domains (or companies).

The situation now is that we can without modification only have a nav list containing 4 times „Home“ because we cannot select the roots ;-)

**Comment by leofeyer** [comment]
As discussed in Mumble on August 30th, we want to include root pages in the custom navigation menu.

**Comment by leofeyer** [comment]
Implemented in contao/contao@912e3f7a64e92f808a086797d27ebb207b8dc479.

**Comment by fritzmg** [comment]
One "problem" I have with this are the generated URLs for the root pages. The contain the alias of the root page, which does not make much sense. The URL will then redirect you to the start page. (Unless that has changed already?)

**Comment by leofeyer** [comment]
So you suggest using the title of the root page but the alias of the first child page? Isn't that confusing for the users?

**Comment by ausi** [comment]
Wouldn’t it be better to use no alias at all?

The root page linking to `example.com/` or `example.com/en/` (depending on the `prepend_locale` setting) would make sense to me.

**Comment by fritzmg** [comment]
Yes, ideally the generated URL for a website root should be just the domain (and language, depending on `prepend_locale`).

**Comment by asaage** [comment]
> So you suggest using the title of the root page but the alias of the first child page? Isn't that confusing for the users?

That is how internal Redirect-Pages without specific target work and i don't think it is confusing.
But linking to ```domain.tld/[locale]``` without any alias sounds reasonable.

**Comment by leofeyer** [comment]
Implemented in contao/contao@3c92fb923e13678c7d47fe397ca6f398ff596515.

**Comment by Defcon0** [comment]
Awesome, thanks :+1: !
