### ISSUE TITLE
email on new core updates (perhaps modules too)

### ISSUE THREAD

**Issue by mosag** [contao/core-bundle#1645]
On drupal it is possible to add the admin email address and get mails if there updates for the core (and for the modules too).
There is a radio button "weekly" and "daily" and you can select "only security updates" and "all updates" (and a checkbox to check or not check for disabled modules too).

Is there a function in Contao too and I'm only blind, or is this a missing feature?
Then this is my feature request ;)

In Contao 3.x there was a notice in the Backend of new updates, I miss this in Contao 4.x (4.4 LTS).

**Comment by m-vo** [comment]
You can subscribe to the packagist RSS feed off the core-bundle or enable notifications on GitHub. As the bundles are released together e.g. turn on notifications for the managed edition repository and you'll get an email if a new release/tag is created. Security updates are announced on contao.org as well.

So I don't think we need an extra feature for this.

**Comment by mosag** [comment]
Ok, thank you for your answer.

I know you "programmer nerds" love GitHub ;) but for me (and for several forum users which post they miss the update information too), it's perhaps more comfortable to simply get an email ... for me GitHub are "Böhmische Dörfer" ;)
(I could not find this feed after a short google search ...)

I don't use any RSS reader, I don't visit contao.org every day and I don't login to the contao manager every day ... 
It could also be helpful, if you administrate multiple websites and get a notice from each site, so you can't forget one.

**Comment by fritzmg** [comment]
Use RSS + https://blogtrottr.com/

**Comment by m-vo** [comment]
Also keep in mind: You do not need to update instantly, if it's not security related.

**Comment by aschempp** [comment]
As a forum user, you can also subscribe to "instant" notifications in the release channel: https://community.contao.org/de/forumdisplay.php?36-Ankündigungen-Hinweise

**Comment by cliffparnitzky** [comment]
The extension [integrity_check](https://packagist.org/packages/bugbuster/integrity_check) sends that mail.

**Comment by mosag** [comment]
Nice solutions! Thanks guys! :)

**Comment by mosag** [comment]
The integrity_check extension seems to be only for contao <4

For other users:
Here are the RSS-Feeds I've "found" (there is no link on the packagist.org ... why?? I've "constructed" it with the link "Atom/RSS Feeds" at the end of the page):
https://packagist.org/feeds/vendor.contao.rss
https://packagist.org/feeds/package.contao/managed-edition.rss

What if I only want a notice about **security updates** for 4.4 LTS Version?

**Comment by fritzmg** [comment]
There is the security newsletter of the CCA: https://c-c-a.org/aktuelles/security-newsletter
But I am not sure if it is still maintained anymore.

**Comment by frontendschlampe** [comment]
> There is the security newsletter of the CCA: https://c-c-a.org/aktuelles/security-newsletter
But I am not sure if it is still maintained anymore.

It is still maintained :-)
