### ISSUE TITLE
News frontEndUrl with auto_item and url_suffix: '/'

### ISSUE THREAD

**Issue by m-knorr** [contao/core-bundle#1651]
Contao 4.5.10

I have the following Sitestructure:

- Blog (Module: News Archive with all Cats)
  - Category1 (Module: News Archive with Category 1)
    - Detail (Module: News Reader)
  - Category2 (Module: News Archive with Category 2)
    - Detail (Module: News Reader)

FolderURLs and auto_item are activated and the following URL setting in the config.yml:

```
# Contao configuration
contao:
  url_suffix: '/'
```

The Following problems occur:

1. The alias for the detail pages get not created with folder like structure f.e. detail_id and not blog/category/detail
2. The frontend url to the details is always www.example.com/newsentryalias/ but it should be www.example.com/blog/category/detail/newsentry or am i wrong? When I deactivate the auto_item it works, but it also adds the /item/ to the url.

**Comment by fritzmg** [comment]
I am not sure an `/` URL suffix is actually supported.

**Comment by bytehead** [comment]
Try with `''` as a suffix.

**Comment by m-knorr** [comment]
In versions < 4.5 it always worked for me, and the other pages work as expected with this URL suffix.

But I'll try the version with ''!

**Comment by m-knorr** [comment]
Changed it to '', works the same way as with '/'.

**Comment by m-knorr** [comment]
Even with no changes in the config.yml the behaviour is the same for the detail alias 🤔

**Comment by m-knorr** [comment]
Ok, I tracked it down to **fritzmg/contao-simple-news-urls** @fritzmg 

The Extension seems not to "respect" the folder-urls and strips away the whole alias!

**Comment by fritzmg** [comment]
> The Extension seems not to "respect" the folder-urls

That's the purpose of the extension ;)

> and strips away the whole alias!

That should not happen though. Please open a ticket in the extension.

**Comment by asaage** [comment]
Anyway i still think there is **some** kind of issue with folder-urls in combination with ```url_suffix: '/' ``` / ```url_suffix: ''``` and ```auto_item```
https://github.com/contao/core-bundle/issues/1624
