### ISSUE TITLE
Select folder in downloads element -> not possible anymore?

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1655]
Hello,

I think in Contao 3 it has been possible to select a folder in a downloads content element so that in the frontend the files in the folder are shown as a list. Unfortunately this doesn't work anymore and if I select a folder, this doesn't get into the picker. Of course I have the possibility to select the files in the folder, but then I'd have to visit the content element everytime I add a new file. For me this wouldn't be a problem but for the customer it is ;-)

Am I doing something wrong or is it a bug?

Bye Defcon0

**Comment by Defcon0** [comment]
Update: I've just seen that it's only the case if I add new files just by ftp and not by using the file manager.

Nevertheless the folder doesn't show up in the form after selecting it in contao.

**Comment by fritzmg** [comment]
> Update: I've just seen that it's only the case if I add new files just by ftp and not by using the file manager.

This is normal behavior. The DBAFS will not be updated, if you upload files directly via FTP.

**Comment by Defcon0** [comment]
Yeah, agreed.

What about the other issue?

**Comment by fritzmg** [comment]
Not sure what you mean. If you select the folder, the files of that folder will be available for download (assuming they are present in the DBAFS).

**Comment by Defcon0** [comment]
If the folder is empty yet, no folder icon is shown next to the picker button. If you like I can post a picture?

**Comment by fritzmg** [comment]
Yes, please post a screenshot.

**Comment by Defcon0** [comment]
See the attached video.

[downloads.zip](https://github.com/contao/core-bundle/files/2269802/downloads.zip)

**Comment by asaage** [comment]
Usually this will display the downloadable **content** of the folder but as it's empty there is nothing to display.
It works perfectly fine though.
On save you won't see a complaint about a blank mandatory field and you can upload your files later into that folder.

**Comment by Defcon0** [comment]
Yes, I already noticed that. It works but nevertheless it would be nice if the folder would appear if it's empty :) It's not crucial, just a little issue. If it's fixed quickly, it would be nice. If not, no problem ;-)
