### ISSUE TITLE
Compilation failed: POSIX collating elements are not supported at offset 5

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#1656]
I have troubles logging into the Contao backend under version 4.5 and 4.6-RC. The error I get is shown on the screenshot:

![2018-08-06 at 11 41](https://user-images.githubusercontent.com/193483/43821381-4b524fd6-9ae9-11e8-95c3-4edc47dda5dd.png)

It is probably related to this line of code:

https://github.com/contao/core-bundle/blob/master/src/Translation/Translator.php#L96

I have investigated it a bit and discovered that my PCRE version is 8.32, whereas on the other server where it worked is 8.41. I am not completely sure if it's relevant to the PCRE version but I am unable to update the library version because it's not available at the moment for CentOS/cPanel/EasyApache I am using right now.

Has anyone of you encountered the same problem? Is PCRE old version really the problem here? If so, is there any chance of making this regexp compatible with older PCRE versions as well?

Any help would be appreciated :wink:

**Comment by ausi** [comment]
The next line has to be changed as well probably:

```php
preg_match_all('/(?:\\\\[\.\\\\]|[^\.])++/s', $id, $matches);
$parts = preg_replace('/\\\\([\.\\\\])/s', '$1', $matches[0]);
```

**Comment by qzminski** [comment]
That works like a charm sir 😎 any chance to get it merged into 4.6?

**Comment by leofeyer** [comment]
@ausi Can I remove the `/s` modifier?

<img width="558" alt="" src="https://user-images.githubusercontent.com/1192057/43896034-adff1012-9bd7-11e8-9279-deb46f0cd31e.png">

**Comment by ausi** [comment]
Yes.

**Comment by leofeyer** [comment]
Fixed in ba03d0cccac1a326a3c20aa8f7ab7b2623b46d21 then.

**Comment by qzminski** [comment]
@leofeyer can you re-open this issue? The error occurs again now in 4.8.4, see referenced commit above: https://github.com/bohnmedia/contao/commit/f1e0671a9596b20dcae9d71acd73f35ce1e6aef8

I would rather say it's quite urgent as it breaks down the Contao backend for some systems.

**Comment by leofeyer** [comment]
I can reopen the issue, but it would not be fixed as it is in `contao/core-bundle`. Please create a new issue in `contao/contao` instead.
