### ISSUE TITLE
Manuelle Sortierung in DCA mode 5 bei gesetzten root

### ISSUE THREAD

**Issue by timgatzky** [contao/core-bundle#1657]
Beispiel: tl_page, Limitierung via "root" auf Seiten id=10,20
$GLOBALS['TL_DCA']['tl_page']['list']['sorting']['root'] = array(10,20);

Bei aktiven Limitierungen wird die manuelle Sortierung "cut and paste" nicht mehr angewendet. Ich weiss das ist schon lange so bzw. noch. Hast das einen gewissen Grund?

**Comment by leofeyer** [comment]
Was genau meinst Du? Ich habe mal testweise in der Official Demo folgendes gesetzt:

```php
$GLOBALS['TL_DCA']['tl_page']['list']['sorting']['root'] = array(48);
```

Dann habe ich versucht, eine Seite per "cut and paste" zu verschieben, was ohne Probleme geklappt hat:

<img width="753" alt="" src="https://user-images.githubusercontent.com/1192057/49658825-398b8d80-fa43-11e8-994b-26bdc4a95ba8.png">

<img width="761" alt="" src="https://user-images.githubusercontent.com/1192057/49658874-4dcf8a80-fa43-11e8-87d7-36a00ebdfde4.png">

**Comment by timgatzky** [comment]
Filter die Ausgabe mal auf reine Kind-Seiten z.b. "Accordion, Content slider, Text elements".
Sind nur noch die Kind-Seiten (nicht mehr direktes Kind-Element) in der Liste, greift die Verschiebung nicht mehr.

**Comment by aschempp** [comment]
Ist das auch reproduzierbar wenn man entsprechende Berechtigungen an den Benutzer vergibt? Oder nur mit dem DCA Code?

**Comment by timgatzky** [comment]
Aufgefallen ist es mir durch eine Funktion in einer Erw. bei mir. Dort muss ein DCA Listing (Mode 5) auf diesem Weg reduziert werden. Falls Contao selbst auf diesem Weg Listings reduziert, wird es den gleichen Effekt haben - ich habe nicht explizit Benutzerrechte getestet (reiner Admin gerade)
Reproduzierbar ist es aber mit der dcaconfig.php, quasi Contao Standard an dieser Stelle.

**Comment by timgatzky** [comment]
Hi Leute, das Issue kann geschlossen werden.
Zum einen greift ab 4.4 hier auch die DCA Filterung, die wiederum Sortierungen berücksichtigt, zum anderen kann die ID Liste sortiert übergeben werden. Thx, Tim
