### ISSUE TITLE
Fehlerhafte deutsche Datumsausgabe

### ISSUE THREAD

**Issue by minstyle** [contao/core-bundle#1660]
- Contao 4.4.20
- PHP 7.2
- Deutsche Website mit eingestelltem Datumsformat "d.m.Y" und Zeitzone "Europe/Berlin"

In einem Contao-Formular habe ich ein "Textfeld" (als Pflichtfeld definiert), welches mit der Eingabeprüfung "Datum" versehen ist. Wird das Datum im Frontend nicht im Format TT.MM.JJJJ ausgefüllt, so erscheint folgende Fehlermeldung:

> Bitte geben Sie das Datum im Format "DD.MM.YYYY“ ein!

Hier sollte allerdings folgende Fehlermeldung stehen:

> Bitte geben Sie das Datum im Format "TT.MM.JJJJ“ ein!

**Comment by Toflar** [comment]
Lässt sich durch `$GLOBALS['TL_LANG']['DATE']` steuern, aber ich denke es wäre gut, wenn das via Transifex übersetzbar wäre.

**Comment by minstyle** [comment]
Du meinst eher `$GLOBALS['TL_LANG']['ERR']['date']`, oder?

**Comment by Toflar** [comment]
Nein, mein ich nicht.

```php
$GLOBALS['TL_LANG']['DATE']['D'] = 'T';
```

Geht ab der 4.5, vorher ist das nicht möglich.

**Comment by leofeyer** [comment]
> Geht ab der 4.5, vorher ist das nicht möglich.

Korrekt.

**Comment by Toflar** [comment]
@leofeyer Willst du nicht die Werte in die Sprachdateien aufnehmen? Dann können sie per Transifex übersetzt werden und wären ab der 4.6 dann für alle Sprachen defaultmässig drin. Sonst muss man sie immer nachführen bei jedem Setup.

**Comment by leofeyer** [comment]
Was genau meinst Du? Die Labels sind ab Contao 4.5 bereits drin.

**Comment by Toflar** [comment]
Ah, stimmt. Sorry.
