### ISSUE TITLE
Shorter name for two factor authentication

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#1661]
Here is what I stumbled across:

* 2 factor authentication
* 2 factor auth (not really sure about this)
* 2FA

Google also uses the term "2-step verification", although this is still longish.

@xchs @bytehead /cc

**Comment by leofeyer** [comment]
We could also just name the item "security". WDYT @contao/developers ?

**Comment by leofeyer** [comment]
<img width="601" alt="" src="https://user-images.githubusercontent.com/1192057/43953491-78f43858-9c99-11e8-9ccc-ff3240a2645c.png">

**Comment by leofeyer** [comment]
I actually like this. And if we add other security features in the future, we can simply append them.

**Comment by xchs** [comment]
> I actually like this

Me too.

**Comment by leofeyer** [comment]
Changed in 3d5191bfa1a5ccd72cde8ee2ca48db775226fd0c then.
