### ISSUE TITLE
File operation permissions on Filemounts broken since 4.5.10?

### ISSUE THREAD

**Issue by tim5chneider** [contao/core-bundle#1666]
Since I update to 4.5.10 User who have File operation permissions (Upload files to the server, Edit, copy or move files and folders and Delete single files and empty folders) on Filemounts with a specific User Group can't do this anymore.

For Test, i extend the group settings with the same File operation permissions on the same Filemounts. This works.

So whats wrong? My Settings or the update?
Does anybody has the same Issue?

**Comment by leofeyer** [comment]
Is this reproducible in the [online demo](https://demo.contao.org/contao)?

**Comment by tim5chneider** [comment]
Not reducible. Sorry for the long delay.
