### ISSUE TITLE
Version hint in BackendCustom without label

### ISSUE THREAD

**Issue by rabauss** [contao/core-bundle#1672]
The version hint in class `BackendCustom` is without label - see:
https://github.com/contao/core-bundle/blob/0e6ace663e45bf4e120b164e9db1c8109d9087b7/src/Resources/contao/controllers/BackendCustom.php#L54

The class `BackendMain` has a label:
https://github.com/contao/core-bundle/blob/0e6ace663e45bf4e120b164e9db1c8109d9087b7/src/Resources/contao/controllers/BackendMain.php#L112

either the label should be added in the backend template `be_main.html5` and removed in the `BackendMain` or the label should be added in the `BackendCustom`!

all contao 4.x versions are affected!

**Comment by leofeyer** [comment]
Fixed in contao/contao@214ef7bda4beaa52d0ba1cacb3cb23e9a9a601a8.
