### ISSUE TITLE
Contao version/ build not updating in backend

### ISSUE THREAD

**Issue by verkruemelt** [contao/core-bundle#1678]
I had run an update via composer:
![image](https://user-images.githubusercontent.com/1926264/49987564-fb76f800-ff73-11e8-8a79-d5890ae4862e.png)
core bundle was updated to **4.4.31**, I assumed I can see this version number in the backend too.
But unfortunatley the version in the backend still shows **4.4.20**:
![image](https://user-images.githubusercontent.com/1926264/49987634-3da03980-ff74-11e8-9b66-12b97b582d90.png)
as of installation.
The same in a test and production enviornment.

Is this a bug or an undocumented feature? :smile:

**Comment by fiedsch** [comment]
I can't confirm this, have never experienced this. 

In addition: the composer log states, that the update was from 4.4.30 to 4.4.31! So just to be sure: did you check the correct backend?

**Comment by verkruemelt** [comment]
Das ist richtig. Ich habe heute das Update durchgeführt von 4.4.30 zu 4.4.31. Auf beiden Systemen.
Aber im Backend wird mir einmal die Version 4.4.20 angezeigt und im zweiten System die 4.4.28.

Dies müsste jeweils die Version sein, mit der das jeweilige Contao installiert wurde - wenn ich mich richtig erinnere. Ich habe auch jeweils eine Systemwartung laufen lassen und die jeweilige Webseite per [Strg] + [F5] komplett neu laden lassen. Aber die alte Versionsnummer wird noch immer angezeigt.

**Comment by Toflar** [comment]
Maybe a modified `be_main` template?

**Comment by ausi** [comment]
Your screenshot of the composer output looks like there is something missing. Did you see the following lines in the output?

```
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

Please check if the file *vendor/ocramius/package-versions/src/PackageVersions/Versions.php* contains the correct version for `contao/core-bundle`.

**Comment by leofeyer** [comment]
Did you clear the cache?

**Comment by verkruemelt** [comment]
Where can I find this template

> Maybe a modified `be_main` template?

Nope


> Your screenshot of the composer output looks like there is something missing. Did you see the following lines in the output?
> 
> ```
> ocramius/package-versions:  Generating version class...
> ocramius/package-versions: ...done generating version class
> ```
> Please check if the file _vendor/ocramius/package-versions/src/PackageVersions/Versions.php_ contains the correct version for `contao/core-bundle`.

These lines are not in the output.
I can't find the folder `<root>/vendor/ocramius`, but ` <root>/vendor/contao/core-bundle/src/Resources/contao/classes/Versions.php`. But there is no version neither.

> Did you clear the cache?

Yep!

**Comment by xchs** [comment]
Rename `composer.lock` to `composer.lock.bak` and run a complete Composer update.

**Comment by fritzmg** [comment]
Also confirm which composer version you are currently using.

**Comment by verkruemelt** [comment]
```
composer --version
Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead.
Composer 1.6.3 2018-01-31 16:28:17
```
newest version is 1.8.0... *will update*
after complete composer Update: HTTP 500
Apache Error log:
```
PHP Fatal error:  Uncaught RuntimeException: Unable to create the store directory (/var/www/html/cms/var/cache/prod/http_cache).
```

**Comment by xchs** [comment]
Is the directory writable or have you reached the disk quota?

**Comment by verkruemelt** [comment]
Owner or files/ folders set to www-data after composer update (per script), Disk quta not reached.

**Comment by ausi** [comment]
>> Did you clear the cache?
>
> Yep!

Can you please try if manually deleting the folders `var/cache/prod` and `var/cache/dev` resolves the problem?

**Comment by aschempp** [comment]
Be aware that the versions are not stored in the cache. They are stored in the vendor folder.

```
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

This is the only relevant suggestion. If this does not appear, there is an issue with your composer update. Or you did run it with `--no-plugins` flag or thelike. Somehow, the versions plugin is not updated. You will most likely find the wrong version in `vendor/ocramius/package-versions/src/PackageVersions/Versions.php`

**Comment by leofeyer** [comment]
I don't think so.

**Comment by leofeyer** [comment]
> Can you please try if manually deleting the folders `var/cache/prod` and `var/cache/dev` resolves the problem?

@verkruemelt Did you try this and did it solve the issue?
