### ISSUE TITLE
List of language keys to be altered.

### ISSUE THREAD

**Issue by discordier** [contao/core-bundle#168]
Posting here a list of all language keys that now have an entirely different meaning and/or are obsolete now.

| Key | Part to change | Reason | 
| ------ | ----- | ---- |
| [tl_install.changePass.1](https://github.com/contao/core-bundle/blob/7b1d8995253edecdd71a11ee4d9eda1f861b009a/src/Resources/contao/languages/en/tl_install.xlf#L26) | - remove all - | The install tool can not be deleted anymore |

**Comment by leofeyer** [comment]
Since the table is not maintained, are you ok with me closing the ticket? I have already updated the one key mentioned above.

**Comment by discordier** [comment]
I am completely ok. I just thought others might want to add theirs as well.
