### ISSUE TITLE
Unvollständige Navigation nach Update auf Contao 4.7.5

### ISSUE THREAD

**Issue by cgoIT** [contao/core-bundle#1688]
**Affected version(s)**
Contao 4.7.5

**Description**  
Ich habe ein Problem, sobald ich Contao 4.7.5 installiere. Mit dieser Version wird meine Navigation nicht mehr vollständig gerendert. Es steht leider kein Eintrag in irgendeinem Log (Server, Contao), so dass ich an dieser Stelle nicht weiterkomme.
Ich habe die Vermutung, dass alle Seite in der Navigation **_nicht_** erscheinen, die als interne Weiterleitung mit einem Response-Code 301 angelegt sind. Reguläre Seite erscheinen ganz normal in der Navigation.

Stelle ich mich nur zu blöd an oder kann das jemand nachvollziehen. Ich bin mir fast sicher, dass es an mir liegen muss, da ich davon ausgehe, dass dieses Problem ansonsten ganz viele Leute hätten.

**How to reproduce**  
Seitensstruktur mit Seiten vom Typ "interne Weiterleitung" anlegen.

**Comment by xchs** [comment]
Siehe https://github.com/contao/contao/issues/466

**Comment by cgoIT** [comment]
Danke für den Hinweis. Hatte zwar gesucht aber nichts gefunden. Dann weiß ich wenigstens, dass es nicht an mir liegt. ;)
