### ISSUE TITLE
[meta] Porting of imi-conrun feature which are missing in contao-console 

### ISSUE THREAD

**Issue by amenk** [contao/core-bundle#1689]
A while ago we created [imi-conrun](https://github.com/iMi-digital/imi-conrun) with the same aim which contao-console is now fulfilling. 

These are the commands of imi-conrun:

```
script                      Runs multiple imi-conrun commands
admin
  admin:user:change-password  Changes the password of a adminhtml user.
  admin:user:create           Create admin user.
  admin:user:delete           Delete the account of a adminhtml user.
  admin:user:list             List admin users.
 cache
  cache:build                 Build internal cache
  cache:flush                 Clean all cache folders
  cache:list                  Lists all Contao caches
 db
  db:console                  Opens mysql client by database config from local.xml
  db:create                   Create currently configured database
  db:drop                     Drop current database
  db:dump                     Dumps database with mysqldump cli client according to informations from local.xml
  db:import                   Imports database with mysql cli client according to database defined in local.xml
  db:info                     Dumps database informations
  db:maintain:check-tables    Check database tables
  db:query                    Executes an SQL query on the database defined in local.xml
  db:status                   Shows important server status information or custom selected status values
  db:variables                Shows important variables or custom selected
 dev
  dev:log:follow              Follow Database Log (tl_log)
 indexer
  indexer:search:build        Build search index
 sys
  sys:info                    Prints infos about the current contao system.
  sys:maintenance             Toggles maintenance mode.
  sys:setup:preview           Compare module version with core_resource table.
  sys:setup:run               Runs all new database update scripts.
 thirdparty
  thirdparty:efg:build-dca    Build DCAs for EFG
```

We are planning to port the missing features to contao console commands and deprecate imi-conrun (which works fine for Contao 3.x but no longer for 4.x)

Are there any thoughts about this?

Otherwise we would just make according pull requests.

**Comment by amenk** [comment]
About the db commands we are not yet sure whether we port them ... if we port them, we would sure use https://github.com/imi-digital/database-helper for providing the functionality.

The first command we would start with would be `sys:setup:run` to run database upgrades after installing modules.

**Comment by m-vo** [comment]
Please do not use this repo for opening issues anymore (use the `contao/contao` mono repo instead).

likely related: https://github.com/contao/contao/issues/404

**Comment by leofeyer** [comment]
As discussed in Mumble on August 29th, the following command would be interesting for us:

* `contao:user:create`
* `contao:user:list`
* `contao:user:delete`

The other commands either already exist (e.g. `contao:user:password`) or there are other tools, which already provide the functionality.

**Comment by leofeyer** [comment]
See contao/contao#1463.
