### ISSUE TITLE
Add option to disable "Lato Retina"

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#1701]
Hello,

I just testen a Contao installation on my new Dell 4k Monitor. Unfortunately for my taste the font is waaay to thin. Especially when it comes to horizontal strokes, it's so thin it's not even the main color of the font.

I know I can change that easily. But I don't have access to all Contao installations I'm using ;-) So a feature "disable high dpi font optimzation" (or think of a better name ;-) ) next to the option to limit the CMS's width would be great.

Is this an option? Of course I could write a pull request for that.

Bye Defcon0

**Comment by m-vo** [comment]
Lato was already dropped in favor of a native font stack.

see e.g. https://github.com/contao/contao/issues/98

Also: Please create new issues in `contao/contao` monorepo.

**Comment by Defcon0** [comment]
Ah, I see. Thanks for the hint.
