### ISSUE TITLE
Insert-Tag {{session::*}}

### ISSUE THREAD

**Issue by syntaxys** [contao/core-bundle#1704]
**Description**  
For pre-filling a form with auto-generated content I used in Contao 3 the extension _inputvar_ which unfortunately is orphaned. Writing and publishing an extension for that purpose would be a lot more to do …

Would it be a big deal to add some lines to
_core-bundle/src/Resources/contao/library/Contao/InsertTags.php_
for handling session stored data in the frontend in an easy way like with {{post::*}}? I've added these 4 lines up from line 576 which served my needs:

**Example**  
```
// SESSION data
case 'session':
	$arrCache[$strTag] = $this->Session->get($elements[1]);
	break;
```

**Comment by leofeyer** [comment]
The `{{post}}` insert tag already accesses `$_SESSION['FORM_DATA']` if the request is not a POST request. Maybe you can use this in your installation?
