### ISSUE TITLE
Closed FE Preview leaves preview.php in URL

### ISSUE THREAD

**Issue by Anke** [contao/core-bundle#1707]
I noticed in two different installations (4.8.4 and 4.8.5) that after closing the preview bar "preview.php" remains in the URL and all links on the page/site (https://domain.de/preview.php/page.html). Is this a bug or meant to be this way for some reason?

**Comment by leofeyer** [comment]
Closing the preview bar does not disable the debug mode, therefore, yes, it is meant to be this way.
