### ISSUE TITLE
Date and number formatting in Symfony 2.7

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#171]
http://symfony.com/blog/new-in-symfony-2-7-default-date-and-number-format-configuration

Looks similar to our current config, so we might want to adapt that.

**Comment by leofeyer** [comment]
We should probably set the Twig default values depending on the current language?

**Comment by aschempp** [comment]
I guess you mean because of the number formatting? Problem is, it's actually bound to the locale. The swiss german format is different than the german format. 

I know that's possible with a de_CH language pack, but I wouldn't set my root page to de_CH if there is no de_DE…

**Comment by leofeyer** [comment]
Will you be working on this issue for Contao 4.1 or shall I change the milestone to 4.x.x?

**Comment by aschempp** [comment]
We should discuss if this is really applicable to us. Please assign `up for discussion`.

**Comment by Zeromax** [comment]
It's off topic, but are you interessted in https://overv.io/?
It is a really good Tool to handle the Issues in an Agile way.

**Comment by leofeyer** [comment]
As discussed on Mumble on November 5th, this "haut so nicht hin" (@discordier).
