### ISSUE TITLE
[4.9.X] - Porting the UserCreateCommand class

### ISSUE THREAD

**Issue by katgirl** [contao/core-bundle#1720]
Please provide the User CreateCommand class in 4.9.X. In 4.9.11 it works without any problems

https://github.com/contao/core-bundle/commit/72c8a9b9bdaf56965fc858b5167f2a6e7fe02b0a

**Comment by m-vo** [comment]
You can do this in an extension/your application. 4.9 is feature complete, so there won't be new ones.
