### ISSUE TITLE
OptInToken.php Mail-Instanz: Absender aus config.yml wird nicht beachtet

### ISSUE THREAD

**Issue by derMatze82** [contao/core-bundle#1722]
Contao Version: 4.12.3

Hat man über die config.yml einen Mailer-Transport und zusätzlich "from" definiert, wird dieser Wert beim Versenden der Aktivierungs-Mail des Registrierungs-Moduls nicht beachtet , sondern der Wert "E-Mail-Adresse des Systemadministrators" verwendet.
Dies kann bei einigen SMTP Servern dazu führen, dass die Mail nicht versendet werden kann.
Das Notification Center z.B. beachtet dieses Einstellung aus der config.yml

**Comment by fritzmg** [comment]
Also duplicate of https://github.com/contao/contao/issues/3573

**Comment by fritzmg** [comment]
@derMatze82 regardless of this being the wrong repository: did you enable the respective mailer transport in your website root? If not, then the config will not be considered. No `from` address will be considered for the default mailer transport.

**Comment by derMatze82** [comment]
@fritzmg thanks for the hint, I didn't notice this setting at the website root.
