### ISSUE TITLE
Problem with users and session

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#179]
The user session storage currently does not work. Sessions are stored using a `register_shutdown_handler`, but at that point Symfony has already closed the session to send the response.

My quick idea was to use a `kernel.response` or `kernel.terminate` handler (same as Symfony uses for session). What do you think?

**Comment by leofeyer** [comment]
+1

**Comment by Toflar** [comment]
I remember, there was another ticket regarding "referer management broken" (I can't find it, wtf), that's 99% related to this one :)

**Comment by leofeyer** [comment]
It is here: #143

**Comment by leofeyer** [comment]
This issue has been fixed, but it seems that the fix introduced a new issue: https://github.com/contao/core-bundle/issues/143#issuecomment-94388947
