### ISSUE TITLE
Switch from MyISAM to InnoDB

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#188]
See https://github.com/contao/core-bundle/issues/113#issuecomment-84988122.

**Comment by fbender** [comment]
One possibility would be omitting the storage engine so the system can use its default engine. Since fulltext indexing is only available since MySQL 5.6, another option is to detect InnoDB+fulltext support and dynamically upgrade from MyISAM to InnoDB where possible.

**Comment by leofeyer** [comment]
As discussed on Mumble on April 21st, it only makes sense to switch to InnoDB if we can remove the (estimated) 800 lines of code of the `DC_Table` class, which keeps the referential integrity. We should instead use InnoDB's foreign key constraints.

**Comment by m-vo** [comment]
Even if the core keeps using ``MyISAM`` until it's [not supported anymore ](https://www.percona.com/blog/2016/10/11/mysql-8-0-end-myisam/);-), don't we want to have a dca property to select the engine (or a setting on a per bundle level)? Database abstraction aside, it's a problem to be restricted to an engine that does not support transactions (nor triggers). 

Btw., I have a use case where I need to synchronize concurrent access. Currently the only way to work around this is something like an 'after installation' pass where I manually change the table's engine to ``InnoDB``.

**Comment by m-vo** [comment]
(@aschempp Just wondered how e.g. isotope works around this when ordering products with a limited availability?)

**Comment by aschempp** [comment]
First of all, Isotope does not support product availability. But I'm generally using lock mechanism to work around concurrent access issues.

**Comment by leofeyer** [comment]
Changed in 83af27b57229ada7ac36d270f3c79c315ceb0b07 now.

**Comment by agoat** [comment]
Superb.
I'm just wondering what it looks like after an update. Will the tables be rewritten on the InnoDB engine?

**Comment by leofeyer** [comment]
No, they will not. You have to do it yourself if you want to change the engine. I'm planning to publish a little update script though.

**Comment by leofeyer** [comment]
Yes, the install tool will offer to merge the table engine and collation.
