### ISSUE TITLE
Set _locale for backend user

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#190]
see http://symfony.com/doc/current/cookbook/session/locale_sticky_session.html

This should replace `TL_LANGUAGE` both in `$GLOBALS` and `$_SESSION`.

**Comment by Toflar** [comment]
:+1:

**Comment by leofeyer** [comment]
Will you create a PR?

**Comment by aschempp** [comment]
I'm on it.

**Comment by aschempp** [comment]
See #237
