### ISSUE TITLE
[RFC] Split up the InitializeSystemListener

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#192]
We currently have the problem that our `InitializeSystemListener ` is pretty complex and does way too much to be tested thoroughly. For instance, it extends our `ScopeAwareListener` which means that whatever you test, you need to set a container to it even if that specific part of the listener you want to test is not related to any container at all.

Also related to https://github.com/contao/core-bundle/issues/175 I think we should really go about this again. I feel like the `InitializeSystemListener` is correctly placed but the components are wrong.

My approach (simplified):

```php
class InitializeSystemListener
{
    private $framework;

    public function __construct(ContaoFramework $framework)
    {
        $this->framework = $framework;
   }

    public function onKernelRequest(GetResponseEvent $event)
    {
        $this->framework->boot();
    }
}
```

```php
class ContaoFramework
{
    public function boot()
    {
        $bootEvent = new BootEvent();
        $this->eventDispatcher->dispatch(ContaoEvents::BOOT_FRAMEWORK, $bootEvent);
    }
}
```

This provides the possibility to have all our other responsibilities such as

* Setting constants
* Setting ini values
* Setting default language
* Error handling
* Validating the installation
* etc.

in their very own listeners listening to `ContaoEvents::BOOT_FRAMEWORK` and they only get the things injected they need :-)

* CoreBundle
    * Listener
        * BootFramework
            * SetConstantsListener.php
            * ValidateInstallationListener.php
            * etc.

RFC ;-)

**Comment by leofeyer** [comment]
Reminds me a lot of #60, in which you guys have voted against changing the listener :)

**Comment by Toflar** [comment]
“you guys” = @aschempp. If you read the comments...

**Comment by leofeyer** [comment]
:D

**Comment by leofeyer** [comment]
IMHO, we should at least create listeners for the non-legacy stuff such as checking for the `/web` subfolder.

**Comment by aschempp** [comment]
I agree we could rewrite it, if we implement something like #175. But we should be aware that doing that will open third-party developers new possibilities for the legacy code. If we do that, we need to think about replacements for stuff like deprecating `iniconfig.php` or fire a real event for `initializeSystem` hook.

Same as @leofeyer wrote in #175, it does not have a very high priority to me (because the current solutions works, and we can easily change everything in any minor release because nothing is API).

**Comment by Toflar** [comment]
> But we should be aware that doing that will open third-party developers new possibilities for the legacy code.

Why do you think it would give them new possibilities?

**Comment by aschempp** [comment]
Because they can subscribe to the same events…

**Comment by Toflar** [comment]
So what? They can also call `Contao\System::whatever()` instead of using new ways if they want to. They can always do wrong things, that should not be our problem :-)

**Comment by discordier** [comment]
Reminds me a lot of the way we work in MetaModels. :)

We have a subsystem boot event and another event for each of frontend and backend.
The developers can therefore attach to the common "boot" event or just the frontend or backend booting.

I wonder however how your framework class is setup though.
Does it only have the boot method or does it get references (and holds them) to the config adapter etc.?

**Comment by Toflar** [comment]
> Does it only have the boot method or does it get references (and holds them) to the config adapter etc.?

Just the boot method. If your listener needs the config or the container scope etc., it should get it injected on its own.

**Comment by dtomasi** [comment]
Could I leave a suggestion ?? ;-)

I think Events should not be dispatched in a Listener. Wouldn´t it be better to wrap this into a service? 
This could also be a lazy service

Maybe something like this: 

services.yml

```yaml
contao.framework_loader:
        class: Contao\CoreBundle\SomeNamespaceThatMakesSence\ContaoFrameworkLoader
        lazy: true
        arguments:
             - "@event_dispatcher"
```


```php
class ContaoFrameworkLoader
{
	private $isBooted = false;
	
	private $eventDispatcher;
	
	public function __construct(EventDispatcher $eventDispatcher)
	{
		$this->eventDispatcher = $eventDispatcher;
	}

	public function boot(Request $request = null) 
	{
		if ($this->isBooted()) {
			return;
		}
		
		$bootEvent = new ContaoFrameworkBootEvent();
		
		if ($request) {
			$bootEvent->setRequest($request);
		}
		
                // Eventdriven Boot-Sequence goes here
		$this->eventDispatcher->dispatch(
			ContaoEvents::BOOT_FRAMEWORK, 
			$bootEvent
		);
		
		$this->isBooted = true;
	}
	
	public function isBooted() 
	{
		return $this->isBooted;
	}
}
```

And then use the service in `InitializeSystemListener`

```php
class InitializeSystemListener
{

    public function onKernelRequest(GetResponseEvent $event)
    {       
    	$loader = $this->container->get('contao.framework_loader');
    
        if (!$this->isFrontendScope() && !$this->isBackendScope()) {
            return;
        }
        $request = $event->getRequest();

        $route = $this->router->generate(
            $request->attributes->get('_route'),
            $request->attributes->get('_route_params')
        );

        $basePath = $request->getBasePath();

        $this->setConstants(
            $this->getModeFromContainerScope(),
            substr($route, strlen($basePath) + 1),
            $basePath,
            $request->attributes->get('_contao_referer_id')
        );

        $loader->boot($request);
    }
    
    public function onConsoleCommand()
    {
    	$loader = $this->container->get('contao.framework_loader');
		$loader->boot();
    }
}

```

of course this is not tested... 

What do you think??

**Comment by aschempp** [comment]
@dtomasi isn't that exactly what @Toflar in his original post?

**Comment by dtomasi** [comment]
@aschempp is it? I don´t think so. Or should `ContaoFramework` be a service?

**Comment by dtomasi** [comment]
of course, the `lazy` option does not make sense if it is called on `kernel.request` and `Console::COMMAND` ... that´s for sure ...

**Comment by Toflar** [comment]
It is exactly what I suggested :D

**Comment by dtomasi** [comment]
@Toflar then I would say: this is a really good suggestion :smile:

**Comment by leofeyer** [comment]
@Toflar Will you create a PR for this?

**Comment by Toflar** [comment]
Some day, yes.

**Comment by dtomasi** [comment]
@leofeyer I talked to @Toflar and will do the PR for him.

**Comment by leofeyer** [comment]
Thank you for your help.
