### ISSUE TITLE
Change the namespace of the TokenGenerator class

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#195]
I think [this class](https://github.com/contao/core-bundle/blob/develop/src/RefererId/TokenGenerator.php) should be in the namspace `Contao\CoreBundle\Security\Csrf`

https://github.com/symfony/symfony/tree/2.7/src/Symfony/Component/Security/Csrf

**Comment by Toflar** [comment]
Nope, I did not place it there because it's

a) Not related to "Security"
b) Not related to "Csrf"

**Comment by aschempp** [comment]
It absolutely is, you're extending the Symfony class ` Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator`
see https://github.com/contao/core-bundle/blob/develop/src/RefererId/TokenGenerator.php#L13

**Comment by aschempp** [comment]
It's actually not related to `RefererId`, we're just using it for that ;-)

**Comment by Toflar** [comment]
No and no. It's just correct the way it is, that's why I placed it there.

**Comment by leofeyer** [comment]
I'm with @aschempp on this one.

**Comment by Toflar** [comment]
Then let's discuss on Wednesday because I'm **clearly** against it. It has nothing to do with security at all. No matter what components it uses. Obviously I thought about that too when I developed it but again, it's totally wrong in the `Security` namespace that's why it is in its own.

**Comment by leofeyer** [comment]
> It has nothing to do with security at all. 

That's true indeed.

**Comment by aschempp** [comment]
> It has nothing to do with security at all.

How come Csrf it's part of the Symfony Security component then?

**Comment by Toflar** [comment]
Because Csrf is about Security?

**Comment by aschempp** [comment]
And this is a Csrf Token Generator. We're using it for the Referer ID, but the class is not bound to that. That's as if you would place the `String` class in `Templates` namespace because you can use it to encode template values…

**Comment by Toflar** [comment]
> And this is a Csrf Token Generator.

No, it is a Referer ID token generator using third party components. It could also use any other library that generates URL safe tokens (enjoy: https://packagist.org/search/?q=token%20generator) but it was simple to use the Csrf Token Generator of Symfony.

> That's as if you would place the String class in Templates namespace because you can use it to encode template values…

Sorry, but that's just a nonsense comparison. The `TokenGenerator` is a class that covers one use case only whereas your general `String` class is a general purpose class. How can you even compare this?

**Comment by leofeyer** [comment]
As discussed on Mumble on May 6th, we want to change the namespace to `Referer`.

**Comment by leofeyer** [comment]
Fixed in 3287e89a8c70bddd16ea4e6338b719c90f140741.
