### ISSUE TITLE
postFlushData is useless

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#196]
The [`postFlushData`](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/library/Contao/Template.php#L275) hook is never executed, especially after merging #70. I suggest to remove it and add an upgrade information.

Btw. I also thought about calling the hook in `kernel.terminate` but we do not have the arguments available so that's probably pretty useless…?

**Comment by Toflar** [comment]
:+1: for removing it. Same for the `initializeSystem` hook. Both can be replaced by using regular kernel events.

**Comment by aschempp** [comment]
I would not remove `initializeSystem` as there is no reason to do so. It works perfectly fine (whereas `postFlushData` will not).

**Comment by leofeyer** [comment]
It is executed if someone uses the deprecated `output()` method, isn't it?

**Comment by aschempp** [comment]
Yeah, but it is very unreliable. That's why I suggest to remove it completely and tell people not to use it anymore (instead of hoping it still works).

**Comment by discordier** [comment]
That hook was the reason why I had an FIXME instead of a `@deprecated` in that method before.

I have to admit that I tend towards the opinion of @aschempp of removing it. We could throw an response exception then from there.

@leofeyer Could you grep the ER2 packages how many are in fact using that hook (would be nice to know for the other hooks also)?

**Comment by leofeyer** [comment]
It is not unreliable at all. In fact, it is the same code than in the Symfony `Response` class :)

**Comment by aschempp** [comment]
> It is not unreliable at all.

I did mean it unreliable to be executed, because it would only happen for old custom page controllers.

**Comment by leofeyer** [comment]
Therefore we should keep it until we officially drop the `output()` method, shouldn't we?

**Comment by aschempp** [comment]
Again: I'm voting to remove it. People should not use it because it is unreliable/not executed by default.

**Comment by Toflar** [comment]
Same here: Voting for removal.

**Comment by leofeyer** [comment]
> People should not use it because it is unreliable/not executed by default.

Ok, so you are only suggesting to remove the hook, not the method, right?

**Comment by aschempp** [comment]
Exactly.

**Comment by leofeyer** [comment]
Then +1.

**Comment by leofeyer** [comment]
Removed in e3b81ca4ed6dc04f9b2c9f4b362a93a64a220000.
