### ISSUE TITLE
Increase the external_code_coverage.timeout

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#198]
The number of failed inspections in Scrutinizer increases, because Travis is taking forever to run the tests (30 minutes and more). What shall we do about it?

1. Increase the `external_code_coverage.timeout` setting?
2. Add the `--testsuite latest` argument so Travis does not run the legacy tests?

**Comment by aschempp** [comment]
I'm fine with 2 (not running the legacy tests). Maybe we can run all on branches but not on PRs?

**Comment by leofeyer** [comment]
Don't know if this can be configured.

**Comment by aschempp** [comment]
You mean if the parameter can be added? Just execute the test suite manually (see http://docs.travis-ci.com/user/build-configuration/#Define-custom-build-lifecycle-commands)

**Comment by leofeyer** [comment]
I have adjusted the configuration so we can continue to work in c1ad97bb7dba3b24f2c11a7914a59da1d7645bd1. Still have to discuss a better solution.

**Comment by leofeyer** [comment]
As discussed on Mumble on April 21st, this is currently the only possibility. The situation might improve once we have adapter classes for all legacy classes.
