### ISSUE TITLE
Move error CSS into namespace or assets

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#199]
See https://github.com/contao/core-bundle/pull/70#discussion_r28313240

/cc @discordier

**Comment by leofeyer** [comment]
Since we only have one layout template now, why don't we store the CSS code in it directly?

**Comment by aschempp** [comment]
I would like that too.

**Comment by leofeyer** [comment]
Changed in 770411074d94a3b093bc7d654eabe4d64546f986.

**Comment by discordier** [comment]
Could you make a block out of it so people can change only the CSS again?

**Comment by leofeyer** [comment]
Changed in 81b06b3a276fefbeaaca13831625dccb5b7bf3ab.
