### ISSUE TITLE
Use @twig services instead of @templating in Symfony 2.7

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#202]
See https://github.com/contao/core-bundle/pull/70#discussion_r28314760

**Comment by leofeyer** [comment]
Will you create a PR?

**Comment by leofeyer** [comment]
@aschempp Any kind of feedback? :smiley:

**Comment by aschempp** [comment]
I can create a PR, probably next week.

**Comment by leofeyer** [comment]
I tried it today but I didn't get it to work with Symfony 2.7-BETA1.

**Comment by leofeyer** [comment]
Fixed in 5e17cc17f3a7aee2724b7f7c95567e4683d6f889.
