### ISSUE TITLE
Config::isComplete() should not check for dbDriver

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#203]
Since the database connection is configured via the *config.yml*, `Config::isComplete()` should not check for `dbDriver` in [Config.php:315](https://github.com/contao/core-bundle/blob/e2831271270198a3140cc6f619b2175fe93bc291/src/Resources/contao/library/Contao/Config.php#L315).

After setting up Contao 4.0.0-beta1 I always got an “503 - Incomplete installation” until I added `$GLOBALS['TL_CONFIG']['dbDriver'] = 'MySQLi';` to *system/config/localconfig.php*.

**Comment by bytehead** [comment]
Got the same problem. But that piece of `dbDriver` won't be used anyway due to doctrine, am I right?

**Comment by ausi** [comment]
> But that piece of dbDriver won't be used anyway due to doctrine, am I right?

I think so, `$GLOBALS['TL_CONFIG']['dbDriver'] = 'foo';` works also :)

**Comment by leofeyer** [comment]
> But that piece of `dbDriver` won't be used anyway due to doctrine, am I right?

Correct. The check has to be removed (and probably also the encryption key check if it is still in there).

**Comment by leofeyer** [comment]
Fixed in c3833b4a334481c6fc7898c62b00bfc310879022.
