### ISSUE TITLE
Destructors don’t get executed

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#206]
Because the registered shutdown function `BackendUser::storeSession()` results in a fatal error *“Failed to start the session because headers have already been sent”* some `__destruct`ors don’t get executed, e.g. `Config::__destruct()`.

Because of that, things like changing settings or disabling maintenance mode via the backend doesn’t work and fails silently without an error message.

**Comment by Toflar** [comment]
I tackled the User issue with: https://github.com/contao/core-bundle/pull/207

**Comment by leofeyer** [comment]
This should be resolved after we have merged #207.

**Comment by aschempp** [comment]
?
This can be closed if @Toflar is fixing that in #207

**Comment by leofeyer** [comment]
I left it open so I don't forget to check if the PR really fixes the issue.

**Comment by leofeyer** [comment]
It did :)
