### ISSUE TITLE
Custom language files without XLIFF

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#211]
If an extension loads a custom language file e.g. `tl_my_extension` which only exists as a PHP file an InvalidArgumentException gets thrown `The file "languages/en/tl_my_extension.xlf" does not exist`.

Probably [System.php:343-349](https://github.com/contao/core-bundle/blob/44f67aa887acd1e16555809acd0a137f05dba6aa/src/Resources/contao/library/Contao/System.php#L343-L349) should also be wrapped in a try-catch block.

**Comment by leofeyer** [comment]
Fixed in 959110bda02647edfe4c0cf6b758839592fb7cf4.

**Comment by ausi** [comment]
Should we add a counter and throw an exception if no language file was loaded at all?

**Comment by leofeyer** [comment]
No, because then we would have to check for DCA files like `tl_cron.php`, which do not have a corresponding language file.
