### ISSUE TITLE
Controller::replaceOldBePaths() is missing for ajax requests

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#212]
If you select a file with the fileTree widget it gets reloaded via ajax and after that the href is pointing to `contao/file.php?…`. This is because in [Ajax.php:333](https://github.com/contao/core-bundle/blob/44f67aa887acd1e16555809acd0a137f05dba6aa/src/Resources/contao/classes/Ajax.php#L333) a call to `Controller::replaceOldBePaths()` is missing. This issue probably occurs also in other ajax actions.

**Comment by leofeyer** [comment]
Fixed in bdfd7f33b9379caee5a5ae8ccd07d34149e977a7.
