### ISSUE TITLE
2-level nested public folders get the wrong icon

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#213]
If you have the folder `files/test1/test2/test3`, mark `files/test1` as public and open the subfolders of it via ajax requests the protected icon gets displayed:

![nested-folders](https://cloud.githubusercontent.com/assets/367169/7178581/4e642654-e430-11e4-8fd4-6faeb0b9a849.png)

After reloading the page all icons are correct:

![nested-folders-correct](https://cloud.githubusercontent.com/assets/367169/7178603/7401ad96-e430-11e4-82a4-f515bcd868cd.png)

**Comment by leofeyer** [comment]
Fixed in d151fbe5900f7f4b49ebe2a53028a5143f1f179f.
