### ISSUE TITLE
Page picker wizard doesn’t insert {{link_url::*}}

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#217]
If you create an image content element and select a page for “Image link target”, the ID of the page gets inserted without the insert tag.

Can be fixed by replacing the regular expression in [assets/js/core.js:870](https://github.com/contao-components/contao/blob/fb3dd793021ce9d021413504a9b216886dbb2fe5/js/core.js#L870) with `/contao\/page(\?|$)/`. There are more occurrences of `page.php` and `file.php` in [core.js](https://github.com/contao-components/contao/blob/fb3dd793021ce9d021413504a9b216886dbb2fe5/js/core.js).

**Comment by leofeyer** [comment]
Fixed in b914d04861bd27e214e13addf5589a76250d82fe.
