### ISSUE TITLE
Template::getTemplate() is no longer used by TemplateInheritance

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#218]
In Contao 3 it was possible to extend from `FrontendTemplate` and change how the template paths get resolved by overwriting the `getTemplate` method. E.g.:

```php
class MyTemplate extends FrontendTemplate {
	public static function getTemplate($template, $format = 'html5') {
		// Custom logic...
		return $path;
	}
```

This is no longer possible because `TemplateInheritance` calls `getTemplate()` on `Controller` in [TemplateInheritance.php:81](https://github.com/contao/core-bundle/blob/808bc63862816b7143b1f6abb8182cf8967a95e6/src/Resources/contao/library/Contao/TemplateInheritance.php#L81).

I’m using that in an extension, but I don’t know how common that is and if other extensions are doing the same. If you agree that this is an issue I can make a pull request.

**Comment by leofeyer** [comment]
How would you resolve it?

**Comment by ausi** [comment]
I’m not sure. Adding a `getTemplate` method to `TemplateInheritance` and calling `Controller::getTemplate()` from there?

**Comment by leofeyer** [comment]
But the `Controller` class already has a `getTemplate()` method and since the `Template` class extends `Controller`, I don't know if that would work. But we could simply give the method another name :)

**Comment by ausi** [comment]
> But we could simply give the method another name :)

It wouldn’t be backwards compatible then but much cleaner than overwriting a method of a parent class with a trait I guess :)

Should I create a pull request with a `TemplateInheritance::getTemplatePath($strTemplate, $strFormat='html5', $default = false)` method?

**Comment by leofeyer** [comment]
Yes. And the method should be protected.
