### ISSUE TITLE
Get rid of the dummy classes in test suite

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#226]

**Comment by leofeyer** [comment]
It won't be possible. You cannot make the legacy code use the mocked classes.

**Comment by aschempp** [comment]
I know you can give mocked classes a name, so if they would have the "correct" name wouldn't that work because the autoloader is not triggered?

**Comment by Toflar** [comment]
I'll give it a shot sometime, just assign this to me :)

**Comment by leofeyer** [comment]
Done. Would be great if you got it to work!

**Comment by Toflar** [comment]
Closing this in favor of https://github.com/contao/core-bundle/pull/241 where the WIP is.
