### ISSUE TITLE
Improve utf8_romanize

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#228]
Ich habe bei meinen blackfire.io-Tests auch gesehen, dass diese Funktion einer der grössten Bottlenecks ist, die Contao noch hat. Ich denke also es wäre sehr sinnvoll, hier ein bisschen Research reinzustecken. Insbesondere, weil wir uns für die 3.5 für PHP 5.4 entschieden haben und nun den Transliterator nutzen könnten: http://php.net/manual/en/class.transliterator.php

Ausserdem hab ich noch ein Package mit 3.5 Millionen Downloads gefunden, welches versucht, die ganzen iconv, Intl und mbstring Sachen zu abstrahieren und je nach System das schnellste zu wählen: https://github.com/tchwork/utf8
Ein return \Patchwork\Utf8::toAscii($str); dürfte womöglich das gleiche Resultat wie bei uns bieten und einiges schneller sein. Die prüft übrigens auch darauf ob überhaupt UTF-8-Ranges betroffen sind (https://github.com/tchwork/utf8/blob/master/class/Patchwork/Utf8.php#L42).

**Comment by leofeyer** [comment]
Siehe auch: https://github.com/contao/core/issues/7748

**Comment by Toflar** [comment]
@aschempp are you trying to use the PHP core `Locale` for #190? Because if so, I guess we can get rid of our own language and country lists and use Symfony's `Intl` component which will provide a fallback for English if the php `intl` extension is not installed :) :) :) Obviously this will improve performance quite a bit!

```php
// Displays an "alphabetically" ordered list of country names in Japanese
use Symfony\Component\Intl\Intl;
\Locale::setDefault('ja');
$countries = Intl::getRegionBundle()->getCountryNames();
print_r($countries);
```

```php
// Displays an alphabetically ordered list of country names in French
use Symfony\Component\Intl\Intl;
\Locale::setDefault('fr');
$countries = Intl::getRegionBundle()->getCountryNames();
print_r($countries);
```

```php
Displays an alphabetically ordered list of languages in German (even "Schweizerdeutsch" is available :-D)
use Symfony\Component\Intl\Intl;
\Locale::setDefault('de');
$languages = Intl::getLanguageBundle()->getLanguageNames();
print_r($languages);
```

**Comment by aschempp** [comment]
@Toflar I'm not, because we don't need any names. But Symfony does set `Locale` (see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpFoundation/Request.php#L1940).

**Comment by Toflar** [comment]
Yes, I know. And it does it in a listener and uses `kernel.default_locale` as fallback if `$request->attributes->get('_locale')` is not available. That's why I was asking: Are you trying to set the `_locale` attribute to the currrent request depending on the browser language, back end user settings, page settings etc.? If so, we can modify `System::getCountries()` and `System::getLanguages()` :)

**Comment by aschempp** [comment]
Dunno how that is related to the system methods, but anyway…
The problem/point is, we do not know the language until a page is loaded. Which is way later than the `kernel.request` listeners. So we need to set/change the language multiple times.

Basically, what I'm working on should replace `$GLOBALS['TL_LANGUAGE']` with `$request->getLocale()` (though "language" and "locale" are not the same thing, see http://en.wikipedia.org/wiki/Locale)

**Comment by Toflar** [comment]
> Dunno how that is related to the system methods, but anyway…

Because we don't need to ship our own `countries.php` and translations for them anymore.

> The problem/point is, we do not know the language until a page is loaded. Which is way later than the kernel.request listeners.

Unless you load the page beforehand? :D

**Comment by aschempp** [comment]
> Because we don't need to ship our own countries.php and translations for them anymore.

Sure, but that's not related to my PR ;-)

> Unless you load the page beforehand? :D

"Impossible", we need the routing first. But that's not really a problem, that was always the case in Contao. The browser language is only used as initial language, e.g. to render the maintenance screen.

**Comment by leofeyer** [comment]
See #336.
