### ISSUE TITLE
Root not redirected if script in URL

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#230]
If `prepend_locale` is active, `/` should be redirected to `/en/` (the fallback language). This only works if no script is in the URL, e.g. `app.php/` is not redirected to `app.php/en/`.

I think that's a problem in the legacy code.

**Comment by leofeyer** [comment]
I have fixed the issue in 36e4d073896ee00793c048b69f991bbee0322f67. Found quite a couple of other redirect and script name issues, which I have fixed, too. You should probably rebase #227 and see if all changes are still necessary.
