### ISSUE TITLE
Clean up composer requirements

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#232]
I think the composer requirements are not correct. `contao/standard-edition` currently requires `symfony/symfony`, but that does not really make much sense to me. Especially because of that our bundle dependencies are not correct.

Examples:
 1. `contao/core-bundle` requires `symfony/twig-bundle` because we render Twig templates
 2. `contao/core-bundle` requires `symfony/security-bundle` because we use firewalls
 3. `contao/core-bundle` requires `sensio/framework-extra-bundle` because we use annotations in controllers.
 4. `contao/core-bundle` supports the WebProfilerBundle (should be a recommendation).
 5. To continue to support `dump()`, we should either require or recommend `DebugBundle`
 4. The AppKernel is addition `SensioDistributionBundle` in dev environment, but that makes no sense because it only adds the configurator.

There are probably a lot of other cases. I can imagine we require-dev the routing component the `FrontendLoader` unit tests use it. That's currently required by the framework-bundle, but not sure if we should still add it?

**Comment by leofeyer** [comment]
The Symfony standard edition requires `symfony/symfony`, therefore I don't see a reason why we should not. The bundle, however, should only require what is required for it to run.

**Comment by aschempp** [comment]
The problem is, as long as our distribution (the base we're all working with) does require `symfony/symfony`, we will not notice if a dependency is missing in our bundle. And I think that already happened a lot…

**Comment by leofeyer** [comment]
Could be. But wouldn't we notice this when running the unit tests?

**Comment by aschempp** [comment]
Good question. I dont, because my tests are running in dist root, but obviously travis is not.

**Comment by leofeyer** [comment]
Exactly :)
