### ISSUE TITLE
Unify customTpl handling

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#235]
I guess for BC reasons the front end modules "Login" as well as "Personal data" (that already supported different templates using a specific setting in the module settings) do not support `customTpl`. I guess we should modify this behavior so it's aligned with the other modules.

**Comment by leofeyer** [comment]
It is not for reasons of BC. It is because the template can be assigned dynamically in these modules (e.g. `mod_login_1cl` and `mod_login_2cl`).

**Comment by Toflar** [comment]
Yeah but you cannot have 5 login modules using different templates (as you'd probably wish).

**Comment by leofeyer** [comment]
Huh?

**Comment by Toflar** [comment]
In every FE module I can have as many custom templates as I wish and I can name them the way I want. That's not possible here.

**Comment by leofeyer** [comment]
I know. Because the template is assigned dynamically (see above).

**Comment by Toflar** [comment]
I know. And this is what's wrong. It should just use `customTpl` as well. Right now it just uses either `mod_login_1cl` or `mod_login_2cl` and `mod_logout_1cl` or `mod_logout_2cl`. However, we should simply ship `mod_login` which contains all the logic. I can then use `customTpl` to have my `mod_login_whatever`. Moreover, I think we could drop the `2cl` thing. Why would you want to have a table layout? :)

**Comment by leofeyer** [comment]
That seems impossible to me, because the template is determined depending on checkboxes the user sets or does not set. Do you suggest to remove these checkboxes?

**Comment by Toflar** [comment]
> Or are you suggesting to remove these checkboxes?

Checkboxes? `tl_module.cols` is a `select` field but yes, I suggest removing this because it can be achieved by selecting (or writing) a different `customTpl`.

**Comment by aschempp** [comment]
I actually think we should have both: A „tableless“ checkbox and the option to use a custom template. The widgets also have two versions for tableless or not. This would also allow for easy migration.

**Comment by Toflar** [comment]
:-1: No, I want to have a unified way which is choosing your `customTpl` if you want. Everything else makes understanding the way Contao works more complicated.

**Comment by aschempp** [comment]
> Everything else makes understanding the way Contao works more complicated.

We already have a "tableless" checkbox in several places, both frontend modules and form generator. I don't think that's more complicated, I think it's way more complicated to select a custom template to switch between table or tableless…

**Comment by Toflar** [comment]
But the naming is not about tableless or not. It says "2 columns" or "1 column" which is confusing.

**Comment by aschempp** [comment]
I know, but it’s actually table or tableless…

**Comment by Toflar** [comment]
See the problem now? :-)

**Comment by aschempp** [comment]
No?

**Comment by Toflar** [comment]
Well to summarize: The way it is now is completely wrong :-)

* It has a dropdown that offers 1 column or 2 column. Anywhere else in Contao it's a checkbox for "tableless".
* I cannot choose my `customTpl` which I can in every other Contao front end module.

**Comment by aschempp** [comment]
> The way it is now is completely wrong

Agreed, it's the old way. The new way would be to have a "tableless" checkbox (both modes supported by the default template), and a `customTpl` option.

**Comment by Toflar** [comment]
Yes. Same for the personal data module.

**Comment by leofeyer** [comment]
Ok, so here are the problematic templates according to my search:

 - `ModuleEventMenu`: the template is set dynamically depending on the `cal_format` field.
 - `ModuleLogin`: the template is set dynamically depending on the `cols` field and on the login status.
 - `ModuleSearch`: the template is set dynamically depending on the `searchType` field.
 - `ModuleNewsMenu`: the template is set dynamically depending on the `news_format` field.

Did I miss something?

**Comment by aschempp** [comment]
ContentText does something with the images.

**Comment by leofeyer** [comment]
No, that was fixed a long time ago. But `ContentHyperlink` still does it :)

**Comment by Toflar** [comment]
Still ModulePersonalData as mentioned in the issue description: https://github.com/contao/core-bundle/blob/76e82f4ab4fd0746ba989aea48b8b60652ee2b96/src/Resources/contao/modules/ModulePersonalData.php#L96-L104

**Comment by leofeyer** [comment]
No, that's just the partial (`member_default` or `member_grouped`). These can be changed already.

**Comment by leofeyer** [comment]
See #247.
