### ISSUE TITLE
Remove the automated logout module

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#236]
It's wrong that this is a front end module because it doesn't make sense. It should be a custom page type.

**Comment by aschempp** [comment]
Not sure, it will be handled by security anyway later on (see #122)

**Comment by Toflar** [comment]
Yeah, whatever - just not a FE module :D

**Comment by leofeyer** [comment]
Will you be working on this issue for Contao 4.1 or shall I change the milestone to 4.x.x?

**Comment by aschempp** [comment]
I don't think this would be correct to add in 4.1. We can't remove the frontend module in a minor release. And adding a page type would probably not be the correct solution in regards of the Symfony security component.

**Comment by leofeyer** [comment]
We would not have to remove the front end module. We could also just add the new page type and mark the front end module as deprecated.

We should discuss the Symfony context though.

**Comment by leofeyer** [comment]
I have created a PR: #469
