### ISSUE TITLE
Add `contao.framework.exception` Event

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#238]
Exception and Errors that occurs in Chain of `contao.framework.boot` (see: #192 ) should be caught in `InitializeSystemListener` and trigger a event like `contao.framework.exception`. In this way all legacy stuff errors can be caught by symfony exception hanling.

**Comment by aschempp** [comment]
why would that be necessary? I don't think the application can continue in this case. Exceptions are already handled by the Symfony kernel exception handling?

**Comment by dtomasi** [comment]
Thats not necessary. Just a next step to decouple legacy stuff from symfony stuff. I would prefer to handle error while initializing legacy-framework in a separated exception handling.

**Comment by aschempp** [comment]
What's the motivation to do so? I mean in the end we need to show the "yellow box" to the user?

**Comment by dtomasi** [comment]
@aschempp I will close this because this suggestion is also based on having a Subsystem for Event-Handling, what we discussed today.
