### ISSUE TITLE
Separate validating CTO4-Installation from initialize process of legacy framework

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#239]
Validating the installation of CTO4 does not belong to the initialize process of legacy framework. In my opinion this should be separated.

**Comment by leofeyer** [comment]
+1

**Comment by dtomasi** [comment]
@leofeyer Would you like to have a PR for this??

**Comment by aschempp** [comment]
It depends… we're currently verifying if the `localconfig.php` etc. is set, which is only necessary for the legacy framework…

**Comment by dtomasi** [comment]
That´s right. What´s the plan to provide Config/Parameters for BC in future? I´m asking because I thought about implementing an Interface to decouple this.

**Comment by aschempp** [comment]
Well the config should be in the container. We already did that for a few properties (e.g. `prefix_locale`), but it only makes sense for stuff we migrate to the new framework (e.g. it does not make sense for `installPassword`.

For most things, the Container will verify there is a value, so we might actually not need a generic listener…

**Comment by dtomasi** [comment]
I agree. Then it should be kept in mind for the future. :)

**Comment by leofeyer** [comment]
As I have said before, I would like the "your installation is insecure" check to be an event listener. The `/web` subfolder is not related to the Contao 3 framework.

**Comment by aschempp** [comment]
Valid point.

**Comment by dtomasi** [comment]
What´s about split the up in `InsecureInstallationListener` and `IncompleteInstallationListener`?

`InsecureInstallationListener` should then be placed in `Contao\CoreBundle\EventListener` and `IncompleteInstallationListener` in `Contao\CoreBundle\EventListener\Framework`, where the legacy stuff is placed.

**Comment by aschempp** [comment]
+1

**Comment by leofeyer** [comment]
IMHO, we don't need separate event listeners for the Contao 3 framework; one `InitializeSystemListener` is enough. But +1 for the `InsecureInstallationListener`.

**Comment by dtomasi** [comment]
But in #234 we need the `IncompleteInstallationListener. This PR splits up the whole `InitializeSystemListener`.

**Comment by leofeyer** [comment]
I'm closing this ticket in favor of #234.
