### ISSUE TITLE
Use attributes from Request instead of Globals in Contao\Input

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#243]
Actual `\Contao\Input` uses `$_GET`, `$_POST` and `$_COOKIE`. This should be replaces with attributes from `Symfony\Component\HttpFoundation\Request`.

**Comment by leofeyer** [comment]
@contao/developers What do you think?

**Comment by aschempp** [comment]
Not that easy, because we do - for example - clean the keys of the array. I'm not sure if we should use the request in `Input` or start to convince people to use the request directly. Not sure about the security implications though…

**Comment by leofeyer** [comment]
> I'm not sure if we should use the request in `Input` or start to convince people to use the request directly.

Definitely the latter. People should use the Symfony request stack.

**Comment by aschempp** [comment]
Symfony does not have input encoding though, which is dangerous if combined with our template engine.

**Comment by leofeyer** [comment]
That's true. So we should definitely leave the `Input` class as is.
