### ISSUE TITLE
Stop using deprecated resources

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#252]
Now that a deprecation error gets triggered when using deprecated resources (see 6f706bc1f050df8f1fd88187ce4904c4bd3e144e), we can find out where we are still using these resources using the debug bar.

**Comment by aschempp** [comment]
I think we should not add the deprecation warning for the stuff only deprecated in Contao 4.0. At least as far as I did understand Symfony, the only add the message after it was already deprecated for some time… What happens to the deprecated notice in production environment?

**Comment by leofeyer** [comment]
They are being ignored.

**Comment by leofeyer** [comment]
Using the Symfony session will be a BC break, because we'll have to replace the `setData()` and `getData()` methods with `replace()` and `all()`.

**Comment by leofeyer** [comment]
Fixed in a1def613d40b8671abe621e7976d5877d1c9570b and 2776bc8a0c7920dbedaa42325976c753b18a4685.
