### ISSUE TITLE
Remove mime icons

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#253]
I think we should remove the mime icons for download elements (related to e54a512aacc1b825cc02ab4d2671fde2dc4385cb)

**Comment by leofeyer** [comment]
We've been discussing this yesterday with @frontendschlampe and @MacKP. I want to provide a style sheet in the layout builder that optionally adds the icons before we remove the markup. Otherwise there is no alternative.

**Comment by aschempp** [comment]
It's frontend design, it's not the core job to add styling to a website…

**Comment by leofeyer** [comment]
We are already providing a tool set for FE developers:

 * `form.css`
 * `grid.css`
 * `layout.css`
 * `reset.css`
 * `responsive.css`

I want to add an `icons.css` style sheet before taking the other option away.

**Comment by aschempp** [comment]
Ah I see. That would be fine with me (thought I never use it ^^). But we could still remove it in 4.0 (BC break to remove the icons) and the method from `File` and add the icons feature in any later version.

**Comment by leofeyer** [comment]
We cannot remove the method from the `File` class. All we are talking about is the templates.

**Comment by aschempp** [comment]
True, but we should deprecate the method in the `File` class ;-)

**Comment by leofeyer** [comment]
I suppose you are only referring to the `getIcon()` method? Because we do need a way to find the mime type. Unless there is a Symfony way to do this of course :)

**Comment by Toflar** [comment]
Symfony does have a `MimeTypeGuesser` :)

**Comment by leofeyer** [comment]
I have removed the `<img>` tags and added the `icon.css` style sheet in 314eba9f82077042974f791d3793f6869dc6c0c5.

Deprecating the methods, however, implies that we remove all icons in the back end and reapply them via CSS, right?

**Comment by aschempp** [comment]
I agree the icons must not be part of the theme. Probably something for the assets.
