### ISSUE TITLE
CoreBundle should depend on FrameworkExtraBundle

### ISSUE THREAD

**Issue by dtomasi** [contao/core-bundle#258]
In our Controllers we use the Annotations from `FrameworkExtraBundle`. Therefor `CoreBundle` should depend on `sensio/framework-extra-bundle` in `composer.json`.

**Comment by leofeyer** [comment]
Fixed in 4f2a770b5130f90fdee41a230f5a7fcd26fdc0c6.

**Comment by aschempp** [comment]
Jup, already mentioned that in #232 ;-)

**Comment by dtomasi** [comment]
Ah ok, have mentioned this while I fixed the tests in #234. ;-)
