### ISSUE TITLE
Move the ContaoFramework class to its own namespace

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#261]
I'd like to discuss moving the Contao framework related resources into their own namespace:

```
src/
    Framework/
        ContaoFramework.php
        FrameworkAwareTrait.php
```

@contao/developers Please vote +1 if you like it.

**Comment by aschempp** [comment]
We've discussed this already. :-1: from me

**Comment by aschempp** [comment]
As a follow up, we can't move the classes in the RC phase, this would be for Contao 5 then…

**Comment by discordier** [comment]
:-1: from me as well. Especially given the fact that we want to remove the framework over the next versions.

**Comment by leofeyer** [comment]
Meanwhile changed through #346.
