### ISSUE TITLE
[4.0.0-RC1] Frontend error: "" is not a supported locale

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#262]
I set up a fresh installation of Contao 4.0.0-RC1, after the setup I get the exception `"" is not a supported locale.` for all front-end requests e.g. `/app_dev.php/` or `/app_dev.php/home.html`. The backend works.

Changing [EventListener/LocaleListener.php:55](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/EventListener/LocaleListener.php#L55) to:

```php
if ($request->attributes->has('_locale') && null !== $request->attributes->get('_locale')) {
```

fixes the issue.

AFAIK `_locale` is set to `null` in [Symfony/Component/HttpKernel/EventListener/RouterListener.php:149](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L149).

**Comment by aschempp** [comment]
1. Did you use the `contao/standard-edition`?
2. Did you enable `prepend_locale`?
3. What version of Symfony did it install for you (visible in the dev console)?

**Comment by ausi** [comment]
1. Yes, I installed it via `php composer.phar create-project contao/standard-edition <zielordner> 4.0.0-RC1`
2. `prepend_locale` is set to `false`
3. Symfony 2.6.7

**Comment by ausi** [comment]
Just tested it also with `prepend_locale: true`, didn’t make a difference.

**Comment by leofeyer** [comment]
@aschempp I was able to reproduce it by setting `prepend_locale` to `false` and the executing `composer run-script post-update-cmd` on the command line.

**Comment by leofeyer** [comment]
I think the problem is here:

https://github.com/contao/core-bundle/blob/develop/src/Routing/FrontendLoader.php#L108

Shouldn't we set a default locale here?

```php
$route->addDefaults(['_locale' => 'en']);
```

This also fixes the issue on my system.

**Comment by leofeyer** [comment]
It also helps to remove the entire line. Why set a `_locale` attribute at all if it is `null`?

**Comment by leofeyer** [comment]
I think @ausi's fix is correct :)

**Comment by leofeyer** [comment]
I have created a PR: https://github.com/contao/core-bundle/pull/264

Please review and vote +1 to merge it.
