### ISSUE TITLE
[4.0.0-RC1]  The "/files" directory does not exist. 

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#265]
Frische Installation, beim Anlegen eines Verzeichnisses  im Backend-Dateiverwaltung und anklicken als öffentliches Verzeichnis kommt 
```
The "/files" directory does not exist.
500 Internal Server Error - InvalidArgumentException 
in vendor/symfony/symfony/src/Symfony/Component/Finder/Finder.php at line 677
```
Physikalisch existiert das files Verzeichnis (install-dir/files), auch mein neues Verzeichnis wurde angelegt.
Gehe ich eine Seite zurück und erneut auf Dateiverwaltung ist das neue Verzeichnis im Backend auch sichtbar, es ist aber nicht veröffentlicht, trotzdem wird kein "Schloss-Icon" angezeigt, als wäre es öffentlich.

**Comment by BugBuster1701** [comment]
Nach Aufruf von 
```app/console contao:symlinks```
wurde web/files angelegt und darin mein neues verlinkt.

**Comment by xchs** [comment]
Die selbe Meldung erhalte ich auch, wenn ich im Backend den "Recreate the symlinks" Job in der Systemwartung ausführen möchte.

**Comment by BugBuster1701** [comment]
Da scheint nur das Unterverzeichnis "files" im Verzeichnis "web" zu fehlen, danach geht es.
app/console scheint das mit anzulegen wie oben erwähnt.

**Comment by aschempp** [comment]
Wie hast du Contao 4 installiert?

**Comment by fiedsch** [comment]
Gleiches Thema hier. Installation mit 

```
composer create-project contao/standard-edition contao4_test 4.0.0-RC1
```
wie in https://contao.org/de/news/contao_4-0-RC1.html beschrieben.

Ach mit manuellem Anlegen des files Verzeichnisses geht nichts (rechte passen; gehört dem User unter dem der Apache läuft). 

Im Gegensatz zu BugBusters Post oben:
```
app/console contao:symlinks
```
entfernt ein manuell angelegtes files unter `<installdir>/web`

**Comment by BugBuster1701** [comment]
Installiert so wie hier beschrieben: https://contao.org/de/news/contao_4-0-RC1.html

**Comment by leofeyer** [comment]
Was genau muss ich tun, um das Problem zu reproduzieren?

**Comment by BugBuster1701** [comment]
Installieren wie auf contao.org beschrieben und über Dateiverwaltung ein Verzeichnis anlegen und es veröffentlichen. Ich verwende übrigens app_dev.php

**Comment by leofeyer** [comment]
Mann muss direkt beim Anlegen schon das Feld "Public" anhaken, damit der Fehler auftritt.

**Comment by fiedsch** [comment]
> Mann muss direkt beim Anlegen schon das Feld "Public" anhaken, damit der Fehler auftritt.

kann ich so nicht bestätigen/reproduzieren: In meiner Testinstallation gilt:

Mann muss das Feld "Public" anhaken, damit der Fehler auftritt.

Der neue Ordner wird in CONTAO_ROOT/files wie gewünscht angelegt. Nur das Hinzufügen (oder entfernen) der Symlinks in CONTAO_ROOT/web/files scheitert mit der besagten Fehlermeldung.

**Comment by leofeyer** [comment]
Behoben in 1618c542e8522d05b1fe7ae54f0d066400ebe8de.
