### ISSUE TITLE
[4.0.0-RC1] An invalid form control is not focusable.

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#266]
It seems not to be possible to add a new content element of type *"Text"*. Firefox always shows an "Bitte füllen Sie dieses Feld aus" message whereas Chrome writes `An invalid form control with name='text' is not focusable.` to the console log.

**Comment by ausi** [comment]
I have the same issue. I think it appears because the textarea `#ctrl_text` has a `required` attribute and the textarea is always empty because the text is only in the tinyMCE editor.

**Comment by aschempp** [comment]
Could be solved my setting `<form novalidate>`, but why does that not happen in earlier versions of Contao?

**Comment by leofeyer** [comment]
Because there is no `required` attribute on the `<textarea>` tag in Contao 3.

**Comment by leofeyer** [comment]
Fixed in 4349cd63a8ac2ffb507cc31ef37ffcd9c2f60235.
