### ISSUE TITLE
[4.0.0-RC1] Install Tool $this->reload() doesn’t work

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#267]
If you go to `/contao/install` and import an example website you get the error message *“The import failed!”* even if the import was successful. The same issue appears if you create an admin user, you get the message *“Please fill in all fields to create an admin user!”*.

This is because we are catching the `RedirectResponseException` in [BackendInstall.php:135](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/controllers/BackendInstall.php#L135) and [BackendInstall.php:563](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/controllers/BackendInstall.php#L563) which was thrown in [BackendInstall.php:484](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/controllers/BackendInstall.php#L484) and [BackendInstall.php:555](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/controllers/BackendInstall.php#L555).

**Comment by leofeyer** [comment]
Fixed in a08ab8c26cad3bd888941739511572af11cf1cf1.
