### ISSUE TITLE
[4.0.0-RC1] Colorpicker has broken images

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#268]
![color-picker](https://cloud.githubusercontent.com/assets/367169/7661813/4e0264c2-fb56-11e4-9543-4fdd3169e4b0.png)

Can be fixed by changing [DataContainer.php:414](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/classes/DataContainer.php#L414) to: `imgPath: "assets/colorpicker/images/",`.

**Comment by aschempp** [comment]
Why has that path changed in the first place?

**Comment by leofeyer** [comment]
Because we are now using components.

**Comment by leofeyer** [comment]
Fixed in de42709d411fe0c4627a7b8321edbda5d637aa60.
