### ISSUE TITLE
[4.0.0-RC1] Frontend login doesn’t display error message for wrong credentials

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#269]
If you try to login as a frontend user with wrong username and password, no error message gets displayed. This is because in [ModuleLogin.php:180-185](https://github.com/contao/core-bundle/blob/0b2194e8fa042e4da5972f7ad06c28415f37677f/src/Resources/contao/modules/ModuleLogin.php#L180-L185) `$_SESSION['TL_ERROR']` should be replaced with `$_SESSION['MESSAGES']['FE']['TL_ERROR']`.

**Comment by aschempp** [comment]
Actually it should be replaces with the Symfony session flash bag (http://symfony.com/doc/current/components/http_foundation/sessions.html#flash-messages).

**Comment by leofeyer** [comment]
Fixed in 8d1b4d6ef69f8dee67cba78fdcd92e77ab32ed6b.
