### ISSUE TITLE
[4.0.0-RC1] The "Toggle all" functionality does not work for template (sub)folders

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#270]
To reproduce:
* Open the *"Layout"* > *"Templates"* back end module
* Add a new template folder
* Create a new template copy and save it to the previously created template folder
* Click the *"Toggle all"* link to expand the node

**Comment by aschempp** [comment]
Works fine for me. Maybe this is related to your session problem (see #271) ?

**Comment by xchs** [comment]
You think so? But then I do not understand why it works everywhere else. I have noticed the issue only in the *"Templates"* back end module (at least until now).

**Comment by leofeyer** [comment]
I cannot reproduce this, either.

**Comment by xchs** [comment]
Does it work for you if the template subfolder is named `Theme`?

**Comment by aschempp** [comment]
Yes that works for me too.
