### ISSUE TITLE
[4.0.0-RC1] Update the keyboard shortcuts link

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#273]
The keyboard shortcuts link on the back end dashboard should point to the new GitBook manual: https://docs.contao.org/books/manual/current/en/02-administration-area/keyboard-shortcuts.html

Is there a way to automatically redirect to the respective language version (according to the browser language and with a fallback to English if there is no match)?

**Comment by aschempp** [comment]
> Is there a way to automatically redirect to the respective language version (according to the browser language and with a fallback to English if there is no match)?

Currently not, as that is all static HTML.

**Comment by leofeyer** [comment]
That's not entirely true, because we are using Contao as entry point. If you open the following URL, you will see the default Contao error page:

https://docs.contao.org/en/books/manual/current/02-administration-area/keyboard-shortcuts.html

@aschempp It should be easy to add the language from the Accept-Language header and redirect, shouldn't it?

**Comment by aschempp** [comment]
Unfortunately it's not that easy, as the links are different in every language.

https://docs.contao.org/books/manual/current/en/02-administration-area/keyboard-shortcuts.html
https://docs.contao.org/books/manual/current/de/02-administrationsbereich/backend-tastaturkuerzel.html

How about adding the link to the language file?

**Comment by aschempp** [comment]
The only other solution I can think of is adding some kind of short URL feature that would redirect based on the language. Would you prefer that?

**Comment by leofeyer** [comment]
I guess we'll add the link to the language file then.

**Comment by aschempp** [comment]
Ok, up to you. A simple https://docs.contao.org/go/keyboard-shortcuts would be fairly easy to implement

**Comment by leofeyer** [comment]
Would we have a short link for every page then? Or just for the keyboard shortcuts?

**Comment by aschempp** [comment]
I would only add what we need, but we could easily extend that.

**Comment by leofeyer** [comment]
Fixed in ba2e11a5fe7111fe624bf6a64a19fc56bef1e668.
