### ISSUE TITLE
[4.0.0-RC1] Image "Important part": non-negative natural numbers for image size and coordinates

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#274]
The "important part" of a picture should be described by coordinates and image size values with non-negative natural numbers.

As it is now, you can edit the corresponding fields of one or more pictures and set the properties to any negative values:

![important_part](https://cloud.githubusercontent.com/assets/1218766/7664192/bcac6e88-fb7c-11e4-8023-b88a050fe18e.png)

Should we change the DCA evaluation regex key to `'rgxp'=>'natural'`? (/cc @ausi)

**Comment by ausi** [comment]
+1 for changing `rgxp` to `natural`, but IMO we should also backport it for version 3.5.

**Comment by Toflar** [comment]
> but IMO we should also backport it for version 3.5.

:+1:

**Comment by leofeyer** [comment]
Changed in contao/core@ddd62860adac627ca734e472d913d5f36a98529b.
