### ISSUE TITLE
Change type to "symfony-bundle"

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#276]
We should change the type in our `composer.json` file from "library" to "symfony-bundle".

**Comment by aschempp** [comment]
Do you have any explanation for this? Not necessarily related to Contao, but in general. I did see a lot of such type use in Symfony bundles, but the Composer documentation clearly says one should use "library" if there is no registered type. And there is not Composer installer for "symfony-bundle" as far as I know.

**Comment by leofeyer** [comment]
I don't know. It seems to be common practice though.

**Comment by aschempp** [comment]
It is, even the composer docs do mention it:

https://getcomposer.org/doc/04-schema.md#type

> Package types are used for custom installation logic. If you have a package that needs some special logic, you can define a custom type. This could be a symfony-bundle, a wordpress-plugin or a typo3-module. These types will all be specific to certain projects, and they will need to provide an installer capable of installing packages of that type.

However, there is no special logic for type "symfony-bunde" (or I could not find any), and there is no installer capable of installing packages of that type. 

I'm pretty familiar with the topic due to the composer plugin ;-)

**Comment by aschempp** [comment]
Maybe @Seldaek can shed some light on this?

**Comment by discordier** [comment]
The type symfony-bundle is a special type IMO as it depends on a certain environment.
Additionally, a symfony bundle might depend on the composer action scripts registered in the symfony application which qualify enough as "installer".

Granted, the documentation is a bit vague on this one. In fact, there is no need to supply a special installer but the only way for a special installer to detect packages it is responsible for is by defining a package type.

I guess the ambiguosity in the docs originate from the fact that before the Plugins there were only custom installers and downloaders and the Plugins replace that legacy system (see differences in `contao-community-alliance-archive/composer-installer` vs. `contao-community-alliance/composer-plugin`).

**Comment by Seldaek** [comment]
I think it's good to use the type for bundles because eventually we might allow filtering on packagist by package type and then it'll be very relevant for bundle discovery.

**Comment by aschempp** [comment]
Good point, thanks for the feedback @Seldaek.
@contao/developers we should think about using a `contao-bundle` then for anything but the core bundle. We already use `contao-module` for old modules and `legacy-contao-module` for the old extension repository. Let's open a new issue though also related to @tenside

**Comment by discordier** [comment]
You could as well reopen this one and change the subject from
> Change type to "symfony-bundle"

to
> Change type to "contao-bundle"

**Comment by aschempp** [comment]
No because it’s already implemented in Contao 4.0 and closed.
