### ISSUE TITLE
[4.0.0-RC1] Session::getInstance()->get('referer') doesn’t work anymore

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#281]
In Contao 3 the `referer` array was stored in `\Session::getInstance()->get('referer')`. This is no longer the case in version 4, because it is now stored in `\System::getContainer()->get('session')->get('referer')` instead of `\System::getContainer()->get('session')->getBag('contao_backend')->get('referer')`.

Is this a known BC break or was this changed accidentally?

**Comment by leofeyer** [comment]
This was changed accidentally. We are no longer storing non-state data in the persistent session bags.

**Comment by leofeyer** [comment]
We should maybe add a compat layer though.

**Comment by aschempp** [comment]
Would be fairly easy, as we have our own attribute bag. We just should disallow writing the legacy session property.

**Comment by leofeyer** [comment]
As discussed on Mumble on May 21st, we need to map the referer request to the attributes bag in the `set()`, `get()`, `setData()` and `getData()` methods. Also, we should store `new_records` in the persistent bag.

**Comment by leofeyer** [comment]
Fixed in 548297c7b2d639c3cfcec8ef9c0a3fd91e21ab20 and 5ba5651286f882271c4cf444215dc18ec871acdc.
