### ISSUE TITLE
Maintenance mode buggy

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#283]
Because the maintenance mode is part of the Contao framework
- the message is not shown if the framework is not initialized
- it is loaded very late and therefore any error in the system could result in the message not being shown

I can think of these solutions:
 1. adjust the entry point (`app.php` only) to trigger the maintenance mode very early
 2. Add a kernel listener for the maintenance mode and move the flag to `parameters.yml`
 3. Also change the exception listener to show maintenance regardless of the kernel error to prevent the generic error message from bubbling up.

**Comment by aschempp** [comment]
Ok I was wrong with that. The maintenance message is shown in the frontend controller. To me, a maintenance mode should not be bound to a route though…

**Comment by Toflar** [comment]
https://github.com/lexik/LexikMaintenanceBundle

**Comment by leofeyer** [comment]
> To me, a maintenance mode should not be bound to a route though…

The maintenance mode was FE only ever since. If it were enabled in the back end too, you could not longer work; and the maintenance mode is e.g. enabled if you install an extension or run the Live Update, which both require back end access.

**Comment by aschempp** [comment]
The maintenance bundle mentioned by @Toflar does fully support excluding routes or url paths like the backend. We should really consider that for a next minor version.

**Comment by leofeyer** [comment]
+1

**Comment by leofeyer** [comment]
Will you be working on this for Contao 4.1?

**Comment by aschempp** [comment]
It's not assigned to me, that's why I didn't stumble upon it. But I just recently stumbled upon it again while reading about OroCRM (they use it and also have bundle autoloading ;-) ).

**Comment by aschempp** [comment]
What I dislike about the bundle is that it requires Symfony to be fully operational (kernel boot & request/response handling). The original Contao implementation was triggered very early. I wonder if we should build a workaround for that?

**Comment by leofeyer** [comment]
Do we need to change it at all?

**Comment by bytehead** [comment]
Regarding to this issue, I have another question:
When [this exception](https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/controllers/FrontendIndex.php#L46) is thrown, there is no scope set.

I have an extended `PrettyErrorScreenListener` in use (because of the fact, that I use the `contao/core-bundle` as a bundle besides for example the `FosUserBundle` and I have to let the exception bubble up, if it's not a `ContaoMasterRequest`, which actually checks for the scope:
```php
protected function isContaoMasterRequest(KernelEvent $event)
{
    return $event->isMasterRequest() && $this->isContaoScope();
}
```

The missing scope is actually the reason for [this three additional lines of code](https://gist.github.com/bytehead/105db00d19d33a2e772a#file-prettyerrorscreenlistener-php-L18-L20).

**Comment by aschempp** [comment]
You mean the exception is also thrown if there is no scope set?

**Comment by bytehead** [comment]
It looks like that.

I would also consider to use `isContaoMasterRequest()` on [this line](https://github.com/contao/core-bundle/blob/develop/src/EventListener/PrettyErrorScreenListener.php#L98) instead of `isMasterRequest` - otherwise you handle potential exceptions of other bundles...

**Comment by aschempp** [comment]
The general exception handling is intended (but not related to this issue ;-)).

Regarding the maintenance mode, it's only thrown if the `FrontendIndex` controller is used? Which should not be the case for your custom routes, so I don't see a point in checking the scope?

**Comment by bytehead** [comment]
My initial question gets cleared up by https://github.com/contao/core-bundle/pull/362.

**Comment by leofeyer** [comment]
To get things going, I have added the Lexik bundle in contao/standard-edition@8a6b551d3e5ee75ccc3158265d7a468abb4abe93. It works like a charm and we should really remove the existing maintenance option instead.

Also, we need to think about a solution for the scenario that Symfony cannot be booted.

**Comment by leofeyer** [comment]
These are the changes necessary to remove the maintenance mode: 35c9ff525033fa01b4a8d5dbcfda79929a2bcc54

@contao/developers Do we also want to remove the `ServiceUnavailableException`?

**Comment by leofeyer** [comment]
Also, the current implementation renders a pretty error screen saying "an error occurred" instead of "service temporarily unavailable". I doubt that this is what we want, right?

**Comment by Toflar** [comment]
> Also, we need to think about a solution for the scenario that Symfony cannot be booted.

Proposal:

```php
// app.php

$maintenancePage = ''; // Enter the html maintenance page path here (e.g. 'maintenance.html')
$retryAfter = 21600; // 6 hours

if ('' !== $maintenancePage) {
    header('HTTP/1.1 503 Service Unavailable');
    header('Retry-After: ' . $retryAfter);
    echo file_get_contents($maintenancePage);
    exit;
}
```

I think we can leave `app_dev.php` as is because those that try to see the page using `app_dev/` don't really need a nice maintenance page and the once who are working on the page can easily keep working on the app using the already implemented user/password implementation.

**Comment by leofeyer** [comment]
That does not seem appropriate. Also, does this handle the case that Symfony cannot be loaded?

```php
try {
    $kernel = new AppKernel('prod', false);
    $kernel->loadClassCache();

    // Handle the request
    $request = Request::createFromGlobals();
    $response = $kernel->handle($request);
    $response->send();
    $kernel->terminate($request, $response);
} finally {
    header('HTTP/1.1 503 Service Unavailable');
    header('Retry-After: 3600');
    exit;
}
```

**Comment by aschempp** [comment]
> To get things going, I have added the Lexik bundle

Great! 

> Do we also want to remove the `ServiceUnavailableException`?

Certainly not, as it would be a BC break

> Also, the current implementation renders a pretty error screen saying "an error occurred" instead of "service temporarily unavailable".

Should be a simply fix by also converting the Lexik exception in the exception converter and/or handle it in the pretty error screen listener.

**Comment by aschempp** [comment]
My draft for the `app.php`:

```php
try {
    $kernel = new AppKernel('prod', false);
    $kernel->loadClassCache();

    // Handle the request
    $request = Request::createFromGlobals();
    $response = $kernel->handle($request);
    $response->send();
    $kernel->terminate($request, $response);
} catch (\Exception $e) {
    if (file_exists('../app/cache/lock') {
        header('HTTP/1.1 503 Service Unavailable');
        header('Retry-After: 3600');
        // Dunno if Retry-After is correct and if we should also output a message.
        exit;
    }

    throw $e;
}
```

Basically, we should only convert the exception to a "service unavailable" if the lock file is present. As the `app.php` belongs to the standard distribution where the path is "correct", if anyone changes the app config they need to change the app.php …

**Comment by aschempp** [comment]
Also, remember that currently it is possible to enable and disable the maintenance mode from the backend! We should provide options for that, possible in the maintenance screen instead of the system settings. Should be fairly simple by triggering the command or use the service (if one is available).

**Comment by aschempp** [comment]
There's even a description about that in the docs: https://github.com/lexik/LexikMaintenanceBundle/blob/master/Resources/doc/index.md#service

One more thing: Currently the frontend is visible if you are logged in to the backend. This would no longer be the case. The bundle does provide a cookie check, but that would not be sufficient for our login cookie. We might need to implement our own driver to work around this (which would be fairly simple).

**Comment by leofeyer** [comment]
> Basically, we should only convert the exception to a "service unavailable" if the lock file is present.

That's wrong, because if the kernel does not boot, you always want the app to return a 503 status to play nicely with Google.

> remember that currently it is possible to enable and disable the maintenance mode from the backend! We should provide options for that

Yes, we probably should.

> Currently the frontend is visible if you are logged in to the backend. This would no longer be the case. 

Or we simply require people to either use the `app_dev.php` entry point or to authorize their IP addresses in the `config.yml` file.

**Comment by aschempp** [comment]
> That's wrong, because if the kernel does not boot, you always want the app to return a 503 status to play nicely with Google.

But it means you won't see why the error occurs, which is probably annoying for most times. Imagine you add a new bundle to the kernel and then you won't see why it does not work… And there's no logging either because we don't have a logger ^^

> Or we simply require people to either use the app_dev.php entry point or to authorize their IP addresses in the config.yml file.

I don't think that's helpful. I often enable maintenance mode while developing a new website (it's enabled by default when installing Contao 3.5), and then have my client use the backend login to see the page. They sure don't want to use the dev entry point (debugger, performance, etc.) and they usually don't have a fixed IP.

Also, `app_dev.php` does currently not prevent the maintenance mode as far as I know?

**Comment by leofeyer** [comment]
Ok, here is what we have got so far (see fc0a8f29f41f7968636304e817913fa4bf5d3b94):

* The core uses the Lexik bundle.
* The maintenance mode can be enabled via command line.
* The maintenance mode can be enabled in the back end maintenance module.
* The back end start page shows a warning if the maintenance mode is enabled.
* I have fixed the pretty error screen listener to correctly handle the exception.

Here is what still needs to be changed/discussed:

* I guess we need to deprecate our own `ServiceUnavailableException` class.
* Do we really want to add ugly code to the `app.php` file?
* How can we bypass the maintenance mode in the front end if we are logged into the back end? Can we require people to adjust the Symfony configuration and add their IP address?

**Comment by Toflar** [comment]
Can you please create a PR like we all do so we can review all the changes? It doesn't belong to the `develop` branch until it's RTM. But looks quite good from your comments, I just want to read and comment the code ;-)

**Comment by leofeyer** [comment]
As discussed on Mumble, we want to add a custom driver which additionally checks the back end cookie so the maintenance mode in the front end is bypassed if you are logged into the back end.

**Comment by aschempp** [comment]
Unfortunately, the *LexikMaintenanceBundle* has several design flaws. Some of the functionality is hard-coded in the event listener, other is in the service. I don't really understand the difference. It appears we should not have a driver, as the driver is only supposed to *lock* and *unlock*. However, the only option to add our own handling would be to replace the event listener, which kinda sucks…

Maybe @spike31 can shed some light on the idea of the drivers? Because the drivers are not services, it's very hard to do anything big in there…

**Comment by leofeyer** [comment]
The architecture of the bundle seems pretty straight forward to me. We simple cannot use a driver to check for an authorized cookie, because the checks are done in the event listener.

Why don't we just set up another event listener which checks for the cookie and dynamically adds the IP address to the whitelist of the maintenance bundle?

**Comment by aschempp** [comment]
That would require a dynamic modification of the container, which is not possible ;-)

**Comment by aschempp** [comment]
And if so, we should better dynamically modify the cookie variable…

**Comment by leofeyer** [comment]
We could also create our own bundle (we might even have to).

**Comment by aschempp** [comment]
We could obviously do that. Why do you think we have to? Just because of that or for additional reasons?

**Comment by leofeyer** [comment]
Just because we cannot adjust the existing bundle to fit our needs.

**Comment by aschempp** [comment]
Well we can always fork and provide a pull request for @spike31 but use our version in the meantime. Let's discuss it again in our next call.

**Comment by leofeyer** [comment]
As discussed on Mumble, we want to work with request attributes (`bypass_maintenance_mode`) and configure it in the Lexik bundle:

```yml
lexik_maintenance:
    authorized:
        attributes: ["bypass_maintenance_mode"]
```

**Comment by leofeyer** [comment]
We will need to move the `disableIpCheck` setting to the Symfony container.

**Comment by aschempp** [comment]
So I started working on this and figured out we're doing some things wrong. I think it is not correct to have a listener in `core-bundle` that expects a configuration to be present in the `standard-edition`. Instead we should use a compiler pass to set the request attribute. However, that means a developer should be able to override the configuration, and that will get pretty complex… I guess we need to discuss that again :-(

**Comment by leofeyer** [comment]
> I think it is not correct to have a listener in core-bundle that expects a configuration to be present in the standard-edition. 

I think you are wrong. Every other bundle is configured this way, too.

**Comment by aschempp** [comment]
For none of the other bundles we have a configuration (like the attribute name and value) that is set / used by our listener. It is similar to the framework bundle that does configure the components if you added them. It should be possible to remove the maintenance bundle completely and still have a fully functional Contao installation/distribution.

**Comment by spike31** [comment]
Hi,

Have you got a question for the MaintenanceBundle? I encourage you to open an issue on the bundle, you will have many chance to have a correct answer ;)

**Comment by leofeyer** [comment]
@aschempp You are right. We should provide a default configuration and merge the settings from the `config.yml` file if present. We are already doing it this way in the core bundle.

**Comment by aschempp** [comment]
Where do we do that in the core bundle?

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/blob/develop/src/DependencyInjection/Configuration.php#L33-L70

**Comment by aschempp** [comment]
I must have been unclear. We obviously do have configuration, but only the configuration for our own bundle. The maintenance bundle however must be configured correctly in the app for our bundle to work. That seems wrong to me. I will update the PR with an example.

**Comment by aschempp** [comment]
I just realized there's no PR (yet) ^^
So simply explained, the `core-bundle` would provide the following configuration (showing default values here):

```yaml
contao:
    maintenance:
        enabled: true
        authorize_backend: true
        backend_path: "^/contao($|/)",
        authorize_users: true
```

Based on this configuration, the bundle (or maybe a compiler pass) will configure the Lexik Maintenance bundle, will eventually disable the backend user listener, and if the maintenance *feature* is disabled then it will also remove the maintenance functionality from the backend.

(not sure if we need `backend_path` as it is not really configurable right now)

**Comment by aschempp** [comment]
Btw. the compiler pass would also check that if you did not install `LexikMaintenanceBundle`, the feature is simply not added to Contao.

**Comment by leofeyer** [comment]
I think it should be the other way round. The Lexik bundle should be part of the distribution and the core bundle should only display the maintenance module if it is present.

**Comment by aschempp** [comment]
Isn't that exactly what I said? The only thing I'm saying is that it's incorrect to have a listener that always sets the route attribute, even though we don't know if the maintenance bundle is installed and even though we don't know if the attribute authorization is present in the `config.yml`.

**Comment by leofeyer** [comment]
No, it is not. In my example, we do not need a `contao.maintenance` configuration.

**Comment by aschempp** [comment]
I know. But we are expecting another bundle to be configured so that it works with ours. That's incorrect, that's what Compilers are for. Our bundle should make sure the configuration is correct.

**Comment by leofeyer** [comment]
No, we are just checking if the distribution has a maintenance bundle and if so, we provide a GUI for enabling/disabling it. But we are **not** configuring the bundle in our bundle.

**Comment by aschempp** [comment]
We are. We're adding route attributes to whitelist the backend …

**Comment by leofeyer** [comment]
This is not trivial. The route attribute is also defined in the standard edition, but it is used in the Contao bundle. If it were a general attribute (not prefixed with `_contao`) and everybody could use it, it would no longer be specific to the core bundle.

**Comment by aschempp** [comment]
It is very trivial. It should not be in the standard edition. If enabled in our bundle, we must add our own attribute to the maintenance bundle config. An attribute that everyone could use is nonsense as there can be unlimited number of attributes.

**Comment by leofeyer** [comment]
I don't agree. The maintenance bundle is not a "feature" of the core bundle. It is part of the distribution – there is either a distribution with or without the bundle and depending on that we should use it or not.

**Comment by leofeyer** [comment]
As discussed on Mumble on November 5th, the bundle should be part of the distribution and the core bundle needs to work with or without it. We'll need to add the listener which adds a compiler path to set the request attribute.

**Comment by leofeyer** [comment]
Changed in a18b307a7fb0696b1fb5647ffaa4cbbf5faa1655 and contao/standard-edition@7d22a4c447e889488fc5406411e2947c21076dcc.

**Comment by aschempp** [comment]
Did you see my comment?
