### ISSUE TITLE
Problem when resizing bundle images using Image::get()

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#287]
The check for `web` folder should probably be added (see https://github.com/contao/core-bundle/blob/release/4.0.0/src/Resources/contao/library/Contao/Image.php#L829)

**Comment by leofeyer** [comment]
Not sure if and how to fix it. Shouldn't the first argument (`$image`) contain the `/web` fragment?

**Comment by aschempp** [comment]
The method returns the same path if the image is not to be resized. That would be a problem when containing `/web`.

**Comment by leofeyer** [comment]
I don't understand.

**Comment by aschempp** [comment]
it would return `/web/bundles/mybundle/image.png`. This path cannot be used in a template.

**Comment by leofeyer** [comment]
Ok, got it.

**Comment by leofeyer** [comment]
Fixed in 8afa71048723a7df1322f62441187c7ce52f7bf4.

**Comment by leofeyer** [comment]
Fixed in d4243e63d1f56651eb5140a142a135351463e041.
