### ISSUE TITLE
Template names not really unified

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#290]
Example from here: https://contao.org/de/news/contao_4-0-RC1.html

```
ce_accordion -> ce_accordionSingle
ce_accordion_start -> ce_accordionStart
ce_accordion_stop -> ce_accordionStop
ce_slider_start -> ce_sliderStart
ce_slider_stop -> ce_sliderStop
mod_article_list -> mod_articlelist
mod_article_nav -> mod_articlenav
mod_random_image -> mod_randomImage
mod_event -> mod_eventreader
mod_newsletter_list -> mod_newsletterList
mod_newsletter_reader -> mod_newsletterReader
```

It's true that the classes are now consistent to the module registration keys (`FMD`) but they will still feel strange to a front end developer.
E.g. `mod_eventreader` (all lowercase) and `mod_newsletterReader` (camelcase). Can we maybe agree that camelcase for a CSS class name feels strange and `strtolower()` them all?

**Comment by leofeyer** [comment]
That would be a BC break, right?

**Comment by Toflar** [comment]
No, template changes.

**Comment by leofeyer** [comment]
I'm not talking about SemVer. I'm talking about existing style sheets, which would have to be adjusted.

**Comment by Toflar** [comment]
You mean when coming from Contao 3 to Contao 4?

**Comment by leofeyer** [comment]
Yes. Right now we have a handful of changes, but if we'd lowercase all CSS classes by default …

However, you are right that all `*list` and `*reader` templates do not use camel-case. We should therefore change `mod_articleList` to `mod_articlelist`. The other templates are correct already, just the `UPGRADE.md` is not.

**Comment by zonky2** [comment]
Please matching the file name of the template with the CSS class - in this time we have a gap e.g. the filename "mod_password.html5" vs. CSS class "mod_lostPassword"...
