### ISSUE TITLE
Folder shown as protected in file selector

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#292]
My folders have a lock icon in the backend file picker, even though they are published. Maybe related to the case that I limited the folder selection to a subfolder (using `eval => path`).

**Comment by leofeyer** [comment]
Where does your `.public` file lie? In the folder you have specified or above?

**Comment by aschempp** [comment]
One level above.

**Comment by leofeyer** [comment]
Then it's clear to me. How is the system to know about the file if the folder is not "mounted"?

**Comment by aschempp** [comment]
Well I guess it should always check all parents about access rights, not only the mounted ones…

**Comment by leofeyer** [comment]
Fixed in 8afa71048723a7df1322f62441187c7ce52f7bf4.
