### ISSUE TITLE
Check the Contao version for security

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#293]
See #288.

**Comment by leofeyer** [comment]
It turns out the Symfony version color is just based on the release cycle:

https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/DataCollector/ConfigDataCollector.php#L273-L290

This does make sense, too, don't you think?

@aschempp @bytehead /cc

**Comment by leofeyer** [comment]
We need to add the following to make this work: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpKernel/Kernel.php#L63-L71 Presumably in the `ContaoCoreBundle` class.

@contao/developers Is this ok with you?

**Comment by aschempp** [comment]
How do other Symfony bundles support it?

**Comment by leofeyer** [comment]
Support what?

**Comment by aschempp** [comment]
The security checker

**Comment by leofeyer** [comment]
We are not talking about the security checker. Please read the ticket again.

**Comment by aschempp** [comment]
I see. But maybe we want to look at both then? ;-)

**Comment by leofeyer** [comment]
No. @bytehead has already provided a solution to check against the security database: https://github.com/1up-lab/contao-security-advisories

**Comment by discordier** [comment]
Neat idea.

**Comment by leofeyer** [comment]
As discussed on Mumble, this issue is not relevant.
