### ISSUE TITLE
MemberGroupModel::findFirstActiveWithJumpToByIds() returns tl_page data

### ISSUE THREAD

**Issue by blairwinans** [contao/core-bundle#294]
The naming of the function seems like it should do what it says, which is to find and return a MemberGroupModel—which it does.

However, the data returned is from a tl_page Database result (see [line 111](https://github.com/contao/core-bundle/blob/release/4.0.0/src/Resources/contao/models/MemberGroupModel.php#L111))

That should be a PageModel. It seems like something is not clear, and I assume this also goes back to other Contao versions. What is being returned should be clarified.

**Comment by leofeyer** [comment]
You are right, however, we cannot change it now because of backwards compatibility. I have assigned the ticket to the next major version.

**Comment by aschempp** [comment]
We should already add a new/correct version and mark the current one as deprecated.

**Comment by leofeyer** [comment]
What do you mean? `findFirstActiveWithJumpToByIds2()`?

**Comment by aschempp** [comment]
Well the method must be there because the core needs it? If that is true, the method probably should be `findFirstActiveJumpToByIds` and maybe be in `PageModel`. Then we can simply drop the method in 5.0

**Comment by leofeyer** [comment]
No, the purpose of the method is to find the first active member group with a `jumpTo` page by a given list of IDs. Then we need to call `->getRelated('jumpTo')` to retrieve the page model.

**Comment by aschempp** [comment]
That's not possible, because the method returns page data only and no member group information. You cannot use `getRelated('jumpTo')` with the data you get.

**Comment by leofeyer** [comment]
That's why I have assigned the ticket to the next major version, where we can correct this misbehavior.

**Comment by aschempp** [comment]
But if you would change the method's functionality in the next mayor version, the method will be useless for the current use case… So we need a new method returning the page data anyways.

**Comment by leofeyer** [comment]
It works like a charm right now, so we don't need to change anything. It simply returns the wrong database record.

**Comment by aschempp** [comment]
After reading the code (https://github.com/contao/core-bundle/blob/b2a111165f347abcc35045b92f4d6e3a9398ed3d/src/Resources/contao/modules/ModuleLogin.php#L91) I understand what you mean by *Then we need to call ->getRelated('jumpTo') to retrieve the page model.*.

However, it means everyone needs to use wrong code and change it in the next major release. We should always provide an upgrade path for such things. To me, this would mean adding a new method with a new name and mark the old one as deprecated. Then we can already change the login module.

/cc @Toflar @discordier

**Comment by aschempp** [comment]
A potential name for the new method could be `findFirstPublishedWithJumpToByIds`…

**Comment by aschempp** [comment]
Or actually `findFirstEnabledWithJumpToByIds` because the DB field is called `disable`.

**Comment by Toflar** [comment]
I am with @aschempp on this. Should be assigned to 4.1 :)

**Comment by discordier** [comment]
I agree with @Toflar and @aschempp.
We should never change the functionality of a method to do something else as in a prior version to avoid confusion and keep the API consistent.

1. add new method implementing the correct behaviour.
2.1. (if possible) use the new method in the old method and transform the result to mimic the previous behaviour.
2.2. mark the old method deprecated.
3. Only use the new method in "our" code.

Move it to 4.1 please

**Comment by leofeyer** [comment]
As discussed on Mumble on August 13th, we want to add a `findFirstActiveByMemberGroups($ids = [])` method in the `PageModel` class and deprecate the other method.

**Comment by leofeyer** [comment]
Changed as discussed in 71dbfc11e443c9f0542c56c8c162501edf229156.
