### ISSUE TITLE
PrettyErrorScreenListener renders error_404 page but not page_not_found template

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#298]
There's some strange behavior in the `PrettyErrorScreenListener` class.

If I throw a `PageNotFoundException`, it is converted to a `NotFoundHttpException` by the `ExceptionConverterListener`. The `PrettyErrorScreenListener` will then check that exception.

 - if it is a `NotFoundHttpException`, it will search for a *page_404* type in your page structure and render that

- If there is no *page_404* exception, it will only render the `page_not_found` template if any of the parent exceptions is a `PageNotFoundException`.

That does not really make sense to me. I guess we need to discuss that in an upcoming Mumble call ^^

**Comment by leofeyer** [comment]
Huh? What do you mean by "page_404 type" and "page_404 exception"?

**Comment by aschempp** [comment]
- "page_404 type" => `tl_page.type` == "error_404"
 - "page_404 exception" => no "error_404"  page type in your page tree

**Comment by leofeyer** [comment]
That seems correct to me, because Symfony has its own 404 handler. We only want to trigger our custom error handler if the exception is a Contao exception and thus has a parent `PageNotFoundException`.

**Comment by aschempp** [comment]
But we are rendering the custom error 404 page in both cases…

**Comment by leofeyer** [comment]
So what is the right solution here? Should we always handle Symfony's `AccessDeniedHttpException` and `NotFoundHttpException` in our pretty error screens listener? Or should we not show the `error_40*` pages if one of the exceptions is thrown directly by Symfony? Both solutions do not make too much sense :)

**Comment by aschempp** [comment]
I think we should always handle 404 and 403 errors, both with a respective page type or with our custom error message, no matter who's throwing what 404 error. The only question to me is if that should only be done for Contao routes (with scope, or a similar check).

**Comment by discordier** [comment]
Only for Contao routes or at least check the `_format` request parameter as it does not make ANY sense to render a Contao 404 HTML when the requested format is json.

**Comment by leofeyer** [comment]
> or at least check the _format request parameter 

Definitely.

**Comment by leofeyer** [comment]
See #334.
