### ISSUE TITLE
Generate a random token on installation

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#302]
See https://github.com/Incenteev/ParameterHandler/issues/78 about a solution with the IncenteevParameterHandler

**Comment by leofeyer** [comment]
What do you mean?

**Comment by aschempp** [comment]
The default kernel secret is `ThisTokenIsNotSoSecretChangeIt`. We should replace the default with a random value so the user does not need to type something manually (but still can if necessary).

**Comment by leofeyer** [comment]
As discussed on Mumble on August 13th, this is a good idea.

**Comment by leofeyer** [comment]
Will you be working on this issue for Contao 4.1 or shall I change the milestone to 4.x.x?

**Comment by aschempp** [comment]
see #358
