### ISSUE TITLE
Failed opening helper/functions.php

### ISSUE THREAD

**Issue by tobemedia** [contao/core-bundle#303]
Adding contao to an existing symfony2 project failed.
I followed the Installation / Activation HowTo at https://github.com/contao/contao.

$ php composer.phar update
After downloading all new deps, the command stops with the following failure message:

PHP Warning:  require(/var/www/symfony/current/system/helper/functions.php): failed to open stream: No such file or directory in /var/www/symfony/current/vendor/contao/core-bundle/contao/bootstrap.php on line 37
PHP Fatal error:  require(): Failed opening required '/var/www/symfony/current/system/helper/functions.php'

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

**Comment by leofeyer** [comment]
What version did you install? The current version neither has the `core-bundle/contao/` subfolder nor the `bootstrap.php` file anymore.
