### ISSUE TITLE
CSS ID is missing in include elements

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#305]
The changes in #250 to merge the CSS classes also affected the handling of the ID. In Contao 3.5 the ID of the content element was used, but in Contao 4 the ID of the module is used now instead.

**Comment by fritzmg** [comment]
Do you mean, if you define an ID both in the include element and the included element, the ID of the included element is used?

**Comment by ausi** [comment]
@fritzmg yes, in Contao 4 the ID of the included element is always used, which is a bug IMO.

**Comment by fritzmg** [comment]
Yeah, I'd also expect that the ID of the include element overrides the ID of the included element.

**Comment by leofeyer** [comment]
Based on my [code comment](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Hybrid.php#L129), I assume that the current behavior is intended.

**Comment by aschempp** [comment]
I also think it should take the ID of the content element if both are set…

**Comment by leofeyer** [comment]
But the point of the new routine is to merge instead of to overwrite. And IDs cannot be merged.

**Comment by ausi** [comment]
In #250 you wrote “It merges the CSS classes if an element is included in another element”, nothing about IDs and also in contao/core#6011 no note about a changed behavior of IDs.

Your code comment is from the Hybrid.php, this issue is about [ContentModule.php](https://github.com/contao/core-bundle/blob/b2a111165f347abcc35045b92f4d6e3a9398ed3d/src/Resources/contao/elements/ContentModule.php#L55) and [ContentAlias.php](https://github.com/contao/core-bundle/blob/b2a111165f347abcc35045b92f4d6e3a9398ed3d/src/Resources/contao/elements/ContentAlias.php#L52).

**Comment by aschempp** [comment]
> But the point of the new routine is to merge instead of to overwrite.

Yep, but noone said who's gonna win with IDs. And to me it's clear the content element should win (because that's "more specific").

**Comment by Aybee** [comment]
I agree with ausi, fritzmg and aschempp to fetch the ID of the included element if the include element has no ID and to prefer the ID of the include element if it is set.

**Comment by leofeyer** [comment]
Fixed in 0f548d4318110f7d6465c84a3c377da804382e0d.
