### ISSUE TITLE
The symlink target "system/themes/flexible" exists and is not a symlink

### ISSUE THREAD

**Issue by gebi84** [contao/core-bundle#308]
i have an public folder in the filesystem "html"
if I add a new public folder "uploads" in the conta filesystem i get this error:

**The symlink target "system/themes/flexible" exists and is not a symlink**

whenn i debug the validateSymlink target i get this:
C:\xampp\htdocs\gebi84/web/files/uploads
C:\xampp\htdocs\gebi84/system/themes/flexible

why it isn't looking for themes in the web directory?
after the error, the first folder isn't public anymore.

contao 4.0 on windows xampp

edit: when i make a new public folder in an existing publlic folder, i get this error too. It copies the new folder to /web/files instead making a symlink:

>Added web/files/html as symlink to files/html.
>  [LogicException]
>  The symlink target "web/files/html\test" exists and is not a symlink.

**Comment by leofeyer** [comment]
What are the exact steps to reproduce this issue?

**Comment by gebi84** [comment]
create a folder in the contao filesystem and make it public. create another folder an make it public. on saving i get the error above with the flexible theme. Perhaps it is an security issue in win 8.1.
To install contao and create the symlinks i needed admin rights. I will try it on win7 too.

**Comment by leofeyer** [comment]
The symlinks have nothing to do with creating folders, therefore I suppose the error can also be triggered by the "recreate symlinks" command in the back end maintenance module? Please try to delete the `system/themes/flexible` folder and see what happens next time you recreate the symlinks.
