### ISSUE TITLE
Rename String class

### ISSUE THREAD

**Issue by comolo** [contao/core-bundle#309]
In PHP 7 **int, float, string and bool** are becoming reserved words.
see: https://wiki.php.net/rfc/scalar_type_hints

It would be nice if you could rename the String class, to make class names PHP 7 compitable.
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/String.php

Thank you.

**Comment by discordier** [comment]
Direct links in the rfc for the paragraph about prohibiting the usage.

Quote (https://wiki.php.net/rfc/scalar_type_hints#scalar_type_hints):
> No new reserved words are added. The names int, integer, float, string, bool and boolean are recognised and allowed as type hints, and prohibited from use as class/interface/trait names (including with use and class_alias).

Quote (https://wiki.php.net/rfc/scalar_type_hints#backward_incompatible_changes):
> `int, integer, float, string, bool` and `boolean` are no longer permitted as class/interface/trait names (including with use and class_alias).

I am currently unsure however how to interpret:
> Since the strict type-checking mode is off by default and must be explicitly used, it does not break backwards-compatibility.

Are these now keywords in global scope or only in strict type checking scope?

In general we have to change the class name for Contao 5 and should deprecate it ASAP if not, drop the class entirely and move the various functions to helper classes within their domain.

**Comment by aschempp** [comment]
Well we don't have to rename to class, we simply remove the global alias. `Contao\String` is perfectly valid.

**Comment by discordier** [comment]
Which will make it impossible to import the class via `use` I guess and therefore requires passing the full namespace.
```php
use Contao\String;

class Foo
{
  // I guess this is illegal as it is ambiguous now.
  public function foo(String $string)
  {
  }

  // legal as full namespace passed here.
  public function foo(\Contao\String $string)
  {
  }

  public function foo()
  {
    // I wonder if this will be an unexpected token or not.
    String::substr('xxx', 1);
  }
```

**Comment by aschempp** [comment]
that might be true. I don't know if PHP recognizes uppercase/lowercase class names.

Anyway, I think just renaming is the wrong solution. We must add alternatives. I'm pretty sure there are Composer dependencies we can add to validate email for example. The class should be split into separate services…

**Comment by leofeyer** [comment]
We will have to rename the class.

**Comment by comolo** [comment]
What about renaming String to let´s say StringUtils **and** set a class alias *only on non-PHP7 environments* for String pointing to StringUtils?

**Comment by discordier** [comment]
This will lead to confusion when Contao works flawless on PHP<7 with all extensions and breaks "randomly" with PHP7.
I vote for renaming it without any class alias at all.

Semantic versioning comes to our rescue here as we are currently requiring PHP ~5.4 - and therefore "everything within the 5.x series but more recent than or equal to 5.4" - and therefore we can savely drop the class name when bumping to PHP ~7.0.

**Comment by aschempp** [comment]
First I liked @comolo's idea, but now I think @discordier is right. Our composer requirement do not "allow" PHP 7 and we can "keep that" as long as there is a problem with the String class. However, again, I'm totally against keeping it just the way it is. We can start now to "clean it up".

There are useless or outdated methods we could drop:
 - [`String::wordWrap()`](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/String.php#L354)
 - [`String::splitCsv()`](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/String.php#L389)
 - [`String::toXhtml()`](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/String.php#L409)
 - [`String::toHtml5()`](https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/String.php#L444)

Simple Tokens should get their own class, like Insert Tags do:
https://github.com/contao/core/blob/d11b2257e9a9c2b9b5daadb383298782f3a065d0/system/modules/core/library/Contao/String.php#L480

`srcToInsertTag` and `insertTagToSrc` can be moved to the `InsertTags` class.

Then there's not much left and we should check which of the remaining methods are actually used anywhere (like `String::censor()`).

**Comment by leofeyer** [comment]
BTW, we are also not compatible with HHVM yet. I have once run a test:

https://travis-ci.org/contao/core-bundle/builds/64407716

**Comment by discordier** [comment]
well, the hhvm build was https://travis-ci.org/contao/core-bundle/jobs/64407720 but yes, we are not compatible yet.

**Comment by leofeyer** [comment]
> 15:38 (Kanal) Toflar: class String extends StringHelper {}
> 15:38 (Kanal) Toflar: und dann StringHelper:: nutzen im code?

This is the most reasonable suggestion so far, because there are quite a few methods such as `substr()`, which belong into a string class.

**Comment by leofeyer** [comment]
According the PHP CS the method should be called `StringUtil`.

**Comment by leofeyer** [comment]
As @discordier pointed out, we don't need to create a `String extends StringUtil` class. The autoloader could create aliases (`class_alias('Contao\\StringUtil', 'Contao\\String')` und `class_alias('Contao\\StringUtil', 'String')` in PHP < 7 and throw an exception in PHP >= 7.

**Comment by leofeyer** [comment]
The majority of the @contao/developers however prefers the `String extends StringUtil` class solution.

**Comment by discordier** [comment]
So, @ausi and @aschempp appear to prefer the following:
```php
namespace Contao;

if (version_compare(PHP_VERSION, '7.0', '>=')) {
    throw new \RuntimeException('The string class can not be used in PHP ' . PHP_VERSION);
} else {
    trigger_error(
        'The string class can not be used in PHP 7.0+ and has been deprecated, ' .
        'please use \Contao\StringUtils', E_USER_DEPRECATED
    );
}

class String extends StringUtils
{
    /* .... */
}
```

**Comment by fbender** [comment]
Will this change come in 4.x or even 3.x? Would be nice to have a compatible "mode" that can be leveraged by developers as early as possible.

**Comment by aschempp** [comment]
We have discussed this topic in the public Mumble call. As far as I can recall, Contao 3.5 will not be changed. Therefore, Contao 3.5 might not work on PHP 7.

As Contao 3.5 is supported until fall 2016, that should be fine if you look at the release/support plan for PHP 5: http://php.net/supported-versions.php

**Comment by ausi** [comment]
IMO we should also change it in Contao 3.5 if this is the only compatibility issue it has with PHP 7.

**Comment by leofeyer** [comment]
Of course it will be changed in Contao 3.5 as discussed on Mumble :)

**Comment by fbender** [comment]
awesome, thanks!

**Comment by leofeyer** [comment]
Changed in 7ffe31fa9b14af44132a0919bd20149750166d2d.

**Comment by leofeyer** [comment]
Back ported in contao/core@007b2af22011307e2f2ccbf39a15823c717aeb28.

**Comment by rorych** [comment]
Hi there, i know this issue is very old allready, but i just had a Contao 3.5.20 Installation that was installed on Contao PHP 5.6 change to 7.0 and i got the String Class Error. How can that be?
What else is there to look out for?

**Comment by Toflar** [comment]
I guess the error is coming from an incompatible extension?

**Comment by rorych** [comment]
Okay, i will check them one by one.

Thanks
