### ISSUE TITLE
icons.css wrong PDF icon

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#311]
The `.ext-pdf` CSS class displays *iconPLAIN.gif* instead of *iconPDF.gif*.

IMO [assets/contao/css/icons.css:68-70](https://github.com/contao-components/contao/blob/d80238fdd23c4367137282f0c4d9533a57d84307/css/icons.css#L68-L70) should be removed, the correct image is already set some lines above in [assets/contao/css/icons.css:60-62](https://github.com/contao-components/contao/blob/d80238fdd23c4367137282f0c4d9533a57d84307/css/icons.css#L60-L62).

**Comment by aschempp** [comment]
see #253

**Comment by leofeyer** [comment]
Fixed in b207733ec28ab63e658048c9277c573a26ffcb5b.
