### ISSUE TITLE
Error when deleting backend user

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#312]
`Catchable Fatal Error: Argument 1 passed to tl_user::removeSession() must be an instance of Contao\DataContainer, string given, called in /home/travelne/public_html/development/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php on line 1525`

Seems to be related to https://github.com/contao/core/issues/5353 and https://github.com/contao/core/commit/55c66f39654273d4c3ee9a3c940112aa9b1a8010

**Comment by leofeyer** [comment]
This is actually a duplicate of #301 (meanwhile fixed).
