### ISSUE TITLE
Replace custom config files with app/Resources

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#314]
We should replace `dcaconfig.php` and `langconfig.php` with `app/Resources/contao/…`. This way we can drop the two files in Contao 5 or so.

"Replacing" probably means updating the manual and notice in the files, as well as adding deprecation info into our document files.

**Comment by leofeyer** [comment]
Would make sense if we also moved the `localconfig.php` file there.

**Comment by aschempp** [comment]
Well I would not move the existing files, because they are "legacy". The new config obviously already is in `app/Resources/`, same as the parameters.yaml

**Comment by leofeyer** [comment]
So `localconfig.php` is legacy but `dcaconfig.php` and `langconfig.php` are not?

**Comment by aschempp** [comment]
No, you got me wrong. People should not add a `dcaconfig.php`. The should add a file to `app/Resources/contao/dca/tl_user.php` if they want to modify the `tl_user` DCA.

**Comment by leofeyer** [comment]
Ah, ok, +1 then.

**Comment by leofeyer** [comment]
Added in adec51dfeaf71a1d82ae11094818dbe817860ede.

**Comment by Riveryuan** [comment]
I want add a field to tl_content named 'itemData', I created file: app/src/Resources/contao/dca/tl_content.php, but this file not loaded..........

**Comment by Riveryuan** [comment]
> No, you got me wrong. People should not add a `dcaconfig.php`. The should add a file to `app/Resources/contao/dca/tl_user.php` if they want to modify the `tl_user` DCA.

Not working.......
I tried 
`app/src/Resources......`
`app/Resources......`

**Comment by fiedsch** [comment]
Did you clear the cache after you made the changes?

**Comment by Riveryuan** [comment]
I tried "contao-console cache:clear", it's working! 
Thank you!

**Comment by leofeyer** [comment]
@Riveryuan Please do not hijack existing tickets but create a new one instead.
