### ISSUE TITLE
Pagination active class

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#315]
In b1a3039f97385e406201d64ab5cbf5e908d76d2c the class for the active pagination item was changed from `current` to `active` in `Pagination::getItemsAsString()` but not in [pagination.html5:18](https://github.com/contao/core-bundle/blob/b2a111165f347abcc35045b92f4d6e3a9398ed3d/src/Resources/contao/templates/pagination/pagination.html5#L18). I think it should also be changed in the template.

Related Ticket: contao/core#5947

**Comment by leofeyer** [comment]
Fixed in b50f4163da43ade4cc52e69098123a703c382e55.
