### ISSUE TITLE
New Auth by LDAP, Shibboleth and other

### ISSUE THREAD

**Issue by katgirl** [contao/core-bundle#316]
We need an auth by other connectors to produce the system by public facilities

If we have then our own OpenLDAP we can have a SSO by forum, website, ....

**Comment by aschempp** [comment]
As soon as we implement full Symfony security (see https://github.com/contao/core-bundle/issues/122) this will be a job for a Symfony Bundle.

**Comment by discordier** [comment]
The current problem is, that we are way to centralized on calling the user classes directly which will not be possible when using other authenticators as they have their own user classes.
I have just implemented JWT authenthication in a symfony project for example. The only thing needed from symfony sides regarding the token are the roles of the authenticated user and an untyped user information.
We are mixing in Contao several things up here. Authentication and Authorization are the domain of the symfony firewall where determining the user data (wo is it, what is the user id, the real name etc.) and using it in controllers must be provided somehow else.
I hvae not yet waded through the security components en detail but I strongly want to emphasize that we must not assume that an user is originating from FOSUserBundle or the like. There are so many different types of Authorization out there that we can not let any slip through.
@aschempp Maybe we could talk about #122 in Lyss?

**Comment by aschempp** [comment]
We sure can. But be aware that I already drafted that implementation in https://github.com/aschempp/contao-core-bundle/tree/feature/advanced-security and it is supposed to be BC. It was not finished because of a lot of open questions which lead to the "simple" implementation.

**Comment by aschempp** [comment]
is this still relevant?

**Comment by discordier** [comment]
For me it is, I still need a way to use other authentication mechanisms than the Contao Database. Using the hooks was way too cumbersome.

Being able to swap the authentication provider and the user provider would be very cool, however the latter is not so important to me.

**Comment by Toflar** [comment]
It's all possible using Symfony auth now, no?

**Comment by aschempp** [comment]
Jup it is…
