### ISSUE TITLE
Cache class usage

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#317]
I think the Cache class is not used anywhere and thus can be dropped in the next major version.

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Cache.php

**Comment by aschempp** [comment]
:+1:

Probably better to use doctrine/cache or similar which also allows for memcached and more advanced configuration.

**Comment by discordier** [comment]
:+1: for marking it deprecated and removing in 5.0
:+1: for using doctrine/cache (I am already using it in MetaModels in Contao 3 for a long time now).

**Comment by leofeyer** [comment]
First of all, `doctrine/cache` does something completely different that our `Cache` class. Second of all, it is wrong that the `Cache` class is not used. Please search for `Cache::` in your IDE and see for yourself.

**Comment by qzminski** [comment]
Yeah, sorry, you're right. I don't know why my IDE did not find results when I looked explicitly for "class usage".
