### ISSUE TITLE
Move insert tags for news, events etc. to the respective bundle

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#318]
The `InsertTags` class in `contao/core-bundle` still handles inserttags for some of the other bundles. This should be refactored.

Feel free to assign this to me :-)

**Comment by aschempp** [comment]
This can only be correctly implemented after the hooks are converted to events…

**Comment by leofeyer** [comment]
You know that is not true :)

**Comment by aschempp** [comment]
Well I'm not gonna write a legacy class and a globals variable if we can add a correct event listener. Might depend on @Toflar too cause he wanted to suggest a new insert tags approach (ESI stuff).

**Comment by discordier** [comment]
I would prefer to entirely render all of these as ESI via sub requests as discussed in Lyss.
Of course each of these routes could then be defined/handled in the corresponding bundle.

However, this is then a breaking change, as currently you are only required to require `contao/core-bundle` to have the inserttag being replaced (as long as there are classes present with the correct names, `NewsModel` etc.). In future you will also need to require the news-bundle to have the insert tags in addition to the classes.
Granted, this is more of a bc breaking bugfix as the insert tags do not make much sense without the corresponding classes but I simply wanted to point this out. :)

**Comment by aschempp** [comment]
I thought about the BC problem, but I think it’s not really valid. As you already pointed out, the insert tags will not work anyways in the current implementation (if e.g. contao/news-bundle is not installed).

**Comment by Toflar** [comment]
Well, what would those InsertTags do if there's no e.g. news data? :D The BC break is that it would output `{{news::foobar}}` instead of replacing it with `''` but I mean that's really neglectable.

**Comment by aschempp** [comment]
> The BC break is that it would output {{news::foobar}} instead of replacing it with '' but I mean that's really neglectable.

Not true, insert tags are replaced with empty content (and logged) if there is no replacement.

**Comment by Toflar** [comment]
Ah okay, so not even a BC break there...

**Comment by aschempp** [comment]
I even guess it would be a bug fix because you would currently get exceptions (using unavailable classes and tables). But anyway, we need the events / ESI first, and I don't know if that will make it into 4.1…?

**Comment by discordier** [comment]
Go  @Toflar, go! ;)

**Comment by aschempp** [comment]
see https://github.com/contao/core-bundle/pull/471
