### ISSUE TITLE
Add insert tag for Request::getBaseUrl

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#322]
In my current case, I want to link the page logo to the page root. I'm using `{{env::path}}`  which returns the base URL and path, where path is generated from `Request::getBasePath`. This, however, does not include the entry point script (e.g. `app_dev.php`) if any exists.

We should add such a method to the `InsertTags` class, but probably not to the `Environment` class as developers should use the request directly.

**Comment by leofeyer** [comment]
What do you suggest? An insert tag just for the entry point script or an insert tag for the extended path (`{{end::path?script=1}}`)?

**Comment by aschempp** [comment]
A new insert tag for sure. `{{env::script}}` is already take though. Maybe something like `{{env::entrypoint}}´ ? Though the name is hard to understand for non-developers.

**Comment by aschempp** [comment]
`{{env::scriptpath}}` ?

**Comment by leofeyer** [comment]
> An insert tag just for the entry point script or an insert tag for the extended path

What is the insert tag supposed to output?

**Comment by aschempp** [comment]
`System::getContainer()->get('request_stack')->getCurrentRequest()->getBaseUrl()` 

(just out of my head ;-) )

**Comment by leofeyer** [comment]
Implemented in b1c2065335877ea4f041e64e68fd1c252ed51d16. Don't know if you are happy with the naming?

**Comment by aschempp** [comment]
makes sense :+1:

**Comment by leofeyer** [comment]
It is actually "path with script name", because "base URL" in the Symfony context would be only `/app_dev.php`.

**Comment by aschempp** [comment]
which would work perfectly fine, wouldn't it?

**Comment by leofeyer** [comment]
Huh? I was explaining why the naming of the insert tag might be incorrect.

**Comment by aschempp** [comment]
well you should probably remove the scheme and host and path, because I might want to redirect to a different domain…

**Comment by leofeyer** [comment]
How do you set up the link to the home page then? Here's how it works right now:

```
// env::base
http://www.example.com/path/to/contao/

// env::base_url
http://www.example.com/app_dev.php/path/to/contao/
```

If I change the logic, it would be:

```
// env::base
http://www.example.com/path/to/contao/

// env::base_url
app_dev.php
```

So to get an equivalent to the "env::base" tag, you would have to use:

```
// env::host env::path env::base_url /
http://www.example.com/path/to/contao/app_dev.php/
```

Is this the desired behavior?

**Comment by aschempp** [comment]
What we need to remember is that `$request->getBasePath()` is not the same as our `{{env::base}}`. Therefore, even if the method is called `getBaseScript()` it's not related to our `base` insert tag!

`/app_dev.php` is a perfectly valid value on it's own. It's an absolute path to the entry point script. If Symfony is installed in a subfolder (unlikely due to `/web`, but possible), the path would be included.
Therefore if I want to point to another domain, I can use `http://example.com{{env::base_script}}`. With your implementation, that would not be possible because you already include the domain.

**Comment by leofeyer** [comment]
So you want me to change it?

**Comment by aschempp** [comment]
I think it would be more flexible if you change it…

Just a question because you might know: It does not output a script if there is none in the URL, right?

**Comment by leofeyer** [comment]
Changed in b27f38a0e4cb2a813eb9f32f0e5f7b77f9f7cd9b. It does not output a script if there is none in the URL.
