### ISSUE TITLE
[4.0.1] Wrong BUILD constant

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#323]
[constants.php:13](https://github.com/contao/core-bundle/blob/38baa2e4f56b6cb2a71fc4b3c6c28a873d78d278/src/Resources/contao/config/constants.php#L13) should be `define('BUILD', '1');`.

**Comment by leofeyer** [comment]
I don't think we are using the `constants.php` file anymore, therefore we won't be incrementing the version and build numbers anymore. @contao/developers Do I recall this correctly?

**Comment by Toflar** [comment]
Afaik we couldn't agree on this.

**Comment by ausi** [comment]
It’s used in the backend to show the current version, that’s how I noticed it.

**Comment by discordier** [comment]
@Toflar is right, we did not come to an final agreement on this one. However I stated (and still am) we can not provide reliable information with this constant anymore and therefore we must drop it.

**Comment by aschempp** [comment]
Yes, we could not agree. But the fact that our debug toolbar shows "Contao 4.0.1" but the constant says something else is stupid to me. The constant should be the core-bundle version, abd sure be deprecated and dropped in 5.0

**Comment by leofeyer** [comment]
I have increased the build number in version 4.0.2. Still want to discuss this though.

**Comment by leofeyer** [comment]
We have discussed it on Mumble on August 13th. We want to keep incrementing the version and build numbers in Contao 4. However, in Contao 5, the constants will be removed.

**Comment by Toflar** [comment]
The alternative using https://github.com/contao/core-bundle/blob/hotfix/4.0.3/src/DependencyInjection/Compiler/AddPackagesPass.php#L54 should be documented in `DEPRECATED.md`, however.

**Comment by leofeyer** [comment]
@Toflar You are right.

**Comment by leofeyer** [comment]
Documented in e8e54a0f46a50ed5d135ba87bc4dc59b6103a98a.
