### ISSUE TITLE
Renaming a folder does not rename the symlink

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#332]
If a folder is renamed in the file manager (backend), the corresponding alias/symlink in /web is not renamed therefore the content can't be served.

**Comment by leofeyer** [comment]
Strangely enough, the symlinks are renamed on my system, too. However, there is no routine in Contao, so I currently don't really know how this works. Did you try it on your Mac?

**Comment by leofeyer** [comment]
It seems that Mac OS takes care of renaming the symlinks.

**Comment by leofeyer** [comment]
Fixed in 5a4093faf0b54843dffb86a083aad756ef4f89d1.

**Comment by leofeyer** [comment]
I have implemented a more sophisticated solution in 086caa2b1095db36eb924f42c369cd20db282d24.
