### ISSUE TITLE
Remove the `eager` and `lazy` loading options

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#333]
As e.g. stated in contao/core#7928, the model handling needs to be fixed and optimized.

**Eager and lazy loading**

Right now it is possible to pass `['eager' => true]` as an option to enforce eager loading of related models. However, it is not possible to pass `['eager' => false]` to enforce lazy loading. 

**Retrieving related models**

Currently the query builder generates a JOIN statement and adds the related columns to every row. The advantage of this approach is that there is only one database query. The disadvantage is that the amount of data sent is quite big.

**A possible solution**

To solve both issues, we should simply remove the `eager` and `lazy` options from the DCA and always use lazy loading unless `['eager' => true]` is explicitly set. It will keep the queries small and it will load existing models from the registry instead of creating them from the DB result.

@contao/developers What do you think?

**Comment by Toflar** [comment]
I think we should use this time to elaborate using doctrine ORM instead and forget about our own model implementation.

**Comment by leofeyer** [comment]
No, this is an entirely different topic. We need a fix for the current implementation (see  contao/core#7928).

**Comment by fritzmg** [comment]
Doctrine ORM uses a lot of memory as well. We always refrained from using it in Symfony projects where a lot of data was handled.

**Comment by Toflar** [comment]
Every ORM uses a lot of RAM if not handled correctly...
But yeah, we can drop the eager loading - I never used it anyway.

**Comment by leofeyer** [comment]
You have used it a lot without knowing, because it has been defined in the DCA :)

**Comment by Toflar** [comment]
I mean in my own implementations. Obviously I know where it's defined and how it works.

**Comment by aschempp** [comment]
Well the most simple solution would be to set all core DCA's to `eager=false`? I'm with @Toflar that I would prefer Doctrine ORM, though I agree that's not gonna be simple.

**Comment by fritzmg** [comment]
> Every ORM uses a lot of RAM if not handled correctly...

Not sure how you could handle such a simple case incorrectly. Sure, any ORM will cause a much higher memory footprint, but the advantage of Contao's Model is, that its footprint is comparatively lightweight - unless a related model has to be loaded. Then its memory consumption explodes (where as with Doctrine ORM, it would stay lower in comparison).

**Comment by aschempp** [comment]
> … unless a related model has to be loaded. Then its memory consumption explodes …

That does not really make sense to me. Why would that be the case?

**Comment by fritzmg** [comment]
I did a little analysis some time ago: https://community.contao.org/de/showthread.php?52268-Newsarchiv-mit-%FCber-10-000-Eintr%E4gen-sprengt-Speicher&p=337337&viewfull=1#post337337
It seems Contao is creating a related object for **every** item in the model. This means, if there are 10,000 news entries in one model, all of the same news archive, there will also be 10,000 objects of the _same_ news archive. This is why the memory consumption explodes. The objects of the related model even consume more memory than the news entries themselves.

**Comment by aschempp** [comment]
That certainly should not be the case since we have a model registry. If that's really true then its a bug we must fix.

**Comment by fritzmg** [comment]
> That certainly should not be the case since we have a model registry. If that's really true then its a bug we must fix.

It does not work indeed. It's easy to test. Just put an echo here: https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Model.php#L163, e.g. `echo "related object not found in registry"` and load 10000 news entries via `\NewsModel::findPublishedByPids(…);` or just `\NewsModel::findAll();`

You will get `"related object not found in registry"` 10000 times (and thus there are 10000 objects in memory for the same news archive).

**Comment by leofeyer** [comment]
We have just discovered a bug in the `Model` class: faeea6e7ffa37ede2a21f62213fe01047815d00f

**Comment by fritzmg** [comment]
:+1: looks good. With the faeea6e fix the memory consumption drops from __187.2 MiB__ to __66.9 MiB__ :) (with my 10,000 news entries dataset)

**Comment by discordier** [comment]
So this now means each item is using about 6.85056kb RAM. Still a bit much but at least somewhat reasonable.
Should be fixed then.

**Comment by leofeyer** [comment]
Back-ported in contao/core@8ede060a871dc503e6aa14c0884224a55aaa51f9.
