### ISSUE TITLE
The file "app/logs/error.log" does not exist after an error occurred.

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#335]
I tried to test the module newsletter list with Contao 4.0.2 but I received an error and the file "error.log" does not exist in "app/logs". I have only `newsletter_1.log` and `dev.log`.

**Comment by leofeyer** [comment]
Did you enable error logging in the back end settings?

**Comment by leofeyer** [comment]
Did you check the `app/log` directory? There should be a `prod.log` and/or `dev.log` file.

**Comment by lionel-m** [comment]
> Did you enable error logging in the back end settings?

I have not found this option in the settings... (?)

> Did you check the app/log directory? There should be a prod.log and/or dev.log file.

Yes and I have the dev.log file but the latest update is dated 2015-08-16.

**Comment by leofeyer** [comment]
What kind of error is it? How can I reproduce the issue?

**Comment by lionel-m** [comment]
The page has returned an error message that says:

> What's the matter?
An error occurred while executing this script. Something does not work properly.
How can I fix the issue?
Open the app/logs/error.log file and find the associated error message (usually the last one).
...
...

The problem is that the `error.log` file does not exist in the `app/logs` folder.

I have found the problem with the module newsletter list with `app_dev.php` but why the error.log is not generated?

For info the error was : 

> Newsletter channels without redirect page cannot be used in a newsletter list
500 Internal Server Error - Exception

**Comment by lionel-m** [comment]
PS : I test this version with MAMP...

**Comment by leofeyer** [comment]
See #338, which should fix this issue.

**Comment by lionel-m** [comment]
Perfect ! :+1:
