### ISSUE TITLE
Frontend calls "system/cron/cron.php" instead of "/_contao/cron"

### ISSUE THREAD

**Issue by jamesdevine** [contao/core-bundle#340]
In the frontend Contao is trying to call `system/cron/cron.php` when I believe it should be calling `/_contao/cron` in order to run the cron jobs.

This is coming from line 754 in `/src/Resources/contao/library/Contao/Controller.php` (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Controller.php#L754)

However, when you are on the admin login page Contao does call the correct cron URL. This means that at the moment cron jobs are only being run when someone visits the admin login page.

**Comment by leofeyer** [comment]
Fixed in d2cba1942c24d47c399e954e0b9b08d9658c52a3.
