### ISSUE TITLE
Replace contao/components-installer with RobLoach/component-installer

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#341]
They look very similar, but RobLoach is far more advanced. Dunno if ours is a fork of that?
http://robloach.github.io/component-installer/

**Comment by leofeyer** [comment]
They may look similar, but they still are different. Main difference is that RobLoach installs the components in the `vendor/` directory and copies the resources whereas our installer directly installs into the `assets/` directory.

**Comment by leofeyer** [comment]
BTW, we were using this installer at the beginning, as you can still see here:

https://github.com/contao-components/mootools/blob/55bc0dc9f8e1bbedbcf07c8663ef8f43343ef419/composer.json

**Comment by aschempp** [comment]
Does that make a difference? Our composer plugin also does link from vendor instead of copy ^^
