### ISSUE TITLE
4.0.3 - Upload files and go back

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#345]
If we click the button "Upload files and go back" in the file manager (File upload view), the redirection does not work.

**Comment by leofeyer** [comment]
Did you upload an invalid file or a file that was resized?

**Comment by lionel-m** [comment]
In all cases (without modification, resized and with an error), there is no redirection.

If there is an error, I assume that is the correct behavior (?).

**Comment by leofeyer** [comment]
I cannot reproduce the issue. Which uploader did you use (default or DropZone)?

**Comment by lionel-m** [comment]
Default.

After clicking the "Upload files and go back" button :

![capture d ecran 2015-10-15 a 17 27 02](https://cloud.githubusercontent.com/assets/814476/10518549/441aa2ba-7362-11e5-816f-85174687150f.png)

**Comment by lionel-m** [comment]
I also tested with 3.3.7 and 3.5.0-RC1 (MAMP) and it does not work...

**Comment by leofeyer** [comment]
I have already [asked you](https://github.com/contao/core-bundle/issues/345#issuecomment-140439838) if the file was resized. In this case, it is correct that you are not redirected, otherwise you would not see the error message.

**Comment by lionel-m** [comment]
Sorry for this example but I specified in all cases.

> In all cases (without modification, resized and with an error), there is no redirection.

Without resizing:

![capture d ecran 2015-10-15 a 18 23 08](https://cloud.githubusercontent.com/assets/814476/10520311/d6748c1e-7369-11e5-9111-9a7fa46de173.png)

**Comment by leofeyer** [comment]
Fixed in 2a57506164f88da067bb2d4fd6148afdff56b1c3.
