### ISSUE TITLE
Update TCPDF

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#352]
I get the following message when using `composer update`:

> Package tecnick.com/tcpdf is abandoned, you should avoid using it. Use tecnickcom/tcpdf instead.

**Comment by leofeyer** [comment]
Changing the vendor name just to remove the dot – oh well …

**Comment by leofeyer** [comment]
Adjusted in 67c4a83e5f61ecf5df1ab7ad30ce1cf4ebfb8713.
