### ISSUE TITLE
Warning: grapheme_substr(): grapheme_substr: length is beyond start

### ISSUE THREAD

**Issue by bytehead** [contao/core-bundle#357]
Warning: grapheme_substr(): grapheme_substr: length is beyond start
500 Internal Server Error - ContextErrorException

My installed versions:
````
contao/core-bundle                        4.1.x-dev 090055e           Contao 4 core bundle
contao/installation-bundle                dev-master c424de5          Contao 4 installation bundle
````

I tried to edit my themes (get parameters: `contao?do=themes`).

My theme is called `TICK`.

For more information see attached screenshot.

![bildschirmfoto 2015-10-07 um 15 27 29](https://cloud.githubusercontent.com/assets/754921/10338749/fe5185ec-6d07-11e5-8529-693bb12752ff.png)

**Comment by leofeyer** [comment]
Here is the code in question:

```php
public static function substr($s, $start, $len = 2147483647)
{
    static $bug62759;
    isset($bug62759) or $bug62759 = extension_loaded('intl') && 'à' === grapheme_substr('éà', 1, -2);

    if ($bug62759) {
        return PHP\Shim\Intl::grapheme_substr_workaround62759($s, $start, $len);
    } else {
        return grapheme_substr($s, $start, $len);
    }
}
```

The first call (`'à' === grapheme_substr('éà', 1, -2)`) causes the problem. It looks like a test for the existence of a PHP bug, which should probably be silenced?

**Comment by leofeyer** [comment]
Which PHP version are you using?

**Comment by bytehead** [comment]
PHP 5.6.4

**Comment by leofeyer** [comment]
Also see: https://github.com/concrete5/concrete5/issues/1459

**Comment by bytehead** [comment]
The `grapheme_*` functions seem to be buggy on PHP 5.6.4. I run the unit tests from [tchwork/utf8](https://github.com/tchwork/utf8) and got some errors.

After updating the PHP version to 5.6.14 the tests (inclusive the skipped ones in https://github.com/nicolas-grekas/Patchwork-UTF8/blob/master/tests/Patchwork/Tests/PHP/Shim/IntlTest.php#L83-L86) did run through.

Sad to say, that the issued error within contao still exists...

**Comment by bytehead** [comment]
Update: I did not restart the php built-in webserver - now everything is running fine :+1:

**Comment by bytehead** [comment]
You probably have to raise your PHP requirements for Contao 4.x, don't you?

**Comment by leofeyer** [comment]
You may be right. Did you try it with PHP 5.5 and PHP 5.4? I only have PHP 5.6 here on my local machine.

**Comment by bytehead** [comment]
It actually runs in all PHP versions except 5.3 [1]. It's probably somehow directly related to 5.4.6. I don't know, if it's even possible to trigger TravisCI to run in 5.6.4 (first attempt failed [2]). On my local machine I  can't go back to 5.6.4.

1: https://travis-ci.org/bytehead/Patchwork-UTF8/builds/84168045
2: https://travis-ci.org/bytehead/Patchwork-UTF8/builds/84168599

**Comment by bytehead** [comment]
I don't now how expressive the tests are here: https://3v4l.org/kIYds

It seems to work even with 5.6.4 (https://3v4l.org/kIYds/perf#tabs).

**Comment by leofeyer** [comment]
So, we can close the ticket eventually, can't we? Our minimum requirement ist PHP 5.4, therefore we are safe.

**Comment by bytehead** [comment]
:+1:  for me.

**Comment by bytehead** [comment]
I definitely have a problem with this - but it is somehow related to my php-stack.
My php-stack is set up with homebrew on OSX 10.10.5.

Installed php-formulas: 
- php56
- php56-intl
- php56-mcrypt
- php56-mongo
- php56-xdebug

The failure does not show up, if `php56-intl` is not installed.

But the `php56-intl` extension is required by [leaue/uri](https://github.com/thephpleague/uri/blob/master/composer.json#L23), which itself is required by [contao/core-bundle](https://github.com/contao/core-bundle/blob/develop/composer.json#L24).

**Comment by leofeyer** [comment]
I have the exact same setup, Homebrew on OS X 10.10.5 with the following formulas:

php56
php56-intl
php56-mcrypt
php56-opcache
php56-xdebug

And I do not have this problem.

**Comment by bytehead** [comment]
Really weird. I don't have a clue anymore...

**Comment by leofeyer** [comment]
Do you have PHP 5.6.14? When was the last time you run `brew update && brew upgrade`?

**Comment by bytehead** [comment]
yes:
- PHP 5.6.14
- intl Version 1.1.0
- ICU Version 55.1
- ICU Data version 55.1
- mcrypt 2.5.8
- mongo 1.5.8
- xdebug 2.3.3

**Comment by bytehead** [comment]
I ran it actually today.

**Comment by leofeyer** [comment]
Can you try to disable xdebug? I have only enabled it on the command line.

**Comment by bytehead** [comment]
phpunit of [tchwork/utf8](https://github.com/tchwork/utf8) runs on my cli... and the tests fail.

**Comment by leofeyer** [comment]
@nicolas-grekas Any idea?

**Comment by bytehead** [comment]
I've also placed an issue here: https://github.com/tchwork/utf8/issues/53
