### ISSUE TITLE
Contao 4: SMTP-Einstellungen werden falsch geladen

### ISSUE THREAD

**Issue by nistech** [contao/core-bundle#363]
Wenn man in den Einstellungen von Contao die SMTP-Daten eingibt, werden diese in der localconfig.php gespeichert. Jedoch werden sie in den Einstellungen nicht korrekt angezeigt (d.h. die falschen Werte) und funktionieren auch nicht. Das Kontrollkästchen "E-Mails via SMTP versenden" selbst funktioniert. Es sieht so aus, als ob Standardwerte angezeigt werden (z.B. Server: 127.0.0.1).

**Comment by fritzmg** [comment]
I am guessing the values probably come from the parameters.yml now.

**Comment by leofeyer** [comment]
We either have to remove the fields from the settings or map the values to the `parameters.yml` file. I prefer the first solution. @contao/developers /cc

**Comment by fritzmg** [comment]
Hm, but if you remove the fields from the settings, where will they be set if you install Contao via /web/install.php for example?

**Comment by aschempp** [comment]
It's a general problem of how to configure the Symfony application… we still have not found or built a solution for that. @fritzmg you would need to edit your `app/config/config.yml` to add the settings.

**Comment by fritzmg** [comment]
I see. I know that these configurations are done in `app/config/config.yml` and `app/config/parameters.yml`, however I didn't know that there currently is no way to configure it from Contao itself as well.

**Comment by leofeyer** [comment]
We should probably configure them in the installation bundle?

**Comment by aschempp** [comment]
I dont know. Do we configure all parameters in the parameters.yml from the install tool? Which means there would not be a backend options for them?

The alternative would be to habe a simple DC that writes the parameters.yml instead of the config.php

**Comment by leofeyer** [comment]
The install tool does no more than the Incenteev handler. It creates the `parameters.yml` file if it does not yet exists. Once the file has been created, you can no longer edit it in the install tool.

Since the Incenteev handler asks the DB and the mailer credentials, we should do the same.

**Comment by leofeyer** [comment]
Fixed in 6cd74de767d4aa3b4ed9c607bee91110fb54f1d2. The install tool ticket is here: contao/installation-bundle#5

**Comment by nistech** [comment]
Und wie funktioniert das mit den SMTP-Einstellungen nun? Was genau mus man in der paramter.yml eintragen? Ich habe das gespeichert: 
mailer_transport: smtp
mailer_port: 587
mailer_encryption: ssl
Natürlich auch Server, Benutzername und Kennwort. Es wird aber beim Formular absenden keine Mail verschickt.

**Comment by bytehead** [comment]
Vielleicht hier mal noch mittels Dokumentation von Swiftmailler die Einstellungen überprüfen: http://symfony.com/doc/current/reference/configuration/swiftmailer.html

**Comment by nistech** [comment]
Vielen Dank für den Hinweis. Das bringt mir leider nichts. Die Einstellungen sind korrekt. Contao sendet trotzdem nicht.
Es ist auch nicht wirklich eine Lösung, die SMTP-Einstellungen aus dem Backend zu entfernen und die User irgendwie zurecht kommen zu lassen....

**Comment by leofeyer** [comment]
Deswegen gibt es ja auch ein zweites Ticket bezüglich Abfrage der Mail-Zugangsdaten im Installtool: contao/installation-bundle#5

**Comment by nistech** [comment]
Das heißt also, ich kann im Moment Contao 4 nicht zum Verschicken von E-Mails überreden?
Noch zum Installtool:
Im Installtool ergeben die SMTP-Einstellungen meines Erachtens nicht so viel Sinn. In Contao kann man mehrere Webs anlegen. Wenn der Admin nun für jedes Web einen anderen SMTP-Server verwenden möchte, sind die Einstellungen dort doch besser aufgehoben, oder? Ich kann mir das z.B. für mehrsprachige Websites vorstellen.

**Comment by bytehead** [comment]
Falls du eine Contao-Installation brauchst, die möglichst ohne Fehler läuft, rate ich dir, die LTS Version 3.5.x zu verwenden.

**Comment by fboes** [comment]
I also had the strange case that SMTP settings in `parameters.yml` were ignored. The SMTP host stayed at `127.0.0.1`, disregarding everything I tried. Strangely enough the DB settings are imported.

My workaround: Setting the SMTP settings in `system/config/localconfig.php`:

```
$GLOBALS['TL_CONFIG']['smtpHost'] = 'example.com'; // etc
```

Obviously the Contao bundle's `Config.php:loadParameters()` does not read the `mailer_host` as one might expect.

**Comment by rorych** [comment]
I am having the same problem, my parameters.yml is being ignored, even after `rm -rf var/cache`.
I want to change the sender_address and am using this code, but it is always sending from and to the email-address set in the settings of contao. But i want it to be sent from the mail that i setup.

This is my Code:

```yml
parameters:
    mailer_transport: smtp
    mailer_host: mymailserver.com
    mailer_user: noreply@mydomain.com
    mailer_password: 'mypassword'
    mailer_port: 465
    mailer_encryption: ssl


# SwiftMailer configuration
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    sender_address: "%mailer_user%"
    password: "%mailer_password%"
    port: "%mailer_port%"
    encryption: "%mailer_encryption%"
```

**Comment by fritzmg** [comment]
> but it is always sending from and to the email-address set in the settings of contao.

That's the expected behaviour.

**Comment by rorych** [comment]
I know, but i would like to change this for this website.

I'm right in thinking it should be possible by using the sender_address?
If yes, where could it still be cached/stored or what am i doing wrong?

**Comment by fritzmg** [comment]
> I'm right in thinking it should be possible by using the sender_address?

No, Contao always uses the administrator email from the website root or system settings. See [Form.php#L387](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/forms/Form.php#L387) for example:
```php
$email->from = $GLOBALS['TL_ADMIN_EMAIL'];
```
The `$GLOBALS['TL_ADMIN_EMAIL']` variable is populated within [FrontendIndex.php#L202-L210](https://github.com/contao/core-bundle/blob/4.4.7/src/Resources/contao/controllers/FrontendIndex.php#L202-L210):
```php
// Set the admin e-mail address
if ($objPage->adminEmail != '')
{
	list($GLOBALS['TL_ADMIN_NAME'], $GLOBALS['TL_ADMIN_EMAIL']) = \StringUtil::splitFriendlyEmail($objPage->adminEmail);
}
else
{
	list($GLOBALS['TL_ADMIN_NAME'], $GLOBALS['TL_ADMIN_EMAIL']) = \StringUtil::splitFriendlyEmail(\Config::get('adminEmail'));
}
```

**Comment by Borkee** [comment]
maybe you could use a hook:
`
$GLOBALS['TL_HOOKS']['processFormData'][] = array('myFrontEndClass', 'myProcessFormData');
`

and send a new email like
```
class myFrontEndClass extends \Frontend
{	
	public function myProcessFormData($arrPost, $arrForm, $arrFiles)
	{
		$email = new Email();
		$email->subject = 'Subject';
		$email->html = ...
		etc
		$email->from = 'myspecialsuperemail@whatever.com';
		$email->sendTo($arrPost['email']);
	}
}
```

**Comment by rorych** [comment]
Thanks for your inputs.
The thing is, i would like to set this for all Mails (from Forms, over System-Mails to Notification Center Mails)
So the Sender is always the Mail-Adress that is configured in the smtp Options.

I'll keep looking for a way to solve this, if i do, i will comment it here.
