### ISSUE TITLE
Contao 4: Versionsnummernanzeige fehlerhaft

### ISSUE THREAD

**Issue by nistech** [contao/core-bundle#364]
Ich habe Contao 4.0.3 installiert und dennoch zeigt das Backend die Version 4.0.2 an. Weiterhin zeigt es an, dass Contao aktuell ist.

**Comment by leofeyer** [comment]
> Weiterhin zeigt es an, dass Contao aktuell ist.

Was genau bedeutet das?

**Comment by fritzmg** [comment]
The with the the version number is probably related to #323 . In Contao 4.0.3 it still says
```php
// Core version
define('VERSION', '4.0');
define('BUILD', '2');
```

**Comment by aschempp** [comment]
Probably already fixed: #351

**Comment by leofeyer** [comment]
It is fixed in #351, however we must not forget to adjust the `constants.php` file as long as we are still supporting it.

**Comment by nistech** [comment]
>>Weiterhin zeigt es an, dass Contao aktuell ist.

>Was genau bedeutet das?

Wenn die Versiosnummer, wie von fritzmg gezeigt, nicht stimmt, warum sagt Contao unter "Systemwartung" dann an "Ihre Contao-Version 4.0.2 ist aktuell", obwohl es ja die Version 4.0.3 gibt. Ich weiß ja nicht, wie diese Überprüfung funktioniert, aber meines Erachtens müsste da stehen, dass es die neue Version 4.0.3 gibt.

**Comment by fritzmg** [comment]
Indeed, it says `Your Contao version 4.0.2 is up to date` under _Live Update_ in the _Maintenance_ view.

**Comment by leofeyer** [comment]
Fixed in 5c7365c10c28fcb54a0582b254eb53016c9304f3.
