### ISSUE TITLE
Contao 4: Liveupdate zeigt Fehler an 

### ISSUE THREAD

**Issue by nistech** [contao/core-bundle#365]
Beim Versuch ein Live-Update zu machen, erscheint der Fehler:
 "Das temporäre Verzeichnis (system/tmp) ist nicht beschreibbar"
 Das Verzeichnis ist jedoch beschreibbar für den Contao User.

**Comment by leofeyer** [comment]
Offensichtlich nicht, sonst käme die Fehlermeldung nicht.

**Comment by aschempp** [comment]
gibt es `system/tmp` überhaupt noch? Ist das nicht in `app/cache`?

**Comment by leofeyer** [comment]
Klar gibt es das noch. BC.

**Comment by aschempp** [comment]
Ja aber als Symlink, oder?

**Comment by leofeyer** [comment]
Nein. `system/logs` ist ein Symlink auf `app/logs` aber `system/tmp` lässt sich nicht eins zu eins mappen.

**Comment by nistech** [comment]
>Offensichtlich nicht, sonst käme die Fehlermeldung nicht.

Wirklich witzig. Als ob Contao immer die korrekte Fehlerursache anzeigen würde. Ich arbeite seit Jahren mit Contao und betreibe viele Websites mit Contao als CMS. Und erst Contao 4 macht diese Probleme. Da kann man seine User und Partner ruhig mal ernst nehmen.

Ich verwalte den Debian-Server mit Plesk. Contao läuft unter einem gesonderten Benutzer, dieser hat in dem Verzeichnis system/tmp Schreibrechte (wie auch z.B. im cache-Ordner - hierein kann Contao offenbar schreiben). Dennoch kommt dieser Fehler. Es ist für mich kein großes Problem. Ich kann ja auch manuell aktualisieren. Ich dachte nur, ich gebe mal bescheid. Man will ja helfen.
Übrigens: der Contao-Check gibt keine Fehler aus.

**Comment by leofeyer** [comment]
Es geht ja nicht darum, ob der Benutzer Schreibrechte hat, sondern der PHP-Prozess. Wenn der Ordner z.B. dem Benutzer `web10` gehört, der PHP-Prozess aber unter `www-data` läuft, kommt es zu genau diesem Problem.

**Comment by nistech** [comment]
Ich habe mal die PHP-Fehleranzeige eingeschaltet. Dieser Fehler erscheint:
`Warning: fclose() expects parameter 1 to be resource, null given in /var/www/vhosts/qualli-life.de/httpdocs/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Files.php on line 182`

**Comment by leofeyer** [comment]
Ganz offensichtlich ein Dateirechte-Problem.

**Comment by nistech** [comment]
Das sehe ich anders. Wenn Contao sonst alles schreiben kann (z.B: die config, den cache) und nur bei der Live-Update-Funktion dieser Fehler kommt, dann sollte man mal über diese Funktion nachdenken.

**Comment by leofeyer** [comment]
Das Live-Update ist sowieso noch nicht für Contao 4 verfügbar und die Frage ist auch, ob es das je sein wird. Wenn unser Composer-Paketmanager Ende des Jahres kommt, kann man seine Installation vermutlich auch darüber aktualisieren. Insofern schließe ich das Ticket jetzt erstmal.
