### ISSUE TITLE
Disable the request token check for Symfony forms

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#371]
If Symfony forms are used in a Contao front end module, the request token check should be disabled in favor of the Symfony CSRF token.

**Comment by leofeyer** [comment]
As discussed on Mumble, this will most likely not be possible, since the name of the token variable can be anything. Therefore the only solution seems to be adding the Contao request token to the Symfony form if the Contao 3 framework is active.

Maybe we can add an option to disable the request token check per route.

**Comment by leofeyer** [comment]
Also see https://github.com/contao/core/issues/8080.

**Comment by discordier** [comment]
Enable per route, not disable per route.

**Comment by leofeyer** [comment]
Yes, you are right.

**Comment by Toflar** [comment]
Started https://github.com/contao/core-bundle/pull/374

**Comment by leofeyer** [comment]
Closed in favor of #374 then.
