### ISSUE TITLE
Thoughts about content element and modules as services

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#377]
After coming up with the basic idea behind #376 I figured we could use the very same approach for content elements and modules with dependency injection.

```php
// config.php
$GLOBALS['FE_MOD']['foobar'] = 'app.frontend_module.foobar`;
```

Now the problem is that the module configuration (`tl_module`) is passed to the module constructor, which won't work with dependency injection. But obviously that's a common problem, and DI has a simple solution for it: **factories**

What we could do is the following:

```php
// config.php
$GLOBALS['FE_MOD']['foobar'] = 'app.frontend_module_factory';

// Controller::getFrontendModule()
$data = [/* the module data from tl_module */];
$module = $GLOBALS['FE_MOD'][$name];
if (System::getContainer()->has($module)) {
    $instance = System::getContainer()->get($module)->create($data);
} else {
    $instance = new $module($data);
    // or whatever we do now to create the instance
}
```

The key in `FE_MOD` (or `TL_CTE` etc.) can be the service name of a factory. Factories must follow an interface that has `create` or whatever we call the method. One factory can handle multiple modules by simply checking the `type` column in the data array.

**Pro's and con's:***
 \+ We could use real dependency injection for frontend modules
 \+ It should be pretty much backwards compatible, except if someone does try to create their own instances from the globals array.
 \- It does not solve the module-as-controller thoughts
 \- It provides new features that are likely being replaced later again
 \- We still need the globals array (for now)

**Comment by Toflar** [comment]
Related to fragment implementation which requires modules etc. to be developed as controllers anyway.
