### ISSUE TITLE
Remove the ConfigAdapter class

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#379]
Since the `ConfigAdapter` class is marked `@internal` and the `contao.adapter.config` service is not public, we must not provide a BC layer. I therefore suggest to remove the class and the `adapter.yml` file.

@contao/developers Any objections?

**Comment by aschempp** [comment]
I dislike the idea. It's not unlikely it was used.

**Comment by Toflar** [comment]
-1 from me too. Just useless.

**Comment by leofeyer** [comment]
So what is `@internal` for then?

**Comment by leofeyer** [comment]
As discussed on Mumble, we are pretty sure that we are using `@internal` in a wrong way. We therefore want to keep the class until the next major release.

Symfony `@internal`: http://symfony.com/doc/current/contributing/code/bc.html

**Comment by aschempp** [comment]
We might want to use the new `deprecated` config in the container. Not sure about 2.7 BC though:
http://symfony.com/blog/new-in-symfony-2-8-deprecated-service-definitions?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+symfony%2Fblog+%28Symfony+Blog%29

**Comment by leofeyer** [comment]
I have already tried it yesterday and the `deprecated` key is ignored in Symfony 2.7. However, since the `ConfigAdapter` class is already deprecated, there is no need to additionally deprecate the service IMHO.

**Comment by aschempp** [comment]
Well if it's ignored by 2.7 then I think we should add it. Upcoming PhpStorm plugins might detect that and also strike through services or similar things.

**Comment by Toflar** [comment]
https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/608 <https://github.com/Haehnchen/idea-php-symfony2-plugin/issues/608> ;-)

**Comment by leofeyer** [comment]
As discussed on Mumble on November 5th and given this [Symfony discussion](https://github.com/symfony/symfony/issues/15977), we want to remove the adpater after all.

**Comment by leofeyer** [comment]
Removed in 02ef7b60724ef9588074968d85d8c3c5ab435a30.
