### ISSUE TITLE
Bug in MetaWizard when no site structure added

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#382]
When you create a folder or file but have no pages added yet, you get a nice message because of

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/MetaWizard.php#L94

However, if you try to store it, you get an error because there are no values submitted here: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/MetaWizard.php#L46

Fix: 

```php
foreach ((array) $varInput as $k=>$v)
```

**Comment by leofeyer** [comment]
Fixed in 3ba70d1b5cc7c283b5fee5703709b9db0b8344e3.
