### ISSUE TITLE
Vorschlag: Ausgewählte Teile von CSS und CSS exportieren lassen

### ISSUE THREAD

**Issue by jenda77** [contao/core-bundle#388]
Ich fände toll, wenn man über den CSS-Editor ausgewählte Sachen exportieren könnte. 

Sagen wir mal, dass es 2 Contao-Installation gibt. Dabei möchte ich von der einen in die andere etwas importieren, was bereits dort mit CSS umgesetzt wurde. Dabei möchte ich aber nicht die ganze CSS exportieren, sondern nur deren Teile. 

Eine Exportfunktion an sich wäre auch wunderbar, falls man nur CSS und nicht gleich das ganze Thema exportieren möchte.

**Comment by leofeyer** [comment]
Dieses Feature gibt es bereits in Contao 3.5.
