### ISSUE TITLE
Add requirement for composer

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#396]
Because we have a Composer script handler, we should add composer as `require-dev` to the `core-bundle`

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/blob/master/composer.json#L34

**Comment by aschempp** [comment]
Oh well, stupid me. Dev-dependencies are obviously not installed if using the standard-edition ;-)

**Comment by leofeyer** [comment]
^^
