### ISSUE TITLE
[4.1/develop] File tree issue

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#398]
Steps to reproduce:

1. Give the `fileTree` an `eval` condition for `extensions` like so: `jpg,png`.
2. Open the file picker popup.
3. No file not matching `.jpg` or `.png` is shown. Correct.
4. Open a subfolder.
5. The `extensions` restriction does not seem to be taken into account anymore. Bug.
6. If you close the window now and you reopen it again (which means due to the session value the subfolder of step 4 is already opened) the subfolder will not contain any file not matching `.jpg` or `.png` anymore.

Conclusion: I think it must be some problem in the ajax method which does not apply the filters.

**Comment by leofeyer** [comment]
Fixed in 4ba7952ed3d6e78a2558ef1469299f4c8b0806a0.

**Comment by Toflar** [comment]
:+1:
