### ISSUE TITLE
Change some "Incomplete installation" text

### ISSUE THREAD

**Issue by DyaGa** [contao/core-bundle#399]
For example, there is a text like

```
Please open the Contao install tool by pointing your browser to /contao/install.
```

As I understand there should be `/install.php`.

And link for text `Contao manual` is wrong in:

```
For more information, please refer to the Contao manual.
```

It links to `https://contao.org/manual/installation.html` but there should be other.

**Comment by aschempp** [comment]
https://github.com/contao/core-bundle/issues/385

The new book can be found at https://docs.contao.org/books/manual/4.0/en/01-installation/installing-contao.html
