### ISSUE TITLE
Wrong label for "Create a new folder" action.

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#407]
In the file manager when we want to create a new folder, the second label is: "Contao automatically adds the file extension.". it is the wrong label for this field.

![capture d ecran 2015-11-12 a 13 04 15](https://cloud.githubusercontent.com/assets/814476/11117909/0164b310-893e-11e5-9c7b-2a02cd7523e9.png)

**Comment by leofeyer** [comment]
Fixed in bcc877bbe390c4e1c6df0e98fa9a8d2adb524005.
