### ISSUE TITLE
4.1.0-dev - problem with the help wizard for "Image size" in the content element "text"

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#408]
Add a new content element text and select the help wizard for the "Image size" fields. It returns a lot of unnecessary information.

![capture d ecran 2015-11-12 a 13 35 00](https://cloud.githubusercontent.com/assets/814476/11118481/717f34fa-8942-11e5-8d60-d050a34a3b72.png)

**Comment by leofeyer** [comment]
Fixed in 15683fe57aefd3d298d51c582fea2d3f71ae2e60.
