### ISSUE TITLE
The page picker redirects the user to the file manager

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#409]
When we click the page picker (for example in the content element "text"-> add an image -> Image link target), we access to the file manager. Even if the link is available from there, would it be possible to go directly to the right place?

**Comment by leofeyer** [comment]
This is actually correct. Since you are configuring an image, the picker shows the image picker by default. Once you have selected a page and there is a `{{link::` insert tag stored in the field, the picker will open the page picker by default.
