### ISSUE TITLE
4.1.0-dev - Images selected from the content element "text" are not displayed

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#410]
Original HTML code:

```
<img height="500" width="800" content="files/image.jpg" itemprop="image" alt="" src="files/image.jpg">
```

It works if we change the link such as `src="../files/image.jpg"`

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by lionel-m** [comment]
Sorry...

Create a new content element "text" and add an image. It will be not displayed because the path generated isn't correct.

**Comment by leofeyer** [comment]
I cannot reproduce it. The image is shown correctly in both the back end and the front end.

**Comment by lionel-m** [comment]
In my case, in the back end it's ok too but not in the front end...

This does not work with the original image selected directly from the `files/` folder. But the resized images are displayed in the front end.

**Comment by leofeyer** [comment]
How did you set up the web server?

**Comment by lionel-m** [comment]
I test locally with MAMP. I just added a virtualhost.

**Comment by lionel-m** [comment]
Tested with Contao 4.0.3 and it works perfectly

**Comment by leofeyer** [comment]
What is the generated markup with Contao 4.0?

**Comment by lionel-m** [comment]
### Contao 4.0.3

```html
<figure itemprop="associatedMedia" itemtype="http://schema.org/ImageObject" itemscope="" class="image_container float_above">
    <img height="250" width="312" content="files/images/test.gif" itemprop="image" alt="" src="files/images/test.gif">
</figure>
```

### Contao 4.1.0-dev

```html
<figure itemprop="associatedMedia" itemtype="http://schema.org/ImageObject" itemscope="" class="image_container float_left">
    <img height="500" width="800" content="files/web_design/ruler.jpg" itemprop="image" alt="" src="files/web_design/ruler.jpg">
</figure>
```

**Comment by lionel-m** [comment]
In Contao 4.1 I must add a word (figcaption) with the picture because if not the entire code is not generated.

**Comment by lionel-m** [comment]
Sorry, the folder was not checked "public".

**Comment by leofeyer** [comment]
That was actually my first guess, but since you wrote that it works if you add `../`, I ruled it out.

**Comment by lionel-m** [comment]
Yes I thought the target was not correct so I have changed the source link with firebug and this works with `../` even if the option "public" is not selected.
