### ISSUE TITLE
4.1.0-dev - default blank option for the "Image size" input fields is not accepted

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#411]
Create a new content element "Image" and save. If we do not select the resize mode, an error occurs.

![capture d ecran 2015-11-12 a 19 21 12](https://cloud.githubusercontent.com/assets/814476/11127152/122af864-8973-11e5-864e-5020f3ab8e6c.png)

Normally the default blank option should be accepted. Same problem with the content element "text" -> "Add an image".

**Comment by leofeyer** [comment]
Fixed in 51352b8e5e2e472fa6549898dac532391eddad7d.
