### ISSUE TITLE
E-Mails are not logged

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#413]
Due to the switch to Monolog, E-Mails are no longer logged. The current configuration logs emails to the default logger, which will only log if an error occurs.

**Comment by aschempp** [comment]
The correct solution for this would be to use a logger channel (e.g. `email`) and then configure the standard edition to log the email channel to a separate file.

However, channels are only supported by either tagging a service or defining them in the app config. None of them works for the `Email` class in the core bundle…

**Comment by aschempp** [comment]
I suggest to revert the changes in 9f2b793f5497a8f28a1301f766911931be7cc419
The Email class has "getters" and "setters" to set the log file, which no longer work now (= BC break).

**Comment by leofeyer** [comment]
The `log_message()` function is deprecated and must not be used anymore. I think a separate channel is the correct solution.

**Comment by aschempp** [comment]
What about the log file attribute of the email class? In my opinion we could deprecated the email class for Contao 5 and suggest to use SwiftMailer directly. Then we could still use the deprecated `log_message()` in the deprecated class.

**Comment by leofeyer** [comment]
> What about the log file attribute of the email class?

We broke this in Contao 4.0 already, therefore the feature is gone now IMO.

> In my opinion we could deprecated the email class for Contao 5 and suggest to use SwiftMailer directly.

I don't think that this is possible. The e-mail class has quite a few features that SwiftMailer has not.

**Comment by aschempp** [comment]
> We broke this in Contao 4.0 already, therefore the feature is gone now IMO.

Nope, it was changed in 4.1

How can the email class have more features if it uses SwiftMailer to send mails?

**Comment by leofeyer** [comment]
> Nope, it was changed in 4.1

Then we have to "fix" it :(

> How can the email class have more features if it uses SwiftMailer to send mails?

You have already answered the question yourself. SwiftMailer is used to **send** the mail, but the `Email` class also **compiles** it:

* Prepares the recipient list (handles CSV data, friendly names etc.)
* Automatically embeds internal images
* Logs rejected e-mail addresses

**Comment by aschempp** [comment]
I see. Well it's like a lot of the Contao classes (like `Request`). It provides quick fixes for a few use cases, but it's not extendible at all. Dunno if there are SwiftMailer plugins for that use case, but we're certainly not change the class for 4.1. We just need to fix the logging…

**Comment by leofeyer** [comment]
I have reverted the changes and realized that we'd be loosing log rotation this way (now done by Monolog). Why don't we implement a real solution?

All we need to do is to add a custom handler which extends [ErrorLogHandler](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/ErrorLogHandler.php#L71) and takes an additional, optional argument to override the log file name.

**Comment by aschempp** [comment]
It would be wrong to introduce such a custom handler for BC reason imho. The email log was not rotated before as far as I remember?

**Comment by leofeyer** [comment]
It would also be wrong to directly use the `error_log()` function and to add a log rotate job to rotate the log files instead of using the built-in Monolog log rotation. Especially since we do not know how the developers will name their log files.

**Comment by aschempp** [comment]
Didn't we have these problems solved before?

**Comment by leofeyer** [comment]
As discussed on Mumble, we generally want to store the mail related log entries in `tl_log` with the category `MAIL`. Newsletters are to be stored in the `NEWSLETTER` category with the log file name as prefix.

**Comment by leofeyer** [comment]
Fixed in c9fd76850e268310da26b57723f1f5f7ddcf772f and contao/newsletter-bundle@ef601d99658489bbe6d9da65fa1327334094ec84.
