### ISSUE TITLE
Move FrameworkAwareTrait to the Framework namespace

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#416]
It should not be in the Command namespace…

**Comment by leofeyer** [comment]
I had asked you whether to put this in a separate namespace but you guys wanted the trait to be in the `Command` namespace (because it is only used by the commands). It does not make too much sense there to me either :)

**Comment by leofeyer** [comment]
See #256 and #261.

**Comment by aschempp** [comment]
Well personally I am against setter injection. But for Doctrine repositories, there is no other way. That's why I needed the trait.

**Comment by leofeyer** [comment]
Implemented in 1d985f0259ed8f0d44ffb77bc2ccb6751daf30e3.
