### ISSUE TITLE
Problem with security.yml

### ISSUE THREAD

**Issue by paha77** [contao/core-bundle#417]
In the composer update I always get this error:

```[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
You are not allowed to define new elements for path "security.firewalls". Please define all elements for this path in one config file.
```

How can I avoid this error?

Thank you!

**Comment by leofeyer** [comment]
I don't think that this is Contao related. Can you post your `composer.json` file please?

**Comment by leofeyer** [comment]
See https://groups.google.com/forum/#!topic/symfony2/BOW2fQqeW0Q.
