### ISSUE TITLE
Nachrichten: Bezeichnung von "Neuer Artikel" in "Neuer Beitrag" ändern

### ISSUE THREAD

**Issue by fenepedia** [contao/core-bundle#418]
Ich fände es für die Logik besser, wenn im Bereich Nachrichten die Schaltfläche für einen neuen Newsbeitrag umbenannt wird.

alt: "Neuer Artikel"
neu: "Neuer Beitrag"

Es führt manchmal zu einer Verwechslung. Da es ja auch die Möglichkeit gibt "Neue Artikel" bei den einzelnen Seiten anzulegen. Zur besseren Abgrenzung fände ich das sinnvoll.

Im Englischen dann "New post" statt "New article".

Was haltet Ihr davon?
Änderung erst in der 4er Version, da sonst die ganzen Dokus der 3er nicht mehr passen ;-)

**Comment by aschempp** [comment]
Hört sich schlüssig an :-)

**Comment by fenepedia** [comment]
Bei Erstellen einer neuen Nachricht steht so gar im Breadcrumb schon:

Nachrichten » test » Beitrag ID 1 bearbeiten

**Comment by leofeyer** [comment]
Wie würden wir das im Englischen handhaben? Dort heißt es auch "new article". Eventuell könnte man "new item" sagen?

**Comment by fenepedia** [comment]
"new post"

**Comment by leofeyer** [comment]
"Post" ist eher für Beiträge in Blogs, Foren oder Newsgroups geeignet. Im Grunde ist "article" schon das richtige, da es den journalistischen Beitrag meint.

http://www.dict.cc/?s=beitrag

**Comment by aschempp** [comment]
Auch bei schema.org heisst es Article: https://schema.org/Article

Ich finde die Unterscheidung in Contao aber wichtiger und die Idee von @fenepedia gewinnbringend.

**Comment by leofeyer** [comment]
Ich habe die deutsche Übersetzung auf Transifex schon mal angepasst.

Mit "post" bin ich jedoch nicht glücklich, weil das wirklich in diesem Zusammenhang nicht gebräuchlich ist. Gängige Übersetzungen wären noch "news item" und "news story".

http://www.linguee.de/deutsch-englisch/search?source=auto&query=nachrichtenbeitrag

Wir können also "new item" oder "new story" verwenden, aber ob das besser ist als "article"?

**Comment by fenepedia** [comment]
Mir geht es primär um die Anpassung auf Deutsch, wenn das erledigt ist, können wir auch die englische auf "new article" lassen.

Sonst gefällt mir "new item" am besten.

**Comment by leofeyer** [comment]
Wie auf Mumble besprochen, wollen wir "item" verwenden.

**Comment by leofeyer** [comment]
Geändert in contao/news-bundle@810d87473ef6f2c0469dec8a2b04a1f3383f6918.
