### ISSUE TITLE
Move default configuration to core bundle

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#428]
I was thinking a lot about the app configuration recently, mainly because I am working on a Contao 4 application that is getting more and more complicated.

I propose to move the default configurations to `core-bundle`, which will also make maintenance much easier. The changes would mean:

`app/config/config.yml` would look like this:

````
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: ../../vendor/contao/core-bundle/Resources/config/default/framework.yml }
    - { resource: ../../vendor/contao/core-bundle/Resources/config/default/doctrine_dbal.yml }
    - { resource: ../../vendor/contao/core-bundle/Resources/config/default/twig.yml }
# … and more if necessary
```

In addition to the individual files there could also be a `all.yml` that then loads all the others. It would make it much easier for app developers to include only the default sections needed and override the custom stuff.

I can make a PR for Contao 4.2 if @contao/developers agree :-)

**Comment by discordier** [comment]
I vote against it.
The configuration is not for the core bundle but for the application and therefore should not reside in the bundle location.

**Comment by aschempp** [comment]
Same applies for routing, but we also include that from the bundle.

**Comment by Toflar** [comment]
Not quite sure but I consider this to be something we should discuss on a call :)

**Comment by discordier** [comment]
@aschempp The routing is not the same, as these can be prefixed etc. You are talking about application configuration however, which can not be overridden by simply importing it with another prefix or the like.
There is a reason that every bundle only provides default configuration for itself and not the others.
It is simply a matter of domains, do not tamper in other people domains, at least not if you are not the root domain (application level).

**Comment by aschempp** [comment]
We've had this discussion before. I'm not saying to override bundles. I'm saying to provide our defaults as files that can be included. Overriding is as simple as removing our file and adding whatever you want.

**Comment by discordier** [comment]
I really wonder what this will solve in your application.
IMO nothing except that you do not want to split the stuff into sub configs in `app/config` (as we already have for security) but to link it to the bundle... your initial problem about your application getting too complicated should be solved by simply creating the following, shouldn't it?
```
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: framework.yml }
    - { resource: doctrine_dbal.yml }
    - { resource: twig.yml }
# … and more if necessary
```

**Comment by aschempp** [comment]
It is not about my complexity at all, its about updating a default Contao app. As @Toflar said, we should probably talk about it.

**Comment by discordier** [comment]
Guess so. :)

**Comment by leofeyer** [comment]
As discussed in Munich in February, 2016, we want to keep the application related configuration in `app/config`. If one of our bundles needs to pre-configure a third-party bundle, we want to use compiler paths to accomplish it.

**Comment by aschempp** [comment]
I agree. Unfortunately, compiler passes won't really work as we discussed, but that's a topic for another call ;-)
