### ISSUE TITLE
Switch to Guard Authentication

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#429]
A simplified authentication mechanism was introduced in Symfony 2.8:
https://github.com/symfony/symfony/pull/14673

I've discussed the topic with @weaverryan at SymfonyCon. We agreed there are no new features when switching from our pre-authentication listener to Guard, it would make replacing the Contao authentication mechanism (described in https://github.com/contao/core-bundle/issues/122) much easier in the future.

Obviously means we would only be compatible with Symfony 2.8. If @contao/developers agree on Symfony 2.8 for Contao 4.2 I can work out a pull request.

**Comment by Toflar** [comment]
Of course that's okay! Thank you BC promise :)

**Comment by leofeyer** [comment]
@aschempp Will you prepare a PR?

**Comment by leofeyer** [comment]
I will have to update the develop branch to Symfony 2.8 beforehand I guess :smile:

**Comment by aschempp** [comment]
Not really, thats just a requirement update. As we discussed yesterday, we should start with actually using Security first (voters etc.). Changing to Guard is a pretty simple step and won’t affect anything.

**Comment by leofeyer** [comment]
> Of course that's okay! Thank you BC promise :)

Haha, how dramatic is this :D

**Comment by Toflar** [comment]
:sunglasses:

**Comment by leofeyer** [comment]
As discussed in Haag, we also want to regenerate the session ID upon login.

**Comment by leofeyer** [comment]
What about the `onAuthenticationSuccess()` and `onAuthenticationFailure()` methods? We would need to return a redirect response, but how would we know where to redirect to?

**Comment by leofeyer** [comment]
As discussed in Mumble on April 20th, Guard does not make much sense for Contao.
