### ISSUE TITLE
'Disable IP check' cannot be set in Backend

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/core-bundle#436]
You cannot set the value for **disableIpCheck** in the backend via `Settings -> Disable IP check` (Einstellungen -> IP-Prüfung deaktivieren)

This gets overwritten by `contao.security.disable_ip_check` in [Config::loadParameters ](https://github.com/contao/core-bundle/blob/b59a083a05b01ff95b7246ce6a734bf62a67919e/src/Resources/contao/library/Contao/Config.php#L506) if I'm correct.

To reproduce: Just go to the settings menu and try to *check* the box and save it. Always returns to unset, although it's set to true in the localconfig.php

If this was done by intention then this checkbox should be removed completely (from the backend). 

----
I found this bug by implementing a bridge authentication service (phpbb <-> contao) and stumbled over a missing `X-Forwarded-For` header implementation in the user login / generateSession methods. But have to dig some more into it and will open a separate ticket if needed.

**Comment by leofeyer** [comment]
> If this was done by intention then this checkbox should be removed completely

Correct.

**Comment by leofeyer** [comment]
Fixed in 5276884282c80ca793e455ba423d3d63b7292de9.
