### ISSUE TITLE
Do not store non-configuration values into `localconfig.php`

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#442]
Configuration values must be static. If these files get updated by a cronjob or whatever, it makes deployment a pain because you want to be able to track the changes of configuration files in a VCS like git.

The current version of the Contao bundle stores e.g. the latest version of Contao that is available into the `localconfig.php` (the key is named `latestVersion`). But this information is not static so it either belongs to the database or a temporary file. 
A quick search resulted in another example where we make that mistake: `installCount`.

These two non-configuration parameters must be removed from the `localconfig.php`. In the case of `latestVersion` I'd even vote to get rid of it completely but I'm open for alternative proposals.

**Comment by discordier** [comment]
I am totally with you on this one. The configuration must be and remain static.
I seem to remember that we had this discussion during Ahrweiler-2nd-edition and came to the conclusion that we ultimately want to get rid of localconfig at all and only want parameters in the future.

However on the topic of the `latestVersion`, I do not see any benefit of this at all aside from confused customers which get the warning in the backend that their Version is not the most recent one. This bears especially the problem that NO checks are done if upgrading will break everything (with ER2) or is impossible (with composer). It simply warns that the core is not up to date and therefore is misleading at best and issuing false assumptions at worst.
Therefore I also vote for getting rid of it completely.

**Comment by leofeyer** [comment]
We can easily store `latestVersion` in the database. But `installCount` will be difficult, because we cannot safely assume that there is a database connection in the install tool.

**Comment by Toflar** [comment]
Imho both could be stored into the tmp folder instead of the localconfig.php. If the tmp folder gets purged, install count would be reset and the new version available message would temporarily be gone until the next cron runs. Both not critical? I don't see why we should pollute the DB.

**Comment by qzminski** [comment]
In my opinion informations like ```installCount``` or ```latestVersion``` or any other of this kind should not be stored in the database but in a separate file that is accessible independently from the system status (e.g. whether it is installed or not; whether it has db connection or not). That control file would not be maintained in the repository and would be for internal app's usage only.

The ```localconfig.php``` file should be in the end moved to the ```parameters.yml```.

I am also for dropping the ```latestVersion``` or at least not displaying it in the backend (perhaps a sf2 debug bar would be more appropriate place?).

**Comment by aschempp** [comment]
Yeah. But we should use a generic Doctrine cache service instead of a custom implementation ;-)

**Comment by leofeyer** [comment]
Changed in a9cc8e924fda5b8328282cf70114830ba54b4ae4 and contao/installation-bundle@d820c54b9aed9cf16d0e2fdb56b369b4895d312d.

**Comment by aschempp** [comment]
Can we please start using the components? As I said, we should use a Doctrine cache driver for everything. This would for example allow people to easily store that information in memcached or Redis!

**Comment by leofeyer** [comment]
As I have said above, there is not necessarily a database connection in the install tool.

**Comment by aschempp** [comment]
Doctrine cache is not related to the database!

**Comment by leofeyer** [comment]
Changed in aa5449a1becabc3bf7eb545edb4c4ed8e26b9625.
