### ISSUE TITLE
Use instanceof instead of !== null

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#451]
<a href="https://github.com/aschempp"><img src="https://avatars.githubusercontent.com/u/1073273?v=3" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/core/pull/8238#discussion_r54377445) by @aschempp
February 29th, 2016, 07:57 GMT

A general idea. If we would write `($objTarget = $this->objModel->getRelated('jumpTo')) instanceof \PageModel`, it would be more safe, we would not need the `@var` hint and work exactly the same.

**Comment by DanielSchwiperich** [comment]
Not directly related: What is the reason contao uses like in @aschempp example global namespace so often?
Afaik this is considered bad practice

**Comment by aschempp** [comment]
Global namespaces were introduced in Contao 3 but are deprecated since Contao 4. They ARE bad practice, but we need to support them in the core for BC reasons.

**Comment by leofeyer** [comment]
We are no longer supporting them in Contao 4, though (see [DEPRECATED.md](https://github.com/contao/core-bundle/blob/master/DEPRECATED.md#contao-class-loader)).

**Comment by DanielSchwiperich** [comment]
But they are still used a lot and I see no reason why (can't see how it would affect BC)

Just 2 quick examples: 
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Ajax.php
`class Ajax extends \Backend`
`$objSessionBag = \System::getContainer()->get('session')->getBag('contao_backend');`
(losts more in this file)

https://github.com/contao/core-bundle/blob/develop/src/Resources/contao/classes/FrontendTemplate.php
`class FrontendTemplate extends \Template`
`if ($blnCheckRequest && \Input::hasUnusedGet())`

I saw it also in a recent commit:
https://github.com/contao/core-bundle/commit/a4656c5ac35810e4bc0a61346a08003fc58f7980
But you did fix this in a later commit. 

So is it just legacy code which will be refactored as time goes by? 
Would you accept external PRs for it? I could let our trainee work in it. I think it would be a good job for someone to learn the core and also doing something productive (we would pre check before the PR for sure)

**Comment by aschempp** [comment]
As far as I remember, we did not want to rewrite all of the legacy code (yet) because it would create a lot of noise in the commit messages (e.g. `git blame`). But I like the idea of having a trainee get something done :-)

It's also a bit complicated because in the legacy code we're still using the "old" style (not PSR-2), but in the new code we do (for the same noise reason).

**Comment by leofeyer** [comment]
Unexpectedly enough, this does not work in my PhpStorm. @aschempp Did you test it? Which plugins do you have installed?

**Comment by aschempp** [comment]
I have not actively tested this. Maybe it does not work because the assignment is in the if-statement. We should figure that out, but it would still be *correct* because otherwise we don't know we can actually call that method…

**Comment by leofeyer** [comment]
True.

**Comment by fritzmg** [comment]
> But they are still used a lot and I see no reason why (can't see how it would affect BC)

It was there to be able to replace core classes, was it not? Many extensions rely on that. Or is there another way now?

**Comment by leofeyer** [comment]
> It was there to be able to replace core classes

This is no longer supported in Contao 4. See [DEPRECATED.md](https://github.com/contao/core-bundle/blob/master/DEPRECATED.md#contao-class-loader).

**Comment by fritzmg** [comment]
I see, but are there new ways to achieve anything like that? Otherwise many extensions would not be possible anymore or they would have to duplicate a lot of core code, to restore the functionality again without extending and replacing a core class.

**Comment by aschempp** [comment]
Extensions are **never** supposed to replace a core class using the class loader. This problem can only be fixed with Dependency Injection in Contao 4, but we're still a long way from that…

**Comment by fritzmg** [comment]
> Extensions are never supposed to replace a core class using the class loader.

Nevertheless, that is what a lot of extensions are doing, otherwise it wouldn't be possible for them to introduce certain functionalities, at least not without providing a lot of duplicate core code themselves. Take the news_categories Extension for instance, which replaces the NewsModel so that the regular ModuleNewsList class can be used. Without replacing the NewsModel class, the extension would need to duplicate and rewrite the ModuleNewsList, so that it uses the FooNewsModel.

> This problem can only be fixed with Dependency Injection in Contao 4, but we're still a long way from that…

I see :)

**Comment by aschempp** [comment]
you might be wrong. People are replacing classes in the `$GLOBALS` array, but not using the `ClassLoader`.

**Comment by fritzmg** [comment]
I mean things like that: https://github.com/codefog/contao-news_categories/blob/master/config/autoload.php#L35

This replaces `\Contao\NewsModel` since the class name is mapped to the root namespace.

**Comment by qzminski** [comment]
The ```news_categories``` indeed overrides the core classes in ```ClassLoader``` to avoid the original code duplication. However, I expect Contao 4 modules to be reworked into a lot more flexible solutions so class overriding in autoloader (which is obviously a bad practice) will no longer be necessary. Afterwards the new version of the ```news_categories``` will be released.

**Comment by leofeyer** [comment]
I have created a PR in #467.
