### ISSUE TITLE
Add a flag to disable the FE preview in a model

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#452]
<a href="https://github.com/Toflar"><img src="https://avatars.githubusercontent.com/u/481937?v=3" align="left" width="42" height="42"></img></a> [Comment](https://github.com/contao/core/pull/8238#commitcomment-16389314) by @Toflar
February 29th, 2016, 13:52 GMT

You could have added a flag to $arrOptions to disable the fePreview check? This would greatly reduce the need of code duplication?

```php
if (!isset($arrOptions['disableFePreviewCheck']) && !BE_USER_LOGGED_IN)
```

**Comment by leofeyer** [comment]
Implemented in 9bca55438dbbe8175119c29362a24a7b371eec99.

**Comment by aschempp** [comment]
how about we call the parameter `BE_USER_LOGGED_IN`? then we could simply pass the actual variable and the model would no longer need the constant.

**Comment by aschempp** [comment]
it would need to be passed everywhere though, thats probably not what we want…

**Comment by qzminski** [comment]
It's not correct to have ```BE_USER_LOGGED_IN``` check in the model so one day this must be changed anyway.
