### ISSUE TITLE
feature: generateAbsoluteUrl, generateRelativeUrl

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#458]
Currently, the function
```php
\Controller::generateFrontendUrl(…)
```
returns either an absolute or a relative URL, depending on certain conditions. In Contao `>=3.3.0,<5-dev` the function always returns a relative URL if the last parameter is set to `false` and it returns either an absolute URL or a relative URL if the last parameter is set to `true`, depending on whether the target page has a DNS entry and whether the domain, under which the function was executed is or is not equal to the domain of the target page.

However, some extensions, and even some parts of the Contao Core _always_ need an absolute URL (i.e. an URL including the scheme and host) - e.g. for building links that are used outside of the Contao Frontend, for example in Newsletters, Sitemaps, RSS Feeds and the like.

Thus it would be helpful to have a framework function that already takes care of always adding the correct scheme and host to the URL. So if the target page has `useSSL` defined, the `https://` scheme is added (otherwise only `http://`), if the target page has no DNS, the current domain is added, if the target page has a DNS, that domain is added.
```php
\Controller::generateAbsoluteUrl(…)
```

Vice versa, some users may find it helpful to have a function where they can rely on that it is always returning a relative URL without scheme and host, so that they can more easily apply their own logic to the URL regarding scheme and host, if desired.
```php
\Controller::generateRelativeUrl(…)
```

**Comment by aschempp** [comment]
Prettty sure the Router in Contao 4 already supports that…

**Comment by leofeyer** [comment]
I don't think the Symfony router can solve it, but we should give it a try.

**Comment by fritzmg** [comment]
There are twig functions, that give you either the absolute URL (`{{ url(…) }}`) or a relative URL (`{{ path(…) }}`) for a route. I don't know of any equivalent in PHP though.

**Comment by leofeyer** [comment]
The Symfony router has a flag: https://github.com/symfony/routing/blob/master/Generator/UrlGenerator.php#L127

**Comment by fritzmg** [comment]
> Prettty sure the Router in Contao 4 already supports that…

As it turns out, yes, but do you want to have to use this code
```php
$objPage = …;
$objRouter = \System::getContainer()->get('router');
$arrParams = [];
$strRoute = 'contao_frontend';

if ($objPage->alias == 'index' && $strParams == '')
{
	$strRoute = 'contao_index';
}
else
{
	$arrParams['alias'] = ($objPage->alias ?: $objPage->id) . $strParams;
}

if ($strForceLang != '')
{
	$arrParams['_locale'] = $strForceLang;
}
elseif (isset($objPage->language) && $objPage->type == 'root')
{
	$arrParams['_locale'] = $objPage->language;
}
elseif (TL_MODE == 'FE')
{
	/** @var PageModel $objPage */
	global $objPage;

	$arrParams['_locale'] = $objPage->rootLanguage;
}

$strUrl = $objRouter->generate($strRoute, $arrParams, UrlGenerator::ABSOLUTE_URL);
$strUrl = substr($strUrl, strlen(\Environment::get('path')) + 1);

if (strpos($strParams, '%') !== false)
{
	$arrMatches = array();
	preg_match_all('/%([sducoxXbgGeEfF])/', $strParams, $arrMatches);

	foreach (array_unique($arrMatches[1]) as $v)
	{
		$strUrl = str_replace('%25' . $v, '%' . $v, $strUrl);
	}
}
```
every time you want to generate an absolute URL to a Contao page?

**Comment by leofeyer** [comment]
I had to add a `getAbsoluteUrl()` method to the page model class in contao/core@354b3a4dfe7d3a341df7767f37b13fc299bad52b. I don't think a `getRelativeUrl()` makes sense though, because it would potentially generate invalid URLs by stripping the hostname, don't you think?

**Comment by fritzmg** [comment]
> I don't think a getRelativeUrl() makes sense though, because it would potentially generate invalid URLs by stripping the hostname, don't you think?

Well, it was just a suggestion, some users might have some use for it, if they want to handle the domain part of the URL themselves for whatever reason.

**Comment by leofeyer** [comment]
Then they will have to add their own method, because I prefer not to add a method which potentially generates invalid stuff.
