### ISSUE TITLE
Cache management in the back end

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#459]
@contao/developers Right now we can rebuild the internal cache in the back end but not the Symfony cache. I wonder what is our goal here:

1. Do we need to rebuild both the internal cache and the Symfony cache **separately** in the back end?
2. Should we only offer to rebuild the Symfony cache, which will rebuild the internal cache automatically?
3. Should we not manage the internal cache and the Symfony cache in the back end at all?

If the package manager will be able to purge the caches, I'd tend towards 3.

**Comment by Toflar** [comment]
Managing caches is part of the application management. It's not a content management task and thus does not belong to a CMS back end.

**Comment by DanielSchwiperich** [comment]
This would mean things like *internal cache*, *create symlinks*, *system log* do also not belong there.

If a user selects all the caches on the maintenance site he expects that all available caches get cleared, but they are not. 

So i would vote for splitting the list into to two sections "content" and "technical/advanced" and maybe hide the tech panel by default. 

No contao/dev here so just an opinion :smile_cat: 
I can remove the comment if you wish

**Comment by Toflar** [comment]
> No contao/dev here so just an opinion

This is a public open source project. It is as good as the opinions and contributions of everyone so please, always feel free to comment! :)

> This would mean things like internal cache, create symlinks, system log do also not belong there.

Yes, they don't belong there either :)

**Comment by aschempp** [comment]
I agree with @toflar but it's difficult atm as the internal cache cannot be bult otherwise (and the container cache will be built automatically).

**Comment by leofeyer** [comment]
That could be solved by building the internal cache every time the container cache is built. And not building it in the dev environment.

**Comment by aschempp** [comment]
I don’t think so. The internal cache is optional (see https://github.com/contao/core-bundle/blob/master/src/Cache/ContaoCacheWarmer.php#L114)

**Comment by leofeyer** [comment]
I know. But it does not have to remain optional, because it does not make sense to run a productional website without it. It is only optional, because there was no dev entry point in Contao 3.

**Comment by aschempp** [comment]
A cache is optional if the system can run without it (see http://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer)

> The isOptional method should return true if it's possible to use the application without calling this cache warmer.

**Comment by leofeyer** [comment]
Just because it **can** run without it, it does not automatically **have to**.

**Comment by discordier** [comment]
Vote: 3 No cache manipulation in the Backend at all.

**Comment by leofeyer** [comment]
As discussed on Mumble on April 21st, the internal cache should be removed from the maintenance module. Also, the internal cache warning should be removed.

**Comment by aschempp** [comment]
Would also mean the checkbox to bypass internal cache will be removed, right?

**Comment by leofeyer** [comment]
Yes.

**Comment by leofeyer** [comment]
Removed as discussed in 825ffde5dba106832ed1b2230ce0f9f855733599.
