### ISSUE TITLE
alias with app_dev.php not working

### ISSUE THREAD

**Issue by gebi84** [contao/core-bundle#465]
in contao 4.1.2 under windows with php 5.6 fcgi

if i call /home in the browser the variable $strRequest is "app_dev.php/home" but should be only "home". So no Page is matching the route.

i inserted this quick fix for me:
\vendor\contao\core-bundle\src\Resources\contao\classes\Frontend.php:71
`$strRequest = str_replace('app_dev.php/', '', $strRequest);`

**Comment by fritzmg** [comment]
duplicate of #426
