### ISSUE TITLE
4.2.0.-beta1 possible bug: Config class redlecaration 

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/core-bundle#476]
Wanted to test #426 in a fresh install and used the new beta release. However when calling the install.php I get the following error: 
```
Fatal error: Cannot redeclare class Contao\Config in /var/www/share/contao-426.test.local/htdocs/standard-edition-4.2.0-beta1/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php on line 22
```

Does not happen with 4.1.3. 
Did not dig into it. Maybe s1 can confirm (or not)?

**Comment by leofeyer** [comment]
How did you install it? `composer create-project`?

**Comment by DanielSchwiperich** [comment]
No just downloaded the beta release and then did a composer install. 
Should have mentioned that I used the standard-edition, but posted the error here since it was caused in a core bundle file. 

https://github.com/contao/standard-edition/releases/tag/4.2.0-beta1
