### ISSUE TITLE
Edit image with special characters in file manager is missing urldecode

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#478]
Steps to reproduce:

1. Create an image that is larger than 699x524 with the file name *image(1).png*
2. Upload it to the Contao file manager
3. Edit the file in the file manager

This produces the error `Warning: file_get_contents(.../image%281%29-20549903.png): failed to open stream: No such file or directory` and the image doesn’t get shown.

Could be fixed by adding `rawurldecode()` to [src/Resources/contao/classes/DataContainer.php:514](https://github.com/contao/core-bundle/blob/cf7916177502b4fdfc48ea0a8d2b3ecc19f87117/src/Resources/contao/classes/DataContainer.php#L514):

```php
$image = rawurldecode(\Image::get($objFile->path, 699, 524, 'box'));
```

**Comment by leofeyer** [comment]
Fixed in 5e97cf99df7a0c53456f1be18524cd55d501992b.
