### ISSUE TITLE
Ability to restrict the access to the maintenance features for users.

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#482]
In a user group, an administrator can restrict the access to one or more of the following features available in the maintenance view:

* Maintenance mode
* Rebuild the search index
* Purge data

For example, a user can rebuild the search index but will not have access to the maintenance mode and purge data features.

![capture d ecran 2016-05-08 a 20 14 21](https://cloud.githubusercontent.com/assets/814476/15099583/821695ee-1559-11e6-9055-a13e7252442d.png)

**Comment by aschempp** [comment]
I assume this is a feature request? Should automatically apply to all maintenance modules imho.

**Comment by leofeyer** [comment]
Does not make too much sense IMHO (not to mention the effort).

After the search index is rebuilt, it e.g. makes sense to purge the HTML cache. And when the maintenance mode is disabled, it might make sense to recreate the XML files. Therefore I think a user should either be allowed to maintain the installation or not.

**Comment by aschempp** [comment]
I think allowing the user to rebuild the search index but not delete internal cache is a very common scenario.

**Comment by leofeyer** [comment]
And how do users check whether the search index has been built correctly if they cannot access the "purge data" module and look at the number of table entries?

**Comment by Toflar** [comment]
There's no point in having them separately anyway. There's no use case at all for purging the index but not rebuilding it. Anyway, not sure we should invest too much time here as this is a maintenance task and should be done on command line when deploying (or using the package manager).

**Comment by lionel-m** [comment]
> After the search index is rebuilt, it e.g. makes sense to purge the HTML cache. And when the maintenance mode is disabled, it might make sense to recreate the XML files. Therefore I think a user should either be allowed to maintain the installation or not.

I had not thought about this scenario. We can close this ticket for me...
