### ISSUE TITLE
Modul Caching konfigurierbar machen

### ISSUE THREAD

**Issue by christianbarkowsky** [contao/core-bundle#483]
Ich wünsche mir die Möglichkeit, bestimmt Module vom Caching ausklammern zu können.

z.B in der autload.ini `caching=false;`

**Comment by aschempp** [comment]
Mit caching meinst du den Internal Cache? Kannst du erklären warum?

**Comment by fritzmg** [comment]
Vielleicht meint er den Seitencache, damit man bestimmte Bereiche (Module) immer dynamisch machen kann. Momentan geht das nur über Insert Tags.

@christianbarkowsky für den Fall, dass du das noch nicht weißt: wenn du ein Modul in deiner Seite immer dynamisch generieren lassen willst, selbst wenn du den Seitencache benutzt, dann kannst du das jeweilige Modul anstatt direkt im Seitenlayout oder über ein Include Inhaltselement mit folgendem Insert Tag einfügen:
```
{{insert_module::*|uncached}}
```
`|uncached` funktioniert für alle (Core?) Insert Tags.

**Comment by christianbarkowsky** [comment]
Ich meine den Internal Cache.

**Comment by fritzmg** [comment]
During development you should use the development environment, i.e. `/app_dev.php`.

**Comment by christianbarkowsky** [comment]
But what about encrypted modules?

**Comment by fritzmg** [comment]
I don't know what those are :wink: (though I would appreciate someone explaining me)

**Comment by DanielSchwiperich** [comment]
Müsste es nicht reichen alles unterhalb app/cache einmal alles zu leeren und dann NICHT den cache aufbauen zu lassen im backend. Da bleibt dann das Warning stehen, bez. warmup, aber interessiert ja nicht. 
Dann werden Module komplett aus dem vendor geladen. Bin ich mir zumindest relativ sicher :smile:

**Comment by fritzmg** [comment]
Sollte das nicht sowieso über das Dev Environment so sein? Welche andere Möglichkeit hätte man in Contao 4 sonst ohne internen cache zu developen?

**Comment by aschempp** [comment]
Interessante Frage. Die Caches von Dev und Prod sind unterschiedlich, aber vermutlich würde der interne Cache im Dev auch aufgebaut. Das sollten wir eigentlich verhindern… @contao/developers ?

**Comment by leofeyer** [comment]
Der interne Cache ist optional, daher wird er gar nicht durch bloßes Aufrufen der Applikation aufgebaut.

**Comment by DanielSchwiperich** [comment]
Der interne Cache wird nur aufgebaut, wenn man es aktiv bestätigt / macht.

Entweder via console `app/console cache:warmup -e prod` oder im Backend. 
Wenn man im Backend `/contao` angemeldet ist, dann wird `prod` aufgebaut. Wenn man im Backend via `app_dev.php/contao/` drin ist wird für dev aufgebaut (Nur wenn man den Button klickt).

Wie schon geschrieben, einfach den cache leeren (hart, oder via Backend -> Maintenance) und dann nicht wieder aufbauen. 
Dann werden auch keine dcas etc gecached.

**Comment by aschempp** [comment]
Korrekt. Ich wäre aber auch dafür das bei `debug=true` der Interne Cache auch bei `cache:clear` / `cache:warmup` nicht gebaut wird. Weis aber nicht wie sich Symfony da sonst verhält.

PS: in Contao 4.2 entfällt der Hinweis und das Cache-bauen im Backend afair.
