### ISSUE TITLE
UrlGenerator and auto_item disabled

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#489]
Just thinking about it, can we still disable `auto_items` in Contao 4? And if so, I think the UrlGenerator would ignore that?

**Comment by leofeyer** [comment]
Can we disable `auto_item` in Contao 3???

**Comment by aschempp** [comment]
Looks like it… https://github.com/contao/core/blob/master/system/modules/core/dca/tl_settings.php#L181

**Comment by leofeyer** [comment]
We have two options:

1. Remove the option; no idea though if people are using it or if there are reasons to disable auto items.
2. Move the setting to the Symfony container and handle it in the UrlGenerator class.

@contao/developers What's your favorite solution?

**Comment by Toflar** [comment]
> Remove the option; no idea though if people are using it or if there are reasons to disable auto items.

That's not an option because of BC, I guess.

> Move the setting to the Symfony container and handle it in the UrlGenerator class.

Obviously, yes. All the other `tl_settings` options will eventually move to the Container anyway, too :)

**Comment by aschempp** [comment]
I don't see the problem. The `UrlGenerator` needs the framework and `$GLOBALS['TL_AUTO_ITEM']` anyway, so we can simply use the current setting.

**Comment by leofeyer** [comment]
This is not quite correct. If the framework was really required, why is it not initialized somewhere in the class? The code only checks `$GLOBALS['TL_AUTO_ITEM']` and if it is not set, it still works.

Therefore I'm with @Toflar on moving the setting into the container.

**Comment by aschempp** [comment]
hmm, but that would completly break `$GLOBALS['TL_AUTO_ITEM']` ?

**Comment by leofeyer** [comment]
Why?

**Comment by aschempp** [comment]
because the global array would only be available if the framework is booted, so the UrlGenerator behaves differently depending on unknown conditions. As I see it, the framework is always available when using the `UrlGenerator` (meaning it should be), because how can you generate a Contao page frontend url if you're not within the framework (e.g. you can't use page models…)

**Comment by leofeyer** [comment]
Still, if the framework needs to be booted, we should do this in the class, shouldn't we?

**Comment by aschempp** [comment]
Definitely

**Comment by leofeyer** [comment]
See #515.
