### ISSUE TITLE
[4.2.0-RC1] Tree view expand icons missing

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#492]
The expand icons are missing in the tree views. It's only possible to expand the tree by using "Toggle all".
However, the expand `<a>` tags are there. Just the icon isn't present.

It seems that the filename is wrong. The header_toggle css class e.g. is referencing to folPlus.svg while the file in the file system is all lowercase.

**Comment by leofeyer** [comment]
I have checked the site structure, the file manager and the article module; the expand icon was there. How do I reproduce this?

**Comment by ben-eSM** [comment]
The issue is present from the start if you do a clean install. The svg files are all lowercase while the css class and probably the DC are referring to `folPlus.svg`. Depending on your webserver configuration, it might look for similar files or just ignore the case.
In my case I have no spelling correction enabled which results in 404 errors when contao requests those files.

**Comment by leofeyer** [comment]
Fixed in d7dbbd3dcb2af1432dc0ed183f37c99e3be5a0e7.
