### ISSUE TITLE
Show the Contao version/build number somewhere in the back end

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#493]
Actually, I miss the Contao version in the back end. The version/build number was previously shown the the back end header topbar.

How I am supposed to know the Contao version/build number without having to look into some config file?

[Contao 4.2.0-RC1]

**Comment by discordier** [comment]
The big problem here is, there is no Contao version. Contao is multiple bundles and an application glueing them together.
You get the Version of the core bundle in the debug bar however.

**Comment by xchs** [comment]
Thanks for the hint. Wouldn't it make sense then to show the "core-bundle" version number directly in the back end header (or for all I care somewhere in the settings or in the maintenance back end module)?

**Comment by leofeyer** [comment]
It is shown in the debug bar, and that is the only place it should be shown IMHO.

**Comment by xchs** [comment]
I disagree.

To run the back end in debug mode we have either:
* to create an accesskey from a (hashed) username/password combo or
* to transfer the complete installation to localhost or
* to "patch" the `app_dev.php` script

Quite cumbersome only to get the release version, I think. Isn't it?

**Comment by leofeyer** [comment]
This is the default behavior of any Symfony app as well, so I don't really see the problem here.

@contao/developers /cc

**Comment by leofeyer** [comment]
We could, of course, but what for?

**Comment by xchs** [comment]
> but what for?

Isn't that useful information?

How we are supposed to know the release version if e.g. we are new to a client's back end? In the past, I used to use the [official Contao announcements on contao.org](https://contao.org/en/news.html) to check the release information of a certain Contao version and whether it is relevant for the jobs which are planned. On contao.org you announce new iterations also specifiying the release version (e.g. "Contao 4.x.x is available"). Looking at the [core bundle change log](https://contao.org/en/changelog/versions/4.1.html), how should I decide in the future if that kind of (perhaps useful) information relates to the installation in which I am currently working on? I would have to run the installation in debug mode, only to get the core bundle version number.

With Contao 4 I'm a bit lost regarding this matter. That's my concern.

**Comment by leofeyer** [comment]
> How we are supposed to know the release version if e.g. we are new to a client's back end?

As @discordier said, the application is now made of multiple bundles and components, each having its own version, therefore you cannot tell what is installed from the back end. You will have to check the `composer.lock` file to be sure.

Once the Contao manager is released, you can also check the package versions there.

**Comment by xchs** [comment]
> the application is now made of multiple bundles and components, each having its own version

Yes, I know. However, it is AFAIK only the **core bundle** version that actually counts when it comes to tell someone which Contao "version" is currently installed. You are using also only the **core bundle** version when you publish and announce a new Contao release, don't you?

> Once the Contao manager is released, you can also check the package versions there.

Ah okay, thanks. I can probably live with that if the package versions are there as well.

**Comment by aschempp** [comment]
More important to me seems the fact that 90% of the users will use a "fixed" Contao release, which always will have a known version number. Regular Contao 4 users are not composer-updating individual bundles. It was already the case that some components like JS plugins have different versions, but they don't matter to the regular user. 

Also, it was sufficient to show the minor version previously, and we can very well assume that you have `news-bundle` 4.2 if `core-bundle` is 4.2.

**Comment by Toflar** [comment]
I think it's actually dangerous to show the core-bundle version in the back end. Contao is no longer a standalone application. It also depends on Symfony components and while e.g. you want to check if your Contao core bundle is up to date (for security reasons) it might very well be the case but in the meantime, Symfony has published security releases and you should do a composer update even though the Contao core bundle that is installed is the latest version.

**Comment by ausi** [comment]
I think checking the version and available updates is part of the “maintenance tasks” and can be done via command line (`composer show -l`) or in the future with the Contao Manager.

**Comment by DanielSchwiperich** [comment]
The backend is part of the core bundle so it should show the version number of the core bundle imho. 
For all installed bundles and deps it's fine to use the Contao Manager once released.

**Comment by aschempp** [comment]
Maybe @1up's security check for Contao can solve this issue?

**Comment by bytehead** [comment]
ATM you won't see the version number for any installed dependency. Except there is a security issue in some package and its version.

**Comment by aschempp** [comment]
That is correct, but it's a *problem* we can't solve. The version released on contao.org is a collection of Composer packages. If you look at the 3.5.21 release, the only changes were in the SwiftMailer package. Contao itself was not actually changed.

There are only two version information we have:
 1. Each Composer package has a version number, so does `contao/core-bundle`. But again, if a bug was found in news, `contao/news-bundle` will get a new version, but `contao/core-bundle` will not.
 2. The distribution you once installed had a version number. That *could be* `contao/standard-edition`, but it can be any other (probably `contao/managed-edition` in the future).

Using the `core-bundle` version (1.) does not really tell you what **exactly** is installed. And the version of your distribution (2.) is only valid as long as you **never** perform any update. Because from that moment, **your distribution** will no longer be the same as it was when you installed it, and it does most likely not match anything published by Contao.

The only thing we can safely say is which **minor version** of Contao you have. Because you will not have `core-bundle` 4.3 and `news-bundle` 4.4.

And honestly, the patch version (see www.semver.org) should not matter, you should always have the latest version. So maybe the only relevant information we should tell is **when the last update was performed**?

**Comment by fritzmg** [comment]
> The version released on contao.org is a collection of Composer packages.

And it does have a version number. So how is this particular version number determined and documented?

**Comment by aschempp** [comment]
> So how is this particular version number determined and documented?

The number is simply the next patch version (if same minor version of Contao). It is attached to the distribution, which is either `contao/standard-edition` or `contao/managed-edition` (in the future). But again, the distribution version is only applicable until you update. Technically speaking, as long as your `composer.lock` file is not modified.

**Comment by leofeyer** [comment]
>> The version released on contao.org is a collection of Composer packages.
>
>And it does have a version number.

Yes, but that is only the version number of the standard edition. And if you have added Contao to your existing Symfony application (or if you are using the managed edition), you might have a different version number.

The only reliable solution is to change the label from "Contao version" to "Contao core bundle version".

**Comment by aschempp** [comment]
When we show the minor version only, I think "Contao version 4.3" is appropriate and much less confusing.

**Comment by xchs** [comment]
Naja, es wäre halt schon fein, wenn man unmittelbar irgendwo sehen könnte, ob die gegenständliche Contao-Installation halbwegs aktuell ist oder ob es sich um eine veraltete Installation handelt. Wenn z. B. ein Kunde anruft und irgendetwas zu seiner Contao-Installation wissen möchte oder weil es eventuell ein Problem o. dgl. gibt, dann gibt es zukünftig zwei Situationen:
1. Für Installationen mit Contao < 4 kann man nachfragen, welche Version denn eigentlich installiert ist, da diese unmittelbar im Backend-Header ersichtlich ist. So kann man relativ schnell und einfach abschätzen, ob die betreffende Installation (halbwegs) aktuell ist oder ob das Problem möglicherweise mit einer veralteten Installation zusammenhängt
2. Für Installationen mit Contao >= 4 wird mir der Kunde am Telefon nicht mehr unmittelbar die Version seiner Contao-Installation nennen können, weil es _DIE_ Version als solches ja nicht mehr gibt. Stattdessen müsste er mir k. A. 10-15 Versionsnummern durchsagen, damit ich einigermaßen abschätzen kann, wie aktuell oder veraltet die betreffende Installation tatsächlich ist

Würde es nicht Sinn machen, wenigstens die Minor-Version (4.3, 4.4 usw.) anzuzeigen, sodass man sofort und unmittelbar sehen kann, ob es sich um eine veraltete, eine aktuelle oder eine LTS-Version handelt? Auch wenn dann seit dem Release die einzelnen Bundles zwischenzeitlich auf neuere Versionen upgedated wurden, so weiß man doch wenigstens, um welchen ungefähren Versionsstand es sich bei der betreffenden Installation handelt.

Für ein Betriebssystem, welches in der Regel ja auch aus unterschiedlichen Paketen und Modulen besteht, gibt es doch auch irgendeine Versionsnummer, welche die Systemgeneration beschreibt und folglich auch abgefragt oder angezeigt werden kann. Selbstverständlich können mit jedem (monatlichen) Update neue Patches oder neuere Versionen dieser Pakete installiert bzw. eingespielt werden. Das ändert aber nichts daran, dass es trotzdem eine Versionsnummer gibt, welches dieses System charakterisiert. So weiß man normalerweise sofort, ob der Anwender mit einem veralteten (z. B. Windows XP) oder mit einem aktuellen System (z. B. Windows 10) arbeitet.

**Comment by leofeyer** [comment]
> Würde es nicht Sinn machen, wenigstens die Minor-Version (4.3, 4.4 usw.) anzuzeigen

Die Minor-Version von was? Vom Core-Bundle? Von der Standard-Edition?

**Comment by xchs** [comment]
> Die Minor-Version von was?

Die selbe Versionsnummer, die auf contao.org für das Release herangezogen wird. Also wahrscheinlich `contao/standard-edition` oder `contao/managed-edition`.

**Comment by aschempp** [comment]
Nur core-bundle ist möglich und aus meiner Sicht sinnvoll.

**Comment by leofeyer** [comment]
> Die selbe Versionsnummer, die auf contao.org für das Release herangezogen wird. Also wahrscheinlich `contao/standard-edition` oder `contao/managed-edition`.

Und was ist, wenn keine der beiden Editionen verwendet wurde? Man kann ja jede beliebige Symfony-Edition als Basis nehmen.

> Nur core-bundle ist möglich und aus meiner Sicht sinnvoll.

So sieht es aus. Siehe auch meinen [Kommentar](https://github.com/contao/core-bundle/issues/493#issuecomment-273592675) oben.

**Comment by aschempp** [comment]
> > Die selbe Versionsnummer, die auf contao.org für das Release herangezogen wird. Also wahrscheinlich contao/standard-edition oder contao/managed-edition.

> Und was ist, wenn keine der beiden Editionen verwendet wurde? Man kann ja jede beliebige Symfony-Edition als Basis nehmen.

Die Frage/Diskussion ist "sinnlos", wir kennen die Version der Distribution nicht.

**Comment by fritzmg** [comment]
Another issue we just discovered in the forum: whenever a new Contao version gets released, there will be a news entry on contao.org, e.g.: https://contao.org/de/news/contao_4-3-3.html

It says "Contao 4.3.3 is available" - yet when you click on the link [Contao change log](https://contao.org/de/changelog/versions/4.3.html) to see what has been changed in the new version, there won't be a version `4.3.3` since it only shows the changelog of the `core-bundle`.

**Comment by fritzmg** [comment]
> Die Frage/Diskussion ist "sinnlos", wir kennen die Version der Distribution nicht.

The "meta" version could be externally determined by looking at the versions of the currently installed bundles. The meta version would then be lowest common denominator. E.g. if the versions of all your installed contao bundles are the same as the `standard-edition` in `4.3.0` and one of your bundles is more up to date than the others, then the resulting meta version could be `4.3.0+`.

**Comment by tabcontao** [comment]
While I understand your arguments, the current "solution" is not a good one. We have a change log for Contao Core-Bundle 4.3.2 - and noone outside of the developer team or even new to Contao will know, that this is the Core-Bundle Version they get with Contao 4.3.3.

Why not take the version number of the core bundle? Sure, you will then still not know, what is exactly installed down to the last bit. But you don't know that either, when you read e.g. "Contao 3.5.24". Although this is not a symfony application, it can still consist of more than just the Contao core and you need to check the versions of all  of it's components to know exactly what you have, when looking at a specific installation. Nevertheless, the version number is still useful information. When I look at a Windows system, it's just the same. 

Maybe we actually need a procedure which generates a (more or less) usable version number out of the version numbers of the components which are under the control of  the Contao developers. If it is not possible to make this computed version number conforming to Contao versioning standard we should either change the standard or use the versions of a subset of components, for which this would be possible. Even if this means using just the core-bundle version. As for updated systems, they still have a core-bundle-version. And for the rest, you really need to look at the versions of the components.

**Comment by leofeyer** [comment]
> The meta version would then be lowest common denominator.

No way. First of all, the installation bundle currently has version 1.2.3, so the lowest common denominator would be 1.2. And even if we excluded the installation bundle, there is no guarantee that e.g. the listing bundle will get a version 4.3 if there are no changes. Then the lowest common denominator would be 4.2, even though there might be version 4.4 of the core bundle and version 4.5 of the calendar bundle.

**Comment by fritzmg** [comment]
> No way. First of all, the installation bundle currently has version 1.2.3, so the lowest common denominator would be 1.2.

No, you misunderstood me. Each individual `contao` bundle's version corresponds to either a specific meta version. E.g. if you have the `installation-bundle` installed in version `1.2.3`, this would correspond to a meta version of `4.3.3` (or possibly higher in the future). If all your other `contao` bundles correspond to the same version, then the meta version of your installation would be `4.3.3`.

**Comment by aschempp** [comment]
What's so hard to understand that there **is no version** for the distribution. If you want to, you can install any combination of 4.3 bundles of the core-bundles, they all work with each other. You can have core-bundle 4.3.2 and news-bundle 4.3.0 (even though there's a 4.3.1). Noone will stop you from doing that, and Contao cannot tell you a version number.

The only actual description would be something like `core:4.3.2/news:4.3.1/calendar:4.3.0/…`. And even that does not tell you if the Symfony components are up-to-date and do not pose a security risk (like SwiftMailer recently did).

I agree it is a problem that you install "Contao 4.3.3" and your dev console will show 4.3.2 because that's the core-bundle version. But the only solution to that is **not** show any version, or show **all** versions. And that won't be possible in a backend title…

**Comment by fritzmg** [comment]
@aschempp see my suggestion about the meta version.

**Comment by asaage** [comment]
> So maybe the only relevant information we should tell is __when the last update was performed__?

I think that's a good idea.

**Comment by fritzmg** [comment]
May be the following matrix makes it more clear what I mean:

![book1](https://cloud.githubusercontent.com/assets/4970961/22112111/1b90fefe-de62-11e6-8b31-bd1aee0b7e58.png)

If you only have the `core-bundle` in version `4.3.2` for example, and the `installation-bundle` in version `1.2.0` then the corresponding meta version (according to the `standard-edition`) would be `4.3.0+`.

**Comment by leofeyer** [comment]
There will be two ways to see the exact versions in the future:

 * Use `composer show` on the command line
 * Or use the Contao Manager in your web browser

This and 461a711931f2b23fd6a6188bb39dc10a562ac930 should solve the issue, shouldn't it?

**Comment by leofeyer** [comment]
We have discussed the issue another time at the core developer's meeting in Munich and we have agreed on keeping the version numbers of the default bundles and editions in sync. So version 4.3.5 of the standard edition (or managed edition) will include version 4.3.5 of the core bundle.

**Comment by xchs** [comment]
That makes sense!

**Comment by fbender** [comment]
I think the best solution for this particular issue is to show the minor version of the core bundle in the backend (where the Contao version was shown previously), which should cover all the sensible use cases (e.g. as described above by @xchs) for the displayed "Contao" version: The most important use case IMHO is that a BE user (e.g. customer) can easily tell the system admin (e.g. agency) which minor version an installation (i.e. the Contao-core-bundle) is on – which, for all intents and purposes, is the only essential info you can draw from that version anyway. As said multiple times, if you really need to do something, you have to go through all bundle versions anyway – but you (or the customer) shouldn't go through all the trouble (which may even require elevated privliges) just to get a first assessment of the situation at hand.

Ergo, what should be shown in the BE is simple and very limited (but still immensely useful in some situations). E.g.: 

```
Contao core (bundle) version: 4.3
```

The (bundle) may be dropped, I'm sure it confuses some people (and the others will need to understand "the `composer` way" anyway).

This example has been proposed numerous times in this thread and should neither be too hard to implement nor increase any potential or actual risk. I hope we can agree on this and finally lay this discussion to rest (it already bound more dev hours than necessary to implement).

**Comment by codiso** [comment]
If I download Contao i have a version number for orientation.
Why do this version number missing in the Backend?
This is not consistent …

**Comment by fenepedia** [comment]
@codiso Contao 4.4 will show the Contao-Version (core-bundle)
![startseite - contao open source cms](https://cloud.githubusercontent.com/assets/566448/26743692/1b5fb5a2-47e3-11e7-9636-59e204b50760.png)

**Comment by codiso** [comment]
Fine :-D

**Comment by visualpix** [comment]
Ja für den Kunden kann man ja im Backend eine Info-Seite erstellen, die er oben mit Anzeigen sichtbar machen kann. Und in der Seite macht man ein Artikel mit dem Insert-Tag {{version}}. Wenn das jemandem hilft.

Oder. Das ist die Version dieser Installation {{version}}

**Comment by codiso** [comment]
Ich denke so lange man auf der Website von Contao die Versionsnummern nutzt um die aktuelle Version von Contao zu benennen, solange sollte auch im Backend diese Versionsnummer sichtbar sein. Macht die Kommunikation mit Kunden deutlich unkomplizierter, als erst die Version durch einen Inserttag sichtbar zu machen …
