### ISSUE TITLE
Important part: limit the clickable area to the preview image dimensions

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#494]
The clickable area to mark the important part of an image should be restricted to the preview image dimensions, i.e. the container of the preview image should have the same width as the image itself.

For instance, if I accidentally click somewhere in the light red area on the right side outside the preview picture (shown in the screenshot below) the important part of the image gets lost/deleted.

![contao_important_part](https://cloud.githubusercontent.com/assets/1218766/15430536/03a22650-1ea6-11e6-9617-2f3fd400e8dc.jpg)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
This could eventually fix the issue:

```css
.tl_edit_preview_enabled {
	display: inline-block;
}
```

**Comment by leofeyer** [comment]
Fixed in 8ef1394af55a864e245c4e5b2e6f6688b7df4045 then.
