### ISSUE TITLE
Show the date format in the tooltip according to the back end date/time setting

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#495]
The date format shown in the tooltip (see the screenshot below) should consider the back end date/time setting.

![contao_date](https://cloud.githubusercontent.com/assets/1218766/15430276/e44a141c-1ea4-11e6-900e-ea2316200249.jpg)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
Changed in 67fa6f4a4605b408bbbb70bd5b9b9230056ea73e.
