### ISSUE TITLE
The Contao logo is missing the tooltip

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#498]
The Contao logo in the back end header is missing the tooltip (to inform the back end user how to get to the home page).

![contao_homepage](https://cloud.githubusercontent.com/assets/1218766/15432493/bdd00094-1eae-11e6-9771-64a97595c8b3.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
A tool tip to explain that the logo links back to the start page? I guess everyone is used to that.

@contao/developers What's your opinion?

**Comment by Toflar** [comment]
An alt tag for handicapped users should be there anyway and if it explains the image correctly, it should say "back to the homepage", so also "regular" users would see that when hovering the image.

**Comment by leofeyer** [comment]
I think you are messing up the alt tag of the image and the title tag of the link. "Back to the homepage" should be the link title and "Contao logo" would be the alternative text of the image (which should not be set IMHO).

**Comment by Toflar** [comment]
Then add both, which would be perfect then :)

**Comment by leofeyer** [comment]
I have just realized that there is no image at all. It is actually a text link which is replaced with a background image via CSS, so there is no easy way to add a tooltip here.

**Comment by aschempp** [comment]
Should be a simple as adding a `title` attribute to the text link?

**Comment by Toflar** [comment]
Any reason why it's not implemented as an inline svg?

**Comment by leofeyer** [comment]
> Should be a simple as adding a `title` attribute to the text link?

Yeah, but then the tool tip is not displayed correctly (it is too far on the left side), so we would have to adjust the `core.js` script. That's why I wrote "there is no *easy* way" :)

**Comment by leofeyer** [comment]
Fixed in f15c1e4a866dc808449682f5e2cc358a8132c178.
