### ISSUE TITLE
Missing data in the form data format help wizard

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#499]
The help wizard for the form data format does not show the right options.

To reproduce in Contao 4.2.0-RC1:
* open the "Form generator" back end module
* create a "New form"
* enable the option "Send form data via e-mail"
* click on the help wizard icon for the "Data format" select field

![contao_data_format](https://cloud.githubusercontent.com/assets/1218766/15434220/2e644c14-1eb6-11e6-86c0-352019071fc3.png)

![contao_help_wizard](https://cloud.githubusercontent.com/assets/1218766/15434222/31fa9996-1eb6-11e6-8bbb-8adc0f5d29a2.png)

EDIT: I have just seen that also for the "Input validation" help wizard (and perhaps others as well) there are no entries.

EDIT 2: Yep, there are a lot more where the help wizard only shows the "Array" texts.

**Comment by leofeyer** [comment]
Fixed in dda30738713d5f0beaa626b1c8203359860ca25f.
