### ISSUE TITLE
File location: show the real file path instead of the hash

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#500]
To reproduce:
* open the "Layout" > "Templates" back end module (the same applies also for the "File manager" back end module)
* create a "New folder" (if none yet exists)
* select the "Edit multiple" mode
* "Select all" entries and edit the "Name" field

![contao_file_location](https://cloud.githubusercontent.com/assets/1218766/15435167/fc983e5c-1eba-11e6-9a66-84f86d097529.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
Fixed in f1356e82e0d42481d835872e1ac2d566878b04ca.

**Comment by xchs** [comment]
Thanks. It works just fine for the file manager but not for the "Templates" back end module. The changes should be applied here as well, I suppose: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_templates.php#L544-L557

**Comment by leofeyer** [comment]
Fixed in d88c55cf51c91f4dcc943babcfdcebddd1870108 then.
