### ISSUE TITLE
Hide the front end preview icon if no username has been set

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#502]
Front end module "Members": Don't show (or disable) the "Preview the front end as member ID x" icon if no username/password has been set yet. The front end preview will not work if there is no username.

![contao_member_fe_preview](https://cloud.githubusercontent.com/assets/1218766/15437495/b7a76fcc-1ec7-11e6-8e46-fc2d61182d05.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
Fixed in 3dd3f6bd793060ee334966c803e6ca568b83c383.
