### ISSUE TITLE
Image settings: wrong arrow indicators for the image margin setting

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#503]
The tiny arrow indicators for the image margin setting are wrong. They do not correspond to the given top, right, bottom and left margin input fields anymore.

![contao_arrows](https://cloud.githubusercontent.com/assets/1218766/15441976/6f8383e0-1ede-11e6-9c81-6ef964d10bf9.png)

[Contao 4.2.0-RC1]

**Comment by leofeyer** [comment]
Fixed in 37951147b75f2f334b5b2bee71efff845c8f9965.
