### ISSUE TITLE
File uploader issue

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#504]
To reproduce:
* set up a new Contao installation
* run the Contao Install Tool and create a new administrator account
* log into the back end using the administrator's credentials
* open the "File manager" back end module
* click the "File upload" and choose a location
* the **Default uploder** is shown
* open the "Personal data" for the administrator back end user
* it is set **DropZone** as the default file uploader

I have to explicitly save the personal data record again, so that the DropZone file uploader is actually active.

[Contao 4.2.0-RC1]

**Comment by christianromeni** [comment]
This has been the same since maybe 3.0

**Comment by leofeyer** [comment]
> the Default uploder is shown

That's probably why it is called the **default** uploader :)

But we should probably make DropZone the default uploader, shouldn't we @contao/developers?

**Comment by christianromeni** [comment]
@leofeyer Yes, its called default uploader.. But although its not checked in the user settings (the DropZone is selected) the default uploader is shown in the upload section. This is only true for the first user directly after installation.
The next users already have the DropZone selected and not the default, so when saving, its the DropZone ;)

Hard to describe it in any other way ;)

**Comment by xchs** [comment]
> That's probably why it is called the default uploader :)

Yeah, LOL. The point however is: if it is supposed to be the **default** (!) uploader, then I'd expect that the default uploader is selected in the user's personal data (in the first place) and **not** DropZone.

"DropZone" or "Default Uploader" – I'm perfectly fine with both of them as the default setting.

**Comment by leofeyer** [comment]
Changed in f287d3ff8385138d951cebeff49cc563be6dc709.
