### ISSUE TITLE
[4.2.x] File manager does not show files.

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#505]
I have 2 seperate installations of Contao 4.2. In both im not possible to see the files in the filemanager or any file selector.
I updated from 4.1.3 where everything worked. The strange thing, if a file was selected in 4.1, it is visible in the selector. Let me demonstrate:

![image](https://cloud.githubusercontent.com/assets/1358040/15453710/fd214cb8-201f-11e6-9fe3-b0b2c69e95cf.png)
No Files Visible

![image](https://cloud.githubusercontent.com/assets/1358040/15453713/13d48934-2020-11e6-9911-2a02c23dae9d.png)
File visible when selected before.

I have cleared the caches and synched files, nothing changed.

**Comment by leofeyer** [comment]
Can you please list the version numbers of the packages that Composer has installed?

**Comment by christianromeni** [comment]
contao-community-alliance/composer-plugin => 3.0.1    
contao-components/ace                     => 1.2.3.1  
contao-components/all                     => 4.2.0    
contao-components/chosen                  => 1.1.0    
contao-components/colorbox                => 1.6.3    
contao-components/colorpicker             => 1.4.0.1  
contao-components/compass                 => 0.12.2   
contao-components/contao                  => 4.3.0    
contao-components/datepicker              => 2.2.0.2  
contao-components/dropzone                => 3.12.0   
contao-components/highlight               => 8.9.1    
contao-components/html5shiv               => 3.7.3    
contao-components/installer               => 1.2.2    
contao-components/jquery                  => 1.12.0   
contao-components/jquery-ui               => 1.11.4   
contao-components/mediabox                => 1.5.4.1  
contao-components/mediaelement            => 2.19.0.2 
contao-components/mootools                => 1.5.2    
contao-components/respimage               => 1.4.2    
contao-components/simplemodal             => 1.2.3    
contao-components/stylect                 => 3.4.6    
contao-components/swipe                   => 2.0.6    
contao-components/tablesort               => 3.4.5    
contao-components/tablesorter             => 2.0.5.3  
contao-components/tinymce4                => 4.3.4.1  
contao/calendar-bundle                    => 4.2.0-RC1
contao/comments-bundle                    => 4.2.0-RC1
contao/contao                             => 4.2.0    
contao/core-bundle                        => 4.2.0-RC1
contao/faq-bundle                         => 4.2.0-RC1
contao/installation-bundle                => 1.1.0-RC1
contao/listing-bundle                     => 4.2.0-RC1
contao/news-bundle                        => 4.2.0-RC1
contao/newsletter-bundle                  => 4.2.0-RC1
doctrine/annotations                      => v1.2.7   
doctrine/cache                            => v1.6.0   
doctrine/collections                      => v1.3.0   
doctrine/common                           => v2.6.1   
doctrine/dbal                             => v2.5.4   
doctrine/doctrine-bundle                  => 1.6.2    
doctrine/doctrine-cache-bundle            => 1.3.0    
doctrine/inflector                        => v1.1.0   
doctrine/lexer                            => v1.0.1   
incenteev/composer-parameter-handler      => v2.1.2   
ircmaxell/password-compat                 => v1.0.4   
jdorn/sql-formatter                       => v1.2.17  
jeremykendall/php-domain-parser           => 3.0.0    
knplabs/knp-time-bundle                   => 1.6.1    
leafo/scssphp                             => v0.6.3   
league/uri                                => 4.1.1    
lexik/maintenance-bundle                  => v2.1.1   
matthiasmullie/minify                     => 1.3.34   
matthiasmullie/path-converter             => 1.0.8    
michelf/php-markdown                      => 1.6.0    
monolog/monolog                           => 1.19.0   
oyejorge/less.php                         => v1.7.0.10
paragonie/random_compat                   => v2.0.2   
patchwork/utf8                            => v1.3.1   
phpspec/php-diff                          => v1.1.0   
psr/http-message                          => 1.0      
psr/log                                   => 1.0.0    
sensio/distribution-bundle                => v3.0.36  
sensio/framework-extra-bundle             => v3.0.16  
sensiolabs/security-checker               => v3.0.2   
simplepie/simplepie                       => 1.4      
swiftmailer/swiftmailer                   => v5.4.2   
symfony/monolog-bundle                    => 2.11.1   
symfony/polyfill-apcu                     => v1.2.0   
symfony/polyfill-intl-icu                 => v1.2.0   
symfony/polyfill-mbstring                 => v1.2.0   
symfony/polyfill-php54                    => v1.2.0   
symfony/polyfill-php55                    => v1.2.0   
symfony/polyfill-php56                    => v1.2.0   
symfony/polyfill-php70                    => v1.2.0   
symfony/polyfill-util                     => v1.2.0   
symfony/security-acl                      => v3.0.0   
symfony/swiftmailer-bundle                => v2.3.11  
symfony/symfony                           => v2.8.6   
tecnickcom/tcpdf                          => 6.2.12   
terminal42/contao-changelanguage          => 2.2.11   
true/punycode                             => 1.1.0    
twig/twig                                 => v1.24.0

**Comment by ben-eSM** [comment]
I think this corresponds to #492. I guess he's simply missing the tree expand icons.

**Comment by christianromeni** [comment]
If that would be the case, the files should be visible when klicking ON a folder with files in it.. right?

**Comment by ben-eSM** [comment]
Nope, apparently not. You still would have to click the expand icon if the folder is collapsed.

**Comment by christianromeni** [comment]
Ah, ok... Yes, thats right.. So it might be related.. yes.

**Comment by leofeyer** [comment]
The package versions look ok. Anyone else having the same problem?

**Comment by taca** [comment]
Hi,
I have the same problem as @christianromeni wrote.  It is very strange, one environment has this problem and another is not.

I got 4.2.0-RC1 by composer and I archived it "tar + gz" and expand it different server environment.

OK:
* PHP 7.0, Apache 2.4.20, MySQL 5.6.30 on OS X 10.11.5.

Not OK:
* PHP 5.6.22, Apache 2.4.20, MySQL 5.6.30 on NetBSD 7.0_STABLE.

Apache, MySQL are build from pkgsrc on both environment.

**Comment by leofeyer** [comment]
Are the file permissions correct?

**Comment by taca** [comment]
Yes, all files under contao are owned by www:www.  If the file permission problem, there should be some information to log files?

**Comment by christianromeni** [comment]
In case its a php issue, for me it is not working on PHP 5.6.14-pl0-gentoo

**Comment by ben-eSM** [comment]
Running php 5.6.22 and 5.6.21 on my servers and don't have the issue.

**Comment by christianromeni** [comment]
Maybe it's because I upgraded from 4.1 to 4.2?
Did you only test on fresh installs or on upgrades from one version to the other..?

**Comment by taca** [comment]
I found my problem and it is fixed by d7dbbd3dcb2af1432dc0ed183f37c99e3be5a0e7 and it is after 4.2.0-RC1 tag.

OK case was OS X 10.11.5, its file system is case insensitive.  Bad case was NetBSD, its file system is case sensitive.

**Comment by leofeyer** [comment]
Thanks for debugging, @taca. See #492 then.

**Comment by christianromeni** [comment]
Sorry, but this is not closed.. I set my "minimum-stability": "dev"
composer update -> same problem...
On a different installation this time.

**Comment by ben-eSM** [comment]
AFAIK you will always get the 4.2.0-RC1 due to package dependencies. Setting `"minimum-stability": "dev"` won't change anything.

**Comment by christianromeni** [comment]
Yep... figured that out just now...
