### ISSUE TITLE
[4.1.3] CSS errors in Filemanager and every select

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#506]
After opening the filemanager everything looks fine:
![image](https://cloud.githubusercontent.com/assets/1358040/15453745/2a9b377a-2021-11e6-8423-c244718d2173.png)
But after opening a folder, I get some strange behaviour:
![image](https://cloud.githubusercontent.com/assets/1358040/15453749/4086c6b2-2021-11e6-91ce-78b4c7691456.png)
The image that is not loading is this: system/themes/flexible/icons/folMinus.svg
When reloading the page, the proper icon (system/themes/flexible/images/folMinus.gif) is loaded.
![image](https://cloud.githubusercontent.com/assets/1358040/15453756/815e4098-2021-11e6-8c0a-0edfaf36669c.png)
I think this is also related: When editing an article, the content element "show more"-Icon is also trying to load the SVG:
![image](https://cloud.githubusercontent.com/assets/1358040/15453803/360f0cb0-2023-11e6-9287-ce5275ec1cc4.png)

The other problem is that every select is styled wrong:
![image](https://cloud.githubusercontent.com/assets/1358040/15453768/bde7ed52-2021-11e6-9534-00bd319ed137.png)
![image](https://cloud.githubusercontent.com/assets/1358040/15453769/cba847c0-2021-11e6-86ca-0cb2eeb2e157.png)

Can someone confirm this?

**Comment by leofeyer** [comment]
Can you please list the version numbers of the packages that Composer has installed?

**Comment by christianromeni** [comment]
contao-community-alliance/composer-plugin  => 3.0.1
contao-components/ace                      => 1.2.3.1
contao-components/all                      => 4.2.0
contao-components/chosen                   => 1.1.0
contao-components/colorbox                 => 1.6.3
contao-components/colorpicker              => 1.4.0.1
contao-components/compass                  => 0.12.2
contao-components/contao                   => 4.3.0
contao-components/datepicker               => 2.2.0.2
contao-components/dropzone                 => 3.12.0
contao-components/highlight                => 8.9.1
contao-components/html5shiv                => 3.7.3
contao-components/installer                => 1.2.2
contao-components/jquery                   => 1.12.0
contao-components/jquery-ui                => 1.11.4
contao-components/mediabox                 => 1.5.4.1
contao-components/mediaelement             => 2.19.0.2
contao-components/mootools                 => 1.5.2
contao-components/respimage                => 1.4.2
contao-components/simplemodal              => 1.2.3
contao-components/stylect                  => 3.4.6
contao-components/swipe                    => 2.0.6
contao-components/tablesort                => 3.4.5
contao-components/tablesorter              => 2.0.5.3
contao-components/tinymce4                 => 4.3.4.1
contao/calendar-bundle                     => 4.1.3
contao/comments-bundle                     => 4.1.2
contao/contao                              => 4.1.0
contao/core-bundle                         => 4.1.3
contao/faq-bundle                          => 4.1.3
contao/installation-bundle                 => 1.0.1
contao/listing-bundle                      => 4.1.3
contao/news-bundle                         => 4.1.3
contao/newsletter-bundle                   => 4.1.3
doctrine/annotations                       => v1.2.7
doctrine/cache                             => v1.6.0
doctrine/collections                       => v1.3.0
doctrine/common                            => v2.6.1
doctrine/dbal                              => v2.5.4
doctrine/doctrine-bundle                   => 1.6.2
doctrine/doctrine-cache-bundle             => 1.3.0
doctrine/inflector                         => v1.1.0
doctrine/lexer                             => v1.0.1
incenteev/composer-parameter-handler       => v2.1.2
ircmaxell/password-compat                  => v1.0.4
jdorn/sql-formatter                        => v1.2.17
jeremykendall/php-domain-parser            => 3.0.0
leafo/scssphp                              => v0.6.3
league/uri                                 => 4.1.1
lexik/maintenance-bundle                   => v2.1.1
matthiasmullie/minify                      => 1.3.34
matthiasmullie/path-converter              => 1.0.8
michelf/php-markdown                       => 1.6.0
monolog/monolog                            => 1.19.0
oyejorge/less.php                          => v1.7.0.10
paragonie/random_compat                    => v1.4.1
patchwork/utf8                             => v1.3.1
phpspec/php-diff                           => v1.1.0
psr/http-message                           => 1.0
psr/log                                    => 1.0.0
sensio/distribution-bundle                 => v3.0.36
sensio/framework-extra-bundle              => v3.0.16
sensiolabs/security-checker                => v3.0.2
simplepie/simplepie                        => 1.4
swiftmailer/swiftmailer                    => v5.4.2
symfony/monolog-bundle                     => 2.11.1
symfony/polyfill-apcu                      => v1.2.0
symfony/polyfill-intl-icu                  => v1.2.0
symfony/polyfill-mbstring                  => v1.2.0
symfony/polyfill-php54                     => v1.2.0
symfony/polyfill-php55                     => v1.2.0
symfony/polyfill-php56                     => v1.2.0
symfony/polyfill-php70                     => v1.2.0
symfony/polyfill-util                      => v1.2.0
symfony/security-acl                       => v3.0.0
symfony/swiftmailer-bundle                 => v2.3.11
symfony/symfony                            => v2.8.6
tecnickcom/tcpdf                           => 6.2.12
true/punycode                              => 1.1.0
twig/twig                                  => v1.24.0

**Comment by leofeyer** [comment]
The problem is caused by the `contao-components/contao` package already being version 4.3 whereas `contao/core-bundle` is still version 4.1. Version 4.3 of the component already has the dimensions needed for the modernized back end in Contao 4.2.

**Comment by aschempp** [comment]
Looks like that's incompatible and should be a new major version?

**Comment by leofeyer** [comment]
A bigger height does not mean it is incompatible. The API is exactly the same as before.

**Comment by leofeyer** [comment]
To fix this, edit your `composer.json` file and adjust the `contao-components/contao` version constraint accordingly.

**Comment by christianromeni** [comment]
Ok, so it should be just adding:

        "contao-components/contao": "4.2.4",
        "contao-components/chosen": "1.0.5",

to the composer.json right?

**Comment by fritzmg** [comment]
Use
```
"contao-components/all": "~4.1"
```
imho

**Comment by aschempp** [comment]
I'm using the following:

    "contao-components/chosen": "1.0.*",
    "contao-components/contao": "4.2.*",
    "contao-components/stylect": "3.4.5",

**Comment by Toflar** [comment]
That's a bug here. Please reopen. The core-bundle 4.1.4 has to require `"contao-components/all": "4.1.*"`.

**Comment by fritzmg** [comment]
Indeed, shouldn't the `core-bundle` (`4.1.*`) simply require `"contao-components/all": "4.1.*"`?

**Comment by aschempp** [comment]
> Indeed, shouldn't the core-bundle (4.1.*) simply require "contao-components/all": "4.1.*"?

That does not help because `all` would still fetch the latest version.

**Comment by leofeyer** [comment]
I have re-tagged the components so the Contao 4.2 code is in version 5.
