### ISSUE TITLE
[4.2.x] modified CSS breaks backend layouts

### ISSUE THREAD

**Issue by bytehead** [contao/core-bundle#508]
The [negative `margin-bottom`](https://github.com/contao/core-bundle/blob/release/4.2.0/src/Resources/contao/themes/flexible/src/main.css#L193) breaks backend layouts:

```css
.tl_message {
    margin:18px 18px -12px;
}
```

Good to see here:
<img width="945" alt="bildschirmfoto 2016-05-23 um 20 22 10" src="https://cloud.githubusercontent.com/assets/754921/15480216/aeb1dd9e-2124-11e6-9ade-dbc2d2c97fe7.png">

Is there any reason for the negative `margin-bottom`?

**Comment by leofeyer** [comment]
There is a reason, but it is nothing that cannot be solved differently.

**Comment by leofeyer** [comment]
Changed in 336f87f1128bbfe98449d844a0d85667f8341286.
