### ISSUE TITLE
YouTube settings not applied

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#509]
The new YouTube implementation seems to ignore the available settings (player size and autoplay).

**Comment by fritzmg** [comment]
The `autoplay` setting did not have any effect in previous Contao versions either (i.e. MediaElement.js does not consider it for YouTube videos).

In the new YouTube Implementation the `autoplay=1` parameter would need to be appended to the iframe's URL.

**Comment by leofeyer** [comment]
Fixed in aad4fc05a3cd4c5f99eee8eca906fc136dd40bb0.

**Comment by aschempp** [comment]
The player size is still ignored?

**Comment by leofeyer** [comment]
It was never ignored on my system. The iframe gets the width and height set accordingly.

**Comment by aschempp** [comment]
And where would that be in your opinion?
https://github.com/contao/core-bundle/blob/release/4.2.0/src/Resources/contao/templates/elements/ce_youtube.html5

**Comment by aschempp** [comment]
Nevermind 😂
