### ISSUE TITLE
[4.1.3] Subpalletes RTE-Loading Bug

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#516]
I have a strange bug, maybe someone could reproduce this.
If I have an RTE (in my case tinyMCE) in a subpallette only (so nowhere else in the formular), there is a problem loading it.
It loads correctly for a few seconds, and then this happens:
![image](https://cloud.githubusercontent.com/assets/1358040/15967435/056007a4-2f28-11e6-987f-bdedfc8faa7f.png)

**Comment by leofeyer** [comment]
It works like a charm on my system:

https://www.dropbox.com/s/lc5l5od6r1q38zw/rte-subpalette.mp4

(I have moved the `text` field into the `addImage` sub-palette for the test.)
