### ISSUE TITLE
[4.2.0] System Message bug (diff.ago.minute)

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#517]
When Logging into Contao 4.2.o, in the System Messages, I get this issue:

![image](https://cloud.githubusercontent.com/assets/1358040/15967653/dad48bbc-2f28-11e6-8977-9a5dddcf10aa.png)

**Comment by leofeyer** [comment]
You need to update the `AppKernel` class and add the `KnpTimeBundle`.
