### ISSUE TITLE
"icons/folPlus.svg" must be "icons/folplus.svg"

### ISSUE THREAD

**Issue by kozi** [contao/core-bundle#518]
https://github.com/contao/core-bundle/blob/7957576978ee85e065f54bc168ed32b80ece7cb7/src/Resources/contao/themes/flexible/src/main.css#L1231

**Comment by leofeyer** [comment]
No, it must not. The icon is called `folPlus.svg`.

**Comment by aschempp** [comment]
Apparently both exist: https://github.com/contao/core-bundle/blob/7957576978ee85e065f54bc168ed32b80ece7cb7/src/Resources/contao/themes/flexible/icons/folplus.svg

**Comment by kozi** [comment]
Then the files must be renamed https://github.com/contao/core-bundle/tree/develop/src/Resources/contao/themes/flexible/icons

**Comment by kozi** [comment]
![folplus](https://cloud.githubusercontent.com/assets/464029/16038354/f1feeba8-3224-11e6-8b82-dcadc1baed9a.png)

**Comment by kozi** [comment]
![misisng](https://cloud.githubusercontent.com/assets/464029/16038444/4a478216-3225-11e6-882b-4504439168bc.PNG)

**Comment by kozi** [comment]
Missing toggle icons in 4.2.0-RC1

**Comment by leofeyer** [comment]
> Apparently both exist

That's odd. It seems that Git has not deleted the "wrong" icons.
