### ISSUE TITLE
Update template mod_comment_form.html5 to global field style

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#519]
We changed the templates of form widgets some time ago. The heavy changes (with div.widget) are already changed. But I think we should change the other things too so that the structure will be identical.

1. add individual class per widget (.widget-*)
2. position of label - first label then input or textarea
3. every widget should have a label
4. restructure captcha widget (actually the question is the label)

Why we can't use the "normal" form widget templates as include?

**Comment by leofeyer** [comment]
> add individual class per widget (.widget-*)

Yes.

> position of label - first label then input or textarea

What's the matter with the current order?

> every widget should have a label

They do, don't they?

> restructure captcha widget (actually the question is the label)

No. The label is "security question".

**Comment by FuturaDink** [comment]
Why are the most .classes writen with "some_thing" (underscore) but "widget-..." has a minus?

**Comment by frontendschlampe** [comment]
> Why are the most .classes writen with "some_thing" (underscore) but "widget-..." has a minus?

The old one are with "_" and the new one with "-" ... I think ... maybe someday we will unify them :-)

>> add individual class per widget (.widget-*)

> Yes.

great :-)

>> position of label - first label then input or textarea

> What's the matter with the current order?

It's not consistent because all other form widget use the order first label and second input/textarea - it's tiring writing styles for forms and additionally writing extra styles for the comments.

>> every widget should have a label

> They do, don't they?

The comment field has a hidden label and the security question has the question as label and not like in forms label + question as span. Please check this page: http://demo.contao.org/en/applications.html
The comment forms should have the same style like the contact form above, I think. Why it's not the same? It's illogical and inconsequent.

>> restructure captcha widget (actually the question is the label)

> No. The label is "security question".

No, the label of captcha in comments is the question. Please check http://demo.contao.org/en/applications.html

**Comment by FuturaDink** [comment]
Can´t we have all of them with underscore?

**Comment by frontendschlampe** [comment]
> Can´t we have all of them with underscore?

I don't know, but we have to discuss in another ticket! ;-)

**Comment by FuturaDink** [comment]
If this needs another ticket, let me know, please: Captcha should be able to appear as placeholder in the comments as well.

**Comment by leofeyer** [comment]
Ok, so changing the markup is actually a BC break, but since there is no BC promise for templates, we could change it in the next minor release (version 3.4.0).

**Comment by leofeyer** [comment]
Changed in 20975c2172c5e848cf3e02cf4b68b99a694fee1b.
