### ISSUE TITLE
Make legacy config files optional

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#521]
We should make the following files optional in Contao 4.3

 - system/config/dcaconfig.php
 - system/config/langconfig.php
 - system/config/initconfig.php

They should still be supported, but the install tool should not generate them by default. The DCA and language config are replaced by `app/Resources/contao`

**Comment by leofeyer** [comment]
As long as we still have the Contao 3 framework, I'd prefer to keep the files.

**Comment by Toflar** [comment]
I'd like to see them gone too. Supported, yes but not autogenerated. This fucks up my git repository all the time.

**Comment by leofeyer** [comment]
Isn't there an ignore rules by default?

**Comment by aschempp** [comment]
Which is wrong, because I want my dcaconfig.php adjustments in GIT if I do any...

**Comment by leofeyer** [comment]
Then maybe we should fix this?

**Comment by discordier** [comment]
By removing the entry in `.gitignore` and not auto generating the files.
I definately do not want empty files end up in git.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 21st, we want to remove the configuration files (except for localconfig.php) and support `app/Resources/dcaconfig.php` and `app/Resources/langconfig.php` instead. Also, we want to add a new configuration namespace `contao.localconfig`, whose values are automatically mapped to `$GLOBALS['TL_CONFIG']`.

**Comment by leofeyer** [comment]
Addendum: The configuration files must still work if someone adds them.

Addendum 2: If a setting is defined in the app configuration (e.g. `contao.localconfig .install_password`), it overwrites the setting from the localconfig.php.

**Comment by aschempp** [comment]
Not fully correct. There must not be a app/Resources/dcaconfig.php but one should create respective files in a dca subfolder. Same applies to languages!

**Comment by leofeyer** [comment]
You are right of course.

**Comment by leofeyer** [comment]
Does the resource locator already handle this?

**Comment by aschempp** [comment]
Yes it does!

**Comment by aschempp** [comment]
Same thing applies for the templates by the way. But they need to be registered in a config/autoload.php …

**Comment by discordier** [comment]
With #552 this is changed and templates do not have to get registered anymore but are located via  resource location.

Just to keep the issues linked.

**Comment by leofeyer** [comment]
Implemented overwriting the local configuration in a186a3e2ba40fddece7de924294c195b0a28dd5d.

**Comment by aschempp** [comment]
I still think we should not rename the localconfig parameter names to follow Sf best practice. Mostly because it will be very hard to use.
 1. you need to manually translate the name in your brain if you want to copy from localconfig to container.
 2. searching for the parameter where it might be set will not show results in the app `config.yml`
 3. There are potential conflicts if the same parameter name exists in camel case and underline etc.

**Comment by Toflar** [comment]
I agree with @aschempp. There's no point in making this harder than it really is.

**Comment by leofeyer** [comment]
Changed in 4c59417818cd69847b60413382d64b312085509c.
