### ISSUE TITLE
4.2.0 Backend Font

### ISSUE THREAD

**Issue by FrankoGitHub** [contao/core-bundle#523]
Das Backend Theme der 4.2.0 gefällt mir - jedoch der Font ( Roboto mit font-weight: 300 ) sieht unter Windows - speziell im Chrome Browser - sehr dürftig aus.
s. Screen: [https://community.contao.org/de/showthread.php?62923-4-2-0-Backend-Theme](https://community.contao.org/de/showthread.php?62923-4-2-0-Backend-Theme)

Die üblichen Lösungsansätze via -webkit-text-stroke o. -webkit-font-smoothing bringen wenig.
Sicher funktioniert bei mir mit Chrome nur die Darstellung via .svg fonts anstelle der .woff Dateien, 
sofern dann die .svg Dateien vor den .woff fonts gesetzt werden.

s. auch: [http://lee.greens.io/blog/2014/01/13/windows-chrome/](http://lee.greens.io/blog/2014/01/13/windows-chrome/)

Allerdings beinhaltet die font.css des 4.2.0 Themes lediglich die .woff Daten des Roboto Fonts ...

**Comment by qzminski** [comment]
By the way this font issue I think ```Helvetica Neue``` would do slightly better as a primary font. Just an idea.

**Comment by fritzmg** [comment]
> By the way this font issue I think Helvetica Neue would do slightly better as a primary font. Just an idea.

The self hosted webfont license for `Helvetica Neue` costs € 1 441,50 for 250.000 page views. I don't think that's an option?

**Comment by qzminski** [comment]
We do not need a license to use it, that's why the CSS ```font-family``` property acts as a stack. If the first font is unavailable the next one is taken. ```Helvetica Neue``` is a popular font across many websites which do not necessarily include their font files - see Bootstrap or even GitHub for the reference. It is already available on many devices out of the box (especially those with Apple logo) so why not take an advantage of it.

In my opinion that font looks better than the current one and if it's available we can use it.

**Comment by fritzmg** [comment]
Yes, but isn't `Helvetica Neue` a little too different from `Roboto`?

**Comment by aschempp** [comment]
If it's too different, it might also make the backend experience different depending on device (e.g. mobile) and make it sometimes harder to design (e.g. fit a title in the backend menu which has always the same with otherwise).

**Comment by fritzmg** [comment]
Hm, there are a few google search results saying, that `Roboto` is basically a "ripoff" of `Helvetica Neue`, so maybe it's feasible to include that as the first option in the font stack.

**Comment by qzminski** [comment]
@aschempp the font is very similar and differs only in the details. It's rather a minor improvement, we are not changing the general style of the font.

Roboto:
![roboto](https://cloud.githubusercontent.com/assets/193483/16373468/bd4d0178-3c52-11e6-8bfd-46d658e04cb8.jpeg)

Helvetica Neue:
![helvetica-neue](https://cloud.githubusercontent.com/assets/193483/16373467/bd4a3010-3c52-11e6-9388-6afd79288d6c.jpeg)

**Comment by frontendschlampe** [comment]
In my opinion the ``Helvetica Neue`` is bad to read. ``Roboto`` is much better. ``Helvetica Neue`` is not made for screens!

**Comment by FrankoGitHub** [comment]
And it does not solve the problem. If the font does not exist (i believe Helevtica Neue is not a windows standard font ) the Roboto will still looks ugly - because of the Chrome/.woff lack ...

**Comment by leofeyer** [comment]
Helvetica Neue is not an option. We should rather focus on adding the missing Roboto formats such as `.woff2` or `.svg`, so the font renders properly on all systems.

**Comment by FrankoGitHub** [comment]
Frage: Müssen in der web/htaccess für die webfonts nicht auch wieder die MIME Types settings eingetragen werden (zumindest bei Apache)?

**Comment by leofeyer** [comment]
Fixed in 51c194ab97c967e201eb8101d281ee7efe9c0e95. Can you please confirm?

**Comment by FrankoGitHub** [comment]
Besser - obwohl ich die Standard Einstellung mit Roboto-300 bei .875rem (14px) noch immer sehr dünn empfinde - Geschmackssache ...
