### ISSUE TITLE
Duplicate HTML ID on text block

### ISSUE THREAD

**Issue by DanMan** [contao/core-bundle#526]
Each ce_text you add to an article has the same "idTextPanel" ID. So if you have more than one on a page, you get duplicate IDs.

I couldn't figure out where it's coming from. It's not literally part of the code, it's assembled somewhere, it seems. Probably buried somewhere in the `$this->block('content')` template method call.

**Comment by Toflar** [comment]
What does `idTextPanel` refer to? This string is not present in the whole contao code base :)

**Comment by DanMan** [comment]
Vanilla install of v3.5.14.

I've got a content slider, containing a ce_text with an added image. Following that, there's another ce_text outside of this slider. Both ce_text contain a `<div>` which have said ID attribute assigned to them.

**Comment by fritzmg** [comment]
The ID _idTextPanel_ comes from http://www.blindtextgenerator.de/ - @DanMan you were copy & pasting the text from there, including the HTML.
```html
<div id="idTextPanel" class="jqDnR">
    <p style="font-family: Verdana,Geneva,sans-serif; font-style: normal; font-weight: normal; font-size: 10px; letter-spacing: normal; line-height: normal; text-transform: none; text-decoration: none; text-align: left;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. …</p>
</div>
```

**Comment by DanMan** [comment]
You know what, that's scary and very possible at the same time, since I can't reproduce it. o_o

Cheers.
