### ISSUE TITLE
TinyMCE icon font not working when using assets URL

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#528]
* Install `constao/standard-edition` `4.2.0`.
* Create a vhost with two domains pointing to the web directory, e.g. `c42.dev` and `c42assets.dev`
* Log into the backend via `c42.dev/contao`.
* Go to _System_ » _Settings_ » _Back end configuration_ and enter `c42assets.dev` into __Assets URL__, then save.
* Go to _Content_  » _Articles_, create/edit an article and then create/edit a text content element (or go somewhere else, where the TinyMCE will be loaded).
* The icons of the TinyMCE will be missing:

![Screenshot of TinyMCE in Chrome (Windows 7 x64)](https://cloud.githubusercontent.com/assets/4970961/16361526/7693e8e2-3b93-11e6-81ad-e3af4907e6d1.png)

FireFox will not report any error in the console, however Chrome will show the following:
```
Font from origin 'http://c42assets.dev' has been blocked from loading by Cross-Origin 
Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the 
requested resource. Origin 'http://c42.dev' is therefore not allowed access.
```

See also https://community.contao.org/de/showthread.php?62969-TinyMCE-Icons-fehlen&p=412574#post412574

This does not happen in Contao 3 btw.

**Comment by fritzmg** [comment]
Ah, I see now, in Contao 3 it works, because the `.htaccess.default` of Contao 3 contains
```
##
# Allow access from all domains for webfonts
# @see https://github.com/h5bp/html5-boilerplate
##
<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff2?|font\.css)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>
```
I am guessing this can be closed, since the default `/web/.htaccess` of Contao 4 does not come with any of the default configurations, that Contao 3 used to have and thus I assume that it is up to the web developer himself to configure the web server properly.

**Comment by discordier** [comment]
We should at least document it in the install docs then.

**Comment by Toflar** [comment]
I think we should put that part into the standard-edition. That's what it is for: a starting point to set up a Symfony application with the Contao core bundle.

**Comment by fritzmg** [comment]
> I think we should put that part into the standard-edition. That's what it is for: a starting point to set up a Symfony application with the Contao core bundle.

Shouldn't it provide more than that then though? e.g. the sending of the correct mime type headers (though I think it's unlikely that modern webservers do not send the correct mime type header by default already).

**Comment by leofeyer** [comment]
We should probably remove `<?= TL_ASSETS_URL ?>` from the `be_tinyMCE.html5` template.

**Comment by fritzmg** [comment]
But shouldn't the __Assets URL__ of the System configuration apply to all assets, frontend and backend?

**Comment by leofeyer** [comment]
Domain sharding is deprecated now that there is HTTP/2.

**Comment by fritzmg** [comment]
Yes, but I thought that change will only happen in Contao 5?

**Comment by leofeyer** [comment]
I rather meant domain sharding as a general concept.

**Comment by leofeyer** [comment]
@contao/developers Any objections to removing `TL_ASSETS_URL` from the editor templates?

**Comment by Toflar** [comment]
Nope

**Comment by leofeyer** [comment]
Sorry, I just noticed that removing `TL_ASSETS_URL` does not make any sense.

> I am guessing this can be closed, since the default /web/.htaccess of Contao 4 does not come with any of the default (Apache) configurations, that Contao 3 used to have and thus I assume that it is up to the web developer him- or herself to configure the web server properly.

This is actually the correct answer.

**Comment by Toflar** [comment]
But still, it should be moved to the standard-edition, because that's where we should set the headers in the default .htaccess.

**Comment by leofeyer** [comment]
Added in contao/standard-edition@1092c2a3dd2787e692727b944eff3093a0645c8f.

**Comment by fritzmg** [comment]
This has been removed in Contao 4.6. Any prticular reason why?
