### ISSUE TITLE
Fatal error related to reoccurring event date

### ISSUE THREAD

**Issue by DanMan** [contao/core-bundle#530]
After changing the date format in the settings to "Y-M-d", making an event reoccurring causes the following error:

```
Fatal error: Uncaught exception Exception with message Invalid date format "Y-M-d" thrown in system/modules/core/library/Contao/Date.php on line 231

#0 system/modules/core/library/Contao/Validator.php(117): Contao\Date::getRegexp('Y-M-d')
#1 system/modules/core/library/Contao/Widget.php(980): Contao\Validator::isDate('2016-Jul-12')
#2 system/modules/core/widgets/TextField.php(131): Contao\Widget->validator('2016-Jul-12')
#3 system/modules/core/library/Contao/Widget.php(804): Contao\TextField->validator('2016-Jul-12')
#4 system/modules/core/classes/DataContainer.php(320): Contao\Widget->validate()
#5 system/modules/core/drivers/DC_Table.php(1951): Contao\DataContainer->row('{title_legend},...')
#6 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#7 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#8 contao/main.php(20): Contao\BackendMain->run()
#9 {main}
```

**Comment by xchs** [comment]
> Contao supports all date and time formats that can be parsed with the PHP date() function. However, to ensure that any input can be transformed into a UNIX timestamp, you can **only use numeric date and time formats** (j, d, m, n, y, Y, g, G, h, H, i, s) in the back end.

**Comment by DanMan** [comment]
> You might want to set the date/time format in the root page settings.
Wouldn't that cause the same error? I guess I'll just do my own date formatting inside of a template. But thanks for the hint.

Still, it's a brutal way to fail with a fatal error just for using an unsupported date format. Just sayin'
