### ISSUE TITLE
Layout: Removing Front-End-Modules not possible

### ISSUE THREAD

**Issue by fenepedia** [contao/core-bundle#534]
If I edit a layout and add a new row, everything works as expected. But If i want to remove a frontend-module, this isn't possible. The row is disabled, but could not removed.

See this video:
https://fenepedia.wistia.com/medias/qr4zmn4p9x

**Comment by aschempp** [comment]
see https://github.com/contao/core-bundle/issues/520

**Comment by fenepedia** [comment]
Sorry, didn't see the ticket…
