### ISSUE TITLE
[4.2.0] System log stays empty

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#536]
I am using a fresh installation of Contao `4.2.0` and the System log stays completely empty.

![screen shot 2016-07-01 at 10 08 20](https://cloud.githubusercontent.com/assets/4970961/16515687/c3783ff8-3f73-11e6-910b-89579be25452.png)

There are no notices of backend logins, content element changes, cronjob executions etc. whatsoever. I am guessing this was introduced with or due to #449.

**Comment by leofeyer** [comment]
This has already been fixed in contao/standard-edition@1ef8948db84c0b466a27a97dbcf829db794c0227.
