### ISSUE TITLE
article.svg in Firefox nur weiß

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#538]
Die Datei `system/themes/flexible/icons/article.svg` wird in Firefox (47, Ubuntu) nur als weiße Fläche dargestellt. In Chrome unter Ubuntu erscheint das korrekte Icon.
Icon ist beispielsweise eingesetzt in der Navigation vor "Inhalte" und in der Seitenstruktur bei "Artikel bearbeiten"

Die `article_.svg' dagegen wird richtig angezeigt.

**Comment by BugBuster1701** [comment]
Das wird nicht viel helfen, aber wenn ich die beiden Angaben
 `gradientTransform="matrix(.032 0 0 .032 -1120.496 -1651.84)"` 
weglasse, geht es.

**Comment by BugBuster1701** [comment]
betrifft auch `system/themes/flexible/icons/articles.svg`

**Comment by leofeyer** [comment]
@frontendschlampe /cc

**Comment by frontendschlampe** [comment]
alles klar ... prüfe ich ...

**Comment by frontendschlampe** [comment]
@BugBuster1701 Kannst du mal bitte testen mit https://github.com/contao/core-bundle/pull/539! :-)

**Comment by BugBuster1701** [comment]
Leider keine Besserung.

**Comment by frontendschlampe** [comment]
so ... habe mal meinen PR aktualisiert und einen anderen Export probiert ... kannst du nochmal probieren? https://github.com/contao/core-bundle/pull/539/commits/80b83c98477f222792dc35ea448f10ee28b21dd3

**Comment by leofeyer** [comment]
Ich schließe dieses Ticket mal zugunsten von #538.
