### ISSUE TITLE
Purge images only if they weren’t accessed for a long time

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#546]
The image purging was removed from TL_CRON now in 9f43f022235324570493bb1bb79c15c40a363f8c. Wouldn’t it be better if we purge the cache automatically but only remove files that didn’t were accessed for at least 30 days or so?

**Comment by discordier** [comment]
Won't work IMO as the web directory will most likely be mounted with `noatime` and therefore the last access time will not get updated.
We would be forced to keep the list external, however we will not have access to the apache log to determine when the image was downloaded the last time and therefore our list will be incomplete at best.

**Comment by ausi** [comment]
We would also have to purge the whole page cache every time, which might not be a good idea.
