### ISSUE TITLE
initialize.php file not being updated

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#564]
I have recently discovered that after the update from Contao core 4.1 to 4.2 one of my dependencies that relies on ```system/initialize.php``` stopped working. That's because the content of the ```initialize.php``` file has changed but it was not updated as it already existed:

https://github.com/contao/core-bundle/blob/master/src/Command/InstallCommand.php#L166

I think you should always update that file even despite the fact that it already exists.

**Comment by leofeyer** [comment]
I don't think this is possible, because the `initialize.php` file might have been customized.

**Comment by aschempp** [comment]
That certainly is not supported…

**Comment by leofeyer** [comment]
Ok.

**Comment by aschempp** [comment]
So I think it should override on `contao:install` command, right?

**Comment by leofeyer** [comment]
Changed in 73de702e0773c096182e778419fd206eb20c561a.
