### ISSUE TITLE
Symlink issues with new template loader

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#571]
I symlinked my whole core bundle into the vendor dir of a contao 4 installation. Unfortunately, the template loader cannot handle this because here (https://github.com/contao/core-bundle/blob/develop/src/Cache/ContaoCacheWarmer.php#L292) it tries to make the path relative by replacing the `rootDir` by `''`. Obviously my directories do not match, so I get an absolute URL which in turn causes the `TemplateLoader` to return something like `/path/to/installation/path/to/symlinked/bundle/etc.` which obviously does not exist.

Why does it have to be relative? Can't we return the absolute path and make sure the `TemplateLoader` does only prefix paths by `TL_ROOT` if they are not absolute (not starting with a `/`)?

**Comment by leofeyer** [comment]
It has to be relative for BC. The template paths have always been relative.

**Comment by Toflar** [comment]
No, see https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/TemplateLoader.php#L120.

I'd simply propose something like this:

```diff
// Load the default template
if (isset(self::$files[$template]))
{
+    if ('/' === self::$files[$template][0]) {
+        return self::$files[$template] . '/' . $file;
+    }
+
    return TL_ROOT . '/' . self::$files[$template] . '/' . $file;
}
```

And just add the the absolute paths when creating the template cache.

**Comment by leofeyer** [comment]
Yes, we can add this. Will it solve your problem?

**Comment by leofeyer** [comment]
We should maybe use some kind of `isAbsolutePath()` method that also supports `C:\`.

**Comment by Toflar** [comment]
Yes, SF's `isAbsolutePath()` on `Filesystem` works perfectly fine.

**Comment by Toflar** [comment]
Let's just forget about this. There are also other things that do not work. E.g. the `contao:symlink` command does not work because it will obviously generate the symlinks somewhere into nowhere.
