### ISSUE TITLE
Future features and their depencencies

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#574]
Starting a list here so we know what issues to tackle first. To be extended/modified.

| Task | Short description | Prerequisites | Logical priority | Pull Request |
| --- | --- | --- | --- | --- |
| 1 | Edge Side Includes | 2, 3, 8, 9 |  | @toflar |
| 2 | No more server related super globals (`$_GET`, `$_POST`, `$_COOKIE`, `$_SERVER`, `$_SESSION`) in the code base. Everything must be either using `Input`, `Environment`, `Session` or already the current request from the request stack. |  | 1 | https://github.com/contao/core-bundle/pull/575 (@discordier) |
| 3 | No more `global $objPage`. Must be an attribute on the current request. |  | 2 | @leofeyer |
| 4 | New search index (page crawler). Way better if done using SF's request stack because everything can be done in the same process (no real web requests = no routing via webserver = faster). | 2 |  | @discordier |
| 5 | New permission system using voters. | 7 |  |  |
| 6 | Better HTTPS support (automatically use cookie_secure etc.) | 3 |  |  |
| 7a | Full support for SF authentication in BE |  | 3 | @bytehead |
| 7b | Full support for SF authentication in FE | 10 | 3 | @bytehead |
| 8 | Make sure page types, fe modules and content elements work like regular controller (request -> response) |  |  |  |
| 9 | Provide a route and integrate with HttpCache to allow splitting up `Cookie` into other headers to allow proxies to `Vary` on them. | 2, 3, 7 |  | #577 (@toflar) |
| 10 | Use the CMF router and provide the page object as request document | | | |

**Comment by discordier** [comment]
Currently working on the super globals usage (number 2 in your list). PR upcoming.

**Comment by discordier** [comment]
My work on the superglobals is a prerequisite of my actual work on number 4.

**Comment by Toflar** [comment]
> My work on the superglobals is a prerequisite of my actual work on number 4.

Already on the list :)

**Comment by discordier** [comment]
You can add #575 for task 2

**Comment by leofeyer** [comment]
@Toflar I guess we have to overwork the list, don't we?

**Comment by Toflar** [comment]
Closing this because in the meantime

1) we have achieved full ESI support 🥳 
2) Server super global access has largely disappeared in v5 🥳 
3) is still there mainly for compatibility reasons but it's also part of the request object 🥳 
4) has landed 🥳 
5) has landed in v5 🥳 
6) has landed 🥳 
7a and 7b) have landed 🥳 
8) is possible, the core still has to migrate the front end modules but content elements are all fragments in v5 🥳 
9) we decided against this, the preflight concept is way to sophisticated for 99% and we have achieved great caching results with other mechanisms 🥳 
10) has landed 🥳
