### ISSUE TITLE
Backend Startseite Breite der Versionsübersicht

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#578]
Die Versionsübersicht auf der Startseite des Backends nimmt bei einer Fensterbreite von ca. 800 bis 960 px nur einen Teil der Breite ein. Neben der Tabelle befindet sich dann innerhalb des ````#main````-div eine weiße Fläche.

Könnte man die Breite der Tabelle nicht einfach auf 100 % setzen, um derartige Probleme zu vermeiden?

**Comment by leofeyer** [comment]
Kann ich nicht nachvollziehen. Könntest Du einen Screenshot machen?

**Comment by fritzmg** [comment]
Ich schätze er meint die weiße Fläche hier rechts:

![screen shot 2016-09-19 at 20 59 39](https://cloud.githubusercontent.com/assets/4970961/18645080/18d9be6e-7eac-11e6-8283-558f64c7bdb1.png)

**Comment by Mynyx** [comment]
Genau

**Comment by leofeyer** [comment]
Ja, das geht. Und wenn wir das machen, sollten wir uns auch um die anderen Ansichten in diesem Breakpoint kümmern, wie z.B.:

<img width="979" src="https://cloud.githubusercontent.com/assets/1192057/18665623/5c82c350-7f28-11e6-82ab-8962d9379095.png">

**Comment by leofeyer** [comment]
Behoben in 292f6745a880365fbebe0564ebf8a3c4fccccb43.
