### ISSUE TITLE
@ContaoCore/Error/service_unavailable.html.twig ist nicht übersetzt bei Aufruf von URL ohne URL-Suffix wenn url_suffix /

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#585]
- URL-Suffix `/` konfigurieren
- Wartungsmodus aktivieren
- URL ohne URL-Suffix aufrufen z. B. `/test` statt `/test/`
- Das angezeigte Template `@ContaoCore/Error/service_unavailable.html.twig` ist nicht übersetzt

**Comment by leofeyer** [comment]
Tritt das Problem auch in der Standard-Konfiguration (Suffix `.html`) auf?

**Comment by Mynyx** [comment]
Nein

**Comment by leofeyer** [comment]
Das liegt daran, dass das Request-Attribut `_locale` nicht gesetzt ist, wenn das URL-Suffix fehlt, daher nimmt Symfony die Default Locale. Wenn Du diese auf `de` umstellst, wird das Template korrekt übersetzt.

@contao/developers IMO bedarf es hier keiner Anpassung. Seht ihr das anders?

**Comment by aschempp** [comment]
Soweit ich mich erinnere nimmt er in Contao 3.x die beste Sprache des aktuellen Browsers?

**Comment by leofeyer** [comment]
Macht er in Contao 4 auch, nur kommt das Skript gar nicht soweit.

**Comment by discordier** [comment]
IMO nichts zu aendern.

**Comment by ausi** [comment]
IMO sollte der Wartungsmodus für `/test` dieselbe Übersetzung liefern wie für `/test/`.

> Das liegt daran, dass das Request-Attribut `_locale` nicht gesetzt ist, wenn das URL-Suffix fehlt

Warum funktioniert es dann mit eingestelltem `.html`-Suffix für `/test` richtig obwohl das Suffix fehlt?

**Comment by leofeyer** [comment]
Keine Ahnung. Hast Du Zeit zu debuggen?

**Comment by ausi** [comment]
Der Unterschied liegt denke ich darin, dass der Symfony-Router für `/` am ende ein spezielles Handling hat. Er erstellt scheinbar einen redirect von `/test` zu `/test/` und in dieser Redirect-Route ist der `_scope` nicht auf `frontend` gesetzt wodurch der `LocaleListener` nicht mehr greift weil der auf `isContaoScope()` testet.

**Comment by discordier** [comment]
@ausi du meinst [das hier](https://github.com/symfony/symfony/blob/bda7e6b7e545b37e76d76bc030ef70eee41db827/src/Symfony/Component/Routing/Matcher/RedirectableUrlMatcher.php#L35)?

**Comment by ausi** [comment]
Die generierte Datei *app/cache/prod/appProdProjectContainerUrlMatcher.php* enthält bei mir folgenden Code:

```php
// contao_frontend
if (preg_match('#^/(?P<alias>.+)/?$#s', $pathinfo, $matches)) {
    if (substr($pathinfo, -1) !== '/') {
        return $this->redirect($pathinfo.'/', 'contao_frontend');
    }
    ...
```

Warum hier der `/` optional gemacht wird, weiß ich aber nicht.

**Comment by ausi** [comment]
Vielleicht hier: [Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php:241](https://github.com/symfony/symfony/blob/bda7e6b7e545b37e76d76bc030ef70eee41db827/src/Symfony/Component/Routing/Matcher/Dumper/PhpMatcherDumper.php#L241)

**Comment by discordier** [comment]
> Warum hier der / optional gemacht wird, weiß ich aber nicht.

Weil dieser eben nicht mandatory ist. Ein apache z.B. liefert bei `/foo` und `/foo/` denselben directory index liefern, oder verstehe ich deine Frage falsch?

**Comment by ausi** [comment]
Da hast du vermutlich recht und das Feature soll wahrscheinlich auch bleiben. Aber ich vermute dass wegen diesem Redirect der locale nicht mehr richtig gesetzt wird im maintenance mode.

**Comment by leofeyer** [comment]
Und wie lösen wir jetzt das Problem?

**Comment by aschempp** [comment]
liegt es nicht eher daran dass Contao mit dem "gekürzten" Alias keine Seite in der Seitenstruktur findet und daher auch keine Sprache bestimmen kann? Wobei er ja immer die des Browsers nehmen müsste?

**Comment by ausi** [comment]
Ich denke soweit kommt es gar nicht, es wird [wie oben beschrieben](https://github.com/contao/core-bundle/issues/585#issuecomment-256599020) eine Redirect-Route erzeugt die der `LocaleListener` nicht behandelt.

**Comment by leofeyer** [comment]
@Mynyx Tritt das Problem in Contao 4.5 noch auf?
