### ISSUE TITLE
UrlGenerator generates alias for root page

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#589]
Reproduce:

``` php
echo $pageModel = \PageModel::findByPk($rootPageId)->getAbsoluteUrl();
```

This will include the alias of the root page.

**Comment by aschempp** [comment]
I think that's intentional

**Comment by leofeyer** [comment]
If `prepend_locale` is enabled (default), it should probably omit the alias, shouldn't it?

**Comment by Toflar** [comment]
I mean in generates something like `domain.tld/root.html` which doesn't even exist. I don't think this can be intentional, can it?

**Comment by leofeyer** [comment]
`PageModel::getAbsoluteUrl()` does not know anything about page types, therefore it simply generates the URL. We would have to enhance the method to handle the case.

**Comment by garyee** [comment]
Same thing happens when using the pagepicker in the backend. If the user chooses a root page, the inserttag class calls the controller which generates a URL for a page that does not exists in the frontend. 
One can not build a website with just a root page, with this fact/logic it would be wrong that a root page can have a frontend URL. On the other hand side, why shouldn't it have an URL when if it has an alias?

**Comment by leofeyer** [comment]
I just tried it in the hotfix/4.3.1 branch with the official demo.

```php
dump(\PageModel::findByPk(1)->getAbsoluteUrl());
```

This generates the following URL:

```
https://standard-edition.local/app_dev.php/en/contao-offical-demo.html
```

The URL will then be redirected to the first active regular subpage:

```
https://standard-edition.local/app_dev.php/en/
```

Besides the redirect, which could be avoided, I do not see any erroneous behavior here.

**Comment by Toflar** [comment]
The URL is inexistent, how can this not be erroneous? E.g. when I want to add it to the search index it generates me a nonsense URL instead of the correct first page.

**Comment by aschempp** [comment]
I can't see a problem, this has always been the case. The page has an alias, so it is existent. It just rediects. Same as a redirect page which has an alias as well.

**Comment by Toflar** [comment]
Anyway, it did cause issues for me but I can't even recall the project anymore because the issue is like 2 lightyears old. Whatever. I close.
