### ISSUE TITLE
add robots.txt + FR (add sitemap.xml files to robots.txt)

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#591]
The file is missing if you install from scratch.

Another nice to have feature:
Add generated sitemap.xml files to the bottom of the robots.txt file automatically either by writing to the file when chron generates sitemaps or by attaching a php handler to the file and get xml-files from there.

**Comment by ADoebeling** [comment]
> Add generated sitemap.xml files to the bottom of the robots.txt file automatically 

+1

**Comment by xchs** [comment]
> Add generated sitemap.xml files to the bottom of the robots.txt file automatically

For reference: https://github.com/contao/core/issues/5014, https://github.com/contao/core/issues/3062, https://github.com/contao/core/issues/691

**Comment by leofeyer** [comment]
The file has been removed intentionally, because there are no entries to make by default.

**Comment by frontendschlampe** [comment]
you can try hofff/contao-robots-txt-editor :-)

**Comment by asaage** [comment]
> you can try hofff/contao-robots-txt-editor :-)

that's nice.
