### ISSUE TITLE
Database connection refused for certain database names

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#593]
I have set up a new Contao 4.2.4 installation. After running the install tool it asks again for the database credentials. The input fields are already pre-filled with the values from the `parameters.yml` config file. However, Contao refuses to connect to the database as long as the database name is built according to this scheme: `foo_example.com`. Only after changing the database name to e.g. `foo_example` I could establish the database connection.

**Comment by leofeyer** [comment]
@contao/developers Could this be a Doctrine restriction?

**Comment by xchs** [comment]
Ahh, that would explain it, since it actually worked like a charm for Contao 3.x.

**Comment by Toflar** [comment]
Never ever use a `.` in a database, table or column name. It's unwritten law.
Even if it works on some platforms, it's bound to break somewhere because it means you have to escape it everywhere. The `.` is used for so many things (aliasing etc.) in queries. Just don't use it.
MySQL doesn't even list it as a valid character: http://dev.mysql.com/doc/refman/5.7/en/identifiers.html

**Comment by leofeyer** [comment]
Then we should prevent the character from being typed in, shouldn't we?

**Comment by Toflar** [comment]
Well, it's not technically incorrect. It's just very dangerous to use, I find :-) So yes, maybe we should only allow `0-9,a-z,A-Z$_`.

**Comment by xchs** [comment]
Okay, thanks for the hint. I will use the underline character instead.

**Comment by leofeyer** [comment]
Fixed in contao/installation-bundle@c56f1d619b04c13e096b09704e0bc4402210368c.

**Comment by aschempp** [comment]
I think a `-` (dash) should be allowed as well. I just used a database name like `contao-3.5.17` and this works fine in 3.5.x …

**Comment by leofeyer** [comment]
Hm, wasn't the initial problem the dot in the database name? So even with a dash, you would not be able to name your database `contao-3.5.17`.

Also, I think the regex is taken directly from MySQL:

<img width="539" alt="" src="https://cloud.githubusercontent.com/assets/1192057/19680190/08f9da00-9aa5-11e6-8a6b-d5b6eccc5b85.png">

**Comment by aschempp** [comment]
Well that's the point, I dont know. I'm using this DB name and everything works just fine. So instead of limiting the input maybe we should figure out where the problem actually is?

**Comment by leofeyer** [comment]
You sure have a point here.

**Comment by mlwebworker** [comment]
Ich denke man darf auch die Problematik der Shared Hoster nicht außer acht lassen. Dort ist der Name der Datenbank in den allermeisten Fällen vorgegeben und kann nicht verändert werden.
Siehe auch Anfrage im Forum https://community.contao.org/de/showthread.php?64779-Contao-4-3-Installation-Fehler-bei-der-DB-Verbindung-Datenbankname

**Comment by leofeyer** [comment]
As long as we are using unquoted identifiers, the regex is correct and a dash will cause problems:

```
create database cu-foo;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-foo' at line 1
```

**Comment by discordier** [comment]
@leofeyer IMO the DB name is the only identifier which should automatically get quoted by doctrine as it is used within the connection parameters (haven't tested yet but as it is never used in a combined query string it should work).
Therefore this regex could most likely get loosened up to allow for dashes.

The restriction stands for table names and field names however, as these are used unquoted all over the places and would break already in all versions (pre 4 and later).

Further search led me to [stackoverflow](http://stackoverflow.com/questions/17043173/doctrine-triple-quotes-sql-alias) where a guy had the problem in the opposite direction, doctrine was quoting everything which already was quoted and therefore broke his query. I wonder if pre-quoted queries work at all in Contao as we do not set the `quote_identifier: false` parameter in the DB. This needs investigation.

**Comment by schorsch66** [comment]
Ich habe zu der Thematik bei meinem Hoster mit folgendem Ergebnis nachgefragt:

Laut MySQL-Dokumentation sind Bindestriche in DB-Namen zulässig: "Permitted
characters in quoted identifiers include the full Unicode Basic Multilingual
Plane (BMP), except U+0000:

ASCII: U+0001 .. U+007F

Extended: U+0080 .. U+FFFF"

Die Contao-Entwickler müssten lediglich ihre DB-Namen-Variablen in Backticks
setzen. Der Fehler ist kein Fehler des Webservers oder der Namensvorgsbe für
Datenbanken.

Eine Änderung an der Benennung kann aktuell hier nicht gemacht werden, weil
dann hunderte Kunden, die die aktuelle Variante problemfrei nutzen (also auch
MIT Bindestrich) ihre Konfigurationsdateien ändern müssten. Andere Programme
haben auch kein Problem mit dem Bindestrich.

**Comment by leofeyer** [comment]
I have reverted the changes in 28e8efc1e3e3acd833994411039cfaffe7b7a7de.

**Comment by srhinow** [comment]
Es kommt aber nicht die Fehlermeldung "Please enter only the following characters: A-Za-z0-9$_"
sondern "Datenbankverbindung fehlgeschlagen!". Also ist es nicht das was Leo da in dem contao/installation-bundle@28e8efc gelöscht hat.
