### ISSUE TITLE
Falsche Dateigrößen Angabe bei der "Datei Upload" Fehlermeldung in Formularen

### ISSUE THREAD

**Issue by rhhamburg** [contao/core-bundle#595]
Ich nutze Contao 4.2.4 und habe ein Formular mit einem Feldtyp "Datei-Upload" erstellt. Überschreitet ein Upload nun die Zulässige Dateigröße wird folgende Fehlermeldung angezeigt:

> Die maximale Größe für Datei-Uploads beträgt 0,0 Byte (Contao- oder php.ini-Einstellungen)!

Es wird immer **0,0 Byte** angezeigt egal was in Contao oder in der php.ini eingestellt ist.

**Comment by rhhamburg** [comment]
Sorry, das Feld hatte ich als "Datei-Upload" Größeneinstellung übersehen :-/. Wenn dort etwas eingetragen ist funktioniert alles perfekt.

Steht in diesem Feld eine **0** greift Contao auf den Wert **Maximale Upload-Dateigröße** aus den Einstellungen zurück. Das konnte ich testen. Wäre es nicht gut wenn Contao dann auch den Wert aus **Maximale Upload-Dateigröße** in der Fehlermeldung ausgibt?

**Comment by leofeyer** [comment]
Behoben in f2098f71854278b10421e4e155a62491ef71eead.
