### ISSUE TITLE
Invalid schema markup

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#598]
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/picture/picture_default.html5#L11

There is no `content` attribute for `img` elements, it's totally unnecessary. The [W3C specification](https://www.w3.org/TR/microdata/#values) says that `content` is only relevant for `meta` tags, and `src` should be used for images.

**Comment by leofeyer** [comment]
No idea why I have added it, but it definitely needs to be removed. :frowning:

**Comment by leofeyer** [comment]
Fixed in 1601002596c53ef8720a51e58e7498e684d894cf.
