### ISSUE TITLE
Edit multiple meta informations in file manager, changes are not saved.

### ISSUE THREAD

**Issue by Balindil** [contao/core-bundle#600]
If I try to edit multiple meta informations in file manager the changes are not saved. 
I can only change and save one at a time.

**Comment by leofeyer** [comment]
What are the exact steps to reproduce this issue?

**Comment by Balindil** [comment]
Going to file manager -> choose "Edit multiple" -> then choose some images -> click edit -> choose "Meta information" -> edit some of the informations -> click "Save and close". After reopening meta informations there are no changes saved.

**Comment by leofeyer** [comment]
Fixed in a2c73ca426dc1918f2d1d1361caad1806dc0c58e.
