### ISSUE TITLE
Handle child child child .. Tables in the Backend class

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#602]
Currently the breadcrumb trail in the backend class is only handling child child tables. 

So if I have the table stack like `tl_theme > tl_style_sheet > tl_styles` everything is going fine.

But I have `tl_themes > tl_blocks > tl_sections > tl_pattern`. When you editing in tl_pattern (third child table) the breadcrump will only show titles of the last two parent tables. Thats misleading.

I think we should rewrite the following part: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Backend.php#L485-L593

**Comment by leofeyer** [comment]
> I think we should rewrite the following part: 

Yes. Are you going to create a pull request?

**Comment by agoat** [comment]
I will try..

**Comment by leofeyer** [comment]
I'm closing this in favor of #623.
