### ISSUE TITLE
Unable to create a "contao-bundle" under contao 4.2.4

### ISSUE THREAD

**Issue by antoinedavid** [contao/core-bundle#603]
Hi,

With a fresh install of Contao 4.2.4 standard-edition the composer autoloader doesn't work.

My basic structure for my moduletest :
```tree
vendor/addictic/
└── moduletest-bundle
    ├── composer.json
    └── src
        ├── AddicticModuletestBundle.php
        └── Resources
            └── contao
                ├── classes
                │   └── Moduletest.php
                ├── config
                │   ├── autoload.ini
                │   ├── autoload.php
                │   ├── config.php
                │   └── ide_compat.php
                ├── dca
                │   └── tl_car.php
                ├── languages
                │   └── fr
                ├── models
                ├── modules
                └── templates
                    ├── modules
                    └── views

14 directories, 8 files
```

vendor/addictic/moduletest-bundle/composer.json :
```json
{
    "name": "addictic/moduletest-bundle",
    "type": "contao-bundle",
    "description": "Addictic moduletest bundle",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Addictic",
            "homepage": "https://www.addictic.fr"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "symfony/framework-bundle": "~2.8|~3.0",
        "contao/core-bundle": "^4.2.1"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "~1.8",
        "phpunit/phpunit": "~4.5",
        "satooshi/php-coveralls": "~0.6",
        "symfony/phpunit-bridge": "~2.8|~3.0"
    },
    "conflict": {
        "contao/core": "*"
    },
    "autoload": {
        "psr-4": {
            "Addictic\\ModuletestBundle\\": "src/"
        },
        "classmap": [
            "src/Resources/contao"
        ],
        "exclude-from-classmap": [
            "src/Resources/contao/config",
            "src/Resources/contao/dca",
            "src/Resources/contao/languages",
            "src/Resources/contao/templates"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "extra": {
        "branch-alias": {
            "dev-develop": "4.3.x-dev"
        }
    }
}
```
vendor/addictic/moduletest-bundle/src/AddicticModuletestBundle.php :
```php
<?php

/*
 * This file is part of Contao.
 *
 * Copyright (c) 2016-2017 Addictic
 *
 * @license LGPL-3.0+
 */

namespace Addictic\ModuletestBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Configures the Addictic moduletest bundle.
 */
class AddicticModuletestBundle extends Bundle
{
}
```
app/appKernel.php add :
```php
new Addictic\ModuletestBundle\AddicticModuletestBundle(),
```

When i launch ``composer update`` i obtain the following :
```bash
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class 'Addictic\ModuletestBundle\AddicticModuletestBundle' not found in /ha.0/contaofresh/www/app/AppKernel.php on line 40
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:
  PHP Fatal error:  Class 'Addictic\ModuletestBundle\AddicticModuletestBundle' not found in /ha.0/contaofresh/www/app/AppKernel.php on line 40
```

Same error when i execute app_dev.php :
```php
ClassNotFoundException in AppKernel.php line 40: Attempted to load class "AddicticModuletestBundle" from namespace "Addictic\ModuletestBundle".
Did you forget a "use" statement for another namespace?
```
It must go through by the depreciated ClassLoader of Contao 3?

Best regard

**Comment by leofeyer** [comment]
Did you run `composer dump-autoload`?

**Comment by discordier** [comment]
Your filename is: `ContaoModuletestBundle.php` whereas your class is `Addictic\ModuletestBundle\AddicticModuletestBundle`.
This can't work.

**Comment by antoinedavid** [comment]
Thanks for Your answers.

@discordier it's a simply error of copy-past for the post. But still with the good name i have the error.

@leofeyer
Nop i don't run this command i try that tomorow and i tell you if that fix my issue

Thanks

**Comment by antoinedavid** [comment]
@leofeyer I just run ``composer dump-autoload`` but I still have the same error. This is logical because ``composer update`` launche ``composer dump-autoload``

**Comment by leofeyer** [comment]
This does not look like a Contao issue to me. Also, your `composer.json` has some strange entries:

```json
    "conflict": {
        "contao/core": "*"
    },
    "autoload": {
        "psr-4": {
            "Addictic\\ModuletestBundle\\": "src/"
        },
        "classmap": [
            "src/Resources/contao"
        ],
        "exclude-from-classmap": [
            "src/Resources/contao/config",
            "src/Resources/contao/dca",
            "src/Resources/contao/languages",
            "src/Resources/contao/templates"
        ]
    },
```

Why does your bundle conflict with `contao/core`? And does the folder `src/Resources/contao` exist?

**Comment by antoinedavid** [comment]
Yes `src/Resources/contao` exist.

Originally my composer.json was minimalist :
```json
{
    "name": "addictic/moduletest-bundle",
    "type": "contao-bundle",
    "autoload": {
        "psr-4": {
            "Addictic\\ModuletestBundle\\": "src/"
        }
    }
}
```
The error was exactly the same and the file /vendor/composer/autoload_psr4.php was not updated. After many tests i copy the composer.json of news-bundle and i reproduce the tree structure.

Now this may be a mistake on my part but I have only two files(1 json and 1 php file), so the spectrum of errors as possible is still relatively small.
I'm going to open a ticket on contao.org.

PS  : A doc for the creation of a bundle contao would be fine

**Comment by aschempp** [comment]
@antoinedavid a bundle is not related to Contao, it's simply a Symfony bundle. Please read up on the Symfony documentation: http://symfony.com/doc/current/bundles.html

The only thing that Contao does is check if your bundle contains a folder `Resources/contao` and then include that in the relevant places.

**Comment by antoinedavid** [comment]
Finally just add ``"addictic/moduletest-bundle": "*"`` in ``/composer.js`` fix this issue.

It is also possible to add the bundle in /src, in that case a symlink is created in /vendor and a ``repositories`` property is needed in the /composer.json. Normaly when the bundle is in /src we do not need to add it to /composer.json, that is strange.

**Comment by aschempp** [comment]
Very strange, but not related to Contao at all 😉

**Comment by antoinedavid** [comment]
I am still perplexed by this situation and its resolution :/
