### ISSUE TITLE
Map Environment::httpHost() to Request::getHost()

### ISSUE THREAD

**Issue by mozan** [contao/core-bundle#604]
Simple fix:
Change the `protected static function httpHost()` method to simply:
`return \System::getContainer()->get('request_stack')->getCurrentRequest()->getHost();`

Use case in actual code: `\Contao\Frontend::getRootPageFromUrl()`

In general `\Contao\Environment` should be upgraded to Symfony way of handling Request stuff.

**Comment by leofeyer** [comment]
No idea what you mean. Can you post a code snippet please?

**Comment by Toflar** [comment]
/@xtra started working on this, maybe he can give some more info here :)

**Comment by aschempp** [comment]
@leofeyer we're probably using `$_SERVER` which does not work in functional unit tests.

**Comment by discordier** [comment]
This issue should already be fixed in my WIP #575.

However, you might get bitten by the method adding the page content to the search cache later on.

@Mozan You might want to give above PR a try if it brings you further.

**Comment by leofeyer** [comment]
@contao/developers Are you ok with mapping `Environment::httpHost()` to Symfony's `Request::getHost()` method?

**Comment by Toflar** [comment]
Imho @discordier should split his PR in yet another one that only takes care of the `Environment` because there's a lot more to it than just the `httpHost()` method.

**Comment by aschempp** [comment]
Yeah I also think it does not make sense to just map one method and not the others.

**Comment by discordier** [comment]
Could do so, however, the Input class (which is also changed) and direct usage of superglobals (which I am currently reducing) also place burdens. I have no feedback from @Mozan yet, therefore I do not know of it resolves his problem.

**Comment by leofeyer** [comment]
> Yeah I also think it does not make sense to just map one method and not the others.

Well, mapping everything is a feature but mapping just the one broken method is a bugfix, isn't it?

**Comment by Toflar** [comment]
Nothing is broken. There are just methods that don't use the request object yet. There's no difference between the httpHost() and other methods.

**Comment by leofeyer** [comment]
Then I got the initial description wrong?

> Simple fix:
> Change the `protected static function httpHost()` method to simply:
> `return \System::getContainer()->get('request_stack')->getCurrentRequest()->getHost();`

**Comment by aschempp** [comment]
He's mocking a request in his functional test, but Contao is not using the request class but the globals. That's exactly what @Toflar described.

**Comment by leofeyer** [comment]
See #575.
