### ISSUE TITLE
PageRegular::prepare() method in a WebTestCase error

### ISSUE THREAD

**Issue by Mozan** [contao/core-bundle#605]
Again while in `WebTestCase`

In `\Contao\PageRegular::prepare()`
the call to
`\System::getContainer()->get('request_stack')->getCurrentRequest()->setLocale($locale)`
causes a fault.
Simply removing this method call clear things up.
`// \System::getContainer()->get('request_stack')->getCurrentRequest()->setLocale($locale)`
BTW. What for is this method called here?

**Comment by leofeyer** [comment]
> Again while in `WebTestCase`

What does that mean?

**Comment by aschempp** [comment]
He's running functional tests: https://symfony.com/doc/current/testing.html

@Mozan do you really think that code is obsolete and can simply be removed? 😉 
We need to know what the fault is and find a fix for that. Setting the language is necessary to render correct error pages.

**Comment by leofeyer** [comment]
@Mozan Can you post the error message and stack trace please?
