### ISSUE TITLE
TemplateLoader and custom composer path repositories

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#607]
I'm used to have following setup when developing:

``` bash
# Root directory of the project
project/

# Custom extensions being stored outside
project/dev/custom-extension1
project/dev/custom-extension2

# Different test installations
/var/www/web1
var/www/web2
```

In my composer.json i add the custom extensions using path repositories which will be symlinked into the `vendor` directory.

``` json
{
    "repositories": [
        {
            "type": "path",
            "url": "/path/to/project/custom-extension1"
        }
    ]
}
```

This worked pretty well until Contao 4.3. I talked with @Toflar and he told me it's an known limitation. But I hope we can find an solution for it.

At the moment there is the following behaviour:
- Template paths from symlinked files get registered as absolute path, 
  e.g. `/path/to/project/custom-extension1/src/Resources/contao/templates/mod_custom.html5`
- So the template loader tries to load it in `/kernel_root_dir//path/to/project/custom-extension1/src/Resources/contao/templates/mod_custom.html5` which does not work
- The paths can not be fixed by using the legacy template loader as the TemplateLoader is called after the class loader (which loads the autoload.php) files

That means that the TemplateLoader section in the autoload.php has no effect anymore. That's the purpose I guess, but it's also a BC break. 

As we already have a BC break here I suggest to do it right. This issue could easily fixed when the template loader always store the absolute paths. Checking if a path is relative and add the kernel root dir in `TemplateLoader::addFile` should be pretty simple. The BC break would be in `TemplateLoader::getFiles` which would return absolute paths instead of relative (or as implemented right now a mix of absolute paths and relative paths when using the setup described above).

If you agree to store absolute paths in the template loader I don't mind to contribute the PR.

**Comment by leofeyer** [comment]
Storing absolute paths breaks the portability of the installation, that is why we are storing relative paths everywhere. I can think of two solutions:

1. Storing symlinked files as relative paths.

Then `/path/to/project/custom-extension/…` becomes `../../../path/to/project/custom-extension/…`, which will also work if the loader prepends the kernel root directory.

2. Use `Filesystem::isAbsolutePath()`

By using `Filesystem::isAbsolutePath()`, we can check if the path is absolute before prepending the kernel root directory.

@contao/developers Which solution would you prefer?

**Comment by dmolineus** [comment]
Afaik the generated templates.php cache of twig also contains absolute paths. So I'm not sure if  portability of an installation would work when sharing the cache.

**Comment by aschempp** [comment]
I would prefer not to change the paths to absolute, also for BC reasons. Why can the automatic finding not run *before* the `autoload.php`? This would also have the advantage that I can manually override anything if needed for any reason.

**Comment by leofeyer** [comment]
Fixed in e95a6b41a672b85665231e0f95b8d1786cb5602e.

**Comment by dmolineus** [comment]
Thx. Would be great if also the Template Loader is changed so working with a non warmed up cache would be possible.

**Comment by leofeyer** [comment]
What do you mean?

**Comment by discordier** [comment]
A non warmed cache is IMO per definition not supported as it implies an incorrect (or incomplete) setup.

**Comment by aschempp** [comment]
> A non warmed cache is IMO per definition not supported as it implies an incorrect (or incomplete) setup.

I disagree with that. There are two types of caches in Symfony, required ones and optional ones. That's why there's a `--no-optional-warmers` flag for `cache:warmup` etc. 
Required caches (like the container) build themselves at runtime if not warmed up. Optional ones (like Twig templates) do not, but the application still works though with lower performance.

so if @dmolineus is correct (I haven't checked the `TemplateLoader`), we must search the filesystem if there is no cache available.

**Comment by Toflar** [comment]
> so if @dmolineus is correct (I haven't checked the TemplateLoader), we must search the filesystem if there is no cache available.

I agree with that.

**Comment by leofeyer** [comment]
We already do (of course).

**Comment by dmolineus** [comment]
> We already do (of course).

Yes, and there the changes should also be applied. That's what I'm talking about. Provided a pull request for that.
