### ISSUE TITLE
Add support for self-referencing tables

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#609]
Is there any way to have rows in a table that reference to other rows in the same table (self parent)?

I have the following situation..

I have a table to manage the dca palette with the input fields. Now I want also manage sub (and sub sub) palettes. The input fields (so the table columns) are the same. Now it would be the easiest to save it to the same table. 
So I configured the table with dynamicPtable, but - as expected - when I set the ptable to itself it will not work. 

My current solution is to have a simple extra table, which is set dynamically as the parent table (see https://github.com/agoat/contao-contentblocks-bundle/blob/feature/subpattern/src/Resources/contao/dca/tl_content_pattern.php#L599-L650). This table only contains the id=pid of the parent row and some infos to handle the headerfields correctly in the DC_TABLE driver.

But as the \Input::get('id') is used inconsistently in the DC_TABLE driver, it´s not easy to catch all edit situations correctly.

Another solution would be to have subpattern, subsubpattern,.. tables. But then I have to duplicate the whole dca and the related class multiple times. Not a pretty solution.

I´m not deep enough into the contao core, so I can´t estimate the workload, that is needed to make it possible to have the same table as a parent table. 
So this question go´s to the @contao/developers.

**Comment by asaage** [comment]
Take a look at [sorting-mode 5](https://docs.contao.org/books/api/dca/reference.html#sorting) i bet that is what you are looking for.

**Comment by aschempp** [comment]
This is probably similar to what Isotope eCommerce does, but you probably have to write your own DC Driver to accomplish such complex cases.

**Comment by leofeyer** [comment]
Please refer to the [forum](https://community.contao.org) for this kind of questions.

**Comment by agoat** [comment]
Sorry if I misused the issues system. Thought that this could probably a nice feature.
A short answer to the comments above (more will be discussed in the forum)..

The sorting mode 5 don´t have the sorting features like mode 4. So this is not an option.

I´m glad to here that Isotope eCommerce use the same 'trick'. Seems I was thinking in the same direction. To write my own DC-Driver would be a step to far for now.
