### ISSUE TITLE
Language cache fails if PHP and XLIFF are mixed

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#613]
Since 6669a09b260d103ae8b987f93df0658f27d32820 (contao/core#8530) the `PhpFileLoader` wraps the PHP code with a `namespace {}` block. The `XliffFileLoader` doesn’t do that and so we can end up with a PHP file that starts without a namespace block, but has one inside it. This results in the error `Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script`.

I think this can be solved by adding `namespace {}` blocks to the `XliffFileLoader` too.

**Comment by leofeyer** [comment]
Fixed in 3212698190fa4b560c4d0d0c346cb31c1412a569. Forgot to adjust the tests though. :(
