### ISSUE TITLE
Error in backend articles when using custom templates in custom theme folder

### ISSUE THREAD

**Issue by silenzium** [contao/core-bundle#614]
When I use a custom template for a 3rd party frontend module (not a contao core frontend module) and I edit the parent article of that module, I get an error 'Could not find template "xxxxxx"'. Everything works fine in the frontend and when I edit the module itself I can also choose this template from the template select field.

To reproduce this usse:
1. Create theme template folder `/templates/mytheme`
2. Select that folder in Layout -> Themes -> edit your theme -> Template Folder
3. Install 3rd party module in /system/modules and register it in the AppKernel.php like this:
`new Contao\CoreBundle\HttpKernel\Bundle\ContaoModuleBundle(('3rdpartymodulename'), $this->getRootDir()),`, then clear cache and update database..
4. Copy a template from the module to your theme folder and append something to the filename (i.e. rename `sharebuttons.html5` to `sharebuttons_custom.html5`)
5. Create Frontendelement for this module and select the custom template
6. Click on "save and close" to get back to the parent article where your get the stated error "Could not find template "sharebuttons_custom"

The reason is that the TemplateLoader searches for the template in `/template/` folder but not in the custom `/template/mytemplate/` folder although I have selected it in the theme configuration.

This does **not happen with core templates** like `ce_text` or ce_html. So if I copy the `ce_text.html5` to `/templates/mytheme/ce_text_custom.html5`, there is no error in the backend  since in the article edit page it will always use the default template `ce_text.html5` for some reason.

I can work around this by duplicating all custom templates directly into the /temlplates/ folder.

**Comment by leofeyer** [comment]
This is not a Contao bug but rather a design flaw of the third-party extension. Contao only assigns custom templates in the front end, which is why the problem does not occur with the text element. The sharebuttons extension, however, always uses the custom template if there is one, but since the custom template only exists in the theme templates folder, the installation breaks. (The theme template folder is only available in the front end.)

**Comment by silenzium** [comment]
Makes sense, thanks for clarification!
