### ISSUE TITLE
AddImagineClassPath must not thrown an exception

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#616]
If the CLI PHP version does not have an image extension, `composer update` will fail, because we are throwing an exception in the `AddImagineClassPath` class. A PHP image extension is not required to run `composer update` (although it is to e.g. run the tests), therefore we should probably not throw the exception?

@contao/developers @DanielSchwiperich /cc

**Comment by leofeyer** [comment]
Also, the Imagine classes seem to have their own sanity checks throwing an `Imagine\Exception\RuntimeException`, therefore I think we do not need our exception.

**Comment by aschempp** [comment]
I don't get the issue. How is Imagine related to Composer?

**Comment by DanielSchwiperich** [comment]
via compiler pass the image class gets set if I'm not wrong. 
And this gets triggered during composer script execution like `post-install-cmd` for example. 

The same happens not only for composer, also if you do a simple `php bin/console cache:clear`

**Comment by ausi** [comment]
IMO it is a requirement that one of the PHP image extensions (GD, Imagick or Gmagick) exists. If none of them are installed the `contao/core-bundle` cannot be used.

Also `ext-gd` is [still a requirement](https://github.com/contao/core-bundle/blob/4176f0f00367245dde0b35e1a7d23ff2a8d91849/composer.json#L15) of `contao/core-bundle` so I’m not sure how `composer update` could work in the first place. But I may be misunderstanding the issue.

If this needs to be fixed, I think we should `return $class;` instead of throwing the exception in [AddImagineClassPass.php:61](https://github.com/contao/core-bundle/blob/4176f0f00367245dde0b35e1a7d23ff2a8d91849/src/DependencyInjection/Compiler/AddImagineClassPass.php#L61) so that `Imagine\Gd\Imagine` gets returned if no implementation is available.

**Comment by Toflar** [comment]
I agree with @ausi. It's a requirement for Contao, so I don't think it's something we need to fix. Especially because we cannot add a `require` that represents "either gd, imagick or gmagick".

**Comment by ausi** [comment]
> we cannot add a `require` that represents "either gd, imagick or gmagick".

I think this would be possible by creating three empty packages that require one of the image extensions and `provide` a virtual package that is than required by `contao/core-bundle`, but that would be too much overhead IMO and should – if at all – be done by the Imagine package itself. Related: composer/composer#751

**Comment by leofeyer** [comment]
One of the PHP image extensions is required to **run** Contao but not to **install** it.

Think of a server with PHP-FPM; the PHP-FPM installation has all the PHP extensions but the CLI version does not. Granted, this is quite an edge case, which @DanielSchwiperich noticed because he is using Docker images to provide PHP. In a regular PHP installation, the CLI version will have the same PHP extensions as the FPM version (if not explicitly configured otherwise).

Still, the exception in our class is not technically required, so we could make this edge case work.

> If this needs to be fixed, I think we should `return $class;`

Agreed.

> Also `ext-gd` is [still a requirement](https://github.com/contao/core-bundle/blob/4176f0f00367245dde0b35e1a7d23ff2a8d91849/composer.json#L15) of `contao/core-bundle` so I’m not sure how `composer update` could work in the first place.

That is a good question. @DanielSchwiperich ?

**Comment by ausi** [comment]
> One of the PHP image extensions is required to **run** Contao but not to **install** it.

IMO `bin/console` and `composer run-script post-install-cmd` is some type of **running** Contao.

Only **installing** it would be something like `composer install --no-scripts` I think.

> Still, the exception in our class is not technically required, so we could make this edge case work.

I agree that we can change it if there is a use case.

**Comment by DanielSchwiperich** [comment]
It's not only Docker, also for CI where you often have an image/environment with only php cli running to build and setup the application before deployment. 

Afaik it's not uncommon on managed servers to have a reduced php cli (ini) running compared to the web accessible one

Maybe also casual developers who develop not locally but directly on a shared hosting do the pre install maybe on their local machine und push it via ftp to avoid memory limits or where they don't have a cli option at all on thos servers. (no idea if that's true)

@leofeyer composer has the `--ignore-platform-reqs` option

> --ignore-platform-reqs: ignore php, hhvm, lib-* and ext-* requirements and force the installation even if the local machine does not fulfill these. See also the platform config option.

**Comment by leofeyer** [comment]
Yeah, but you cannot really expect the application to run if you use `--ignore-platform-reqs`, can you?

**Comment by ausi** [comment]
How about using `composer install --no-scripts --ignore-platform-reqs`?

The cache warmup should then be executed in the “real” environment IMO.

**Comment by DanielSchwiperich** [comment]
I already use this to only have the vendors available in phpstorm for example. 
The post-install-cmd is needed to setup the application, not to run it. 

> The cache warmup should then be executed in the “real” environment IMO

Then it should not be run as part of post-install-cmd / post-update-cmd. Would also solve the problem.

**Comment by DanielSchwiperich** [comment]
> Yeah, but you cannot really expect the application to run if you use --ignore-platform-reqs, can you?

yes you only do this if you know you fullfill the requirements in *production*

**Comment by leofeyer** [comment]
Yes. It is still an edge case, but since it will not hurt to remove the exception, I guess we will do it.

**Comment by aschempp** [comment]
I think image is a requirement. There could be command line jobs that process images, so it should always be available.

**Comment by DanielSchwiperich** [comment]
> I think image is a requirement. There could be command line jobs that process images, so it should always be available.

Yes that's true.

**Comment by leofeyer** [comment]
Fixed in 1f07da0c0520d00ba88d93df2f1317a4eaca853b.

**Comment by aschempp** [comment]
Hmm, why did you change this now? The majority agreed that it's correct to throw the exception?

**Comment by leofeyer** [comment]
No, actually the majority agreed that it will not hurt to fix it:

<img width="783" alt="" src="https://cloud.githubusercontent.com/assets/1192057/20172425/5470ea9a-a735-11e6-81dc-0cc5a452aaed.png">
