### ISSUE TITLE
Use Symfony LockableTrait for commands

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#618]
Symfony 3.2 added a `LockableTrait` for commands: https://github.com/symfony/console/blob/master/Command/LockableTrait.php

I think this could replace our `AbstractLockedCommand`.

**Comment by leofeyer** [comment]
We also need to drop support for Symfony 2.8 (and 3.0 and 3.1) for this, don't we?

**Comment by aschempp** [comment]
Correct. Just something for the "future" list :-)
