### ISSUE TITLE
[4.3-dev] Pages get cached while backend user is logged in.

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#628]
Before #576 the page cache checked if `$_SESSION['DISABLE_CACHE']` is set. This happens for example when a backend user is logged in: [Frontend.php:527-530](https://github.com/contao/core-bundle/blob/29c50a8dd47fb34cb78af91758f217930c5a21b7/src/Resources/contao/classes/Frontend.php#L527-L530). This is no longer the case because now only `FE_USER_LOGGED_IN` and `BE_USER_LOGGED_IN` are checked, and they are both `false` if a backend user is logged in.

**Comment by ausi** [comment]
We should probably add a `$this->hasAuthenticatedBackendUser()` check to [FrontendTemplate.php:368](https://github.com/contao/core-bundle/blob/d5d0bbcf17e8959143dc7495ea9dd0022ebac69d/src/Resources/contao/classes/FrontendTemplate.php#L368)

**Comment by leofeyer** [comment]
Fixed in 8467415851ba3be9cb0b7335c5ac88c720b01565.
