### ISSUE TITLE
Move all images (resized and unresized) to the assets folder

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#636]
When uploaded a file smaller then 50x50 Pixel there will be no preview shown in the filetree when the folder is not made public. This happens because no images will be upscaled (generally ok) or resized to the same size. In these cases the path to the files folder is used but normally is not accessible via http. 

![untitled-2](https://cloud.githubusercontent.com/assets/1402434/20746302/7ef0283e-b6e5-11e6-9976-8ea825378a30.png)

This happens in the backend as well as in the frontend. Particularly difficult when using images sizes and coincidental one of the sources have the same size or is bigger than the original.

**All (used) images should be moved to the assets folder!**

**Comment by ausi** [comment]
Does that work in Contao 3.5?

**Comment by agoat** [comment]
I didn't testet it right now but I think as long as the folder is not protected in contao 3.5 there is no problem. But when the protection is activated, the same will happen. 
In contao 4+ folders are protected by default, so the images would not be loaded from the /files/.. folder by default.

**Comment by agoat** [comment]
I fixed this temporarily for me in my extension that deferres the image calculation:
https://github.com/agoat/contao-deferredimages-bundle/blob/contao4.3/develop/src/Image/DeferredResizer.php?ts=4#L110-L120

**Comment by leofeyer** [comment]
@contao/developers A more general question is whether we should generate publicly accessible thumbnails for protected images at all? We might as well use inline images in this case.

**Comment by aschempp** [comment]
I don't feel like piping is a good idea… but obviously thumbnails mean that protected images will be publicly accessible...

**Comment by Toflar** [comment]
I think piping is an excellent idea and the only one that solves this issue for protected images.
Given that the image itself knows whether it's protected or not (we should be able to find out if that's the case or not), we could provide a second filesystem cache in the image factory that is protected and add a controller for those images (`_contao/protected-images/<cachekey>` for example). @ausi do you think that would be possible?

**Comment by agoat** [comment]
The source image is protected, but the thumnails generated from are publicly accessible. Isn´t that the idea behind the protection of the files folder?? The source is protected. 

Why should I upload images to a cms and don´t give publicly access in some way.

Currently, if a images is required in a smaller size, a smaller version is rendered into the assets folder. We just have to handle images without resizing.

Another question is how to recognize images required through css files?? - Maybe that can be implemented into the css parser when the urls are rewritten.

**Comment by Toflar** [comment]
> Why should I upload images to a cms and don´t give publicly access in some way.

Because you upload the images to a page that is protected for certain members? Only they should be able to see the images and thumbnails of them?

> Another question is how to recognize images required through css files?? - Maybe that can be implemented into the css parser when the urls are rewritten.

Not really, CSS is not anything related to a CMS. We will likely not have any CSS editor or parser anymore in Contao 5. But anyway, your CSS could contain something like `background: url(_contao/protected-images/<key>);` too. I think it's very unlikely to reference protected images in a CSS file though.

**Comment by agoat** [comment]
> Because you upload the images to a page that is protected for certain members? Only they should be able to see the images and thumbnails of them?

Thats right. IMO this is also publicly, but for a restricted group instead of anonymous visitors. That´s what I meant when I wrote to upload and publish content.

The question is if we have to protect the thumbnail images as well. As we have cryptic asset names I don´t think these can be crawled. The paths for images in protected pages are only send to the client if the client is authenticated. But if we want a more advanced security concept your suggestion with a second protected file cache could be a solution (check for the token before delivering the image or so). 
Maybe a general Controller for the assets folder (or a protected assets folder).

But before we make a new security concept: As I written above, resized images are handled correctly (without thinking to much about security), but the Image class can´t give back a url to an image inside a protected folder.

**Comment by leofeyer** [comment]
The general concept as outlined by @Toflar is correct. However, I'm also unsure if we need this kind of protection for the generated thumbnails, too.

> we could provide a second filesystem cache in the image factory

There is a filesystem cache in the image factory?

**Comment by agoat** [comment]
This is off-Topic but I have to say some words about :

> We will likely not have any CSS editor or parser anymore in Contao 5. 

**Please, don´t do that.** 

The two mainly reasons I use Contao is the nice handling of images resizing and the css and scss parser. That's a unique selling point of Contao.

**Comment by leofeyer** [comment]
Please do not mix the discussion topics in this ticket! We have not even started working on Contao 5 and there have not been made any decisions whether to drop the CSS/SCSS parsers.

**Comment by leofeyer** [comment]
The questionable lines in the `contao/image` library are https://github.com/contao/image/blob/master/src/Resizer.php#L92-L95. They prevent the cached image from being created and return the path to the original image instead. @ausi Does it make sense to remove these lines?

**Comment by ausi** [comment]
> we could provide a second filesystem cache in the image factory that is protected and add a controller for those images. @ausi do you think that would be possible?

Should be possible I think, either with a second resizer service that gets a different cache directory injected, or we add a `cachePath` option to the `ResizeOptionsInterface`.

> The questionable lines in the `contao/image` library are [Resizer.php:92-95](https://github.com/contao/image/blob/957e1bb8fb0330b26456f015d112fcab853dce89/src/Resizer.php#L92-L95). They prevent the cached image from being created and return the path to the original image instead. @ausi Does it make sense to remove these lines?

I’m not sure. This would re-save the original image with different JPEG settings which could have unwanted effects and uses much more disk space. Maybe we should add an option to the image sizes that enables re-saving? It would however not solve the issue for things like lightbox links which link to the original image.

**Comment by agoat** [comment]
I don't think it's a good idea to simply remove these lines in the contao/image library. As @ausi said, it would re-save the image with eventually unwanted effects. Copying the image would be a better solution.

**Comment by leofeyer** [comment]
> Maybe we should add an option to the image sizes that enables re-saving?

We might as well just copy the image. As long as it gets the correct cache name.

**Comment by aschempp** [comment]
Didn't we discuss this back in Contao 3.5 as well for protected folders?

**Comment by ausi** [comment]
> Didn't we discuss this back in Contao 3.5 as well for protected folders?

There was an issue with images in the filemanager in contao/core#7795.

**Comment by leofeyer** [comment]
> The questionable lines in the `contao/image` library are https://github.com/contao/image/blob/master/src/Resizer.php#L92-L95. They prevent the cached image from being created and return the path to the original image instead. @ausi Does it make sense to remove these lines?

Turns out I was wrong. As @ausi explained, this would generally copy all images (not only small ones) if no resizing is necessary, and that is not what we want. We will have to re-think this.

**Comment by agoat** [comment]
I suggest to just copy the image (similar to what if have done in my extension [contao-deferredimages-bundle](https://github.com/agoat/contao-deferredimages-bundle/blob/contao4.3/develop/src/Image/DeferredResizer.php?ts=4#L110-L120). 

And for images that have not exactly the same size as the original, simply crop the original to have the correct ratio and let the upscaling do the browser (in accordance to #667)

**Comment by leofeyer** [comment]
As discussed in Mumble on March 23rd, those small images should be inlined.

**Comment by agoat** [comment]
> those small images should be inlined.

Does this only refer to the images in the file browser?
What about big images in the frontend (e.g. a 1280x720 image is supposed to be renderd to 1920x1080)? It's not a good idea to inline this image. It should be only cropped to the aspect ratio but not upscaled.

**Comment by Toflar** [comment]
Bigger images get a thumbnail?

**Comment by leofeyer** [comment]
Fixed in f4a32d5054270b5d4c8e98b51e3b4b8a98f37856.
