### ISSUE TITLE
Uploads marked as failed but uploaded and resized correctly

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#637]
When uploading files(images) mostly all files marked as failed. I tested this with a clean contao 4.3 installation. 

![untitled-1](https://cloud.githubusercontent.com/assets/1402434/20749021/dae32c76-b6f0-11e6-988e-505940e4664b.png)

Afterwards it look like this in the filetree:
![untitled-3](https://cloud.githubusercontent.com/assets/1402434/20749100/2cae102a-b6f1-11e6-8618-7b2e41976574.png)

Could not find where it goes wrong.

**Comment by aschempp** [comment]
ddce4dfebae4fe15105c6e929c92ce61392e64a8 is breaking the uploader because `AjaxRedirectResponseException` no longer returns a 2xx status code.

**Comment by agoat** [comment]
An extra question: Is it possible that we can add support of html5 chunked upload?? I know dropzone.js doesn´t support that but there is a fork which implemented chunked upload with dropzone (from 2012): https://github.com/bootle/DropZone
Another solution could be this one:
https://github.com/23/resumable.js (also have a look into this discussion: https://github.com/enyo/dropzone/issues/339)

Maybe worth to have a look. 
I think this would be a great benefit for contao to supports large file uploads (e.g. videos).

**Comment by aschempp** [comment]
Not related to this ticket…

**Comment by agoat** [comment]
Ok, I opened an extra ticket for chunk support: https://github.com/contao/core-bundle/issues/650

**Comment by leofeyer** [comment]
Fixed in 19f560b69eebece7d0278e9950c3fdedabcee2ed.

**Comment by aschempp** [comment]
Not sure if that fix is really correct. A 302 response without a location header sounds invalid to me?

**Comment by discordier** [comment]
@aschempp It is a 204 response now?

**Comment by aschempp** [comment]
In this specific case, yes. But the AjaxRedirectResponseException is 302 without a location.

**Comment by discordier** [comment]
According to RFC, a 302 SHOULD indicate an alternative location but does not have to.
