### ISSUE TITLE
Kernel::getContaoRootDir()

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#638]
I think we should provide a `Kernel::getContaoRootDir()` method instead of relying on `TL_ROOT` always being `dirname($container->getParameter('kernel.root_dir'))`. @contao/developers WDYT?

**Comment by Toflar** [comment]
Makes no sense. It's the app root dir and not related to Contao at all.

**Comment by ausi** [comment]
Also a parameter that can be used instead of `"%kernel.root_dir%/.."` would be great.

**Comment by discordier** [comment]
IMHO such a method is not needed at all.
Instead of relying on the constant you will have to fetch the kernel always then which is almost as bad as the constant.

A parameter (which can be injected into services) makes more sense.

In the end, we should remove the references to `TL_ROOT` altogether and use the proper locations (cache dir etc.) directly.

**Comment by aschempp** [comment]
We should first find out why we need that parameter, and why Symfony does not…

**Comment by leofeyer** [comment]
We need the parameter, because our paths are all relative to `TL_ROOT` and Symfony's paths are relative to `TL_ROOT.'/app'` (or where ever the app dir is).

At the moment, we assume (hardcoded!) that `TL_ROOT === dirname('kernel.root_dir')`, which of course only works as long as the kernel is in `app/` and `app/` is in the root level. This implicit directory structure requirement needs to be removed IMO.

**Comment by aschempp** [comment]
I'm very well aware of the current situation. I just wonder why anyone would need the root path at all. 

For example you cannot use the root to find your bundles files, because you would hardcode the vendor path which is wrong too.

**Comment by leofeyer** [comment]
Here are some places where it would be useful:

* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/Cache/ContaoCacheWarmer.php#L256
* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/Resources/config/services.yml#L158 (@ausi's example)
* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/HttpKernel/Bundle/ContaoModuleBundle.php#L33
* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/DependencyInjection/Compiler/AddResourcesPathsPass.php#L41
* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/Command/InstallCommand.php#L96
* https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/Config/Loader/XliffFileLoader.php#L78

**Comment by leofeyer** [comment]
Just search for `dirname($this->rootDir)` or `dirname(… 'kernel.root_dir')`. All these hardcoded assumptions need to be fixed.

**Comment by aschempp** [comment]
As discussed at the SymfonyCon in Berlin, the problem basically is that we're relying on a fixed directory structure. This *can* be done for the legacy code (like `system/modules`), but certainly is wrong for anything Symfony-related like `web/` or even `vendor/`. Making everything configurable would be the correct approach, but that will be a fairly tedious task…

**Comment by leofeyer** [comment]
As also discussed, there is a simple solution which solves **all** those problems: the Contao root should be the same as the kernel root, so all the Contao directories need to be moved into the `app/` folder.

**Comment by aschempp** [comment]
I think that would be wrong. We also make assumptions about vendor and web dir which would not be solved with this.

**Comment by discordier** [comment]
let alone that we then would be required to symlink everything to both places now, as migrated extensions might rely now on being symlinked to project root.
We can not simply shuffle directories around every release.

**Comment by leofeyer** [comment]
No, you are both wrong. Everything in Contao relies on `TL_ROOT`, so we can actually move the directories to another place without a problem. And our Composer plugin has access to the Composer configuration and can read the app dir (if available).

**Comment by aschempp** [comment]
Unfortunately that is only true for users of TL_ROOT. If I'm currently "hardcoding" my path from system/modules/xxx to app/Resources for whatever reason the changes will break things.

**Comment by discordier** [comment]
I have to second @aschempp on this one.
We have decided to deprecate TL_ROOT for good reason and have shifted away from using it and are using a well known layout for the transitional phase until everything is properly "serviced".
So we already have a bunch of hard coded paths which will all of a sudden break when upgrading Contao if we change the path again.

**Comment by leofeyer** [comment]
> If I'm currently "hardcoding" my path from system/modules/xxx to app/Resources

Yes, but that is wrong in the first place.

> So we already have a bunch of hard coded paths 

We do? Where do we have a hardcoded, absolute path that does not use `TL_ROOT`?

**Comment by aschempp** [comment]
> We do? Where do we have a hardcoded, absolute path that does not use TL_ROOT?

https://github.com/contao/core-bundle/blob/87ae8c6ff95fe6428ba96e8cdf0aae3dbf37de24/src/ContaoCoreBundle.php#L49

And as I said, you can't rely on the location of the vendor folder either…

**Comment by leofeyer** [comment]
> And as I said, you can't rely on the location of the vendor folder either…

Exactly, this is why we need to discuss this in the first place. 😄

**Comment by leofeyer** [comment]
As discussed in Mumble on December 14th, we should add a configuration parameter `contao.root_path`, which is `"%kernel.root_dir%/.."` by default. This should solve 80% of the problems (except e.g. finding the `web/` directory when creating symlinks).

**Comment by leofeyer** [comment]
Also, we need to re-think [this](https://github.com/contao/core-bundle/blob/hotfix/4.3.1/src/Cache/ContaoCacheWarmer.php#L256), because the template paths might as well be relative to the kernel root directory.

**Comment by discordier** [comment]
I still did not get the hype of trying to use relative symlinks in general.
Why did we move to them in the first place?
AFAIS we are experiencing more and more problems and seem to roll back to use explicit links everywhere (I am even tempted to do so in the `composer-plugin` for Windows reasons).

**Comment by aschempp** [comment]
Very bad idea. @fabpot talked about *everything relative* at SymfonyCon in Berlin. Otherwise it will not be possible to build an application in one folder and deploy it into another. Which is explicitly supported in Symfony 3.2.

**Comment by discordier** [comment]
I wonder how they solved the various issues on Windows then, as Windows is also officially supported AFAIK?

**Comment by aschempp** [comment]
Maybe they didn't, it's just Windows after all 😂

**Comment by fritzmg** [comment]
Maybe their reasoning is, that it's a bug in PHP and it ought to be fixed eventually ;)

**Comment by discordier** [comment]
So what shall we do then? Revert the relative symlinks or simply not care about Windows at all? :smile:

btw. @aschempp, is there anywhere a recording about the talk you mentioned? I searched a little but did not find anything even mentioning it.

**Comment by aschempp** [comment]
Videos have been recorded, and as far as I know they will be published at https://www.youtube.com/SensioLabs

**Comment by leofeyer** [comment]
@discordier I don't get your problem. If you just use `(new Filesystem())->symlink()`, the method will automatically create an absolute symlink if the OS does not support relative symlinks.

**Comment by fritzmg** [comment]
@leofeyer not sure if that's possible for the `composer-plugin`, I think it needs to work without any dependencies from other packages?

**Comment by discordier** [comment]
The creation is not always the problem but checking if an existing symlink is relative and pointing to the desired destination is a much bigger culprit (as discussed in the other tickets).
Most of the times I can create them just fine but not READ them.
Unless we agree on removing and recreating all links, no matter where they are currently pointing to, I do not see how using `(new Filesystem())->symlink()` will help me there.

My concerns are generally about symlinks on Windows, which fail on different machines for apparently different reasons (even on appveyor) yet are working locally on a virtual Win 7 machine.
Second, we can not use the symfony Filesystem class in the composer-plugin, as it is not available there.
Only solution would be to copy&paste the code into the plugin.

**Comment by aschempp** [comment]
Does the Composer Filesystem class not offer the same functionality?

**Comment by discordier** [comment]
No it doesn't, however, apparently I was partially wrong on not having `symfony/filesystem` available as it is embedded in composer.
Yet we can not add a dependency on this package, as it would pull in the component into the application (instead of requiring it to be available during runtime of composer).
The plugin IMO must not have any external dependencies (aside from composer-api) as it could break in future composer releases then.
I will however try to pin point the culprits further.

**Comment by leofeyer** [comment]
> As discussed in Mumble on December 14th, we should add a configuration parameter `contao.root_dir`, which is `"%kernel.root_dir%/.."` by default. This should solve 80% of the problems (except e.g. finding the `web/` directory when creating symlinks).

See #662.
