### ISSUE TITLE
Layout selection in article uses custom section ID instead of title

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#640]
While the section dropdown in the page layout for modules uses the title of custom sections, the section dropdown in an article's settings still uses the ID of the custom section instead of the title:

![lc](https://cloud.githubusercontent.com/assets/4970961/20755090/000f0cc8-b70e-11e6-9516-e46ba8dce6de.png)

The titles in this case would have been `Section 1` and `Section 2`:

![lc2](https://cloud.githubusercontent.com/assets/4970961/20755150/2c53a2d0-b70e-11e6-8072-1b146d8e67fb.png)

**Comment by leofeyer** [comment]
Fixed in b2744e09eec27b717ee725940f533045d6219f75.
