### ISSUE TITLE
translations and log_message still references app/logs

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#641]
Within the translations, the `app/logs` folder is hardcoded (e.g. `XPT.errorFixOne`). However, when you do a fresh installation of Contao 4.3, the folder is now named `var/logs`, while when you update to Contao 4.3 from Contao 4.2, it's still `app/logs`.

Same goes for the `log_message` helper function.

**Comment by leofeyer** [comment]
Fixed in efe77a5570ce737d5eb46a36928e6bf7085be56b and contao/newsletter-bundle@3b83368c6bcdf71c7f01111d851d122626cceba7.

**Comment by aschempp** [comment]
We should actually use `$kernel->getLogsDir()` for that…

**Comment by leofeyer** [comment]
How it that supposed to work in an .xlf file?

**Comment by aschempp** [comment]
ever heard of `sprintf`? 😝

**Comment by leofeyer** [comment]
Changed in 63fc5bea03a2e964a5b17e7ce74d7a5839327871.
