### ISSUE TITLE
XLIFF Original language not english

### ISSUE THREAD

**Issue by antoinedavid** [contao/core-bundle#642]
Hi,
It would be a good thing for the translation of the modules that the English language is not compulsory.

In the language directory `en` only `<source>` is read, in others language directory only `<target>` is read (if I'm not mistaken). So we can't make a translation de to es for example with the logic of the XLIFF format.
It will be necessary to take into account the attributes `original`, `source-language` and `target-language` of `<xliff version="1.1"><file>`

Best,
Antoine

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by aschempp** [comment]
Not sure if I understand the issue. XLIFF requires a source language, so one must always be present. If I remember correctly, the correct approach is to read target, if target is missing read source. Not sure if Contao already does that?

**Comment by leofeyer** [comment]
If the translation is English, we read the source; otherwise we read the target.

@antoinedavid What exactly do you want to accomplish?

**Comment by aschempp** [comment]
Then we must change our parser. Always read target if available, always fall back to source if target is not available

**Comment by antoinedavid** [comment]
Hi,

The attributes `source-language` and `target-language`  of `<file>` must be interpreted.

If we have source-language="fr" and target-language="de", then for french language `source` must be read, and, for deutsch language `target` must be read.

Exemple :

/fr/tl_mymodule.xlf
```xml
<?xml version="1.0" ?><xliff version="1.1">
  <file datatype="php" original="src/Resources/contao/languages/fr/default.php" source-language="fr" target-language="de">
    <body>
      <trans-unit id="tl_mymodule.hello">
        <source>Bonjour</source>
      </trans-unit>
    </body>
  </file>
</xliff>
```

/de/tl_mymodule.xlf
```xml
<?xml version="1.0" ?><xliff version="1.1">
  <file datatype="php" original="src/Resources/contao/languages/fr/default.php" source-language="fr" target-language="de">
    <body>
      <trans-unit id="tl_mymodule.hello">
        <source>Bonjour</source>
        <target>Hallo</target>
      </trans-unit>
    </body>
  </file>
</xliff>
```

**Comment by discordier** [comment]
You are right about the general parsing, the language attributes must be examined correctly.

However, your icing of the cake is well beyond how xliff works, as then you would need to specify the way to lookup other languages in the file which is not how translation files work in general.

**Comment by antoinedavid** [comment]
for the icing of the cake it's just to assure a default language

**Comment by discordier** [comment]
Which is, by definition, "en" in Contao and, by definition, one of the languages in the xliff is also "en" and, by current definition, it is the source language.
However, I feel your pain that the source and target language parsing must honor the attributes of the xliff node properly.

**Comment by leofeyer** [comment]
As discussed in Mumble on December 14th, @ausi is going to enhance our .xlf parser to handle this case.

**Comment by ausi** [comment]
Pull request: #654

**Comment by leofeyer** [comment]
Thank you @ausi. I'm closing this ticket in favor of #654 then.
