### ISSUE TITLE
Incompatible with symfony 3.2 (http_cache)

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#643]
The http_cache causes an error when symfony 3.2 is installed (within contao 4.3).

After setting the server cache timeout on the page settings (other than zero), there will be no output when the page is cached. So the first call is rendered but the second has no output. 
After the timeout when the page is revalidated following error is printed:
```
Fatal error: Cannot declare class Symfony\Component\HttpFoundation\ResponseHeaderBag, because the name is already in use in /cms/contao4-clean/var/cache/prod/classes.php on line 4491
```
After the page cache is cleared the next call is rendered and the same is happening as written above.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
@agoat could you please try if removing the line
 
```php 
$kernel->loadClassCache();
```

from the *web/app.php* file fixes the issue?

**Comment by agoat** [comment]
@ausi 
When this line is removed the pages are loaded corretly.

But this is like the cache is deactivated, am I right?

**Comment by ausi** [comment]
I don’t think so, at least if you use PHP 7. This will be removed in a future version of Symfony, see symfony/symfony-standard#1030.

Nevertheless, we should investigate why `loadClassCache()` causes the issue.

**Comment by discordier** [comment]
symfony/symfony#20753 appears to be the same problem while menioning another class name.

**Comment by Toflar** [comment]
Imho we should kill `loadClassCache()` completely. SF still loads it when running a PHP version lower than PHP7 but to be honest, if you want to optimize for performance, switching to PHP7 is the first thing to do. I don't see why we should even bother about performance stuff in other PHP versions.

**Comment by leofeyer** [comment]
What does this have to do with PHP7? And why do you think Symfony automatically loads the class cache under PHP5?

**Comment by Toflar** [comment]
https://github.com/symfony/symfony-standard/commit/e21e941e7df7a47122613db42b353c27d10747d9

**Comment by leofeyer** [comment]
Ok, so let's remove this entirely. In version 4.3.1 or in 4.4.0?

**Comment by aschempp** [comment]
4.3.1 is fine with me, it's not a change anyone would notice, I already removed it from my applications.

**Comment by discordier** [comment]
So did I.

**Comment by agoat** [comment]
I didn´t understand what `$kernel->loadClassCache();` was doing, but I also removed it and everything is fine.

**Comment by discordier** [comment]
It is a speedup attempt which preloads classes which are needed in most requests.
This is however obsolete in PHP7.0 and marginal in PHP 5.6 - therefore it is save to remove it.

**Comment by leofeyer** [comment]
Fixed in the following commits:

 * contao/core-bundle@df3372850190f7f6b4edcdbfdf30412dcee3793a
 * contao/installation-bundle@553cca2ad7e9c7ff319385b1f2454e239b296c7b
 * contao/standard-edition@645b14afb34b8747c38fdd7350837d6cacb77c9d
 * contao/standard-edition@b5f928e72405723ee3190b07ccccbfeed5390fc6
