### ISSUE TITLE
Style issue in theme upload

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#645]
![bildschirmfoto 2016-12-05 um 22 36 56](https://cloud.githubusercontent.com/assets/1073273/20903373/5c3ceeb2-bb3b-11e6-9865-b3ee6b149ab5.png)

I was able to reproduce this on the contao.org backend.

**Comment by leofeyer** [comment]
Fixed in 02f82cae2a095fcd3a321c9bee83f0942daa9287.
