### ISSUE TITLE
Contao models can't be loaded from Symfony Controller

### ISSUE THREAD

**Issue by christian-kolb** [contao/core-bundle#646]
When building a custom API for content in Contao the natural starting point would be a custom route and a controller in Symfony. From there I would for example call 

`MemberModel::findActiveByEmailAndUsername()`. 

This directly fails with 

```
ClassNotFoundException in MemberModel.php line 174:
Attempted to load class "Model" from the global namespace.
Did you forget a "use" statement?
in MemberModel.php line 174
```

When I initialize the whole Contao Framework first with:

```
$contaoFramework = $this->get('contao.framework');
$contaoFramework->initialize();

$member = MemberModel::findActiveByEmailAndUsername();
```

everything works.

I guess this is due to the custom loading of Contao and it's components. The model is just one example here, I guess all other components from Contao have the same issue.

It would be awesome if this wouldn't be necessary and Contao would be loaded through composer.

**Comment by aschempp** [comment]
If you need the Contao 3 framework, you must initialize the framework. This is by design in Contao 4.

**Comment by christian-kolb** [comment]
Ok, if that's "Contao 3" functionality this makes perfect sense. But how else would I access the core Contao models like Member other then with those Models? Are there Member repositories or something similar in Contao 4?

**Comment by aschempp** [comment]
Not yet. Somewhen we want to rewrite all Contao 3 stuff, Models will probably become Doctrine entities. As long as that's not complete (and that will take a long time…), initializing the framework is the correct way to go.

**Comment by discordier** [comment]
Also keep in mind not to use the classes from global namespace anymore as the Contao 3 `class_alias` hack is deprecated, unsupported and already non-working in some areas.

**Comment by christian-kolb** [comment]
I always use `use Contao\MemberModel;` but unfortunately Contao itself doesn't as it always uses the global space: `class MemberModel extends \Model` in `MemberModel.php`.
I guess this was necessary at some point but is now also an issue. Although even if Contao would use full namespaces everywhere the models still wouldn't work without initializing the framework, does it @aschempp ? So this doesn't matter here anyway.

**Comment by discordier** [comment]
No, it won't work currently but might in the future.

I just wanted to point out that you should never use from global namespace anymore.

Contao code uses the global namespace for bc reasons in some places (and simply because noone had the time to work on this so far in other places) but is slowly moving away from this.

When ever you want to interface with the legacy code, you need the framework booted (as otherwise any extensions attaching to HOOKs and the like) won't work properly.

**Comment by christian-kolb** [comment]
Ok, then I can close this issue as it's not going to be relevant for a long time.

**Comment by theDyingMountain** [comment]
I run into the same Problem. I'm loading the Model in a class registered in the Cron Scheduler. 
Everytime the Cronjob is running I got this `Attempted to load class "Model" from the global namespace.` Error.
I'm initializing the legacy code with:
`$contaoFramework = \System::getContainer()->get('contao.framework');
        $contaoFramework->initialize();`
But the Problem still appears. Even if i call 
`class SampleModel extends \Contao\Model`.

Do you have any solution or hint for me?
