### ISSUE TITLE
Add html5 chunks support in the backend file uploader

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#650]
Is it possible to add support for html5 chunks in file upload?? I know dropzone.js doesn´t support that but there is a fork which implements chunked upload with dropzone (from 2012): https://github.com/bootle/DropZone
Another solution could be this one:
https://github.com/23/resumable.js (is discussed here: enyo/dropzone#339)

Maybe worth to have a look.
I think this would be a great benefit for contao to supports large file uploads (e.g. videos).

**Comment by leofeyer** [comment]
There is an ongoing discussion about DropZone [here](https://github.com/contao/core/issues/8385).

**Comment by leofeyer** [comment]
AFAIK, Dropzone does not support chunked uploads. You should probably use https://github.com/terminal42/contao-fineuploader instead.

**Comment by agoat** [comment]
So there is no plan to add chunked uploads to the core?

The terminal42/contao-fineuploader is for extension developers and don´t provide the fineuploader as an alternative for dropzone in the file uploader menu.

Looks like I have to develop my own extension.

**Comment by leofeyer** [comment]
> So there is no plan to add chunked uploads to the core?

There sure is no plan to exchange the existing uploader if chunked uploads are the only benefit. Once Dropzone adds chunked uploads, they will be available in Contao automatically.
