### ISSUE TITLE
Redirect target and CSS classes doesn't work in minicalendar

### ISSUE THREAD

**Issue by Balindil** [contao/core-bundle#656]
`Redirect taget` (Use default, Page, Article, External URL) on a single event only works in `cal_default` - the 
big calendar. In `cal_mini` it uses exclusively the target which is selected in the module.

CSS classes that I give to a single event also are not included in cal_mini.

**Comment by leofeyer** [comment]
This is because the mini calendar does not trigger single events. It is only meant to switch the date in combination with an event list.
