### ISSUE TITLE
Caching problem?

### ISSUE THREAD

**Issue by Balindil** [contao/core-bundle#658]
Although I have not changed anything on the Contao 4.3 installation in the morning the website is down and an error is displayed:
`Fatal error: Cannot declare class Symfony\Component\HttpFoundation\Response, because the name is already in use in /XXXXX/app/cache/prod/classes.php on line 3777`
I guess it´s a caching problem but didn't know it exactly. After purge the page cache in the backend everything is fine. Since activation of the cache, this occurs every night.

I have made the following settings:
Server cache timeout: 12 hours
Client cache timeout: 5 Minutes

I put the server cache on 5 minutes and could reproduce the error.

**Comment by leofeyer** [comment]
This has already been fixed in [Contao 4.3.1](https://contao.org/en/news/contao-4_3_1.html).

**Comment by Balindil** [comment]
Unfortunately, this problem still exists in version 4.3.1.

**Comment by leofeyer** [comment]
Then you did not update the PHP entry points as described in the news I have linked above.

**Comment by Balindil** [comment]
I have to change it manually?! Ok, I can do it. But why does not this happen with an update?

**Comment by Toflar** [comment]
It's a Symfony app. Contao is just a regular Symfony bundle. The entry points are part of your app, so you are also the one to update/adjust/maintain them.
