### ISSUE TITLE
The new image service does not recognize the assets url (TL_ASSETS_URL)

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#659]
Tested with a clean contao 4.3.1 installation.

When setting the assets url in the root page settings, the css and script asset paths are using the assets url, but not the images.

I couldn't find any use of the contant TL_ASSETS_URL in the contao/image repository. Not sure if the image service should use TL_ASSETS_URL in the image->getUrl() method or contao/core have to bring this in (with the second prefix parameter).

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
It’s a bug, the use of `TL_FILES_URL` was missing. I created a fix: #661

**Comment by leofeyer** [comment]
Closed in favor of #661.
