### ISSUE TITLE
Enlarge a picture

### ISSUE THREAD

**Issue by antoinedavid** [contao/core-bundle#667]
Hi,
With contao 4.3.1, the responsives images does not seem to work.
Best,

**Comment by leofeyer** [comment]
What exactly do you mean and how can it be reproduced in the online demo?

**Comment by antoinedavid** [comment]
Hi,

Finally it may not be a bug, and the responsive image it's not the probleme

In Contao 4.2.5 and older we can enlarge a picture but now it's impossible.

See from demo site :
![contao-redim-img](https://cloud.githubusercontent.com/assets/16242303/21674397/dba4fdb6-d32d-11e6-95b8-1cfc5ff763cf.jpg)

**Comment by leofeyer** [comment]
You mean upscaling an 800x240 image to 2000x600?

**Comment by leofeyer** [comment]
I guess that has been changed on purpose, hasn't it @ausi?

**Comment by frontendschlampe** [comment]
> I guess that has been changed on purpose, hasn't it @ausi?

Yes ... I think, there was a ticket for it ... I just search for it ...

**Comment by frontendschlampe** [comment]
> I guess that has been changed on purpose, hasn't it @ausi?

https://github.com/contao/core/issues/8201

**Comment by ausi** [comment]
> I guess that has been changed on purpose, hasn't it @ausi?

Yes. AFAIR we discussed if we should make it configurable, but we couldn’t think of a use case where it makes sense to upscale images. 

@antoinedavid is there a reason why you want to upscale the image?

**Comment by antoinedavid** [comment]
@frontendschlampe :
First my German is very limited for read totaly #8201, sorry
Secondly i think it's not the same issue because gdMaxImgWidth does not restrict resizing in my case, and in Contao 4.2.5 i've not this problem.

I've try an other test from the demo site :

Original image : 725px x 446px
Image size requested : Proportional; width : 1024px
Image generated : 725px x 446px

@ausi :
Yes, full width image by example

**Comment by ausi** [comment]
> Yes, full width image by example

You can do that with CSS, which would save a lot of bandwidth because a smaller image gets sent to the browser:

```css
.class-of-your-image-container img {
	width: 100%;
	height: auto;
}
```

**Comment by antoinedavid** [comment]
Yes of course...
But I used to set all my responsive image sizes via Contao, so it surprised me not to be able to do it as before especially since this change is not mentioned in the changelog of Contao 4.3: https://contao.org/de/changelog/versions/4.3.html.

Why did you decide not to be able to enlarge an image since Contao 4.3?

Now imagine that I want to enlarge the selected area of my image via the file explorer how I do in CSS? I start by generating a smaller image and then I enlarge it in CSS, whereas before I could do everything at once.

And if a customer wants to enlarge an image, I tell him to take photoshop?

For me this mode of operation is a downgrade, although in absolute enlarge an image is not good thing

**Comment by frontendschlampe** [comment]
The problem we have: Why should an image be resized? There will be a loss of quality for the image! Depending on the image size which will be the bigger one, there will be a high loss of quality and the images will look extremly ugly. That's why we decide there's no resizing.

**Comment by asaage** [comment]
I agree on loss of quality and increased filesize.
Nevertheless if you request a specific Dimension (wich is in the valid gd-range) not serving it or serving the original just does not feel right.
In addition to that (i assume) you wont be able to get just the important-part of the image.

**Comment by antoinedavid** [comment]
Yes i totaly agree with @asaage.

A 1920x1080px  picture enlarge @ 2500x1406px is not extremly ugly.

For me the loss of quality of an image is not the responsibility of Contao or of the development team of Contao but of the user of Contao.

My car can go up to 200 km / h but I am not allowed to go beyond 130 km / h on the highway. Yet if the manufacturer limited for France my car at 130 km / h I will not be happy and I will not take this car.

**Comment by antoinedavid** [comment]
To finish it's bug, if i choose crop 500x250px in the backend and the result it's a picture of 325x125px (for example) in the frontend, something is wrong

**Comment by ausi** [comment]
> To finish it's bug, if i choose crop 500x250px in the backend and the result it's a picture of 325x125px (for example) in the frontend, something is wrong

That would be a bug indeed, because the ratio of 500x250 and 325x125 is different. Can you tell the steps how to reproduce this?

**Comment by antoinedavid** [comment]
I've understand now, you apply the ratio of the requested size and apply it according to the original dimension of the image without ever exceeding it, so for that ok, now i understand the optimization, charge load and co.

But in fact the requested size is not the size generated (if upscaling) and that a bug.

May be that it would be necessary to add a `rationalize` options which will have for action the current system of resizing.

**Comment by leofeyer** [comment]
As discussed in Mumble on March 23rd, this is the new intended behavior. We realize that it has worked before, but it was never a supported use case. Also, upscaling via CSS produces the same result while saving bandwidth and storage space, so it seems a much better solution.

**Comment by ben-eSM** [comment]
I'd like to reopen this issue.
@ausi You were looking for a use case but couldn't find one.
I just stumbled upon one when I've updated a client project to Contao 4.4.

I used a defined picture size for a slider in the header. The picture size made sure that all slides are the same height and width. The client is supposed to upload the images in a big enough resolution. However, sometimes they still upload pictures which are slightly smaller. So they got upscaled by the image service and still had the correct aspect ratio, even if the quality degraded a little.
In Contao 4.4 that's now an issue. Some of the sliders are now adapting the height by traversing through the slides. That doesn't look good. So at least if we could enable upscaling, I'd be glad.

You know, sometimes you can tell the client hundreds of time to use big enough images, still they sometimes come up with smaller ones. :)

**Comment by fritzmg** [comment]
@ben-eSM is the image not processed at all? Or is it at least cropped to the desired aspect ratio?

**Comment by ben-eSM** [comment]
Shame on me. I shouldn't rush with writing tickets. You are correct indeed. The images got processed to the correct aspect ratio. The issue however was the slider extension itself who did the height math wrong.
Although the aspect ratio was correct, the slider calculated different vw values for the height.
Problem is solved and the issue is an non issue...sorry!
