### ISSUE TITLE
Layout selection in the article module shows custom section ID instead of title

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#670]
In the overview of the articles the layout sections are shown in brackets after the article titel. 
But custom sections are shown with the ID instead of the title!
The filter selection also lists only the ID when it comes to custom layout sections.

![custom_layout_sections1](https://cloud.githubusercontent.com/assets/1402434/21862257/b884e8fe-d838-11e6-864f-ed55eeb23e60.jpg)
![custom_layout_sections2](https://cloud.githubusercontent.com/assets/1402434/21862262/bc8e16aa-d838-11e6-9183-b204a44e0995.jpg)

**Comment by fritzmg** [comment]
Did you test this with the `core-bundle` `4.3.1`?

**Comment by agoat** [comment]
> Did you test this with the core-bundle 4.3.1?

Yes.
The Issue you described in #640 is fixed. As visible in the screenshots above the title is shown for custom sections in the article settings. But in the article list only the ID is shown.

In the DCA in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_article.php#L60-L61 the inColumn is set to shown in brackets after the title. But only the main, left, right, header and footer sections have a translation set as reference for the inColumn field. 

IMO we have to add a label_callback in tl_article.php to load titles for custom sections.

**Comment by leofeyer** [comment]
Fixed in 123e2c54a11bd6fc0b579378ab76c2db13e2a44b.
