### ISSUE TITLE
Contao 4.3.1 Fehler im CSS-Editor nach Einstellung "Maximum Datensätze pro Seite" auf 0

### ISSUE THREAD

**Issue by Benjaminscherf** [contao/core-bundle#675]
Contao 4.3.3 Fehler im CSS-Editor nach Einstellung "Maximum Datensätze pro Seite" auf 0.

```
Warning: Division by zero in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php on line 5451
Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5451) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149
Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5451) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149
Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5451) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149
Warning: Cannot modify header information - headers already sent by (output started at /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:5451) in /homepages/22/d615086249/htdocs/concept/vendor/contao/core-bundle/src/EventListener/MergeHttpHeadersListener.php on line 149
```

**Comment by leofeyer** [comment]
Wie genau lässt sich das reproduzieren?

**Comment by Benjaminscherf** [comment]
Hallo,

ich habe die Version 4.3.3 zu laufen, auf der 4.3.2 trat der selbe Fehler auf. 
Installiert sind die Extensions:

simple_columns
conditionalselectmenu
dcawizard
dc_multilingual
_autoload
haste
httprequestextended
multicolumnwizard
notification_center
tablelookupwizard
isotope
isotope_rules
isotope_reports

Wenn unter Systemeinstellungen im Bereich Backendeinstellungen die Maximum Datensätze pro Seite auf "0" gesetzt werden, tritt sobald die Selektorenliste eines internen Stylesheet aufgerufen wird, diese Fehlermeldung auf.

**Comment by sheeep** [comment]
I'm able to reproduce this.

The problem is [this line](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/drivers/DC_Table.php#L5451), where an unchecked `0` value will be passed to a division.

```php
$options_total = ceil($this->total / \Config::get('resultsPerPage'));
```

We could either decide to avoid having zeros (or sub-zero numbers) as a valid value for this field or suppress the output of the select menu altogether.

```php
// Don't build an option menu if resultsPerPage is set to zero.
if (0 === (int) \Config::get('resultsPerPage')) {
    return '';
}
```

I tried the former snipped and it seems to work. Let me know if I should provide a PR.

**Comment by leofeyer** [comment]
Fixed in 1ab72deae81b55c7825942b9ec5bb14080c6ea27.
