### ISSUE TITLE
customizable Error-Templates

### ISSUE THREAD

**Issue by asaage** [contao/core-bundle#676]
Currently it is not possible to add [these Templates](https://github.com/contao/core-bundle/tree/master/src/Resources/views/Error) via the BE.

The footer states: *To customize this notice, create a custom Twig template overriding @ContaoCore/Error/no_root_page_found.html.twig.*
In 3.5 you could put something directly under ```templates/``` - just wonder if this feature is droped or if we will find it elsewhere like in contao-manager for instance.

**Comment by leofeyer** [comment]
The footer says _create a custom **Twig** template_! And you cannot create Twig templates in the back end.

**Comment by asaage** [comment]
Correct lable should be __incompatible__ then 😄 
I don't like it though.
