### ISSUE TITLE
Optimize the element preview height

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#678]
Change `h64` to `h36`:

```php
		// Limit the element's height
		if (!Config::get('doNotCollapse'))
		{
			$class .=  ' h36';
		}
```

Replace the green arrow with a smaller solution:

<img width="864" alt="" src="https://cloud.githubusercontent.com/assets/1192057/22200776/d1620592-e160-11e6-88da-3e4a0cdc4713.png">

**Comment by leofeyer** [comment]
Here are some more possible designs:

### 1

<img width="887" alt="" src="https://cloud.githubusercontent.com/assets/1192057/23074613/a5031d28-f539-11e6-9c25-6aa9aec53e4f.png">

### 2

<img width="882" alt="" src="https://cloud.githubusercontent.com/assets/1192057/23074619/aa5a8612-f539-11e6-87bd-f287c17439b1.png">

### 3

<img width="886" alt="" src="https://cloud.githubusercontent.com/assets/1192057/23074624/b05898a6-f539-11e6-9a4d-bd166e732526.png">

Feedback and other suggestions are welcome. 😄

**Comment by Toflar** [comment]
I like the one in the initial issue description the best. If you don't like this, I could live with 1. I don't think putting the arrow to the right like in 2 and 3 makes a lot of sense. I didn't even find the arrow at first sight 😄

**Comment by aschempp** [comment]
I don't like 2 and 3 either. Out of these exames, I would go with the arrow from 1 but the with of the initial version.

**Comment by agoat** [comment]
The button should not too tiny! 
Some buttons in the general nice contao backend theme are somewhat too small.

**Comment by leofeyer** [comment]
See #810.
