### ISSUE TITLE
Add option to add external javascript to layout

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#690]
Currently javascript can only be added as a template to the layout (and inside the template js files from the filesystem can be loaded though the browser with the include command). 

But if it would be possible to add javascript from the file system directly and be delivered from the assets folder - like the external style sheets - then it will be possible to include javascript files without the need to give public access to folders.

**Comment by aschempp** [comment]
I don't get your reasons. The files will be public when copied, why not make the folder public in the first place?

**Comment by agoat** [comment]
> I don't get your reasons. The files will be public when copied, why not make the folder public in the first place?

1) The js script template files are added to the bottom of the html page. But what if I want the scripts be loaded as an assets file in the header (like the jquery core or the css files).
2) I have more then one script file and want them all to be combined (with the jquery or mootools core script).

**Comment by leofeyer** [comment]
Implemented in 87d33977f86fd97bcf41b63c1eb44a4f2fe537e2.
