### ISSUE TITLE
External CSS files can't be loaded in dev environment

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#691]
If an external css file from the file system is included in the layout and the page is loaded in the dev environment (through app_dev.php) the css file can't be loaded unless the containing folder is given public access. 

That's because only scss and less files will be compiled and saved in the assets folder when in dev mode (see the [getFilesUrls() method in the Combiner class](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Combiner.php#L185-L231)).

The css files should also be moved to the assets folder in the dev environment to have the same behavior like in the production environment (and when the files are combined to one).

**Comment by leofeyer** [comment]
Why don't you just publish the folder with the CSS file?

**Comment by agoat** [comment]
This problem is only relevant for extension developers or when I decide not to combine the css files. I ran into this issue while working on a extension and using the app_dev.php for debugging. 

> Why don't you just publish the folder with the CSS file?

I want a clean output. That means I don´t want some css files loaded from the assets folder but others from a deep folder structur in the file system.  

As an example:
I included the normalize.css as an external css file. I also use scss to write my style. If combining the stylesheet files everything works well in production environment, but in the dev environment the files will not be combined and then the scss files will work but the css will not (unless given public access).
I took me some time to figure out why my page looks broken when I load it though my dev environment..

Maybe a real asset managing solution will be helpful and btw. fix some other problems too (like inresized images, a.s.o.)

**Comment by leofeyer** [comment]
> I want a clean output.

The output **is** clean except in the debug mode, where the output is not clean anyways.

Sorry, but that really is a problem of your own making.

**Comment by agoat** [comment]
> The output is clean except in the debug mode

The output is not clean when not combining scripts (which is not recommended for http/2 as the info says). Included .css files will be loaded from the files folder whereas scss files will be loaded from the assets folder.

**Comment by leofeyer** [comment]
That is a clean output IMHO.

**Comment by agoat** [comment]
I agree it's a clean output in the sense of html web standards. 

But I like to have assets loaded from the assets/css|js folders and don't want to give an insight into my files folder structure.

Normally I use scss and so there is no problem for me. It's not a real bug, more a little flaw in the assets handling design.
