### ISSUE TITLE
Wrong icon for PNG image

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#693]
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/config/mimetypes.php#L98

I guess that's not the right image 😂

**Comment by leofeyer** [comment]
I guess it is. At least there is no `iconPNG.svg` icon:

https://github.com/contao-components/contao/tree/master/images

**Comment by aschempp** [comment]
Well then we should use iconPLAIN at least, because the TIF icon sure is wrong.

**Comment by asaage** [comment]
preferably iconJPG

**Comment by agoat** [comment]
What about creating a iconPNG?

Why we differ between gif, bmp, tif but not jpg and png?

**Comment by leofeyer** [comment]
Just create an `iconPNG.svg` file and I'll add it.

**Comment by agoat** [comment]
I've just looked at the mimetype icons and came up with some questions:

1) I need to know what font has been used. Then I can create a `iconPNG.svg`.

2) The audio and video icon is for all mime types for audio or rather video, but the image has multiple icons (bmp, gif, ..). Wouldn't it enough to have one image icon for all images, too?

3) If we decide to have multiple image icons, should we extend this also to have an icon for svg, scss a.s.o?

**Comment by leofeyer** [comment]
@frontendschlampe /cc

**Comment by leofeyer** [comment]
Fixed in contao/core-bundle#802 and contao-components/contao#6. Thank you @frontendschlampe.
