### ISSUE TITLE
ModuleArticleList.php returning the article title as link

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#694]
In the class [ModuleArticleList.php](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleArticleList.php#L109) the link parameter in the returning array should give the alias instead of the title.

```php
$articles[] = array
(
	'link' => $objArticles->alias,
	'title' => \StringUtil::specialchars($objArticles->title),
	'id' => $cssID[0] ?: 'article-' . $objArticles->id,
	'articleId' => $objArticles->id
);
````

**Comment by asaage** [comment]
I dont't think so
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/templates/modules/mod_articlelist.html5#L7

**Comment by agoat** [comment]
Ahh, I forgot I changed my template file..

Then I have to extend this:
Let's say I want the article list to be a menu to open the articles directly. I need the alias or better the correct article link. The current template is only for anchor links. But if there would be also the real article link in the array, there would be a broader application.

I recommend to extend this:
Actually the parameter `link` should be a 'link', but to avoid BC we should not touch it. So I added a `url` parameter.
```php
while ($objArticles->next())
{
	// Skip first article
	if (++$intCount <= intval($this->skipFirst))
	{
		continue;
	}
 
	$strAlias = $objArticles->alias ?: $objArticles->id;
	$cssID = \StringUtil::deserialize($objArticles->cssID, true);

	$articles[] = array
	(
		'link' => $objArticles->title,
		'title' => \StringUtil::specialchars($objArticles->title),
		'id' => $cssID[0] ?: 'article-' . $objArticles->id,
		'articleId' => $objArticles->id,
		'url' => ($objTarget ?: $objPage)->getFrontendUrl('/articles/' . $strAlias)
	);
}
```

Now I can do something like this:
```php
<li><a href="<?= $article['url'] ?>" title="<?= $article['title'] ?>"><?= $article['link'] ?></a></li>
```

**Comment by asaage** [comment]
I think a correct article link is what you get if you display article as teaser - the usecase for ModuleArticleList is onpage-navigation as far as i understand.

**Comment by agoat** [comment]
I also think it's mainly for onpage-navigation. But what is the sense to be able to select a reference page then? The links directing to the page and the anchor position.

At least there should be also returned the alias to be able to generate a correct article link.

```php
while ($objArticles->next())
{
	// Skip first article
	if (++$intCount <= intval($this->skipFirst))
	{
		continue;
	}
 
	$cssID = \StringUtil::deserialize($objArticles->cssID, true);

	$articles[] = array
	(
		'link' => $objArticles->title,
		'title' => \StringUtil::specialchars($objArticles->title),
		'id' => $cssID[0] ?: 'article-' . $objArticles->id,
		'articleId' => $objArticles->id,
		'alias' => $objArticles->alias 
	);
}
```

So I can create a full article link in my template:
```html
<li><a href="<?= $this->request ?>/articles/<?= $article['alias'] ?>" title="<?= $article['title'] ?>"><?= $article['link'] ?></a></li>
```

**Comment by asaage** [comment]
i see...
ModArticleNavigation works kind of that way but without the ability to select a reference page.
I only use both modules rarely because i get allways confused.
Navigation works only if it's included in the layout - List will probably fail if you only display teasers.
I have no idea... 😄

**Comment by leofeyer** [comment]
I have added the `href` parameter in 15ed60e722e1c4a136c53425efcba7a321c3facd.
