### ISSUE TITLE
Syntax Error in cron-js

### ISSUE THREAD

**Issue by comolo** [contao/core-bundle#697]
Hallo,

der Javascript-Code, der das Cron-Skript auslöst, enthält wohl einen Syntax error.

Console:
`
Uncaught SyntaxError: Unexpected token &&`

``` js
<script>
setTimeout(function(){jQuery.ajax("system/cron/cron.txt",{complete:function(e){var t=e.responseText||0;parseInt(t)<Math.round(+(new Date)/1e3)-&&jQuery.ajax("system/cron/cron.php")}})},5e3)
</script>
```

Browser: Chrome 56 & 
Contao: 4.3

**Comment by leofeyer** [comment]
Ich nehme an, dass Du irgendein altes Template verwendest. In Contao 4 gibt es diesen Aufruf nämlich nicht mehr.
