### ISSUE TITLE
Subresource Integrity (SRI)

### ISSUE THREAD

**Issue by lionel-m** [contao/core-bundle#702]
Could you add the subresource Integrity (SRI) check for jquery and other external resources if exist.

Example for jquery :

```HTML
<script src="https://code.jquery.com/jquery-1.12.4.min.js"
	     integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
             crossorigin="anonymous"></script>
```

>This allows browsers to ensure that resources hosted on third-party servers have not been tampered with. Use of SRI is recommended as a best-practice, whenever libraries are loaded from a third-party source.

For jquery the values are available in https://code.jquery.com/

**Comment by leofeyer** [comment]
We have to think about a good way to maintain the hashes though.

**Comment by Toflar** [comment]
It would be just another attribute on the resource. Resource collection for HTML output should be a service. Something like this:

```php
interface ResourceCollectionInterface
{
   public function addResource(ResourceInterface $resource);
   public function getResources();
}


interface ResourceInterface {}

interface HtmlResourceInterface
{
    public function getAsHtml();
}
```

So the page type would do sth like this:

```php
$head = '';

foreach ($this->resourceCollection as $resource) {
    if ($resource implements HtmlResourceInterface) {
        $head .= $resource->getHtml();
    }
}

$template->head = $head;
```

The JS resource could then look like this:

```php
class Javascript implements HtmlResourceInterface
{
    public function setAsync();
    public function setIntegrity($integrity);
    // etc.

    public function getHtml()
    {
        return '<script src="...async...integrity...crossorigin...>';
    }
}
```

**Comment by leofeyer** [comment]
+1, although that is not what I meant. I was thinking about this:

```php
$mapper = [
    'jquery' => [
        // …
        '1.12.4' => 'sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=',
    ],
    'mootools' => [
        // …
    ],
];
```

We need the hashes for every version that can be installed via `contao-components/*`. Maybe we can add the hashes to the `extra` section of the `composer.json` file?

**Comment by Toflar** [comment]
Leaving this for the record: Puli might solve this issue.

**Comment by leofeyer** [comment]
I don't think so. Puli does handle [ResourceMetadata](http://api.puli.io/latest/class-Puli.Repository.Api.Resource.ResourceMetadata.html), however this relates to local files and not remote resources from a CDN.

**Comment by Toflar** [comment]
You can add any resource provider you want, providing any type of resource you like, consumed by and consumer you wish ;)

**Comment by xchs** [comment]
The integrity hashes could be obtained by e.g.
```
 curl -s https://code.jquery.com/jquery-3.2.1.min.js | openssl dgst -sha256 -binary | openssl base64 -A
```
although I'd prefer hashes with a sha384 hash function.

I think it is also important to add an `crossorigin="anonymous"` attribute so that there will be no exchange of sensitive data via cookies etc.

**Comment by aschempp** [comment]
Calculating them by download does not really make sense. If the resource was tampered with, the hash will still be valid…

**Comment by xchs** [comment]
That's right. However, I would add those integrity hashes also to self-hosted scripts.

**Comment by leofeyer** [comment]
As discussed in Mumble on August 30th, we could add the SHA in the `composer.json` file of each release and use it if present.

**Comment by leofeyer** [comment]
I have found a maintenance free way to add the SRI hash when loading jQuery from CDN in 65a878ddbd7e156c1e1dd1056cb900d2d5ac2e28. It does not work for MooTools, because we are shipping our own build, but MooTools is dead anyways. At least we have the `crossorigin="anonymous"` attribute added for MooTools (and jQuery of course).

**Comment by aschempp** [comment]
Really? Calculating the hash of the file on **every** request? Also, calculating the hash from a local file for the remote, CDN file?

**Comment by leofeyer** [comment]
> Calculating the hash of the file on every request?

We should probably re-think this.

> Also, calculating the hash from a local file for the remote, CDN file?

Both files should be the same, so this seems correct to me.

**Comment by leofeyer** [comment]
>> Calculating the hash of the file on every request?
>
> We should probably re-think this.

Is this really a problem? We do have a cache after all.

**Comment by aschempp** [comment]
> Both files should be the same, so this seems correct to me.

well don't we have our own fork of everything?
Honestly, I don't understand why anyone would use this feature anyway…
