### ISSUE TITLE
mod_password & mod_change_password

### ISSUE THREAD

**Issue by jedoStyle** [contao/core-bundle#704]
customTPL is not working on Contao 4.3.4.

the dropdown is empty

![screenshot at feb 12 12-15-29](https://cloud.githubusercontent.com/assets/1821865/22861597/0cb297b2-f11d-11e6-922d-d7f6649b9d62.png)

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by jedoStyle** [comment]
- install contao 4.3.4
- add a password or change_password module
- select a custom template (it's empty)

- contao installieren
- theme und layout erstellen
- module hinzufügen (hier ist die Auswahl bereits leer)

**Comment by jedoStyle** [comment]
Die Templates müssten heißen (in den klammern ist die aktuelle Bezeichnung):

mod_lostPassword.html5 (mod_password.html5)
mod_changePassword.html5 (mod_change_password.html5)

**Comment by leofeyer** [comment]
Hast Du denn ein eigenes Template angelegt? Und wenn ja, wie hast Du es benannt?

**Comment by jedoStyle** [comment]
nein ich habe kein eigenes angelegt, da diese nicht abgefragt werden. in meinen letzten post stehen in den klammern die Bezeichnungen, die in den Modulen hinterlegt sind.

diese werden aber nicht geladen, auch nicht wenn man eigene nutzt.

das was vor den klammen steht müsste die eigentliche Bezeichnung sein, damit es wieder funktioniert, aber das ist nur eine Vermutung

**Comment by leofeyer** [comment]
Beim Testen ist mir aufgefallen, dass das Problem auch mit den Newsletter-Modulen besteht. Wir sollten also einmal alle Module und Inhaltselemente prüfen.

**Comment by leofeyer** [comment]
Folgendes müssen wir ändern:

**Custom Navigation**

Die individuelle Navigation nutzt aktuell das Template `mod_navigation`, sollte aber `mod_customnav` nutzen, damit das Template ausgewählt und überschrieben werden kann.

**Change Password**

Das Modul "Passwort ändern" nutzt das Template `mod_change_password`, sollte aber `mod_changePassword` nutzen.

**Lost Password**

Das Modul "Passwort vergessen" nutzt das Template `mod_password`, sollte aber `mod_lostPassword` nutzen.

**Close Account**

Das Modul "Konto schließen" nutzt das Template `mod_password`, sollte aber `mod_closeAccount` nutzen.

**Module Comments**

Das Kommentarmodul nutzt das Template `ce_comments`, sollte aber `mod_comments` nutzen.

Ich würde gerne alle Änderungen bis zum nächsten Feature-Release (Contao 4.4) aufschieben, da es zwar grundsätzlich Bugfixes sind, aber sie ggf. Auswirkungen auf angepasste Templates haben.

**Comment by Toflar** [comment]
> Ich würde gerne alle Änderungen bis zum nächsten Feature-Release (Contao 4.4) aufschieben, da es zwar grundsätzlich Bugfixes sind, aber sie ggf. Auswirkungen auf angepasste Templates haben.

Approved.

**Comment by jedoStyle** [comment]
ich konnte kein Template anpassen, da dieses nicht geladen bzw. zur Auswahl steht. Das bezieht sich aber nur auf die beiden Passwort-Module, die anderen nutze ich selber nicht.

**Comment by leofeyer** [comment]
Geändert in a4e7ab8c3ac332a9563c46ab7e52e3f98f5d5c57.
