### ISSUE TITLE
prepareMetaDescription reduce max length to 160

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#706]
Since the prepareMetaDescription is meant for Meta Descriptions, it should resemble the currently recommended max lengths for search engines.
I know that they vary, but almost all of them are below 160 symbols.. So I guess the Line 595 in Frontend.php should be 

$strText = \StringUtil::substr($strText, 160);

https://github.com/contao/core-bundle/blob/7f746f41156f81867aefbb812f5e086e543d5bdd/src/Resources/contao/classes/Frontend.php#L595

**Comment by leofeyer** [comment]
I don't see any reason to enforce a length limit on people here, so -1 from me.

**Comment by christianromeni** [comment]
Well, you are already doing it by limiting it to 180 .. So why not limit it to some sort of standard then?
Otherwise, remove the limit completely... Following your logic.

**Comment by leofeyer** [comment]
Ah, I got you wrong, sorry. Reducing the limit might be ok. Let's see what other people think about it, ok? @contao/developers /cc

**Comment by discordier** [comment]
Ich kenne mich mit dem Thema nicht wirklich aus und muss mich daher relativ enthalten, [sistrix](https://www.sistrix.de/frag-sistrix/onpage-optimierung/meta-element-meta-tag/wie-sieht-die-optimale-meta-description-aus/) hingegen empfiehlt:
> - nicht mehr als 156 Zeichen (inkl. Leerzeichen)
>   - mehr als 156 Zeichen werden durch (…) abgeschnitten
> - verfügt die Webseite über ein “veröffentlicht am” Datum oder eine Produktauflistung (1 – 25 von 250) so wird dies mit Wahrscheinlichkeit als Teil der Meta-Description vorangestellt angezeigt
>   - sollte dies der Fall sein, so empfiehlt es sich, nicht mehr als 139 Zeichen (inkl. Leerzeichen) zu verwenden

Und:
> Technisch gesehen wird die maximale Länge einer Meta-Description seitens Google nicht durch die Anzahl der Zeichen bestimmt, sondern auf Pixelbasis berechnet. Auf einer Breite (engl. width) von ~ 500 Pixel lässt sich die Meta-Description unterbringen.

Das werden wir aber sicher nicht berechnen (koennen und wollen).

Ich bin also mit beidem zufrieden, ob wir es aendern oder belassen.

**Comment by ausi** [comment]
I’m OK with both limits, 160 and 180. But I think it’s insignificant if Contao or the search engine cuts the text. AFAIK this method is not used for meta descriptions from `tl_page` but for things like generating a meta description from a news teaser text.

**Comment by Toflar** [comment]
This is something I expect Contao to just do correctly out of the box. It's not a technical question so I don't really care :-D If the SEO people can agree on a length, then we can adjust it.

**Comment by aschempp** [comment]
I don't like the limit. Of what use is a meta description if the user entered 300 chars because he didn't know? Then half of his words would be lost and noone will notice. 
It should rather be in die field description, same as it is in tl_page if I remember correctly.

**Comment by christianromeni** [comment]
It is used primarily when there is no field for entering a meta description, like in news or custom modules...
It is true that search engines cut the end when displaying.. But they notice and mark as negative if the description is too long. Otherwise I think most SEO Tools would not recommend the length to be below 160.
So when having no input field for description, it should just cut it at the right place... And, in the meta description field in tl_page, there is a hint as well:
"Hier können Sie eine kurze Beschreibung der Seite eingeben, die von Suchmaschinen wie Google oder Yahoo ausgewertet wird. Suchmaschinen indizieren normalerweise zwischen 150 und 300 Zeichen."
Maybe this should be changed as well to suite the current commonly used limits..

**Comment by ausi** [comment]
> It is true that search engines cut the end when displaying.. But they notice and mark as negative if the description is too long.

I don’t think this is true. Do you have an official statement from Google or Bing that verifies this?

But as already said, im OK with reducing the limit to 160, so I think we should just change it to end this discussion.

**Comment by bytehead** [comment]
I'm fine with reducing the limit as well.

**Comment by christianromeni** [comment]
> I don’t think this is true. Do you have an official statement from Google or Bing that verifies this?
No, that was an assumption based on the many tools that state the limit.

**Comment by DanielSchwiperich** [comment]
Shouldn't this be a config value? Set it as default to 160 in the Configuration.php, but so it can be overwritten for example in a Russian standard edition optimised for Yandex or Chinese / Baidu.

**Comment by leofeyer** [comment]
Changed in 0e6407d6b9fd212318f532c825a0be09e2aa2c7c.
