### ISSUE TITLE
symlink to public folder remains after folder is deleted

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#710]
Reproduction:

1. Go to _File manager_.
2. Create a new folder and make it public.
3. There should be a symlink to that folder within `/web/files` now.
4. Delete the folder in the _File manager_ again.

The symlink in `/web/files` remains, at least under Windows 10, PHP 7.1.1 (FastCGI). The reproduction was done with the `contao/standard-edition` `4.3.5`.

**Comment by de-es** [comment]
Falls es zur Eingrenzung beiträgt, hier unter Win7, PHP 7.0.16 (FastCGI / x64) funktioniert es einwandfrei.

**Comment by leofeyer** [comment]
Fixed in 9fb5b9ef304327f03e67b1a98a58891cd3574d24.
