### ISSUE TITLE
Move installation related code to the installation bundle

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#711]
* `Contao\CoreBundle\Composer\ScriptHandler::generateRandomSecret()`
* `Contao\CoreBundle\Composer\ScriptHandler::addDirectories()`

I am thinking about moving these classes and the related commands into the installation bundle. @contao/developers Any objections?

**Comment by aschempp** [comment]
Why would you do that? It would no longer be possible to install Contao without having the installation bundle. Currently I only need it for the graphical UI, which I don't need when using `contao.localconfig` config and Doctrine Migrations.

**Comment by ausi** [comment]
I think @aschempp is right. Once the installation bundle becomes obsolete we will still need these methods.

**Comment by leofeyer** [comment]
> It would no longer be possible to install Contao without having the installation bundle

Actually, this sentence says it all. To install Contao, you need the installation bundle. 😄

**Comment by aschempp** [comment]
That is not correct. You need it to have the UI, but I can add DB using migrations and a user with the commands.

**Comment by Toflar** [comment]
The installation bundle must die, yes.

**Comment by aschempp** [comment]
Another zwo points. 

1. The installation bundle will be obsolete with the Manager, but the command will not

2. if it would be necessary to have the installation-bundle to run Contao, it should be part of the core.
