### ISSUE TITLE
Dateiverwaltung: Meta-Felder

### ISSUE THREAD

**Issue by pressi** [contao/core-bundle#717]
Hallo!

Im Backend ist es jetzt zwar möglich ein neues Meta-Feld hinzuzufügen für eine Sprache.

Auszug aus dem dca > tl_files.php > Feld: meta > eval (Zeile #221):
```
'metaFields'=>array('title'=>'maxlength="255"', 'alt'=>'maxlength="255"', 'link'=>'maxlength="255"', 'caption'=>'maxlength="255"'
```

Die Ausgabe eines neuen Feldes funktioniert aber nicht.
In der Controller.php, Funktion: addImageToTemplate sind die Felder hardcoded hinterlegt (Zeile #1605):
```
$objTemplate->src = TL_FILES_URL . $src;
$objTemplate->alt = \StringUtil::specialchars($arrItem['alt']);
$objTemplate->title = \StringUtil::specialchars($arrItem['title']);
$objTemplate->linkTitle = \StringUtil::specialchars($arrItem['linkTitle'] ?: $arrItem['title']);
$objTemplate->fullsize = $arrItem['fullsize'] ? true : false;
$objTemplate->addBefore = ($arrItem['floating'] != 'below');
$objTemplate->margin = static::generateMargin($arrMargin);
$objTemplate->caption = $arrItem['caption'];
$objTemplate->singleSRC = $arrItem['singleSRC'];
$objTemplate->addImage = true;
```

Und was auch noch gut wäre ist wenn nicht nur input's möglich wären als Felder, sondern auch z.B. eine textarea oder für das Link-Feld der Link-Wizard zum auswählen von einer Seite oder einer anderen Datei (PDF's bei Bildern z.B.).

Liebe Grüße
pressi

**Comment by fritzmg** [comment]
You simply need to fetch the meta data yourself with `\FilesModel::findBy…`.

**Comment by pressi** [comment]
Ja aber im ce_image und gallery_default Template wäre es ja einfacher wenn solche Felder bereits dabei wären und man nicht extra wieder das ganze Bild hereinladen müsste damit man die restlichen Meta-Felder bekommt.

**Comment by Toflar** [comment]
Hat mich auch schon genervt. 👍

**Comment by leofeyer** [comment]
Behoben in 0fb2a8939cdd6be4c1e3b365ff5d4d8ec52faa0e.
