### ISSUE TITLE
Hint overlays text with multiple external style sheets

### ISSUE THREAD

**Issue by hanski** [contao/core-bundle#722]
If you select multiple external style sheets in a page layout, a hint to re-order them is displayed. This hint overlays the text from the line above.

also present in Contao 3.5
![contao_stylesheets](https://cloud.githubusercontent.com/assets/2739020/23751852/63d09f66-04d3-11e7-9c38-00a3e5e43267.png)

**Comment by leofeyer** [comment]
Fixed in 23d8ec4669c8007cd816a92635f4d2612a5e299d.
