### ISSUE TITLE
Install tool cannot handle comma in default value

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#723]
`varchar(255) NOT NULL default ','` will break the install tool.

Background information:
 - The install tool allows to execute each field update individually
 - The Doctrine schema tool reports one query for all fields (`ALTER TABLE tl_content ADD COLUMN foobar INT NULL, ADD COLUMN bar INT NULL`)

Due to this the install tool currently splits the query by comma and re-creates individual update queries. Which obviously fails if a comma is somewhere else than expected.

**Comment by Toflar** [comment]
This should actually go to the installation-bundle and should be easily fixable with look-ahead and look-behind assertions. Try this: https://github.com/contao/installation-bundle/pull/45

**Comment by leofeyer** [comment]
Thank you @Toflar.
