### ISSUE TITLE
Language in URL

### ISSUE THREAD

**Issue by Chibko** [contao/core-bundle#724]
Hello,

In CONTAO 3.5, we had a checkbox in the tab settings : "Add the language to the URL"

I can't see this checkbox in CONTAO 4.3.5 managed edition. I have look if this option has been moved to the root page settings. No…

So, now in CONTAO 4.3.5, the language string is always added to the page URL ? even if there is just one website root ? It's a bit annoying…

**Comment by fritzmg** [comment]
> I can't see this checkbox in CONTAO 4.3.5 managed edition. I have look if this option has been moved to the root page settings. No…

You need to add
```yaml
    prepend_locale: false
```
to your `parameters.yml`. You need to delete the production cache afterwards, either by hand or by running
```
vendor/bin/contao-console cache:clear -e=prod
```
In the future all this can be done with the Contao Manager, presumably.

> So, now in CONTAO 4.3.5, the language string is always added to the page URL ? even if there is just one website root ? It's a bit annoying…

The default behaviour has changed in the `managed-edition`, yes: https://github.com/contao/manager-bundle/commit/5477fda5469e19d7df5451933815be49f5d661cd

**Comment by Chibko** [comment]
OK, thank you very much !
I see that the default behaviour is now the enable this option. It's not my choice because when i have a multilingual website, I always use the localized domain name. Contao is multilingual but also multi domains !
- www.mywebsite.fr for the French version
- www.mywebsite.fr for English version
- www.mywebsite.es for spanish version
- …
 I think it's better for SEO. Btw, it's ok for me now that i can disable the feature. Thanks again.

**Comment by fritzmg** [comment]
Yes, well, see the discussion I linked :)
