### ISSUE TITLE
Drop popupWidth and popupHeight

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#727]
We are currently using `popupWidth` and `popupHeight` to calculate the size of the modal window in the file manager. However, we are always showing the modal window in full height as of Contao 3.5.25 due to https://github.com/contao/core/issues/8631, so we actually do not need `popupWidth` and `popupHeight` anymore.

I would like to drop them entirely in Contao 4.4, because calculating the width and height of **every** image in the file tree is quite expensive – especially if the results are no longer used.

@contao/developers Any objections?

**Comment by aschempp** [comment]
Can you point to the code where `popupWidth` and `popupHeight` are used? I can't see a reason not to drop it.

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/search?utf8=%E2%9C%93&q=popupHeight 😄

**Comment by Toflar** [comment]
I don't see why we'd need this really...

**Comment by aschempp** [comment]
Clever you, I guess we can remove it 😛

**Comment by leofeyer** [comment]
Removed in 71c292be35b912372ada966e8b861c0ddf4f6121.
