### ISSUE TITLE
error page shown together with regular page on fatal error in insert tag

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#731]
If a fatal error occurs within an insert tag, the error page will be generated, but sent together with the regular page to the browser.

### Reproduction:

1. Create an HTML content element and insert `{{file::test.php}}`.
2. Create a file called `test.php` within `/templates` and generate a fatal error within, e.g. `<?php $foo = new Foo();` (assuming there is no class `Foo` loaded 😉).
3. Visit the page in the front-end (_not_ via `app_dev.php`).

### Result:

If you look at the source (or response), you will see the regular page, plus the error page:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Start - Website</title>
  <base href="http://c43.dev/">
  <meta name="robots" content="index,follow">
  <meta name="description" content="">
  <meta name="generator" content="Contao Open Source CMS">
  <!--[if lt IE 9]><script src="assets/html5shiv/js/html5shiv-printshiv.min.js"></script><![endif]-->
</head>
<body id="top" class="win firefox gecko fx52" itemscope itemtype="http://schema.org/WebPage">
  <div id="wrapper">
    <div id="container">
      <main id="main" itemscope itemtype="http://schema.org/WebPageElement" itemprop="mainContentOfPage">
        <div class="inside">
          <div class="mod_article first last block" id="article-1">
<!DOCTYPE html><html><head><meta charset="utf-8"><title>    An error occurred …
```
If you visit the front-end via `app_dev.php`, everything is fine (only the error page is generated and sent).

**Comment by Toflar** [comment]
This is due to the ESI request. Not sure how to handle this properly yet but I'll have a look at it somewhen.

**Comment by fritzmg** [comment]
Are all insert tags handled via ESI now, not just the "uncached" ones?

**Comment by Toflar** [comment]
`{{file::` is an uncached one ;)

**Comment by aschempp** [comment]
If I remember correctly, ESI has handling suggestions for http status codes.

**Comment by fritzmg** [comment]
Ah, I though that `{{file::….html5/php}}` is not an uncached one in Contao 4 anymore, due to this problem: https://github.com/contao/core/issues/8658
@aschempp thought it was changed in Contao 4 (https://github.com/contao/core/issues/8658#issuecomment-283910850) but apparently that is not the case.

**Comment by Toflar** [comment]
> If I remember correctly, ESI has handling suggestions for http status codes.

No.

> Ah, I though that {{file::….html5/php}} is not an uncached one in Contao 4 anymore, due to this problem: contao/core#8658

No idea what you're talking about, but the result of a `{{file::<path}}` insert tag must never be cached because we don't know what it does. And it's not so this is correct.

I just need to figure out what to do in case of an error. Probably just show the response but I know the HttpCache SF reverse proxy does check for status code `200` so I really need to dig into this. But not now.

**Comment by fritzmg** [comment]
> but the result of a {{file::<path}} insert tag must never be cached because we don't know what it does

But that is exactly why you must not remove that decision from the user/developer. Currently Contao enforces the `uncached` behavior on __all__ `{{file` insert tags, even if it is a `{{file::PATH}}` insert tag. However, the script behind `{{file::PATH}}` might need data that is not available in the cached environment.

Consider the following example:

1. Create a file named `foo.php` within `/templates`, with the following content: [1]
2. Create an HTML content element and insert `{{file::foo.php}}`.
3. Activate the page cache.
4. Open the front end without being logged into the back end. You will see `string(1) "1"`.
5. Reload the page. You will see `NULL`.

(Tested in Contao `4.3.6`)

[1]
```php
<?php

global $objPage;

var_dump($objPage->layout);
```

The user has no chance but to __not__ use the `{{file` insert tag in this case, if he wants to use the page cache, since _all_ `{{file` insert tags are enforced to be `uncached`.

If instead only `{{file::UUID}}` insert tags are `uncached` by default and `{{file::PATH}}` insert tags are not, you could still make them uncached with `{{file::PATH|uncached}}` whenever necessary. This would also be more intuitive and in line with the official documentation.

This is also explained in https://github.com/contao/core/issues/8658

**Comment by Toflar** [comment]
We could do that, yes.

**Comment by leofeyer** [comment]
What needs to be done here @fritzmg and @Toflar?

**Comment by Toflar** [comment]
@fritzmg should make a PR, I think that would be the best because he discovered the issue ;)

**Comment by fritzmg** [comment]
Well, we were discussing two different things here:

_Uncached insert tags being replaced with the contao error page, if an error occurs within them._

This is the original issue and described in the first post. I won't be able to provide a PR for that, due to lack of experience with edge side includes in general and the framework handling this part 😉 

_`{{file::PATH}}` insert tags always being uncached._

This is a follow up to this issue. Having this insert tag always being uncached (with no choice) can be problematic (see [here](https://github.com/contao/core/issues/8658#issuecomment-283900502) for example). I could provide a PR for that, I guess.

**Comment by fritzmg** [comment]
@leofeyer: me and @Toflar discussed this in IRC and we came to two conclusions: 

* the error being shown within the rest of the page response is normal
* `{{file::PATH}}` insert tags should not be forced to be `uncached` » #801
