### ISSUE TITLE
C4: Database::getInstance() für externe Datenbank?

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#733]
Hallo zusammen,

ich versuche gerade, eine Verbindung zu einer externen Datenbank aufzubauen:

```
class Foo extends \Backend
{
    public function bar()
    {
        $db = \Database::getInstance(array(
            'host' => 'foo',
            'user' => 'foo',
            'password' => 'foo',
            'dbname' => 'foo'
        ));
    }
}
```

bekomme aber nur die Fehlermeldung

> "The parameter "database_driver" must be defined."

In der 

> library/Contao/Database.php

 steht im Konstruktor:

```
$arrParams = array
(
    'driver'    => \System::getContainer()->getParameter('database_driver'),
    [...]
);
```

Ich finde aber weder in den Configs noch sonstwo im Code 'database_driver'.
Mache ich etwas falsch oder ist das ein Bug?

**Comment by aschempp** [comment]
Du solltest dafür Doctrine nutzen, und nicht die alte Contao Datenbank-Klasse.

**Comment by pgerundt** [comment]
Sorry, ich stehe gerade auf dem Schlauch.

Hier ist scheinbar die Vorgehensweise bis 4.0 beschrieben:
[https://github.com/contao/core-bundle/commit/016d9b6768fb89a86ef425263a61be6a8f1b010e](https://github.com/contao/core-bundle/commit/016d9b6768fb89a86ef425263a61be6a8f1b010e)

Aber wozu gibt es dann bei `Database::getInstance()` den Parameter `$arrCustomConfig` ?

Und die UPGRADE.md besagt:

```
### Custom database drivers

The database classes have been mapped to the Doctrine DBAL, therefore custom
drivers are no longer supported. If you have been using a custom driver for a
database other than MySQL, use the corresponding Doctrine driver instead.
```

Aber ich will ja MySQL - nur eben nicht auf die Contao-Datenbank...

**Comment by aschempp** [comment]
Die Database-Klasse stammt aus Contao 3, ist aber deprecated. 

http://symfony.com/doc/current/doctrine/dbal.html

**Comment by fritzmg** [comment]
> Die Database-Klasse stammt aus Contao 3, ist aber deprecated.

Weder in [DEPRECATED.md](https://github.com/contao/core-bundle/blob/master/DEPRECATED.md) noch direkt in [Database.php](https://github.com/contao/core-bundle/blob/4.3.7/src/Resources/contao/library/Contao/Database.php) ist `Contao\Database` als deprecated gekennzeichnet.

Einzig und allein die Verwendung von `$arrConfig` im Konstruktor ist als deprecated gekennzeichnet: [Database.php#L71-L87](https://github.com/contao/core-bundle/blob/4.3.7/src/Resources/contao/library/Contao/Database.php#L71-L87)
```
Passing a custom configuration to Database::__construct() has been deprecated and will no longer work in Contao 5.0.
```

**Comment by fritzmg** [comment]
Das Problem kann ich auf jeden Fall bestätigen. Generell führt der Aufruf
```php
\System::getContainer()->getParameter('database_driver');
```
zu folgendem Fehler:
```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException:
The parameter "database_driver" must be defined. in /var/cache/prod/appProdProjectContainer.php:3379
```

**Comment by fritzmg** [comment]
@pgerundt du musst einfach nur zusätzlich
```yml
    database_driver: pdo_mysql
```
in deiner `parameters.yml` einfügen und danach den production cache löschen, dann funktioniert (logischerweise) der Aufruf
```php
\System::getContainer()->getParameter('database_driver');
```

**Comment by leofeyer** [comment]
> Das Problem kann ich auf jeden Fall bestätigen. Generell führt der Aufruf
>```php
>\System::getContainer()->getParameter('database_driver');
>```
>zu folgendem Fehler:

Das ist ja auch komplett falsch. Wie @aschempp schon geschrieben hat, sollst Du eine zweite Doctrine-Connection erstellen und diese dann mittels `System::getContainer()->get('doctrine.dbal.custom_connection');` vom Container holen.

**Comment by fritzmg** [comment]
> Das ist ja auch komplett falsch.

Der Code kommt ja nicht von mir, sondern von Contao ;) » https://github.com/contao/core-bundle/blob/4.3.7/src/Resources/contao/library/Contao/Database.php#L78
```php
	/**
	 * Establish the database connection
	 *
	 * @param array $arrConfig The configuration array
	 *
	 * @throws \Exception If a connection cannot be established
	 */
	protected function __construct(array $arrConfig)
	{
		// Deprecated since Contao 4.0, to be removed in Contao 5.0
		if (!empty($arrConfig))
		{
			@trigger_error('Passing a custom configuration to Database::__construct() has been deprecated and will no longer work in Contao 5.0.', E_USER_DEPRECATED);
			$arrParams = array
			(
				'driver'    => \System::getContainer()->getParameter('database_driver'),
				'host'      => $arrConfig['dbHost'],
				'port'      => $arrConfig['dbPort'],
				'user'      => $arrConfig['dbUser'],
				'password'  => $arrConfig['dbPass'],
				'dbname'    => $arrConfig['dbDatabase']
			);
			$this->resConnection = DriverManager::getConnection($arrParams);
		}
		else
		{
			$this->resConnection = \System::getContainer()->get('database_connection');
		}
		if (!is_object($this->resConnection))
		{
			throw new \Exception(sprintf('Could not connect to database (%s)', $this->error));
		}
	}
```
Da die Benutzung von `Database::__construct($arrConfig)` aber ohnehin deprecated ist reicht es wohl, wenn irgendwo dokumentiert ist (wenn auch nur durch dieses Ticket), dass man
```yml
    database_driver: pdo_mysql
```
in der `parameters.yml` benötigt.

**Comment by aschempp** [comment]
aaah, das ist tatsächlich ein Bug. Da müsste einfach `pdo_mysql` stehen, denn etwas anderes unterstützt die DB-Klasse sowieso nicht.

**Comment by fritzmg** [comment]
Oder man nimmt den `driver` der default connection, damit es nicht hard codet sein muss. Vielleicht war das auch die ursprüngliche Absicht?

**Comment by aschempp** [comment]
wie gesagt, das macht keinen Sinn weil es sowieso nicht funktioniert. Die "ursprünglich Absicht" basiert auf einer Version die gar nie funktioniert haben kann ;)

**Comment by fritzmg** [comment]
Was genau funktioniert nicht? Wenn man den `database_driver` Parameter setzt funktioniert ja das aufbauen der Datenbank Verbindung mit `Database::getInstance($arrConfig)`.

**Comment by pgerundt** [comment]
Hallo zusammen,

ich habe mich in den letzten Stunden etwas zurückgehalten, weil mich die "Das-ist-sowieso-deprecated"-Aussagen ein klein wenig echauffiert haben - aber nix für ungut.

Nur zur Vollständigkeit: Um eine Datenbankverbindung zu einer "fremden" Datenbank aufzubauen, kann man nun entweder

- auf die 4.3.8 warten
- den Eintrag `database_driver: pdo_mysql` in der `parameters.yml` machen und `Database::getInstance($arrConfig)` nutzen
- die `Database.php` modifizieren und statt `\System::getContainer()->getParameter('database_driver')` hartkodiert `pdo_mysql` setzen
- in der `parameters.yml` eine zweite Verbindung anlegen und diese per `System::getContainer()->get('doctrine.dbal.custom_connection')` nutzen (**empfohlener Weg, da alles andere deprecated**)

Somit wäre dieser Bug und der empfohlene Lösungsweg für mich hinreichend dokumentiert. Danke an alle Beteiligten.

**Comment by fritzmg** [comment]
> in der parameters.yml eine zweite Verbindung anlegen

In der `/app/config.yml` :)

**Comment by pgerundt** [comment]
Fast. `/app/config/config.yml`, oder? Aber danke, ich habs korrigiert.

**Comment by fritzmg** [comment]
Jap, sorry.

**Comment by leofeyer** [comment]
Behoben in 63402099ce56a6c61a46e908697aafa9052993fa.
