### ISSUE TITLE
Externe Stylesheets lassen sich nicht zum Layout hinzufügen 4.3.6

### ISSUE THREAD

**Issue by Ainschy** [contao/core-bundle#734]
Hi,
bei dem Versuch externe CSS / SCSS Dateien im Layout hinzuzufügen kann ich diese zwar auswählen, sie werden aber nicht hinzugefügt. Wenn ich diese zuvor in einem Ordner gelegt habe, den ich von der Synchronisierung ausschließen möchte.

TLDR;
Dateien (wie CSS/SCSS/LESS) die in Ordnern liegen die von der Synchronisierung ausgeschlossen sind, lassen sich nicht zum Layout hinzufügen.

Hintergrund:
In der Annahme das Layout Dateien nicht synchronisiert werden müssen, da sie nur Layout spezifische Definitionen enthalten, hatte ich den Ordner in den Ausnahmen eingetragen.

**Comment by leofeyer** [comment]
Diese Annahme ist falsch.

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/pages/PageRegular.php#L593
