### ISSUE TITLE
Filter and search still not working right in article module

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#739]
After the changes to fix #716 only the filtered articles are displayed. But if more than one article from a page fit the filtered argument, the same page is displayed multiple times.

Tested on a clean contao 4.3.7 installation.

Unfiltered article list:
![filter1](https://cloud.githubusercontent.com/assets/1402434/24394868/f418f568-139d-11e7-8669-0289df1fede3.jpg)

Filtered article lists:
![filter2](https://cloud.githubusercontent.com/assets/1402434/24394968/4091bcfe-139e-11e7-9efd-11b08b6d9ac9.jpg)

![filter3](https://cloud.githubusercontent.com/assets/1402434/24394985/4e1ce84e-139e-11e7-9e22-1f4cab136dca.jpg)

![filter4](https://cloud.githubusercontent.com/assets/1402434/24395142/ec8515c4-139e-11e7-98bb-29783af58d44.jpg)

And it would be useful if the filtered results will have the same sorting as the unfiltered.

**Comment by leofeyer** [comment]
Fixed in 015224712e12411604e104834013e110117c7c0a.
