### ISSUE TITLE
Adding a ArticleTree widget (like PageTree)

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#747]
I think to be able to select articles like pages (e.g. in the content element article and teaser) would be a big benefit!!

Currently there is only a simple select field to select articles. Very difficult to select an article when having a big page structure. And only the teaser element restricts the selection to the current root page tree.

I can start a PR for this, but I think I will need help from the core-team. After a quick try I realized, that this isn't a simple task..

Is this of interest (also for other extension developers)?

**Comment by Toflar** [comment]
> Is this of interest (also for other extension developers)?
In 9 years I have never ever had the need to pick a single article. I have never used this teaser feature so I cannot really help here.
But @leofeyer is working on a rather general picker solution for events, news etc. so maybe implementing this gets easier. You should maybe wait for this 😄

**Comment by agoat** [comment]
I don't use the content elements to insert article or teaser but I use to article select field in extensions (e.g. to select related articles or so).

> But @leofeyer is working on a rather general picker solution for events, news etc. so maybe implementing this gets easier.

That sounds interesting ..

**Comment by leofeyer** [comment]
> But @leofeyer is working on a rather general picker solution for events, news etc.

I am working on a rather specific picker for new and events only. We have already discussed and discarded implementing a general picker by adjusting the `DC_Table` class.

But at least my implementation will make it easier to add a custom link to the picker menu.

**Comment by asaage** [comment]
> I am working on a rather specific picker for new and events only.

👍 

FAQ & Articles should be added to cover all core-entities that provide a distinct url.

**Comment by leofeyer** [comment]
Feel free to create a pull request. 👍

**Comment by agoat** [comment]
> But at least my implementation will make it easier to add a custom link to the picker menu.

Will we have some general structure for tree/list picker functions?

I don't know the discussion about implementing a general picker and therefor not the reason to discard the implementation of a general picker. But I think a general method would be helpful. 
Currently the `TreePage` widget uses the `PageSelection` widget to generate the page tree. But the PageSelection is a customized duplication of what the DC_Table is generating for the page structure menu. For a ArticleTree picker we will have nearly the same, and also for news, events, a.s.o.

Is it possible to have some helper methods (render the tree view of different tables - page+article, news_archiv+news, calender+calendar_event)??

**Comment by leofeyer** [comment]
Implemented in #755.
