### ISSUE TITLE
True\Punycode auf Version 2 heben 

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#748]
Aus der Changelog:
```
    [Enhancement] PHP 7 support
    [Fix] Renamed True namespace to TrueBV as it is a reserved word in PHP 7
```

Achtung, der Namespace ändert sich, daher müsste hier dieser angepasst werden:
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Idna.php#L13

in 
`use TrueBV\Punycode;`

in composer.json dann
`true/punycode:~2.0`

_Ein weiterer Grund ist, dass eine Erweiterung von mir eine Lib nutzt, die von Punycode die 2.x benötigt, in Contao 4 führt das dann zum Konflikt._

Nachtrag: Der PHP 7 Grund ist wohl nicht eindeutig, aber die Aktualisierung wäre trotzdem wünschenswert. Es gibt auch weitere Bugfixe wie "Cannot decode domain in uppercase"

**Comment by BugBuster1701** [comment]
**Achtung**:
Punycode prüft neuerdings in der decode Methode ob die Parts des Parameters "between 1 and 63 octets," ist, wenn nein folgt eine Exception. siehe [Punycode.php#L176-L199](https://github.com/true/php-punycode/blob/master/src/Punycode.php#L176-L199)
Dadurch lässt sich System->Einstellungen nicht mehr aufrufen. (mit Punycode 2.x)
(Datei-URL wird mit leerem Parameter (default) versucht zu decodieren)

Ich musste daher folgendes anpassen in Idna::decode
```
        public static function decode($strDomain)
        {
                $objPunycode = new Punycode;

                return $objPunycode->decode($strDomain);
        }
```
wird zu 
```
        public static function decode($strDomain)
        {
                if ($strDomain == '')
                {
                        return '';
                }

                $objPunycode = new Punycode;

                return $objPunycode->decode($strDomain);
        }
```
bei Punycode->encode() wird das auch geprüft.

**Comment by leofeyer** [comment]
Aktualisiert in 1c6a5e76ec8ae54df247e2004e7f8504aa76289d.

**Comment by BugBuster1701** [comment]
Reopen oder neu anlegen? Du hast ja dankenswerterweise vor in die 4.4 wieder Punycode 2 zu integrieren.

**Comment by joergmoldenhauer** [comment]
As discussed in the forum (https://community.contao.org/de/showthread.php?66532-Elementtyp-Youtube-fehlerhaft) it might be a good idea not to use "rgxp" => "url" for youtube ids.

Suggestions from this forum thread for new eval options:
* "rgxp" => "youtubeid"
* "rgxp" => "realalnum" which is /^[[:alnum:]]*$/
* "rgxp" => "regex([a-zA-Z0-9]*)" (the part in brackets is a regex which can be set individually)
* no validation, instead just "urlencode" => true

**Comment by leofeyer** [comment]
Implemented in ca7545f715e46d72e2bf9095d6ac1f4dea1264e3.

**Comment by BugBuster1701** [comment]
Da es noch nicht in der Beta1 enthalten ist die Frage, kommt es mit der RC1?

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/blob/develop/CHANGELOG.md
