### ISSUE TITLE
cron.txt

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#753]
Die cron.txt wird nicht mehr im Template fe_page verwendet, jedoch wird sie weiterhin geschrieben. Ist das beabsichtigt?

Siehe ``/vendor/contao/core-bundle/src/Command/InstallCommand.php`` Zeile 72 und ``vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendCron.php`` Zeile 174.

**Comment by leofeyer** [comment]
@contao/developers Spricht irgendwas dagegen, die Funktion und die Datei zu entfernen?

**Comment by Toflar** [comment]
Imho nicht.

**Comment by aschempp** [comment]
Die hatten wir ja nur per Javascript ausgelesen um den Cron nicht auszuführen. Da dies jetzt aber über `kernel.terminate` läuft sollte das obsolete sein.

**Comment by leofeyer** [comment]
Entfernt in 76741770ca50f5cb47b4ce7da918a51b8d895f5f.
