### ISSUE TITLE
Don't allow upload of files into root folder

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#754]
Files uploaded into the root folder in the file manager are protected by default and can not be made public (because only folders will/can be symlinked). 

To make it easier and to avoid misunderstandings the upload of files should be only possible in folders and not directly to the root.

**Comment by asaage** [comment]
related: https://github.com/contao/core-bundle/pull/712

**Comment by leofeyer** [comment]
We have discussed this in Mumble on March 23rd (see #712) and agreed that there is no valid reason to prevent users from uploading files into the upload folder – even if they cannot be made public.
