### ISSUE TITLE
[4.4] Use kernel.project_dir and require Symfony 3.3

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#758]
http://symfony.com/blog/new-in-symfony-3-3-a-simpler-way-to-get-the-project-root-directory?utm_source=feedburner&utm_medium=twitter&utm_campaign=Feed%3A+symfony%2Fblog+%28Symfony+Blog%29

**Comment by leofeyer** [comment]
+1 for using `kernel.project_dir`.

@contao/developers Do we want to keep our `contao.root_dir` parameter or remove it in favor of `kernel.project_dir`? Theoretically, `contao.root_dir` allows us to place the Contao folders into a completely different folder – but who will ever do this?

**Comment by ausi** [comment]
I think we should get rid of `contao.root_dir` and use the `kernel.project_dir` instead.

**Comment by aschempp** [comment]
We should definitely not add `contao.root_dir` (which should only have been added in 4.4).

**Comment by leofeyer** [comment]
See #803.
