### ISSUE TITLE
contao/core-bundle 4.3.7: missing dependency

### ISSUE THREAD

**Issue by bytehead** [contao/core-bundle#760]
If you just require `contao/core-bundle` on a plain symfony 3.3-DEV installation, the `bin/console` fails with: 
`PHP Fatal error:  Class 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand' not found in /vendor/contao/core-bundle/src/Command/DoctrineMigrationsDiffCommand.php on line 26`.

Is there a missing dependency on `contao/installation-bundle` to run the `bin/console` properly?

**Comment by aschempp** [comment]
Do you use doctrine migrations? There's a compiler pass that should register or remove the command depending on the migrations bundle availability. Maybe you added `doctrine/migrations` but not the bundle?

**Comment by bytehead** [comment]
It's a barebone symfony 3.3-DEV installed via `symfony new test-project`. `doctrine/migrations` is not installed.

**Comment by aschempp** [comment]
Please debug the compiler pass to see why the command is added at all…

**Comment by sheeep** [comment]
> By default, Symfony will take a look in the Command directory of each bundle and automatically register your commands. 

http://symfony.com/doc/current/console/commands_as_services.html

To me, it sounds like Symfony is trying to auto-register this Command. The compiler pass is not yet called at the time the fatal error is thrown.

**Comment by sheeep** [comment]
Looks likely to me.

Dump every [`$file`](https://github.com/symfony/http-kernel/blob/master/Bundle/Bundle.php#L179) the `$finder` finds in `Bundle::registerCommands`. You'll find `DoctrineMigrationsDiffCommand.php` which will be used for doing the following:

```php
$r = new \ReflectionClass($class);
$r->newInstance();
```

This way the DoctrineMigrationBundle becomes a hard dependency of this bundle.

**Comment by leofeyer** [comment]
@sheeep Any updates? Version 4.3.8 will be released early next week.

**Comment by sheeep** [comment]
Looks like `synthetic:true` on the command service definition does not prevent the container to autoload the command, as `$container->has` will return false (which makes sense IMO). Providing a class solves this problem, but the command is not available if the migration bundle is present. I'm currently looking for a new way to circumvent the command registration.

**Comment by sheeep** [comment]
I think the easiest way to achieve this is to rename the Command class.

My suggestion:

* Rename `DoctrineMigrationsDiffCommand` to `DoctrineMigrationsDiffCommandTemplate`
* Remove the synthetic command definition in `service.yml`

It does work as intended, but I'm not sure how well this fits in your preferable way of registering commands. Any ideas? @contao/developers

**Comment by leofeyer** [comment]
Sounds reasonable to me. Let's see what @aschempp says. 😄

**Comment by aschempp** [comment]
Hmm, that sure would work. What also works is not making the service definition synthetic. Simply add the command class name, it should not matter as there is no tag and the service will never be loaded, right?

**Comment by sheeep** [comment]
> Simply add the command class name, it should not matter as there is no tag and the service will never be loaded, right?

This is correct. I verified it with my installation, and it works. However, the command can not be made private (`public: false`), which means it will show up in the list of available services in `debug:container` even though it serves no purpose. Worse than that, I guess if you try to use it, it will throw an error. I'm not exactly sure if I like that. :)

Nevertheless, I'll provide a PR for either variant if you tell me the way to go.

**Comment by aschempp** [comment]
idk, really. `Template` is not really correct as that class is actually used for the command if migrations is available. The dummy service is not ideal either, but I doubt anyone would actually use that? I mean every Symfony command will get a service name for no reason too…

**Comment by sheeep** [comment]
I can totally see that. What about overriding the `registerCommands` method in the `Contao\CoreBundle\ContaoCoreBundle` class to disable auto registering for this bundle? I mean, we register them in the `commands.yml` anyway.

**Comment by aschempp** [comment]
I think we discussed that and there were objections because the default Symfony behavior (adding a command is automatically registered) would no longer work :/
If all core commands are services, that would be a valid option for me too, dunno about @contao/developers

**Comment by backbone87** [comment]
all commands as services is super easy in symfony 3.3 with the new autoconfigure option

**Comment by leofeyer** [comment]
Fixed in 8b8416108b2fe4e0765f2e446f28cb0b15373d9c.

**Comment by fritzmg** [comment]
Due to the release of Symfony `3.3.0`, this problem also happens with the regular `contao/managed-edition` now. Reproduction:

1. Download Contao 4.3.10 from contao.org and extract.
2. Run `composer update` in the installation root.

You will see
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 4 installs, 8 updates, 0 removals
  […]
Writing lock file
Generating autoload files
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

Fatal error: Class 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand' not found in …/vendor/contao/core-bundle/src/Command/DoctrineMigrationsDiffCommand.php on line 26
PHP Fatal error:  Class 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand' not found in …/vendor/contao/core-bundle/src/Command/DoctrineMigrationsDiffCommand.php on line 26
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command.

```
Shouldn't this fix be back ported to `4.3.11` as well?

**Comment by K0NZ1** [comment]
contao `4.3.10` is not compatible with symfony `3.3` yet. Simply change in your project composer.json the line `"symfony/symfony": "^2.8|^3.0",` to `"symfony/symfony": "^2.8|<3.3",` and clear your var/cache folder before you run `composer update`

**Comment by ausi** [comment]
@K0NZ1 `^2.8|<3.3` is the same as `<3.3` and should not be used that way in this case I think. You can use `>=2.8,<3.3` instead.

**Comment by aschempp** [comment]
I think it should be `"symfony/symfony": "^2.8 <3.3",`, because `"^2.8|<3.3"` means *>2.8 OR <3.3* so 2.5 would be applicable because it's < 3.3

**Comment by ausi** [comment]
But `^2.8 <3.3` means `^2.8` AND `<3.3`, that would not work for `3.0.0` for example because it is not `^2.8`. 

`>=2.8,<3.3` should work AFAIK.

**Comment by fritzmg** [comment]
Or `~2.8 || 3.2.*` :Þ

**Comment by BugBuster1701** [comment]
Grad ne 4.3.10 damit zerschossen :-1: Wie bekomme ich die wieder ans Laufen?

**Comment by DanielSchwiperich** [comment]
temporär könntest du in deiner composer.json symfony 3.3 vermeiden. 
Z.b. mit
`"symfony/symfony": "3.2.9",`
oder
`"symfony/symfony": "3.2.*",`

und dann composer neu laufen lassen

**Comment by agoat** [comment]
This should be fixed for contao 4.3.x immediately!!
Either with the fix in 8b8416108b2fe4e0765f2e446f28cb0b15373d9c or a change in the composer.json.

If someone is making a composer update it will break contao.
And that will keep people from using contao 4 for sure.

**Comment by BugBuster1701** [comment]
# Bitte in die 4.3.11, im Forum zerschießt sich einer nach dem anderem die Managed Edition.

**Comment by BugBuster1701** [comment]
Danke.
