### ISSUE TITLE
Issue “Delete single files and empty folders“ for user groups

### ISSUE THREAD

**Issue by Balindil** [contao/core-bundle#764]
If I check “Delete single files and empty folders“ for user groups, login as a user of this group, then go to file manager, the red cross on empty folders isn't activ and I can't delete empty folders.

But if I try “Edit multiple“ I can check the folder and press button “Delete“.

**Comment by leofeyer** [comment]
Fixed in b99b796b1c7ca9f096fdddee995d0c34faa19259.
