### ISSUE TITLE
Möglichkeit, die Filter/Suchen etc. via Screenreader zu überspringen

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#769]
Aus dem aktuellen Barrierefreiheit-Test, den Heiko Kunert und ich mit der aktuellsten Contao 4-Version durchgeführt haben:

Für sehbehinderte und blinde Nutzer ist es mühsam, dass sie im Hauptbereich immer erst an den ganzen Filter-/Sortier-/Suchoptionen vorbeikommen müssen, bevor sie beim eigentlichen Inhalt sind. 

Es wäre für sie hilfreich, wenn es an dieser Stelle z.B. einen Sprunglink gäbe, mit der diese komplette form übersprungen werden könnte. Der Sprunglink sollte gleich nach der h1 von MAIN platziert sein und den Zielanker unmittelbar nach dem ersten form von MAIN haben.

**Comment by aschempp** [comment]
Ich kann mich erinnern dass mir ein Experte kürzlich erklärt hat dass man Sprunglinks nicht mehr machen sollte. Kann der Bereich nicht besser über eine Aria-Role (oder wie das heisst) angesprochen werden?

**Comment by NinaG** [comment]
Wenn es eine bessere Lösung gibt, sollte man auf diese setzen. Wenn keine bessere Lösung da ist, sind Sprunglinks weiterhin berechtigt.

Eine passende Landmark (role) gibt es imho an der Stelle nicht. Der gesamte Hauptbereich sollte sinnvollerweise (siehe anderes Ticket) mit einer role gekennzeichnet sein, aber ich wüsste nicht, wie man dann darin den ganzen Inhalt AUSSER die Filter/Sortierleiste nochmal mit einer universellen Landmark versehen sollte. Da müsste man schon was neues erfinden, wobei da a) eher umstritten ist und b) auch imho von Verschachtelungen der allgemeinen Landmarks abgeraten wird.

Eine Lösung die ich mit Heiko besprochen habe, wäre einfach eine generelle Überschrift an der Stelle unmittelbar nach der FORM. Dann könnten die Nutzer die Ebene damit direkt anvisieren. Aber da fiel mir keine sinnvolle Beschriftung ein, die universell funktioniert. Wenn jemandem etwas einfällt, wäre das wohl eine brauchbare Alternative für Screenreader-Nutzer.

**Comment by NinaG** [comment]
Wir könnten vielleicht eine region-Landmark einsetzen, die den Inhalt der Hauptspalte unterhalb der Filter-Sortierleiste umrahmt, da imho wirklich keine der sonst gängigen Landmarks dafür passt. Dabei müssen wir aber darauf achten, dass wir sie dann auch verpflichtend mit einem aussagekräftigen aria-Label versehen müssen (generell müssten wir dafür sorgen, dass die eingesetzten aria-Labels natürlich auch entsprechend der Backend-Sprache sinnvoll übersetzt werden).

Wir hätten da dann also z.B.
`<div role="region" aria-label="Aktionsbereich">...</div>`

Am perfektesten wäre sicher die Kombi aus Landmark + sichtbarer Überschrift, damit liefe es so:
`<div  role="region" aria-labelledby="foo">
  <h2 id="foo">Aktionsbereich</h2> ... </div> `

**Comment by aschempp** [comment]
Für mich gehören die Filter nicht zum Hauptbereich, sondern nur der echte Inhalt? Die Filter sind doch mehr eine Art Navigation welche entsprechend ausgeklammert werden sollte? Es gibt eine extra Aria Role "search" doch genau dafür?


Freundliche Grüsse

Andreas Schempp
terminal42 gmbh

**Comment by NinaG** [comment]
Du meinst also, den gesamten Hauptbereich als role="main" deklarieren und dann die erste FORM darin als role="search"? Wäre theoretisch eine Möglichkeit. Allerdings ist es fraglich, ob man die Inhalte der FORM wirklich semantisch korrekt mit einer role="search" markiert, schließlich ist die Suche nur ein kleiner Teil davon, während der Großteil vor allem eine Filteroption ist.

**Comment by NinaG** [comment]
Ich habe die Situation in einer Web Accessibility-Gruppe auf facebook mal genau beschrieben (also welche Funktionen es gibt und die bisherigen Gedankengänge dazu). Mal schauen, was die anderen Pros dazu denken :)

**Comment by NinaG** [comment]
Noch ein Nachtrag: Wenn wir die Sache mit den Landmarks ordentlich machen, können wir uns imho in der left-Spalte den unsichtbaren Sprunglink sparen.

**Comment by NinaG** [comment]
Zwischenmeldung: Es kommen interessante Ideen auf (bisher beteiligen sich u.a. Eric Eggert, Marco Zehe und Martin Stehle). Ergebnisse folgen, sobald wir das ausdiskutiert haben (soweit das geht ;-)).

**Comment by aschempp** [comment]
Ich würde den Aria-Begriff "search" nicht so eng sehen. Filter sind auch eine Möglichkeit nach etwas zu finden nach dem man sucht. Aber ich weiss natürlich nicht was die Spezifikation dazu sagt.

**Comment by leofeyer** [comment]
Erledigt sich dieses Ticket nicht sowieso durch #768?
