### ISSUE TITLE
Barrierefreiheit-Probleme mit Dropzone

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#770]
Aus dem aktuellen Barrierefreiheit-Test, den Heiko Kunert und ich mit der aktuellsten Contao 4-Version durchgeführt haben:

Dropzone ist ein sehr praktischer Uploader. Allerdings gibt es ein paar elementare Probleme, die die Sache für Screenreader-Nutzer sehr erschweren.

1.
Das Feld „Hier klicken ...“ wird dem Screenreader nicht als Aktivfeld (klickbar) angesagt, da es sich nur um ein DIV handelt. Es wäre am einfachsten, wenn zumindest der Text in einen BUTTON umgewandelt wird. Die normale Funktion bleibt erhalten (müsste nur wieder leicht per CSS umgestyled werden), aber das Feld ist nun auch für Screenreader-Nutzer erkennbar. Das wäre dann:
`<div class="dz-default dz-message"><button>Hier klicken oder Dateien ablegen</button></div>`

2.
Etwaige Fehler- oder Erfolgsmeldungen über dem Feld werden von Screenreader-Nutzern nicht bemerkt. Mittels Aria-Anweisungen könnten wir dem Screenreader mitteilen, dass es eine wichtige Meldung gab (ohne dass er den Fokus dorthin verschieben muss).
Hier gibt die WCAG2 eine schöne Info, wie man das macht: https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html und hier ergänzend von Mozilla ein Beispiel: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role
Abgesehen davon wäre es toll, wenn Contao generell so barrierefreier auf wichtige Meldungen hinweist (im ganzen Backend und toller Weise vielleicht auch bei Formularen im Frontend).

3. 
Ein ähnliches Problem gibt es dann noch mit den Upload-Leisten. Sehende Nutzer können visuell wahrnehmen, dass die Datei ausgewählt ist, sich im Upload-Prozess befindet und schlussendlich dann erfolgreich/nicht erfolgreich hochgeladen wurde. Die Screenreader-Nutzer bekommen davon nichts mit. Hier wäre möglicherweise auch der Alert-Hinweis brauchbar.

PS: Ich spreche der Einfachheit halber nur von Screenreadern, aber die ARIA-Lösungen wirken idealerweise für alle Arten von assistiven Technologien (AT).

**Comment by aschempp** [comment]
Dropzone scheint nicht barrierefrei zu sein, entsprechend müssten wir wohl einen alternativen Uploader finden…?

**Comment by NinaG** [comment]
Entweder das, oder wir bringen die notwendigen Modifikationen bei der Übernahme in Contao an. Wäre natürlich ein Aufwand für das Contao-Team, der bei Dropzone-Updates immer wieder anfiele. Alternativ würde ich notfalls vorschlagen, dass wir das Dropzone-Team deswegen ansprechen. Hier habe ich aber die Sorge, dass sie sich direkt verweigern oder das erst irgendwann(tm) machen. Solange wäre dieser Uploader dann nicht barrierefrei nutzbar. Wenn wir wenigstens den Standard-Uploader barrierefreier bekommen (siehe Ticket #771 ), wäre etwas Warten vertretbar. Mittelfristig müsste aber schon der primäre Uploader auch barrierefrei sein - und da die LTS-Version vor der Tür steht, wäre es natürlich wichtig, das dort noch reinzubekommen, sonst verschleppen wir es ewig.

**Comment by leofeyer** [comment]
Bitte nicht vergessen, dass DropZone ein alternativer Uploader ist. Der Standard-Uploader sollte diese Probleme nicht haben.

**Comment by leofeyer** [comment]
Ich schließe das Ticket zu Gunsten von #771. Wir sollten uns darauf fokussieren, den Standard-Uploader barrierefrei zu machen, damit dieser genutzt werden kann.

**Comment by NinaG** [comment]
Ich werde versuchen, den DropZone-Entwickler zu Verbesserungen zu bewegen. 
Und ja, wenn wir zumindest beim Standard-Uploader schnellstmöglich die Probleme beheben, wäre das schon eine sehr wichtige Verbesserung :)
