### ISSUE TITLE
Backend-Pagination barrierefreier auszeichnen

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#775]
Ich schlage für die be_pagination.html5 folgende Änderungen vor, damit sie für assistive Technologien (AT wie z.B. Screenreader) besser zugänglich ist:

Die Pagination sollte von einem NAV-Element umhüllt, sowie mit einer entsprechenden role und einem ARIA-Label versehen werden.

Im Template sähe das dann so aus:
```
<div class="pagination <?= $this->class ?>">

<nav role="navigation" aria-label="Pagination">
  <p><?= $this->total ?></p>
  <ul>
    <?php if ($this->hasFirst): ?>
      <li class="first"><a href="<?= $this->first['href'] ?>" class="first" title="<?= $this->first['title'] ?>"><?= $this->first['link'] ?></a></li>
    <?php endif; ?>
    <?php if ($this->hasPrevious): ?>
      <li class="previous"><a href="<?= $this->previous['href'] ?>" class="previous" title="<?= $this->previous['title'] ?>"><?= $this->previous['link'] ?></a></li>
    <?php endif; ?>
    <?= $this->items ?>
    <?php if ($this->hasNext): ?>
      <li class="next"><a href="<?= $this->next['href'] ?>" class="next" title="<?= $this->next['title'] ?>"><?= $this->next['link'] ?></a></li>
    <?php endif; ?>
    <?php if ($this->hasLast): ?>
      <li class="last"><a href="<?= $this->last['href'] ?>" class="last" title="<?= $this->last['title'] ?>"><?= $this->last['link'] ?></a></li>
    <?php endif; ?>
  </ul>
</nav>

</div>
```

// Aktualisiert, siehe nachfolgendes Kommentar von mir

**Comment by NinaG** [comment]
... hm, habe mir das gerade nochmal angeschaut. Verwechsle ich da gerade etwas? Ich dachte, es ist die Positionsbezeichnung im Backend, aber nun sehe ich im BE gerade, dass die Positionsbezeichnung direkt in der H1 gemacht wurde. Hatte das falsch zugeordnet.

An welcher Stelle kommt denn die obige Pagination zum Einsatz?

**Comment by cliffparnitzky** [comment]
gilt für Pagination z.B. in System-Log oder beim genügend Einträgen (> 30) auch Mitglieder, etc.

**Comment by leofeyer** [comment]
Siehe #869.
