### ISSUE TITLE
Adjust the `PageError404` class

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#78]
Adjust the `PageError404` class to the changes from contao/core#7666: https://github.com/contao/core/commit/4d3ef21fdd1a98d8443c2fa55a3c145c7929dedb

**Comment by aschempp** [comment]
You can probably use the catch-all alias for that (see #77)

**Comment by leofeyer** [comment]
Fixed in 09b25c6c7b130f68b1bc194f258a7c30ee30bb0b.
