### ISSUE TITLE
Drag'n'Drop-Icon für Screenreader ausblenden

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#780]
Das Drag'n'Drop-Icon (u.a. bei der Listenansicht der Inhaltselemente eines Artikels) macht für Screenreader-Nutzer keinen Sinn. Da es sowieso eine redundante Funktion ist (Screenreader-Nutzer können die normale Verschieben-Funktion an der Stelle nutzen), schlage ich vor, dass dieser Button vor Screenreadern komplett versteckt wird. Dann führt er auch zu keiner Irritation.

Statt bisher:
`<button type="button" class="drag-handle" title="Inhaltselement ID 1 verschieben"><img src="system/themes/flexible/icons/drag.svg" width="16" height="16" alt=""></button>`

Wäre das dann mit dem Attribut **aria-hidden="true"**:
`<button type="button" class="drag-handle" title="Inhaltselement ID 1 verschieben" aria-hidden="true"><img src="system/themes/flexible/icons/drag.svg" width="16" height="16" alt=""></button>`

Wichtig ist, dass dieses Attribut nur eingesetzt wird, wenn Screenreader-Nutzer hierdurch keine Funktion verlieren, sondern mit möglichst keinem Mehraufwand einen gleichwertigen Ersatz haben und es durch das problematische Element für sie unnötige Missverständnisse gäbe. Beides ist hier klar der Fall.

**Comment by leofeyer** [comment]
Implementiert in 0854acd0c062b6bd0e1995fd708336d7ddf60a9b. Ich wäre dafür, das auch in die 4.4 LTS zurück zu portieren.

**Comment by leofeyer** [comment]
Backported in 71ee0edbb1bdb18c96f6c92391fcfa57c4100f5c.
