### ISSUE TITLE
Clear cache problem during update [4.3.8]

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#784]
Running composer update, everything is going fine.

It also says: `[OK] Cache for the "prod" environment (debug=false) was successfully cleared.`

The placeholder text for an empty news list is now in English (it was German under 4.3.7).

I have to clear the cache by hand.

Then the text shows up in German again.

**Comment by wiphi** [comment]
Can confirm this. Clearing the cache manually solves the problem. Thanks for this little workaround ;)

**Comment by leofeyer** [comment]
What exactly does "clear the cache by hand mean? Did you run `bin/console cache:clear` or `rm -r var/cache/prod`?

**Comment by netzarbeiter** [comment]
I did `rm -rf var/cache/prod`.

**Comment by wiphi** [comment]
Run the command line like @netzarbeiter `rm -rf var/cache/prod`

**Comment by leofeyer** [comment]
Fixed in 9befda47971b16e48f1e41640c96fa16ea085232.
