### ISSUE TITLE
The language is no longer added automatically to the url [4.3.8]

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#785]
Why has this change been done in a bug fix release?

If you want to add the language to the url go to `app/parameters.yml` and place `prepend_locale: true` as a parameter.

**Comment by fritzmg** [comment]
For reference:

* https://github.com/contao/manager-bundle/commit/5477fda5469e19d7df5451933815be49f5d661cd
* https://github.com/contao/manager-bundle/commit/869b1739ff4ea45f546e8d775b940dbbcfab8802

**Comment by leofeyer** [comment]
Reverted in 37f9215d45431b91d8149c7767cc18fb13ced6a2. We will only change the default value in Contao 4.4.
