### ISSUE TITLE
Backend-Breadcrumb für Screenreader-Nutzer nicht erkennbar

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#786]
Wenn man z.B. die Seitenstruktur verkürzt sehen will, kann man auf einen Seitennamen klicken. Danach zeigt Contao nur noch diese Seite mit ihren Unterseiten an. Ergänzend erscheint über der eigentlichen Seitenliste eine weitere Liste, die als Breadcrumb dient (ein Klick auf den ersten Eintrag „Alle“ zeigt wieder die komplette Seitenstruktur an).

Das Problem für Screenreader-Nutzer: Sie können nicht verstehen, was da geschieht. Für sie ist das einfach nur eine weitere Liste, ohne jegliche Zuordnung.

Daher möchte ich vorschlagen, dass die grundlegenden Infos ergänzt werden. Um die Liste sollte folgendes HTML ergänzt werden:
` <nav aria-label="Aktueller Standort in der verkürzten Listenansicht"> ...</nav> `(über die Formulierung der Beschriftung könnte man natürlich noch reden)

**Comment by cliffparnitzky** [comment]
Zu testen in
- Artikel/Seitenstruktur
- Templates
- Dateiverwaltung

**Comment by leofeyer** [comment]
Siehe #868.
