### ISSUE TITLE
Link „Neuer Beitrag“ in „Neuer Artikel“ umbenennen

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#788]
Es ist für Redakteure irritierend, dass der Link in der Artikelübersicht „Neuer Beitrag“ heißt statt „Neuer Artikel“, zudem ja auch im Linktitel „Einen neuen Artikel anlegen“ steht. Es wäre schön, wenn das geändert wird.

**Comment by cliffparnitzky** [comment]
Unter Umstände wurde das nun mit #790 bereits behoben.

@leofeyer Wenn du mir Zugang zum Transifex gewährst, kann ich das bestätigen bzw. korrigieren.

**Comment by leofeyer** [comment]
Wo genau befindet sich dieser Link?

**Comment by cliffparnitzky** [comment]
![screen](https://cloud.githubusercontent.com/assets/1247552/26572781/7fda5a66-451b-11e7-8e3c-0328e34cdd2d.png)

**Comment by leofeyer** [comment]
Das scheint mit #790 bereits behoben zu sein. Zumindest in meinem Testsystem steht da jetzt "Neuer Artikel".

**Comment by cliffparnitzky** [comment]
@leofeyer Okay, glauben wir mal 😁 ... könnte in Transifex nachschauen .... wenn ich dort entsprechenden Zugriff hätte 😉

**Comment by fenepedia** [comment]
Alles gut :-)
![artikel - contao open source cms](https://user-images.githubusercontent.com/566448/26849881-fed093fe-4b05-11e7-9fee-da007a6a316c.png)
