### ISSUE TITLE
Unterschiedliche Funktionsicons in Artikelübersicht mit identischem Alternativtitel

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#789]
In der Artikelübersicht lautet der Alternativtext für edit.svg und header.svg jeweils identisch "Artikel bearbeiten". Nur ihre Linktitel unterscheiden sich, was aber - wie an anderer Stelle erwähnt - bei vielen Screenreader-Nutzern nicht ausgegeben wird. Somit haben sie je Artikel zwei Funktionsicons die vollkommen identisch heißen, was die Unterscheidung an der Stelle fast unmöglich macht.

Bitte benennt den Alternativtext für header.svg in "Artikeleinstellungen bearbeiten" um.

Das identische Problem gibt es bei:

- der Übersicht der Nachrichtenarchive (edit.svg und header.svg jeweils identisc "Archiv bearbeiten" als Alternativtext)
- der Übersicht der Kalender (edit.svg und header.svg jeweils identisc "Kalender bearbeiten" als Alternativtext)
- der Übersicht der FAQ (edit.svg und header.svg jeweils identisc "Kategorie bearbeiten" als Alternativtext)
- usw. (also im Prinzip scheinbar überall, wo diese beiden Funktionsicons im Einsatz sind)

**Comment by cliffparnitzky** [comment]
Im Grunde sind die Texte der Schlüssel "tl_....edit.0" und "tl_....editheader.0" oft identisch. Das müsste DCA für DCA in allen Bundles geprüft werden. Das in allen Sprachen ist ne Menge Holz.
