### ISSUE TITLE
Alternativtext für cut.svg in Artikelübersicht umbenennen

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#790]
In der Artikelübersicht lautet der Alternativtext für das Funktionssymbol cut.svg bei den Artikeln "Beitrag verschieben". Da sonst fast ausschließlich von Artikeln die Rede ist (u.a. im zugehörigen Linktitel), irritiert das u.a. Screenreader-Nutzer. Es wäre besser, wenn der Alternativtext für die cut.svg "Artikel verschieben" lautet.

Dito beim Funktionssymbol delete.svg an derselben Stelle. Hier lautet der Alternativtext "Beitrag löschen", während im Linktitel verständlicher von "Artikel löschen" die Rede ist. Es wäre besser, wenn der Alternativtext für die delete.svg "Artikel löschen" lautet.

**Comment by cliffparnitzky** [comment]
Betrifft im Grunde folgenden Buttons:

- `new` - Neuer Beitrag --> Neuer Artikel
- `show` - Beitragsdetails --> Artikeldetails
- `copy` - Beitrag duplizieren --> Artikel duplizieren
- `cut` - Beitrag verschieben --> Artikel verschieben
- `delete` - Beitrag löschen --> Artikel löschen
- `toggle` - Beitrag veröffentlichen/unveröffentlichen --> Artikel veröffentlichen/unveröffentlichen

Da die Alternativtexte aus den Sprachdateien genommen werden, sollte man dies bei Transifex anpassen.

**Comment by leofeyer** [comment]
Ich kann das Problem weder in Contao 3.5 noch in Contao 4 nachvollziehen.

<img width="300" alt="" src="https://cloud.githubusercontent.com/assets/1192057/26549913/9ac44562-447b-11e7-9977-8b42895b0e44.png">

**Comment by cliffparnitzky** [comment]
Geht, wie in einigen anderen Tickets nicht um die Tooltips (die aus dem `title`-Attribut gezogen werden), sondern um die Werte im `alt`-Attribut:

![screen](https://cloud.githubusercontent.com/assets/1247552/26552791/f9b0b80a-4488-11e7-8f42-fc0cf4295343.png)

**Comment by leofeyer** [comment]
Ich habe die Übersetzung auf transifex.com entsprechend korrigiert.

**Comment by NinaG** [comment]
Danke
