### ISSUE TITLE
Source code formatting not beautiful

### ISSUE THREAD

**Issue by Teetrinker** [contao/core-bundle#791]
Unlike in Contao Version3, the html source code is not aligned properly.

- the meta tags are not aligned
- random whitespace between #wrapper/#container/#main
- line break inside h1
- whitespace between .ce_text and its p

![screenshot-contao-v4](https://cloud.githubusercontent.com/assets/1758653/25379981/f7382148-29ae-11e7-99f3-04387ba9c4cb.jpg)

how to reproduce:
I set up a new installation with Contao 4.3 (managed edition), created a layout, a root and home page, two content elements, a title and a ce_text. No styling.

**Comment by bytehead** [comment]
Do you really care about generated source code style? 🤔

**Comment by discordier** [comment]
Feel free to add an `kernel.response` listener which pipes the whole stuff through `html_tidy()`.
Yet I feel as @bytehead, the generated code is not subject to code style.

**Comment by bytehead** [comment]
There's also a [bundle](https://github.com/wachterjohannes/AsapoTidyBundle). I don't know if it's plug and play, but looks like there is a kernel response listener.

**Comment by Teetrinker** [comment]
@bytehead For sure this is not high priority :) But it's the little things...

**Comment by leofeyer** [comment]
We stopped caring a long time ago, because there are plenty of tools which do exactly this.

**Comment by fritzmg** [comment]
> There's also a bundle. I don't know if it's plug and play, but looks like there is a kernel response listener.

Hm, I just tried the bundle together with Contao 4 - but it does not seem to work. Were you able to get it to work?
