### ISSUE TITLE
Queries not starting with SELECT or SHOW are unusable

### ISSUE THREAD

**Issue by backbone87** [contao/core-bundle#792]
Queries that do not start with SELECT or SHOW are unusable.

This is a BC break compared to contao 3. Is it intended?

https://github.com/contao/core-bundle/blame/master/src/Resources/contao/library/Contao/Database/Statement.php#L287

Use case: Union queries ala `(SELECT ...) UNION (SELECT ...)`, but I am sure there are others.

The old check for a result resource after the statement was much more robust.

**Comment by leofeyer** [comment]
I assume you are referring to this?

https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Database/Statement.php#L301

I'm fine with changing the code. @contao/developers Any objections?

**Comment by discordier** [comment]
Nope, no objections, we should restore the original behavior.

**Comment by aschempp** [comment]
Sounds reasonable.

**Comment by leofeyer** [comment]
Turns out we cannot restore the original behavior, because `$this->statement` is always a `PDOStatement` object. We could use `columnCount()` though I guess:

```php
// Execute the query
$this->statement = $this->resConnection->executeQuery($this->strQuery);

// No result set available
if ($this->statement->columnCount() < 1)
{
	return $this;
}

// Instantiate a result object
return new \Database\Result($this->statement, $this->strQuery);
```

According to the phpDoc, this should work fine (in contrast to using `rowCount()`):

```php
/**
 * Returns the number of columns in the result set
 *
 * @return integer The number of columns in the result set represented
 *                 by the PDOStatement object. If there is no result set,
 *                 this method should return 0.
 */
```

@contao/developers /cc

**Comment by backbone87** [comment]
do non-select queries expose result sets?

**Comment by leofeyer** [comment]
> do non-selects expose a statement with `columnCount() == 0`?

Yes.

**Comment by backbone87** [comment]
from my side then i am good to go. even if its not 100% equal to previous behavior, we can edge out these cases with future tickets.

**Comment by leofeyer** [comment]
Changed in 70806c6a92ab251fa7b27a2ce25415d60e0fb41b then.
