### ISSUE TITLE
Theme details - folder only shows hash

### ISSUE THREAD

**Issue by christianromeni** [contao/core-bundle#793]
When looking at the theme details (Pressing i to open the lightbox), the Folderpath and Screenshot are only shown as hash:

![image](https://cloud.githubusercontent.com/assets/1358040/25472268/ef8580d0-2b2a-11e7-9c5e-655b54e2f971.png)

**Comment by leofeyer** [comment]
Showing the UUID is the normal behavior (try the same with user groups or content elements or […]). @contao/developers Would it make sense to restore the file paths here?

**Comment by Toflar** [comment]
I think the path plus UUID would make sense? While we're at it: would be great if developers could influence the output which is not possible atm ;)

**Comment by leofeyer** [comment]
Implemented in 300ad0f339d3c0a5be814041af3b299166205d9f.
