### ISSUE TITLE
Speichern und duplizieren schlägt fehl

### ISSUE THREAD

**Issue by joke1** [contao/core-bundle#797]
Wenn man ein neues Frontend-Modul erstellt und anschließend Speichert und dupliziert, wird der Datensatz der nachfolgenden Eingabemaske nicht gespeichert.

https://demo.contao.org/contao
1. Themes -> Frontend-Module -> Neues Modul.
2. Als Titel "Test1" eingeben und unten auf "Speichern und duplizieren".
3. In der neuen Eingabemaske als Titel "Test2" eingeben und unten auf "Speichern und schließen" (oder auch nur "Speichern").
4. In der Modul-Übersicht findet man kein "Test2". 

"Speichern und neu" funktioniert dagegen ohne Probleme.

**Comment by leofeyer** [comment]
Behoben in c171596d63ab9452d84f594b579e29cd76093abe.
