### ISSUE TITLE
Consistent ::class usage

### ISSUE THREAD

**Issue by backbone87** [contao/core-bundle#798]
Why are strings used here:
https://github.com/contao/core-bundle/blob/master/src/ContaoManager/Plugin.php#L40

But not 5 lines above:
https://github.com/contao/core-bundle/blob/master/src/ContaoManager/Plugin.php#L35

Accessing the `::class` contant does not trigger a class load.

**Comment by aschempp** [comment]
No reason, feel free to PR a fix :-)

**Comment by aschempp** [comment]
Ah, I was wrong. The dependencies must not necessarily be available / installed, so using class constants wont always work…

**Comment by backbone87** [comment]
class constants always work :) thats why i wrote: "Accessing the ::class contant does not trigger a class load."

**Comment by backbone87** [comment]
To expand on this:
```
use Some\Non\Existing\Thing;

echo Thing::class;
```
Will always work and prints: `Some\Non\Existing\Thing`

`use` and `::class` are only strings based on "file-local" information, nothing will be searched for or loaded

**Comment by leofeyer** [comment]
It's true what @backbone87 says.

**Comment by leofeyer** [comment]
Changed in 49f93d433be895f8a693f961ff34fd6ca5e5b817.
