### ISSUE TITLE
Problem using Insert-Tags in combination with frontend JS-Frameworks

### ISSUE THREAD

**Issue by codiso** [contao/core-bundle#805]
Most of modern JS-Frontend-Frameworks are using the {{ mustache }} syntax for their placeholders or directives. Modern web apps are normaly using JS-Frontend-Framework for interaction and data-transport between frontend and backend and vice versa. If a combination of Contao and a JS-Frontend-Framework (like e.g. Angular, Ember, Moon etc.) is planned, there will be a huge show stopper in the interpretation of Contao-Insert-Tags.

Contao is replacing the {{ mustache }} syntax also if the content in the {{ mustache }} syntax does not match the syntax of Contao-Insert-Tags {{(*.)::(.*)}}. So it is not possible to integrate the {{ mustache }} syntax of Framework-Commands into Contao-Templates.

**Comment by Toflar** [comment]
Contao insert tags do not necessarily need a `::`. Even the core does provide such type of insert tags:

* `{{link_close}}`
* `{{date}}`
* `{{last_update}}`
* `{{version}}`
* `{{request_token}}`
* `{{toggle_view}}`
* `{{br}}`

But I see two possible optimizations here:

1. We could adjust the regular expression to not allow spaces. So `{{foobar}}` does work but `{{ foobar }}` does not. I have never seen a Contao insert tag that works with spaces anyway and I think this should be pretty safe. Mustache, Twig and co. handle spaces after `{{` and before `}}`.
2. We could leave insert tags not known to Contao or any extension as is. So `{{iamabsolutenonsensetocontao}}` stays as it is in the output.

**Comment by leofeyer** [comment]
Isn't 2. the case already in Contao 4?

**Comment by Toflar** [comment]
No :)

**Comment by leofeyer** [comment]
You are right. And this issue could easily be solved by adding a `replaceInsertTags` hook which simply returns unknown insert tags, couldn't it?

**Comment by Toflar** [comment]
You could, yes. But might be still worth changing the behaviour in 4.4.

**Comment by aschempp** [comment]
I don't think we should keep unknown inserttags, as this would be a behavior change. The space thing is actually fairly clever and might solve a lot of issues.

I know this would work for Twig and Vue.js, dunno about Mustache.

**Comment by leofeyer** [comment]
Then I guess the easiest solution is to adjust the [regex](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L81) like this:

```php
$tags = preg_split('/{{([^ ][^{}]+[^ ])}}/', $strBuffer, -1, PREG_SPLIT_DELIM_CAPTURE);
```

@ausi What do you think?

**Comment by ausi** [comment]
Your regex would not match `{{br}}` or `{{abbr::Foo Bar }}`. 

I think we should only forbid the space character at the beginning of the insert tag, not at the end:

```php
$tags = preg_split('/{{(?!\s)([^{}]+)}}/', $strBuffer, -1, PREG_SPLIT_DELIM_CAPTURE);
```

**Comment by leofeyer** [comment]
Ok. 😄

**Comment by ausi** [comment]
Maybe we could even require that the insert tag has to start with a letter?  
With `/{{([a-z][^{}]*)}}/`.

This would improve compatibility with the mustache syntax which has `{{#`, `{{>`, `{{/`, `{{^`, `{{&` and `{{!`.

**Comment by leofeyer** [comment]
At least we could require it not to start with any of those reserved characters.

**Comment by Toflar** [comment]
I think that's an excellent idea. Our insert tags are for editors, I don't see why you would ever want it to start with something else than a letter.

**Comment by leofeyer** [comment]
E.g. `{{2nd-name}}`?

**Comment by Toflar** [comment]
Never seen any insert tags like this and I have seen a lot of them 😄

**Comment by leofeyer** [comment]
Well, I have. And I have also seen insert tags with special chars (ä, ö, ü, é, etc.) and with upper-case chars, so I think we should rather use `/{{([\pL\pN][^{}]*)}}/` or `/{{([^#>\/^&! ][^{}]*)}}/`.

**Comment by ausi** [comment]
I would prefer `[\pL\pN]` over `[^#>\/^&! ]`, but I’d like `[a-zA-Z0-9]` more because special characters in the insert tag name do not have to be supported IMO.

**Comment by Toflar** [comment]
I agree with @ausi.

**Comment by leofeyer** [comment]
I disagree, because there is no valid reason to prevent insert tags like `{{cité}}`, is there?

**Comment by leofeyer** [comment]
Or even `{{シュタット}}`.

**Comment by Toflar** [comment]
I would never write an insert tag that is not in English. Just like I would never write a twig function that is not in English. I think it's bad practice.

**Comment by Toflar** [comment]
> don't you think?

No, as I said, English is the way to go. The core does not provide any language specific insert tags either.

**Comment by leofeyer** [comment]
That's not a point. Unicode insert tags work right now and changing it would be a BC break. And if we decided to break BC, we should do it consistently and not for the first character only.

**Comment by asaage** [comment]
Is this realy an issue?
@codiso said it is not possible to integrate the {{ mustache }} syntax of Framework-Commands into Contao-Templates.
@leofeyer said Insert tags are for users, not for programmers.
everytime i used an inserttag inside a template without the ```replaceInsertTags``` method it just got passed through and i would be able to use it as is on the client-side.

**Comment by ausi** [comment]
> everytime i used an inserttag inside a template without the `replaceInsertTags` method it just got passed through and i would be able to use it as is on the client-side.

Insert tags get evaluated at a global level before the HTML gets sent to the client. If you put `{{foobar}}` anywhere in your template it will get replaced with an empty string and the client cannot see the insert tag itself.

**Comment by asaage** [comment]
@ausi i see.
But on an old 3.0 installation this is not the case. Since then i was used to use ```replaceInsertTags()``` inside templates. Not shure though when and why this has changed exactly.

**Comment by fritzmg** [comment]
In Contao 3, Insert Tags are not replaced recursively. Thus it might happen that you see the insert tag in the front end.

**Comment by asaage** [comment]
Yes i remember that there was a change with recursiveness.
Just for curiosity:
Is there a way to escape insertTags (```{{``` & ```}}```)?
(Obviously the [docs](https://docs.contao.org/books/manual/3.4/de/04-inhalte-verwalten/inserttags.html) are not build with contao...)
and if not: wouldn't that be a better approach instead of changing what is valid inside?

**Comment by Toflar** [comment]
You can escape by using `[{]` and `[}]` (note: only one bracket!).

**Comment by leofeyer** [comment]
Implemented in c9ed4fa346ea00c99d3658059e98d0c611bee370.

**Comment by ausi** [comment]
If you use the blacklist version I think you should include `{` and `}` too, like `[^% #^/!>&{}]`. But as already noted in https://github.com/contao/core-bundle/issues/805#issuecomment-299115321 I would prefer `[\pL\pN]`.

**Comment by leofeyer** [comment]
Changed in c2e2a54a0538acff67acacdb4d7faa5789d4d64d.
