### ISSUE TITLE
Image Meta information Link is not used for single images

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#806]
In the file manager we have 4 **Meta informations** for images: _Title_, _Alternate text_, _Link_ and _Caption_. If I create a gallery content element, all 4 informations will be used.
But if I create a single image and save them, only _Title_, _Alternate text_ and _Image caption_ will be filled out automatically. The _Image link target_ field is still empty.

Should not be the _Link_ content in the _Image link target_ field?

Contao version: Managed edition v4.3.9

**Comment by fritzmg** [comment]
Related: https://github.com/contao/core/issues/7774

In the future, single `image` or `text` elements will get their meta information directly from the Dbafs - though you can override them with the new checkbox. This would (probably) solve this issue as well.
