### ISSUE TITLE
Show the STOP screen if a version is overwritten

### ISSUE THREAD

**Issue by leofeyer** [contao/core-bundle#811]
This is a follow-up ticket of #809. @aschempp suggests to show the STOP screen instead of just an error message if a version is overwritten.

Current situation:

<img width="939" alt="" src="https://cloud.githubusercontent.com/assets/1192057/25751916/e95c2fdc-31b6-11e7-839a-2e087181dbd5.png">

Suggested situation:

<img width="744" alt="" src="https://cloud.githubusercontent.com/assets/1192057/25751926/f10d225e-31b6-11e7-93fc-a1342a335a60.png">

Of course, the content of the STOP screen has to be adjusted.

**Comment by aschempp** [comment]
ideally, the stop screen would directly show the diff any maybe allow what version to keep.

**Comment by leofeyer** [comment]
I don't think it will be a "use theirs or use mine" situation. I assume that the content needs to be merged in most cases. But still, I agree that showing the diff view would be desirable.

**Comment by leofeyer** [comment]
As discussed in Mumble on May 18th, the message is now shown on a separate page in 7e9fa2a26b0dd7747165479317fbe45a69daee50.

<img width="816" alt="" src="https://cloud.githubusercontent.com/assets/1192057/26250725/46347c10-3cab-11e7-930d-f0df16a98d07.png">

We are planning to enhance the functionality in the future, e.g. with an auto merging option or the possibility to select the versions to be compared. Please create new pull requests for these enhancements.

**Comment by leofeyer** [comment]
Sadly, I have to rework the implementation. Checking the user's permission is so cumbersome that the only way to accomplish it is to throw a `ContentException` from within the data container.

**Comment by leofeyer** [comment]
Implemented in cf5c60f12aca5803e4156a6703b9a9ff70b0145c now.
