### ISSUE TITLE
BE deutsche Sprache nach Update nicht ladbar

### ISSUE THREAD

**Issue by BugBuster1701** [contao/core-bundle#812]
Das Problem von hier https://github.com/contao/core-bundle/issues/783
lässt sich bei mir wie folgt reproduzieren:

Sobald ich auf Kommandozeile ein `composer update` durchlaufen lasse oder per Contao-Manager, auch wenn das **nichts zum updaten findet**, wird das Backend in englisch dargestellt obwohl mit deutsch angemeldet.
Nur externe installierte Erweiterungen werden in deutsch ausgegeben.

Ein `vendor/bin/contao-console cache:clear -e=prod` bringt nichts, wäre auch seltsam, da `composer update` dieses ja wohl auch aufruft.

Erst ein Aufruf von "domain/contao/install" inkl. Anmeldung! führt dazu, dass das Backend in diesem Augenblick wieder auf deutsch springt. 

Contao 4.3.9 Managed-Edition.

**Comment by leofeyer** [comment]
Siehe #784.
