### ISSUE TITLE
Visuelle Select-Felder im Backend nicht barrierefrei (einfache Lösung)

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#813]
Die Ausklappfelder werden im Contao-Backend durch einen alternativen Aufbau ersetzt, der optisch gut aussieht, aber hinsichtlich der Barrierefreiheit fatal ist.

Da im Quellcode davor aber sowieso die originale Select-Liste steht (die nur vom Script ausgeblendet wird), schlage ich vor, dass die Nutzer in ihren persönlichen Einstellungen eine Möglichkeit erhalten, mit der sie einstellen können, dass sie das normale Ausklappfeld statt der neuen fancy-Ansicht angezeigt bekommen (entweder indem das Script für sie durch diesen Switch gar nicht erst geladen wird, oder aber via CSS per !important-Anweisung das normale Select-Feld aktiv geschaltet und das fiktive Feld inaktiv wird). Das würde mit minimalem Aufwand eine enorme Verbesserung für Nutzer darstellen, die auf eine barrierefreie Bedienung angewiesen sind!

In einem zweiten Schritt könnte man die visuelle Darstellung auch barrierefreier machen, aber das würde ich dann in einem separaten Ticket erläutern. Hier geht es um die Bitte, diese kleine und simple Option einzubauen, die für Screenreader-Nutzer extrem hilfreich wäre.

**Comment by aschempp** [comment]
Ich wäre dafür das Select-Feld einfach per CSS zu stylen und das Plugin zu entfernen, mit modernen Browsern sollte das Problemlos gehen.

**Comment by leofeyer** [comment]
Wir nutzen Stylect in Contao 4 gar nicht mehr (seit Contao 4.2 glaube ich).

**Comment by NinaG** [comment]
@leofeyer Es ist doch noch ganz normal da, auch in der Demo? Ein beliebiges Inhaltselement bearbeiten und das Elementtyp-Feld ansehen.

**Comment by NinaG** [comment]
@aschempp Dann wäre aber das Suchfeld nicht mehr da, das damals eingebaut wurde um die Liste nach Bedarf zu verkürzen.

**Comment by aschempp** [comment]
Das ist etwas anderes. Wir verwenden zwei verschiedene Scripts, Stylect (im alten Theme) nur für Styling, und Select2 für die Suchfunktion.

**Comment by leofeyer** [comment]
Wäre es nur Select2 – es ist aber Chosen. 😄 Trotzdem gilt das, was @aschempp gesagt hat.

**Comment by leofeyer** [comment]
Somit ist das Ticket ein Duplikat von #773.

**Comment by NinaG** [comment]
Ein echtes Select-Field wäre immer das Optimum, da es garantiert für alle Nutzer funktioniert :)
