### ISSUE TITLE
ARIA-Labels im RTE sind in Englisch statt Deutsch

### ISSUE THREAD

**Issue by NinaG** [contao/core-bundle#814]
Im RTE werden bei den ARIA-Labels die Beschriftungen derzeit nur in Englisch ausgegeben. Beim Fettdruck-Button ist die ARIA-Beschriftung derzeit also „Bold“ statt Fettdruck.

Bitte stellt hier die korrekten Sprachfiles ein, damit auch die ARIA-Labels in der passenden Sprache sind. Falls Übersetzungen fehlen, könnt ihr mir gerne sagen, welche Files ich übersetzen soll.

**Comment by fritzmg** [comment]
Das Ticket müsstest du hier aufmachen: https://github.com/tinymce/tinymce/issues
