### ISSUE TITLE
C4: mod_sitemap: Items are shown even when "Show in sitemap" is set to "Show never"

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#818]
I guess there is a typo in
`/contao/modules/Module.php`, method [renderNavigation()](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/Module.php#L312)

line 312 should be
`if ($this instanceof ModuleSitemap && $objSubpage->sitemap == 'map_never')`
instead of
`if ($this instanceof ModuleSitemap && $objSubpages->sitemap == 'map_never')`

Can anyone confirm?

**Comment by leofeyer** [comment]
Fixed in 65d53006c09c894a813301f1a553c1dd45aa601a.
