### ISSUE TITLE
FE module titles with square brackets: wrong styling in the page layout

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#820]
If there are front end modules that have square brackets in the module title (e.g. "foo [bar]"), the module type does not get assigned the correct styling in the front end module drop down list.

![fe_mod](https://cloud.githubusercontent.com/assets/1218766/25869812/02103750-3502-11e7-81e0-3a42bdda3566.png)

**Comment by leofeyer** [comment]
Fixed in contao-components/chosen@a6648e0e2b25370710455ee81809d6c74251f1c8.
