### ISSUE TITLE
problem with module breadcrumb

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#822]
the active element becomes the name of *pageTitle* instead of **title**

following example of a page structure:
- title: **page 1**, pageTitle: *test 1*
  - title: **page 1.1**, pageTitle: *test 1.1*

active page: **page 1**
in breadcrumb: *test 1*

active page: **page 1.1**
in breadcrumb: **page 1** > *test 1.1*

The breadcrumb navigation should work consistent. ;-)

**Comment by leofeyer** [comment]
This is the desired behavior in both [Contao 3](https://github.com/contao/core/blob/master/system/modules/core/modules/ModuleBreadcrumb.php#L197) and [Contao 4](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/modules/ModuleBreadcrumb.php#L199).

**Comment by frontendschlampe** [comment]
desired? When page is active, it's pageTitle and when the same page is inactive it's the title. This can't be desired! This is incosistent and extremely confusing for the visitor!

**Comment by leofeyer** [comment]
You can easily change this in the template if you don't like it the way it is.

**Comment by leofeyer** [comment]
BTW, it is absolutely common that a menu item has a different name than the page title it links to. You are even doing it on your own website, where there is a menu item called "Design" that links to a page called "Design, Gestaltung, Layout & Satz".

**Comment by frontendschlampe** [comment]
> You can easily change this in the template if you don't like it the way it is.

No, I can't. When I use ```<?= $item['title'] ?>``` it shows ```pageTitle``` for linked elements, too. For active elements you use ```<?= $item['title'] ?>```and for linked elements ```<?= $item['link'] ?>``` - that's incosistent and illogical!!!

> BTW, it is absolutely common that a menu item has a different name than the page title it links to. You are even doing it on your own website, where there is a menu item called "Design" that links to a page called "Design, Gestaltung, Layout & Satz".

That's right, but in navigation the page is called "Design" no matter if the page is active or linked!

I have no problem, that there's the ```pageTitle``` used for naming menu items in breadcrumb but if you use it, you should use it everytime no matter if the page is active or not!

**Comment by leofeyer** [comment]
It's not inconsistent. We use the page *name* for all links and the page *title* for the active element.

Just replace `<?= $item['title'] ?>` with `{{page::title}}` if you don't like the default behavior.

**Comment by discordier** [comment]
The problem is, that the shown value changes when an item is changing from active state to trail. Then the value is title before and link afterwards, which is confusing.

**Comment by ausi** [comment]
This behavior of Contao confused me too, several times. I think `tl_page.pageTitle` should never be used in the breadcrumbs module, `tl_page.title` is the correct field IMO. The breadcrumbs module is a navigation module and all other navigation modules use `tl_page.title` consistently AFAIK.

**Comment by leofeyer** [comment]
OMG. Fortunately we do not have more important things to do!

Changed in bc07b9f574fb0df25e148575019632ead72ed4b6.
