### ISSUE TITLE
[4.4.0-beta1] Interchanged arguments in be_page

### ISSUE THREAD

**Issue by tjoussen** [contao/core-bundle#823]
Hi!

I tried to test the new Custom Backend Route feature, but it looks like that the defined blocks are not passed to the correct keys in the arguments array for the `render_contao_backend_template` twig extension.

My custom backend template looks like the example from #512 

```twig
{% extends "@ContaoCore/Backend/be_page.html.twig" %}

{% block error %}
    An error occured
{% endblock %}

{% block headline %}
    Panel
{% endblock %}

{% block main %}
    {{ content }}
{% endblock %}
```

The current `vendor/contao/core-bundle/src/Resources/views/Backend/be_page.html.twig` is defined as:

```twig
{{ render_contao_backend_template({
    main: block('main'),
    error: block('headline'),
    headline: block('error')
}) | raw }}
```
 The arguments `error: block('headline')` and `headline: block('error')` are interchanged.

Fix:
```twig
{{ render_contao_backend_template({
    main: block('main'),
    error: block('error'),
    headline: block('headline')
}) | raw }}
```

My current output looks like
![bildschirmfoto vom 2017-05-12 15-58-21](https://cloud.githubusercontent.com/assets/21999844/26001213/f463695c-372b-11e7-8d9e-da2bbadc5164.png)

**Comment by bytehead** [comment]
@sheeep is actually in holidays right now. Could take a while.

**Comment by aschempp** [comment]
How dare him taking holidays! 😬

**Comment by bytehead** [comment]
We don't have to wait - it's a typo.
There is only a basic `foreach` later on: https://github.com/contao/core-bundle/blob/4.4.0-beta1/src/Twig/Extension/ContaoTemplateExtension.php#L83-L85

**Comment by leofeyer** [comment]
Thank you @bytehead.
