### ISSUE TITLE
Bug: DC_Folder does not check for gdlib when generating thumbnails

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#826]
This means that `gdMaxImgHeight` and `gdMaxImgWidth` are considered even though I use Imagemagick.

**Comment by DanielSchwiperich** [comment]
composer.json requires `ext-gd` so running gdlib is necessary I assume

**Comment by Toflar** [comment]
Gd is absolutely not a requirement. That's another bug then :)

**Comment by ausi** [comment]
`ext-gd` is a requirement until Contao 5.0, see https://github.com/contao/core-bundle/issues/533#issuecomment-236212693

But the requirement of GD has nothing to do with the fact that we should ignore `gdMaxImgWidth/Height` if Imagick or Gmagick is used by the image services. We do this already in the LegacyResizer in [src/Image/LegacyResizer.php:122](https://github.com/contao/core-bundle/blob/1448b9d4a9faa9f3fcf6e5518d8bb159bf7f1821/src/Image/LegacyResizer.php#L122)

**Comment by leofeyer** [comment]
How can we check the implementation here?

https://github.com/contao/core-bundle/blob/release/4.4.0/src/Resources/contao/classes/DataContainer.php#L613

https://github.com/contao/core-bundle/blob/release/4.4.0/src/Resources/contao/drivers/DC_Folder.php#L2754

**Comment by ausi** [comment]
With `\System::getContainer()->get('contao.image.imagine') instanceof \Imagine\Gd\Imagine`

**Comment by leofeyer** [comment]
Fixed in 933f9f497e07f47ea5b800b569d349a9a8825b57.
