### ISSUE TITLE
textarea not full width

### ISSUE THREAD

**Issue by netzarbeiter** [contao/core-bundle#827]
<img width="1064" alt="bildschirmfoto 2017-05-16 um 23 45 33" src="https://cloud.githubusercontent.com/assets/1942550/26130013/03dabefc-3a93-11e7-83f9-eddf898775af.png">

Introduced in commit https://github.com/contao/core-bundle/commit/3553e05601c97e0e80bdcaf729bb52a3e344b325

**Comment by leofeyer** [comment]
Fixed in 8a5ca7460f4ee9a17cc400184518e28ea7561d4b and 1cdfd1169f52130c6b29c016673075507837cccd.
