### ISSUE TITLE
Edit several in files "public"

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core-bundle#828]
small visual bug
<img width="909" alt="bildschirmfoto 2017-05-17 um 08 15 06" src="https://cloud.githubusercontent.com/assets/8327905/26140854/4f751ac4-3ad9-11e7-9a30-e4b0e8c567cb.png">

**Comment by leofeyer** [comment]
Fixed in 8c6c64eca85efd5f72454b272db5fecd49ec8d0f and ff0f7fe425c0770239d2e4e85d5ae5fc1043370b.
