### ISSUE TITLE
Fehler in der Bezeichnung in DE bei CE-Downloads

### ISSUE THREAD

**Issue by zonky2** [contao/core-bundle#831]
Fehler in der Bezeichnung in DE bei CE-Downloads: es handelt sich m.E. um das Mitgliederverzeichnis (FE) und nicht der der Benutzer (BE)

![shot351](https://cloud.githubusercontent.com/assets/1045318/26203599/2f1b0e1a-3bdc-11e7-90f3-95a22cfe9136.jpg)

in 3.5 auch schon/noch

**Comment by leofeyer** [comment]
Das Wort "Benutzerverzeichnis" ist einfach die deutsche Übersetzung von "home directory". Das Wort "Mitgliederverzeichnis" ist hingegen ein Verzeichnis aller Mitglieder – Du meinst vermutlich "Mitgliedsverzeichnis", was aber überhaupt nicht gebräuchlich ist und wahrscheinlich eher verwirrt als die korrekte Übersetzung.

**Comment by leofeyer** [comment]
Andere mehr oder weniger gängige Übersetzungen für "home directory" sind:

* Home-Verzeichnis
* Heimatverzeichnis
* Homedirectory

"Home-Verzeichnis" schlägt sogar Google Translate als Übersetzung vor. 🤔

**Comment by zonky2** [comment]
Aus Sicht einer "konsistenten Benutzerführung" gibt es bei Contao (DE) die Unterscheidung zwischen "Benutzern" und "Mitgliedern" - diese sprachliche Einteilung sollte sich m.E. auch in allen "zugehörigen Bezeichnungen" in genau dieser Weise widerspiegeln...

**Comment by leofeyer** [comment]
Geändert in f969775204cf4caf78a39566815768c4bb8ab72a.

**Comment by zonky2** [comment]
glaube, sieht gut aus...
