### ISSUE TITLE
DCA-Felder aus dcaconfig.php mit 'exclude' => true werden auch für Admins nicht angezeigt

### ISSUE THREAD

**Issue by LinkingYou** [contao/core-bundle#836]
**Ausgangssituation:**

Wir haben über die dcaconfig.php die tl_calendar_events um ein Feld erweitert:

```
<?php
$GLOBALS['TL_DCA']['tl_calendar_events']['palettes']['default'] = str_replace
(
    'author;',
    'author,seminargebuehr;',
    $GLOBALS['TL_DCA']['tl_calendar_events']['palettes']['default']
);

$GLOBALS['TL_DCA']['tl_calendar_events']['fields']['seminargebuehr'] = array
(
    'label' => array(
        'Seminargebühr',
        'Seminargebühr'
    ),
    'inputType' => 'text',
    'eval' => array('maxlength' => 255),
    'sql' => "varchar(255) NOT NULL default ''",
    'exclude' => true
);
```

**Problem:**

In der Backend-Maske wird das neue Feld "seminargebuehr" nicht ausgeben. Der eingeloggte User ist Admin. Wenn man das "exclude"-Feld auf "false" setzt, dann wird das Feld ordnungsgemäß gerendert.

Getestet in den Contao-Versionen 3.5.27 und 4.3.10 (Managed Edition).

**Ursachenforschung:**

Contao lädt die DCA in der Contao/Classes/Backend.php im Bereich um Zeile 364 korrekt ein mit dem Wert 'exclude' => true.

Ein paar Zeilen später im Zeile 380 wird das Feld dann korrekt auf 'false' gesetzt, da ja die nötige Berechtigung durch den Admin-User gegeben ist:
$GLOBALS['TL_DCA'][$strTable]['fields'][$k]['exclude'] = false;

Soweit so gut - nur hat die Tabelle (tl_calendar_events) eine Parent-Table und somit wird diese in Zeile 492 ebenfalls geladen. Ab diesem Zeitpunkt steht in unserem exclude-Feld wieder "true" (unabhänig vom eingeloggten User) und wird später auch im Formular nicht ausgeben.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core/issues/7386 I think.

**Comment by aschempp** [comment]
Hast du die Abhängigkeiten korrekt konfiguriert sodass deine Erweiterung nach "calendar" geladen wird?

**Comment by LinkingYou** [comment]
Innerhalb einer Erweiterung funktioniert das ganze - nur nicht wenn man das eine Feld über die dcaconfig.php definiert. Und bei nur einem Feld wollten wir uns eine Erweiterung sparen. 

Evtl. machen wir jetzt doch eine Erweiterung draus, wenn sich keine Bugfix-Lösung innerhalb von Contao andeutet.

**Comment by aschempp** [comment]
Ah sorry, ich hatte überlesen dass es sich um die dcaconfig.php handelt. Falls du Contao 4 benutzt, tritt das Problem auch in app/Resources/contao/dca/… auf?

**Comment by LinkingYou** [comment]
Hab jetzt eine app/Resources/contao/dca/tl_calendar_events.php mit gleichem Inhalt angelegt. 

Hier ist das Verhalten korrekt und es funktioniert wie gewünscht. Danke für den Tipp.

Noch ein Grund mehr, alles auf Contao 4 zu setzen ... :-)
