### ISSUE TITLE
template selection shows full path to extension template folder under Windows

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#837]
Yet another Windows path problem: when an extension under `system/modules` is present with a `templates` folder and you go to _Templates_ » _New template_, the full path to those extension templates will be shown in the `<optgroup>` label:

![newtemplate](https://cloud.githubusercontent.com/assets/4970961/26247254/592a7bfc-3c9d-11e7-8c5c-b400632a1f86.png)

Responsible code: [src/Resources/contao/dca/tl_templates.php#L249](https://github.com/contao/core-bundle/blob/4.3.10/src/Resources/contao/dca/tl_templates.php#L249)
```php
/** @var SplFileInfo[] $files */
$files = System::getContainer()->get('contao.resource_finder')->findIn('templates')->files()->name('/\.(' . implode('|', $arrAllowed) . ')$/');

foreach ($files as $file)
{
	$strRelpath = str_replace(TL_ROOT . DIRECTORY_SEPARATOR, '', $file->getPathname());
	$strModule = preg_replace('@^(vendor|system/modules)/([^/]+(/.*-bundle)?)/.*$@', '$2', strtr($strRelpath, '\\', '/'));
	$arrAllTemplates[$strModule][$strRelpath] = basename($strRelpath);
}
```
`$file->getPathname()` will be
```
C:\xampp\htdocs\contao4/system/modules/changelanguage/templates\block_alternate_links.html5
```
for example, thus
```php
str_replace(TL_ROOT . DIRECTORY_SEPARATOR, '', $file->getPathname());
```
will not have any effect, because it tries to remove
```
C:\xampp\htdocs\contao4\
```
from the full path. Due to the failure of the `str_replace`, the `preg_replace` also won't have any effect.

**Comment by fritzmg** [comment]
Example output of `$file->getPathname()` for a `vendor` package (e.g. the `core-bundle`):
```
C:\xampp\htdocs\contao4\vendor\contao\core-bundle\src/Resources/contao/templates\analytics\analytics_google.html5
```

**Comment by fritzmg** [comment]
It could be fixed by changing [src/DependencyInjection/Compiler/AddResourcesPathsPass.php#L45](https://github.com/contao/core-bundle/blob/4.3.10/src/DependencyInjection/Compiler/AddResourcesPathsPass.php#L45) from
```php
$paths[] = sprintf('%s/system/modules/%s', $rootDir, $name);
```
to
```php
$paths[] = sprintf('%ssystem/modules/%s', $rootDir . DIRECTORY_SEPARATOR, $name);
```
Not sure if this is the best way to go though.

**Comment by leofeyer** [comment]
I assume it also works if you replace `DIRECTORY_SEPARATOR ` with `'/'` in [line 249](https://github.com/contao/core-bundle/blob/4.3.10/src/Resources/contao/dca/tl_templates.php#L249)?

**Comment by fritzmg** [comment]
No, then it won't work for the vendor paths, because there the root path has a backslash at the end.

**Comment by ausi** [comment]
These kind of issues should disappear in Contao 4.4, because we added a more robust `StringUtil::stripRootDir()` in 8a74bb16f659e5c79b6c428c33360dc3f42264a6.

**Comment by fritzmg** [comment]
@ausi: looks good :)

**Comment by leofeyer** [comment]
Please close the ticket then, so you can re-open it in case the issue occurs in Contao 4.4 as well.

**Comment by fritzmg** [comment]
The assignment from the 4.3.11 milestone should probably be removed.

**Comment by fritzmg** [comment]
The assignment to the 4.3.11 milestone should probably be removed.
