### ISSUE TITLE
backend #container has insufficient height during new template selection

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#838]
1. Log into the Contao back end.
2. Go to _Templates_ » _New template_.
3. Reduce your viewport width to `991px` or less.
4. Click on the __Original template__ dropdown.

You will see that it is cut off. Due to the absent `#left` container, the `#container` will not have enough height anymore to display the content of the dropdown.

![dropdown](https://cloud.githubusercontent.com/assets/4970961/26247596/e9dda7e0-3c9e-11e7-96fb-341c0c2692df.png)

**Comment by leofeyer** [comment]
Fixed in c9659ca261a14e13a7dec5b0e8b4afc6dd97ab13.
