### ISSUE TITLE
Bilder wichtiger Teil über "mehrere bearbeiten" festlegen

### ISSUE THREAD

**Issue by fenepedia** [contao/core-bundle#839]
Wenn ich den wichtigen Teil bei mehreren Bildern gleichzeitig festlegen möchte, dann kann ich bei der Auswahl der Felder zusätzlich auch Koordinaten, sowie Breite als Feld auswählen.

Wenn ich dann im Bearbeitenmodus bin, dann kann ich nur beim 1. Bild den wichtigen Teil mit der Maus auswählen. Bei den anderen Bildern geht das nicht.

Hier sehe ich aber im Gegensatz zum 1. Bild die zusätzlichen Felder für Koordinaten und Breite.

Ist das Verhalten ein Fehler oder technisch nicht anders möglich?

Was ist zu tun:

1. Dateiverwaltung
2. mehrere Bearbeiten aktivieren
3. mehr als 1 Bild auswählen
4. Vorhandene Felder: Alle auswählen
5. Bei Bild 1 kann jetzt der wichtige Teil ausgewählt werden
6. Bei Bild 2 - X ist das nicht per Maus möglich, sondern es werden zusätzliche Felder angezeigt.

Contao 4.3.10

**Comment by fenepedia** [comment]
Habe gerade gesehen, dass die Console JS-Fehler wirft.

<code>
core.min.js:3 Uncaught TypeError: Cannot read property 'getElements' of null
    at h (http://demo.de/bundles/contaocore/core.min.js:3:6950)
    at http://demo.de/assets/mootools/js/mootools.min.js:3:30947
    at Array.forEach (native)
    at Function.forEach (http://demo.de/assets/mootools/js/mootools.min.js:2:2716)
    at Array.each (http://demo.de/assets/mootools/js/mootools.min.js:2:4566)
    at fireEvent (http://demo.de/assets/mootools/js/mootools.min.js:3:30908)
    at HTMLDocument.h (http://demo.de/assets/mootools/js/mootools.min.js:4:25542)
</code>

**Comment by leofeyer** [comment]
@ausi /cc

**Comment by ausi** [comment]
In Contao 3.5 tritt der Fehler nicht auf.
Anscheinend hängt das Problem mit einer Änderung im JavaScript-Code zusammen.

Sollte sich beheben lassen indem wir in [src/Resources/public/core.js:2516](https://github.com/contao/core-bundle/blob/fbbb49334cb100f0cbfbddec09ff32dee24d29de/src/Resources/public/core.js#L2516) `getParent('.tl_tbox')` mit `getParent('.tl_tbox,.tl_box')` ersetzen.

**Comment by leofeyer** [comment]
Behoben in 6022634a67458182463091d1f50e37a0700e55a1.
