### ISSUE TITLE
renaming own layoutsection title (not sync with frontend modules)

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core-bundle#841]
![screenshot-192 168 50 11-2017-05-21-16-32-08](https://cloud.githubusercontent.com/assets/8327905/26284776/1e563aaa-3e43-11e7-80d5-297a54b5a872.png)
If I rename an own layoutsection title under the managed-edition (4.3.10), the name will only update under "own layoutsections" not under "frontend modules".

ps: ofc. I saved after renaming, also cleared prod cache.

**Comment by aschempp** [comment]
you need to save the layout record to apply the changes.

**Comment by NicolasGoerlach** [comment]
As I said: I saved the layout record, nothing change.

**Comment by leofeyer** [comment]
How do I reproduce this in the [online demo](https://demo.contao.org/contao)?

**Comment by fritzmg** [comment]
Hm, I can't reproduce this issue.

**Comment by NicolasGoerlach** [comment]
Hm, works fine now... Don't know what was wrong
