### ISSUE TITLE
Alias-Generierung bei Umlauten

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#842]
Contao 4 erstellt im Gegensatz zu Contao andere Aliase bei Umlauten. Früher wurde aus z.B. ü ue, jetzt steht nur ein u da. Ist das beabsichtigt? Gefunden bei Seiten und Artikeln.

**Comment by fritzmg** [comment]
Duplicate of #635. See https://github.com/contao/core-bundle/issues/560 and https://github.com/contao/core-bundle/pull/569.
