### ISSUE TITLE
mootao unconditionally overwrites options in sortable refactor

### ISSUE THREAD

**Issue by backbone87** [contao/core-bundle#844]
https://github.com/contao/core-bundle/blob/master/src/Resources/public/mootao.js#L268

If i provide options.dragOptions.unDraggableTags myself, mootao just overwrites them...

**Comment by backbone87** [comment]
ref #666

**Comment by leofeyer** [comment]
What are you suggesting?

**Comment by backbone87** [comment]
Check if the array is absent from custom options before overwriting it, else just do nothing.

**Comment by leofeyer** [comment]
Fixed in 5add8a4be667dc30853f149b68c661845dfbf145.
