### ISSUE TITLE
Exception beim Update per Composer und beim Aufruf der install.php

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#845]
Beim Update per Composer bekomme ich seit gestern folgende Fehlermeldung:
![image](https://cloud.githubusercontent.com/assets/2657385/26366018/c883e764-3fe9-11e7-85a6-37fa1fb82d8e.png)
```
Script Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks handling the post-update-cmd event terminated with an exception
                               
  [RuntimeException]                                                
  An error occurred while executing the "contao:symlinks" command.  
```

Letzte Woche war noch alles okay.

Die Symlinks werden aber - soweit ich beurteilen kann - korrekt gesetzt.

Wenn ich versuche, auf die install.php bzw contao/install zuzugreifen, kommt folgender Fehler:
```
[2017-05-23 18:38:57] request.INFO: Matched route "contao_install". {"route":"contao_install","route_parameters":{"_scope":"backend","_token_check":true,"_controller":"Contao\\InstallationBundle\\Controller\\InstallationController::installAction","_route":"contao_install"},"request_uri":"https://***.de/contao/install","method":"GET"} []
[2017-05-23 18:38:57] app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Filesystem\\Exception\\IOException(code: 0): Using the Contao\\RequestToken class has been deprecated and will no longer work in Contao 5.0. Use the Symfony CSRF service via the container instead. at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/LockHandler.php:86)"} []
```
Erinnert mich an https://github.com/contao/managed-edition/issues/6
Wir erhalten eine Warnung/Notice, die aber als CRITICAL Error eingestuft wird.

Ich vermute, dass beide dieselbe Ursache haben (Symfony\\Component\\Filesystem\\Exception\\IOException)

An der Symfony-Version liegt es nicht (ich habe es zurück mit 2.3.6 (aktuell: 2.3.8) probiert).
An contao/core-bundle eigentlich auch nicht (ich bin zurück bis 4.3.7), allerdings bin ich gerade mit meinem Latein am Ende. Letzte Woche funktionierte es noch (da hatte ich aber regelmäßig das Backend-Sprachwechsel-Problem https://github.com/contao/core-bundle/issues/812 ).

Wir verwenden Contao 4.3.10 und PHP 7.0.6 und einen Haufen Erweiterungen.
Composer-Caches, vendor, var/cache sind alle geleert.

Was kann ich machen, um dem Fehler auf die Spur zu kommen?

**Comment by Xendiadyon** [comment]
Die Verbose-Ausgabe:
```                                                     
  [Symfony\Component\Filesystem\Exception\IOException]  
                                                        

Exception trace:
 () at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Filesystem/LockHandler.php:86
 Symfony\Component\Filesystem\LockHandler->lock() at /kunden/***/www/vendor/contao/core-bundle/src/Command/AbstractLockedCommand.php:32
 Contao\CoreBundle\Command\AbstractLockedCommand->execute() at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:853
 Symfony\Component\Console\Application->doRunCommand() at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:200
 Symfony\Component\Console\Application->doRun() at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /kunden/***/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /kunden/***/www/bin/console:33

contao:symlinks [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<target>]

Script Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks handling the post-update-cmd event terminated with an exception

                                                                    
  [RuntimeException]                                                
  An error occurred while executing the "contao:symlinks" command.  
                                                                    

Exception trace:
 () at /kunden/***/www/vendor/contao/core-bundle/src/Composer/ScriptHandler.php:101
 Contao\CoreBundle\Composer\ScriptHandler::executeCommand() at /kunden/***/www/vendor/contao/core-bundle/src/Composer/ScriptHandler.php:43
 Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks() at phar:///kunden/***/www/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:282
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///kunden/***/www/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:205
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///kunden/***/www/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///kunden/***/www/composer.phar/src/Composer/Installer.php:307
 Composer\Installer->run() at phar:///kunden/***/www/composer.phar/src/Composer/Command/UpdateCommand.php:158
 Composer\Command\UpdateCommand->execute() at phar:///kunden/***/www/composer.phar/vendor/symfony/console/Command/Command.php:267
 Symfony\Component\Console\Command\Command->run() at phar:///kunden/***/www/composer.phar/vendor/symfony/console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at phar:///kunden/***/www/composer.phar/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at phar:///kunden/***/www/composer.phar/src/Composer/Console/Application.php:227
 Composer\Console\Application->doRun() at phar:///kunden/***/www/composer.phar/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at phar:///kunden/***/www/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///kunden/***/www/composer.phar/bin/composer:54
 require() at /kunden/***/www/composer.phar:24

```

**Comment by Xendiadyon** [comment]
Update:
Wenn ich im Contao-Backend die Symlinks neu erstelle, erhalte ich denselben Fehler.
Beim zweiten Mal heißt er aber nicht "this class is deprecated" sondern "Trying to get property of non-object". Sagt mir aber leider auch nichts :(

**Comment by Xendiadyon** [comment]
Es geht um die Datei `/tmp/sf.contao-symlinks.59a5ad6d1e94fd76fb1f72c544f6e14ac0dfe26f0441f5e81b370a382e46e65a.lock`

Auf den /tmp-Ordner kann nicht zugegriffen werden, da wir keine Rechte haben... Ich check das mal.

**Comment by Xendiadyon** [comment]
Als Hotfix habe ich nun in der php.ini
  upload_tmp_dir = "/kunden/***/tmp"
  sys_temp_dir = "/kunden/***/tmp"
gesetzt. Unser Admin ist benachrichtigt :)

Frage: Gäbe es Sinn, dass Contao die Schreibrechte des tmp Ordners oder der tmp-Datei überprüft und ggfs. eine verständliche Fehlermeldung auswirft?

**Comment by fritzmg** [comment]
> Frage: Gäbe es Sinn, dass Contao die Schreibrechte des tmp Ordners oder der tmp-Datei überprüft und ggfs. eine verständliche Fehlermeldung auswirft?

In Contao vielleicht nicht, aber der Contao Check macht das bereits.

**Comment by Xendiadyon** [comment]
Aber jedenfalls sollte diese Stelle überarbeitet werden, damit die korrekte Fehlermeldung ausgeworfen wird. 
Ich gehe mal stark davon aus, dass zumindest die fehlerhafte Ausgabe des Fehlers ein Symfony-Problem ist https://github.com/symfony/symfony/issues/22882

Noch lieber wäre es mir aber, dass Contao bei der Installation bemerkt, wenn es ein Problem mit tmp gibt und dort (selbstständig) Abhilfe schaffen könnte.

**Comment by fritzmg** [comment]
> Noch lieber wäre es mir aber, dass Contao bei der Installation bemerkt, wenn es ein Problem mit tmp gibt und dort (selbstständig) Abhilfe schaffen könnte.

Contao 4 hat ja auch noch andere Systemvoraussetzungen, auf die es nicht selbst prüft. Dafür ist der Contao Check da.

**Comment by leofeyer** [comment]
Die php.ini-Werte `upload_tmp_dir` und `sys_temp_dir` müssen natürlich so gesetzt sein, dass der PHP-Prozess auch auf die Ordner zugreifen kann, was Aufgabe des Serveradmins ist. Das gilt sowohl für das PHP-Binary des Webprozesses als auch für das des CLI-Prozesses.
