### ISSUE TITLE
4.4.0-RC1 - BE styles

### ISSUE THREAD

**Issue by squidi** [contao/core-bundle#846]
Hi,

für das BE sieht das derzeit so aus mit dem aktuellen Flexible Theme :(

![bildschirmfoto 2017-05-24 um 08 26 09](https://cloud.githubusercontent.com/assets/488443/26389760/cc91267e-405b-11e7-8bcc-1c9846b5f40d.png)

**Comment by squidi** [comment]
Alternativ habe ich das Flexible Theme aus 4.4.0-beta1 in den Theme-Ordner geladen :)

![bildschirmfoto 2017-05-24 um 08 27 18](https://cloud.githubusercontent.com/assets/488443/26390482/02d58e66-405f-11e7-909d-c97ce34c8dba.png)

**Comment by leofeyer** [comment]
Behoben in b14294c2ead92f2c02ca3a232f036ec2603296df.
