### ISSUE TITLE
[4.4.0-RC1] Chosen dropdowns malfunction

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#847]
As can be seen on the screens, the chosen fields are displaying malformed labels.
![chosen_issue_1](https://cloud.githubusercontent.com/assets/1228764/26395456/526a9d16-4070-11e7-8c0f-26463df30b46.png)
![chosen_issue_2](https://cloud.githubusercontent.com/assets/1228764/26395460/554400fe-4070-11e7-87ab-f1d894b23f69.png)

**Comment by squidi** [comment]
Hatte ich in der 4.4.0-beta1 auch schon. Ich meine es hängt mit dem installieren von Erweiterungen zusammen, wobei dieser Fehler auch beim löschen der Erweiterung bestehen bleibt und auch nach dem updaten auf 4.4.0-RC1.

Bei der frischen jungfräulichen 4.4.0-RC1 sieht alles gut aus.

**Comment by ben-eSM** [comment]
Ich hatte das auch schon in den letzten dev-developer nach 4.4.0-beta1. Aber bei mir besteht das Problem ohne das ich Erweiterungen installiert habe. Prinzipiell eine jungfäuliche Installation, welche lediglich per composer update mittlerweile auf RC1 gehievt wurde.

**Comment by ausi** [comment]
Bringt das leeren des Browsercaches oder der Inkognitomodus einen Unterschied?

**Comment by ben-eSM** [comment]
@ausi Nein, weder Browsercache leeren, noch der Versuch eventuell über `console cache::clear` das Problem zu beheben.

**Comment by ben-eSM** [comment]
I found the issue. The malformed chosen fields are linked to ´contao-components/chosen v1.1.4´ released 8 days ago. If I roll back to v1.1.3, the chosen fields are displayed properly.

**Comment by leofeyer** [comment]
I cannot reproduce the issue. Which browser and OS?

**Comment by squidi** [comment]
Hab das Problem nicht mehr gehabt mit 4.4.0-RC1 und dev-release.
OSX 10.10 - Safari 10.1.1

**Comment by ben-eSM** [comment]
I can't reproduce it anymore, either. Could a newer core-bundle commit influenced the display behaviour?
Before it was always reproducible for me whenever I let composer install `contao-components/chosen v1.1.4`.
However, it works now, so issue can be closed.
