### ISSUE TITLE
ESI breaks the nested insert tags

### ISSUE THREAD

**Issue by qzminski** [contao/core-bundle#849]
The ESI seems to break the nested insert tags (https://github.com/codefog/contao-haste/issues/106). For example if we have an insert tag `{{options_label::45::{{post::anrede}}}}` it would compile to:

```
/vendor/contao/core-bundle/src/Controller/InsertTagsController.php:57:string 
'{{options_label::45::<esi:include src="/_fragment?_path=insertTag%3D%257B%257Bpost%253A%253Aanrede%257Cuncached%257D%257D%26_format%3Dhtml%26_locale%3Den%26_controller%3Dcontao.controller.insert_tags%253ArenderAction&_hash=VxEWZAAouUOI3LMJsG8fHf1DbwWUpezpRXeKsWPsXOU%3D" onerror="continue" />|uncached}}' (length=303)
```

Due to fragment handler usage in https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L123

**Comment by aschempp** [comment]
The solution is probably not to replace insert tags from inside out, but detect nested insert tags. 

 1. Do not check for `{}´ inside insert tag here: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L81
 2. Check for `{{` if the insert tag is not to be cached (https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L126)
 3. Not sure if we still need the recursion check at https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/InsertTags.php#L53

**Comment by leofeyer** [comment]
@Toflar @ausi /cc

**Comment by ausi** [comment]
I’m not sure if uncached insert-tags inside another insert-tag should be a supported use-case.

Using the `{{post::*}}` insert tag this way is also a security problem IMO.

**Comment by aschempp** [comment]
I agree, but it does not work if you "uncache" the main insert tag either…

**Comment by ausi** [comment]
I think the inner insert tag must be cached one, the outer can be `uncache`d.

**Comment by aschempp** [comment]
Well in this case both are uncached? For whatever reason…?

**Comment by ausi** [comment]
`{{post::*}}` is always uncached IMO, because the value changes on every request.

**Comment by Toflar** [comment]
Imho, when one nested insert tag is uncached, the outer one needs to become an uncached one too. Then it should work, no?

**Comment by qzminski** [comment]
Here is the solution suggested by @aschempp and what he says is that the other ways are too complicated:

```php
// FrontendTemplate.php#L134
$this->strBuffer = $this->replaceInsertTags($this->strBuffer, $GLOBALS['objPage']->cache > 0);
```

I have tested it and it works.

**Comment by leofeyer** [comment]
If @ausi agrees, I'll change the `FrontendTemplate` class accordingly.

**Comment by xchs** [comment]
I can also confirm that the fix proposed by @aschempp and @qzminski has solved my issue. Thanks a lot.

**Comment by ausi** [comment]
> Imho, when one nested insert tag is uncached, the outer one needs to become an uncached one too. Then it should work, no?

I’m not sure if the insert tags controller that handles the fragments searches for nested ESI tags in the insert tag string, otherwise it would not work I think.

Regarding the change adding `$GLOBALS['objPage']->cache > 0`:

> I have tested it and it works.

Did you also test if it still works if you set a cache time for the affected page?
If this solution is only a fix for not-cached pages, I don’t think we should add it.

**Comment by xchs** [comment]
> Did you also test if it still works if you set a cache time for the affected page?
> If this solution is only a fix for not-cached pages, I don’t think we should add it.

Too bad. Unfortunately, the fix does not work anymore.

**Comment by Toflar** [comment]
It is the easiest "fix". It does not make a lot of sense to cache a page when it has dynamic content on it. Right now it does not work at all. The change makes sure you **can** fix it by setting the page to uncached. A real fix to this problem would be very hard to implement.

**Comment by leofeyer** [comment]
> I’m not sure if uncached insert-tags inside another insert-tag should be a supported use-case.

I second @ausi's point of view that this is not a supported use case.

> Using the `{{post::*}}` insert tag this way is also a security problem IMO.

Did you all read and understand this? 😄

**Comment by backbone87** [comment]
Since i didnt follow the whole discussion: uncached insert tags inside another uncached insert tag would still be possible?

**Comment by aschempp** [comment]
No. Uncached inserttag inside inserttag (regardless of type) only works if the page is not cached at all.

**Comment by xchs** [comment]
So what else do you suggest when it comes to output an **option label** on a form confirmation page? Since the `{{options_label::*::{{post::foo}}}}` construct does not work unfortunately: someone knows a better way to retrieve the option label?

**Comment by ausi** [comment]
`\FormFieldModel::findByPk($id)`, see [library/Haste/Util/InsertTag.php:166](https://github.com/codefog/contao-haste/blob/693e3d7cc4828655c3553f0e20dc1b1c23c9ffeb/library/Haste/Util/InsertTag.php#L166)

**Comment by xchs** [comment]
?

It is a pity that Contao currently does not provide insert tags for form handling given that we have insert tags for almost everything else.

Regarding the `{{post::*}}` insert tag: considering the comments
> Using the {{post::*}} insert tag this way is also a security problem IMO.

> Did you all read and understand this?

the [insert tag description](https://docs.contao.org/books/manual/4.3/en/04-managing-content/insert-tags.html#miscellaneous)

> This tag will be replaced by a given POST variable. **It could be used to display fields from a submitted form.**

seems to be wrong, actually.
