### ISSUE TITLE
size of "own javascript-code" & "additional <head>-tags" under pagelayout

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core-bundle#850]
need to be 100% instead of 50%.
![bildschirmfoto 2017-05-27 um 00 17 19](https://cloud.githubusercontent.com/assets/8327905/26514408/e77afee8-4271-11e7-8f27-5683707e90ca.png)
![bildschirmfoto 2017-05-27 um 00 17 31](https://cloud.githubusercontent.com/assets/8327905/26514409/e78653d8-4271-11e7-88ed-53f6b1c890e4.png)

**Comment by leofeyer** [comment]
See #827.
