### ISSUE TITLE
width "Included modules" need to be expanded

### ISSUE THREAD

**Issue by NicolasGoerlach** [contao/core-bundle#851]
can we pls use the same width like in 3.5?
Module names can be very long.
![bildschirmfoto 2017-05-27 um 00 18 55](https://cloud.githubusercontent.com/assets/8327905/26514449/3a456a1e-4272-11e7-9125-87abdfae44b0.png)
![bildschirmfoto 2017-05-27 um 00 19 01](https://cloud.githubusercontent.com/assets/8327905/26514448/3a452f22-4272-11e7-89f9-5f69af89a441.png)

**Comment by fritzmg** [comment]
Also the width stays when adding a new module. It does not expand automatically, when the new module has a longer name than the previous ones. The width is only updated when saving.

**Comment by leofeyer** [comment]
This has been fixed in the latest `release/4.0.0` branch.
