### ISSUE TITLE
Add github topics to contao repositories

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao/core-bundle#853]
In January github [topics were introduced](https://github.com/blog/2309-introducing-topics). This helps to find similar repositories. For example to find all contao modules available on github. 

![symfony symfony the symfony php framework](https://cloud.githubusercontent.com/assets/2045722/26522221/ba9ea142-42fb-11e7-8d63-5b5251a9df48.png)

Contao repositories itself should support it, and also give recommendations for extension developers which tags should be used.

For example there are already some using [contao-bundle](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acontao-bundle&type=Repositories), some [contao-module](https://github.com/search?utf8=%E2%9C%93&q=topic%3Acontao-module&type=Repositories) and others using [contao-extension](https://github.com/search?q=topic%3Acontao-extension&type=Repositories).
This is not good and should be more homogen.

Edit: Picture added

**Comment by leofeyer** [comment]
Both `contao-bundle` and `contao-module` are valid Composer types and therefore valid GitHub topics (see [contao-mailchimp](https://github.com/1up-lab/contao-mailchimp/blob/master/composer.json#L5) and [contao-xing-bundle](https://github.com/BugBuster1701/contao-xing-bundle/blob/master/composer.json#L5) for example). They should not be mixed up.

**Comment by leofeyer** [comment]
Here's what I would suggest:

**Contao core**
`contao` `cms` `php` `symfony` `symfony-bundle`

**Contao 4 bundles**
`contao` `cms` `php` `symfony` `contao-bundle` + specific tags

**Contao modules**
`contao` `cms` `php` `contao-module` + specific tags

Specific tags are tags that describe the purpose of the package such as `calendar` `events` for the Contao calendar bundle or `isotope` `ecommerce` `shop` for Isotope.

**Comment by leofeyer** [comment]
I have added topics to all Contao packages.

**Comment by discordier** [comment]
Would maybe make sense to add some guideline to the docs for extension developers?

**Comment by leofeyer** [comment]
To which docs?

**Comment by DanielSchwiperich** [comment]
Could be put here: https://docs.contao.org/books/extending-contao4/

But if all the contao bundles follow the same schema than an extension developer should imho easily understand how it's intended
