### ISSUE TITLE
[4.4.0-dev] Commit #8ecb142 results in bad font rendering on Chrome (Windows)

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#854]
At least on my Desktop the font renders almost unreadable.
Especially in light font width some chars are to thin and distorted (e.g. the letter "e").
Can someone else confirm this?

![contao_font_rendering](https://cloud.githubusercontent.com/assets/1228764/26542690/3e93fe38-445b-11e7-8b68-650c2d36307e.png)

**Comment by fenepedia** [comment]
Which Browser an OS do you use?

**Comment by leofeyer** [comment]
You mean 8ecb14281ee2fbb29277a2d6fcf0cef4d6c65458 made it worse? Because it actually improved the font rendering on our test systems. Also, before 8ecb14281ee2fbb29277a2d6fcf0cef4d6c65458 we were using Lato version 1 and now we are using the current version 2.

**Comment by ben-eSM** [comment]
As odd as it sounds, but yes, version 2 made it worse. Even in Firefox it doesn't render very well.
I can't compare it to my other Windows machine atm. But if it's a generic issue for Windows, I shouldn't be the only one.

@fenepedia mentioned in topic headline except Windows version which is 10 (Build 1703)

**Comment by leofeyer** [comment]
I have changed the fonts in 7648433f183644331b2596e458834404407a36fe. It will now use a font weight of 400 and 600 on non-retina displays and 300 and 500 on retina display.

@ben-eSM @fenepedia Does this fix your issues?

**Comment by fenepedia** [comment]
Looks great for me! Thank you.

**Comment by ben-eSM** [comment]
Looks great on my end, too! Thanks!
