### ISSUE TITLE
4.4.0-RC1 - Dateiverwaltung "Auswahl aufheben"

### ISSUE THREAD

**Issue by squidi** [contao/core-bundle#856]
Mir fehlt in der Dateiverwaltung "Auswahl aufheben"

Zwar ist es jetzt z.b. im Contentelement Galerie möglich, per Klick einzelne Dateien als Quelldatei zu entfernen, was aber durchaus zu vielen Klicks führen kann, bei einer grossen Anzahl von Bildern.

Ich würde es daher begrüssen, wenn es trotzdem weiterhin in der Dateiverwaltung "Auswahl aufheben" geben würde.

**Comment by fenepedia** [comment]
Als Workaround kannst du vorerst 2x auf "Alle auswählen" klicken. Zuerst werden dann alle markiert und dann die Markierungen entfernt.

**Comment by leofeyer** [comment]
"Auswahl aufheben" gibt es nur bei Radio-Buttons. Bei Checkboxen musst Du es so machen, wie es @fenepedia beschrieben hat.

**Comment by squidi** [comment]
Muss da noch mal einhaken => "Auswahl aufheben" gibt es nur bei Radio-Buttons.

Auch wenn nur Radio-Buttons zur Auswahl stehen, gibt es diese Funktion nicht mehr in der Dateiverwaltung, so wie es noch in 4.3.x vorhanden war. Heisst man müsste in einer Erweiterung zwangsläufig immer ein "addImage" verwenden. :(

**Comment by leofeyer** [comment]
> gibt es diese Funktion nicht mehr in der Dateiverwaltung, so wie es noch in 4.3.x vorhanden war

Kannst Du bitte einen Screenshot von der Funktion in Contao 4.3 posten?

**Comment by squidi** [comment]
Ja hier dies meine ich

![bildschirmfoto 2017-05-30 um 12 00 22](https://cloud.githubusercontent.com/assets/488443/26578354/d037089c-452f-11e7-884a-4e03e7b36c9b.png)

**Comment by squidi** [comment]
Hat man z.b. in einer Erweiterung auch Images ohne *mandatory'=>true* und diese einmal ausgewählt, bekommt man die Auswahl nicht mehr aufgehoben und verbleibt in der DB.

**Comment by squidi** [comment]
Meiner Meinung nach ist das ein Bug.

Sowohl in 4.3.x als auch in 4.4.0-RC1 wird das in der FileSelector.php ( Zeile 279 bis 293 ) definiert. Lediglich in der 4.4.0-RC1 erscheint es dann nicht im Popup der Dateiauswahl :(

**Comment by leofeyer** [comment]
Behoben in 313080701cde15aca3e6ea32df9139f1c052e196.

**Comment by fenepedia** [comment]
Kannst du das noch rechtsbündig ausrichten?

**Comment by leofeyer** [comment]
Ist rechtsbündig bei mir.

**Comment by fenepedia** [comment]
Sorry, mein Fehler, war ein Caching-Problem. Ist bei mir jetzt auch rechtsbündig.

**Comment by squidi** [comment]
Bei mir ist auch alles super jetzt, danke :)

![bildschirmfoto 2017-06-06 um 20 42 59](https://user-images.githubusercontent.com/488443/26846073-efb4666e-4af8-11e7-946e-013665d023d0.png)
