### ISSUE TITLE
Inserttag mit strtoupper Option wandelt Umlaute nicht in Großbuchstaben

### ISSUE THREAD

**Issue by Ainschy** [contao/core-bundle#859]
Eher durch Zufall bin ich darüber gestolpert das z.B. bei {{page::title|strtoupper}} die Umlaute nicht in Großbuchstaben umgewandelt werden. Bereits großgeschrieben Umlaute werden korrekt groß dargestellt.

Der Bug ist auch unter 3.5 zu finden.

In der Demo überprüft.

**Comment by Toflar** [comment]
`utf8_strtoupper? :)

**Comment by Ainschy** [comment]
hmpf ... muss ich wohl übersehen haben ... Danke @Toflar
