### ISSUE TITLE
Install-Tool lässt sich nicht mehr öffnen

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#864]
Contao-Version 4.3.11

Ich erhalte beim Aufruf des Installtools folgende Fehlermeldung:
![image](https://user-images.githubusercontent.com/2657385/26837986-29bd6d98-4adf-11e7-803a-cf6fed4a5e28.png)
1. Dort steht noch app/console. Es müsste bin/console heißen.
2. Ich glaube eigentlich nicht, dass hier jemand das Installtool falsch eingegeben hätte.

![image](https://user-images.githubusercontent.com/2657385/26838005-33d0200a-4adf-11e7-8316-5fe6f46b7177.png)
3. Das Löschen des Caches bringt gar nichts.

Ich habe den composer-cache und vendor komplett gelöscht und installiere gerade alles noch mal neu.
Die Installation läuft sauber durch, das Install-Tool sperrt sich aber noch immer. Hilfe?

![image](https://user-images.githubusercontent.com/2657385/26838083-68877140-4adf-11e7-8ee5-b59a027fec74.png)
~~4. Was mich wundert (eventuell hat das einen Zusammenhang): ich kann mir gerade auch nicht per Composer die installierten Packages anzeigen lassen.~~ Edit: Die Caches waren gelöscht. Nach der Neuinstallation funktioniert zumindest das wieder.

Vielen Dank!

**Comment by xchs** [comment]
Related issue: https://github.com/contao/managed-edition/issues/14
