### ISSUE TITLE
4.4.0 dev - Systemwartung

### ISSUE THREAD

**Issue by squidi** [contao/core-bundle#865]
Für die Ansicht > Systemwartung fehlt noch für die Tabelle eine width: 100%; bzw. class für das BE-Layout ohne max. Breite.

![bildschirmfoto 2017-06-07 um 12 44 03](https://user-images.githubusercontent.com/488443/26875043-690837ca-4b80-11e7-9040-b6a0b31f9b7e.png)

![bildschirmfoto 2017-06-07 um 12 43 20](https://user-images.githubusercontent.com/488443/26875054-71b6001e-4b80-11e7-80f9-60a0b3bc9800.png)

**Comment by leofeyer** [comment]
Fixed in fca703384a60ff600ae9641dd558a4be9056b5a7.
