### ISSUE TITLE
Calling install.php causes translation of xliff files to be missing

### ISSUE THREAD

**Issue by Defcon0** [contao/core-bundle#866]
After calling install.php in an existing installation and reentering contao, the translation is gone (at least for xliff files it seems). -> see attachment

Contao version: 4.3.11 (managed)

After calling composer run-script post-update-cmd the translation is in place again.

![screen](https://user-images.githubusercontent.com/1485098/26934439-ae17457e-4c69-11e7-942f-6d4d01562df9.png)

**Comment by leofeyer** [comment]
Can this be reproduced somehow?

**Comment by fritzmg** [comment]
I have seen this before as well, but I was unable to reproduce it a second time.

**Comment by Defcon0** [comment]
Mhm, in my installation this can be reproduced easily by accessing the install.php. But later on I can check in a fresh managed edition. Could be related to third party modules, but in contao 3.x we never had the issue.
