### ISSUE TITLE
Theme import symlinks

### ISSUE THREAD

**Issue by ausi** [contao/core-bundle#867]
If a theme with public folders gets imported, the symlinks for these folders are missing. I think after extracting the theme files and importing the xml we should execute `Automator->generateSymlinks()`.

**Comment by leofeyer** [comment]
You mean [here](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/Theme.php#L693)?

**Comment by ausi** [comment]
yes

**Comment by leofeyer** [comment]
Fixed in 20573ee22e62c22578d3c2eb7d8cec2269d9ca8e.
