### ISSUE TITLE
Backend navigation: padding on list items and anchors

### ISSUE THREAD

**Issue by bezin** [contao/core-bundle#873]
Hi there,

the backend navigation has a minor styling and usability issue: 

The top and bottom padding on the level 2 list items leave a gap between all the level 2 anchor. Hovering over the gap triggers the anchor hover, giving the user the impression, that you can interact with the link and may click it. 

This could easily be solved by applying the hover styles to the anchor itself rather than the list item, as well as the top and bottom padding of 6px. 

Cheerio

**Comment by leofeyer** [comment]
Can you upload a screenshot please?

**Comment by bezin** [comment]
Sure, here you are: [Screenshot Backend Styles](https://share.presentprogressive.de/backend_nav_styles.gif)

**Comment by leofeyer** [comment]
```css
#tl_navigation .tl_level_2 li {
    cursor: pointer;
}
```

Does this fix the issue?

**Comment by leofeyer** [comment]
Ah, forget about it. It cannot fix the issue of course. 😄

**Comment by leofeyer** [comment]
Fixed in adc6427c579bf5dfe35f9253359ade99773a2fd3.
