### ISSUE TITLE
Layout: The allowed template types are ignored

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#875]
Contao lists all templates in the layouts, even if they do not have any of the supported file extensions.

To reproduce:
* <kbd>Layout</kbd> > <kbd>Templates</kbd> > <kbd>Create a new template</kbd>
* Select e.g. the template `j_mediaelement.html5` and store a copy in the target folder
* Rename the template copy to e.g. `j_foo.html5`
* <kbd>Layout</kbd> > <kbd>Themes</kbd> > <kbd>Page layouts</kbd> > Edit a layout
* Scroll down to the "jQuery" section: the new template `j_foo` is listed among all the other "jQuery templates"
* Open a console window and remove the file extension of the template: `j_foo.html5` > `j_foo`
* Switch back to the Contao back end
* <kbd>Layout</kbd> > <kbd>Templates</kbd>
* The template `j_foo` now disappeared since it matches none of the supported default template file types (see  <kbd>System</kbd> > <kbd>Settings</kbd> > <kbd>Template file types</kbd>)
* Open again <kbd>Layout</kbd> > <kbd>Themes</kbd> > <kbd>Page layouts</kbd> > Edit a layout
* The  template `j_foo` is still listed in the "jQuery templates" section, although it does not match any of the supported template file types anymore.

**Comment by agoat** [comment]
I think it's not intended to change the suffix of the template files via the console. In the template editor only the name can be changed, not the suffix. 

But it's generally the question whether we need a list with template file types at all. Currently only html5 files are used. Everything else is just a relic from the time of xhtml.
AFAIK the twig template system will be used in the future.

**Comment by xchs** [comment]
> I think it's not intended to change the suffix of the template files via the console.

Why not? I used to use this a lot, e.g. to (temporarily) disable a template (`j_mediaelement.html5` > `j_mediaelement.html5.bak`).

**Comment by agoat** [comment]
> I used to use this a lot, e.g. to (temporarily) disable a template (j_mediaelement.html5 > j_mediaelement.html5.bak).

Why not simply rename it in the template editor instead on the console like so: `j_mediaelement.html5` > `j_mediaelement_bak.html5`

**Comment by xchs** [comment]
> Why not simply rename it in the template editor instead on the console like so: j_mediaelement.html5 > j_mediaelement_bak.html5

No, sorry, that would make no sense (to me). The template would still be visible everywhere in the back end.
Apart from that: I'm a lot faster to do such things on the console or via FTP client (since these programs are open anyway most of the time).

In any case, that does not matter here at all.

**Comment by agoat** [comment]
> No, sorry, that would make no sense (to me). The template would still be visible everywhere in the back end.

I don't know your workflow and team constellation, but I think there is a good reason why you do it this way.

> In any case, that does not matter here at all.

Right. To solve the problem we will have to check against the allowed Templatefile suffixes in the method `getTemplateGroup` in the [Controller class](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Controller.php#L93).

**Comment by leofeyer** [comment]
Fixed in 35e4ea925c2161046622b2a4490510ed80dec071.
