### ISSUE TITLE
MetaWizard: add a tooltip for the delete icon

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#877]
There is no tooltip for the delete icon in the MetaWizard widget 'cause the `title` attribute is missing (see https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/MetaWizard.php#L141)

![metawizard_delete](https://user-images.githubusercontent.com/1218766/27246456-03e2fd52-52f2-11e7-9278-c742c902e8b5.png)

**Comment by leofeyer** [comment]
Fixed in 6a6c792c8c6ec0417790283188810e98cb784f5b.
