### ISSUE TITLE
DCA picker: edit multiple records at once

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#881]
For the probably most unusual case that someone (like me 😄 ) selects all records in the DCA picker, Contao cannot handle the link target properly.

To reproduce:
* open an arbitrary article and edit a (text) content element
* insert a new link and open the DCA (page) picker to select a link target
* click "Edit multiple" and "Select all" records
* <kbd>Apply</kbd> the changes
* Contao adds something like `on,1,19,16,2,48,51,52,53,54,55,56,57,49,63,64,58,8,59,70,61,60,62,71,66,50,31,67,43,44,32,34,41,28` in the link URL field

Would it make sense to disable those button functions (except "Toggle all") in the DCA picker?

Admittedly, the described scenario is more of a test case. 😸

**Comment by aschempp** [comment]
Select-Multiple does not make sense here at all in my opinion.

**Comment by leofeyer** [comment]
But what if I want to edit multiple records prior to selecting?

**Comment by aschempp** [comment]
well don't use the popup for that 😂

**Comment by aschempp** [comment]
Will be fixed in #950 (6a7d052a4b08047e4d42cd9f084d27d195aea0b1)
