### ISSUE TITLE
Seitenstruktur: Interne Weiterleitung zeigt Modal ohne Radio-Buttons

### ISSUE THREAD

**Issue by denniserdmann** [contao/core-bundle#883]
Wenn ich eine interne Weiterleitung anlegen will, fehlen die Radio-Buttons, um eine Seite auszuwählen, siehe Screenshot. 
<img width="634" alt="modal-interne-weiterleitung" src="https://user-images.githubusercontent.com/3773697/27261757-d9d35436-5449-11e7-99c4-3c8ec4110906.png">

**Comment by pwaldhauer** [comment]
@leofeyer Gibt's eine Timeline für 4.4.1? Der Bug scheint mir recht groß (ich setze gerade ein Contao auf, Mehrsprachig, und würde gerne die Seitenzuordnungen für das ChangeLanguage-Plugin vornehmen, das geht nun leider aber nicht, also muss ich es in der Datenbank manuell machen, was der Kunde natürlich nicht machen kann).

**Comment by leofeyer** [comment]
Nein, gibt es nicht. Voraussichtlich im Laufe der nächsten Woche.

**Comment by OMOSde** [comment]
Der gleiche Fehler tritt auf, wenn ich das DCA von tl_page mit einem eigenem pageTree-Feld erweitere. Wenn ich das DCA anderer Tabellen um das gleiche Feld erweitere sind die Auswahl-Buttons vorhanden.

**Comment by aschempp** [comment]
see #906
