### ISSUE TITLE
Change yellow radio buttons in dcaPicker

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#884]
As we already noticed on the conference, the yellow backgrounds are quite confusing. Why do we not simply use the same text as we do with the past button, just a "select an option" above the tree?

**Comment by ausi** [comment]
I don’t like the yellow background too, but we already discussed this in https://github.com/contao/core-bundle/pull/755#issuecomment-294210756

>> The backend style of Contao consists mostly of white and light-gray areas with gray borders. Isn’t the yellow background of the checkboxes/radios too much?
> 
> I don't think so. It just draws enough attention so you realize what you need to do. 😄

**Comment by aschempp** [comment]
Well but apparently noone came up with the idea to use the already-existing hint :P

**Comment by leofeyer** [comment]
Yes, I did. But I like the yellow background better.

**Comment by leofeyer** [comment]
Also, I think the paste hint does not really work in this case:

<img width="922" alt="" src="https://user-images.githubusercontent.com/1192057/27826520-a1040b7a-60b3-11e7-9854-d3a9d1151ee8.png">

<img width="928" alt="" src="https://user-images.githubusercontent.com/1192057/27826530-a7262a6a-60b3-11e7-9522-58b2de19d6fa.png">

Especially in the parent view, the arrow points to the "edit header" icon, which is confusing.

**Comment by planepix** [comment]
Why not using the same orange color value ( #F47C00 ) as used in the header?

**Comment by aschempp** [comment]
![bildschirmfoto 2017-07-13 um 16 17 26](https://user-images.githubusercontent.com/1073273/28170815-c768ebc0-67e6-11e7-9555-762b438c260b.png)

**Comment by leofeyer** [comment]
<img width="901" alt="" src="https://user-images.githubusercontent.com/1192057/28170876-f048847e-67e6-11e7-8aaf-91f074cb82fd.png">

**Comment by aschempp** [comment]
![bildschirmfoto 2017-07-13 um 16 20 01](https://user-images.githubusercontent.com/1073273/28170934-244d49c6-67e7-11e7-9b4a-44eccc146592.png)

**Comment by leofeyer** [comment]
<img width="900" alt="" src="https://user-images.githubusercontent.com/1192057/28170976-4d20fdca-67e7-11e7-8985-ed31614ff7c4.png">

**Comment by leofeyer** [comment]
<img width="899" alt="" src="https://user-images.githubusercontent.com/1192057/28171112-b81193d8-67e7-11e7-90ff-81aba8386ace.png">

**Comment by leofeyer** [comment]
<img width="900" alt="" src="https://user-images.githubusercontent.com/1192057/28171307-443e7a60-67e8-11e7-90b6-a137da7cacf8.png">

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, we want to change the color to `#f0f0f2`. Additionally, we want to try how a left border would look like.

**Comment by leofeyer** [comment]
Changed in 61269523ddc9f11976fed978f4ab13082c2c1902. I wasn't able to add a border.
