### ISSUE TITLE
Contao 4.4 standard-edition, install script problem

### ISSUE THREAD

**Issue by tsarma** [contao/core-bundle#885]
When I run Install script in Contao 4.4.0. The first step -> "CREATE TABLE" and "Update database" remains active all the time, even after tables are created. It does not give feed back "The database is up to date", like it used to do.

I have asked in Contao forum and it seems others have the issue too. 
https://community.contao.org/en/showthread.php?23655-Contao-4-4-standard-edition-install-script-problem

**Comment by ben-eSM** [comment]
I do encounter a similar issue with one project running Contao 4.4 on ``PHP 5.6``.
However, some other project running on ``PHP 7`` seem not to having this issue.
@tsarma What PHP Version are you running?

**Comment by aschempp** [comment]
This could be related to OpCode Cache

**Comment by ben-eSM** [comment]
@aschempp You're correct! I just tested it without opcache enabled. This fixes the problem temporarily.
Thought of that before, but didn't test it until now.

**Comment by tsarma** [comment]
@ben-eSM I tried it on both php 5.6 and php 7.1 without success. Also on machine with php 5.6, I have opcache disabled, but no success

**Comment by tsarma** [comment]
I think I've found the source of this issue. It is caused by the introduction of `Installer::dropNonContaoTables` 

Basically there should be two changes required.
1. `$toSchema = $this->dropNonContaoTables($this->schemaProvider->createSchema());` should not be wrapped inside `dropNonContaoTables` function. Thus it should be 
```php 
$toSchema = $this->schemaProvider->createSchema(); 
```
2. `if (0 !== strpos($tableName, $needle))` condition inside function `dropNonContaoTables` should be change to, otherwise Schema _tables array is empty
```php
if (false !== strpos($tableName, $needle))
```

**Comment by ben-eSM** [comment]
If this is confirmed, the ticket should be split in 2 separate ones as the OpCode Cache issue still stands.

**Comment by aschempp** [comment]
Can you explain the problem? It does not yet make sense to me. The whole point is to remove tables that do not start with `tl_` from the install tool.

Applying 1. would mean these will be included, which is not what we want
Applying 2. would mean the table name can appear somewhere within the name instead of at the beginning. Does not make sense to me?

**Comment by tsarma** [comment]
@aschempp You are correct. I was a completely thinking in the wrong way. 
I got tripped off by `if (0 !== strpos($tableName, $needle))` always returning false in my case. But now once again I think, I knew the reason.

Inside Doctrine Schema class Table names are always converted to lowercase string, 
`$tableName = $table->getFullQualifiedName($this->getName());` 

 and where as
`$schema->getName()` just returns the database name. (My database name contained uppercase string).

If we also convert the `$needle` inside `dropNonContaoTables` also to lowercase, then the problem should be solved.

**Comment by aschempp** [comment]
see https://github.com/contao/installation-bundle/pull/59

**Comment by tsarma** [comment]
Thank you. I close this issue as it is solved now.
