### ISSUE TITLE
Contao 4.4: new DCA picker does not work for non-admins

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#886]
### Reproduction

1. Log-in as a non-admin user.
2. Create a new text element and write some text.
3. Select the text and choose _Edit/insert link_.
4. Click on the "browse" icon.

You will see the message "Forbidden - Invalid content element ID".

### Cause

The picker popup is opened with the following GET parameters:

```
array(5) {
  ["target"] => string(20) "tl_content.singleSRC"
  ["value"] => string(2) "10"
  ["context"] => string(4) "link"
  ["popup"] => string(1) "1"
  ["do"] => string(4) "page"
}
```
However, the function `tl_content::checkPermissions` requires an `id` parameter, containing the `id` of the article. Since this is missing, `tl_content::checkAccessToElement` is called with `NULL` for `$id` and thus the `AccessDeniedException` with `Invalid content element ID ` is thrown.

It still works for admins, since no such permissions are checked for admins of course.

**Comment by ausi** [comment]
I can confirm this issue in Contao 4.4.0. It also happens with the page picker for the “Image link target” field where the `target` parameter is set to something like `tl_content.imageUrl.123` where `123` is the ID of the content element.

**Comment by rabauss** [comment]
we have similiar problems with the new dca-picker in the isotope filetree popup.
All users (also admins) get permission errors ("File or folder "" is not within the files directory.") for actions in the filetree for product attributes.
we discovered, that without the get-parameter 'target' the actions are allowed.

for uploads via dropzone there is a backlink missing in the lightbox!

**Comment by leofeyer** [comment]
@contao/developers I have no idea how to fix this except removing the permission check here:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_content.php#L902

But that also seems like a bad idea. 😄

**Comment by leofeyer** [comment]
Here's another solution. We could replace [this line](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/classes/DataContainer.php#L892) with:

```php
$ref = new \ReflectionClass($strDriver);
$objDca = $ref->newInstanceWithoutConstructor();
```

This would prevent the `onload_callback` from being executed. Side effects are possible though.

**Comment by leofeyer** [comment]
Here's the PR as discussed: #926
