### ISSUE TITLE
Update auf Contao 4.4: böse Falle bei "Metadaten überschreiben" für Bilder

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#888]
Wir haben ein Update von Contao 4.3.x auf Contao 4.4 gemacht und mit Contao 4.4 wurde ja die Möglichkeit eingeführt, dass bei Bildern nicht sofort die Metadaten angezeigt werden, sondern erst auf Aktivierung einer Checkbox. Contao 4.4 deaktiviert diese Checkbox jedoch im Standard. Das ist bei einem Update natürlich sehr bescheiden, denn alle bereits eingegebenen Metadaten werden nun ignoriert und wir müssen alle Elemente durchgehen und wieder aktivieren.

Es wäre bei einem Update sinnvoller, vorher zu prüfen, ob eines der Metadatenfelder ausgefüllt ist. Wenn ja, dann muss der Punkt "Metadaten überschreiben" aktiviert werden.

**Comment by discordier** [comment]
Fix in the DB by issuing:
```sql
UPDATE tl_content
SET overwriteMeta = 1
WHERE 
(alt <> '') OR 
(imageTitle <> '') OR 
(imageUrl <> '') OR 
(caption <> '')
```

**Comment by asaage** [comment]
https://github.com/contao/core/issues/7774#issuecomment-274161047

**Comment by frontendschlampe** [comment]
> contao/core#7774 (comment)

Das wurde aber nicht gemacht! Das Feld ist einfach deaktiviert.

**Comment by fenepedia** [comment]
Ich kann das Problem beim Update bestätigen. Ist mir auch schon aufgefallen.

**Comment by jankout** [comment]
Leider ist das bei mir auch passiert und damit sind alle Metainformationen verschwunden. Weiß jemand, wie ich das von der alten Datenbank in die neue übertragen kann? Danke

**Comment by fritzmg** [comment]
Die Daten sind nicht verschwunden. Sind sind ja immer noch da, nur das Feld `tl_content.overwriteMeta` ist bei diesen Elementen nicht auf `1` gesetzt. Siehe https://github.com/contao/core-bundle/issues/888#issuecomment-310310630

**Comment by jankout** [comment]
Der Blick in der Datenbank sagt mir allerdings etwas anderes. Bei mir steht in der Tabelle _tl_files_ in der Spalte _meta_ überall NULL

**Comment by fritzmg** [comment]
Hier in diesem Issue geht es aber um etwas anderes. Du kannst ja Community Forum nach Ratschlägen Fragen, warum deine Meta Daten nicht übernommen worden sind.

**Comment by jankout** [comment]
Allerdings passierte das nicht nur bei einer Installation. Daher gehe davon aus, dass es sich auch um einen Fehler handelt. Daher passt es hierher, oder?

**Comment by fritzmg** [comment]
> Daher passt es hierher, oder?

Nein, hier geht es um etwas anderes. Hier geht es um den Umstand, dass bei einem Upgrade auf Contao 4.4 (egal von welcher Contao Version), nicht berücksichtigt wird, dass `tl_content.overwriteMeta` auf `true` gesetzt wird, wenn bei einem Inhaltselement Meta Daten für das `singleSRC` eingegeben wurden. Somit werden diese Daten im Frontend auch nicht ausgegeben.

**Comment by leofeyer** [comment]
Behoben in contao/installation-bundle@30506c1172de5b2745cc629396277db2b556502b.

**Comment by Xendiadyon** [comment]
overrideMeta gibt's auch in tl_news, oder? Wird es gerade nur in tl_content gefixt oder auch in tl_news?

**Comment by fritzmg** [comment]
Wurde momentan nur für `tl_content` gemacht: https://github.com/contao/installation-bundle/blob/4.4.1/src/Database/Version440Update.php#L42

**Comment by leofeyer** [comment]
Geändert in contao/installation-bundle@4c096c0965aabfae4556d12ac9b8fc51b05cf90e.
