### ISSUE TITLE
[4.4.0] Install tool OpCode Cache issue with PHP 5.6

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#890]
I have issues with the install tool running on PHP 5.6 with OpCode Cache enabled.
Everytime I end up with an Error 500 after Updating the database. After some time, most likely after PHP clears the OpCode cache, I can access the install tool again. 
```
(104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
Premature end of script headers: app.php
```
Other steps of the install tool are working fine. But as soon after the database was updated, the above Error occurs.
Disabling opcache on PHP 5.6 solves the issue.

However, some other projects running on PHP 7 with opcache enabled seem not to having this issue.

**Comment by leofeyer** [comment]
Can anyone else confirm this?

**Comment by tsarma** [comment]
Install tool runs without problem even when OpCode is enabled on PHP 5.6 and as well as on PHP 7.1 . So I can not confirm this. I had it tested due to this issue https://github.com/contao/core-bundle/issues/885.
