### ISSUE TITLE
Combine the scripts in the back end

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#891]
It seems that starting with Contao 4, the scripts in the back end are no longer combined.

**Comment by asaage** [comment]
i think this is because of http2 and i like it.

**Comment by leofeyer** [comment]
Correct. No longer required with HTTP/2, therefore gone in the back end and configurable in the front end.

<img width="404" alt="" src="https://user-images.githubusercontent.com/1192057/27442720-4d10d688-5771-11e7-9b65-36f8e1dff830.png">

**Comment by xchs** [comment]
I knew that. I have only asked myself why I have a choice for the front end and not for the back end.

**Comment by leofeyer** [comment]
Because its up to the user whether they want to optimize their website (front end) for HTTP/1 or not.
