### ISSUE TITLE
4.4 interner CSS-Editor

### ISSUE THREAD

**Issue by jewo5** [contao/core-bundle#893]
Wenn man im internen CSS-Editor "auf die Schnelle" eine CSS-Anweisung ein/ausblenden will (Auge-Symbol), muss erst die Systemwartung ausgeführt werden, damit das Ergebnis im Frontend angezeigt wird. Getestet in Edge, Chrome, FF. Mit Version 3.5.27 auf demselben Rechner und senselben Browsern keine Probleme.

**Comment by leofeyer** [comment]
Die Methode `toggleVisibility()` führt den `onsubmit_callback` aus, der eigentlich ein Update der Dateien anstösst.

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/dca/tl_style.php#L860

**Comment by ausi** [comment]
I can confirm this issue. I think the issue is that `tl_style::scheduleUpdate()` skips in [tl_style.php:706](https://github.com/contao/core-bundle/blob/4bce7faa695d3585e4f881fc4fedf745ffd99080/src/Resources/contao/dca/tl_style.php#L706) if the request is an ajax request.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
Fixed in 51398278e90e0285493e95f5c59b976269579179.

**Comment by jewo5** [comment]
funktioniert in 4.4.3 immer noch nicht richtig - wenn ich den Style das erste Mal ausblende, passiert nichts, blende ich ihn danach wieder ein, wird er ausgeblendet und ab diesem Mal ausblenden funktioniert es von da an "falsch herum"
