### ISSUE TITLE
redirect loop in contao backend

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#894]
This happened to one of my (local) installations: After sending login credentials for the BE (/contao route) the browser gets trapped in a redirect loop. 

![redirect_error](https://user-images.githubusercontent.com/5305677/27475708-71110022-5806-11e7-9903-7f48e14a7b13.jpg)
The problem appears across different browsers, clearing the symfony cache and deleting cookies does not change anything. However, accessing the backend via app_dev.php still works.

(core-bundle 4.4.0)

**Comment by leofeyer** [comment]
I cannot reproduce this.

**Comment by m-vo** [comment]
I tried to step through it in the debugger.

The request gets handled, response is looked up from cache and has the header ``t42-force-no-cache`` set, ``Terminal42\HeaderReplay\SymfonyCache\HeaderReplaySubscriber`` then gets called afterwards and issues a subrequest that then leads to a 301 redirect. And then everything starts over again.

Any idea what could be wrong or where I could search? To me this seems like a bug as there is nothing special to the installation.

**Comment by leofeyer** [comment]
@Toflar /cc

**Comment by Toflar** [comment]
Can you figure out who is causing the redirect? Or can you manage to find a way how I could reproduce the issue to debug myself?

**Comment by m-vo** [comment]
It looks like when ``\Symfony\Component\HttpKernel\RouterListener->onKernelRequest()`` gets called (when dispatching ``KernelEvents::REQUEST`` in ``HttpKernel->handleRaw()``)  the url matcher always tries to match the path ``/contao/``. 

Excerpt from the autogenerated ``appProdProjectContainerUrlMatcher`` file: 
````PHP
if (0 === strpos($pathinfo, '/contao')) {
[...]
    // contao_backend
    if ('/contao' === $pathinfo) {
        return array (  '_scope' => 'backend',  '_token_check' => true,  '_controller' => 'Contao\\CoreBundle\\Controller\\BackendController::mainAction',  '_route' => 'contao_backend',);
     }

[...]
    // contao_backend_redirect
    if ('/contao' === $trimmedPathinfo) {
        if (substr($pathinfo, -1) !== '/') {
            return $this->redirect($pathinfo.'/', 'contao_backend_redirect');
        }

        return array (  '_scope' => 'backend',  '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction',  'route' => 'contao_backend',  'permanent' => true,  '_route' => 'contao_backend_redirect',);
    }
}
````
Because of the trailing slash the ``Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::redirectAction`` gets set instead of the ``BackendController`` which leads to a redirect.

**Comment by fritzmg** [comment]
Apache or nginx?

**Comment by m-vo** [comment]
This one's an apache (xampp).

**Comment by Toflar** [comment]
I think I have an idea here. Will check after my holidays :)

**Comment by mecintosch** [comment]
Ein ähnliches Problem habe ich beim Versuch mich als FE User einzuloggen. Es entsteht eine Endlosschleife zur Weiterleitungsseite. Der FE_User Cookie wird gesetzt. Solange dieser Cookie existiert öffnet sich keine FE Seite mehr. Lösche ich den Cookie beginnt das Spiel wieder von vorne.

![bildschirmfoto 2017-06-28 um 15 21 55](https://user-images.githubusercontent.com/16761621/27639363-3f9e0760-5c16-11e7-8855-07a90f635e0c.png)

**Comment by Toflar** [comment]
Can anyone provide a way how to reproduce this? I'm absolutely unable to create a scenario. Neither in the back end nor in the front end.

**Comment by m-vo** [comment]
Found the problem and I cannot believe how I could oversee this. 😳 

Inside the web directory was an empty directory called ``contao``. I actually do not know how that got in there, must have been a mistake. That seems to be the reason why ``domain.local/app_dev.php/contao`` works because in that case real path and route differ. So the behaviour surely depends on what the server treats as a route. 

But I would have expected to either see it working (despite the folder) or seeing an error from the server that the resource was not found. And I'm still not fully understanding why that's not the case.

**Comment by mecintosch** [comment]
I dont have any unused folders in my installation.

My logfile var/logs/ has this entry - 
[2017-07-03 07:45:55] security.INFO: Attempting SimplePreAuthentication. {"key":"frontend","authenticator":"Contao\\CoreBundle\\Security\\ContaoAuthenticator"} []

Contao log says: User "x" has logged in.

**Comment by Toflar** [comment]
The log files etc. do not really help in this case. We need to find a way how we can reliably reproduce the issue, so everybody can work with the same use case and understand the problem.

**Comment by mecintosch** [comment]
Nach vielem testen hab ich jetzt die Ursache gefunden. Sobald ich das Isotope Warenkorb Modul im Seitenlayout eingebunden habe und ich mich versuche als FE-User einzuloggen kommt dieser Cookie Fehler.

**Comment by m-vo** [comment]
To me that sounds like two completely different issues / observations.

**Comment by Toflar** [comment]
@m-vo  can you try to require "terminal42/header-replay-bundle": "dev-hotfix/1.0.2 as 1.0.0" to see if that fixes the issue?

**Comment by m-vo** [comment]
@Toflar nope, the redirect issue still exists as long a folder named ``contao`` is in the webdir

**Comment by Toflar** [comment]
Ah, yeah that is not fixed. This is not a bug to me, there should be no contao folder. No idea where that comes from.

**Comment by leofeyer** [comment]
So can I close the ticket then?

**Comment by m-vo** [comment]
I think so, this issue is probably documentation enough. :-)
