### ISSUE TITLE
Layout looks weird on the maintenance page in 4.4.0

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#896]
When the window (or screen) is higher than the content on the maintenance page, the 'Purge data' section is sticked at the bottom and there is a gap to the 'Rebuild the search index' section:

![hightscreen](https://user-images.githubusercontent.com/1402434/27483419-987169da-5825-11e7-9117-0154364686f8.jpg)

Another problem is the position of the message when purging the data. The message is shown in the 'Rebuild the search index' section:
![purgeddata](https://user-images.githubusercontent.com/1402434/27483527-12f816d6-5826-11e7-8487-b2c83881eefb.jpg)

**Comment by leofeyer** [comment]
Fixed in f4ffd535c8c146747c6b716917e62dae9d117dc6.

**Comment by xchs** [comment]
> Another problem is the position of the message when purging the data. The message is shown in the 'Rebuild the search index' section:

@leofeyer Should this be treated in a new ticket since it is not addressed in the fix?

**Comment by leofeyer** [comment]
No, I'll reopen this ticket.

**Comment by leofeyer** [comment]
Fixed in 357e95c7cd7eafce3103a897f7ad3937ef840ad3.
