### ISSUE TITLE
Tiny layout problem in 4.4.0 with the chrome browser

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#897]
As the layout is in general rather small, I use the browser zoom function quit often. 
When zooming in Googles Chrome browser, there is a little (rounding) problem, that result in a broken layout.

![tinylayoutproblem](https://user-images.githubusercontent.com/1402434/27483726-dbf1bd9e-5826-11e7-882f-f9542477b023.jpg)

This only happens when a checkbox on right column is followed by an input field. It might be a rounding problem when zooming, so the checkbox is not high enough for the floating layout. 

It can simply be fixed by changing the height for checkboxes from 56px to 58px in the basic.css file (around line 518):

```css
.cbx {
    height: 58px;
}
```

**Comment by fenepedia** [comment]
I could confirm the layout break. With Chrome "zoom 110%"
![wrong](https://user-images.githubusercontent.com/566448/27708195-6100a41e-5d18-11e7-9e47-f87d8c703859.png)

**Comment by leofeyer** [comment]
Isn't this a Chrome bug? Because the DIV is exactly 80px height like all the others. Only if I zoom in to 110%, Chrome suddenly calculates 79.99 instead of 80.

**Comment by leofeyer** [comment]
I have tested the other browsers and zooming works like a charm there.

**Comment by agoat** [comment]
It's definitiv a chrome bug! I just suggested a workaround.
