### ISSUE TITLE
display error in filemanager / public parents ignored

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#898]
How to reproduce:
- create a folder and make it public
- create a subfolder
- restrict the tree to show only the subfolder (clicking on the subfolder name)
- the icon now looks like a private folder (lock symbol)

[core-bundle 4.4.0]

**Comment by agoat** [comment]
I can confirm this. The public/private status is not shown correctly when filtering or restricting the folder tree. Below are some test results.

![folders1](https://user-images.githubusercontent.com/1402434/27510049-aa3c9542-5909-11e7-8afa-1e0ced22659d.jpg)
![folders2](https://user-images.githubusercontent.com/1402434/27510050-b2eedd94-5909-11e7-84e4-05567d5c9bab.jpg)
![folders3](https://user-images.githubusercontent.com/1402434/27510051-b40a9bb4-5909-11e7-99ec-b6119f146ee5.jpg)
![folders4](https://user-images.githubusercontent.com/1402434/27510053-b5315a46-5909-11e7-8980-f499e71499ae.jpg)

**Comment by leofeyer** [comment]
Fixed in 3a9a19073f8b35040f6cdc1616c7252d16f5b19c.
