### ISSUE TITLE
prepend_locale: why in parameters.yml?

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#901]
The `parameters.yml` of a Symfony application is typically not something that you deploy to your live server for example, since it usually contains configuration parameters for the installation on the current host - e.g. database connection and smtp settings.

But currently it also contains the `prepend_locale` setting of Contao. If you forget to change that on your deployment target as well, the website will suddenly be without the language in the URL. Other URL related settings like the `url_suffix` is handled in the `config.yml` as well, why not the `prepand_locale` setting too?

**Comment by aschempp** [comment]
Duplicate of https://github.com/contao/standard-edition/issues/65

**Comment by fritzmg** [comment]
Sorry, didn't notice.
