### ISSUE TITLE
Automatisch generierte CSS ID aus dem Alias funktioniert nicht mehr

### ISSUE THREAD

**Issue by mlwebworker** [contao/core-bundle#903]
Bei Contao 3 wurde bei Artikeln eine CSS-ID aus dem Alias generiert. Nach dem Update einer Installation von 3.5.27 auf 4.4 (Neuinstallation mit Update DB) steht an gleicher Stelle die Artikel-ID. Falls das so beabsichtigt ist sollte es dokumentiert werden. Falls nicht kann das vielleicht beim nächsten Release behoben werden.
Siehe dazu auch https://community.contao.org/de/showthread.php?67151-quot-Update-quot-von-3-5-27-auf-4-4&p=443782&viewfull=1#post443782

**Comment by fenepedia** [comment]
Ist so beabsichtigt und ist schon seit der 4.0 geändert.
Um das Problem schnell zu beheben, vergibst du einfach dem Artikel die ID manuell.
Siehe Changelog: https://contao.org/de/changelog/versions/4.0.html

**Comment by mlwebworker** [comment]
Danke

**Comment by dillinja** [comment]
oder eben mod_article.html5 anpassen (OnePager, Artikelnavigation, informative Links!)

**Comment by dillinja** [comment]
Onepager mit Artikelnavigation und sinnvollen Links ohne dem Kunden was von 'ID vergeben' zu erzählen - adé - wer brauch eine Artikel ID ala article-123?

**Comment by Toflar** [comment]
Niemand und niemand der One-Pager macht, will dass sich die ID's einfach so ändern wenn jemand auf die Idee kommt das Alias des Artikels zu ändern. Deshalb musst du sie manuell eingeben, was ja immer noch möglich und richtig ist.

**Comment by dillinja** [comment]
Es sollte sich genau so verhalten wie bei dem Erstellen einer neuen Seite. Wenn da jemand auf die Idee kommt einen Seiten-Alias zu ändern, hatte es die gleichen Auswirkungen wie die Änderung des Alias eines Artikels (im Hinblick auf Links). Täusche ich mich, oder sind diese beiden Dinge in ihrer jeweiligen Struktur nicht genau das Gleiche? Ein Alias wir ja auch beim Ändern des Titels nicht automatisch aktualisiert, weder in der Seite noch im Artikel.

Wenn jemand auf die Idee kommt, irgend einen Alias zu ändern, dann ist genau das der Punkt, der in jedem Fall **bedacht** getan werden soll - Seite, sowie Onepager Artikel.
