### ISSUE TITLE
No back button in file picker popup

### ISSUE THREAD

**Issue by aschempp** [contao/core-bundle#905]
When a file is uploaded in the file picker menu, there is no back button to go back to the tree view.

![bildschirmfoto 2017-06-28 um 14 37 00](https://user-images.githubusercontent.com/1073273/27637227-4e1b3242-5c0f-11e7-962f-fcad85a25b9e.png)

**Comment by leofeyer** [comment]
Hm …

<img width="978" alt="" src="https://user-images.githubusercontent.com/1192057/27821746-a96a1db4-60a3-11e7-93af-325b1c4396f3.png">

**Comment by aschempp** [comment]
Looks like you selected another dialog? The title in the popup is different?

**Comment by netzarbeiter** [comment]
Content > Articles > Edit article > Edit content > Add an image > Source file: Change selection > File upload 

![back](https://user-images.githubusercontent.com/1942550/27830019-b1d9232a-60c4-11e7-9404-e3c29da4e40e.png)

**Comment by leofeyer** [comment]
Same result:

<img width="974" alt="" src="https://user-images.githubusercontent.com/1192057/27830284-ff75c006-60c5-11e7-84c2-ce5dcccd44d1.png">

**Comment by netzarbeiter** [comment]
```
body.popup .header_back {
    display: none;
}
```

**Comment by leofeyer** [comment]
Diese Anweisung gibt es bei mir gar nicht:

https://github.com/contao/core-bundle/blob/master/src/Resources/contao/themes/flexible/src/main.css

**Comment by netzarbeiter** [comment]
Du kannst das Ticket schliessen das CSS kommt von Isotope.
