### ISSUE TITLE
Eval rgxp=absurl and rgxp=relurl

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#910]
It's not a real bug. But should an url input not allways start with `http` or `mailto` (or it's a `{{insert_tags}}`?
Currently you can enter everything, except some special characters, in the url field of the hyperlink content element.

Would it not be better to check for a complete url if an (absolute) url is requested?

**Comment by aschempp** [comment]
No, the validation is supposed to allow that. An URL can be relative, for example.

**Comment by agoat** [comment]
But in the case of the hyperlink content element, all relative (internal) urls could be selected with the (new) dca picker and will be insert as a insert tag. So I don't see why I should enter some relative url here.

Maybe it could be helpful to extend the validation to check for absolute and relative (which is more or less anything) urls.

**Comment by m-vo** [comment]
Imo all relative URLs must be allowed. Think of custom routes / bundles outside the contao ecosystem or modules that are not supported by the picker.

**Comment by agoat** [comment]
> Think of custom routes / bundles outside the contao ecosystem

You're right. But if I extablish a system beside contao under the same domain name, it would be a better way to create a custom content element (or module). With that I give the user the ability to select the outsided system correctly. That's the way I would do it.

But I understand that relative urls should also be allowed. That's why I proposed two rgxp url checks (absolute and relative). At least it would be helpfull for some of my extensions (and certainly for other developers, too).

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/issues/1384.
