### ISSUE TITLE
News article not selectable in new dca picker

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#911]
When trying to insert a link to a news article wih the wizard in the hyperlink content element, only the news archives are shown, but no articles.

![no_newsarticle](https://user-images.githubusercontent.com/1402434/27702948-1ad66b3e-5d06-11e7-851e-c0481d37f433.jpg)

And the hotfix from PR/#906 does not help completely.

![no_newsarticle_patch](https://user-images.githubusercontent.com/1402434/27703013-5e4fd5d0-5d06-11e7-9019-f721123ab9f4.jpg)

**Comment by fenepedia** [comment]
You need to klick to "edit" and then select the news article.

**Comment by agoat** [comment]
> You need to click to "edit" on the "news archive"

OK, that work. 
But IMO that shouldn't the way how to select news articles. I want to select and not edit articles in an archive. I never expected first to click on edit and then be able to select (Although I know why it just work that way).

**Comment by fenepedia** [comment]
Yes, I totally agree you. I hope this would be changed in the future. That is a bad user experience.

**Comment by leofeyer** [comment]
Of course you first need to select an archive! How is the picker supposed to know otherwise?

**Comment by fritzmg** [comment]
I think @fenepedia means that it is confusing since you are seeing the interface for editing or creating news archives or news articles and thus it is not apparent that you need to "edit" an archive in order to _selec_t a news article from that archive.

**Comment by leofeyer** [comment]
So what would be less confusing in your opinion?

**Comment by fritzmg** [comment]
Hm, I see a few possibilities. Probably the "easiest" would be to __not__ show the _edit_, _editheader_, _copy_, _delete_ and _show_ operations while being in the DCA select mode - and instead show an ➡️ or something.

Another possibility (which would require a lot more work of course) is having a tree view instead, where you can simply open any news archive as if it was a site structure and then select the desired news article. Though I think this is not feasible, since you won't be able to use a pagination then and a news archive could have thousands of entries.

**Comment by agoat** [comment]
One solution could be that the archive have also a select button which open the article list.

The second (and IMO better) solution would be a tree view for all parts of the dca. So the archive can be opened like folders in the file selection (or pages in the page tree).

**Comment by fritzmg** [comment]
Hehe, same ideas ;)

**Comment by agoat** [comment]
In generall, a tree view driver over multiple tables (pages>articles>element or archive>articles) would be great anyway!

**Comment by leofeyer** [comment]
I don't like any of your ideas (no hard feelings).

We have designed the DCA picker so you can browse the back end and do anything you want (including edit, move, delete operations) and additionally select records. The old page picker had the "edit the site structure" and "go back to the page picker" links and it was cumbersome having to switch between the two views.

**Comment by aschempp** [comment]
That will not be possible, because a tree view does not have pagination, and you would potentially get a list of 10000 news entries in one archive. We had that issue in Isotope eCommerce 1.x and it broke the backend :D

**Comment by fritzmg** [comment]
Maybe a hint (like the one when pasting/inserting elements) directing you to "edit" the news archive in order to select its news entries would suffice :)

**Comment by agoat** [comment]
> That will not be possible, because a tree view does not have pagination

Why not adding a pagination to the tree view? I know it's not easy. And if we do, it will surely bring a revision of the whole dca drivers. Maybe something for a future version.

**Comment by agoat** [comment]
> We have designed the DCA picker so you can browse the back end and do anything you want (including edit, move, delete operations) and additionally select records.

But how do I know, that I first need to edit an archive to then be able to select articles?
Like @fritzmg suggested, there should be a hint. What about an arrow at the end (at the place of the selection points for the articels) to indicate that the articles can be selected inside?

**Comment by leofeyer** [comment]
> But how do I know, that I first need to edit an archive to then be able to select articles?

It's pretty intuitive actually. If you want to create a news item, you need to open the archive. If you want to edit a news item, you have to open the archive. If you want to publish a news item, you have to open the archive. And if you want to select a news item, you have to open the archive.

I really don't see why we need a hint in this case.

**Comment by DyaGa** [comment]
Another solution. Allow to search news items by title in the same way as in File manager. But, there is a problem of showing search results.

**Comment by rabauss** [comment]
perhabs it would be a little bit more intuitiv if the yellow marker would be on the edit icon in the archive liste - or any other color or highlight, wich will be prefered in the other issue...

**Comment by m-vo** [comment]
What about a hint above (like the one when moving a page for example)? ;-)

 IMO the problem is that the edit icon sometimes means 'edit this' and sometimes 'show child elements / show what's inside'.

**Comment by fenepedia** [comment]
What about making the Archive-Title clickable? Maybe we should wait how often someone ask this question after all?

**Comment by agoat** [comment]
> It's pretty intuitive actually. If you want to create a news item, you need to open the archive. If you want to edit a news item, you have to open the archive. If you want to publish a news item, you have to open the archive. And if you want to select a news item, you have to open the archive.

The problem is the kind of action.
When I create a news item I'm EDITING. When I edit a news item I'm EDITING. When I want to publish a news item I'm EDITING. But when I have to select a news item I'm SELECTING.
So when I want to edit a new item, it's clear to click on the news archives edit button. But when I only have to select one, it's not intuitive to first click on an edit button.

So the 'old' picker was not that bad. To have a selection mode and edit mode was not the badest idea. 
But I also like the 'new' one in general. But we need some kind of indicator, that the selectable items are on the next level.

When I first opened the picker for news items I expected to have a tree view. Maybe we can establish an extra tree view (with pagination) for the picker.

**Comment by leofeyer** [comment]
> Maybe we can establish an extra tree view (with pagination) for the picker.

Definitely -1!

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, all the suggestions have relevant drawbacks. We concluded that the current implementation – albeit not perfect – is the best way to go.
