### ISSUE TITLE
[4.4] contao-console contao:symlink issue

### ISSUE THREAD

**Issue by Tastaturberuf** [contao/core-bundle#913]
if you put images etc direct in the /files folder they become 404.

```
/files/tao/[...]
/files/demo/[...]
/files/isNotLinkable.jpg
```

the symlink console task link all included folders like this:
```
[xxx@xxx contao-4.4]$ ll web/files/
total 0
lrwxrwxrwx 1 xxx xxx 16 Jul  2 18:26 demo -> ../../files/demo
lrwxrwxrwx 1 xxx xxx 15 Jul  2 18:26 tao -> ../../files/tao
```
The root files are not linked!

but we need a symlink from 

`/web/files -> ../files`

**Comment by fritzmg** [comment]
This is normal. Only folders within the files folder can be made public in Contao 4.

**Comment by Tastaturberuf** [comment]
Jetzt mal in Deutsch damit es nicht zu Missverständnissen kommt.

> This is normal. Only folders within the files folder can be made public in Contao 4.
Ist ist nicht normal, sondern unlogisch. 
Dann muss es im Backend verhindert werden das dort Dateien abgelegt werden können.

Was spricht dageben einfach web/files -> files zu linken?

**Comment by fritzmg** [comment]
Das würde bedeuten, dass dann _alle_ Dateien und Ordner automatisch public sind.

**Comment by Tastaturberuf** [comment]
Ok stimmt. Ich nutze die "Ordner sichern"-Funktion nie, hab daran nicht gedacht.

Trotzdem muss das irgendwie geändert werden. Man kann dort Dateien ablegen und auch in Elementen und Modulem auswählen, nur im Frontend tauchen die nicht mehr auf.

Am besten sollten alle Dateien der /files-Ebene auch verlinkt werden.

**Comment by m-vo** [comment]
Das Gegenteil ist der Standardfall: Nur Ordner, die du öffentlich machst, werden gesymlinked. Ich möchte den Filepicker z.B. auch für Dateien verwenden können, die nicht öffentlich sein sollen.

(Random thought: But maybe the way the asset management works for images can be improved: Images that are output without beeing resized point to the path they originally live in, all other versions get stored inside the assets dir. In that case we maybe could create a symlink to the file inside the asset folder instead? )

**Comment by leofeyer** [comment]
https://github.com/contao/core-bundle/blob/master/UPGRADE.md#protected-folders
