### ISSUE TITLE
consider not loading bundle stylesheets when not logged in

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#914]
The backend login (``/contao``) gives hints which bundles are installed without beeing logged in because their stylesheets get loaded. 

![contao_backend_css](https://user-images.githubusercontent.com/5305677/27772167-d55215be-5f5c-11e7-896a-e0c49ae77929.png)

This might be a security flaw allthough maybe an insignificant one.

**Comment by leofeyer** [comment]
Certainly not a security issue. And not much we can do about it, either.

**Comment by agoat** [comment]
If you want to be secure, you should restrict the access to the backend anyway. 

For example, I only allow access to the backend from certain subdomains. So no one can check the backend by simply add '/contao' to the url (medium level security)
Or you add an extra authentication on web server basis (high level security).

**Comment by fritzmg** [comment]
@m-vo if you want to know whether a specific extension is installed on a website running Contao, you can just open those asset URLs anyway.

**Comment by m-vo** [comment]
True!
