### ISSUE TITLE
jQuery version for next contao release

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#916]
We should rise the jQuery version in the next minor (4.5) or, at least, major (5.0) contao version. 
To be stucked with jQuery 1.x, which is not actively maintenanced anymore, is not forward-looking.

I know about the backwards compatibility problem (#718) , but contao (backend) itself works fine with the newest jQuery version. So it's only about the users scripts that being problematic. But hey, who expect an update from 4.3 to 4.4 to be easy? If my webpage rely on a big javascript base, I have to anticipate more work when updating the cms.

**Comment by fritzmg** [comment]
> But hey, who expect an update from 4.3 to 4.4 to be easy?

I do. There is nothing special about an update from 4.3 to 4.4. I certainly would not expect my JavaScript code to break for example.

**Comment by agoat** [comment]
>  I certainly would not expect my JavaScript code to break for example.

And what about an update from 4.5 to 5.0?

IMO most of the 'normal' tiny or medium scripts will work with jquery 3. At least with some tiny adjustments. For pages with exzessive javascript use it could be a bigger problem.

I never expect an update to be easy. Not with the composer anymore, when updating a lot of dependency packages at once. So it needs some time to update anyway, and with rising complexity the time (and cost) is rising, too.

**Comment by fritzmg** [comment]
> And what about an update from 4.5 to 5.0?

Problems can be expected there and Contao `5.0` can also safely increase the jQuery version.

> I never expect an update to be easy.

You only need to expect backwards compatibility breaks when changing major versions. Backwards compatibility breaks are not expected when changing minor or bugfix versions.

**Comment by fritzmg** [comment]
> Not with the composer anymore, when updating a lot of dependency packages at once.

Especially with composer and semantic versioning you don't have to worry that much anymore ;).

**Comment by aschempp** [comment]
I think Contao 5 will not bundle jQuery anyway, but nobody knows exactly what Contao 5 will bring yet, thats a future topic.

**Comment by agoat** [comment]
> Especially with composer and semantic versioning you don't have to worry that much anymore ;).

Just to remember, symfony updates broke contao twice. And every minor contao update breaks at least on or two of my extensions (not badly, most can be fixed easily).

**Comment by leofeyer** [comment]
If we should use jQuery in Contao 5 (see @aschempp's comment), we'd certainly use the most recent version.

**Comment by agoat** [comment]
What about a jQuery version selector in the themes layout? Not the best solution and maybe too complicated, but it's an option to avoid a BC-Break and be up to date at the same time.

**Comment by leofeyer** [comment]
See https://github.com/contao-components/jquery/issues/2
