### ISSUE TITLE
Feature: Nachrichtenliste um Sortierfunktion ergänzen

### ISSUE THREAD

**Issue by fenepedia** [contao/core-bundle#917]
Die Ausgabe der Nachrichtenliste sollte um eine Sortierfunktion ergänzt werden, so dass über das Modul gesteuert werden kann, in welcher Reihenfolge die News ausgegeben werden.

- absteigend (Datum)
- aufsteigen (Datum)
- A - Z (Titel)
- Z - A (Titel)
- Zufällig

Früher gab es eine Erweiterung news_sorted. Aus meiner Sicht eine hilfreiche Funktion die in den Core integriert werden sollte.

**Comment by fritzmg** [comment]
👍 gehört aber hier hin: https://github.com/contao/news-bundle/issues ;)

**Comment by fenepedia** [comment]
Danke, dann werde ich das gleich mal anpassen

**Comment by fenepedia** [comment]
Neues Ticket erstellt: https://github.com/contao/news-bundle/issues/12
