### ISSUE TITLE
4.4 Insertag {{insert_module::}}

### ISSUE THREAD

**Issue by Mediaquery** [contao/core-bundle#919]
The insertag for module do not include the id or class of the module anymore.

**Comment by leofeyer** [comment]
How do I reproduce this?

**Comment by Mediaquery** [comment]
Ein beliebes Module mit Klasse ID anlegen und mittels {{insert_module::*}} in ein HTML Module einfügen schwupps sind Sie weg.

**Comment by fenepedia** [comment]
Ich konnte den Fehler so nicht reproduzieren.
Habe ein neues Modul mit Typ "Formular" angelegt. Das dann in einem HTML-Element per insertag eingefügt.

![modul](https://user-images.githubusercontent.com/566448/27807511-a085c0d4-6041-11e7-9b99-efd4bd52625a.png)

![html-code](https://user-images.githubusercontent.com/566448/27807531-b9f10808-6041-11e7-892f-77a18770a19c.png)

**Comment by b-fender** [comment]
I can confirm, that css-classes, added to a module, are added when modules are included by inserttag.

![unbenannt-2](https://user-images.githubusercontent.com/1473692/28545215-6ab72f52-70c6-11e7-965f-5df968a17688.jpg)
