### ISSUE TITLE
4.4 - Exterene Stylesheets aus files/css

### ISSUE THREAD

**Issue by Mediaquery** [contao/core-bundle#922]
Mir ist gerade aufgefallen das sich bei mir CSS Dateien nicht aus dem Pfad /files/css/ im Theme einbetten lassen, falls dieser per FTP übertragen wurde. Wenn man den Ordner in z.B. files/styles umbennt funktioniert es ohne Probleme. Wenn jedoch der Ordner /css über die Dateiverwaltung  funktioniert es. Der per FTP erstellte Ordner wurde danach über die Dateiverwaltung auf öffentlich gesetzt. Synchronisieren und auf Öffentlich stellen alleine war nicht ausreichend.

**Comment by leofeyer** [comment]
Wie genau lässt sich das reproduzieren?

**Comment by xchs** [comment]
Ich kann das nicht reproduzieren (getestet in Contao 4.4.3). Der per FTP ins Contao Files-Verzeichnis übertragene Ordner inklusive Stylesheet (`css/styles.css`) lässt sich – wie erwartet – problemlos im Seitenlayout einbinden.
