### ISSUE TITLE
Interne Weiterleitung

### ISSUE THREAD

**Issue by Schockwelle** [contao/core-bundle#927]
Interne Weiterleitung funktioniert nicht.

Seitenstruktur > Seite bearbeiten > Seitentyp = Interne Weiterleitung

Weiterleitungstyp: Bei der Auswahl öffnet sich das Modal "Weiterleitungsseite", allerdings kann man dann keine Auswahl vornehmen.

Contao 4.4.0

**Comment by leofeyer** [comment]
Siehe #906, #883, #904, #899, contao/managed-edition#21 and probably others. It wouldn't hurt to use the search function before creating new issues. 😄
