### ISSUE TITLE
Contao springt immer zurück zum Seitenanfang

### ISSUE THREAD

**Issue by dackelchen** [contao/core-bundle#928]
Moin, bei der 3.5 war es so, dass, ich wenn ich beispielsweise Inhaltselemente kopiert und eingefügt habe, an der Position auf der Seite weiterarbeiten konnte, an der ich eingefügt hatte. Bei C 4.4 ist es jetzt so, dass ich immer oben auf der Seite lande und erst einmal wieder nach unten scrollen und suchen muss, wo ich gerade war, wenn ich nicht gerade das unterste Inhaltselement bearbeite.

 Das gilt auch für das Löschen von Inhaltselementen.

Ein Traum wäre natürlich, wenn man Contao generell dazu bringen könnte, sich immer die Position zu merken und nie an den Seitenanfang zurückzuspringen.

**Comment by leofeyer** [comment]
Ich kann das Problem nicht reproduzieren. Ich vermute aber, dass das `BE_PAGE_OFFSET`-Cookie bei Dir das `HttpOnly`-Flag gesetzt hat und es deswegen vom JavaScript nicht verändert werden kann. In diesem Fall kannst Du das Cookie einfach löschen und danach sollte es wieder funktionieren.

**Comment by fritzmg** [comment]
Hm, also ich kann das Problem reproduzieren. Ich habe vorher verifiziert, dass das `BE_PAGE_OFFSET` nicht existiert. Beim Test ist der Wert des Cookies immer `0` (wobei ich jetzt nicht feststellen kann, ob der Wert jemals größer `0` ist und vielleicht nur nachdem die Seite neu geladen hat und man wieder ganz oben ist, wieder auf `0` gesetzt wird).

**Comment by leofeyer** [comment]
Analysiere mal das Cookie z.B. mittels der Web Developer-Erweiterung für Chrome.

<img width="842" alt="" src="https://user-images.githubusercontent.com/1192057/27900407-87ce7fba-622e-11e7-8680-5d7bff55a605.png">

Wenn da `HttpOnly` auf `Yes` steht, kann es nicht funktionieren. Allerdings frage ich mich auch, warum das bei mir jetzt wieder auf `Yes` steht. 😄

**Comment by fritzmg** [comment]
Daran liegt es nicht:

![bepageoffset](https://user-images.githubusercontent.com/4970961/27900717-bf59d58c-622f-11e7-8035-cece0e5882ef.png)

Ich hab mir ein `console.log(window.getScroll().y);` in `Backend.getScrollOffset` von `core.js` (bzw. `core.min.js`) eingefügt - es wird immer `0` ausgegeben (FireFox 54.0.1).

**Comment by fritzmg** [comment]
Es wirkt so als würde der Browser `Backend.getScrollOffset()` erst ausführen _nachdem_ die Seite nach der jeweiligen Aktion neu geladen hat. Ruft man `Backend.getScrollOffset()` ansonsten manuell auf (also nicht nach einer Aktion, die die Seite neu laden würde), wird die richtige Scroll Position ausgegeben.

**Comment by fritzmg** [comment]
Dass der Browser `onclick` JavaScript code erst ausführt, nachdem der `href` geladen wurde, scheint nicht unüblich zu sein: https://stackoverflow.com/questions/10712528/a-href-link-executes-and-redirects-page-before-javascript-onclick-function-is-ab

Sollte dann aber in Contao 3 genauso nicht funktionieren.

**Comment by leofeyer** [comment]
Das Problem ist, dass der `MergeHttpHeadersListener` bei der Übernahme der Cookies das `HttpOnly`-Flag auf `true` setzt (gemäß der Symfony-Vorgaben).

<img width="553" alt="" src="https://user-images.githubusercontent.com/1192057/27901285-c759d744-6231-11e7-9e05-33a769c144c6.png">

Danach darf das JavaScript das Cookie nicht mehr verändern.

@Toflar Sollten wir Cookies gesondert behandeln im `MergeHttpHeadersListener`?

**Comment by fritzmg** [comment]
Sorry, dass der Wert immer `0` ist stimmt nicht - hatte falsch getestet. Aber du hattest Recht @leofeyer, aus irgendeinem Grund hat das Cookie irgendwann `HttpOnly` aktiv und kann dann durch das JavaScript nicht mehr aktualisiert werden.

**Comment by leofeyer** [comment]
Das Problem entsteht hier: https://github.com/symfony/http-foundation/blob/master/ResponseHeaderBag.php#L129

**Comment by leofeyer** [comment]
Bzw. dann hier:

https://github.com/symfony/http-foundation/blob/master/Cookie.php#L49

**Comment by Toflar** [comment]
`Cookie::fromString()` müsste doch `httpOnly` nur auf `true` setzen, wenn es auch da ist? Oder bin ich da jetzt falsch?

**Comment by leofeyer** [comment]
Ja, müsste es. Macht Symfony aber nicht. 😢

**Comment by fritzmg** [comment]
> Cookie::fromString() müsste doch httpOnly nur auf true setzen, wenn es auch da ist? Oder bin ich da jetzt falsch?

Es setzt httpOnly by default auf true. Wenn dann im Cookie string httpOnly nicht mehr vorkommt, bleibt es auch true. Insofern köntne man ja
```JavaScript
/**
 * Get the current scroll offset and store it in a cookie
 */
getScrollOffset: function() {
	document.cookie = "BE_PAGE_OFFSET=" + window.getScroll().y + "; httpOnly=0; path=" + (Contao.path || '/');
},
```
machen, oder nicht?

**Comment by leofeyer** [comment]
Das JavaScript ist nicht das Problem.

**Comment by Toflar** [comment]
Warum es so ist, sehe ich schon. Ich frag mich nur ob es ein Symfony Bug ist oder ob wir den Fall abfangen müssen. Ich bin dann mal HTTP Spezifikationen lesen...

**Comment by fritzmg** [comment]
> Das JavaScript ist nicht das Problem.

Hier würde `httpOnly` dann theoretisch wieder `false` werden: https://github.com/symfony/http-foundation/blob/master/Cookie.php#L75

**Comment by leofeyer** [comment]
Ich weiß nicht, ob man `httponly=false` setzen darf. In der Dokumentation wird der Fall nicht erwähnt.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by Toflar** [comment]
Ich bin ziemlich überzeugt davon, dass es ein SF Bug ist. Ich mach einen PR fertig.

**Comment by leofeyer** [comment]
Hab ich schon gemacht: https://github.com/symfony/symfony/issues/23424

**Comment by Toflar** [comment]
So, PR ist jetzt auch da. Ich denk das Ticket können wir schliessen sobald wir da Rückmeldung haben.

**Comment by leofeyer** [comment]
Wir brauchen trotzdem eine Lösung für uns, oder?

**Comment by Toflar** [comment]
Warum? Das Flag wäre ja dann richtig und das Cookie könnte vom JS gelesen werden?

**Comment by leofeyer** [comment]
Also willst Du auf Symfony 3.3.5 warten und solange ist die Funktion einfach kaputt?

**Comment by Toflar** [comment]
Natürlich?

**Comment by leofeyer** [comment]
Find ich nicht gut. Wir wissen ja auch gar nicht, ob und wann Sf das einbaut.

**Comment by Toflar** [comment]
Es ist bereits assigned, kommt garantiert mit dem nächsten 3er-Release.

**Comment by leofeyer** [comment]
Behoben in 1789f67e3251d8c210d714921453f7f6f10f4b92.
