### ISSUE TITLE
akzeptiert beim installieren kein Punkt . in dem Datenbanknamen

### ISSUE THREAD

**Issue by srhinow** [contao/core-bundle#929]
Wenn ich einen Datenbanknamen mit einem Punkt im Namen habe, wird bei der Installation mit "/contao/install" mir angezeigt das der Kontakt mit der Datenbank fehlgeschlagen ist. Wenn ich eine Datenbank ohne Punkt nehme funktioniert es wie es soll. In der Vergangenheit habe ich alle lokalen Projekte immer so benannt wie die Domain also die Datenbank hieß dann "projekt1.local". Es ging also schonmal in früheren Contao 2 und 3 Versionen.

**Comment by fritzmg** [comment]
Duplicate of https://github.com/contao/core-bundle/issues/593
However, I am not sure if `.` should actually work now or not.

**Comment by srhinow** [comment]
Das ist in der Contao 4.4.0 aktuell heute gewesen und nicht in einer älteren Version. Wieso wurde es dann als doppelt und geschlossen markiert?

**Comment by fritzmg** [comment]
Weil es so ein Ticket bereits gibt, wie schon erwähnt. Du musst wenn dann dort neue Kommentare hinzufügen. Aus dem Inhalt ursprünglichen Tickets bin ich mir jetzt aber auch nicht sicher, ob Datenbanknamen mit `.` nun prinizpiell noch unterstützt werden in Contao 4 oder nicht.

**Comment by srhinow** [comment]
Es kommt auch nicht die Fehlermeldung "Please enter only the following characters: A-Za-z0-9$_"
sondern "Datenbankverbindung fehlgeschlagen!". Also ist es nicht das was Leo da in dem https://github.com/contao/installation-bundle/commit/28e8efc1e3e3acd833994411039cfaffe7b7a7de gelöscht hat.

**Comment by leofeyer** [comment]
Das Ticket ist kein Duplikat von #593. Allerdings kann ich das Problem auch nicht reproduzieren.

**Comment by xchs** [comment]
Ich kann das Problem reproduzieren.

Getestet mit:
- Contao 4.4.3 ME
- MySQL: 5.1.73-log mit PHP-Erweiterung MySQLi
- DB name: `contao.test` 

![db](https://user-images.githubusercontent.com/1218766/29496863-f95ad4a0-85db-11e7-8926-7c39dac874d4.png)

**Comment by aschempp** [comment]
I'm not sure if DBAL supports database names with a dot, but I couldn't find anything on a quick Google search.

**Comment by xchs** [comment]
> I'm not sure if DBAL supports database names with a dot

Offenbar nicht. Wir hatten das ja auch schon in https://github.com/contao/core-bundle/issues/593 diskutiert. Und nachdem @Toflar  uns für die Verwendung von `.` in Datenbanknamen gerügt hat 😄 , verwende ich stattdessen einfach Unterstriche oder Bindestriche.

**Comment by srhinow** [comment]
ist ja auch soweit in Ordnung wenn man nur die Fehlermeldung anpassen könnte. So weiß man doch gar nicht was da falsch ist und probiert ewig den Benutzer und das Passwort neu einzugeben.

**Comment by arno1979** [comment]
Bin gerade genau in die gleiche Falle gelaufen, also auch einen `.` im Datenbanknamen.
Eine Anpassung der Fehlermeldung wäre auf jeden Fall sehr hilfreich!

**Comment by leofeyer** [comment]
Geändert in contao/installation-bundle@220a5f895eef18877b5f53521be5ca1a3363b1bb.
