### ISSUE TITLE
Filter options in the (new) dcaPicker also apply to normal module view

### ISSUE THREAD

**Issue by agoat** [contao/core-bundle#932]
When selecting a page (or any other picker element like news, articles) and using the search (or any filter) to find what I want to select (e.g. in the hyperlink content element), the filters will also be used for the normal module views. 

Steps to reproduce:
1. Check if any filter is set in the 'Site structure' view.
2. Edit an article and add a hyperlink content element.
3. Use the dcaPicker wizard and search for something or set a filter on the page tab.
4. Save and go back to the 'Site structure' view >> You will have the same search or filter option set in the dcaPicker!!

IMO the dcaPicker can take the filter settings from normal view, but should delete it's own settings when closing or it's using own filter settings beside the normal view.

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, we consider this a feature and not a bug.
