### ISSUE TITLE
add more information in title if editing an article or a content element (or others)

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core-bundle#933]
I've been talking about the headline in top of page (below the orange bar):

edit an article:
***Articles*** *› Edit article ID XX*

better:
***Page*** *› "My page title" (ID XX) ›* ***Articles*** *› Edit article "My article title" (ID XX)*

edit a content element:
***Articles*** *› "My article title" ›* ***Content elements*** *› Edit content element ID XX*

better:
***Page*** *› "My page title" (ID XX) ›* ***Articles*** *› "My article title" (ID XX) ›* ***Content elements*** *› Edit content element ID XX*

Maybe also with direct links to the article or pages. Editing modules there should be the title of the theme, for news, events and faq the title of archive, form elements the title of the form.

**Comment by leofeyer** [comment]
The breadcrumb items are made from the table hierarchy and since `tl_page` is not a parent table of `tl_article`, I doubt that this is possible. At least not without a special hard coded if condition, which I would not recommend to add.

**Comment by agoat** [comment]
When I worked on the PR #623, I also thought about a linkable breadcrumb. But that wasn't easy to do without lot of (potentially time consuming) extra work to generate the correct links. 

But that would be a nice feature for usability. 

My suggestion for a whole breadcrumb from page to article to content element would be the following:

- In the Article module (tree view):
_Articles:_

- Editing an article:
_Articles: rootpage title > regularpage title > Editing article title (ID XX)_

- In the content element table (list view):
_Articles: rootpage title > regularpage title > article title_

- Editing a content element:
_Articles: rootpage title > regularpage title > article title > Editing content element ID XX_

**Comment by leofeyer** [comment]
As discussed in Mumble on July 13th, we do not want to hardcode the page titles in front of the article module. But we can try to change

… ›* ***Articles*** *› Edit article ID XX

to

… ›* ***Articles*** *› "My article title" (ID XX)

**Comment by leofeyer** [comment]
I wonder if this really makes sense, as the article title is shown right under the headline.

<img width="641" alt="" src="https://user-images.githubusercontent.com/1192057/33073808-62a925b6-cec4-11e7-81ce-4c910f991933.png">

**Comment by frontendschlampe** [comment]
You're right. It was just more consistant in my example in combination with page title, I think.

**Comment by leofeyer** [comment]
I think so, too.
