### ISSUE TITLE
4.4 - Backend Theme - Create Template, create button is out of view on small window sizes

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#937]
If you create a new template on `/contao?do=tpl_editor&key=new_tpl` and your browser window size isn't very hight, you don't see the "Create Template" button. If you scroll down, you can see him.

![bildschirmfoto](https://user-images.githubusercontent.com/26099903/27921988-d42ce2fc-6279-11e7-9ac4-6827264a0957.png)

**Comment by leofeyer** [comment]
Of course, because the buttons sit at the bottom of the page and not at the bottom of the browser window. You might want to try the [StickyBEFooter](https://github.com/may17/contao-m17StickyBEFooter) extension if you want the buttons to remain at the bottom of the browser window.

**Comment by websolutions-hamburg** [comment]
Hmm ok, I know what you mean. But I think the solution in version 4.3, where the buttons sit at the end of the content, was a better **usability** solution. But I will not discuss this here in the ticket with you. Thanks for the extension link. Maybe it can help me ;-)

**Comment by leofeyer** [comment]
I'm not saying that you don't have a point here. I also stumbled across this when creating new templates and when importing CSV data, because in these cases the form only consists of two input fields, which don't take up much height. But it works like a charm in most other cases …

**Comment by ausi** [comment]
Could possibly be fixed by using a `min-height` instead of `flex-grow`:

```css
.tl_edit_form .tl_formbody_edit {
    flex-grow: 0;
    min-height: calc(100vh - 180px)
}
```

**Comment by websolutions-hamburg** [comment]
With `min-height: calc(100vh - 180px)` it looks sometimes weird. But only the `flex-grow: 0;`looks good for me.

Example with `min-height: calc(100vh - 180px)`:
![bildschirmfoto](https://user-images.githubusercontent.com/26099903/28018085-2da8019a-657c-11e7-9038-6d8a584d6fc2.png)
