### ISSUE TITLE
Dateiverwaltung Fehler bei Löschen über Funktion "Mehrere bearbeiten"

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#941]
Wenn man in der Dateiverwaltung über die Funktion "Mehrere bearbeiten" einen Ordner und eine darin enthaltene Datei auswählt und diese anschließend löscht, erscheint folgende Fehlermeldung:

````File or folder "files/test/test.txt" is not mounted or cannot be found.````

**Comment by leofeyer** [comment]
Das liegt daran, dass Contao im ersten Schritt schon den Ordner inklusive aller Dateien löscht und somit die Datei im zweiten Schritt nicht mehr existiert.

@contao/developers /cc

**Comment by Toflar** [comment]
Warum muss dieser Fall überhaupt abgefangen und eine Fehlermeldung angezeigt werden? Der User wollte die Datei löschen, wenn sie bereits weg ist, ist doch auch gut? Hauptsache sie ist weg? :-D

**Comment by leofeyer** [comment]
Wie am 13. Juli auf Mumble besprochen, sollten wir die Fehler einfach ignorieren, da das gewünschte Resultat (das Löschen der Dateien) ja bereits vorhanden ist.

**Comment by leofeyer** [comment]
Behoben in d508ba60c5b069d8d9fd452e5a27b6710a424a72.
