### ISSUE TITLE
Add confirmation message to modules such as ModulePersonalData

### ISSUE THREAD

**Issue by ben-eSM** [contao/core-bundle#945]
It would be nice if modules like ```ModulePersonalData``` could show a confirmation message if the form is submitted an there's no ```jumpTo``` page specified in the module settings.
Sometimes I don't want to redirect to a confirmation page, yet the user should at least get short info that the form has been submitted successfully.

**Comment by aschempp** [comment]
Take a look at our [ajaxform](https://github.com/terminal42/contao-ajaxform) extension 😎

**Comment by ben-eSM** [comment]
So far I did in those use cases! :wink:
But I thought the message part should be implemented in the core (not the ajax part of course).

**Comment by leofeyer** [comment]
This should be the case already. 🤔 

https://github.com/contao/core-bundle/blob/133cebc0a9716f935637dcb64cd46a5b37920d02/src/Resources/contao/modules/ModulePersonalData.php#L369
