### ISSUE TITLE
Edit multiple mode doesn't work correctly with subpalette fields

### ISSUE THREAD

**Issue by daniel-nemeth** [contao/core-bundle#946]
Hi!

If you go into the edit multiple mode on tl_page and choose the both fields "Assign a layout" and "Page Layout" there is a strange behaviour when activating the checkbox which reload subpalette fields.

It loads on the same field the checkbox "Assign a layout" a second time directly below the current item.

See the screenshot:
![screen shot 2017-07-10 at 23 09 25](https://user-images.githubusercontent.com/5083254/28040199-51b730da-65c5-11e7-844a-1511266e475a.png)

Thanks for your great job doing with this lovely CMS!

**Comment by leofeyer** [comment]
Fixed in 51cecdcae7ade03a16c1b8557de5886819ec2f4c.
