### ISSUE TITLE
Galerie: Metainformationen werden nicht übernommen

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#947]
Die Metainformationen werden nicht im Inhaltselement _**Galerie**_ übernommen, obwohl diese in der Dateiverwaltung vorhanden sind, und zwar sowohl für den alternativen Text als auch für den Titel. Statt dessen wird einfach der Dateiname übernommen.

Ich habe von 3.5.x auf 4.4. aktualisiert.  

Ich weiß es nicht, ob die Anweisung in der Vorlage _gallery_default_ richtig ist. 

`<?php if ($col->linkTitle) echo ' title="' . $col->linkTitle . '"'; ?>`

**Comment by leofeyer** [comment]
Kann ich nicht reproduzieren.

![](https://user-images.githubusercontent.com/1192057/28060707-4f75a58c-6628-11e7-9fe3-ef62bb16fd03.png)

**Comment by jankout** [comment]
Es tut mir leid, aber das Problem besteht bei mehreren Seiten, die ich von 3.5.x auf 4.4 aktualisiert habe. Siehe Metainformation des Sliders im Quellcode auf http://www.cadus.org/de/projekt/mobiles-krankenhaus Beide Infos sowohl für den alternativen Text als auch für den Titel habe ich ausgefüllt. 


<img width="898" alt="snimek obrazovky 2017-07-12 v 14 52 43" src="https://user-images.githubusercontent.com/3715050/28118647-29c66b24-6712-11e7-85f7-20c9939c085e.png">
<img width="904" alt="snimek obrazovky 2017-07-12 v 12 41 33" src="https://user-images.githubusercontent.com/3715050/28118652-2c2204fa-6712-11e7-8bf9-8b68472777ad.png">

**Comment by fritzmg** [comment]
Ich glaube du solltest das eher im Forum posten.

**Comment by jankout** [comment]
Das habe ich bereits https://community.contao.org/de/showthread.php?67350-4-4-Galerie-Metainformationen-werden-nicht-übernommen&p=445450#post445450
