### ISSUE TITLE
Tschechisch/Tschechien: Korrektes Sprachkürzel

### ISSUE THREAD

**Issue by jankout** [contao/core-bundle#948]
Seit Jahren benutzt Contao das falsche Sprachkürzel für Tschechien. Offiziell wird _**cz**_ benutzt, nicht _cs_. Das heißt, dass das offizielle Kürzel für tschechische Domains _**cz**_ ist. Und für die Metainformationen benutzt man _**lang="cs-CZ"**_. Leider unterscheiden sich hier die Sachen für das Land und für die Sprache. 

Ein gutes Beispiel ist die Seite von Apple [www.apple.cz](http://www.apple.cz). 

Für den Übersetzungsordner kann weiterhin _**cs**_ benutzt werden (das tut auch Apple). Das stimmt schon. 

Es wäre ganz wichtig, das zu korrigieren. Danke.

**Comment by ausi** [comment]
An welcher Stelle in Contao wird das Sprachkürzel falsch verwendet?

**Comment by leofeyer** [comment]
Über das Sprachkürzel entscheiden nicht wir, sondern Transifex.

<img width="643" alt="" src="https://user-images.githubusercontent.com/1192057/28054835-ccb7f796-6616-11e7-888a-029218a33a6c.png">

Am besten meldest Du den Fehler dort: https://www.transifex.com/contact/

**Comment by ausi** [comment]
`cs` ist ja das korrekte Sprachenkürzel für Tschechisch. Wenn ich @jankout richtig verstanden habe wird es aber an irgendeiner Stelle für das Land Tschechien verwendet, nicht für die Sprache.

**Comment by leofeyer** [comment]
> Seit Jahren benutzt Contao das falsche Sprachkürzel für Tschechien.

Es geht um das Sprachkürzel und nicht um das Länderkürzel.

**Comment by fritzmg** [comment]
@jankout das korrekte Sprachkürzel ist `cs`, siehe https://en.m.wikipedia.org/wiki/List_of_ISO_639-1_codes 

Außerdem siehst du ja auch bei Apple, dass `cs` benutzt wird.

Bei zweiteiligen language codes, wie zB `cs-CZ` ist der erste Teil die generelle Spracheinordnung (`cs`) und der zweite Teil eine lokale Sprachvariante oder Dialekt (`CZ`). Beispiele im Deutschen: `de-DE` (Deutsch wie es in Deutschland benutzt wird), `de-AT` (Deutsch wie es in Österreich benutzt wird), `de-CH` (Deutsch wie es in der Schweiz benutzt wird). 

Die Top Level Domain `.cz` hat prinzipiell nichts mit der Sprache zu tun.

**Comment by jankout** [comment]
Ja, allerdings benutzt man für Tschechien CZ, nich CS, genauso wie das Apple macht.

**Comment by leofeyer** [comment]
Also `apple.com/cz` bedeutet "zeig mir die Apple-Webseite **für das Land cz**", wohingegen z.B. `contao.org/de` bedeutet "zeig mir die Contao-Webseite **in der Sprache de**. Es sind zwei ganz unterschiedliche Ansätze, die man nicht vergleichen kann.

**Comment by ausi** [comment]
Außerdem hat Apple ein ganz eigenes System was das betrifft, siehe z. B. `apple.com/chde/`. `chde` ist kein offizielles Sprachen-/Länderkürzel.

**Comment by fritzmg** [comment]
@jankout du hast meinen Kommentar nicht ganz gelesen, denke ich. Für Tschechisch benutzt man `cs` oder `cs-CZ`, je nach dem. Letzteres benutzt Apple. Beides kannst du in Contao verwenden.
