### ISSUE TITLE
Alias-Umschreibung ä zu ae mit setLocale funktioniert nicht mehr

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#954]
Seit Contao 4.4 (managed-edition) funktioniert der bekannte https://github.com/contao/core/issues/8107#issuecomment-314686796 Workaround nicht mehr, in der initconfig das setlocale zu setzen:
```
// Umlaute umschreiben soll ü zu ue machen. Daher setlocale.
setlocale (LC_CTYPE, 'de_DE');
```

Ich erhalte trotzdem einen Umlaut im alias:
![image](https://user-images.githubusercontent.com/2657385/28107787-8663a4ce-66e9-11e7-9fb5-debc2327fd6c.png)

Wie kann ich dem alias sagen, dass ich die Umlaute umgeschrieben haben möchte?

**Comment by Toflar** [comment]
Das wäre schon ziemlich cool, müsste aber imho auf Root-Seiten-Level gemacht werden :)

**Comment by leofeyer** [comment]
Ich möchte das eigentlich nicht wieder einführen, da wir uns darauf geeinigt haben, Unicode in URLs und Dateinamen zu unterstützen. Lässt sich das nicht als Extension umsetzen?

**Comment by Xendiadyon** [comment]
Wenn Unicode-URLs unterstützt werden und problemlos funktionieren und mittlerweile auch nicht mehr urlencoded angezeigt werden, dann finde ich auch nicht, dass wir da einen Rückschritt machen sollten.

Es ging ja anfangs in erster Linie darum, dass ä -> "a" und nicht zu "ae" umgeschrieben wird. Wenn ä jetzt einfach ä bleibt und das im Produktivbetrieb keine Nachteile mit sich bringt, wär das ja super.

**Comment by ausi** [comment]
Unicode in URLs zu unterstützen widerspricht aus meiner Sicht nicht einer sinnvollen Alias-Generierung. Welche Zeichen in den URLs verwendet werden dürfen, sollte pro Installation konfigurierbar sein IMO.

Es spricht aus technischer Sicht auch nichts dagegen Großbuchstaben zu erlauben, wie z. B. Wikipedia.

**Comment by asaage** [comment]
Lustigerweise sind Großbuchstaben schon erlaubt - obwohl bei der Generierung alles klein gemacht wird.
Solang das Alias-Feld alles schluckt, was technisch unterstützt wird und gültig ist bin ich zufrieden. Darüber, was eine sinnvolle Generierung bedeutet wird man sich sicherlich nicht so schnell einig werden fürchte ich.
https://emojipedia.org/emoji/%F0%9F%91%8D/

**Comment by Webstylerin** [comment]
Also ich hätte auch sehr gerne die Möglichkeit die Umlaute wieder wie gewohnt automatisch umschreiben zu lassen, also aus "ö" wird ein "oe". Sehr gerne auch individuell im Startpunkt der Seite konfigurierbar, ob im Core oder mit Erweiterung wäre mir in diesem Falle egal.

Wenn technisch alles glatt laufen würde, könnte ich mich schon an die ungewohnte Schreibweise gewöhnen, aber wenn dann aus der "panflöte" eine "panfl%C3%B6te" wird, bekomm ich die Krise. ;)

**Comment by do-while** [comment]
Seit Jahren erklärt man den Kunden, dass sie, wenn sie selbst einen Alias vergeben, keine Umlaute, Blanks oder sonstige Sonderzeichen eintragen sollten. Jetzt werden einige verwirrt sein und sich fragen, was hat er (in den Fall ich) uns damals da erklärt.

Ist denn wirklich sichergestellt, dass das überall im Internet funktioniert mit Umlauten in der URL?
Uns ist ja nicht geholfen, wenn dadurch bei einigen die Seiten nicht abrufbar sind. Das gilt auch für Abrufe aus dem Ausland, wo ggf. noch ältere Technik im Einsatz ist.

Kompromiss wäre eine Checkbox in den Einstellungen oder in der Startseite. Einstellungen ist sicherlich besser, da dann Contao nicht mal so und mal anders prüfen muss.

**Comment by aschempp** [comment]
> Seit Jahren erklärt man den Kunden, dass sie, wenn sie selbst einen Alias vergeben, keine Umlaute, Blanks oder sonstige Sonderzeichen eintragen sollten.

Jahrelang hat man den Kunden erklärt wie man Schreibmaschinen benutzt. Es waren bestimmt einige verwirrt als es Computer gab. Die Technik ändert sich, die Leute müssen umlernen 😉 


https://www.w3.org/International/articles/idn-and-iri/
> Client-side support for IDN is appears in the recent versions of major browsers, including Internet Explorer 7, Firefox, Mozilla, Netscape, Opera, and Safari. It only works in Internet Explorer 6 if you download a plug-in.

**Comment by Aybee** [comment]
> @Webstylerin aber wenn dann aus der "panflöte" eine "panfl%C3%B6te" wird, bekomm ich die Krise. ;)

Ich auch. Das wird an vielen Stellen (wenn auch nicht direkt in der Adresszeile) unlesbare Dateinamen und URLs erzeugen.

**Comment by m-vo** [comment]
Wo denn zum Beispiel?

**Comment by ausi** [comment]
Wenn man z. B. die URL im Firefox aus der Adresszeile kopiert und in einen Text-Editor einfügt.

**Comment by Aybee** [comment]
In E-Mails.

**Comment by kikmedia** [comment]
... beim Teilen via Twitter ...

**Comment by m-vo** [comment]
So wait, die Emailadresse darf Unicode enthalten, der Body nicht? :-) Und Twitter erlaubt kein Sharen von Unicode-Urls? Ist das wirklich noch ein Problem?

Falls ja, ist ein konfigurierbarer / austauschbarer Service wohl die einzig sinnige Variante.

**Comment by Webstylerin** [comment]
> So wait, die Emailadresse darf Unicode enthalten, der Body nicht? :-)

Heute erst mit Apple Mail testweise eine Mail an eine ß-Domain geschickt. Der Hampel macht nach dem Versenden "ss" draus, so viel dazu.

Schön, dass Leo die Funktion mit 4.5 einführen will, aber was mach ich so lange die 4.4 als LTS aktiv ist? Ich arbeite fast ausschließlich nur mit LTS-Versionen.

**Comment by Xendiadyon** [comment]
Stimmt schon. Wenn ich einen Link https://www.../panfl%C3%B6te/ aus der Adresszeile rauskopiere und per E-Mail verschicke, dann ist das primär mal ziemlich doof. Da wird doch niemand draufklicken, weil alle denken, es wäre Spam ;)

Bei so etwas wäre https://www.../panfloete/ viel schöner.

**Comment by kikmedia** [comment]
> So wait, die Emailadresse darf Unicode enthalten, der Body nicht? :-)

Auch Mailadressen mit Unicode sind eine schlechte Idee angesichts der vielen bescheiden konfigurierten Mailserver auf diesem Globus.

Anyway. So ist es zwar lobenswert aber auch in sehr sehr vielen Fällen unbrauchbar. Configurable, please.

**Comment by ausi** [comment]
Ich hab mal eine kleine Slug-Library dafür gebaut [ausi/slug-generator](https://github.com/ausi/slug-generator), die sollte meiner Meinung nach so funktionieren wie wir das möchten.

Ich kann einen PR für Contao machen der die Library für die Generierung der Aliase verwendet. Bezüglich der Konfiguration, soll es in den Root-Seiten-Einstellungen ein Feld geben dass definiert welche Zeichen erlaubt sind (z. B. `a-z9-0`)? Oder benötigen wir mehr Einstellungsmöglichkeiten?

**Comment by Toflar** [comment]
Die Lib sieht super aus! Danke!!

> Bezüglich der Konfiguration, soll es in den Root-Seiten-Einstellungen ein Feld geben dass definiert welche Zeichen erlaubt sind (z. B. a-z9-0)? Oder benötigen wir mehr Einstellungsmöglichkeiten?

M.M.n. reicht folgendes:

1. Alias-Bearbeitung aktivieren (cbx)
2. Erlaubte Zeichen (textfeld, default `A-Za-z9-0`)
3. Uppercase zu Lowercase konvertieren (cbx, default `true`)

**Comment by ausi** [comment]
> 3. Uppercase zu Lowercase konvertieren (cbx, default `true`)

Diese Einstellung ist gar nicht nötig, das macht die Library automatisch abhängig von den erlaubten Zeiten: `a-z` macht lowercase, `A-Z` macht uppercase und `a-zA-Z` lässt die Groß- und Kleinschreibung unangetastet.

**Comment by ausi** [comment]
Add options: Unicode, Unicode lowercase, ASCII, ASCII lowercase

**Comment by Xendiadyon** [comment]
@ausi Did you think of the News and Events aliases? There should occur the same problem and it should be fixed likewise with your slug-generator?

**Comment by ausi** [comment]
@Xendiadyon Yes, I will make pull requests to news and events too.

**Comment by ausi** [comment]
@leofeyer I think this can be closed in favor of #1016.
