### ISSUE TITLE
Favicon in backend causes usability glitches

### ISSUE THREAD

**Issue by kikmedia** [contao/core-bundle#958]
In https://github.com/contao/core-bundle/commit/b311944ad406dd721a7101cbcb7bc0d5982707c5 a separate icon for the backend was introduced which causes usability glitches.

I am completely fine with an _option_ showing a backend icon, showing love and prideness for Contao, BUT since I often work in multiple backends at the same time, the community forums are open at the same time in browser and still the Contao project page is open more or less generally AND they all use the same icon now, I just find this not only confusing but annoying.

Shouldn't this be configurable?

**Comment by fritzmg** [comment]
I agree, I also get confused now while having the community forums and multiple contao backends open within the same browser window.

**Comment by agoat** [comment]
> Shouldn't this be configurable?

You can simply change the be_main.html5 template (change/delete the favicon link)

Just an idea: Make the contao favicon for the backend without color (a grey icon)?!

**Comment by fritzmg** [comment]
> You can simply change the be_main.html5 template (change/delete the favicon link)

You would have to override the __complete__ `be_main.html5` template just for this one line. A template block could be introduced for the favicon.
```php
  <?php $this->block('favicon'); ?>
    <link rel="icon" type="image/png" href="<?= TL_ASSETS_URL ?>bundles/contaocore/favicon.ico">
  <?php $this->endblock(); ?>
```

> Just an idea: Make the contao favicon for the backend without color (a grey icon)?!

Yeah, I'd like that too - but also make it configurable (either via a setting or via a template block).

**Comment by agoat** [comment]
> You would have to override the complete be_main.html5

Why the 'complete' template? Just the favicon line..

**Comment by fritzmg** [comment]
> Why the 'complete' template? Just the favicon line..

No, you have to override the complete template, because there are no template blocks defined.

**Comment by agoat** [comment]
>  With template blocks your own be_main.html5 template could look like this

Can I extend the same template (name) itself? I know the way to extend the 'block_searchable' a.s.o. but never extended the origin template itself without changing the name.

**Comment by fritzmg** [comment]
Yes, you can do that (but only in the `/templates` folder).

**Comment by agoat** [comment]
You never stop learning..

> This is the recommended way of changing the fe_page template too.

Is there a source for recommendation? 
In general I make a copy (by simply creating a template from `fe_page` in the contao template editor), rename it and make my changes. In the layout I select then the changed `fe_page` template.

**Comment by fritzmg** [comment]
It is inherently recommended ;). If you don't have to override a template completely, you won't miss out on any updates to the parent template.

Another example: if you want to add additional meta tags to the `<head>` in your `fe_page`, then your `fe_page.html5` could look like this:
```php
<?php $this->extend('fe_page'); ?>

<?php $this->block('meta'); ?>
  <?php $this->parent(); ?>
  <meta name="og:type" content="website">
<?php $this->endblock(); ?>
```

**Comment by leofeyer** [comment]
Removed in ad7b624943c4e9c6ce4d8995ef408b51717d264b.

**Comment by agoat** [comment]
> Removed in ad7b624.

Why not using a different favicon?

**Comment by kikmedia** [comment]
> Why not using a different favicon?

Because three backends mean that there will be three lookalike favicons, which is in fact not useful. You should be able to control this behaviour, setting individual icons. After removing the code, you are able to do so by simply placing an icon at root level and putting another icon for the frontend into your layout.

**Comment by agoat** [comment]
> After removing the code, you are able to do so by simply placing an icon at root level and putting another icon for the frontend into your layout.

Ok. I understand. IMO that looks like the easiest way to do. 
A config setting for a backend favicon is somehow too much. Maybe the `be_main.html5` template separeted in blocks will bring some advantage to this.

**Comment by fritzmg** [comment]
It seems this has been reverted to the orange icon in Contao 4.5-beta3. Was this done deliberately?

**Comment by Aybee** [comment]
Why not simply add a favicon.ico to the root? There has to be no code in the HEAD.

A year ago I created a pull request to https://github.com/Ma3xl3/Contao-EasyFavicon. When this will get merged everyone who uses EasyFavicon can easily add the chosen favicon for FE also to the BE by activating a checkbox.

**Comment by leofeyer** [comment]
> It seems the favicon has been re-added Contao 4.5-beta3 (Managed Edition).

What exactly do you mean?

**Comment by fritzmg** [comment]
> @fritzmg What exactly do you mean?

Execute
```
composer create-project contao/managed-edition … 4.5-beta3
```
There will be a `web/favicon.ico` (the orange Contao logo).

It has been added here: https://github.com/contao/manager-bundle/commit/aa4e4e4090362a0116e896236143e14fd5c23db4

**Comment by leofeyer** [comment]
That's fine. The issue in this ticket was a different one.

**Comment by fritzmg** [comment]
Yeah I realize that now. But still, do we want to have this? Now I have to delete it with every new Contao installation. It's only a minor nuissance, but still.

**Comment by fritzmg** [comment]
Deleting the `web/favicon.ico` doesn't work, it's added with every `composer update`.
```
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

 Added/updated the web/app.php file.
 Added/updated the web/app_dev.php file.
 Added/updated the web/favicon.ico file.
```

**Comment by dmolineus** [comment]
If I understand the code right after a first short look, the favicon is only added of none exists. Same for the .htaccess file. So you're forced now to add a custom one of you don't want to see the Contao icon.

**Comment by fritzmg** [comment]
> If I understand the code right after a first short look, the favicon is only added of none exists. Same for the .htaccess file. So you're forced now to add a custom one of you don't want to see the Contao icon.

Yes, that's why I wrote

> Instead, one has to replace it with another favicon.ico.

However, that's still a little annoying. Implementing the favicon isn't usually the first thing that happens during the development of a website - and if you don't do that, then you got the original problem of this ticket.

So if there's got to be a default `favicon.ico`, can it at least be the grey one from https://github.com/contao/core-bundle/pull/963 so that we can distinguish between developing Contao sites and `contao.org` at a glance again?
