### ISSUE TITLE
4.4.1: DCA-Picker doesn't work for Custom Elements

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#959]
https://github.com/contao/core-bundle/issues/886 https://github.com/contao/core-bundle/pull/934
**First:** Thank you for your really fast bugfixing. DCA-Picker for Links does now work.

**Second:** Your bugfix unfortunately destroyed the DCA-Picker for Rocksolid Custom Elements:
![image](https://user-images.githubusercontent.com/2657385/28117905-7964abd0-670f-11e7-804a-c44151467189.png)
![image](https://user-images.githubusercontent.com/2657385/28118029-e0334470-670f-11e7-9e18-a4662857a10b.png)

Teaserbox-Config:
![image](https://user-images.githubusercontent.com/2657385/28118067-032af662-6710-11e7-824d-ae0921f12686.png)

**Comment by leofeyer** [comment]
https://contao.org/en/news/contao-4_4_1.html

**DCA picker**

Unfortunately, the new DCA picker, which has been added in Contao 4.4.0, is still not usable for regular back end users in Contao 4.4.1.

To fix the picker, we have to rework the implementation from scratch (see contao/core-bundle#950), therefore we ask all developers not to publish extensions using the new picker yet. The new implementation cannot be backwards compatible for technical reasons.
