### ISSUE TITLE
"Search on contao.org" nicht übersetzt

### ISSUE THREAD

**Issue by Mynyx** [contao/core-bundle#960]
Im Template ````@ContaoCore/Error/layout.html.twig```` ist oben rechts der Text "Search on contao.org" nicht übersetzt.

**Comment by aschempp** [comment]
I think we should remove the search field completely, it does not make sense anyway.

**Comment by leofeyer** [comment]
Maybe we can add a link to docs.contao.org?

**Comment by Mynyx** [comment]
Ein Link zu docs.contao.org ist für die Besucher einer Website allerdings weniger hilfreich?

Und der Websitebetreiber selbst sollte die Contao-Website ja kennen.

**Comment by leofeyer** [comment]
Removed in 91bec28590f7a9e261282ed052a95115b8cf16a4.
