### ISSUE TITLE
DCA-Picker: Linking Images: Can neither select pages nor files

### ISSUE THREAD

**Issue by Xendiadyon** [contao/core-bundle#965]
I cannot link to pages or files using the new DCA-Picker on Contao 4.4.1.

How to reproduce:
1. Click on DCA-Picker at Image-Link-Address.
![image](https://user-images.githubusercontent.com/2657385/28218497-02d12df8-68b9-11e7-871b-1204db564417.png)
2. There is no Select-Checkbox, we cannot select anything in the Pages-Tab:
![image](https://user-images.githubusercontent.com/2657385/28218603-5763b9d0-68b9-11e7-893e-c9f0a55e30c5.png)

Also, we cannot select any file (regardless if image, pdf, ...)
![image](https://user-images.githubusercontent.com/2657385/28218682-8dd1c84a-68b9-11e7-8f39-8bf3af9dd1b3.png)

The Checkbox (or Radio Button) is missing!
This is the case both with reduced rights and as administrator.

This error was introduced in the Update from Contao 4.4.0 to 4.4.1

**Comment by pandroid** [comment]
Same problem for CE Hyperlink

**Comment by leofeyer** [comment]
The picker does not fully work in Contao 4.4.1 (https://contao.org/en/news/contao-4_4_1.html).
