### ISSUE TITLE
[FR] eigene Checkbox in Umschlagelementen bei "Mehrere Bearbeiten" zur Auswahl 

### ISSUE THREAD

**Issue by zonky2** [contao/core-bundle#968]
eigene Checkbox in Umschlagelementen bei "Mehrere Bearbeiten" zur Auswahl aller Elemente von Umschlag-Anfang bis Umschlag-Ende - leider gibt es hierzu auch keine spezielle Filterung, mit der man sich hier das Leben leichter machen könnte...

**Comment by aschempp** [comment]
Benutz doch einfach die Shift-Taste und Klick das erste und letzte Element an (in Contao 4)? 😎

**Comment by leofeyer** [comment]
Shift-Klick geht auch in Contao 3.5.

https://github.com/contao/core/blob/master/assets/contao/js/core-uncompressed.js#L2146

**Comment by zonky2** [comment]
ahh - o.k.!

THX
