### ISSUE TITLE
Use the Symfony event dispatcher for hooks and callbacks

### ISSUE THREAD

**Issue by importer** [contao/core-bundle#97]
> <a href="https://github.com/leofeyer"><img src="https://avatars.githubusercontent.com/u/1192057?v=3" align="left" width="42" height="42" hspace="10"></img></a> [Issue](https://github.com/contao/contao/issues/19) by @leofeyer
Thursday Aug 14, 2014 at 19:00 GMT

We want to use the Symfony event dispatcher for hooks and callbacks in a backwards compatible manner.

**Comment by leofeyer** [comment]
Closed in favor of #204.
