### ISSUE TITLE
Content element table - I can't shrink increased table sizes

### ISSUE THREAD

**Issue by websolutions-hamburg** [contao/core-bundle#971]
For table content elements exists an increase button. But no option to shrink the table size back.

<img width="525" alt="bildschirmfoto 2017-07-18 um 11 47 31" src="https://user-images.githubusercontent.com/26099903/28311153-045f5a8e-6baf-11e7-85d8-69f5b755551f.png">

**Comment by leofeyer** [comment]
Fixed in f506386455282fae1476b46ce60959d11e5e6806.
