### ISSUE TITLE
Controller::redirect does not work outside of regular pages

### ISSUE THREAD

**Issue by fritzmg** [contao/core-bundle#974]
For example if you have an `initializeSystem` hook which might call `Contao\Controller::redirect` the redirect does not work anymore when `terminal42/header-replay-bundle` is installed in version `1.1.0`.

If you have `terminal42/header-replay-bundle` installed in version `1.0.0` or `1.0.1` everything still works as expected.

Not sure whether the `core-bundle` has to adapt something here or the `header-replay-bundle` has to fix something...

/cc @Toflar

**Comment by Toflar** [comment]
The `header-replay-bundle` just causes this to happen but it is not a bug in the `header-replay-bundle`. It would happen with any piece of code that works with sending multiple requests through the kernel in the same process. The bug is already fixed. See https://github.com/contao/core-bundle/pull/969.

**Comment by fritzmg** [comment]
Cool, thx :)

**Comment by aschempp** [comment]
I think this is not correct. #969 is related to merging HTTP headers, but `Controller::redirect` is (correctly) throwing an exception. This must be another issue…

**Comment by fritzmg** [comment]
To reproduce, just do
```php
\Controller::redirect('https://www.google.com/');
```
within an `initializeSystem` hook and then open the front end. The redirect won't happen when `header-replay-bundle` `1.1.0` is installed.

**Comment by aschempp** [comment]
It's something we need to fix in `header-reply`, we just discussed it over lunch :/

**Comment by fritzmg** [comment]
Ah ok. Should I open a new ticket in `header-replay-bundle`?

**Comment by Toflar** [comment]
Yes please :)

**Comment by fritzmg** [comment]
Ok, see https://github.com/terminal42/header-replay-bundle/issues/2
