### ISSUE TITLE
file picker: no files could be selected, radio/checkbox missing

### ISSUE THREAD

**Issue by stephanbauer** [contao/core-bundle#975]
reproduced in demo.contao.org 4.4.1

in format definitions of a style sheet, it is not possible to chose a background image (jpg/png)

![bildschirmfoto vom 2017-07-20 11-05-37](https://user-images.githubusercontent.com/3224960/28409959-7dd2f0cc-6d3c-11e7-8ef3-5e98c5645a67.png)

**Comment by m-vo** [comment]
see https://github.com/contao/core-bundle/pull/950
