### ISSUE TITLE
Sollte der "getPageLayout"-Hook nicht einen Rückgabewert haben?

### ISSUE THREAD

**Issue by pgerundt** [contao/core-bundle#977]
Macht der "getPageLayout"-Hook (mit dessen Hilfe man doch nachträglich das Layout ändern können sollte) erst dann Sinn, wenn er $objLayout als Rückgabewert erwartet?

PageRegular.php:
```
// HOOK: modify the page or layout object (see #4736)
if (isset($GLOBALS['TL_HOOKS']['getPageLayout']) && is_array($GLOBALS['TL_HOOKS']['getPageLayout']))
{
	foreach ($GLOBALS['TL_HOOKS']['getPageLayout'] as $callback)
	{
		$this->import($callback[0]);
		**$objLayout =** $this->{$callback[0]}->{$callback[1]}($objPage, $objLayout, $this);
	}
}
```

Spricht da irgendwas dagegen?
Ich habe nämlich ohne Rückgabewert keine Idee, wie ich das Layout ändern könnte...

**Comment by Toflar** [comment]
Objekte sind in PHP immer Referenzen. Verändere einfach die Variable.

**Comment by pgerundt** [comment]
Puh, danke. Daran hatte ich nicht gedacht. Was ein "&" alles ausmacht. Danke.
