### ISSUE TITLE
Fehler im FE bei Inserttag {{link::.......}}

### ISSUE THREAD

**Issue by AgentCT** [contao/core-bundle#978]
Bei der Verwendung des Tag {{link::....}} wird dieser im Frontend nicht korrekt aufgelöst. Auf der Contao Demo erhält man neben dem Bild die Anzeige 

> Content Elements" itemprop="contentUrl">

Das sollte aber nicht links neben dem Bild stehen. Offensichtlich wird der Link nicht korrekt aufgelöst.

**Comment by fritzmg** [comment]
Du verwendest den Insert Tag falsch. Dieser erzeugt folgendes Markup:
```html
<a href="<a href="PAGEURL" title="PAGETITLE">
  PAGETITLE
</a>
```
Ich vermute mal du willst eigentlich `{{link_open::*}}` und `{{link_close}}` oder nur `{{link_url::*}}` verwenden. Siehe https://docs.contao.org/books/manual/4.3/en/04-managing-content/insert-tags.html

**Comment by AgentCT** [comment]
Ich wollte diesen Inserttag nehmen:

{{link::*}} | This tag will be replaced with a link to an internal page (replace * with the page ID or alias).

Ich wollte ein Bild mit einem Link versehen, wie auf der Contao Demo gerade noch auf der Startseite zu sehen.

**Comment by fritzmg** [comment]
Ja, wie schon erwähnt ist das der falsche Insert Tag. Du musst `{{link_url::*}}` benutzen. Damit wird nur die URL zu einer Seite erzeugt. Mit `{{link::*}}` wird ein fertiger Link erzeugt.

**Comment by AgentCT** [comment]
okay, dann habe ich die Beschreibung falsch verstanden.
Vielen Dank für die Hilfe.
