### ISSUE TITLE
Interner CSS-Editor: Hintergrundbilder lassen sich nicht auswählen

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#979]
Siehe Onlinedemo.

1. Neues Stylesheet im BE anlegen
2. Neuen Selektor im Stylesheet anlegen
3. Hintergrundbild auswählen

Man landet sofort im Bearbeitungsmodus und nicht im Auswahlmodus des Dateimanagers. Es gibt auch keine Möglichkeit den Modus zu wechseln. In der gelben Spalte sind statt der Auswahlboxen Bearbeitungslinks:

![Image](http://www.schachbund.de/files/contao-forum/bildauswahl.jpg)

**Comment by leofeyer** [comment]
Siehe #965 und #975 sowie https://contao.org/de/news/contao_4-4-1.html.
