### ISSUE TITLE
TinyMCE speichert keinen Text

### ISSUE THREAD

**Issue by Samson1964** [contao/core-bundle#980]
Leicht nachzuvollziehen in der Onlinedemo.
Der TinyMCE speichert bei Textelementen - und wahrscheinlich woanders auch - keinen Text. Nach Klick auf Speichern wird der Text entfernt und Contao meckert, das der Text fehlt. Funktioniert auch nicht beim Umweg über die HTML-Ansicht.

Damit ist Contao im Moment leider für die Bearbeitung von Content untauglich. Gibt es schon einen Hotfix?

**Comment by pandroid** [comment]
Bist du sicher? Ich habe es gerade in der Online-Demo 4.4.1 im Chrome Version 59.0.3071.115 und Mac OS Sierra 10.12.5 getestet. Da hat alles funktioniert.

**Comment by Samson1964** [comment]
Ich habe weiter getestet:
Rechner 1: FF 54.0.1 (32 Bit), Win10 mit KIS - alles i.O.
Rechner 2: FF 54.0.1 (32 Bit), Win8.1 mit Antivir - Fehler
Rechner 2: Chrome 59.0.3071.115 (Offizieller Build) (64-Bit), Win8.1 mit Antivir - alles i.O.
Bei Rechner 2 hat die Deaktivierung der Browser-Überwachung durch Antivir nichts gebracht. Ich starte mal die Kiste neu. Die läuft schon ein paar Tage durch.

**Comment by fiedsch** [comment]
Kann das ebenfalls nicht nachvollziehen (Online-Demo und lokale Installation). Ist also wahrscheinlich ein Windows/Virenscanner-Problem und keines von Contao.

**Comment by Samson1964** [comment]
Sehr seltsam. Nach dem Neustart ist der Spuk vorbei.
