### ISSUE TITLE
Contao 4.4 beta9 - /contao/install was not found on this server

### ISSUE THREAD

**Issue by TiriTM** [contao/core-bundle#985]
I get this error, when I try to install Contao 4.4 on **local environment** (Mac OS X El Capitan 10.11.6 with MAMP) using `contao-manager.phar.php`.

The Installation via the Contao Manager works fine (given that my `/htdocs` folder is totally empty except from the `/web` folder, which is usually not the case as I have to manage several web-projects and indeed this is the very first with Contao 4.4, but that's another topic) but when I click on "Open Installtool" - after the manager installation has finished - I get:

> # Not Found
> The requested URL /contao/install was not found on this server.

And indeed, there's no `/contao` folder in my `/htdocs` and therefore no `/contao/install.php` so I'm totally blocked to complete the Contao 4.4 installation.

I did the following steps:
1. downloaded the `contao-manager.phar` from [contao.org](https://contao.org/de/download.html)
2. copy & paste this file from my Downloads folder to `/Applications/MAMP/htdocs/web`
3. renamed it by adding `.php` so final name was `contao-manager.phar.php`
4. called `http://127.0.0.1/web/contao-manager.phar.php` in my Webbrowser (Google Chrome 59.0.3071.115)
5. select Username and Password
6. click on "Install Contao"
7. Wait for the Installation to be completed (approximately 30 up to 60 Minutes!!!)
8. click on "Open Installtool"
9. pull off my hair because of the error mentioned above

Any help is appreciated.

**Comment by fritzmg** [comment]
> And indeed, there's no /contao folder in my /htdocs

That's normal.  `/contao/install` is a route, not a phyical path.

> Any help is appreciated.

You should ask for help on the community forum for example. The issue tracker is for bug reports etc.

**Comment by TiriTM** [comment]
> That's normal. /contao/install is a route, not a phyical path.
I know it's a route, but there is no contao folder in my htdocs at all and therefore no install.php inside a contao folder.

> You should ask for help on the community forum for example. The issue tracker is for bug reports etc.
and yes, I assume this as a bug, because the manager installation asks me to "Open installtool" which is simply not present anywhere. So this is an **unexpected behavior** that **blocks** me from realizing a customer's project.

**Comment by aschempp** [comment]
> but there is no contao folder in my htdocs at all and therefore no install.php inside a contao folder.

There is no such file **supposed** to be there! This was only the case in Contao 3, but no more in Contao 4.

Your issue is that your webserver points to the root and you're opening the manager in the `web` directory by adding that folder to the URL. You need to change the MAMP configuration to point to the `web` folder. Alternatively, you can open the install tool via `http://127.0.0.1/web/contao/install` but be aware this works only on localhost.

**Comment by fritzmg** [comment]
> I know it's a route, but there is no contao folder in my htdocs at all and therefore no install.php inside a contao folder.

As already said, it's a route, not a physical path. There is no `contao` folder in `web` in Contao 4.

**Comment by TiriTM** [comment]
> Alternatively, you can open the install tool via http://127.0.0.1/web/contao/install but be aware this works only on localhost.
Nope, this doesn't work either, same error message.
