### ISSUE TITLE
Cache für SCSS-Dateien wird bei jedem Seitenaufruf neu erstellt.

### ISSUE THREAD

**Issue by eki89** [contao/core-bundle#987]
Bei der Verwendung von SCSS-Dateien, werden diese bei jedem Seitenaufruf im Frontend neu kompiliert. Dadurch kommt es bei der Verwendung vieler SCSS-Dateien zu einer Verzögerung bei der Auslieferung der Seite.

Verantwortlich für die Kompilierung sind folgende Zeilen in der Combiner.php: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/Combiner.php#L215-L217

An dieser Stelle würde eine Überprüfung, ob sich seit der letzten Kompilierung die SCSS-Quelldatei verändert hat, nicht ausreichen, da innerhalb der SCSS Datei befindliche Imports nicht berücksichtigt werden können.
Vor der Kompilierung müsste also geprüft werden, ob sich eine eingebundene SCSS-Quelldatei, seit der letzten Kompilierung verändert hat, inklusive der darin importierten SCSS-Dateien, um daraufhin sämtliche SCSS Dateien neu zu generieren.

Kombiniert man die Dateien mit Hilfe des im Layout verankerten Flags "skripte zusammenfassen", ist Contao in der Lage die zusammengefasste Dateien gecached abzurufen. Änderungen an den SCSS-Quelldateien führen allerdings nicht zur Neukompilierung der zusammengefassten Cachedatei.

**Comment by agoat** [comment]
> Änderungen an den SCSS-Quelldateien führen allerdings nicht zur Neukompilierung der zusammengefassten Cachedatei.

Das stimmt so nicht. Wenn eine Quelldatei in der Dateiverwaltung gespeichert wird, dann wird gleichzeitig der Skript- und Assets-Ordner geleert. Dadurch werden zwangsweise neue Cache-Dateien beim nächsten Aufruf generiert.

> Bei der Verwendung von SCSS-Dateien, werden diese bei jedem Seitenaufruf im Frontend neu kompiliert. 

Hier sollte tatsächlich die Existenz einer compilierten SCSS-Datei geprüft werden.

**Comment by leofeyer** [comment]
> Vor der Kompilierung müsste also geprüft werden, ob sich eine eingebundene SCSS-Quelldatei, seit der letzten Kompilierung verändert hat, inklusive der darin importierten SCSS-Dateien, um daraufhin sämtliche SCSS Dateien neu zu generieren.

Richtig. Allerdings müssten wir dann irgendwie die Checksummen oder die mtime der Dateien speichern. @contao/developers Wie machen wir das am besten?

**Comment by agoat** [comment]
@leofeyer Warum so aufwendig? Da beim speichern der Quelldateien immer der `assets` Ordner geleert wird, brauchen wir nur - wie bei den zusammen gefügten SCSS-Dateien - auf das Vorhandensein der Datei im `assets` Ordner prüfen.

Ich habe hierzu mal einen PR erstellt (siehe #1004).

**Comment by Aybee** [comment]
Die meisten Entwickler ändern die SCSS-Dateien allerdings nicht im BE, sondern mit ihrem Editor. D.h. eine Prüfung auf Zeit wäre da schon angebracht.

**Comment by agoat** [comment]
Ich muss gestehen, dass der PR das hier erwähnte Problem nicht löst. Er behebt nur den 'Fehler' dass die SCSS-Dateien bei jedem Aufruf kompiliert werden, wenn diese nicht in eine Datei zusammen geführt werden.

> Die meisten Entwickler ändern die SCSS-Dateien allerdings nicht im BE, sondern mit ihrem Editor.

Das stellt natürlich ein Problem dar zu dem mir Ad hoc auch keine Lösung einfällt. 
Das schwierige hier ist, dass die in der Haupt-SCSS-Datei eingebundenen SCSS-Dateien eigentlich erst ermittelt werden müssten, wofür ich aber die Haupt-SCSS-Datei bereits compilieren müsste. Eine Prüfung aller Dateien wäre auch nicht zielführend, da ich Projekte mit weit über 1000 Dateien (Bilder) habe. 

Man könnte höchstens die Prüfung auf den Pfad des Themas und SCSS-Dateien beschränken. Das könnte von der Performance her noch gehen. Dazu wäre es sicher noch sinnvoll, die permanente Prüfung im Layout optional aktivierbar zu machen, da dies ja eigentlich nur bei der Layout-Entwicklung eine Rolle spielt.

**Comment by Aybee** [comment]
Ich hatte mal das umgekehrte Problem (in C3.5), da wurden die CSS-Dateien nicht erneuert nachdem ich meine SCSS bearbeitet hatte. Dazu habe ich mir dann diesen Code in die initconfig.php geschrieben.
```php
/**
 * Delete CSS files in assets/css/ which are older than the newest SCSS file in files
 * @author Andreas Burg <http://andreasburg.de/>
 */
if(TL_MODE == 'FE') // check only in FE
{
  // Only if a BE user is logged in
  if(sha1(session_id().(!Config::get('disableIpCheck') ? Environment::get('ip') : '').'BE_USER_AUTH') == Input::cookie('BE_USER_AUTH'))
  {
    $subFolder = '/contaodemo/theme/scss'; // A subfolder of files/ - e.g. /contaodemo/theme/scss

    // Calculate the newest SCSS file time
    $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(TL_ROOT.'/files'.$subFolder));
    foreach($iterator as $objFile)
    {
      if($objFile->getExtension() == 'scss')
      {
        $lastChange = max($lastChange, $objFile->getCTime());
      }
    }

    // Delete older CSS files in assets/css/
    foreach(glob('assets/css/*.css') as $file)
    {
      if(filectime($file) < $lastChange)
      {
        unlink($file);
      }
    }
  }
}
```
Dabei prüfe ich, ob die CSS in assets älter sind, als die neueste SCSS. Wenn JA, dann lösche ich diese CSS, damit sie neu erstellt werden. Das ganze nur, wenn ich im BE eingeloggt bin und bei einem FE-Aufruf.

Vielleicht könnte dieser Code so ein Ansatz in die Richtung sein.

**Comment by ausi** [comment]
Sollte es nicht so sein, dass während ich als Entwickler an den SCSS-Dateien arbeite ich auch den Cache deaktiviere bzw. im Debug-Mode arbeite? Im Live-Betrieb sollte dann immer der Cache verwendet werden sofern vorhanden.

**Comment by aschempp** [comment]
Totally agree with @ausi

**Comment by Aybee** [comment]
Wie es für **mich** sein sollte kann ich kurz sagen: Wenn ein Kunde anruft der ein kleines CSS-Problem hat, dann will ich die Datei mit meinem Editor vom Server öffnen ändern und speichern. Ins BE will ich da nicht unbedingt. Und **wenn** ich ins BE muss, dann will ich da nicht unbedingt irgendwo einen Cache ausschalten, oder einen Debug-Mode einschalten. Ich möchte da im FE dann auch nicht unbedingt ein zusätzliches Debug-HTML-Markup vor mir haben. Eigentlich möchte ich die Seite so sehen, wie sie veröffentlicht wird.

CSS-Dateien werden ja auch nicht wirklich gecacht, oder? Die liegen halt in assets/css/ und werden ins FE eingebunden. Dass sie neu erstellt werden müssen, wenn ich die Quellen dieser Dateien verändere versteht sich ja von selbst. Wenn ich mich dazu im BE einloggen muss, ok - aber dann da auch noch extra was einstellen möchte ich nicht. Contao sieht ja, dass ich im BE bin, oder?

So, das ist meine Wunschvorstellung bezgl. CSS (SCSS) und JS in Contao 4.

In Contao 3.5 läuft da irgendwas ganz quer im Moment, aber das gehört ja nicht hierhin. Da ich erst versuchsweise mit SCSS arbeite, reicht mir das im Moment auch. Habe im Moment nicht die Zeit eine Versuchsreihe durchzuspielen um zu prüfen, wann CSS Dateien erstellt werden und wann nicht. Das sind so viele Parameter, die ich durchtesten müsste.

- Eingeloggt, nicht eingeloggt
- "interner Cache" an/aus
- Seitencachezeit ein/aus (bei C4 Server/Client)
- Einstellungen-Cache-Modus: Server/Browser/'Server u. Browser'/keiner
- Externe CSS
- 'TL_CSS' CSS
- Externe SCSS
- 'TL_CSS' SCSS

Da wäre es einfach, wenn irgendwo beschrieben wäre, was ich einstellen müsste, damit ich CSS(o. SCSS)-Dateien bearbeiten kann. Das könnte man dann leicht testen, ob es funktioniert. Aber eins ist ja klar, man möchte nicht für jede Änderung irgendeinen Cache löschen. Und wenn man dann im BE erst irgendwelche Einstellungen betätigen muss, wenn man an seinen CSS-Dateien arbeiten möchte, dann wäre das für mich auch unbefriedigend.

**Comment by leofeyer** [comment]
Ich habe einen PR dazu erstellt (siehe #1010).

**Comment by agoat** [comment]
@ausi Wie kann der CSS-Cache im assets-Verzeichnis deaktiviert werden? Ich kenne dafür keine Einstellung. Auch im Debug-Modus (app_dev.php) wird kein Cache deaktiviert (die Dateien werden nur nicht zusammengefügt, aber SCSS-Dateien müssen immer noch kompiliert werden).

**Comment by ausi** [comment]
@agoat Ich habe beschrieben wie ich mir den richtigen workflow vorstelle, ich selbst nutze den SCSS-Compiler von Contao nicht. Falls es keine Option gibt den CSS/SCSS-Cache zu deaktivieren/leeren, sollten wir diese eventuell hinzufügen.

**Comment by agoat** [comment]
> Falls es keine Option gibt den CSS/SCSS-Cache zu deaktivieren/leeren, sollten wir diese eventuell hinzufügen.

Habe ich [hier](https://github.com/contao/core-bundle/pull/1010#issuecomment-320970044) vorgeschlagen, statt den Zeitstempel der SCSS-Dateien bei jedem Aufruf zu prüfen.

**Comment by Toflar** [comment]
Softwarearchitektonisch richtig wäre meiner Meinung nach ein Cache mit Cache Tagging.
Als Tag würde ich jeweils einen sha1 Hash des Pfades nehmen, aber zur vereinfachten Darstellung nehmen wir hier einfach direkt den Dateinamen (der ja bereits unique ist, ich würde nur deshalb einen Hash wählen, weil der sicher kompatibler ist als Tag).

Beispiel:

* grid.scss
* main.scss (importiert grid.scss)
* home.scss (importiert main.scss)

Im Layout binden wir "home.scss" ein.
Sprich wir haben "home.scss -> main.scss -> grid.scss".

Wir sammeln jetzt rekursiv von "home.scss" alle referenzierten Dateien und taggen unterwegs mit den "parents".
Also "home.css" kriegt keinen Tag, weil es direkt im Seitenlayout includiert ist. "main.css" kriegt das Tag "home.scss". "grid.scss" kriegt die Tags "home.scss" und "main.scss".

Jetzt gehen wir alle 3 Dateien durch und prüfen ob sie geändert wurden (nur im dev Modus, nie in Produktion). Wenn sie geändert wurden, aktualisieren wir die Datei und **invalidieren die dazugehörigen Tags**. D.h. wenn nur "grid.scss" verändert wurde, werden die Tags "home.scss" und "main.scss" invalidiert. Somit ist deren Cache geleert und wird beim nächsten Aufruf neu generiert. Wir müssten uns also noch merken ob irgend eine Datei sich verändert hat und solange dem so ist, nochmal bei "home.scss" anfangen.

Die Symfony Cache Komponente kann Tagging 😄

**Comment by fenepedia** [comment]
Wenn ich aktuelle eine SCSS-Datei für mein CSS nutze und das von Contao kompilieren lasse, dann muss ich zwingend bei jeder Änderung den CSS-Cache leeren, außer ich verwende app_dev.php. Ist das korrekt oder gibt es da nun schon eine Option, CSS-Cache deaktivieren?

**Comment by fkaminski** [comment]
Habe dies hierzu gefunden:
https://github.com/ErdmannFreunde/theme-toolbox

> When enabling "Bypass script cache" in the Contao Maintenance settings, the SCSS files do not get cached in production mode.
