### ISSUE TITLE
Convert value to integer when applying date() in DC_Table

### ISSUE THREAD

**Issue by m-vo** [contao/core-bundle#988]
There are several places in ``DC_Table`` where PHP's ``date()`` function is used either directly or through ``\Date::parse()``. This function produces a warning if anything else than an integer is passed as the second parameter. 

The code for [sorting mode flags 5 to 10](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/drivers/DC_Table.php#L5993-L6019) produces an error in the BE when using fixed field sorting (mode 1) with a field that is no integer (like for example ``start``/``stop`` in ``tl_article``*):

> Warning: date() expects parameter 2 to be integer, string given

Wrapping the values in ``intval()`` or casting to ``int`` solves the problem. 

----
*) OT: Why aren't these columns ``int`` in the first place?

**Comment by asaage** [comment]
>*) OT: Why aren't these columns int in the first place?

related:
- https://github.com/contao/core/issues/5850
- https://github.com/contao/core/issues/8593#issuecomment-268387809
- https://github.com/contao/core/issues/5591

**Comment by leofeyer** [comment]
How do I reproduce this in the back end?

**Comment by leofeyer** [comment]
I wasn't able to reproduce this. I tried it as described above:

```php
// tl_article.php
…
	'list' => array
	(
		'sorting' => array
		(
			'mode'                    => 1,
			'fields'                  => array('start'),
…
```

**Comment by m-vo** [comment]
It turns out the problem lies somewhere else: 

The column I was sorting by can be set by the user via the date picker widget (compare to ``start/stop`` in ``tl_article``). In one of my datasets there was an entry post 2038-01-19 which as a number exceeds ``PHP_INT_SIZE`` on a 32-bit PHP environment. This is where the implicit cast fails.

Therefore wrapping the value in ``intval()`` or casting did not produce the right output (but at least prevented an exception on 32-bit environments):

```php
$date = ‌2717535600; // ‌2056-02

echo PHP_INT_MAX; // ‌2147483647
echo intval($value) == $value; // false
echo date('Y-m', $value) // wrobecause $value is treated as float
‌‌echo date('Y-m', intval($value))‌ // 2038-01

```

Here is a working alternative:

```php
echo \DateTime::createFromFormat(
    'U', $value, new \DateTimeZone(date_default_timezone_get())
)->format("Y-m"); // ‌2056-02
```

**Comment by m-vo** [comment]
@leofeyer Could we change this (see code above) or do you see any drawbacks? 

(Btw.: Seems that on Windows 64bit PHP is kind of a problem so there this issue is likely to show up.)

**Comment by leofeyer** [comment]
@contao/developers What do you think?

**Comment by Toflar** [comment]
I have no idea at all. I just know we should stop working with timestamps, that's all 😄  If it works just the same and has no drawbacks, I'm fine with the change but I honestly don't know. So please not in a maintenance release anyway.

**Comment by discordier** [comment]
Above code should work correctly but...

- ... as noted by @Toflar, not in a maintenance release and secondly, we should change to real date fields.
- ... I wonder if we really need to support 32bit servers - I have not seen any in the wild for the past 10 years or so. Therefore I am tempted to mark this as won't fix.

**Comment by aschempp** [comment]
There are tons of 32bit servers according to what I see with the Contao Manager. Also, our database INT fields are 32bit, not sure if that applies here. Anyway, correct date fields are the way to go.

Unfortunately, the mentioned code will not work as expected. According to the manual, [a timezone is ignored for timestamp values](http://php.net/manual/en/datetime.createfromformat.php). That means our timestamps are in the local timezone, but `DateTime` will read them as UTC …

**Comment by m-vo** [comment]
I think you could probably set the timezone afterwards with ``$obj->setTimezone(...)``.
http://php.net/manual/en/datetime.settimezone.php

**Comment by aschempp** [comment]
Shouldn't that re-calculate the date/time then?

**Comment by m-vo** [comment]
Yes, I think so. Isn't that what we would want if our 'timestamps' were not timezone independent? (But are they in the first place?)

Of course date fields really are the way to go on a long term. But that will probably introduce lots of BC breaks even if we add a compat layer where possible. Think of extensions that access the DB directly... Would this be something suitable for a minor version change or C5?
