### ISSUE TITLE
Modal window buttons still disabled for non-picker modals

### ISSUE THREAD

**Issue by Toflar** [contao/core-bundle#990]
It was actually part of @aschempp's picker PR (see https://github.com/contao/core-bundle/pull/950/commits/9a5181e08fd71adcd03018a34c8e4fc951caf315). There must have gone something wrong when you merged that branch into master. Can you please verify if there is other stuff missing?

**Comment by leofeyer** [comment]
Fixed in 8217678841c757cb4d6412206df2452449338f05. I have changed the order of the two conditions, because IMO `$$('.tl_tree_checkbox,.tl_tree_radio').length > 0` takes longer to evaluate than `document.location.search.test('act=select')`.
