### ISSUE TITLE
Checkboxen und Radio-Buttons nebeneinander statt untereinander

### ISSUE THREAD

**Issue by madi84** [contao/core-bundle#991]
Beim Formulargenerator werden in Rohdaten-Mails die Checkboxen und Radio-Buttons nebeneinander statt untereinader dargestellt.

Text-Feld 1: Wert 1
Text-Feld 2: Wert 2
Radio-Feld 1: Auswahl 1 Radio-Feld 2: Auswahl 2 Radio-Feld 3: Auswahl 3 ...
Text-Feld 3: Wert 3

**Comment by leofeyer** [comment]
Ich konnte das Problem nicht reproduzieren. Ich habe zwei Radio-Button-Menüs und ein Checkbox-Menü untereinander angelegt und mir die Rohdaten per E-Mail schicken lassen:

```
Salutation: mrs
Name: Theo Test
E-Mail: theo@test.de
Radio1: option_5
Radio2: option_6
Checkbox: option_2, option_3
Your Message:
```
