### ISSUE TITLE
Update components/plugins

### ISSUE THREAD

**Issue by xchs** [contao/core-bundle#993]
I've just updated to Contao 4.4.2.

Running `$ composer outdated` shows a list of outdated packages:
```
contao-components/dropzone                4.3.0     5.0.1     DropZone integration for Contao Open Source CMS
contao-components/highlight               8.9.1     9.12.0    Highlight.js integration for Contao Open Source CMS
contao-components/jquery                  1.12.4    3.2.1     jQuery integration for Contao Open Source CMS
imagine/imagine                           v0.6.3    v0.7.1    Image processing for PHP 5.3
league/uri                                4.2.2     5.0.0     URI manipulation library
swiftmailer/swiftmailer                   v5.4.8    v6.0.1    Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle                    v2.12.1   v3.1.0    Symfony MonologBundle
symfony/swiftmailer-bundle                v2.6.3    v3.0.3    Symfony SwiftmailerBundle
twig/twig                                 v1.34.4   v2.4.3    Twig, the flexible, fast, and secure template language for PHP
```

Can we maybe require newer versions of some of the listed components/plugins? I'm aware that some of the plugins cannot yet be raised to a newer version due to compatibility issues.

**Comment by leofeyer** [comment]
Your interpretation of the `composer outdated` result is wrong. Of course there is jQuery 3.2.1 but we are currently using jQuery 1.12 in Contao. And of course there is SwiftMailer 6, but it is only compatible with PHP 7, therefore we are currently using version 5 in Contao.

You should use `composer update --dry-run` instead to find updatable packages.

**Comment by xchs** [comment]
> Of course there is jQuery 3.2.1 but we are currently using jQuery 1.12 in Contao. And of course there is SwiftMailer 6, but it is only compatible with PHP 7, therefore we are currently using version 5 in Contao.

Yes, I knew that. That's why I wrote:
> I'm aware that some of the plugins cannot yet be raised to a newer version due to compatibility issues.

What about other libraries listed above, e.g. `dropzone`, `highlight`, `imagine`, `uri` ? Can we raise the version number for this?

**Comment by leofeyer** [comment]
Yes, major version updates are possible in the next feature release.

**Comment by leofeyer** [comment]
Updated in 90840d35f75ab980c923eb9c81065b266aa15a05.

**Comment by m-vo** [comment]
...regarding `league/uri`:

Why do we now require a version >5? If [the possible BC breaks](https://github.com/thephpleague/uri/blob/master/docs/upgrading/5.0.md) did not affect us, couldn't we be ok with v4 *or* 5? Unfortunately this conflicts with other packages that still require v4...

**Comment by leofeyer** [comment]
> If the possible BC breaks did not affect us

They did affect us.

**Comment by m-vo** [comment]
I see.
