### ISSUE TITLE
Contao 4.4.2 Bundle / Tabellen werden von Installertool nicht erkannt

### ISSUE THREAD

**Issue by flo1stof8** [contao/core-bundle#996]
Hallo,
ich versuche aktuell meine eigene Contao Erweiterung zu erstellen, scheitere hier allerdings schon in einem relativ frühen Stadium, da die von mir unter dem Pfad src/ContaoBundle/Resources/contao/dca/tl_cars.php erstellte Tabelle vom Installertool nicht erkannt wird da die Datenbanken laut ihm aktuell sind. 
Ich habe bereits gelesen dass es bei der Version 4.4.1 Probleme mit dem DCA-Picker gab, diese sollten aber doch bei der 4.4.2 gelöst sein?
Hat jemand ähnliche Tipps, bzw. das gleiche Problem und kann mir weiter helfen?

**Comment by aschempp** [comment]
Ich vermute mal du hast den Cache nicht geleert?

**Comment by flo1stof8** [comment]
Doch, Browser sowie Contao Cache ist komplett geleert.

**Comment by fritzmg** [comment]
May be related to https://github.com/contao/installation-bundle/issues/63

**Comment by flo1stof8** [comment]
Vielleicht sollte ich dazu erwähnen nach was ich genau vorgehe: https://xuad.net/artikel/contao-4-bundle-plugin-erstellen-backend-und-frontend
Evtl. ist diese Vorgehensweise ja schon überholt oder ähnliches?

**Comment by leofeyer** [comment]
Am besten wendest Du Dich mit solchen Fragen ans [Forum](https://community.contao.org/de/). Falls sich dort herausstellt, dass das Problem von einem Fehler in Contao verursacht wird, kannst Du diesen hier melden.
