### ISSUE TITLE
Wizard class is removed

### ISSUE THREAD

**Issue by dmolineus** [contao/core-bundle#997]
Before Contao 4.4.2 it was possible to set the `wizard` class manually using `tl_class` in the dca config. Useful if a custom backend widget provides always uses a widget.

The current implementation introduced with https://github.com/contao/core-bundle/commit/874076de55cbf962fd5e41c00e853e4dec8842a#diff-b187da7f3bf59a72fc3327dbb0246dd4R536 removes the wizard class if no custom wizard is added.

Furthermore it's would custom classes containing `wizard`, e.g. `wizard-2x`

**Comment by leofeyer** [comment]
@aschempp /cc

**Comment by aschempp** [comment]
> Useful if a custom backend widget provides always uses a widget.

What do you mean by that? Can you give an example?

**Comment by aschempp** [comment]
🤔 if your widget always adds a wizard, it should also always add the wizard class? Not in the template, but in the widget attributes?

Btw, you should probably update your composer.json. [Support section](https://github.com/netzmacht/contao-leaflet-geocode-widget/blob/master/composer.json#L20) looks wrong and a `contao-bundle` does not require the composer plugin 😉

**Comment by dmolineus** [comment]
> 🤔 if your widget always adds a wizard, it should also always add the wizard class? Not in the template, but in the widget attributes?

It depends on user configuration which class should be added. Often it's wizard, sometimes `wizard-2x` or `wizard-3x` if some custom wizards are added. 

In general there shouldn't be any magic changes to the classes which are applied manually in the dca settings. Maybe you could introduce a new css class instead which wasn't available in the previous releases to not break this beheaviour in an bugfix release.

> Btw, you should probably update your composer.json. Support section looks wrong and a contao-bundle does not require the composer plugin 😉

😮 Thanks.

**Comment by leofeyer** [comment]
@aschempp Can't we simply remove the `str_replace()` call? It will not hurt if the `wizard` class is added twice, will it?

**Comment by Toflar** [comment]
Completely untested but you get the point: https://github.com/contao/core-bundle/pull/1011

**Comment by leofeyer** [comment]
See #1011 then.
